### ISSUE TITLE
Restoring dump with system collections fails with non-root user

### ISSUE THREAD

**Issue by Simran-B** [arangodb/arangodb#13014] opened 2020-11-10 11:13 UTC
_Reported by Rico in Community Slack_

## My Environment

* __ArangoDB Version__:        3.7.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

arangorestore

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Create dump with `--include-system-collections`
2. Create user with _Administrate_ permission for the respective collections (including system collections)
3. Restore dump with `--include-system-collections` and `--server.username <user>` (do not use `root`)

__Problem__:
At specific collection, the process is terminated with `error: connect() failed with #61 - Connection refused`.
After many trials, turned out the problem happens if `--include-system-collections true` with `--server.username` other than root is used. Unclear whether this is a bug or feature.

__Expected result__:
Be able to restore dumps equally with `root` and `<user>` given that the latter has the necessary permissions.

**Comment by Simran-B** [comment] 2020-11-12 11:58
Asked for additional information:
>Can you clarify what the deployment type and operating system is?
>Was the non-root user created before you took the dump, i.e. is it included in the dump's _users collection?
>Also, is this in the default _system database or one that you created?

**Comment by maxkernbach** [comment] 2020-12-02 15:56
Closing - could not reproduce the issue and no further information was provided by the user.

**Comment by goldsky** [comment] 2020-12-30 06:55
I am very sorry for the delayed response.
I didn't aware of the slack's notification.
This happened on cloud environment with arangodb 3.7.2-1 - community edition:
* 1 agent
* 2 coordinator
* 2 db

You may try this:
1. Database was created by root
2. arangorestore by other user (with "Administrate" permission)

**Comment by Simran-B** [comment] 2021-04-20 06:53
If there is a crash involved here, then it could be related or #14021

**Comment by jsteemann** [comment] 2021-04-20 07:47
Potentially fixed via https://github.com/arangodb/arangodb/pull/14023

**Comment by jsteemann** [comment] 2021-04-23 06:47
Should be fixed in 3.7.11.

**Comment by maxkernbach** [comment] 2021-05-10 09:36
Hi @goldsky,

Version 3.7.11 including a fix has been released.

Could you please let us know whether the issue is resolved?

**Closed** 2021-06-02 14:36 UTC
Labels: 1 Analyzing, 2 Cannot Reproduce, 2 Fixed, 3 ImportExport, Waiting User Reply
