### ISSUE TITLE
Foxx Unit Test call via UI/PostMan Gets stuck and CPU is stuck at >50% with each call

### ISSUE THREAD

**Issue by dashdeep13** [arangodb/arangodb#3890] opened 2017-12-04 18:05 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [X] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [X] Single-Server

Storage-Engine:
- [X] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [X] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:   chrome  running on this OS: Mac OSX
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1. I have a single test file that contains 240 tests all same, arangodb version 3.2.5 as:
 describe('Verify JWT ', function () {
        it('When Signed with a wrong secret(secret) ', function () {
            assert('true', 'worked');
        });
       it('When Signed with a wrong secret(secret) ', function () {
            assert('true', 'worked');
        });
  .
  .
  .
  });
2. Replacing the Foxx service in Prod mode, and then clicking the UI test button or calling the test endpoint, the test execution does not complete.
3.  From the UI the status report does not show up after clicking the test button and endpoint calls don't return data. Also I see the arangod utilization to 50+%.
4. Calling the same endpoint again results in the same and now the cpu is 100+% (the cpu usage is incremental with each execution).
5. This DOES not occur for a cluster mode of operation.

**Comment by pluma** [comment] 2017-12-05 15:54
Thanks for reporting this problem. The observed behaviour seems to be a duplicate of the existing issue #1946. I'm closing this issue as a duplicate but feel free to reopen the issue if you think it is unrelated.

**Closed by pluma** 2017-12-05 15:54 UTC
Labels: 3 Foxx
