### ISSUE TITLE
ArangoDB 3.2alpha4 Many web-interface issues

### ISSUE THREAD

**Issue by DeShadow** [arangodb/arangodb#2457] opened 2017-04-26 15:01 UTC
**ArangoDB 3.2alpha4**

I met some web issues.

1. Collection tab 'Info' has not info for any collection.

2. Collection tab 'Settings' has empty fields 'Journal size' and 'Index buckets'. Info buttons don't show popup infos.

3. Click on button to change database always redirects to login form with message 'You do not have permission to a database.'

**Comment by jsteemann** [comment] 2017-04-26 15:33
@DeShadow : Did you use the default configuration or have you adjusted the storage engine?

**Comment by DeShadow** [comment] 2017-04-26 15:40
@jsteemann I use RocksDB engine.
Collections were created from my script with arangojs.

**Comment by frankmayer** [comment] 2017-04-26 15:46
@jsteemann I can confirm the third point but not points one and two. 
Seems that 1. and 2. have a different cause than 3.

My scenario was an upgrade from a previous 3.2 alpha (don't remember which one, I think it was 3.2a2 or a3)
Using Default configuration. (mmfiles)


BTW, what level of granularity is there for choosing a storage engine and where does this happen in the GUI? Couldn't find any docs on this, besides the help of `arangod`

**Comment by DeShadow** [comment] 2017-04-26 15:50
@frankmayer https://www.arangodb.com/download-technical-preview/

The alpha4 features
– pluggable storage engine: RocksDB

If you want to test ArangoDB with the new RocksDB engine, use the following:

– stop the currently running ArangoDB server
– create a new directory, for example /tmp/rocksdb
– start arangodb --server.storage-engine=rocksdb /tmp/rocksdb

**Comment by jsteemann** [comment] 2017-04-26 15:57
@frankmayer: we're currently writing the docs for setting up the storage engine.
The granularity for selecting the storage engine is per server. That means it's not as in MySQL, where the storage engine can be different per table.

**Comment by frankmayer** [comment] 2017-04-26 16:03
@DeShadow I definitely want to test it! ;) Thanks for the detailed info.
@jsteemann Also thanks for the info. Are there any plans in making it possible to define that per Database or Collection? (Not that I expect it to be, but flexibility comes to mind ;) )

**Comment by jsteemann** [comment] 2017-04-26 16:07
@frankmayer: we initially thought about making the setting per collection or per database, but this would have caused too many issues.
For example, if it's per collection, then we would need to have written all changes to our WAL (to keep writes to multiple different storage engines crash-safe and consistent) and also to the storage engine. RocksDB has its own WAL however, so this would have meant lots of unnecessary writes even in the general case even if only a single storage engine is used. 
Crash recovery is also much more complicated when there are multiple sources of truth and the global WAL and the engines have different versions of the data. 
So we decided against it for simplicity and performance.

**Comment by frankmayer** [comment] 2017-04-26 16:20
@jsteemann thanks for the clarification. :+1:

**Comment by hkernbach** [comment] 2017-04-26 17:18
Thanks for the report. ( 1 ) , ( 2 ) and ( 3 ) fixed.

**Comment by DeShadow** [comment] 2017-04-26 18:00
@hkernbach Thanks! :) When will the changes be?

**Comment by jsteemann** [comment] 2017-04-27 07:04
@DeShadow : they will become available with the next 3.2 release (which will probably be the beta). It is expect to be released within the next two weeks.
It may become available earlier via a nightly build though.

**Comment by khamin** [comment] 2017-05-02 12:26
Just got `You do not have permission to a database.`
on [3.2.dev nightly 2017-05-02](https://www.arangodb.com/repositories/nightly/xUbuntu_16.04/amd64/arangodb3-3.2.devel-1_amd64.deb)

**Comment by hkernbach** [comment] 2017-05-02 13:07
We apologize for any inconvenience. Sadly the frontend part is currently not part of the nightly builds. I've just added the frontent build manually d856a33f3a8a1b91cbb3054bffe9c6ffb99091d2 to the repo. So the code changes/fixes will appear in the next nightly build.

**Comment by khamin** [comment] 2017-05-02 13:09
@hkernbach Thanks!

**Comment by dothebart** [comment] 2017-06-20 09:33
Since 3.2 Beta1 containing this fix is available, I will close this now.

**Closed by dothebart** 2017-06-20 09:33 UTC
Labels: 1 Bug, 2 Fixed, 3 Front-End
