### ISSUE TITLE
Arango freezes

### ISSUE THREAD

**Issue by tthil** [arangodb/arangodb#1912] opened 2016-06-30 07:45 UTC
Hi,

When I develop Foxx applications in Arango the environment freezes and the only way to get out of it is to hard boot the computer. Any suggestions on where I should start to have look on whats the reason for this behaviour? Any logs, etc?

//Thomas

**Comment by dothebart** [comment] 2016-06-30 08:37
Can you give a little more details on your operating system etc?
You should always be able to terminate ArangoDB forcefully regardless whether OS you use - no reboot required.

**Comment by tthil** [comment] 2016-06-30 10:50
Mac OS El Capitan Version 10.11.5, Arango 2.8

All windows freezes and the only way to get it back is to switch of the machine.

//Thomas

**Comment by dothebart** [comment] 2016-06-30 11:47
if you run `top` in another window and reproduce the incident - do you see ArangoDB starting to use lots of resources? Or is the machine instantly dead including mouse cursor etc? In that case I would rather think that it may be a deffective disk?

**Comment by jsteemann** [comment] 2016-06-30 12:27
The most interesting thing to look at will be the resource usage & availability. For example, if all RAM is used by the running processes (including ArangoDB), the system will start swapping, do a lot of disk I/O and may get really slow. Is there any utility for Mac to monitor resource usage and (ideally) record it so figures are available after a restart?

**Comment by dothebart** [comment] 2016-07-14 10:57
@tthil is this still relevant? Or could we close this?

**Comment by dothebart** [comment] 2016-08-18 09:34
I'm closing this because of inactivity. If you think that the problem hasn't been solved or that there is anything missing, feel free to re-open the issue.

**Closed by dothebart** 2016-08-18 09:34 UTC
