### ISSUE TITLE
Add "ignore-collection" option to the arangodump command

### ISSUE THREAD

**Issue by AntoineAA** [arangodb/arangodb#16346] opened 2022-05-30 10:11 UTC
## My Environment

* __ArangoDB Version__:        3.9.0
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:    systemd
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:         256GB
* __Disks in use__:         SSD
* __Used Package__:              Ubuntu .deb

## Component, Query & Data

__Affected feature__:
arangodump

__AQL query (if applicable)__:

__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:
1.7TB

__Replication Factor & Number of Shards (Cluster only)__:

__Problem__:
It would be useful to add an "ignore-collection" option to dump the whole database except a few collections.
We use a CRON to do the dump, and we would have to update it each time we add a new collection.
We just need to exclude 1/27 collections.

__Expected result__:

**Comment by Zyqsempai** [comment] 2023-02-28 15:20
Hey @AntoineAA,
Thanks a lot for sharing with us this idea, our Product Team currently reviewing your request, we will circle back with an update in the next few weeks.
Best.

**Comment by matcho** [comment] 2023-03-02 09:37
Duplicate of #12712 btw ?

**Comment by hkernbach** [comment] 2023-10-24 15:06
Status update here: Feature is in the development process. Still needs to pass CI's and Reviews, but will then be merged soon.

**Comment by matcho** [comment] 2024-04-15 12:21
Works in 3.12

**Comment by dothebart** [comment] 2024-05-14 10:06
closing Since 3.12.0.2 is available for download.

**Closed by dothebart** 2024-05-14 10:06 UTC
Labels: 1 Feature, 3 ImportExport
