### ISSUE TITLE
Browsing collection shows some documents without _key

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#1952] opened 2016-07-21 04:44 UTC
Dear Team,

  We are running aragnodb 3.0 in RHEL 6. We noticed one thing while browsing the collection.

Some of the documents are there with out _key. And when I clicked on that, its not opening.

So can I know the reason behind this. Also wanted to know what is meant by dead and alive objects.

Regards,
Sajeev

**Comment by jsteemann** [comment] 2016-07-21 06:25
@sajeevpr : this has the same root cause as https://github.com/arangodb/arangodb/issues/1949
For documents with more than a certain number of attributes (IIRC the limit is 20) the _key attribute is neither queried not shown by the web interface, so it's not clickable there. The documents actually have the _key attribute, it's just a query in the web interface that does not fetch it when there are many attributes. I fixed that query yesterday, and the fix will be provided in 3.0.4.

**Comment by jsteemann** [comment] 2016-08-02 14:31
Fixed in 3.0.4, which was released today.

**Closed by jsteemann** 2016-08-02 14:31 UTC
