### ISSUE TITLE
Error message: 'Unable to connect

### ISSUE THREAD

**Issue by 24865p** [arangodb/arangodb#11660] opened 2020-05-20 11:32 UTC
## My Environment

* __ArangoDB Version__:        ArangoDB 3.6.3-1
* __Storage Engine__:             RocksDB6.2.0
* __Deployment Mode__:        Cluster
* __Deployment Strategy__:   Manual Start 
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        Centos8
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              rpm

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. I installed arangodb on 3 centos8 servers. I have to cluster them, but there are many errors.
2. Also, I hope you can easily explain how to cluster these three servers.
3. 

__Problem__:
The first error was 
ARANGODB_DEFAULT_ROOT_PASSWORD=6625 arango-secure-installation
2020-05-20T11:28:08Z [8765] INFO [a1c60] {syscall} file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2020-05-20T11:28:09Z [8765] ERROR [4ec19] {startup} startup aborted: caught exception during start of feature 'Upgrade': collection or view not found: _users. shutting down
2020-05-20T11:28:10Z [8765] ERROR [5d508] arangod terminated because of an exception: startup aborted: caught exception during start of feature 'Upgrade': collection or view not found: _users

Using other methods, the error occurred.

[root@localhost ~]# /usr/sbin/arango-secure-installation
Please enter a new password for the ArangoDB root user: 
Repeat password: 
2020-05-20T11:24:22Z [8578] INFO [a1c60] {syscall} file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2020-05-20T11:24:23Z [8578] ERROR [4ec19] {startup} startup aborted: caught exception during start of feature 'Upgrade': collection or view not found: _users. shutting down
2020-05-20T11:24:23Z [8578] ERROR [5d508] arangod terminated because of an exception: startup aborted: caught exception during start of feature 'Upgrade': collection or view not found: _users

[root@localhost ~]# arangosh
Please specify a password: 

                                       _     
  __ _ _ __ __ _ _ __   __ _  ___  ___| |__  
 / _` | '__/ _` | '_ \ / _` |/ _ \/ __| '_ \ 
| (_| | | | (_| | | | | (_| | (_) \__ \ | | |
 \__,_|_|  \__,_|_| |_|\__, |\___/|___/_| |_|
                       |___/                 

arangosh (ArangoDB 3.6.3-1 enterprise [linux] 64bit, using jemalloc, build tags/v3.6.3.1-0-g76b2e00b64-dirty, VPack 0.1.33, RocksDB 6.2.0, ICU 58.1, V8 7.1.302.28, OpenSSL 1.1.1g  21 Apr 2020)
Copyright (c) ArangoDB GmbH

Command-line history will be persisted when the shell is exited. You can use `--console.history false` to turn this off
Could not connect to endpoint 'tcp://203.255.92.193:8529', database: '_system', username: 'root'
Error message: 'Unable to connect'

203.255.92.193:8529@_system>

__Expected result__:

**Comment by Simran-B** [comment] 2020-05-27 10:45
Hi @24865p,

how did you install ArangoDB? Was a random root password set during the process, and did you invoke arango-secure-installation manually to set a different one? Did you start `arangod` before that at least once? Was a new database directory created or do you want to upgrade one from a previous version?

**Comment by Simran-B** [comment] 2020-06-03 10:28
Hi @24865p,
can you provide us some more details so that we can help?

**Comment by Simran-B** [comment] 2020-06-24 12:52
I tried the followings:
```
docker run -it centos:8

curl https://download.arangodb.com/arangodb36/Community/Linux/arangodb3-3.6.4-1.0.x86_64.rpm -o arangodb3-3.6.4-1.0.x86_64.rpm
yum localinstall arangodb3-3.6.4-1.0.x86_64.rpm
ARANGODB_DEFAULT_ROOT_PASSWORD=6625 arango-secure-installation
```

Setting the password interactively by starting `arango-secure-installation` also resulted in:

```
INFO [95cab] Password changed.
INFO [7da27] {startup} server will now shut down due to upgrade, database initialization or admin restoration.
```

Same with `rpm -ivh arangodb3-3.6.4-1.0.x86_64.rpm` and 3.6.4-1.

Going from 3.4.9 to 3.6.3 raised the following error on `arango-secure-installation`:
```
Database directory version (30409) is lower than current version (30603).
```

Starting the command with `--database.auto-upgrade` and changing the password then worked fine.

**Comment by Simran-B** [comment] 2020-07-01 10:10
Hey @24865p,
we can't reproduce the problem and would require more information about how you upgraded the deployment or whether this was a fresh database directory. Closing this ticket for now, but feel free to re-open with additional information.

**Closed by Simran-B** 2020-07-01 10:10 UTC
Labels: 1 Analyzing, 3 Cluster, 3 UserManagement, Waiting User Reply
