### ISSUE TITLE
Search view not being updated with new items added to collections in 3.5 RC7

### ISSUE THREAD

**Issue by davechallis** [arangodb/arangodb#9765] opened 2019-08-20 11:40 UTC
## My Environment

* __ArangoDB Version__:        3.5 RC7
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter in Docker
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        64Gb
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__:

Search views

__Problem__:

I've got a custom search view with a custom analyzer defined, which has been running ok for around a week.

As of today, I noticed that new items I added to some collections weren't being returned in searches on that view, and looking at the logs, found several warnings that looked related:

    WARN: /work/ArangoDB/3rdParty/iresearch/core/index/index_writer.cpp:1598 Failed to finish consolidation id='140525993122928' for segment '_397', found only '1' out of '2' candidates
    2019-08-20T11:12:50Z [1] WARNING [bce4f] {arangosearch} error while consolidating arangosearch link '37580641': 4 failure while executing consolidation policy '{\n  "type" : "tier",\n  "segmentsBytesFloor" : 2097152,\n  "segmentsBytesMax" : 5368709120,\n "segmentsMax" : 10,\n  "segmentsMin" : 1,\n  "minScore" : 0\n}' on arangosearch link '37580641' run id '140525993123831'

(and the same warning repeated several times)

In case it's useful, the search view is defined with:

```
{
  "writebufferIdle": 64,
  "writebufferActive": 0,
  "type": "arangosearch",
  "primarySort": [],
  "writebufferSizeMax": 33554432,
  "commitIntervalMsec": 1000,
  "consolidationPolicy": {
    "type": "tier",
    "segmentsBytesFloor": 2097152,
    "segmentsBytesMax": 5368709120,
    "segmentsMax": 10,
    "segmentsMin": 1,
    "minScore": 0
  },
  "globallyUniqueId": "hF34C50DDF48B/23525305",
  "cleanupIntervalStep": 2,
  "id": "23525305",
  "links": {
    "assignee": {
      "analyzers": [
        "identity"
      ],
      "fields": {
        "name": {
          "analyzers": [
            "noStemmingAnalyzer"
          ]
        }
      },
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    },
    "organisation": {
      "analyzers": [
        "identity"
      ],
      "fields": {
        "name": {
          "analyzers": [
            "noStemmingAnalyzer"
          ]
        }
      },
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    }
  },
  "consolidationIntervalMsec": 10000
}
```

The "noStemmingAnalyzer" is identical to the "text_en" analyzer, but with stemming disabled.

**Comment by Dronplane** [comment] 2019-08-20 13:26
Hi, @davechallis!
Thanks for reporting this issue.
Looks like this problem is already addressed by https://github.com/arangodb/arangodb/issues/9612

**Comment by maxkernbach** [comment] 2019-08-20 13:59
@davechallis 

Closing this issue as "Duplicate" since it has already been reported in https://github.com/arangodb/arangodb/issues/9612.

A fix for this bug will be available in versions 3.4.8 and 3.5.1. We will inform you in the linked issue once these versions have been released. In case this problem persists using the stated versions, please let us know.

Thanks again for reporting!

**Closed by maxkernbach** 2019-08-20 13:59 UTC

**Comment by Darkheir** [comment] 2019-12-03 11:36
I see the following issue in `3.5.3`:

```
WARNING [bce4f] {arangosearch} error while consolidating arangosearch link '15040296': 4 caught exception while executing consolidation policy '{\n  "type" : "tier",\n  "segmentsBytesFloor" : 2097152,\n  "segmentsBytesMax" : 5368709120,\n  "segmentsMax" : 10,\n  "segmentsMin" : 1,\n  "minScore" : 0\n}' on arangosearch link '15040296' run id '140080272846839': while beginning doc_ in postings_writer, error: docs out of order '129867' < '573915'
```

**Comment by rocketraman** [comment] 2019-12-03 13:30
Also seeing various errors with Arangosearch and 3.5.3:

```
arangodb-db-1 arangodb 2019-12-03T13:13:26.581090858Z WARN: /work/ArangoDB/3rdParty/iresearch/core/index/index_writer.cpp:1611 Failed to finish consolidation id='140505610398784' for segment '_149', found only '1' out of '2' candidates
arangodb-db-1 arangodb 2019-12-03T13:13:26.581196859Z 2019-12-03T13:13:26Z [1] WARNING [bce4f] {arangosearch} error while consolidating arangosearch link '178250584': 4 failure while executing consolidation policy '{\n  "type" : "tier",\n  "segmentsBytesFloor" : 2097152,\n  "segmentsBytesMax" : 5368709120,\n  "segmentsMax" : 10,\n  "segmentsMin" : 1,\n  "minScore" : 0\n}' on arangosearch link '178250584' run id '140505610399735'
arangodb-db-1 arangodb 2019-12-03T13:24:36.504685181Z WARN: /work/ArangoDB/3rdParty/iresearch/core/index/index_writer.cpp:1611 Failed to finish consolidation id='140505610398784' for segment '_158', found only '0' out of '2' candidates
arangodb-db-1 arangodb 2019-12-03T13:24:36.5144437Z 2019-12-03T13:24:36Z [1] WARNING [bce4f] {arangosearch} error while consolidating arangosearch link '178250584': 4 failure while executing consolidation policy '{\n  "type" : "tier",\n  "segmentsBytesFloor" : 2097152,\n  "segmentsBytesMax" : 5368709120,\n  "segmentsMax" : 10,\n  "segmentsMin" : 1,\n  "minScore" : 0\n}' on arangosearch link '178250584' run id '140505610399735'
```

**Comment by Dronplane** [comment] 2019-12-03 13:47
Hi, @rocketraman ! This warning is expected. This basically means ArangoSearch segments choosen for consolidation were updated  while consolidation thread was  building new consolidated segment, so this consolidation iteration was aborted and will be another consolidation pass in future.

**Comment by Dronplane** [comment] 2019-12-03 13:49
Hi @Darkheir ! Thank you for reporting! Is it possible to share a dataset and more details about use case leading to this failures so we could investgate?

**Comment by Darkheir** [comment] 2019-12-03 14:19
Hi, thank you for your answer. 

We will try to reproduce it with a smaller dataset, because the error is occurring in production with millions of records.

**Comment by Darkheir** [comment] 2019-12-03 14:32
Actually the errors is happening on all the environments (local, test, prod) on all the views no matter the collection(s) it references...

**Comment by Dronplane** [comment] 2019-12-03 14:45
Could you please share at least view definitions?  Although sample dataset would be a great help.

**Comment by Darkheir** [comment] 2019-12-03 14:56
Here's one of the definitions:

```
{
  "writebufferIdle": 64,
  "writebufferActive": 0,
  "type": "arangosearch",
  "primarySort": [],
  "writebufferSizeMax": 33554432,
  "commitIntervalMsec": 1000,
  "consolidationPolicy": {
    "type": "tier",
    "segmentsBytesFloor": 2097152,
    "segmentsBytesMax": 5368709120,
    "segmentsMax": 10,
    "segmentsMin": 1,
    "minScore": 0
  },
  "globallyUniqueId": "h87D0183B3976/607836628",
  "cleanupIntervalStep": 2,
  "id": "607836628",
  "links": {
    "my_coll": {
      "analyzers": [
        "identity"
      ],
      "fields": {
        "_key": {},
        "last_address": {},
        "first_address": {}
      },
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    }
  },
  "consolidationIntervalMsec": 10000
}
```

It seems that changing the consolidation policy to `bytes_accum` solves the issue (or at least the error disappears).

I don't understand why the policy is set to `tier` because in the documentation it states that `bytes_accum` is the default and we didn't modify it...

**Comment by Dronplane** [comment] 2019-12-03 15:06
Thanks for the view definition. Could you please give some details about use case? Are you doing data import into collection? Inserts? Deletions? Or just reading without dataset changes?

**Comment by Darkheir** [comment] 2019-12-03 15:56
The errors are happening without any read or write. Periodically (every 10 seconds) the error is thrown. I think it is because of the `consolidationIntervalMsec` set to `10 000`.

**Comment by Dronplane** [comment] 2019-12-03 16:04
Could you please share full index folder ? This folder could be found in path like <Your-database-dir>/databases/database-1/arangosearch_<link number>

**Comment by Darkheir** [comment] 2019-12-03 16:32
The data we store is a bit sensitive and I can't share it with you.

I will try to create a dataset reproducing the issue and I will share with you both the dataset and the index.
