### ISSUE TITLE
Arango DB crashes

### ISSUE THREAD

**Issue by jcdutton** [arangodb/arangodb#6937] opened 2018-10-16 21:49 UTC
## My Environment

* __ArangoDB Version__:        INFO ArangoDB 3.3.14 [linux] 64bit, using jemalloc, build tags/v3.3.14-0-g377be26, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2k-fips  26 Jan 2017
>
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:              cluster
* __Infrastructure__:              own
* __Operating System__:       CentOS 7.5
* __Used Package__:             CentOS package

## Component, Query & Data

__Affected feature__:
Arango DB graph query

__AQL query (if applicable)__:
TODO

__AQL explain (if applicable)__:

TODO

__Dataset__:

TODO

__Replication Factor & Number of Shards (Cluster only)__:

TODO

## Steps to reproduce

1. Run graph query
2. Crashes due to out of memory (best guess of the reason for the crash).
3. 

__Problem__:
dmesg output when it crashes:
[1009649.241557] traps: V8 WorkerThread[21883] trap invalid opcode ip:1c5a40e sp:7f824f6481a0 error:0 in arangod[400000+2444000]
When this happens, no more queries can be submitted for about 10 seconds.

__Expected result__:
Either complete query, or returns error.

**Comment by maxkernbach** [comment] 2018-10-22 16:42
Hi @jcdutton,

could you please share some further information so that we can investigate this issue? 

1. The graph query that lead to the crash.
2. Number of agents, coordinators and dbservers.
3. Replication factor and number of shards for the involved collections.
4. The structure of your graph collections or optimally a small dataset to reproduce the crash.
5. Logs of agents, coordinators and dbservers.

Thanks

**Comment by dothebart** [comment] 2018-10-26 12:37
Hi @jcdutton,
please use the latest available verison, 3.3.19 as of yesterday. 
Please also have a look at memory usage and the number of used filedescriptors.

**Comment by mpoeter** [comment] 2018-10-28 18:05
What strikes me is the error "invalid opcode". If you still get the same error with 3.3.19, could you create a crash dump?

**Comment by SaulDoesCode** [comment] 2018-11-05 15:53
Was running 3.3.17 for a whole while, and it was stable more or less then last night with no log or anything it just crashed. Only thing different with this one is that I had stats turned off, so no dashboard.

I wiped the server, (just a small testing app, no heavy writes [at most logging server requests every 15 seconds] or anything), and started fresh with the latest docker preview version 3.4 RC4, and since it started the memory was just leaking and its memory usage just kept growing. It seems just now, a half hour or so ago it finally crashed.

Running a single instance of the latest 3.4 docker preview version, this is the only command, nothing custom about it except what you see here.
```bash
docker run -p 8529:8529 -p 8530:8530 -d --name rango -v /var/arango:/var/lib/arango3 -v /etc/letsencrypt:/etc/letsencrypt -e ARANGO_ROOT_PASSWORD=XXXXX -e ARANGO_STORAGE_ENGINE=rocksdb arangodb/arangodb-preview:3.4 arangod --server.endpoint ssl://[::]:8530 --server.authentication true --ssl.keyfile /etc/letsencrypt/live/grimstack.io/server.key --ssl.session-cache true
```

![ArangoDB memory leak and crash](https://i.imgur.com/pZest1v.png)

if the image loads, you should see the initial memory drop from 4am this morning when the 3.3.17 instance died, and then again a steep slope followed by a drop off from when the new instance 3.4 died earlier today.

I don't know what caused it, since it was a fresh install and all I've been pushing is minimal logs, and some other documents, from a highly work in progress project, the source code of which you may inspect at your leisure [here](https://github.com/SaulDoesCode/anend), it was using the ``go-driver``.

**Comment by SaulDoesCode** [comment] 2018-11-06 07:35
The same setup as described above, crashed again this morning after having restarted the container last afternoon. Is there a way to force ``server.threads`` to be lower on single core systems, even if it is a preview build?

**Comment by dothebart** [comment] 2018-11-14 14:36
Hi, 
can you also try the memory setting mentioned here: https://github.com/arangodb/arangodb/issues/5579#issuecomment-437367671

**Comment by SaulDoesCode** [comment] 2018-11-14 15:01
Hi, Thanks 👍. I saw the post a while back and things have been pretty stable since, with ``vm.overcommit_memory`` set to 0.

**Comment by dothebart** [comment] 2018-11-14 15:10
Ok, so I think we can close this issue now..

**Closed by dothebart** 2018-11-14 15:10 UTC
Labels: 1 Analyzing, 3 Cluster, Waiting User Reply
