### ISSUE TITLE
More flexible API documentation integration

### ISSUE THREAD

**Issue by pluma** [arangodb/arangodb#1327] opened 2015-05-06 12:05 UTC
Via #1290:

Currently the API documentation is part of the admin frontend using a modified version of Swagger 1. There is now a standalone Foxx app for per-app documentation that uses Swagger 2.

It would be neat if documentation could be mounted on a per-app level similar to the standalone version but maybe (optionally) guarded by app-specific authentication mechanism.

@razvanphp Could you describe your specific use case and the requirements for access control? I may be overthinking this, but I'm not sure whether we can develop a one-size-fits-all approach that improves upon the existing solution (other than using Swagger 2 instead of Swagger 1).

**Comment by razvanphp** [comment] 2015-05-06 12:21
The use case is pretty general I think, in my company, I presented the documentation for a foxx app I wrote in the admin frontend to other teams (the ones that are supposed to use those endpoints) and of course the logical question was where can they consult this documentation. At this point, I realised I cannot provide them with access because this would mean I have to give them auth credentials for my whole database.

Your idea with a "documentation" method to the controller seems very good to me, and would solve this use case. I would imagine that in any foxx app, you can specify the documentation endpoint, that is mounted on a configurable URL. This way, each app can have it's own basic auth in "before" method, and the documentation is protected with the same password, or even not protected at all. When the "Try me!" functionality is used, it will ask for basic auth anyway.

I don't really get the last statement, but I would use the same swagger version, so that the documentation looks the same, regardless of what method is used to expose it: i.e. the same `swagger.json`. For example, if the foxx app exposes the documentation, you would include it as an iframe inside the admin, instead of the internal one, or the other way around, you expose the internal one in a way that is accessible also from outside.

**Comment by pluma** [comment] 2015-05-06 12:34
My biggest concern is handling the assets required by Swagger. The documentation is really made up of three parts: 1. the static page itself, 2. the endpoint producing the JSON for swagger, 3. additional assets like stylesheets and frontend code.

I could imagine something like this:

Add a method `documentation` to the Foxx.Controller that takes a URL and a function (like the `destroySession` method). The URL is then used as the base URL of the documentation routes, e.g. if the URL is `/my/docs` the URL `/my/docs` serves the HTML, `/my/docs/swagger.json` serves the JSON for swagger and `/my/docs/assets/swagger.js` and so on serve the assets. Every request touching any of those routes first goes through the function, which can implement authentication or something fancy like that.

I'm not entirely sure where we would store the common assets, yet, (because normally they would reside in the relevant Foxx app) but that can likely be solved.

**Comment by razvanphp** [comment] 2015-05-06 12:38
Making the documentation an integrated system app that is used both internally and externally would solve your problem with the assets?

**Comment by pluma** [comment] 2015-05-06 12:58
We could have the assets reside at a central location (e.g. `/_admin/docs/`), but then they would no longer be in the path of your app (e.g. `/my-app/`), which impacts the use case where you only want to use a reverse proxy to expose a single Foxx app (e.g. treat all incoming request paths as relative to `/my-app/` so `www.example.com/api/foo` becomes `localhost:8529/_db/_system/my-app/foo`).

There's no way to "export" assets of a Foxx app so other Foxx apps can use them yet, either. I.e. there's no way to have one Foxx app serve another Foxx app's assets under its own base URL.

**Comment by pluma** [comment] 2015-05-06 13:12
I had a chat with Jan and I think this could work. We could store the common assets in aardvark and just `fs.read` them from there internally. The only problem would be if for some reason you don't have the admin frontend app installed but if you go around deleting system apps, you're already asking for trouble.

So the plan would be as follows:

* add a `documentation` method to the Controller as above
* replace Swagger in aardvark with Swagger 2.0
* serve the appropriate HTML at the documentation base route (first argument to `documentation`)
* serve the app's swagger JSON at the appropriate sub-route (e.g. `swagger.json`)
* serve the appropriate assets for all requests relative to the documentation base route (via `fs.read`)
* for all requests relative to the documentation base route apply the `before` function passed to the `documentation` method, if any.

**Comment by razvanphp** [comment] 2015-05-06 13:19
Sounds great. Just a funny question, is the documentation URL going to be in the `swagger.json` ? something like inception :)

Swagger 2 must be tweaked a little bit, for example it has a remote validator that does not work for private, interval URLs.

**Comment by pluma** [comment] 2015-05-06 14:30
I think the documentation endpoint itself may end up in swagger.json, but not the individual sub-routes (like swagger.json itself).

**Comment by pluma** [comment] 2015-05-07 08:16
`controller.apiDocumentation(path, beforeFn)` has landed in devel and works as planned.

@razvanphp you can try the feature in the devel branch. Basically it works as described (`path` will be interpreted as a directory, so no trailing `*` wildcard suffix is needed, e.g. `/my/dox` or `/my/dox/` both work). If you don't want the route to be resolved as normally, you can return `false` from your `beforeFn`. The path relative to the endpoint is in `req.suffix` as an array (as with any wildcard suffix match).

I'll leave this ticket open for now as there's still some adjustments to be done (e.g. documenting the feature properly).

**Comment by razvanphp** [comment] 2015-05-07 10:14
Sorry but why do we need another before function? I thought the `controller.before` is applied too?

**Comment by pluma** [comment] 2015-05-07 10:37
@razvanphp you can use `controller.before`. The additional `beforeFn` is just there so you can add custom logic specifically to that sub-path (analogous to `destroySession` and so on). It's entirely optional and just a convenience.

**Comment by pluma** [comment] 2015-05-07 13:31
Fixed in devel.

**Comment by razvanphp** [comment] 2015-05-28 10:25
I installed today 2.6.0a2, and the documentation in web admin does not seem to work out of the box, i.e. without specifying `controller.apiDocumentation`. The error in the iFrame is:
````json
{
    "error": true,
    "code": 404,
    "errorNum": 404,
    "errorMessage": "unknown path '/_admin/aardvark/foxxes/docs/index.html?mount=%2Fsorter-api'"
}
````

**Comment by razvanphp** [comment] 2015-05-28 11:25
Also, I know it might be too late, but maybe not, given the fact that we are in alpha stage, I think this configuration should probably go into the `manifest.json`. 

For me, it's strange to define it a controller, because for example I have 4 controllers. So in which one should I put it? And it does not make so much sense there anyway, since the mount point of the documentation is application wise, not a subroute of the controller mount point.

The `opts` can be defined there as well, except maybe for the `before` function that has arguable use cases anyway.

**Comment by pluma** [comment] 2015-05-28 12:27
I think there's a misunderstanding. The documentation shown by aardvark (the web admin) is generated by the aardvark app, not the app that is documented. I'm not sure why this is resulting in a 404 error in the iframe for you, but @jsteemann is reporting the same. I'll have to try and reproduce that problem locally.

The `apiDocumentation` method is *only* necessary if you want to mount the documentation yourself (e.g. if you want to make it available to other users who don't have access to the web admin). You can use this in any controller you want, you can even use it to mount another app's documentation in your own app. This lets you provide your own access controls and so on.

Without having the documentation mounted in a controller, there's no way to apply any access controls (i.e. there's no way to have a `controller.before` apply to it or being able to pass in a `before` function, which is how you can customize the assets and API data like the web admin does).

**Comment by pluma** [comment] 2015-05-28 12:58
I'm reopening this issue until the error can no longer be reproduced.

@jsteemann suggested it might have to do with the online validator, but it never tried to access the online validator on my machine. This is extremely strange.

**Comment by razvanphp** [comment] 2015-05-28 13:41
I understood, I just said that now I can't see the documentation at all, not within the admin and also not with the new `apiDocumentation` method.

Maybe it has something to do with the upgrade? I installed the alpha version from the unstable repo and I had to run `/etc/init.d/arangodb upgrade`

Other things:
- documentation for `aardvark` or any other system app does not work as well
- `aardvark/foxxes/docu/{mount}` works
- `aardvark/foxxes/billboard?mount={mount}` works as well (donno what this is)
- `foxxes.js` seems to have your last changes, but `indexFile: 'index-alt.html'` seems strange to me, because my iFrame tries to load `index.html` as you can see from the error.

**Comment by pluma** [comment] 2015-05-28 14:27
Interesting. It seems as if the web admin app did not get updated. @fceller any idea how that could happen?

The `index.html` is correct. The `index-alt.html` in the config only specifies that a different file should be returned when the index.html route is requested. The route name doesn't change.

The bug @jsteemann reported appears to be different: the online validator is invoked automagically if it doesn't recognize the route as running on localhost. That needs to be manually circumvented, apparently. I'll see how I can fix that.

**Comment by fceller** [comment] 2015-05-28 14:29
@pluma did you find a way to reproduce this?

**Comment by pluma** [comment] 2015-05-28 14:36
Okay, I've fixed the error @jsteemann reported.

@fceller no, I can't find any way to reproduce the issue @razvanphp is reporting. But the only reason I can imagine why the aardvark swagger routes would result in a 404 for *every* mount point is that the mounted version of aardvark is not the same as the version of aardvark in devel. Can you conceive of any situation in which that could happen when upgrading from an earlier version of ArangoDB?

**Comment by fceller** [comment] 2015-05-28 14:40
@pluma I will try to install 2.5.4 and then 2.6.0 on my machine

**Comment by razvanphp** [comment] 2015-05-28 14:40
![screen shot 2015-05-28 at 16 38 35](https://cloud.githubusercontent.com/assets/4599319/7862740/222bf6a4-0558-11e5-9e99-ae21573969bc.png)

This is how it looks, the same in my foxx app. Since there is no minor version in aardvark, I cannot know what exact version is there, but I can look into the code on the server; where to look for the changes?

**Comment by pluma** [comment] 2015-05-28 15:05
@razvanphp For the sanity check, just open the foxxes.js in which you found the indexFile setting and before the line "`controller.apiDocumentation('/docs', function (req, res) {`" (i.e. in line 378 or so), add the following:

`require('console').log('*****Using new aardvark*****');`

then restart ArangoDB and check the console output of the server when you open the web admin.

If you *don't* see the log output you added, something's very fishy. If you *do* see the log output but the problem persists, something's even fishier.

**Comment by razvanphp** [comment] 2015-05-28 15:48
Got it:
````
2015-05-28T17:42:33 [4748] INFO ArangoDB (version 2.6.0-alpha2 [linux]) is ready for business. Have fun!
2015-05-28T17:48:09 [4748] INFO *****Using new aardvark*****
````

**Comment by razvanphp** [comment] 2015-05-29 10:06
So I checked `js/server/modules/org/arangodb/foxx/controller.js` and `js/apps/system/_admin/aardvark/APP/foxxes.js` files that I have, and they seem identical with the devel branch, at least the documentation part.

I added the `console.log` that you suggested <i>after</i> `controller.apiDocumentation('/docs'..` just before the return, and the log appears when I try to access the documentation URL, and not when I access the web admin.

The only thing that might be different is the swagger parts, can you point me to the right commit / files that I can check for differences?

I would also be happy with a new build, or instructions how to compile and install the devel version given that I have the repo stuff in the VM.

**Comment by razvanphp** [comment] 2015-05-29 11:10
Ok, I think I found the reason:
````bash
root@aboutyou:/usr/share/arangodb/js/server/assets/swagger# ls -alh
total 192K
drwxr-xr-x 3 root root 4.0K May 29 12:47 .
drwxr-xr-x 3 root root 4.0K May 28 11:29 ..
drwxr-xr-x 3 root root 4.0K May 28 11:29 lib
-rw-r--r-- 1 root root 108K May 20 18:55 swagger-ui.js
-rw-r--r-- 1 root root  63K May 20 18:55 swagger-ui.min.js
root@aboutyou:/usr/share/arangodb/js/server/assets/swagger#
````

So the files are really not in the package, I checked it with `dpkg-query -L arangodb |grep swagger` the error is thrown in `swagger.js` after `swaggerPath()` is called.

Another problem seems to be that the default opts are not there, when you have a before function just with return true, for example the `swagger.json` path throws:
````
ERROR Error in foxx route '{ "match" : "/categories/dada/*", "methods" : [ "get" ] }': '[ArangoError 3009: App not found at: undefined]', Stacktrace: [ArangoError 3009: App not found at: undefined]
ERROR   at lookupApp (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/manager.js:233:11)
ERROR   at Object.routes (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/manager.js:268:13)
ERROR   at swaggerJson (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/swagger.js:106:26)
ERROR   at /usr/share/arangodb/js/server/modules/org/arangodb/foxx/swagger.js:76:9
ERROR   at Object.res.action.callback (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/internals.js:101:5)
ERROR   at /usr/share/arangodb/js/server/modules/org/arangodb/foxx/routing.js:324:19
ERROR   at execute (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1318:7)
ERROR   at next (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1335:7)
ERROR   at [object Object]:386:5
ERROR   at execute (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1318:7)
ERROR   at routeRequest (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1339:3)
ERROR   at foxxRouting (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1092:7)
ERROR   at execute (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1318:7)
ERROR   at Object.routeRequest (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1339:3)
ERROR   at Function.actions.defineHttp.callback (/usr/share/arangodb/js/actions/api-system.js:58:15)
ERROR
INFO /test-api, outgoing response with status 500 of type application/json, body length: 59
````

this is because `result` ends up being exactly what is returned from before function, and not defaults merged with this object. Maybe some validation here would be good.

**Comment by pluma** [comment] 2015-05-29 14:02
@fceller could you check why the swagger files aren't in the packages?

@razvanphp The default return value should be `undefined`, not `true`.

**Comment by fceller** [comment] 2015-05-29 14:30
Strange:

The centos 7 package contains:

/usr/share/arangodb/js/server/assets/swagger/swagger-ui.js
/usr/share/arangodb/js/server/assets/swagger/swagger-ui.min.js

the debian 8 package:

./usr/share/arangodb/js/server/assets/swagger/swagger-ui.js
./usr/share/arangodb/js/server/assets/swagger/swagger-ui.min.js

**Comment by fceller** [comment] 2015-05-29 14:30
@razvanphp which package did you use?

**Comment by fceller** [comment] 2015-05-29 14:49
I have installed 2.5.4 and then 2.6.0a2:

root@germany:/home/jenkins/arangodb_repository/unstable/Debian_8.0/amd64# ls -l /usr/share/arangodb/js/server/assets/swagger
total 184
drwxr-xr-x 3 root root   4096 May 29 16:36 lib
-rw-r--r-- 1 root root 110176 May 20 16:57 swagger-ui.js
-rw-r--r-- 1 root root  63560 May 20 16:57 swagger-ui.min.js
 
I have no idea we it is missing.

**Comment by razvanphp** [comment] 2015-05-29 15:45
I used the apt repository `https://www.arangodb.com/repositories/unstable/Debian_7.0/` and then installed with `apt-get install arangodb=2.6.0a2` over the previous 2.5.4 install.

So can you reproduce this?

**Comment by fceller** [comment] 2015-05-29 16:18
I will try a Debian 7 system

**Comment by razvanphp** [comment] 2015-05-29 16:37
But you already see the problem in Debian 8 too, it should be more than the two js files and the lib folder.

i.e.
````
root@aboutyou:/usr/share/arangodb/js/server/assets/swagger# ls -al
total 220
drwxr-xr-x 6 root root   4096 May 29 15:59 .
drwxr-xr-x 3 root root   4096 May 28 11:29 ..
drwxr-xr-x 2 root root   4096 May 29 14:24 css
drwxr-xr-x 2 root root   4096 May 29 14:24 fonts
drwxr-xr-x 2 root root   4096 May 29 14:24 images
-rw-r--r-- 1 root root   3150 May 29 15:54 index-alt.html
-rw-r--r-- 1 root root   3292 May 29 15:53 index.html
drwxr-xr-x 3 root root   4096 May 29 14:24 lib
-rw-r--r-- 1 root root    595 May 29 14:24 LICENSE
-rw-r--r-- 1 root root    449 May 29 14:24 o2c.html
-rw-r--r-- 1 root root 110176 May 29 14:24 swagger-ui.js
-rw-r--r-- 1 root root  63560 May 29 14:24 swagger-ui.min.js
root@aboutyou:/usr/share/arangodb/js/server/assets/swagger#
````

**Comment by fceller** [comment] 2015-05-29 16:38
@pluma 
Using razvan packages I ended up with

root@6e88f3b5dfda:/tmp# dpkg-query -L arangodb |grep swagger
/usr/share/arangodb/js/server/modules/org/arangodb/foxx/swagger.js
/usr/share/arangodb/js/server/modules/org/arangodb/foxx/swaggerDocs.js
/usr/share/arangodb/js/server/assets/swagger
/usr/share/arangodb/js/server/assets/swagger/swagger-ui.js
/usr/share/arangodb/js/server/assets/swagger/swagger-ui.min.js
/usr/share/arangodb/js/server/assets/swagger/lib
/usr/share/arangodb/js/server/assets/swagger/lib/jquery.ba-bbq.min.js
/usr/share/arangodb/js/server/assets/swagger/lib/underscore-min.js
/usr/share/arangodb/js/server/assets/swagger/lib/handlebars-2.0.0.js
/usr/share/arangodb/js/server/assets/swagger/lib/jquery-1.8.0.min.js
/usr/share/arangodb/js/server/assets/swagger/lib/swagger-client.js
/usr/share/arangodb/js/server/assets/swagger/lib/shred
/usr/share/arangodb/js/server/assets/swagger/lib/shred/content.js
/usr/share/arangodb/js/server/assets/swagger/lib/marked.js
/usr/share/arangodb/js/server/assets/swagger/lib/swagger-oauth.js
/usr/share/arangodb/js/server/assets/swagger/lib/jquery.wiggle.min.js
/usr/share/arangodb/js/server/assets/swagger/lib/jquery.slideto.min.js
/usr/share/arangodb/js/server/assets/swagger/lib/shred.bundle.js
/usr/share/arangodb/js/server/assets/swagger/lib/backbone-min.js
/usr/share/arangodb/js/server/assets/swagger/lib/highlight.7.3.pack.js
/usr/share/arangodb/js/apps/system/_admin/aardvark/APP/frontend/img/swagger
/usr/share/arangodb/js/apps/system/_admin/aardvark/APP/frontend/img/swagger/logo_small.png
/usr/share/arangodb/js/apps/system/_admin/aardvark/APP/frontend/img/swagger/throbber.gif
/usr/share/arangodb/js/apps/system/_admin/aardvark/APP/frontend/css/swaggerView.css
/usr/share/arangodb/js/apps/system/_admin/aardvark/APP/frontend/css/swagger
/usr/share/arangodb/js/apps/system/_admin/aardvark/APP/frontend/css/swagger/screen.scss
/usr/share/arangodb/js/apps/system/_admin/aardvark/APP/frontend/css/swagger/screen.css
/usr/share/arangodb/js/apps/system/_admin/aardvark/APP/frontend/css/swagger/hightlight.default.css
/usr/share/arangodb/js/apps/system/_admin/aardvark/APP/frontend/js/lib/swagger-ui.js
/usr/share/arangodb/js/apps/system/_admin/aardvark/APP/frontend/js/lib/swagger.js
/usr/share/arangodb/js/apps/system/_admin/aardvark/APP/frontend/js/lib/swagger-ui.min.js
/usr/share/arangodb/js/apps/system/_admin/aardvark/APP/lib/swagger.js
root@6e88f3b5dfda:/tmp# ls -l /usr/share/arangodb/js/server/assets/swagger/
total 176
drwxr-xr-x 3 root root   4096 May 29 16:28 lib
-rw-r--r-- 1 root root 110176 May 20 16:55 swagger-ui.js
-rw-r--r-- 1 root root  63560 May 20 16:55 swagger-ui.min.js

is that correct or not?

**Comment by razvanphp** [comment] 2015-05-29 16:40
no, you miss css, css, images folder + the two index.html files.

**Comment by fceller** [comment] 2015-05-29 16:44
Ok, will try to fix

**Comment by fceller** [comment] 2015-05-31 12:11
@razvanphp 2.6.0-alpha3 is currently building:

https://build.opensuse.org/package/show/home:fceller:unstable/arangodb-2.6

should now include all swagger files

**Closed** 2015-06-03 10:12 UTC
Labels: front-end
