### ISSUE TITLE
Memory leak..

### ISSUE THREAD

**Issue by kwando** [arangodb/arangodb#5414] opened 2018-05-22 06:29 UTC
This database node barely contains any data, and is almost idle all the time. Memory usage keeps rising until the node get an out of memory error and it dies. Then it is restarted by systemd.
As you can see in the graph this happens quite frequently and I have no idea how to debug this.

Basically every dip in the graph is arangodb dying/getting killed.

![node-overview](https://user-images.githubusercontent.com/891566/40345455-8f673d7c-5d99-11e8-9104-adff01b1c9d3.png)

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [X] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [X] Single-Server

Storage-Engine:
- [ ] mmfiles
- [X] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [X] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

**Comment by dothebart** [comment] 2018-05-22 12:30
Hi, 
did you set any ulimit on the memory? 
Can you try running without foxx-queues and without statistics enabled?

**Comment by kwando** [comment] 2018-05-22 14:23
I've not set any ulimit. I'm creating/running my arangodb container like this. 
I'm not sure how to make it read a config file where foxx-queues and statistics is disabled.
```
docker run \
-e ARANGO_STORAGE_ENGINE=rocksdb \
-e ARANGO_ROOT_PASSWORD=<my passwd>\
-p 127.0.0.1:8529:8529 \
--name arangodb \
-v /data/arangodb:/var/lib/arangodb3 arangodb
```

**Comment by martinkunevtoptal** [comment] 2018-06-15 14:41
I am experiencing the same issue in 3.3.9 with RocksDB (haven't tested with MMFiles). When I disable statistics, there seems to no longer be a memory leak. If I change STATISTICS_INTERVAL in js/server/modules/@arangodb/statistics.js, this influences the rate the memory grows. It seems that the leak is related to storing data or in particular to storing statistics.

**Comment by dsonet** [comment] 2018-07-17 15:09
I already upgraded to version 3.3.12 with MMFiles, I tested single mode on windows, there are no operations, I can see from the process monitor, the arangodb use memory start from 190MB, increased very fast to 930MB, then drop back to about 200MB, up & down very frequently, but just keep increasing.

**Comment by dsonet** [comment] 2018-07-17 16:00
Just tried turn off the foxx.queues to false, now the memory remains the same. Turn off statistics is not enough.

**Comment by jsteemann** [comment] 2018-11-09 14:01
@kwando @dsonet : I have responded in a related ticket: https://github.com/arangodb/arangodb/issues/5579#issuecomment-437367671
If this is still an issue, you may want to check my comment there. Thanks!

**Comment by Levalis** [comment] 2019-02-06 21:38
I'm having the same issue with version 3.4.2-1. The db is running inside a container on Docker 18.06.1 with the following compose yml:

```
version: '3'

services:
  arango-server:
    container_name: 'arango-server'
    build: .
    restart: unless-stopped
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=Tuybjhbb567FGI7TV
    volumes:
      - /var/lib/arangodb3:/var/lib/arangodb3
```

My dockerfile is simply `FROM arangodb/arangodb:3.4.2`.

The server is running on a small VPS with 1GB of memory and no activity. The memory graph shows that the DB leaks then crashes when the host refuses to allocate more. Docker then restarts the container. The database should behave like this with a basic setup.

<img width="1037" alt="screenshot 2019-02-06 at 19 11 05" src="https://user-images.githubusercontent.com/9040600/52374778-71707a80-2a5e-11e9-825f-c83411fd1b3f.png">

I'm trying out different configurations with `COPY arangod.conf /etc/arangodb3/arangod.conf`. I'll report my findings. BTW a simple way to configure the database like this should be documented for beginners like me. Digging in the container to figure out how it loads the conf is not ideal.

**Comment by jsteemann** [comment] 2019-02-07 09:56
@kwando : I doubt that this is a "leak" in the actual sense of a memory leak.
I think the growing memory usage is due to some in-memory buffers (e.g. caches) being filled over time, and they are probably getting bigger than the available memory. Even though there is probably no user-induced activity happening in the server, there are some background statistics being produced every other second, which cause a low amount of background writes going into the database. For these there may also be in-memory buffering etc., and this is probably the reason why memory usage grows over time even though there is no other activity.

There are two ways to address this:
* turning off background statistics, by starting with option `--server.statistics false`
* reducing the sizes of the most obvious buffers/caches, i.e. `--cache.size`, `--rocksdb.block-cache-size` and `--rocksdb.total-write-buffer-size`

**Comment by Levalis** [comment] 2019-02-07 10:51
@jsteemann thank you for the config pointers. `--cache.size` and `--rocksdb.block-cache-size` are default set to 256M. I reduced `--rocksdb.total-write-buffer-size` to 128M. Should we also set `rocksdb.enforce-block-cache-size-limit` for the cache limits to take effect?

If I understand correctly, I should add the `cache.size` and `rocksdb.total-write-buffer-size` to have the global cache limit of the DB?

Is there an option to sync to disk periodically to avoid having buffers growing for hours? `rocksdb.sync-interval` syncs only the WAL if I understand correctly.

**Comment by jsteemann** [comment] 2019-02-07 11:40
The cache configured via `--cache.size` will mostly be used for caching edges data. In case your workload does not contain many edge collections, you can reduce the size of this cache to a very low value. 
Reducing the value for the `--rocksdb.total-write-buffer-size` option is probably the thing that will help most. The default size for the in-memory write buffers is relatively big, in order to have most write operations happen in memory and not have to fall back to disk so early.

And yes, `--rocksdb.sync-interval` is used for syncing the WAL only. To my best knowledge there is no option to control the interval for automatic flushing of write-buffers yet.

**Comment by Levalis** [comment] 2019-02-07 12:12
@jsteemann Thanks for the detailed answer. We disabled statistics for now and monitor the memory usage.

**Comment by beast-in-black** [comment] 2019-03-01 22:05
@jsteemann as per my comment in #5579 I can confirm this issue.

I made the following changes (directly changed the defaults in the C++ code):

- `--rocksdb.total-write-buffer-size 314572800` (300 MB)
- `--rocksdb.block-cache-size 268435456` (256 MB)
- `--cache.size 268435456` (256 MB)

Even with the above (statistics is **enabled** because I need it for my use case), running arango as a Docker image with the above settings on AWS under Kubernetes **continues to show a memory increase until the DB primary pod is OOM-killed** (1 DB Primary, 1 agency, 1 coordinator).
    - AMI Instance runs debian stretch with the following kernel:
    ```
    Linux <IP REDACTED> #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
    ```
    - Docker image is based on the arango helper stretch image, compiled with gcc/gcc 6

**Comment by bischoje** [comment] 2019-05-24 19:53
We are also observing this issue. The memory usage with RocksDB cannot be controlled, regardless of what we set the buffer sizes to.

We are running ArangoDB 3.4.5 (with RocksDB 5.16.0) inside of Kubernetes 1.14.1.

We are using the following settings in our arangodb.conf:

`
[rocksdb]
# Write buffers
write-buffer-size = 2048000 # 2M
total-write-buffer-size = 536870912 # 512M
max-write-buffer-number = 4
max-total-wal-size = 1024000 # 1M

# Read buffers
block-cache-size = 268435456 # 256M
enforce-block-cache-size-limit = true

[cache]
size = 268435456 # 256M

[query]
cache-mode = on
memory-limit = 536870912 # 512M

[server]
# Disabled to avoid bug https://github.com/arangodb/arangodb/issues/5414
statistics = false

[foxx]
# Disabled to avoid bug https://github.com/arangodb/arangodb/issues/5414
queues = false

[javascript]
startup-directory = /usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps
v8-contexts = 2
v8-max-heap = 512 # 512M (apparently)

[log]
level = info
file = -
`

As you can see, we have already disabled statistics and foxx queues based on earlier suggestions in the comments of this issue. However, this has not impacted our observed performance. 

Despite the stringent cache settings, we are allocating a memory limit of 16Gi for this pod. However, it takes only a few minutes of traffic hitting arangodb to exhaust the entire 16 GB and cause an OOMKilled event. 

How can we constrain the memory usage so the container does not get OOMKilled? It seems very hard to manage the arangoDB memory usage with RocksDB enabled.

**Comment by graetzer** [comment] 2019-05-25 00:43
Can you provide more details about what you are doing? Is there a test program we could use

**Comment by jsteemann** [comment] 2019-05-27 12:29
@bischoje : just to rule out an obvious reason for increasing memory usage: 
can you check whether `vm.overcommit_memory` is set to a value of `0` (default) or `1`? If it's set to a value of `2` it is very likely that memory usage grows over time.

If it's not set to `2`, can you confirm it is resident memory usage (RSS) that grows over time, or is it virtual memory usage? Virtual memory usage is expected to grow over time, and its peak usage is not restricted by the above configuration settings. However, resident memory usage should be controlled by the above options and stay within reasonable bounds when configured appropriately.

I agree with @graetzer here in that it would make sense if you could provide more information about the setup (single server, cluster, active failover?) and workload. Otherwise it will be just guessing from our side. Thanks!

**Comment by bischoje** [comment] 2019-05-28 16:27
Thanks for the responses, I'd be happy to provide more details about our setup!

We are using a `vm.overcommit_memory` setting of `1`:

```
$ cat /proc/sys/vm/overcommit_memory
1
```

Regarding the memory usage figures that I am monitoring--apparently in Kubernetes memory usage is equal to:

"...the total resident set size (RSS) and page cache usage of a container."

Therefore, it's possible that not all the usage is RSS, the page cache could account for some of it. The tools (ctop) I'm using to monitor currently don't provide that level of granularity, but I believe other tools do. I will have to install something that lets me see how much of the growth is RSS vs. page cache.

Regarding our setup, we are using:

- ArangoDB 3.4.5 
- Kubernetes 1.14.1
- Single node (running in a container)

Regarding workload, we are working with a few gigabytes of data at a time.

We load new data in about every 10 minutes, resulting in a a new database of ~1GB. We prune our databases periodically, keeping only the two most recent. We will typically have 3-4 databases before the pruning kicks in. We'll have queries running against this data, some of which can take several minutes to execute. However, we don't have very many concurrent consumers.

In this same environment, if we run with `mmfiles`, the container typically consumes <1GB of memory and never more than 6GB. With `rocksdb`, we are hitting 16GB and getting OOMKilled.

**Comment by bischoje** [comment] 2019-05-28 21:40
So I can confirm that it is the RSS that is creeping all the way up to 16GB. Check out this graph from Prometheus:

![image](https://user-images.githubusercontent.com/18429523/58510815-89801d00-8167-11e9-8fb6-2dcdb4234a1b.png)

The red line represents a container that was OOMKilled. The green line is a container that was automatically started to replace it. I'm not sure what caused the big drop in the green line. 

Note that during the 1 hour time period, I wasn't running any big queries. The memory usage crept up at a slow, steady pace. Had I ran some big queries, the memory usage would have increased more rapidly.

Here is that same graph, a little while later (note the line is now red because the previous pod aged out of the data window):

<img width="1418" alt="Screen Shot 2019-05-28 at 5 21 54 PM" src="https://user-images.githubusercontent.com/18429523/58514255-6ce7e300-816f-11e9-8f3e-6f207d4e3216.png">

...and finally, another OOMKilled event:

<img width="1416" alt="Screen Shot 2019-05-28 at 5 36 31 PM" src="https://user-images.githubusercontent.com/18429523/58514295-8b4dde80-816f-11e9-872a-537a29b79f20.png">

I didn't do any big queries during this experiment. The usual data loading/purging was going on however. 

In case it helps, here is the arangod.conf that I used during this experiment:

```
# ArangoDB configuration file
# 
# Documentation: 
# https://docs.arangodb.com/latest/Manual/Administration/Configuration/
# 

[database]
directory = /var/lib/arangodb3

# maximal-journal-size = 33554432

[server]
# Specify the endpoint for HTTP requests by clients.
#  tcp://ipv4-address:port
#  tcp://[ipv6-address]:port
#  ssl://ipv4-address:port
#  ssl://[ipv6-address]:port
#  unix:///path/to/socket
#
# Examples:
#   endpoint = tcp://0.0.0.0:8529
#   endpoint = tcp://0.0.0.0:8529
#   endpoint = tcp://localhost:8529
#   endpoint = tcp://myserver.arangodb.com:8529
#   endpoint = tcp://[::]:8529
#   endpoint = tcp://[fe80::21a:5df1:aede:98cf]:8529
#
endpoint = tcp://0.0.0.0:8529
storage-engine = rocksdb

# reuse a port on restart or wait until it is freed by the operating system
# reuse-address = false

authentication = true

# number of server threads. use 0 to make arangod determine the
# number of threads automatically, based on available CPUs
# threads = 0

# gather server statistics
#statistics = true

# the user and group are normally set in the start script
uid = arangodb
gid = arangodb

uid = arangodb

[rocksdb]
# Write buffers
write-buffer-size = 2048000 # 2M
total-write-buffer-size = 536870912 # 512M
max-write-buffer-number = 4
max-total-wal-size = 1024000 # 1M

# Read buffers
block-cache-size = 268435456 # 256M
enforce-block-cache-size-limit = true

[cache]
size = 268435456 # 256M

[query]
cache-mode = on
memory-limit = 536870912 # 512M

[server]
# Disabled to avoid bug https://github.com/arangodb/arangodb/issues/5414
statistics = false

[foxx]
# Disabled to avoid bug https://github.com/arangodb/arangodb/issues/5414
queues = false

[javascript]
startup-directory = /usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps
v8-contexts = 1
v8-max-heap = 512 # 512M (apparently)

[log]
level = info
file = -
```

**Comment by bischoje** [comment] 2019-05-30 15:23
I was able to reproduce this issue on ArangoDB 3.4.6 as well.

The RSS growth looks like this:

<img width="1416" alt="Screen Shot 2019-05-29 at 10 30 24 PM" src="https://user-images.githubusercontent.com/18429523/58643322-08429a80-82cd-11e9-911a-983c659b4657.png">

The growth is RSS is very steady. The small blips that you see is our loading of new data (every 10 minutes).

The logs during (a snippet) of this period of time look like this:

```
arangodb: 2019-05-30T01:35:11Z [1] WARNING {engines} slow background settings sync: 1.020807 s
arangodb: 2019-05-30T01:35:24Z [1] WARNING {engines} slow background settings sync: 0.779402 s
arangodb: 2019-05-30T01:35:41Z [1] WARNING {engines} slow background settings sync: 1.371651 s
arangodb: 2019-05-30T01:36:12Z [1] WARNING {engines} slow background settings sync: 1.010393 s
arangodb: 2019-05-30T01:43:12Z [1] WARNING {queries} slow query: 'FOR se IN svc\nFILTER se.oid IN ["72938604991984","72938584020016","72938601583904","72919267317072","72938605647344","72938597258608","72938603288016","72919272953088","72919273215264","72938599748880","72919267185984","72970615294416","72970606905680","72970610051328","72919267317056","72919272035584","72919272166688","72938601714944","72919267186032","72919267186016","72919267317088","72919272559920","72938583626800","72919271904544","72938600011056","72938607351200","72919273084208","72938570520448","72970603890928","72938600797552","72970613459296","72919267185936","72970607561008","72919272822080","72938604205440","72970614770048","72938601846128","72919272297808","72919267316992","72938569996160","72970610706768","72970613852544","72970023660112","72919272953168","72970605332736","72919272035648","72938601977152","72919272166752","72919267185968","72938600535376","72919267317040","72938606695808","72919272035696","72919267317024","72938602501456"
arangodb: ,"72919271904608","72938605254016","72938603943232","72938606957840","72919272428928","72919267186128","72919267317200","72919272560000","72919272691072","72970604152864","72938583233664","72919272166800","72949539971488","72919267186112","72919267317184","72938604598608","72938597127648","72929361424992","72919272822160","72919272953232","72959675235648","72919273084304","72919272297888","72919267186160","72938603681120","72938570127200","72938601321872","72938570782560","72919272035760","72919273215360","72949539971457","72938606826784","72919267317216","72938602370448","72938582447264","72919271904672","72938597914064","72938582054096","72938599880128","72919267186064","72919267317136","72948211832528","72919272691136","72938606302496","72919272166864","72970614245632","72919267317120","72919272560080","72938603549952","72919271773632","72919272953296","72919273215440","72949539971536","72919267186096","72970608085376","72970609265040","72938600666560","72970604808272","72919267317152","72938582578400","7
arangodb: 2919272822256","72938599093728","72931783246752","72938570651440","72919273084400","72938598831120","72919272297472","72919267054672","72919267185744","72919267316816","72919272559616","72919272166416","72938603812048","72919267316800","72970611755040","72970603497888","72938569733824","72919271904256","72938598437936","72919267316848","72938600404000","72919271773232","72938604860608","72919267185760","72938583495984","72919272428608","72938597389344","72938605778080","72919267316752","72919272690752","72938581398816","72919272821824","72970612934752","72938581267744","72919272952896","72919273083968","72919272166480","72958137114832","72919272297552","72938583889248","72919267185664","72959502612016","72919272559696","72938581529904","72919272035392","72970610313328","72970609920112","72919267185712","72938581661040","72919271773296","72919272035440","72938605122688","72919273215040","72938582971760","72970613065808","72942905070800","72919267185696","72919267316768","72938599224416","72938602239056","7291
arangodb: 9271904352","72938597782752","72949765550848","72919267185872","72919267316944","72938598044896","72919272166544","72919273215136","72919272297616","72938598569088","72970606774480","72919267185856","72970612148384","72919272559760","72938598307056","72970603366688","72919272821904","72938605384800","72970613328000","72938597520576","72919267185904","72919267316976","72919272690848","72938603418736","72938600273056","72919271773360","72938606433344","72919273084064","72919267316960","72938601452672","72919272953008","72938599617728","72919267185808","72938583758320","72919267316880","72970605463696","72938596734112","72919273215200","72970605070704","72919272428752","72919267185792","72919267316864","72919271904448","72938581136816","72919272035520","72919272166624","72919267316912","72919272821984","72970613983280","72938600142048","72938603156528","72938570389040","72938581923296","72919272297712","72938570257968","72938582840816","72919267185824","72919272559856","72919267316896","72919272690928","7293860
arangodb: 1190592","72937547258672","72919273084144","72919272167168","...', took: 14.068954 s
arangodb: 2019-05-30T01:44:24Z [1] WARNING {engines} slow background settings sync: 0.870224 s
arangodb: 2019-05-30T01:44:30Z [1] WARNING {engines} slow background settings sync: 1.021748 s
arangodb: 2019-05-30T01:44:45Z [1] WARNING {engines} slow background settings sync: 1.154522 s
arangodb: 2019-05-30T01:52:48Z [1] WARNING {engines} slow background settings sync: 1.379094 s
```

Please advise what my next steps should be in debugging/collecting data. 

I will see if it is possible to create a sample program to reproduce this, though it may be difficult.

**Comment by bischoje** [comment] 2019-05-31 02:48
Okay, I seem to be noticing another aspect to this mystery. My rocksDB journal files never get deleted or shrink, even though I periodically delete all but my most recent databases. I did not observe a similar problem with mmFiles enabled.

Also, the rate of RSS growth is approximately equal to the increase in size of the rocksDB journal files. 

The files never get cleaned up, so if I let it OOM and restart a few times it will eventually fill the entire (100GB) disk.

**Comment by jsteemann** [comment] 2019-05-31 09:09
@bischoje : the journal files should eventually be moved by RocksDB to the `archive` subdirectory and be removed from there. If you are using a single server (as you mentioned above) it is completely unexpected that they are not wiped after some time.
I guess that this may somehow be related to RocksDB snapshots still being around, which will keep the journal files from being deleted.

To confirm, can you run the following command from the arangosh from time to time?
```js
stats = db._engineStats(); 
Object.keys(stats).filter(function(name) { return /snapshot/.test(name); }).forEach(function(name) { print(name, "->", stats[name]); });
```
This should show the number of snapshots around plus the "age" of the oldest snapshot, e.g.:
```
rocksdb.num-snapshots -> 1
rocksdb.oldest-snapshot-time -> 1559293591
```
The number of snapshots should not grow over time if the workload is constant. From time to time there may of course be snapshots active, but they should vanish eventually. Additionally, if there is a snapshot around, the oldest-snapshot-time should increase eventually. If it stays constant, it means that a snapshot is not released, which will keep journal files from being removed. 
Thanks!

**Comment by bischoje** [comment] 2019-06-01 01:51
@jsteemann, I took measurements at seven different times (I'll call them snapshots) during the course of a single container's lifecycle. The first snapshot was taken shortly after startup completed, while the seventh was taken shortly before the OOMKill event. These were taken ad-hoc, so the interval between each snapshot varies. I took more snapshots towards the end. Here are the results:

Snapshot 1:
rocksdb.num-snapshots -> 1
rocksdb.oldest-snapshot-time -> 1559349905
2.4GB RSS and 3.4GB engine (2.7GB journals)

Snapshot 2:
rocksdb.num-snapshots -> 0
rocksdb.oldest-snapshot-time -> 0
8GB RSS and 7.3GB engine (6.6GB journals)

Snapshot 3:
rocksdb.num-snapshots -> 1
rocksdb.oldest-snapshot-time -> 1559351578
9.5GB RSS and 9.4GB engine (8.7GB journals)

Snapshot 4:
rocksdb.num-snapshots -> 0
rocksdb.oldest-snapshot-time -> 0
10.8B RSS and 11GB engine (11GB journals)

Snapshot 5:
rocksdb.num-snapshots -> 0
rocksdb.oldest-snapshot-time -> 0
13.5B RSS and 14GB engine (13GB journals)

Snapshot 6:
rocksdb.num-snapshots -> 0
rocksdb.oldest-snapshot-time -> 0
14B RSS and 14GB engine (14GB journals)

Snapshot 7:
rocksdb.num-snapshots -> 0
rocksdb.oldest-snapshot-time -> 0
15.25 RSS and 16GB engine (15GB journals)

I'll also include the final stats output that I was able to grab during snapshot 7:

```
127.0.0.1:8529@_system> stats = db._engineStats(); 
{ 
  "rocksdb.num-files-at-level0" : "1", 
  "rocksdb.compression-ratio-at-level0" : "0.996656", 
  "rocksdb.num-files-at-level1" : "0", 
  "rocksdb.compression-ratio-at-level1" : "-1.000000", 
  "rocksdb.num-files-at-level2" : "0", 
  "rocksdb.compression-ratio-at-level2" : "-1.000000", 
  "rocksdb.num-files-at-level3" : "0", 
  "rocksdb.compression-ratio-at-level3" : "-1.000000", 
  "rocksdb.num-files-at-level4" : "0", 
  "rocksdb.compression-ratio-at-level4" : "-1.000000", 
  "rocksdb.num-files-at-level5" : "0", 
  "rocksdb.compression-ratio-at-level5" : "-1.000000", 
  "rocksdb.num-files-at-level6" : "0", 
  "rocksdb.compression-ratio-at-level6" : "-1.000000", 
  "rocksdb.num-immutable-mem-table" : 0, 
  "rocksdb.num-immutable-mem-table-flushed" : 0, 
  "rocksdb.mem-table-flush-pending" : 0, 
  "rocksdb.compaction-pending" : 0, 
  "rocksdb.background-errors" : 0, 
  "rocksdb.cur-size-active-mem-table" : 724873152, 
  "rocksdb.cur-size-all-mem-tables" : 724873152, 
  "rocksdb.size-all-mem-tables" : 724873152, 
  "rocksdb.num-entries-active-mem-table" : 26395, 
  "rocksdb.num-entries-imm-mem-tables" : 0, 
  "rocksdb.num-deletes-active-mem-table" : 441, 
  "rocksdb.num-deletes-imm-mem-tables" : 0, 
  "rocksdb.estimate-num-keys" : 25642, 
  "rocksdb.estimate-table-readers-mem" : 1900, 
  "rocksdb.num-snapshots" : 0, 
  "rocksdb.oldest-snapshot-time" : 0, 
  "rocksdb.num-live-versions" : 1, 
  "rocksdb.min-log-number-to-keep" : 0, 
  "rocksdb.estimate-live-data-size" : 615800, 
  "rocksdb.live-sst-files-size" : 615800, 
  "rocksdb.dbstats" : "\n** DB Stats **\nUptime(secs): 4133.1 total, 299.8 interval\nCumulative writes: 62K writes, 32M keys, 61K commit groups, 1.0 writes per commit group, ingest: 12.23 GB, 3.03 MB/s\nCumulative WAL: 62K writes, 0 syncs, 62864.00 writes per sync, written: 12.23 GB...", 
  "rocksdb.sstables" : "--- level 0 --- version# 21 ---\n 32:615800['300000000000000001' seq:3, type:1 .. '3D000000000000B955' seq:5414619, type:1](0)\n--- level 1 --- version# 21 ---\n--- level 2 --- version# 21 ---\n--- level 3 --- version# 21 ---\n--- level 4 --- version# 21 ---\n--...", 
  "rocksdb.num-running-compactions" : 0, 
  "rocksdb.num-running-flushes" : 0, 
  "rocksdb.is-file-deletions-enabled" : 1, 
  "rocksdb.estimate-pending-compaction-bytes" : 0, 
  "rocksdb.base-level" : 6, 
  "rocksdb.block-cache-capacity" : 268435456000000, 
  "rocksdb.block-cache-usage" : 180864, 
  "rocksdb.block-cache-pinned-usage" : 0, 
  "rocksdb.total-sst-files-size" : 615800, 
  "rocksdb.actual-delayed-write-rate" : 0, 
  "rocksdb.is-write-stopped" : 0, 
  "cache.limit" : 268435456000000, 
  "cache.allocated" : 1688136, 
  "cache.hit-rate-lifetime" : 0, 
  "cache.hit-rate-recent" : 0, 
  "columnFamilies" : { 
    "definitions" : { 
      "dbstats" : "\n** Compaction Stats [default] **\nLevel    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop\n--------------------------------------------------------------------...", 
      "memory" : 725052970 
    }, 
    "documents" : { 
      "dbstats" : "\n** Compaction Stats [Documents] **\nLevel    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop\n------------------------------------------------------------------...", 
      "memory" : 11924254142 
    }, 
    "primary" : { 
      "dbstats" : "\n** Compaction Stats [PrimaryIndex] **\nLevel    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop\n---------------------------------------------------------------...", 
      "memory" : 262713506 
    }, 
    "edge" : { 
      "dbstats" : "\n** Compaction Stats [EdgeIndex] **\nLevel    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop\n------------------------------------------------------------------...", 
      "memory" : 511523305 
    }, 
    "vpack" : { 
      "dbstats" : "\n** Compaction Stats [VPackIndex] **\nLevel    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop\n-----------------------------------------------------------------...", 
      "memory" : 366718042 
    }, 
    "geo" : { 
      "dbstats" : "\n** Compaction Stats [GeoIndex] **\nLevel    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop\n-------------------------------------------------------------------...", 
      "memory" : 0 
    }, 
    "fulltext" : { 
      "dbstats" : "\n** Compaction Stats [FulltextIndex] **\nLevel    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop\n--------------------------------------------------------------...", 
      "memory" : 269356644 
    } 
  } 
}
```

It sounds from your description that the snapshots at least are working as expected? I hope there's some other clue in this data.

**Comment by jsteemann** [comment] 2019-06-03 14:45
@bischoje : it seems from your data that all snapshots get released timely, so snapshots are not to blame here.

I am a bit concerned however about the capacities of both `--rocksdb.block-cache-size` and `--cache.size`, as from the stats it seems they are set to a max of 256 TB each, which looks a few orders of magnitude too high. This _may_ also be the cause of the system finally running out of memory.

I think the syntax config file syntax does not support lines such as
`block-cache-size = 268435456 # 256M`
I think effectively this will be interpreted as something like
`block-cache-size = 268435456256000000`, which is way higher than intended.

So the config you want to have in effect isn't. Can you try removing the comments from the same lines as the key/value pairs (a comment on a separate line works just fine)? That will at least put the desired configuration into effect. 
I cannot guarantee this will change the server's memory consumption, but it should at least make the limits kick in while right now they aren't kicking in at all.

**Comment by bischoje** [comment] 2019-06-03 15:18
Oh my god, are you serious? The thought had crossed my mind at one point that those comments might not be supported, but I couldn't find an easy way to see the "effective" maximums from the running instance. I mostly looked in the logs and the UI--I didn't know I could find them here! I should have moved them to separate lines, just to be safe. 

I'll update the configuration and re-test this ASAP. I will let you guys know how it goes.

One quick clarification in the meantime: What unit are those cache sizes specified in? Is bytes the only option for specifying it? It's odd to me that not only did the 256 get appended to the value, but six zeros got added as well. Do those zeroes always get added?

**Comment by graetzer** [comment] 2019-06-03 15:35
i think you can use suffixes like MiB / MB. Just write 256MiB instead of 268435456

**Comment by jsteemann** [comment] 2019-06-03 15:45
The suffixes are ok to use.
The problem is just the combination of comments & suffixes such as 
```
key = value # 2M
```
However, both of the following variants will work:
```
key = value
key = 2M
```

**Comment by jsteemann** [comment] 2019-06-03 18:32
@bischoje : yes, the unit for these options is "bytes" unless otherwise specified.
However, the config file parser just didn't expect comments in the middle of a line, so something went completely wrong when using them. Effectively the trailing "M" of "# 256M" was used as a multiplicator of 1000 * 1000 and applied to the original value, so that
```
block-cache-size = 268435456 # 256M
```
effectively becomes
```
block-cache-size = 268435456000000
```
I am right now trying to fix this in some PRs. However, the only thing that can be done in the released versions is to not use comments and values in the same line.

**Comment by bischoje** [comment] 2019-06-03 19:06
Thanks guys! I removed the comments and it worked a lot better. After the changes, RSS usage peaks around 2GB and generally sits around 800-900MB. Disk usage is also greatly reduced, especially in the case of the journals. It seems stable for a few hours now.

I tried using values like 256MiB, and this seems to work well. I see the same "268435456" value getting set in the stats output from arangosh. I wish I knew from the beginning that this was supported! One of the problems I faced was that it was hard to find out what the actual, effective values were--is this something we could print to the logs during startup? I was looking there and didn't know to look in the stats output instead. I could have caught this a lot faster.

**Comment by jsteemann** [comment] 2019-06-03 19:13
@bischoje : thanks for getting back with the confirmation that this has improved the situation.
I have to admit this handling of config options was also unexpected for me, although the docs somehow mention that comments should be placed at the beginning of each line: 
https://github.com/arangodb/arangodb/blame/3.4/Documentation/Books/Manual/Administration/Configuration/README.md#L120

However, I don't expect anyone to read the documentation for the config file format, and I guess we just need to improve here. 

PR https://github.com/arangodb/arangodb/pull/9170 will improve the situation, and I also created PR https://github.com/arangodb/docs/pull/61 to highlight the importance of putting comments only at the beginning of each line.

A colleague of mine also opened a feature request for showing the config values somewhere in the web UI: https://github.com/arangodb/arangodb/issues/9175

All of this together will hopefully improve the situation enough in the near future.

**Comment by bischoje** [comment] 2019-06-03 19:26
@jsteemann, thanks for the link. I hadn't seen that particular documentation. It also mentions this tidbit that I was unaware of: "Only command line options with a value should be set within the configuration
file." I'll keep that one in mind too.

I really appreciate the help in figuring this out, not to mention all the follow-up tasks that you guys are taking on. Thanks!

**Comment by jsteemann** [comment] 2019-06-03 19:50
Thank you for helping us finding out the root cause (hopefully) of the problem!
I am sorry it took so long to figure out, but the problem seems to have been at a very unexpected location, namely the processing of config options.
I strongly hope that by adjusting the conf values it will now work fine without ever-growing memory usage. :crossed_fingers:

**Comment by Simran-B** [comment] 2019-06-11 13:32
> Only command line options with a value should be set within the configuration file. Command line options which act as flags should only be entered on the command line when starting the server.

Well, there are Boolean options for which you don't have to specify `true` and there are command options which terminate the process afterwards. The latter should not be added to a config file, because it doesn't make much sense to have a config which ends the server process almost immediately. Technically, it is possible to execute the `--version` command however, by putting `version=true` in the config.

For some Boolean options it makes sense to add them to the config file, e.g. `foxx.queues`. The `--console` option to "Start a javascript emergency console" on the other hand doesn't make much sense. I wonder if it is incorrectly marked as regular option instead of as command option...

**Comment by maxkernbach** [comment] 2019-08-19 07:50
Hi all,

in the meantime v3.4.7 and v3.3.24, which both include the fix for the parsing of ArangoDB config files with inline comments, have been released. 

From the [Changelog](https://github.com/arangodb/arangodb/blob/1f27aac6b47ab6f84c73675aa9732366245fe7d1/CHANGELOG#L33):

> * Fixed parsing of ArangoDB config files with inlined comments. Previous versions didn't handle
>   line comments properly if they were appended to an otherwise valid option value.
> 
>   For example, the comment in the line
> 
>       max-total-wal-size = 1024000 # 1M
> 
>   was not ignored and made part of the value. In the end, the value was interpreted as if
> 
>       max-total-wal-size = 10240001000000
> 
>   was specified.
>   This version fixes the handling of comments in the config files so that they behave as intended.
> 

Is anyone still facing memory issues after checking the **vm.overcommit_memory** value and comments in the ArangoDB config file? Can this issue be resolved?

@mantissa7 

Do you still have this problem or have you been able to fix it?
Did you check whether vm.overcommit_memory is set to a value of 0 (default) or 1? If it's set to a value of 2 it is very likely that memory usage grows over time.

**Comment by mantissa7** [comment] 2019-08-19 14:05
I think it's fine. It seems to have settled, with a steady rhythm of little bumps which I assume is probably garbage collection. It's a dev server with very little activity, idle most days. Digital Ocean stats show the droplet sitting at about 60% total memory.

I haven't been active on the project since i've been busy with other work, so I haven't done any more testing, but for now it seems to be fine.

<img width="1218" alt="Screenshot 2019-08-19 at 14 46 03" src="https://user-images.githubusercontent.com/13873136/63270876-e126b400-c290-11e9-9c2d-be0b2683a51a.png">

**Comment by maxkernbach** [comment] 2019-10-24 08:46
Since there are no additional reports since the config file parsing fix is available, I am closing this issue.

Thanks again for helping us to find out the root cause of this problem.

**Closed by maxkernbach** 2019-10-24 08:46 UTC
Labels: 1 Bug, 2 Fixed, 3 OOM, 3 RocksDB, Waiting User Reply
