### ISSUE TITLE
Foxx manifest "lib" option should not affect node_modules resolution

### ISSUE THREAD

**Issue by lewisdiamond** [arangodb/arangodb#2139] opened 2016-11-02 00:10 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

https://docs.arangodb.com/3.0/Manual/Foxx/Dependencies.html#module-dependencies

How do you configure the "dependencies" field in manifest.json such that your dependencies are picked up properly? How do you use them? require('chai-spies')?

**Comment by lewisdiamond** [comment] 2016-11-02 01:31
Here's an example with chai-spies:
```
2016-11-02T01:28:55Z [1] ERROR Service "/_admin/aardvark" encountered error 500 while handling POST http://localhost:8529/_db/chopchop_test/_admin/aardvark/foxxes/tests?mount=%252Fchopchop
2016-11-02T01:28:55Z [1] ERROR ArangoError: failed to invoke module
2016-11-02T01:28:55Z [1] ERROR File: /var/lib/arangodb3-apps/_db/chopchop_test/chopchop/APP/dist/tests/models/item.js
2016-11-02T01:28:55Z [1] ERROR Cause: ArangoError: cannot locate module
2016-11-02T01:28:55Z [1] ERROR File: chai-spies
2016-11-02T01:28:55Z [1] ERROR     at Function.Module._resolveFilename (/usr/share/arangodb3/js/common/bootstrap/modules.js:524:11)
2016-11-02T01:28:55Z [1] ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:443:25)
2016-11-02T01:28:55Z [1] ERROR     at require (/usr/share/arangodb3/js/common/bootstrap/modules.js:95:19)
2016-11-02T01:28:55Z [1] ERROR     at Object.<anonymous> (/var/lib/arangodb3-apps/_db/chopchop_test/chopchop/APP/dist/tests/models/item.js:12:15)
2016-11-02T01:28:55Z [1] ERROR     at Module._compile (/usr/share/arangodb3/js/common/bootstrap/modules.js:593:6)
2016-11-02T01:28:55Z [1] ERROR     at Object.Module._extensions..js (/usr/share/arangodb3/js/common/bootstrap/modules.js:613:10)
2016-11-02T01:28:55Z [1] ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:544:34)
2016-11-02T01:28:55Z [1] ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:488:14)
2016-11-02T01:28:55Z [1] ERROR     at require (/usr/share/arangodb3/js/common/bootstrap/modules.js:95:19)
2016-11-02T01:28:55Z [1] ERROR     at Suite.describe (/var/lib/arangodb3-apps/_db/chopchop_test/chopchop/APP/dist/tests/models/index.js:4:5)
2016-11-02T01:28:55Z [1] ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:547:21)
2016-11-02T01:28:55Z [1] ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:488:14)
2016-11-02T01:28:55Z [1] ERROR     at require (/usr/share/arangodb3/js/common/bootstrap/modules.js:95:19)
2016-11-02T01:28:55Z [1] ERROR     at Suite.describe (/var/lib/arangodb3-apps/_db/chopchop_test/chopchop/APP/dist/tests/models/index.js:4:5)
2016-11-02T01:28:55Z [1] ERROR     at context.describe.context.context (/usr/share/arangodb3/js/node/node_modules/mocha/lib/interfaces/bdd.js:47:10)
2016-11-02T01:28:55Z [1] ERROR     at Object.<anonymous> (/var/lib/arangodb3-apps/_db/chopchop_test/chopchop/APP/dist/tests/models/index.js:3:1)
2016-11-02T01:28:55Z [1] ERROR     at Module._compile (/usr/share/arangodb3/js/common/bootstrap/modules.js:593:6)
2016-11-02T01:28:55Z [1] ERROR     at Object.Module._extensions..js (/usr/share/arangodb3/js/common/bootstrap/modules.js:613:10)
2016-11-02T01:28:55Z [1] ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:544:34)
2016-11-02T01:28:55Z [1] ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:488:14)
2016-11-02T01:28:55Z [1] ERROR via ArangoError: cannot locate module
2016-11-02T01:28:55Z [1] ERROR File: chai-spies
2016-11-02T01:28:55Z [1] ERROR     at Function.Module._resolveFilename (/usr/share/arangodb3/js/common/bootstrap/modules.js:524:11)
2016-11-02T01:28:55Z [1] ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:443:25)
2016-11-02T01:28:55Z [1] ERROR     at require (/usr/share/arangodb3/js/common/bootstrap/modules.js:95:19)
2016-11-02T01:28:55Z [1] ERROR     at Object.<anonymous> (/var/lib/arangodb3-apps/_db/chopchop_test/chopchop/APP/dist/tests/models/item.js:12:15)
2016-11-02T01:28:55Z [1] ERROR     at Module._compile (/usr/share/arangodb3/js/common/bootstrap/modules.js:593:6)
2016-11-02T01:28:55Z [1] ERROR     at Object.Module._extensions..js (/usr/share/arangodb3/js/common/bootstrap/modules.js:613:10)
2016-11-02T01:28:55Z [1] ERROR     at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:544:34)
2016-11-02T01:28:55Z [1] ERROR     at Function.Module._load (/usr/share/arangodb3/js/common/bootstrap/modules.js:488:14)
2016-11-02T01:28:55Z [1] ERROR     at require (/usr/share/arangodb3/js/common/bootstrap/modules.js:95:19)
2016-11-02T01:28:55Z [1] ERROR     at Suite.describe (/var/lib/arangodb3-apps/_db/chopchop_test/chopchop/APP/dist/tests/models/index.js:4:5)
```
code:
```
const spies = require('chai-spies')

console.log(spies)
```

```
$ sudo npm run bash
[sudo] password for ldiamond:

> arangodb@1.0.0 bash /home/ldiamond/dev/proj/chopchop/arangodb
> docker exec -it $npm_package_config_instance_name /bin/bash

root@d5f4711aa63f:/# ls /var/lib/arangodb3-apps/_db/
_system/       chopchop/      chopchop_test/
root@d5f4711aa63f:/# ls /var/lib/arangodb3-apps/_db/chopchop_test/chopchop/APP/
.babelrc            .gitignore          .package.json.swp   manifest.json       package.json        src/
.git/               .manifest.json.swp  dist/               node_modules/       scripts/
root@d5f4711aa63f:/# ls /var/lib/arangodb3-apps/_db/chopchop_test/chopchop/APP/node_modules/ch
chai-spies/ chalk/      chokidar/
root@d5f4711aa63f:/# ls /var/lib/arangodb3-apps/_db/chopchop_test/chopchop/APP/node_modules/chai-spies/
History.md  LICENSE  Makefile  README.md  ReleaseNotes.md  bower.json  chai-spies.js  component.json  index.js  lib  package.json  support  test
root@d5f4711aa63f:/#
```

**Comment by pluma** [comment] 2016-11-02 01:36
The source of that module seems to live here: https://github.com/chaijs/chai-spies

I think the problem is that the `package.json` specifies `main` as `./index` but the actual file is called `index.js`. This is probably an edge case, but we should emulate node's behaviour here and attempt to resolve the path like a require path (i.e. the usual directory/extension attempts logic).

**Comment by pluma** [comment] 2016-11-02 17:19
Nope, the problem seems to be with the way the "lib" option in the manifest works.

**Comment by pluma** [comment] 2016-11-02 17:37
Your directory layout actually shows why "lib" is pretty useless: I'm guessing your "lib" points at the "dist" folder and "src" contains the babel sources. But your "scripts" folder lives outside that folder so probably your scripts aren't being found either -- and if they are, this is a bug according to the documentation which clearly states "all file paths" will be resolved relative to the "lib" path.

The main purpose of the "lib" option in 2.x was avoiding redundancy when specifying all the various controllers and exports and scripts. That seems redundant considering there's now (as of 3.0) an explicit entry file that can be arbitrarily deeply nested and all relative imports from there will be resolved as relative to that file (as of the change of how require works back in 2.x).

If removing the "lib" option and adjusting the "main" path as necessary fixes this problem, my recommendation would be that we officially deprecated the "lib" option for 3.x services and only keep it for backwards compatibility with 2.x services. We can implement deprecation warnings for 3.x (non-legacy) services using the option.

Right now "lib" is only helpful in situations where all JavaScript code (including tests, scripts and `node_modules`) lives in a subfolder of the service root. This doesn't seem to cover any real world usage patterns except some historical services that needed to distinguish between Foxx JS code and "asset" JS code living side-by-side.

**Comment by pluma** [comment] 2016-11-02 17:40
I'll remove the "bug" label if @lewisdiamond can confirm removing the "lib" option makes the behaviour go away.

Deprecation or not, we should adjust the docs to specify how "lib" affects node_modules and add an example for plain node_modules to the dependency page of the docs.

**Comment by lewisdiamond** [comment] 2016-11-02 19:54
Just to respond to your 2nd comment.

I used "lib" for a few reasons:

- Babel uses src and pushes the result to dist
- Babel does not delete files that were deleted in src
- Clearing the dist folder requires skipping manifest.json, package.json, node_modules, and others as you add them, i.e. it adds maintenance
- Removing libs means you must have package.json inside dist/ and run npm install in dist/ as well. Meaning the build now either runs it every time (which takes a while) or somehow decides when to skip that (or the developer needs to remember running it when it gets updated).
- The "scripts" folder you see is not related to the Foxx service itself. These are scripts used to push the application to the server and run the unit tests + output the result. I.e. they are long scripts used in package.json "scripts" option.

The alternative option is to prefix every file in manifest.json with dist (i.e. "main", "tests", "scripts")

**Comment by pluma** [comment] 2016-11-02 20:30
For context: the "lib" field seems to be originally based on "directories.lib" which NPM inherited from the [CommonJS Packages/1.0 spec](http://wiki.commonjs.org/wiki/Packages/1.0) which Node.js however does not implement. Even NPM only specifies that [the property exists but doesn't do anything](https://docs.npmjs.com/files/package.json).

I think the change to the module loader in 2.8 may have actually introduced the behaviour you've been observing but FWIW the behaviour before 2.8 wasn't fully compatible with Node modules to begin with.

There may be a way to rewrite the manifest on install to respect the "lib" property as part of the validation step (and drop the "lib" property from the stored manifest to avoid corruption) which would solve the problematic behaviour without requiring any modification to the module loader itself (which would be a deal breaker).

I'm still in favour of deprecating the property in 3.2 but we will continue to support it for all future 3.x releases and if we can sort out the behaviour we probably don't need to add deprecation warnings.

There's only one very unlikely scenario I can think of that would make this a breaking change:

1. The Foxx service uses a "lib" folder
2. The service's base folder contains a "node_modules" folder containing a Node-specific module that is incompatible with Foxx
3. ArangoDB provides a Foxx-compatible surrogate with the same name as a bundled module
4. The Foxx service requires the module expecting the ArangoDB surrogate and instead receiving the incompatible version contained in the service bundle

However this can be fixed by removing unrelated files from the bundle before deployment, so I consider this an unimportant edge case.

**Closed** 2016-11-03 09:35 UTC
Labels: 3_Feature, foxx
