### ISSUE TITLE
AQL query with Length and Filter using index with scalar and array entries [A, B[*] ] returns wrong count

### ISSUE THREAD

**Issue by ajscarvalho** [arangodb/arangodb#13675] opened 2021-03-10 15:44 UTC
## My Environment

* __ArangoDB Version__:        3.7.6, 3.7.9
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Kubernetes
* __Configuration__:               standard with settings to limit memory consumption
* __Infrastructure__:               own
* __Operating System__:        your docker container arangodb/arangodb
* __Total RAM in your machine__:        4GB
* __Disks in use__:       ceph
* __Used Package__:              using docker image

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
```

return length(for c in Content filter c.contentType == 'movie' return c) // returns 40357 instead of 12K

```
__AQL explain and/or profile (if applicable)__:

Execution plan:
 Id   NodeType            Calls   Items   Runtime [s]   Comment
  1   SingletonNode           1       1       0.00001   * ROOT
 12   SubqueryStartNode       1       2       0.00001     - LET #1 = ( /* subquery begin */
 11   IndexNode               1       2       0.05930       - FOR c IN Content   /* hash index scan, scan only */    /* with count optimization */
 13   SubqueryEndNode         1       1       0.00003         - RETURN  c ) /* subquery end */
  8   CalculationNode         1       1       0.00002     - LET #5 = SUM(#1)   /* simple expression */
  9   ReturnNode              1       1       0.00002     - RETURN #5

Indexes used:
 By   Name                      Type   Collection   Unique   Sparse   Selectivity   Fields                           Ranges
 11   idx_1681266476083838976   hash   Content      false    false         0.03 %   [ `contentType`, `genres[*]` ]   (c.`contentType` == "movie")

Optimization rules applied:
 Id   RuleName
  1   optimize-subqueries
  2   move-calculations-up-2
  3   use-indexes
  4   remove-filter-covered-by-index
  5   remove-unnecessary-calculations-2
  6   optimize-count
  7   splice-subqueries

__Dataset__:

__Size of your Dataset on disk__:
~500MB

__Replication Factor & Number of Shards (Cluster only)__:
Single instance

## Steps to reproduce

1. Run Query on web UI, also check other queries below that return the correct results, and my comments

__Problem__:

for c in Content filter c.contentType == 'movie' return c._id  // returns 12K elements

return length(for c in Content filter c.contentType == 'movie' return c) // returns [40357]

let a = (for c in Content filter c.contentType == 'movie' return {_id: c._id, contentType: c.contentType})
return {a, LEN: length(a)}
// returns 12K in LEN

let a = (for c in Content filter c.contentType == 'movie' return {_id: c._id, contentType: c.contentType})
return length(a)
// returns 40K again

Comments:
it seems that it's using an index with contentType and genres[*]
IMHO, since genres is an array, if a content has two genres it will count as 2

__Expected result__:

should return the length of the filtered collection, not of the index...

**Comment by maxkernbach** [comment] 2021-03-12 17:32
Hi @ajscarvalho,

Thanks for reporting.

> it seems that it's using an index with contentType and genres[*]
IMHO, since genres is an array, if a content has two genres it will count as 2

This observation seems to be correct. I created 100 test documents containing an array `genres[]` with 3 elements and the returned document count was exactly 3x the of the actual count.

Reproducible via latest version 3.7.9 with `arangosh`:

1. create test collection
```
db._createDocumentCollection("Content");
```
2. create index on two fields (one array field)
```
db.Content.ensureIndex({ type: "persistent", fields: [ "contentType", "genres[*]" ] });
```
3. insert 100 documents (`genres[]` contains 3 elements)
```
db._query(`FOR i IN 1..100 INSERT {    "contentType":"movie",    "genres":[       {          "g1":"a"       },       {          "g2":"b"       },       {          "g3":"c"       }    ] } INTO Content`);
```
4. run reported query (`FILTER` returns all elements since all documents have `"contentType":"movie"`)
```
db._query(`return length(for c in Content filter c.contentType == 'movie' return c)`);
[object ArangoQueryCursor, count: 1, cached: false, hasMore: false]

[ 
  300 
]
```
5. run query which returns the actual document count
```
db._query(`return length(Content)`);
[object ArangoQueryCursor, count: 1, cached: false, hasMore: false]

[ 
  100 
]
```

As shown above, using the index `contentType, genres[*]`, the returned document count is 300, which is the true document count times the number of elements in `genres[]` (100 * 3).

**Comment by Simran-B** [comment] 2021-03-18 15:34
FWIW, the following index and query combination was not affected:
```js
db.Content.ensureIndex({ type: "persistent", fields: [ "contentType", "genres[*].g1" ] });
db._query(`return length(for c in Content filter c.contentType == 'movie' and 'a' in c.genres[*].g1 return c)`);
```

**Comment by maxkernbach** [comment] 2021-05-10 09:29
Hi @ajscarvalho,

Version 3.7.11 including a fix has been released.

Could you please let us know whether the issue is resolved?

**Closed** 2021-05-19 14:32 UTC
Labels: 1 Bug, 2 Fixed, 3 AQL, 3 Index, Waiting User Reply
