### ISSUE TITLE
service "/_admin/aardvark" encountered error 500 while handling GET /_db/_system/_admin/aardvark/statistics/coordshort

### ISSUE THREAD

**Issue by nicolaselkhoury** [arangodb/arangodb#3301] opened 2017-09-20 14:22 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [X ] 3.1
- [ ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ x] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [x ] this Driver: ArangoJS

 we are running a production Database cluster consisting of the following:
 
Three AWS linux servers, each of which contains one Coordinator, one Agent, and one Primary Database. All three servers are located in a private network on AWS. The databases are ran as docker images (ArangoDB v3.1.24).

The cluster is consistent and is running smoothly. However, every couple of days, one or more coordinators generate the following warning, for a few hours, and then everything comes back to normal:

   ` 2017-09-20T14:07:33Z [1] WARNING cannot contact coordinator <COORDINATOR_ID> on endpoint <endpoint>

    2017-09-20T14:01:40Z [1] ERROR Service "/_admin/aardvark" encountered error 500 while handling GET http://<host>:<port>/_db/_system/_admin/aardvark/statistics/coordshort
    2017-09-20T14:01:40Z [1] ERROR TypeError: Cannot read property '0' of undefined
    2017-09-20T14:01:40Z [1] ERROR     at /usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:480:64
    2017-09-20T14:01:40Z [1] ERROR     at arrayEach (/usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:530:11)
    2017-09-20T14:01:40Z [1] ERROR     at Function.forEach (/usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:9319:14)
    2017-09-20T14:01:40Z [1] ERROR     at /usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:479:15
    2017-09-20T14:01:40Z [1] ERROR     at arrayEach (/usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:530:11)
    2017-09-20T14:01:40Z [1] ERROR     at Function.forEach (/usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:9319:14)
    2017-09-20T14:01:40Z [1] ERROR     at /usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:477:13
    2017-09-20T14:01:40Z [1] ERROR     at arrayEach (/usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:530:11)
    2017-09-20T14:01:40Z [1] ERROR     at Function.forEach (/usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:9319:14)
    2017-09-20T14:01:40Z [1] ERROR     at mergeHistory (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:440:7)`

I can't really figure out why this happens, and why it stops happening on its own.

PS: When it happens, I can't access the Arango Dashboard, however the database, remains working fine.

**Comment by dothebart** [comment] 2017-09-20 14:51
Hi, 
this may happen during the cluster startup, but should go away once everything is up and running. 

Can you revalidate that?

**Comment by nicolaselkhoury** [comment] 2017-09-20 14:54
Thank you for your quick reply. The cluster has been up and running for about two months now. Every few days we get this error.

**Comment by dothebart** [comment] 2017-11-23 15:02
Hi, 
meanwhile ArangoDB 3.1.28 was released, can you upgrade and check whether this is still reproducible?

**Comment by maxkernbach** [comment] 2018-02-12 13:26
Hi @nicolaselkhoury,

closing this issue for now because we have not received any feedback for a few months. Please reopen this issue if it persists with current versions.

Thanks

**Closed by maxkernbach** 2018-02-12 13:26 UTC
Labels: 1 Bug, 3 Cluster, Waiting User Reply
