### ISSUE TITLE
Using DOCUMENT() to get a different collection's document inside a modification FOR loop of a collection doesn't work as expected

### ISSUE THREAD

**Issue by lostpebble** [arangodb/arangodb#11858] opened 2020-06-12 11:17 UTC
## My Environment

* __ArangoDB Version__:        3.6.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Oasis (OneShard)

## Component, Query & Data

*Copying my messages sent on the Slack channel*

> I have the following query in AQL. I'd like to update a property geoLvlShort on all documents in the geolevel_za_populations collection:

```
FOR geoPop IN geolevel_za_populations
  LET gl = DOCUMENT("geolevel_za_v2", geoPop._key)
  LET short = gl.geoLvlShort
  //RETURN { geoLvlShort: short  }
  UPDATE geoPop WITH { geoLvlShort: short } IN geolevel_za_populations
```

The property geoLvlShort is currently null on each document inside the geolevel_za_populations collection.

This query doesn't seem to do anything. The property remains null - even though I know for sure that `gl.geoLvlShort` is returning a string value (If I uncomment the return statement there, we are getting a table full of correct `geoLvlShort` values).

I'm kinda stumped as to what's going on here? It feels a bit unexpected.. surely my call to UPDATE the geoPop document should overwrite the value at geoLvlShort instead of doing nothing?

---

> Very strangely enough - this worked!

```
FOR geoPop IN geolevel_za_populations
  LET gl = FIRST(FOR geoLvl IN geolevel_za_v2 FILTER geoLvl._key == geoPop._key RETURN geoLvl)
  LET short = gl.geoLvlShort
  // RETURN short
  UPDATE geoPop WITH { geoLvlShort: short } IN geolevel_za_populations OPTIONS { keepNull: false }
  RETURN NEW
```

It seems that using the `DOCUMENT()` notation confused ArangoDB.

---

## Profiles of queries

Profile for the query that **failed** to update correctly:

```
Query String (263 chars, cacheable: false):
 FOR geoPop IN geolevel_za_populations
    LET gl = DOCUMENT("geolevel_za_v2", geoPop._key)
    LET short = gl.geoLvlShort
    // RETURN short
    UPDATE geoPop WITH { geoLvlShort: short } IN geolevel_za_populations OPTIONS { keepNull: false }
    RETURN NEW
Execution plan:
 Id   NodeType          Site  Calls   Items   Runtime [s]   Comment
  1   SingletonNode     DBS       1       1       0.00000   * ROOT
 16   IndexNode         DBS       1     240       0.00045     - FOR geoPop IN geolevel_za_populations   /* primary index scan, index only, projections: `_key`, 1 shard(s) */    
  3   CalculationNode   DBS       1     240       0.00180       - LET gl = DOCUMENT("geolevel_za_v2", geoPop.`_key`)   /* simple expression */   /* collections used: geoPop : geolevel_za_populations */
  5   CalculationNode   DBS       1     240       0.00015       - LET #5 = { "geoLvlShort" : gl.`geoLvlShort` }   /* simple expression */
  6   UpdateNode        DBS       1     240       0.01167       - UPDATE geoPop WITH #5 IN geolevel_za_populations 
 10   RemoteNode        COOR      2     240       0.00262       - REMOTE
 11   GatherNode        COOR      2     240       0.00019       - GATHER   /* parallel */
  7   ReturnNode        COOR      2     240       0.00000       - RETURN $NEW
Indexes used:
 By   Name      Type      Collection                Unique   Sparse   Selectivity   Fields       Ranges
 16   primary   primary   geolevel_za_populations   true     false       100.00 %   [ `_key` ]   *
  6   primary   primary   geolevel_za_populations   true     false       100.00 %   [ `_key` ]   geoPop
Optimization rules applied:
 Id   RuleName
  1   remove-unnecessary-calculations
  2   remove-data-modification-out-variables
  3   patch-update-statements
  4   distribute-in-cluster
  5   scatter-in-cluster
  6   remove-unnecessary-remote-scatter
  7   undistribute-remove-after-enum-coll
  8   reduce-extraction-to-projection
  9   parallelize-gather
Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          true
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        false
 useIsRestore             false
 consultAqlWriteFilter    false
 exclusive                false
 overwrite                false
 ignoreRevs               true
Query Statistics:
 Writes Exec   Writes Ign   Scan Full   Scan Index   Filtered   Exec Time [s]
         240            0           0          240          0         0.02736
Query Profile:
 Query Stage           Duration [s]
 initializing               0.00000
 parsing                    0.00008
 optimizing ast             0.00001
 loading collections        0.00000
 instantiating plan         0.00002
 optimizing plan            0.00354
 executing                  0.01693
 finalizing                 0.00677
```

Profile of the query that worked:

```
Query String (291 chars, cacheable: false):
 FOR geoPop IN geolevel_za_populations
   LET gl = FIRST(FOR geoLvl IN geolevel_za_v2 FILTER geoLvl._key == geoPop._key RETURN geoLvl)
   LET short = gl.geoLvlShort
   // RETURN short
   UPDATE geoPop WITH { geoLvlShort: short } IN geolevel_za_populations OPTIONS { keepNull: false }
   RETURN NEW
Execution plan:
 Id   NodeType                  Site  Calls   Items   Runtime [s]   Comment
  1   SingletonNode             DBS       1       1       0.00000   * ROOT
  2   EnumerateCollectionNode   DBS       1     240       0.00051     - FOR geoPop IN geolevel_za_populations   /* full collection scan, 1 shard(s) */
  8   SubqueryNode              DBS       1     240       0.00418       - LET #2 = ...   /* subquery */
  3   SingletonNode             DBS     240     240       0.00020         * ROOT
 15   IndexNode                 DBS     240     240       0.00264           - FOR geoLvl IN geolevel_za_v2   /* primary index scan, 1 shard(s) */    
 14   LimitNode                 DBS     240     240       0.00039             - LIMIT 0, 1
  7   ReturnNode                DBS     240     240       0.00046             - RETURN geoLvl
 11   CalculationNode           DBS       1     240       0.00035       - LET #10 = { "geoLvlShort" : FIRST(#2).`geoLvlShort` }   /* simple expression */
 12   UpdateNode                DBS       1     240       0.01254       - UPDATE geoPop WITH #10 IN geolevel_za_populations 
 16   RemoteNode                COOR      2     240       0.00338       - REMOTE
 17   GatherNode                COOR      2     240       0.00025       - GATHER 
 13   ReturnNode                COOR      2     240       0.00000       - RETURN $NEW
Indexes used:
 By   Name      Type      Collection                Unique   Sparse   Selectivity   Fields       Ranges
 15   primary   primary   geolevel_za_v2            true     false       100.00 %   [ `_key` ]   (geoLvl.`_key` == geoPop.`_key`)
 12   primary   primary   geolevel_za_populations   true     false       100.00 %   [ `_key` ]   geoPop
Optimization rules applied:
 Id   RuleName
  1   remove-unnecessary-calculations
  2   optimize-subqueries
  3   remove-data-modification-out-variables
  4   use-indexes
  5   remove-filter-covered-by-index
  6   remove-unnecessary-calculations-2
  7   cluster-one-shard
Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          true
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        true
 useIsRestore             false
 consultAqlWriteFilter    false
 exclusive                false
 overwrite                false
 ignoreRevs               true
Query Statistics:
 Writes Exec   Writes Ign   Scan Full   Scan Index   Filtered   Exec Time [s]
         240            0         240          240          0         0.03690
Query Profile:
 Query Stage           Duration [s]
 initializing               0.00000
 parsing                    0.00011
 optimizing ast             0.00001
 loading collections        0.00001
 instantiating plan         0.00003
 optimizing plan            0.00798
 executing                  0.02126
 finalizing                 0.00747
```

**Comment by maxkernbach** [comment] 2020-06-25 11:15
Hi @lostpebble,

Thanks for reporting, this seems to be a bug.

The described behavior (`DOCUMENT()` resulting in a `null` value of `geoLvlShort` in the **geolevel_za_populations** collection) occurs in any cluster deployment. It is not limited to Oasis OneShard.

In a single server deployment both queries update the `geoLvlShort` field as expected, whether `LET gl = DOCUMENT("geolevel_za_v2", geoPop._key)` or `LET gl = FIRST(FOR geoLvl IN geolevel_za_v2 FILTER geoLvl._key == geoPop._key RETURN geoLvl)` is used.

Attached is a small database dump that reproduces this issue: [dump.zip](https://github.com/arangodb/arangodb/files/4830834/dump.zip)

We will look into this issue and get back to you.

**Comment by markuspf** [comment] 2020-06-25 14:33
Hi. 

I believe I found the bug, if you need a temporary workaround for this query, try using `{optimizer: { rules: ["-undistribute-remove-after-enum-coll"] } }`; fix to be available soon.

**Comment by lostpebble** [comment] 2020-06-25 15:04
Great! Thanks for the workaround - I ended up just using the filter method for now, as technically I assume its optimized in the same way as a regular `DOCUMENT()` get? In any case, I no longer need the query I was running which hit the issue.

**Comment by markuspf** [comment] 2020-06-25 15:18
There are some subtle differences in the execution: The `DOCUMENT` solution does not use any subqueries, whereas your filter method does; subqueries are more expensive to execute.

**Comment by markuspf** [comment] 2020-06-29 15:12
Note that the fix for this issue has just been merged (and backports to previous arangodb releases are pending), so this problem should be fixed with future releases.

**Closed** 2020-06-29 15:11 UTC
Labels: 1 Bug, 3 AQL, 3 Optimizer
