### ISSUE TITLE
Different result sets depending on no index, index and arrayindex

### ISSUE THREAD

**Issue by defvoid** [arangodb/arangodb#1629] opened 2015-12-22 12:32 UTC
OS: `Linux Arch x86_64`

ArangoDB: `2.8.0-beta2`

## Description

I noticed some IMO weird behaviour when playing around with array indices.

First of all AQL does not return what I actually expect it to, coming from other database systems :)

Secondly, queries 3 & 5 (see below) return different result sets depending on what indices is in the collection. Is this a bug?

## Test

Full test script can be found [here](https://gist.github.com/defvoid/441a9205a39e8bb3ca28)

```
db._create('test');
db.test.save({ _key: "1", value: "foo" });
db.test.save({ _key: "2", value: [ "foo", "bar" ] });
```

> Notice that the expected result is what I personally would expect.

#### Testing without indices;

1. FOR t IN test RETURN t._key
> PASSED -- expect: 1,2 actual: 1,2

2. FOR t in test FILTER t.value IN [ "foo" ] RETURN t._key
> FAILED -- expect: 1,2 actual: 1

3. FOR t in test FILTER "foo" IN t.value RETURN t._key
> FAILED -- expect: 1,2 actual: 2

4. FOR t in test FILTER t.value[*] IN [ "foo" ] RETURN t._key
> FAILED -- expect: 1,2 actual:

5. FOR t in test FILTER "foo" IN t.value[*] RETURN t._key
> PASSED -- expect: 1,2 actual: 1,2

#### Testing with index; value

1. FOR t IN test RETURN t._key
> PASSED -- expect: 1,2 actual: 1,2

2. FOR t in test FILTER t.value IN [ "foo" ] RETURN t._key
> FAILED -- expect: 1,2 actual: 1

3. FOR t in test FILTER "foo" IN t.value RETURN t._key
> FAILED -- expect: 1,2 actual:

4. FOR t in test FILTER t.value[*] IN [ "foo" ] RETURN t._key
> FAILED -- expect: 1,2 actual:

5. FOR t in test FILTER "foo" IN t.value[*] RETURN t._key
> PASSED -- expect: 1,2 actual: 1,2

#### Testing with index; value value[*]

1. FOR t IN test RETURN t._key
> PASSED -- expect: 1,2 actual: 1,2

2. FOR t in test FILTER t.value IN [ "foo" ] RETURN t._key
> FAILED -- expect: 1,2 actual: 1

3. FOR t in test FILTER "foo" IN t.value RETURN t._key
> FAILED -- expect: 1,2 actual:

4. FOR t in test FILTER t.value[*] IN [ "foo" ] RETURN t._key
> FAILED -- expect: 1,2 actual:

5. FOR t in test FILTER "foo" IN t.value[*] RETURN t._key
> FAILED -- expect: 1,2 actual: 2

**Comment by CoDEmanX** [comment] 2015-12-22 13:46
**Without indexes**

2: Your query is wrong if you want to check if "foo" is in `t.value`. What it does is search for documents whose `t.value` attribute is contained in `["foo"]` and `["foo", "bar"]` is not. Document 2 would match if you queried `FOR t IN test FILTER t.value IN [["foo", "bar"]]`, but you would probably rather write it as `t.value == ["foo", "bar"]`.

3: Your query checks if "foo" is contained in `t.value`, and for document 2 it is true (it is actually an array with a string element "foo"). Document 1 does not match, because `t.value` is not an array. It would match if you stored it like `value: ["foo"]`. In Python, it would result in the following pseudo-condition for document 1: `"foo" IN ["f", "o", "o"]`. In AQL however, there is no iteration over the string. Thus, even `"f" IN t.value` won't match. You achieve the desired result, ensure that `t.value` is an array: `FOR t IN test FILTER "foo" IN TO_ARRAY(t.value) RETURN t._key`.

4: `t.value[*]` is `["foo"]` for doc 1 and `["foo", "bar"]` for doc 2. The latter is not contained in `["foo"]`, see my number 2 above.

5: Because `[*]` turns `"foo"` into `["foo"]` in case of document 1, the query actually works - and it's an alternative to my suggestion in 3 (TO_ARRAY).

**With indexes**

Quite interesting that query 3 returns a different result if there are indexes. I think I have a rough idea how this happens, but either the regular index or the array index should make it return the correct result still...

Query 5 with an array index might fail, because `t.value[*]` doesn't cast `t.value` to an array, because `[*]` has a different meaning/purpose in presence of an array index. Maybe it's a bad idea to rely on the casting behavior and use an explicit cast `TO_ARRAY()` instead as mentioned earlier. But then the array index might not be (fully?) utilized. Your best option is to change your data model, so the `value` attribute is always an array: `value: ["foo"]`. The array index will then include it and can be used to speed up the query.

**Comment by defvoid** [comment] 2015-12-22 16:31
Thank you for a good response @CoDEmanX!

In regards to the different result sets, depending on index, I think an index purpose is only to speed things up and should never ever change the way the result is returned. In a perfect system (where indices are still needed) the indices are created automagically when the system itself has concluded that one is needed, depending on various thing. Would you not agree?

I thought the arrayindex would be able to enable and speed up queries where i.e. you want to return documents where `tags` `CONTAINS` `SOME` value(s) from another array.

After running some more tests, with an array only data model, it seems the arrayindex is only used in `FILTER "foo" IN tags`. Using `TO_ARRAY`, `INTERSECTION` or `LET <sub-query>` works for some scenarios but the arrayindex is **not** used so that does not help speed things up.

Maybe we need `SOME` more AQL functions for these kind of things?

**Comment by CoDEmanX** [comment] 2015-12-22 17:27
I agree that the DBMS shouldn't let you run into situations easily, in which an index makes the result set incomplete. I do understand the technical reasons, why this can happen, but I'm not particularly happy about it.

AFAIK array indexes are meant to find one element in the bowl of all individually indexed array elements (or rather the containing documents), e.g. `"foo"` in an attribute `value`, which must be an array with zero, one or multiple elements. In which position an array element `"foo"` occurs in the documents doesn't matter. 

Without array index, every `value` needs to be checked (individual comparison of the array elements), whereas Arango can figure out the right documents by only looking at the index if there is one for arrays. Everything that isn't added to the index (non-array elements) cannot be found if the index is used.

Related:
http://stackoverflow.com/a/27938317/2044940 (see my comment)
https://github.com/arangodb/arangodb/issues/1502

I think there is one more discussion around how to check if (at least) the elements of array A are also in array B.

**Comment by jsteemann** [comment] 2015-12-23 15:17
I agree that the existence or non-existence of an index should not change the result set returned by the server (that is, apart from result set order if a query does not specify the `SORT` explicitly).

Regarding the queries, I think @CoDEmanX has answered it already, but I repeat what the expected behavior is (expected from the viewpoint of how the operators work in AQL):

* `FOR t in test FILTER t.value IN [ "foo" ] RETURN t._key`: this should only return the document with _key `1`, as `"foo" IN [ "foo" ]` is true, but `[ "foo", "bar" ] IN [ "foo" ]` is not.
* `FOR t in test FILTER "foo" IN t.value RETURN t._key`: this should return the document with key `2`, as `"foo" IN "foo"` is false, but `"foo" IN [ "foo", "bar" ]` is true.
* `FOR t in test FILTER t.value[*] IN [ "foo" ] RETURN t._key`: this should return no documents, as `"foo"[*] IN [ "foo" ]` is false, and `[ "foo", "bar" ][*] IN [ "foo" ]` is also false.
* `FOR t in test FILTER "foo" IN t.value[*] RETURN t._key`: this should return just document with _key `2`, as `"foo" IN "foo"[*]` is false, but `"foo" IN [ "foo", "bar" ][*]` is true.

The are a few things here that were probably confusing here are:
* we spotted an inconsistent behavior for the `[*]` operator between using it in indexes and elsewhere in AQL. For example, `"foo"[*]` produced `[ "foo" ]` when not used in conjunction with an index, but when using it for an index definition it produced an empty array (`[ ]`) and thus no index entries. That behavior was unified in latest 2.8 so it's consistent: using the `[*]` operator on a non-array value will now always produce an empty array, and not automagically convert the value to an array. That inconsistency was also the reason for why queries returned different values depending on whether indexes were defined or not. This should be fixed in latest 2.8 and devel.
- `IN` in ArangoDB compares the left-hand operand against each member of the right-hand array operand. It requires its right-hand operand to be an array. If the right-hand operand is a non-array, then the result of `IN` is always false. This is the case e.g. for `"foo" IN "foo"` (= false), which only works when written as `"foo" IN [ "foo" ]`. Vice versa, `[ "foo" ] IN [ "foo" ]` is also false, because the left-hand value `[ "foo" ]` is not a member of the right-hand array (it equals the right-hand value, but the `IN` operator` compares the left-hand value to each member of the right-hand value).
* it may be different elsewhere (e.g. MongoDB), where searching for `{ value: "foo" }` will find both `{ value: "foo" }` and `{ value: [ "foo", "bar" ] }`.

Because the array index relies on `[*]`, it will only include values from an array attribute value, and will not index other values (e.g. simple string values such as `"foo"`.
An array index will not be used for filter conditions such as `FILTER doc.value == @value` or `FILTER doc.value IN @value`. The only filter variant that can make use of the array index is `FILTER @value IN doc.value`.
For non-array hash and skiplist indexes, the triggering variants are still `FILTER @value IN doc.value` and `FILTER @value operator doc.value` AND `FILTER doc.value operator @value`.

I think the behavior of the operators is now consistent, so that queries return the same values regardless of (array) indexes are present or not.
What would be helpful in order to support more queries and use cases are probably some operators that compare the values of two arrays, e.g.
- `[ "foo", "bar" ] ANY IN [ "foo", "baz" ]`: could compare all elements from the left-hand array against all elements from the right-hand array and returns true if there's at least one match, false otherwise. That's the same as the `CONTAINS` operator mentioned above by @defvoid. We probably cannot name an operator `CONTAINS` because there is already an AQL function of the same name, but the idea is the same.
- `[ "foo", "bar" ] ALL IN [ "foo", "baz" ]`: could compare all elements from the left-hand array against all elements from the right-hand array and returns true if there's at least one match, false otherwise.

And maybe the optimizer could make use of array indexes in more cases than it does now.
Any suggestions for that and the operators are highly welcome!

**Comment by defvoid** [comment] 2015-12-27 16:15
The operators `ANY`and `ALL` would be great, although I think you mean `ALL` would return true if all elements in the left-hand array exists in the right-hand array(?).

How about checking if none in the left-hand array is in the right-hand array?

1. `<array> [NOT] ANY|ALL IN <array>`
2. `<array> ANY|ALL [NOT] IN <array>`
3. `[NOT] <array> ANY|ALL IN <array>`
4. `ANY|ALL <array> [NOT] IN <array>`
5. `<array> ANY|ALL|NONE IN <array>`

I think number four is the most appealing when I look at it.

**Comment by jsteemann** [comment] 2015-12-29 16:51
@defvoid : you're right, I made a mistake in my explanation of `ALL` and your correction of it is what I had intended to write.

A quick test with the grammar reveals that variants 1, 2, 3, and 5 do work parser-wise. For variant 5 there would need to be an extra `NONE` keyword of course. 
Variant 4 is causing reduce-reduce conflicts, so it would need refactoring of the grammar.

**Comment by defvoid** [comment] 2015-12-29 18:30
Cool! I figured 4 would involve more work (since I liked that one, haha). Runner ups are 2 and 5, IMO.

Which one do you guys (users of ArangoDB) prefer?

**Comment by dothebart** [comment] 2016-01-04 14:48
Theme drift. Since the bug is fixed meanwhile, relabeling.

**Comment by CoDEmanX** [comment] 2016-02-03 19:34
`NONE IN` is actually equivalent to `NOT ANY IN` / `ANY NOT IN`, but by far more natural and understandable. The inversion of `ANY IN` is a bit of a brain twister. A Borat-style variant would be funny though: `<array> ANY IN <array> ... NOT!`. Slightly better, but still worse than `NONE IN`: `<array> ANY NOT IN <array>`.

`NOT ALL IN` is a bit tricky: "not all in" might be misread as "one or more in" (=ANY IN), which is contrary to a logical negation of `all in`. It needs to be read as `not(all in)` (one or more in, but not all). Another potential fallacy is to think that `NOT ALL IN` would be equal to `NONE IN`, because *all* and *none* are antonyms:

 [1,2,3] ... IN | [1,2,3] | [2,4] | [5] | Comment
---|---|---|---|---
ALL | true | false | false |
NOT ALL | false | **true** | true | 
NONE | false | **false** | true | behavior different compared to NOT ALL 
NOT ANY | false | false | true | same as NONE
ANY | true | true | false |
NOT NONE | true | true | false | same as ANY

Conclusion: the negations `NOT ANY IN` and `NOT NONE IN` are hard to understand and redundant, and don't really need to be supported. On the other hand, there's no alternative to `NOT ALL IN` behavior-wise, and thus this negation needs to be supported. 

So there are 4 possible operations, to test if...
1. all of the elements in array A are included in array B (array B may contain more elements though)
2. any of the elements (one or more) in array A are included in array B
3. none of the elements in array A is contained in array B
4. array B does not contain all elements, that array A has (NOT ALL IN; array B may optionally contain more elements though)

Another possible operation a user might want perform is to test if array B has all elements array A has, but not any others. Examples:

```
[1,2,3] -> [1,2,3] = true
[1,2,3] -> [1,2,3,4] = false
[1,2,3] -> [1,2,4] = false
[1,2,3,1] -> [1,2,1,2,3] = true
```
This can be achieved by `<arrayA> ALL IN <arrayB> AND <arrayB> ALL IN <arrayB>`. A shorthand `ONLY IN` could be introduced: `<arrayA> ONLY IN <arrayB>`. It may not be a common use case however. Even lesser `NOT ONLY IN` to check if array B contains all elements of array A and at least one additional element.

Yet another operation I can think of: "n out of m", for example `[1,2,3] 2 IN [1,2,4,5] == true` (two out of three elements of array A are included in array B). Because array A and B may have a varying numbers of elements, support for relative amounts could be useful: `[1,2,3,4] 75% IN [...]` (here: at least 3 elements of array A must be contained in array B). If one additionally introduced weighting for the array elements, we would enter the field of fuzzy sets and sophisticated information retrieval. But I guess such scoring is beyond the scope of (vanilla) AQL.

**Comment by Simran-B** [comment] 2016-02-11 19:55
Array operators landed in devel:

* added AQL array comparison operators 

  All AQL comparison operators now lso exist in an array variant. In the 
  array variant, the operator is prefixed with one of the keywords *ALL*, *ANY*
  or *NONE*. Using one of these keywords changes the operator behavior to
  execute the comparison operation for all, any, or none of its left hand 
  argument values. It is therefore expected that the left hand argument
  of an array operator is an array.

  Examples:

      [ 1, 2, 3 ] ANY IN [ 4, 5, 6 ]   // false
      [ 1, 2, 3 ] ANY IN [ 1, 42 ]     // true
      [ 1, 2, 3 ] ALL IN [ 2, 3, 4 ]   // false
      [ 1, 2, 3 ] ALL IN [ 1, 2, 3 ]   // true
      [ 1, 2, 3 ] NONE IN [ 3 ]        // false
      [ 1, 2, 3 ] NONE IN [ 23, 42 ]   // true
      [ 1, 2, 3 ] ANY == 2             // true
      [ 1, 2, 3 ] ANY == 4             // false
      [ 1, 2, 3 ] ANY > 0              // true
      [ 1, 2, 3 ] ANY <= 1             // true
      [ 1, 2, 3 ] ALL > 2              // false
      [ 1, 2, 3 ] ALL > 0              // true
      [ 1, 2, 3 ] ALL >= 3             // false
      [ 1, 2, 3 ] NONE < 99            // false
      [ 1, 2, 3 ] NONE > 10            // true
      ["foo", "bar"] ALL != "moo"      // true
      ["foo", "bar"] NONE == "bar"     // false

As you can see, it's not only possible to compare two arrays, but also to compare the elements of an array to a single string, number etc.

Negations a la `NOT ALL IN` are not supported. Something like `NOT([1,2,3] ALL IN [...])` does work however. If you leave out the parens, NOT negates `[1,2,3]` (!true, so false) and filters out all documents, giving you an empty result - probably not what you want. So keep that in mind.

**Closed by Simran-B** 2016-02-11 19:55 UTC
Labels: 3_Feature, aql
