### ISSUE TITLE
Arangodb crashes when other process take more memory in linux

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#2268] opened 2017-01-13 08:07 UTC
Dear team,
  We are using Arangodb 3.1.2 in rhel 6.6.
 
When we run some high memory utilizing programs, the DB crashes.

Is there any way this can be avoided?

Regards,
Sajeev

**Comment by baslr** [comment] 2017-01-13 15:29
Disable Linuxs oom killer or run the program on a stand alone server.

This is not a bug this is by design. If Linux, the kernel, needs more ram as being available it kills processes to gain free ram.

**Comment by sajeevpr** [comment] 2017-01-14 13:51
@baslr , Thank you for the response. we will try these options.

**Comment by sajeevpr** [comment] 2017-01-20 01:28
@baslr, if we run only Arangodb process in a linux machine of RAM 192 GB and database size of 300 GB with all collections loaded, will it crash?

**Comment by baslr** [comment] 2017-01-20 07:55
ArangoDB wont crash, but at some point linux has do drop pages with already mapped datafiles to map unmapped datafiles into the ram. If a query needs documents that are not longer mapped in ram expect degraded performance.

**Comment by sleto-it** [comment] 2017-11-06 21:08
Hi @sajeevpr,

Is there anything else we can do to help you more with this ticket - or can we consider it solved?

Thanks,

**Comment by sleto-it** [comment] 2017-11-16 09:52
Hi,

We haven't received any recent feedback on this ticket. I am closing it now. Please comment if you have any other questions and we will reopen it

Many thanks,

**Closed by sleto-it** 2017-11-16 09:52 UTC
Labels: 1 Question, Waiting User Reply
