### ISSUE TITLE
request module slow down on 204 responses

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1962] opened 2016-07-24 20:30 UTC
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [x] 2.8

On this operating system:
- [x] MacOS, version:

I have an nginx server that returns status 204 ("No Content") on any type of request. When using `require('org/arangodb/request').head('http://myserver', {})` everything is fine and fast, but when making another type of request like get or post, the request takes super long to complete. On my machine, it takes exactly 5s every time.

Changing the config of the server to return a short string like "OK" with status 200, the request is fast.

If I were to guess without looking at the code, I'd say request has an internal default timeout of 5s and doesn't understand the meaning of a 204 response.

**Comment by pekeler** [comment] 2016-07-24 20:36
No, 5s is the default `keepalive_timeout` setting of nginx. So it seems request doesn't close the connection.

This is what request returns after 5s:

```JSON
{ "statusCode" : 204, "status" : 204, "message" : "No Content", "headers" : { "connection" : "keep-alive", "date" : "Sun, 24 Jul 2016 20:33:05 GMT", "http/1.1" : "204 No Content", "server" : "nginx/1.10.1" }, "rawBody" : [Object { "length" : 0 }], "body" : "" }
```

**Comment by jsteemann** [comment] 2016-07-25 08:01
I guess this is caused by nginx not setting the "content-length" header.

**Comment by jsteemann** [comment] 2016-07-25 08:16
Confirmed. If a response is missing the "Content-Length" header, the request module will choke on this.

**Comment by jsteemann** [comment] 2016-07-25 08:22
Suggested fix:
```diff
diff --git a/lib/SimpleHttpClient/SimpleHttpResult.cpp b/lib/SimpleHttpClient/SimpleHttpResult.cpp
index ade99a9..ef164c7 100644
--- a/lib/SimpleHttpClient/SimpleHttpResult.cpp
+++ b/lib/SimpleHttpClient/SimpleHttpResult.cpp
@@ -151,6 +151,13 @@ namespace triagens {
                 (value[2] >= '0' && value[2] <= '9')) {
               // set response code
               setHttpReturnCode(100 * (value[0] - '0') + 10 * (value[1] - '0') + (value[2] - '0'));
+
+              if (_returnCode == 204) {
+                // HTTP 204 = No content. Assume we will have a content-length of 0.
+                // note that will value can be overridden later if the response has the content-length
+                // header set to some other value
+                setContentLength(0);
+              }
             }
          
             if (valueLength >= 4) {
```

**Comment by jsteemann** [comment] 2016-07-25 09:50
204 responses without `Content-Length` header are now properly handled by the request module.

**Comment by jsteemann** [comment] 2016-08-02 14:28
Should be fixed in 3.0.4, which was released today.

**Comment by baslr** [comment] 2017-02-09 17:07
@pekeler can you confirm its no more slowing down?

**Comment by dothebart** [comment] 2017-07-21 11:47
We're pleased to anounce that ArangoDB 3.2 containing lots of improvements and the Rocksdb Storage Engine. 
Since there has been no activity to this ticket I will close this now.

**Closed by dothebart** 2017-07-21 11:47 UTC
Labels: 1 Bug, 2 Fixed, 3 Core
