### ISSUE TITLE
truncate collection error

### ISSUE THREAD

**Issue by stuxuhai** [arangodb/arangodb#3601] opened 2017-11-07 07:49 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [x] other: CentOS 6
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[x] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [x] arangosh
- [ ] this Driver:

exception log:
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 98,7: ArangoError 1473: could not truncate collection
!      throw error;
!      ^
stacktrace: ArangoError: could not truncate collection
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:96:21)
    at ArangoCollection.truncate (/usr/share/arangodb3/js/client/modules/@arangodb/arango-collection.js:480:12)
    at <shell command>:1:14

**Comment by dothebart** [comment] 2017-11-21 16:57
Hi, 
we found a cause for this issue regarding that the frontend wouldn't be patient enough for the dbservers executing the truncation process of the shards. 
With ArangoDB 3.2.8 this timeout was increased, so most probably you shouldn't get this error anymore after an upgrade of your installation. 

We will however also work on the performance itself (as you noted in #3631 )

So I will mark this as a duplicate of #3631 and close it.

**Closed by dothebart** 2017-11-21 16:57 UTC
Labels: 3 Cluster
