### ISSUE TITLE
Bi-directional cursor

### ISSUE THREAD

**Issue by Mangatt** [arangodb/arangodb#10253] opened 2019-10-15 04:35 UTC
Not a bug, but feature request - it would be nice for AQL to support bi-directional cursors, e.g. loading after/before certain item in results.

Maybe something like this:
```
FOR u IN users
    LIMIT 5 AFTER 'last-user-id'
    RETURN u
```

**Comment by mpoeter** [comment] 2020-09-03 09:05
Closing as duplicate of #10413

**Closed by mpoeter** 2020-09-03 09:05 UTC
Labels: 1 Feature, 3 AQL
