### ISSUE TITLE
database's VERSION file disappears after restarting Linux Box

### ISSUE THREAD

**Issue by msukhov** [arangodb/arangodb#2275] opened 2017-01-16 17:02 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an installation-related issue:
I've noticed the issue that arangodb won't start after creating new database and restarting the linux box. This issue happens very often but not permanent. I'm using CentOS 6 installed in OpenVZ v6 container.

Steps to reproduce:
1) Install arangodb
`$ yum install arangodb3`

2) change the root password from shell with 
`$ arango-secure-installation`

3) change endpoint of arangodb to "tcp://0.0.0.0:8529" by editing /etc/arangodb3/arangod.conf

4) exit the system and restart container:
`$ exit`
`$ vzctl restart CTID`

5) Open Web Admin Panel from other PC in local network

6) Create new user and database from Web Admin Panel

7) restart container with ArangoDB instance once again:
`$ vzctl restart CTID`

After these steps arangodb service won't starts because VERSION file of new database could not be found on the disk. arangod.log contains this error:
`FATAL Database version check failed for 'DBNAME'. Please inspect the logs for any errors`

One more minor issue:
After i try to start servise manually:
`/etc/init.d/arangodb3 start`

The script outs next line:
`database version check failed, maybe need to run 'upgrade'?`

If i try `upgrade` option for start script, it outs next error:
`unknown option '--upgrade'`
`Please note that the specified option '--upgrade' has been renamed to '--database.auto-upgrade' in this ArangoDB version`

**Comment by dothebart** [comment] 2017-02-14 14:19
Hi, 
sorry to come back on you so late.
Did you actually install 3.0? or 3.1? If 3.0 - why didn't you install 3.1? 
We currently don't have any OpenVZ enabled system around. Can you also reproduce this using docker containers?

**Comment by dothebart** [comment] 2017-03-01 16:19
Hi, is this still an issue?

**Comment by msukhov** [comment] 2017-03-10 13:57
Sorry for silence...

Yes this issue is actual for current version. I'm just reproduce it with fresh installation.

Please see the arangod log file:
```2017-03-10T13:43:48Z [542] INFO ArangoDB 3.1.13 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.1e-fips 11 Feb 2013
2017-03-10T13:43:48Z [542] INFO file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2017-03-10T13:43:48Z [542] INFO JavaScript using startup '/usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
2017-03-10T13:43:50Z [577] INFO ArangoDB 3.1.13 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.1e-fips 11 Feb 2013
2017-03-10T13:43:50Z [577] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
2017-03-10T13:43:50Z [577] INFO Starting up with role SINGLE
2017-03-10T13:43:50Z [577] INFO Authentication is turned on
2017-03-10T13:43:50Z [577] INFO Authentication system only
2017-03-10T13:43:50Z [577] INFO Authentication for unix sockets is turned on
2017-03-10T13:43:50Z [577] INFO file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2017-03-10T13:43:51Z [577] INFO JavaScript using startup '/usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
2017-03-10T13:43:52Z [577] INFO using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
2017-03-10T13:43:52Z [577] INFO ArangoDB (version 3.1.13 [linux]) is ready for business. Have fun!
2017-03-10T13:45:11Z [577] INFO created application directory '/var/lib/arangodb3-apps/_db/data' for database 'data'
2017-03-10T13:45:42Z [577] INFO control-c received, beginning shut down sequence
2017-03-10T13:45:42Z [577] FATAL control-c received (again!), terminating
2017-03-10T13:45:50Z [543] INFO ArangoDB 3.1.13 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.1e-fips 11 Feb 2013
2017-03-10T13:45:50Z [543] INFO file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2017-03-10T13:45:51Z [543] INFO running WAL recovery (2 logfiles)
2017-03-10T13:45:51Z [543] INFO replaying WAL logfile '/var/lib/arangodb3/journals/logfile-148.db' (1 of 2)
2017-03-10T13:45:52Z [543] INFO replaying WAL logfile '/var/lib/arangodb3/journals/logfile-149.db' (2 of 2)
2017-03-10T13:45:52Z [543] INFO WAL recovery finished successfully
2017-03-10T13:45:52Z [543] INFO JavaScript using startup '/usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
2017-03-10T13:45:54Z [543] FATAL Database version check failed for 'data'. Please inspect the logs for any errors
```

Here is a directory listing for `_system` database `ls -l /var/lib/arangodb3/databases/database-1/`:
```
-rw-r--r-- 1 arangodb arangodb  318 Mar 10 08:43 VERSION
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:41 collection-2-3645700337
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:41 collection-20-3107792296
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:41 collection-23-465447976
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:41 collection-36-3302844216
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:45 collection-38-2478561782
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:45 collection-44-3732163338
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:45 collection-49-3978118013
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:41 collection-54-2366224217
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:41 collection-56-584834147
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:41 collection-58-591021646
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:41 collection-6-420581795
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:41 collection-60-2823233842
-rw-r----- 1 arangodb arangodb   44 Mar 10 08:41 parameter.json
```

And this is a directory listing for `data` database `ls -l /var/lib/arangodb3/databases/database-307/`:
```
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:45 collection-309-4006215710
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:45 collection-311-2852101462
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:45 collection-313-1834351635
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:45 collection-326-2594539524
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:45 collection-328-3237622598
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:45 collection-330-210413576
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:45 collection-332-1620234966
drwxr-xr-x 2 arangodb arangodb 4096 Mar 10 08:45 collection-334-779859762
-rw-r----- 1 arangodb arangodb   43 Mar 10 08:45 parameter.json
```
No VERSION file found.

Parameters file content `cat /var/lib/arangodb3/databases/database-307/parameter.json`
```
{"deleted":false,"id":"307","name":"data"}
```

**Comment by msukhov** [comment] 2017-03-10 14:01
I think that the issue appers on following log lines:
```2017-03-10T13:45:42Z [577] INFO control-c received, beginning shut down sequence
2017-03-10T13:45:42Z [577] FATAL control-c received (again!), terminating```

At this moment I've restarted the OpenVZ container

**Comment by dothebart** [comment] 2017-03-20 15:02
hm, I was only able to achieve this by killing the service like this:

    kill $PID ; kill $PID

which I'd call rather rude. 
You should make sure that on shut down of the containers regular init scripts are executed and allow arangodb to shut down properly.

**Comment by jsteemann** [comment] 2017-03-20 15:56
This is probably due to virtualization. We have seen file systems in virtual machines behaving other than local file systems a few times before. For example, virtualization environments may defer writing to underlying physical file system way longer than "real" file systems, with writes being cached in temporary buffers and not being written to the actual file system. If the server then gets restarted, the only-cached writes would be lost.

Note that this is just a hypothesis at the moment.

**Comment by msukhov** [comment] 2017-03-20 18:37
I've check the host system setting for O_DIRECT writes. O_DIRECT disabled on the host for all virtual containers... So it may be the cause of issue, but no other similar issues are happens earlier.

I'll try to reproduce the issue with O_DIRECT and FSYNC globally enabled. Currently I've default values for these parameters.

**Comment by dothebart** [comment] 2017-07-27 08:51
@msukhov did this appear again for you? or did the O_DIRECT & FSYNC flags fix this for you?

**Comment by dothebart** [comment] 2017-09-25 12:52
Ok, seems its not reprocudeable. Closing for now. Feel free to comment if you can reproduce this.

**Closed by dothebart** 2017-09-25 12:52 UTC
Labels: 1 Bug, 3 Core, 4 OpenVZ
