### ISSUE TITLE
uWebsocket for most lightweight, efficient & scalable WebSocket & HTTP server implementation

### ISSUE THREAD

**Issue by ansarizafar** [arangodb/arangodb#2417] opened 2017-04-10 12:58 UTC
Please consider using [uWebsocket](https://github.com/uWebSockets/uWebSockets) for most lightweight, efficient & scalable WebSocket & HTTP server implementation.

**Comment by dothebart** [comment] 2017-04-11 11:27
Thanks for the pointers, interesting Project. However, I'd like to close this as a duplicate of #602

**Closed by dothebart** 2017-04-11 11:27 UTC
