### ISSUE TITLE
FILTER logic totally broke for my query in 3.4-rc4

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb#7522] opened 2018-11-29 09:09 UTC
I installed anrango 3.4-rc4 and some of my unit tests failed. While fixing some of them I found this bug:
DUMP: [debugDump.zip](https://github.com/arangodb/arangodb/files/2628340/debugDump.zip)

This is a reduced version of my query:
```
FOR orderedDish IN OrderedDish
FILTER 
  orderedDish._from == @target && 
  orderedDish.cart == @cart && 
  (!orderedDish.isOrdered || orderedDish.isCanceled)

RETURN {
  cartEntry: orderedDish,
  notOrdered: !orderedDish.isOrdered,
  canceled: orderedDish.canceled,
  wrong: orderedDish._from == @target && orderedDish.cart == @cart && (!orderedDish.isOrdered || orderedDish.isCanceled)
}
```
where the result is:

```
[
  {
    "cartEntry": {...},
    "notOrdered": false,
    "canceled": null,
    "wrong": false <--- THIS IS THE FILTER STATEMENT!!!
  }
]
```

checking the execution plan shows this:

```
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  7   IndexNode            2     - FOR orderedDish IN OrderedDish   /* edge index scan */
  8   CalculationNode      2       - LET #1 = (orderedDish.`cart` == "cartA")   /* simple expression */   /* collections used: orderedDish : OrderedDish */
  4   FilterNode           2       - FILTER #1
  5   CalculationNode      2       - LET #3 = { "cartEntry" : orderedDish, "notOrdered" : ! orderedDish.`isOrdered`, "canceled" : orderedDish.`canceled`, "wrong" : (((orderedDish.`_from` == "Client/62952180") && (orderedDish.`cart` == "cartA")) && (! orderedDish.`isOrdered` || orderedDish.`isCanceled`)) }   /* simple expression */   /* collections used: orderedDish : OrderedDish */
  6   ReturnNode           2       - RETURN #3
```

Looking at line 4 `4   FilterNode           2       - FILTER #1`  you can see that the filter statement is reduced in a wrong way.

**Comment by konsultaner** [comment] 2018-11-29 09:15
a quick fix is:

```
FOR orderedDish IN OrderedDish
LET a = orderedDish._from == @target
LET b = orderedDish.cart == @cart
LET c = (!orderedDish.isOrdered || orderedDish.isCanceled)
LET d = a&&b&&c
FILTER 
  a&&b&&c
RETURN {
  cartEntry: orderedDish,
  notOrdered: !orderedDish.isOrdered,
  canceled: orderedDish.canceled,
  wrong: orderedDish._from == @target && orderedDish.cart == @cart && (!orderedDish.isOrdered || orderedDish.isCanceled)
}
```

it does not work without `LET d = a&&b&&c`.

**Comment by jsteemann** [comment] 2018-11-29 15:53
Fixed by https://github.com/arangodb/arangodb/pull/7554

**Comment by konsultaner** [comment] 2018-12-03 14:59
why is 3.4.0-RC.5 released an this issue is not part of it? Or should it be closed?

**Comment by jsteemann** [comment] 2018-12-03 15:32
@konsultaner : what exactly do you mean when you say "this issue is not part of it"?
Do you mean the bugfix is not included in it? Do you have any evidence supporting this claim, i.e. did you try the query with 3.4.0-rc5 and checked the issue is still there? I am asking because I think the fix *is* included in 3.4.0-rc5.

**Comment by Simran-B** [comment] 2018-12-03 16:37
Please [get RC.5](https://www.arangodb.com/download-technical-preview/) if you haven't, make sure you access the right instance (e.g. in the web interface check the bottom left corner for the server version) and retry the query.

The team will go through all issues with milestone 3.4.0-RC.5 and close them in the next few days now that RC.5 is out. We label issues as _2 Fixed_ As soon as a fix is in place in the code, but we leave issues open until new binaries become available.

**Comment by konsultaner** [comment] 2018-12-04 09:18
@jsteemann @Simran-B I got it. I was confused by the comment

> Fixed by #7554

I thought it will auto close this issue. I didn't know that:

> The team will go through all issues with milestone 3.4.0-RC.5 and close them in the next few days now that RC.5 is out. We label issues as 2 Fixed as soon as a fix is in place in the code, but we leave issues open until new binaries become available.

I'll give it a try late on today. Thanks for the quick fix!

**Comment by maxkernbach** [comment] 2018-12-10 10:20
Hi @konsultaner,

did you already have a chance to try 3.4.0-RC.5?

**Comment by konsultaner** [comment] 2018-12-10 10:45
@maxkernbach sorry for not replying. yes, it did work. Thank you!

**Closed** 2018-12-10 10:45 UTC
Labels: 1 Bug, 2 Fixed, 3 AQL, Waiting User Reply
