### ISSUE TITLE
data reverts to an older state (happened several times)

### ISSUE THREAD

**Issue by dimitryvolkov** [arangodb/arangodb#3519] opened 2017-10-26 09:24 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X ] 3.2.0

Mode:
- [X ] Cluster
- [X ] Single-Server

Storage-Engine:
- [X ] mmfiles

On this operating system:
- [X ] Linux 
  - [X ] other: Ubuntu 16.04.2 LTS on AWS

This is a reoccurring issue I've had over a long time span, I have tried several ArangoDB installations (with 3.2.0 and previous versions), one where I have installed it directly, I have also used the one supplied on the AWS marketplace, I have attempted a cluster setup and a single server setup but this issue seems to appear again and again.

While I love using ArangoDB and have enjoyed it's many benefits in production, this issue puts that in risk.

As the subject line describes, I have found multiple occasions in which my data was reverted back to a specific date, the dataset itself is fairly simple and is comprised of a collection of simple objects, no graphs are involved.

I have a single API endpoint for modifying data which I have refrained from using during my testing time to rule out any user intervention and have used only data retrieval queries this whole time.

I couldn't find anything relating to that in my log files (though I'm running with default log options so I might be missing some logs).

I am aware that a similar issue (#3226) exists, looking at that, I see that unlike what was reported there, my filesystem is ext4 and my supervisor logs show no signals or apparent crashes.

**Comment by dothebart** [comment] 2017-10-27 12:00
Hi, 
do you use arangorestore with several databases on the same instance?

**Comment by dimitryvolkov** [comment] 2017-10-27 12:08
actually no, have never used arangorestore, I just manually edited the data when it was reverted.
Also I'm not running multiple databases on the same instance

**Comment by dimitryvolkov** [comment] 2017-10-29 13:25
The issue just occurred again for me, logs show nothing regarding a crash and there was no use over the weekend for the service, however, we did shutdown the server itself over the weekend, could this be the cause?
A bad shutdown?

**Comment by dothebart** [comment] 2017-11-07 13:48
Sorry to get back to you a little late. 
do you see whether the service is correctly shut down during the shutdown of the service? Which filesystem do you use? Ext4?

**Comment by dimitryvolkov** [comment] 2017-11-07 13:50
No problem, nothing seems out of the ordinary in my logs regarding shutdown.
And yes, I am using ext4

**Comment by georgekaf** [comment] 2017-11-15 12:53
Why is the filesystem relevant? 
It looks like #2437.

**Comment by dimitryvolkov** [comment] 2017-11-15 12:56
@georgekaf , please note the referenced issue describes a situation of multiple databases on the same server, and usage of arangodump and arangorestore, to which I have already replied that I wasn't using and that my case has a single database on a single server.

**Comment by dothebart** [comment] 2017-11-22 12:10
@dimitryvolkov if you look at the logfiles of arangodb, the brackets [xxxx] hold the PID of the process; on a restart these will most probably change. do you also see something in the supervisor log?

Can you update your system to 3.2.8 since we fixed memory leak related issues?

**Comment by sleto-it** [comment] 2017-12-05 18:02
Hi @dimitryvolkov ,

FYI version 3.2.9 has been released
It would be useful to know if you saw similar problems again, recently, with never versions?

I am sorry about this problem: we really would like to help you more
I am not aware of other users reporting similar problems
Seems a bit strange to me that you have the same issue on a cluster and standalone server

How did you start the cluster - and on many machines?
Are you able to reproduce the issue on your local machine (not AWS)?

Many Thanks,

**Comment by dothebart** [comment] 2018-04-26 14:35
I'm closing this as no reports have been on this issue for 5 months now. 
If it reoccurs and you have more details on this, comment and we will reopen this.

**Closed by dothebart** 2018-04-26 14:35 UTC
Labels: 1 Analyzing, 3 Core
