### ISSUE TITLE
HTTP Graph vertex collection save doesn't implement returnNew

### ISSUE THREAD

**Issue by dmk255** [arangodb/arangodb#2763] opened 2017-07-10 15:29 UTC
Initially reported in https://github.com/arangodb/arangojs/issues/75

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [ ] 3.2 Beta1
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

The graph api should also implement the `returnNew` option for saving documents to collections.

**Comment by dothebart** [comment] 2017-11-23 17:13
Closing as a duplicate of #2365

**Closed by dothebart** 2017-11-23 17:13 UTC
Labels: 1 Feature, 3 API, 3 Graph
