### ISSUE TITLE
Temp folder failure in AWS AMI installs

### ISSUE THREAD

**Issue by davidmw** [arangodb/arangodb#4300] opened 2018-01-14 00:01 UTC
- [ ] 3.3
- [ ] Single-Server
- [ ] mmfiles
- [ ] AWS

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

Yesterday I tried to create a cheaper AWS instance for development purposes. I started with the T2 Medium, then the M3 Medium, then the recommended (by the AMI) R3 X Large.

After initialization of the Ubuntu instance and login via SSH as user 'ubuntu' the server is suggesting a restart is needed and that 81 updates are available.

A quick check of running processes results in: 
`root      1292  0.0  0.6  89992 25840 ?        Ss   22:49   0:00 /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-tty false --supervisor
arangodb  1293  0.6  6.5 985456 250656 ?       Sl   22:49   0:01 /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-tty false --supervisor
ubuntu   15220  0.0  0.0  12944   948 pts/0    R+   22:53   0:00 grep -F --color=auto arangod
`

While a check of /var/tmp:
`ubuntu@ip-172-31-23-242:~$ ls /var/tmp/
systemd-private-2cb76b27ac0f430ca88f0d8e7c646efa-systemd-timesyncd.service-h30SYp`
finds that the temp.path has not been created. 

Starting the WebUI and checking the log:
<img width="1035" alt="screen shot 2018-01-14 at 11 01 21 am" src="https://user-images.githubusercontent.com/3413901/34910875-b5f666ce-f922-11e7-9fd5-9fee7d0fe10e.png">

I killed the arangod process then applied system updates using:
`
sudo apt-get update
sudo apt-get upgrade
`

Results in arangodb being touched:
`
Get:7 https://www.arangodb.com/repositories/arangodb32/xUbuntu_16.04  arangodb3 3.2.10 [33.6 MB]
Preparing to unpack .../arangodb3_3.2.10_amd64.deb ...
Unpacking arangodb3 (3.2.10) over (3.2.0) ...
Setting up arangodb3 (3.2.10) ...
Installing new version of config file /etc/arangodb3/arangod.conf ...
`
System needs a restart so:
`sudo shutdown -r`

Then reconnect via SSH and follow up upgrade instructions for Ubuntu 16.04

https://www.arangodb.com/download-major/ubuntu/

SO TO RECAP...
The AMI installed version 3.2.0.  The Ubuntu system update bumped ArangoDB to 3.2.10. And I've just manually upgraded to 3.3.2.

With 3.2.0 installed if I 'import queries' as ArangoDB user root - the /var/tmp/arangod will be created with owner and group arangodb and the perms look correct.

After the system upgrade bumped ArangoDB to 3.2.10 - importing queries is IMPOSSIBLE and the /var/tmp/arangod folder is NOT created. The WebUI log shows no log entires for failed import attempts.

After upgrading to 3.3.2 the /var/tmp/arangob folder is created with the wrong owner and perms.  Here is the upgrade activity and result:

`
ubuntu@ip-172-31-6-21:$ sudo apt-get update
Hit:1 http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]      
Ign:5 https://www.arangodb.com/repositories/arangodb32/xUbuntu_16.04  InRelease
Ign:6 https://download.arangodb.com/arangodb33/xUbuntu_16.04  InRelease
Hit:7 https://www.arangodb.com/repositories/arangodb32/xUbuntu_16.04  Release
Get:9 https://download.arangodb.com/arangodb33/xUbuntu_16.04  Release [1,206 B]
Get:10 https://download.arangodb.com/arangodb33/xUbuntu_16.04  Release.gpg [819 B]
Get:11 https://download.arangodb.com/arangodb33/xUbuntu_16.04  Packages [2,575 B]
Fetched 107 kB in 2s (36.8 kB/s)       
Reading package lists... Done
ubuntu@ip-172-31-6-21:$ sudo apt-get install arangodb3=3.3.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-53 linux-headers-4.4.0-53-generic linux-image-4.4.0-53-generic
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  arangodb3
1 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 33.8 MB of archives.
After this operation, 2,311 kB of additional disk space will be used.
Get:1 https://download.arangodb.com/arangodb33/xUbuntu_16.04  arangodb3 3.3.2 [33.8 MB]
Fetched 33.8 MB in 7s (4,459 kB/s)                                                                                                                                  
Preconfiguring packages ...
(Reading database ... 117616 files and directories currently installed.)
Preparing to unpack .../arangodb3_3.3.2_amd64.deb ...
Unpacking arangodb3 (3.3.2) over (3.2.10) ...
Processing triggers for systemd (229-4ubuntu21) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up arangodb3 (3.3.2) ...
Upgrading database files.
2018-01-13T23:51:19Z [2458] WARNING {memory} maximum number of memory mappings per process is 65530, which seems too low. it is recommended to set it to at least 128000
2018-01-13T23:51:19Z [2458] WARNING {memory} execute 'sudo sysctl -w "vm.max_map_count=128000"'
2018-01-13T23:51:19Z [2458] WARNING {memory} /sys/kernel/mm/transparent_hugepage/enabled is set to 'always'. It is recommended to set it to a value of 'never' or 'madvise'
2018-01-13T23:51:19Z [2458] WARNING {memory} /sys/kernel/mm/transparent_hugepage/defrag is set to 'always'. It is recommended to set it to a value of 'never' or 'madvise'
2018-01-13T23:51:19Z [2458] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/enabled"'
2018-01-13T23:51:19Z [2458] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/defrag"'
2018-01-13T23:51:19Z [2458] INFO {syscall} file-descriptors (nofiles) hard limit is 1048576, soft limit is 1048576
**ubuntu@ip-172-31-6-21:$ ls -l /var/tmp
total 12
drwx------ 2 root root 4096 Jan 13 23:51 arangod**
drwxrwxrwt 2 root root 4096 Jan 13 23:33 cloud-init
drwx------ 3 root root 4096 Jan 13 23:33 systemd-private-ee99c4bfe7ec495b84c9949f169aac72-systemd-timesyncd.service-VvUcF0
ubuntu@ip-172-31-6-21:$ ubuntu@ip-172-31-6-21:~$ ps auxw| fgrep arangod
root      2613  0.0  0.8 105284 34580 ?        Ss   Jan13   0:00 /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-tty false --supervisor
arangodb  2614  0.4  8.8 2031640 357680 ?      Sl   Jan13   0:02 /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-tty false --supervisor

`

**Comment by dothebart** [comment] 2018-01-16 12:28
Hi, 
thanks for reporting this issue. 
With ArangoDB 3.2.0 we added a more detailed user access control which does access checking to the collection containing the queries. So the permission denied error you get is not dependent on permissions in /var/tmp/, but rather on permissions on the database collection. 

So this is basically a duplicate of your bug number #4222

**Closed** 2018-01-16 12:28 UTC
Labels: 1 Bug, 1 Duplicate, 3 UserManagement
