### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by weickdev** [arangodb/arangodb#3603] opened 2017-11-07 08:56 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2.5
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

When I import massive datas, I get below error:
```
com.arangodb.ArangoDBException: Response: 500, Error: 3 - out of memory (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/Cluster/ClusterMethods.cpp:212)
	at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:106) ~[arangodb-java-driver-4.2.0.jar!/:?]
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:134) ~[arangodb-java-driver-4.2.0.jar!/:?]
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:46) ~[arangodb-java-driver-4.2.0.jar!/:?]
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:96) ~[arangodb-java-driver-4.2.0.jar!/:?]
	at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:46) ~[arangodb-java-driver-4.2.0.jar!/:?]
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:58) ~[arangodb-java-driver-4.2.0.jar!/:?]
```

**Comment by dothebart** [comment] 2017-11-08 09:57
Hi, 
this is most probably also a duplicate of #3342 ; I will notify you here once 3.2.7 containing the patched V8 is released.

**Comment by weickdev** [comment] 2017-11-08 10:26
Thanks @dothebart , so when do you plan to release 3.2.7?

**Comment by sleto-it** [comment] 2017-11-08 12:43
Hi @weickdev we plan to release it by the end of this week

Thanks,

**Comment by weickdev** [comment] 2017-11-13 10:15
@sleto-it will you release 3.2.7 today?

**Comment by sleto-it** [comment] 2017-11-15 19:55
Hi @weickdev,

Thanks again for opening this ticket. Version 3.2.7 has now been released 

Please could you upgrade? I am now closing this ticket. If the issue persists, please feel free to comment

Many thanks,

**Closed by sleto-it** 2017-11-15 19:55 UTC
Labels: 3 Cluster, 3 OOM
