### ISSUE TITLE
Keyboard shortcuts for query editor

### ISSUE THREAD

**Issue by ciscoheat** [arangodb/arangodb#1772] opened 2016-03-07 14:49 UTC
A very common keyboard shortcut is `Ctrl+Enter` to send something, it would be nice if this was the case with the AQL editor too.

In case this is low priority, I've made a [Tampermonkey](https://tampermonkey.net/) script for enabling this shortcut and two others:

```js
// ==UserScript==
// @name         ArangoDB keyboard shortcuts for queries
// @namespace    http://arangodb.com/
// @version      0.1
// @match        http*://*/_db/*/_admin/aardvark/standalone.html
// @grant        none
// ==/UserScript==
/* jshint -W097 */
'use strict';

// Ctrl+Enter executes current query
// Ctrl+Shift+Enter explains current query

// Ctrl+Enter in output window goes back to the query

(function($) {
    $(function() {
        $('body').on('keyup', function(e) {
            if(e.keyCode == 13 && e.ctrlKey) {                
                if($('#tabContentResult').is(':visible')) {
                    e.preventDefault();
                    $('#query-switch').click();
                } else if($('#tabContentQuery').is(':visible')) {
                    e.preventDefault();
                    var buttonId = e.shiftKey ? '#explainQueryButton' : '#submitQueryButton';
                    $(buttonId).click();
                }
            }
        });        
    });
})(jQuery); 
```

**Comment by hkernbach** [comment] 2016-03-08 17:16
Hm, Ctrl+Return should be enabled. I just checked version 2.8.4, and there it is working. Which version are you using? FYI: We're currently doing a complete redesign of the aql editor, which also supports Ctrl+Shift+Enter shortcut and offers lots of more features. It will be available in version 3.0.

**Comment by ciscoheat** [comment] 2016-03-08 19:16
That's strange, I'm using 2.8.4 too (Win7/Chrome), and it didn't work, hence the script. But I'm fine for now, looking forward to 3.0!

**Comment by hkernbach** [comment] 2016-03-12 15:34
I can confirm that using Win10/Chrome the shortcut is not working. When connecting with a Chrome/Linux or Chrome/Max client, it is working. So there seems to be an issue with clients hosted on windows. We will investigate.

**Comment by hkernbach** [comment] 2016-03-29 09:12
Will be fixed in next release.

**Closed by hkernbach** 2016-03-29 09:12 UTC
Labels: front-end

**Comment by ciscoheat** [comment] 2016-03-29 11:24
Sounds good, thank you!
