### ISSUE TITLE
GEO_INTERSECTS doesn't support a GEO_Polygon or GEO_MultiPolygon with holes.

### ISSUE THREAD

**Issue by tom919hsu** [arangodb/arangodb#10770] opened 2019-12-24 03:04 UTC
## My Environment

* __ArangoDB Version__:    3.5.3    
* __Storage Engine__:   MMFiles
* __Deployment Mode__:  Single Server >
* __Deployment Strategy__:   Manual Start
* __Configuration__:   standard
* __Infrastructure__:    Own
* __Operating System__:  Redhat 7.6
* __Total RAM in your machine__:    256G
* __Disks in use__:   900G
* __Used Package__:   ArangoDB repository

## Component, Query & Data

__Affected feature__: arango engine

__AQL query (if applicable)__:
```
LET Area = {
      "type": "Feature",
      "properties": {
        "ID" :"Polygon1"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [-122.89521,48.07939],
            [-122.88500,48.07939],
            [-122.88500,48.07738],
            [-122.89521,48.07738],
            [-122.89521,48.07939]
          ],
          [
            [-122.88901,48.07939],
            [-122.88701,48.07939],
            [-122.88701,48.07738],
            [-122.88901,48.07738],
            [-122.88901,48.07939]
          ]
        ]
      }
    }
LET polygon = GEO_POLYGON([[-122.89021,48.07839],[-122.89000,48.07839],[-122.89000,48.07738],[-122.89021,48.07738],[-122.89021,48.07839]])
RETURN GEO_INTERSECTS(Area.geometry, polygon)
```

__AQL explain (if applicable)__:
```
 LET Area = {
       "type": "Feature",
       "properties": {
         "ID" :"Polygon1"
       },
       "geometry": {
         "type": "Polygon",
         "coordinates": [
           [
             [-122.89521,48.07939],
             [-122.88500,48.07939],
             [-122.88500,48.07738],
             [-122.89521,48.07738],
             [-122.89521,48.07939]
           ],
           [
             [-122.88901,48.07939],
             [-122.88701,48.07939],
             [-122.88701,48.07738],
             [-122.88901,48.07738],
             [-122.88901,48.07939]
           ]
         ]
       }
     }
 LET polygon = 
 GEO_POLYGON([[-122.89021,48.07839],[-122.89000,48.07839],[-122.89000,48.07738],[-122.89021,48.07738],[-122.89021,48.07839]])
 RETURN GEO_INTERSECTS(Area.geometry, polygon)

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  4   CalculationNode      1     - LET #2 = null   /* json expression */   /* const assignment */
  5   ReturnNode           1     - RETURN #2

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   remove-unnecessary-calculations

Warnings:
 Code   Message
   10   in function 'GEO_INTERSECTS()': Subsequent loop not a hole in polygon
```
__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Execute the query manually and it won't return "true"

__Problem__:
unable to get "true" result with GEO_INTERSECTS function

__Expected result__:
expect to get "True" boolean.

**Comment by mpoeter** [comment] 2021-06-07 12:31
The problem is that the second polygon in `Area` does not describe a whole inside the first polygon since the upper/lower latitude is the same. So instead of cutting a whole into the first polygon (rectangle), its cuts it into two separate rectangles. This is not supported by the S2 library which we use internally. With a small adaptation to the coordinates of the second polygon it works as expected:
```
LET Area = {
      "type": "Feature",
      "properties": {
        "ID" :"Polygon1"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [-122.89521,48.07939],
            [-122.88500,48.07939],
            [-122.88500,48.07738],
            [-122.89521,48.07738],
            [-122.89521,48.07939]
          ],
          [
            [-122.88901,48.079389],
            [-122.88701,48.079389],
            [-122.88701,48.077381],
            [-122.88901,48.077381],
            [-122.88901,48.079389]
          ]
        ]
      }
    }
LET polygon = GEO_POLYGON([[-122.89021,48.07839],[-122.89000,48.07839],[-122.89000,48.07738],[-122.89021,48.07738],[-122.89021,48.07839]])
RETURN GEO_INTERSECTS(Area.geometry, polygon)
```
We can (and will) improve the documentation about these limitations and perhaps also improve the error messages, but otherwise we are not going change the current behavior, so I am closing this as won't fix.

**Closed by mpoeter** 2021-06-07 12:31 UTC
Labels: 3 Geo
