### ISSUE TITLE
Getting TRI_ERROR_CLUSTER_NOT_ALL_SHARDING_ATTRIBUTES_GIVEN when doing REPLACE of document in cluster setup

### ISSUE THREAD

**Issue by amit-macrometa** [arangodb/arangodb#14751] opened 2021-09-09 12:50 UTC
## My Environment

* __ArangoDB Version__:        <3.5.4 >
* __Storage Engine__:             < RocksDB>
* __Deployment Mode__:       < Cluster >
* __Deployment Strategy__:   < Kubernetes>
* __Configuration__:               
* __Infrastructure__:               < own >
* __Operating System__:        <Ubuntu 20.04 >
* __Total RAM in your machine__:        <32Gb. >
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:
< AQL query using web interface >

__AQL query (if applicable)__:
```
LET local = DOCUMENT("test", "key1")
REPLACE {_key: "key1"} WITH local IN test

```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

1

## Steps to reproduce

1. Run arangodb in `cluster` setup.
2. Create a document-collection with 1 document in it using web interface.
3. Run above AQL

__Problem__:
Getting failure: `Query: AQL: not all sharding attributes given (while executing).`

__Expected result__:
No Error

__Additional information__:
Below AQL give no error:
```
LET local = DOCUMENT("test", "key1")
REPLACE {_key: "key1"} WITH UNSET(local, "_key") IN test
```

```
The error is caused by the logic in Aql/SingleRemoteModificationExecutor.cpp (function merge). This function does not set _key in the payload in case the key is present in the replacement document (local) in this case. This leads to error TRI_ERROR_CLUSTER_NOT_ALL_SHARDING_ATTRIBUTES_GIVEN in hashByAttributesImpl (file Sharding/ShardingStrategyDefault.cpp).
```
**Note**: We do not see this behaviour in `singleserver` mode

**Comment by Simran-B** [comment] 2021-09-15 12:31
ArangoDB 3.5 is end-of-life: https://www.arangodb.com/subscriptions/end-of-life-notice/
Is this reproducible with 3.7 or later?

**Comment by amit-macrometa** [comment] 2021-09-15 12:46
@Simran-B I will try it on 3.7. Can you also please check on 3.7, if you have some time ? Its very easy to reproduce.

**Comment by dothebart** [comment] 2021-09-15 13:07
it only returns `[]` , no error. 
Hence closing.

**Closed by dothebart** 2021-09-15 13:07 UTC
Labels: 3 Cluster, Waiting User Reply, 1 Analyzing, 2 Out Of Date

**Comment by amit-macrometa** [comment] 2021-09-15 13:12
@dothebart Can you please verify below:
1) Your arangodb was running in  `cluster` mode ?
2) you used `latest` arangodb version ?

**Comment by dothebart** [comment] 2021-09-15 13:22
I was using cluster for sure, since that's what its all about?
 3.7.15-nightly packages.
I created a `test` collection, inserted a document with:
```
{"_id":"test/key1","_key":"key1","_rev":"_c8kOcLy--_","abc":"cde"}
``` 
executed the query.
