### ISSUE TITLE
db.createEdgeCollection() hangs and gets operation timeout

### ISSUE THREAD

**Issue by kishorel** [arangodb/arangodb#5625] opened 2018-06-18 12:33 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
-  3.3
- [ ] self-compiled devel branch

Mode:
-  Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
-  rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
-  Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
-  I'm using graph features

I'm issuing AQL via:
-  web interface with this browser:     running on this OS:
-  arangosh
- Arangodb 3.3 this Driver:

Hi,

We are facing an issue with the existing cluster having 14 collections, when trying to create a new collection using `db.createEdgeCollection("NAME",{numberOfShards : 3,replicationFactor : 2})` it hangs and throwing operation timeout.

The same command created the collection for "test" database on the same cluster. Even the same command with `numberOfShards` as `1` and `replicationFactor` as `1` worked.

Error log:
```
IP:8529@DB> db._createEdgeCollection("CollName",{numberOfShards : 3,replicationFactor : 2})
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 98,7: ArangoError 1457: timeout in cluster operation
!      throw error;
!      ^
stacktrace: ArangoError: timeout in cluster operation
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:96:21)
    at Proxy.ArangoDatabase._create (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:395:12)
    at Proxy.ArangoDatabase._createEdgeCollection (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:420:15)
    at <shell command>:1:4
```
The same issue seems to be appeared in ArangoDB 3.2 and marked as solved at https://github.com/arangodb/arangodb/issues/3602

Also let us know the reason for the following message in the dbServer logs.
```
[14910] ERROR {replication} initial sync failed for database 'ursDB': cannot dump: collection 's4014431', type edge, id 38030037 not found on slave. Collection info {"allowUserKeys":true,"cacheEnabled":false,"cid":"38030037","deleted":false,"globallyUniqueId":"s4014431","id":"38030037","indexes":[{"fields":["_key"],"id":"0","selectivityEstimate":1,"sparse":false,"type":"primary","unique":true},{"fields":["_from"],"id":"1","selectivityEstimate":0.8269446999897782,"sparse":false,"type":"edge","unique":false},{"fields":["_to"],"id":"2","selectivityEstimate":0.9448726932959589,"sparse":false,"type":"edge","unique":false},{"deduplicate":false,"fields":["lastUpdatedAt"],"id":"10062551","selectivityEstimate":0.8315510744474998,"sparse":true,"type":"skiplist","unique":false}],"isSmart":false,"isSystem":false,"keyOptions":{"allowUserKeys":true,"lastValue":8174779,"type":"traditional"},"name":"s4014431","numberOfShards":3,"planId":"4014428","replicationFactor":2,"shardKeys":["_key"],"shards":{"s4014429":["PRMR-ca205d3f-6e15-4b78-8575-099cda9fff9a","PRMR-ebf65ced-ab25-4fa5-8a37-47e25e8e7825","PRMR-3263bc25-745d-401d-b065-7e7659063a15"],"s4014430":["PRMR-ca205d3f-6e15-4b78-8575-099cda9fff9a","PRMR-ebf65ced-ab25-4fa5-8a37-47e25e8e7825","PRMR-3263bc25-745d-401d-b065-7e7659063a15"],"s4014431":["PRMR-3263bc25-745d-401d-b065-7e7659063a15","PRMR-ebf65ced-ab25-4fa5-8a37-47e25e8e7825","PRMR-ca205d3f-6e15-4b78-8575-099cda9fff9a"]},"status":3,"type":3,"version":6,"waitForSync":false}

```

This is a blocker for new feature which needs a new collection.

Please help.

**Comment by kishorel** [comment] 2018-06-26 07:01
Hi Team,

Any update on the mentioned issue? Please help.

**Comment by arijeetsaha** [comment] 2018-06-28 06:49
This behavior is simply not acceptable. We are already in production with this setup and we are stuck at deploying new feature.
Please check ASAP

**Comment by sleto-it** [comment] 2018-06-28 10:43
Hi @arijeetsaha,

While we want to help you solving this issue, please note that there are not guaranteed SLA for ArangoDB Community Support. We do provide some commercial subscriptions, though. If you are running a cluster on production and require specific SLAs my suggestion is to consider one of our subscriptions (https://arangodb.com/subscriptions/)

That said, we will try to get back in this ticket as soon as possible and help as part of our effort to help all our Community, after prioritizing requests coming from our Customers

Many Thanks,

Santo Leto,
Director, Global Customer Support, ArangoDB

**Comment by dothebart** [comment] 2020-09-02 08:55
closing as duplicate of https://github.com/arangodb/arangodb/issues/3380

**Closed by dothebart** 2020-09-02 08:55 UTC
Labels: 1 Analyzing, 3 Cluster
