### ISSUE TITLE
query ID not found while iterating streaming cursor

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9166] opened 2019-06-03 07:43 UTC
RocksDB, 3.4.5, using python-arango.
While iterating the streaming cursor,  an exception accured:
    raise CursorNextError(resp, request)
arango.exceptions.CursorNextError: [HTTP 404][ERR 1591] AQL: Error message received from shard '' on cluster node 'PRMR-3b6fa38b-cd65-4914-81c9-40fc2612ff0c': query ID not found (while executing)
What's the reason, how to avoid it ?

**Comment by OmarAyo** [comment] 2019-06-05 15:02
Hi @daoxian 

How long it takes from the time he starts the query until the error happens

**Comment by daoxian** [comment] 2019-06-06 06:50
It's is about half an hour, far longer than the cursor's ttl. But I think the ttl value should be reset whenever a query arrives, am I correct ?

**Comment by dothebart** [comment] 2020-09-02 12:36
Hi, the TTL is absolute. 
Closing this as a duplicate of the feature request for a relative TTL: https://github.com/arangodb/arangodb/issues/4490

please note [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.

**Closed by dothebart** 2020-09-02 12:36 UTC
Labels: 1 Analyzing, 3 API, 3 AQL
