### ISSUE TITLE
Fatal {startup} cannot locate 'usr\share\arangodb3\icudtl.dat' from Windows zip file

### ISSUE THREAD

**Issue by Key2Publish** [arangodb/arangodb#2475] opened 2017-05-09 10:12 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x ] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x ] Windows, version: 10
- [ ] MacOS, version:

### this is an installation-related issue:
I have downloaded the Windows-zip file and it gives me on version 3.1.18 and 3.1.19 a Fatal Error when trying too start the executables in the usr/bin file. I did not have this issue on 3.1.15 and 3.1.17

command: arangod.exe
directory: D:\DB\Arangodb\usr\bin
output: [10860] Fatal {startup} cannot locate 'usr\share\arangodb3\icudtl.dat'; please make sure it is available; the variable ICU_DATA='' should point to the directory containing 'icudtl.dat'

I can see the file at that location. So it is there, but the variable ICU_DATA is empty so perhaps I should add it too a config? Or did something went wrong with the windows version. I know I didn't need to on 3.1.15 and 3.1.17

Any help to resolve this issue is appreciated, even if I did something wrong.

**Comment by dothebart** [comment] 2017-05-09 10:16
could this be a duplicate of #2472 and the solution proposed there help you too?

**Comment by Key2Publish** [comment] 2017-05-09 10:29
A excuse me you are correct, I did not see that issue, even though I searched before. Thank you that helped resolve it.

**Closed** 2017-05-09 10:30 UTC

**Comment by dothebart** [comment] 2017-05-09 11:35
You're welcome - no wories. it will have to be fixed too.
