### ISSUE TITLE
Python driver to be used for a system that makes highly concurrent requests to db

### ISSUE THREAD

**Issue by dilipvamsi** [arangodb/arangodb#5372] opened 2018-05-16 18:40 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

### this is a question
As there is an issue raised in pyArango ([When using gevent/greenlets, highly concurrent requests can return incorrect responses](https://github.com/tariqdaouda/pyArango/issues/65)), what would be the best python driver to use in such scenarios.
Is there any roadmap for the implementation of official driver from the ArangoDB team.

Thanks,
Dilip Vamsi.

**Comment by dothebart** [comment] 2018-05-17 07:53
Hi, 
as demonstrated with the performance blog post series, 
you need to monkey patch the propper http client to be used:
https://arangodb.com/2017/10/performance-analysis-pyarango-usage-scenarios/

The reporter also forked pyArango and added some changes: 
 https://github.com/bosskeyproductions/pyArango
which are currently in production use. 
However, we didn't inspect them for backporting yet.

**Comment by dilipvamsi** [comment] 2018-05-17 10:36
Hi @dothebart ,
So, for just a monkey patch we don't the statsd client, right? Or, do I need to make any other changes.
Also I'm not clear on which version of pyArango to use as the version by [booskeyproductions](https://github.com/bosskeyproductions/pyArango) is old.
Can you point to the repo which has active development.
What are your thoughts about [python-arango](https://github.com/joowani/python-arango) which uses rest api of arangodb. 
Can this be an alternative of this scenario for high concurrency or just stick with the monkey patch.

This is a changed version of code without statsd client.
``` python
#!/usr/bin/python
import json as json_mod
import sys
import random
import pyArango
from datetime import datetime
from pyArango.connection import *
from pyArango.collection import *
import requests
from gevent import monkey
from gevent import GreenletExit
monkey.patch_all()
import gevent
import grequests
 
auth_token = None
connection_urls = [
    "http://127.0.0.1:8529"
]
 
class JWTAuth(requests.auth.AuthBase):
    def __init__(self, token):
        self.token = token
 
    def __call__(self, r):
        # Implement JWT authentication
        r.headers['Authorization'] = 'Bearer %s' % self.token
        return r
def get_auth_token():
    global auth_token, connection_urls
 
    if auth_token:
        return auth_token
 
    kwargs = {'data': '{"username":"%s","password":"%s"}' % ("root", "test")}
    for connection_url in connection_urls:
        response = requests.post('%s/_open/auth' % connection_url, **kwargs)
        if response.ok:
            json_data = response.content
            if json_data:
                data_dict = json_mod.loads(json_data)
                auth_token = data_dict.get('jwt')
                break
    return auth_token
 
class AikidoSession(object):
    def __init__(self, session_username, session_password):
        if session_username:
            self.auth = JWTAuth(session_password)
        else:
            self.auth = None
 
    def post(self, url, data=None, json=None, **kwargs):
        if data is not None:
            kwargs['data'] = data
        if json is not None:
            kwargs['json'] = json
 
        kwargs['auth'] = self.auth
        return grequests.map([grequests.post(url, **kwargs)])[0]
 
    def get(self, url, **kwargs):
        kwargs['auth'] = self.auth
        result = grequests.map([grequests.get(url, **kwargs)])[0]
        return result
 
    def put(self, url, data=None, **kwargs):
        if data is not None:
            kwargs['data'] = data
        kwargs['auth'] = self.auth
        return grequests.map([grequests.put(url, **kwargs)])[0]
 
    def head(self, url, **kwargs):
        kwargs['auth'] = self.auth
        return grequests.map([grequests.put(url, **kwargs)])[0]
 
    def options(self, url, **kwargs):
        kwargs['auth'] = self.auth
        return grequests.map([grequests.options(url, **kwargs)])[0]
 
    def patch(self, url, data=None, **kwargs):
        if data is not None:
            kwargs['data'] = data
        kwargs['auth'] = self.auth
        return grequests.map([grequests.patch(url, **kwargs)])[0]
 
    def delete(self, url, **kwargs):
        kwargs['auth'] = self.auth
        return grequests.map([grequests.delete(url, **kwargs)])[0]
 
    def disconnect(self):
        pass
 
# Monkey patch the connection object:
pyArango.connection.AikidoSession = AikidoSession

conn = Connection(username="root", password=get_auth_token())
db = conn["_system"]
print(db.collections)
```
Thanks,
Dilip Vamsi.

**Comment by dothebart** [comment] 2018-05-17 12:42
Hi, 
the statsd functionality has meanwhile been integrated in pyArango for optional use; however you don't need it from the functional point of view. 

pyArango and python-arango use [the HTTP API](http://docs.arangodb.com/latest/HTTP/) - so no difference from that POV. Both meanwhile run on python 3. Neither one has native gevent support; I personally only tried to monkey patch it into pyArango. 

The pyArango aikidosession has been the source of troubles during the python 3.0 migration which have been resolved. For monkey-patching it has prooven to be good ;)

Both maintainers tend to be reactive to pullrequests, issues etc. 

In general its probably a question which provided python api you like better - that of pyArango or python-arango.

**Comment by dilipvamsi** [comment] 2018-05-19 06:04
Hi,
This is the final version of code that be directly imported as file.
```python
"""Connection creator."""
import json as _json
import random as _random
import requests as _requests
import grequests as _grequests

class TokenGenrator(object):

    def __init__(self, username, password, connection_urls):
        """Init the credentials for getting the auth token.

        Parameters
        ----------
        username : string
            username that exists in db.
        password : string
            password for the given user.
        connection_urls : list(string)
            list of connection strings for the db instances.

        """
        self.username = username
        self.password = password
        self.connection_urls = connection_urls
        self._auth_token = None
        self._connection_indices = list(range(len(connection_urls)))

    def get_connection_indicies(self, pick_random_server):
        """Return the connection indicies."""
        if not pick_random_server:
            return self._connection_indices
        connection_indices = list(range(len(self.connection_urls)))
        _random.shuffle(connection_indices)
        return connection_indices

    def get_auth_token(self, pick_random_server=False):
        """Get auth token from given list of servers.

        pick_random_server : bool, optional
            pick selection of server by random
            (the default is False, which means select in the given order.)

        Returns
        -------
        string
            auth token generated from the server.

        """
        if self._auth_token is not None:
            return self._auth_token

        kwargs = {
            'data': '{"username":"%s","password":"%s"}' % (
                self.username, self.password
            )
        }

        for connection_index in self.get_connection_indicies(
                pick_random_server
        ):
            response = _requests.post(
                '%s/_open/auth' % self.connection_urls[connection_index],
                **kwargs
            )
            if response.ok:
                json_data = response.content
                if json_data:
                    data_dict = _json.loads(json_data)
                    self._auth_token = data_dict.get('jwt')
        return self._auth_token


class JWTAuth(_requests.auth.AuthBase):
    def __init__(self, token):
        self.token = token

    def __call__(self, r):
        # Implement JWT authentication
        r.headers['Authorization'] = 'Bearer %s' % self.token
        return r


class AikidoSession(object):
    def __init__(self, session_username, session_password):
        if session_username:
            self.auth = JWTAuth(session_password)
        else:
            self.auth = None

    def post(self, url, data=None, json=None, **kwargs):
        if data is not None:
            kwargs['data'] = data
        if json is not None:
            kwargs['json'] = json

        kwargs['auth'] = self.auth
        return _grequests.map([_grequests.post(url, **kwargs)])[0]

    def get(self, url, **kwargs):
        kwargs['auth'] = self.auth
        result = _grequests.map([_grequests.get(url, **kwargs)])[0]
        return result

    def put(self, url, data=None, **kwargs):
        if data is not None:
            kwargs['data'] = data
        kwargs['auth'] = self.auth
        return _grequests.map([_grequests.put(url, **kwargs)])[0]

    def head(self, url, **kwargs):
        kwargs['auth'] = self.auth
        return _grequests.map([_grequests.put(url, **kwargs)])[0]

    def options(self, url, **kwargs):
        kwargs['auth'] = self.auth
        return _grequests.map([_grequests.options(url, **kwargs)])[0]

    def patch(self, url, data=None, **kwargs):
        if data is not None:
            kwargs['data'] = data
        kwargs['auth'] = self.auth
        return _grequests.map([_grequests.patch(url, **kwargs)])[0]

    def delete(self, url, **kwargs):
        kwargs['auth'] = self.auth
        return _grequests.map([_grequests.delete(url, **kwargs)])[0]

    def disconnect(self):
        pass


def get_connection(
        username, password, connection_urls, is_gevent=False,
        pick_random_server=False
):
    """Get the connection for the given credentials.

    Parameters
    ----------
    username : string
        username that exists in db.
    password : string
        password for the given user.
    connection_urls : list(string)
        list of connection strings for the db instances.
    is_gevent : bool, optional
        mokey patchs to AikidoSession (the default is False,
        which means don't patch)
    pick_random_server : bool, optional
        pick selection of server by random
        (the default is False, which means select in the given order.)

    Returns
    -------
    pyArango.connection.Connection
        returns patched version if the connection is for gevent.

    """
    import pyArango.connection
    if is_gevent:
        pyArango.connection.AikidoSession = AikidoSession
        auth_token = TokenGenrator(username, password, connection_urls)
        return pyArango.connection.Connection(
            username=username,
            password=auth_token.get_auth_token(pick_random_server)
        )

    # for dev.
    connection_index = 0 if not pick_random_server \
        else _random.randint(0, len(connection_urls) - 1)
    return pyArango.connection.Connection(
        arangoURL=connection_urls[connection_index],
        username=username, password=password
    )

if __name__  == "__main__":
    import db_settings
    CONNECTION = get_connection(
        db_settings.USERNAME, db_settings.PASSWORD, db_settings.CONNECTION_URLS,
        db_settings.IS_GEVENT, db_settings.PICK_RANDOM_SERVER
    )
    print(CONNECTION["_system"].collections)
```

**Comment by dothebart** [comment] 2018-05-22 11:38
@tariqdaouda do you see a good way to integrate this into pyArango for users that want to use gevent?

**Comment by tariqdaouda** [comment] 2018-05-22 17:41
Nice! From a quick glance It seems to me that is pretty much integrated already. Could you send me a pull request? That would make the comparison with the current version a little easier.

**Comment by dothebart** [comment] 2018-05-23 08:43
@tariqdaouda the question would be, how to switch the Aikidosession if running with gevent or native in the most elegant way?

**Comment by tariqdaouda** [comment] 2018-05-23 17:41
Ok, I'll find a way to integrate it that makes it transparent to the user.

**Comment by tariqdaouda** [comment] 2018-05-27 11:05
I have a few questions:

- The full URL is given for every request type, which means that it must contain the server URL as well.  Is this the expected behavior or should the server be chosen among the ones in the list?

- By server do you mean endpoint? In that case, the list can be retrieved from the DB.

**Comment by dilipvamsi** [comment] 2018-05-28 17:21
Hi @tariqdaouda ,
For attaining the auth token you need to do a post request to the **server_url/_open/auth** with credentials.
So, to my understanding the endpoint of the arangodb web interface is what is to be given to make that rest call.

**Comment by dothebart** [comment] 2018-05-29 07:50
Hi, 
you need to specify all URLs of the coordinators. 
You should know that clusters are for when your machine out-does the storage size of one machine, or if you need more js-computing power for foxx. If you need HA, a single server failover setup is better.

**Comment by tariqdaouda** [comment] 2018-05-30 16:58
Thanks @dothebart and @dilipvamsi. So the list of servers here is the list of all coordinators. What is HA?
I srill have a few questions for you regarding the loop for getting the auth key:
* Do you need to ask all the coordinators for the auth key or is one enough?
* Why do you randomize the list of servers before looping, this action is only done once.

**Comment by Simran-B** [comment] 2018-05-31 11:31
HA = High Availability

**Comment by ewoutp** [comment] 2018-06-01 09:59
@tariqdaouda I've written most of the go-driver and from there I can give you some points regarding the intended fail-over behavior.

All requests are send only to a single specific coordinator. The fail-over part is only relevant when a coordinator cannot be reached. The go-driver implements that as follows:
It tries to send the request to the coordinator and sets a flag as soon as the OS network stack has begun sending the first byte of the request. As soon as that flag is set, the request will never be retried (automatically) on another coordinator, because there is just no way to know if the request reached the coordinator and the coordinator processed it. It is possible that the request did not reach the coordinator, but it is also possible that the result did not reach the calling client.
So only if there is a failure or timeout before the first request data is send, will the go-driver retry the request on another coordinator. This is for example the case when no database is listening on the specified address.

Once the go-driver finds a coordinator that gives a proper response, it will remember that coordinator and start using it for future requests.

Now besides fail-over there is also load-balancing (not yet implemented in the go-driver). If implemented by the client (there are other possibilities), the client should not use the same coordinator for every request, but either rotate requests over all of them (in a circular fashion) or just pick a coordinator randomly for each request. When rotating, it will help if every client randomizes its list of coordinators, so the coordinator selection has a higher chance or actually spreading the load over all coordinators.

To get the addresses (URLs) of all coordinators, you can either configure all of them in your client or ask 1 of the coordinator to fetch all endpoints (`GET /_api/cluster/endpoints`)

Hope this helps. If you have further questions, please ask.

**Comment by ewoutp** [comment] 2018-06-01 10:06
One more addition. When doing requests that return cursor (`/_api/cursor`), you must always use the same coordinator for followup calls.

**Comment by tariqdaouda** [comment] 2018-06-02 06:54
Thanks, @ewoutp. This helps a lot.

**Comment by OmarAyo** [comment] 2018-06-18 12:06
Hi @dilipvamsi and @tariqdaouda,

Just sending a quick followup, are you all set with this ticket?
Can we go ahead and close it, or you prefer to leave it open for now?

Thanks,

**Comment by tariqdaouda** [comment] 2018-06-18 14:05
I haven't had the time to implement all of it yet, but it will be done. I think it's better to leave it open for now in case other questions arise.

**Comment by OmarAyo** [comment] 2018-06-18 14:30
Hi @tariqdaouda 

Sure, we will leave this ticket open 

Yours,

**Comment by maxkernbach** [comment] 2018-08-13 10:34
Hi @tariqdaouda,

how are things going? Are you making progress with your implementation?

**Comment by tariqdaouda** [comment] 2018-08-14 03:45
Hi @maxkernbach,

I started the implementation and I have some ideas on how to complete it. But unfortunately, I am extremely busy at the moment.

**Comment by maxkernbach** [comment] 2018-08-14 08:33
Sure, take your time. Please just let us know when you have some news.

**Comment by tariqdaouda** [comment] 2018-08-16 12:31
Will do thank you for asking.

**Comment by dilipvamsi** [comment] 2018-09-03 14:13
Hi @dothebart ,
While running the sample code to print the system db for the new version of the arangodb (3.3.14), I'm getting connection error.

**Sample Code**

```python
import json as json_mod
import pyArango.connection
from gevent import monkey
from gevent import GreenletExit
monkey.patch_all()
import gevent
import grequests
import requests

connection_urls = ["http://127.0.0.1:8529"]
auth_token = None

USERNAME = "root"
PASSWORD = "password"


class JWTAuth(requests.auth.AuthBase):
    def __init__(self, token):
        self.token = token

    def __call__(self, r):
        # Implement JWT authentication
        r.headers['Authorization'] = 'Bearer %s' % self.token
        return r

def get_auth_token():
    global auth_token, connection_urls

    if auth_token:
        return auth_token

    kwargs = {'data': '{"username":"%s","password":"%s"}' % (USERNAME, PASSWORD)}
    for connection_url in connection_urls:
        response = requests.post('%s/_open/auth' % connection_url, **kwargs)
        if response.ok:
            json_data = response.content
            if json_data:
                data_dict = json_mod.loads(json_data)
                auth_token = data_dict.get('jwt')
                break
    print(auth_token)
    return auth_token

class AikidoSession(object):
    def __init__(self, session_username, session_password):
        if session_username:
            self.auth = JWTAuth(session_password)
        else:
            self.auth = None

    def post(self, url, data=None, json=None, **kwargs):
        if data is not None:
            kwargs['data'] = data
        if json is not None:
            kwargs['json'] = json

        kwargs['auth'] = self.auth
        return grequests.map([grequests.post(url, **kwargs)])[0]

    def get(self, url, **kwargs):
        kwargs['auth'] = self.auth
        result = grequests.map([grequests.get(url, **kwargs)])[0]
        return result

    def put(self, url, data=None, **kwargs):
        if data is not None:
            kwargs['data'] = data
        kwargs['auth'] = self.auth
        return grequests.map([grequests.put(url, **kwargs)])[0]

    def head(self, url, **kwargs):
        kwargs['auth'] = self.auth
        return grequests.map([grequests.put(url, **kwargs)])[0]

    def options(self, url, **kwargs):
        kwargs['auth'] = self.auth
        return grequests.map([grequests.options(url, **kwargs)])[0]

    def patch(self, url, data=None, **kwargs):
        if data is not None:
            kwargs['data'] = data
        kwargs['auth'] = self.auth
        return grequests.map([grequests.patch(url, **kwargs)])[0]

    def delete(self, url, **kwargs):
        kwargs['auth'] = self.auth
        return grequests.map([grequests.delete(url, **kwargs)])[0]

    def disconnect(self):
        pass

# Monkey patch the connection object:
pyArango.connection.AikidoSession = AikidoSession

conncetion = pyArango.connection.Connection(
    username=USERNAME,
    password=get_auth_token()
)

print(conncetion['_system'].collections)
```
**Stack Trace**
```
ConnectionError                           Traceback (most recent call last)
~/test/pyArango/sample.py in <module>()
     91 conncetion = pyArango.connection.Connection(
     92     username="root",
---> 93     password=get_auth_token()
     94 )
     95 

~/venv/lib/python3.6/site-packages/pyArango/connection.py in __init__(self, arangoURL, username, password, verbose)
    103 
    104         self.users = Users(self)
--> 105         self.reload()
    106 
    107     def disconnectSession(self) :

~/venv/lib/python3.6/site-packages/pyArango/connection.py in reload(self)
    129                     self.databases[dbName] = DBHandle(self, dbName)
    130         else :
--> 131             raise ConnectionError(data["errorMessage"], self.databasesURL, r.status_code, r.content)
    132 
    133     def createDatabase(self, name, **dbArgs) :

ConnectionError: not authorized to execute this request. URL: http://127.0.0.1:8529/_api/user/root/database, status: 401. Errors: b'{"error":true,"errorNum":11,"errorMessage":"not authorized to execute this request","code":401}'
```

**Comment by dothebart** [comment] 2018-09-03 14:59
wrong passvoid?

**Comment by dilipvamsi** [comment] 2018-09-03 15:01
No I'm able to connect if I'm not using the monkey patching.

**Comment by dothebart** [comment] 2018-09-03 15:10
I'd use `ngrep -Wbyline -d lo port 8529` to check out whats going on on the wire, all the rest is just guesswork, like maybe your user doesn't have access to a specific database or so?

**Comment by dilipvamsi** [comment] 2018-09-03 15:11
Hi @dothebart  
The sample code is working fine for locally running arangodb. 
But somehow it is throwing the error for arangodb which is hosted in cloud.
Both have same credentials.

**Comment by dothebart** [comment] 2018-09-03 15:13
maybe you've got troubles with the JWT (if)? sniffing and checking whats in the http headers should bring you more information whats going on.

**Comment by dilipvamsi** [comment] 2018-09-03 15:14
It is able to get some jwt token
But it is not getting authenticated.

**Comment by dilipvamsi** [comment] 2018-09-03 15:48
@dothebart ,
I'm actually not passing the arangoURL and that is causing the issue.

**Comment by tariqdaouda** [comment] 2018-10-10 08:58
I've pushed an implementation to [this branch](https://github.com/tariqdaouda/pyArango/tree/geevent). Works for me besides a few:
`ResourceWarning: unclosed`
f any of you guys could give it a try and test it, it would great.

**Comment by dothebart** [comment] 2018-10-11 09:50
ok, tested; I see the grequests aikidosession being used. Now to some serious 3.4 hammering ;-)

**Comment by dilipvamsi** [comment] 2018-10-11 12:05
Hi @tariqdaouda @dothebart ,
For longer connections if the acquired auth token got expired, the token has to be reset. I think that is only part that is missing.

Regards,
Dilip Vamsi.

**Comment by dilipvamsi** [comment] 2018-10-11 12:17
Hi @tariqdaouda ,
Use Queue instead of the currentURLId (url index) for round robin. As Queues in python are thread safe and performs better round robin ( pop front and push it to the back).

Regards,
Dilip Vamsi.

**Comment by dilipvamsi** [comment] 2018-10-15 07:49
> For longer connections if the acquired auth token got expired, the token has to be reset. I think that is only part that is missing.

@dothebart any suggestions for implementations.

Thanks,
Dilip Vamsi.

**Comment by dothebart** [comment] 2020-09-02 07:56
[I recently created the ability to use bulk requests with pyArango](https://github.com/ArangoDB-Community/pyArango/pull/139).

With the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) I'm closing this as solved.

**Closed by dothebart** 2020-09-02 07:56 UTC
Labels: 1 Question, performance
