### ISSUE TITLE
Description metadata for collection

### ISSUE THREAD

**Issue by gendalf** [arangodb/arangodb#2393] opened 2017-03-23 12:48 UTC
Very often I encounter the need to document the structure of the collection. It would be very convenient to have a similar text description for the collection in the web interface.

**Comment by grexe** [comment] 2017-07-26 11:48
this is exactly our requirement, too - I really miss the feature of RDBMS where you could add descriptions for each TABLE and COLUMN...
I imagine this would be easy to add since every document already has a `properties` map that can hold arbitrary key/value pairs, so you could add the same map to the Collection type and define a reserved name like `_description` that holds the description for this collection or field.

**Comment by Simran-B** [comment] 2017-11-29 19:12
I really like this idea. It's not possible to add per-column (per-attribute) descriptions because ArangoDB is schema-free, but a general description field for every collection would be useful.

What also comes to mind: groups and labels for collections.

Displaying collections sorted by a string `_group` in the Web UI would make it easier to see which collections are related (e.g. two vertex collections and an edge collection, that make up a graph). 

Labels could be used for the quick search. Each collection could have 0-n labels, stored as an array of strings in `_labels`.

**Comment by grexe** [comment] 2017-11-30 13:55
Thanks for getting back to this @Simran-B - esp. groups would be very useful and could also serve as namespaces, e.g. we have different modules in the team that have common entities, so we share a database but could need some kind of separation.

So groups and labels could provide a softer, more semantic organization of entities (collections) in a database, instead of a physical separation by database.

**Comment by dothebart** [comment] 2020-09-02 09:31
Closing as a duplicate of https://github.com/arangodb/arangodb/issues/6048

**Closed by dothebart** 2020-09-02 09:31 UTC
Labels: 1 Feature, 3 Core, 3 UI
