### ISSUE TITLE
ArangoError 1205: illegal document handle in arangodump for an edge collection

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#1671] opened 2016-01-21 14:32 UTC
We don't know why this collection is special, but it does not work to dump it in the command line. If I download the json from the web interface, it works.

```
root@server:~# arangodump --server.database bi_stage ./dump --server.password xxx --collection has
Server version: 2.8.0-beta8
Connected to ArangoDB 'tcp://127.0.0.1:8529', database: 'bi_stage', username: 'root'
Writing dump to output directory './dump'
Last tick provided by server is: 3086304330723163
# Dumping edge collection 'has'...
Error: got error from server: HTTP 400 (Bad Request): ArangoError 1205: illegal document handle
Processed 1 collection(s), wrote 0 byte(s) into datafiles, sent 1 batch(es)
root@server2:~#
```

In the HTTP log:

```
2016-01-21T13:26:29 [87058] INFO ,"http-request","127.0.0.1","GET","HTTP/1.1",200,0,43,"/_api/version",0.000035
2016-01-21T13:26:29 [87058] INFO ,"http-request","127.0.0.1","GET","HTTP/1.1",200,0,42,"/_admin/server/role",0.000420
2016-01-21T13:26:29 [87058] INFO ,"http-request","127.0.0.1","POST","HTTP/1.1",200,11,25,"/_api/replication/batch",0.000067
2016-01-21T13:26:29 [87058] INFO ,"http-request","127.0.0.1","GET","HTTP/1.1",200,0,6386,"/_api/replication/inventory?includeSystem=false",0.000871
2016-01-21T13:26:29 [87058] INFO ,"http-request","127.0.0.1","PUT","HTTP/1.1",200,0,26,"/_admin/wal/flush?waitForSync=true&waitForCollector=true",0.451248
2016-01-21T13:26:29 [87058] INFO ,"http-request","127.0.0.1","PUT","HTTP/1.1",204,11,0,"/_api/replication/batch/3084912775868251",0.000142
2016-01-21T13:26:29 [87058] INFO ,"http-request","127.0.0.1","GET","HTTP/1.1",400,0,82,"/_api/replication/dump?collection=2884290558712915&ticks=false&translateIds=true&flush=false&from=0&chunkSize=2097152&to=3084912775868251&failOnUnknown=true",0.001502
2016-01-21T13:26:29 [87058] INFO ,"http-request","127.0.0.1","DELETE","HTTP/1.1",204,0,0,"/_api/replication/batch/3084912775868251",0.001082
```

**Comment by dothebart** [comment] 2016-01-26 12:11
this is a side effect of #1581 closing there fore as known issue.

**Closed by dothebart** 2016-01-26 12:11 UTC

**Comment by razvanphp** [comment] 2016-01-26 12:25
I'm not sure about that, usually the dump should work, and it would contain "_unknown" entries in there that I can fix.

**Comment by jsteemann** [comment] 2016-01-26 12:32
It's definitely caused by unknown collection ids used by `_from` or `_to` of edges.
This will lead to the exact same error when dumping an edge collection which such edges.

*arangodump* in 2.8 will fail by default is such an edge is found, and return that error code. There is a `--force` option for *arangodump* that can be set to `true` to have these collections exported anyway. 
In 2.7 I think the only (and non-configurable) behavior was to export the edges with a collection name of `_unknown`.

**Comment by razvanphp** [comment] 2016-01-26 12:39
Ok, makes sense now, and `--force` will just ignore those invalid edges or they will be exported with `_unknown` like before?

Why downloading from the web interface is different?
