### ISSUE TITLE
Arangodb,How to return an isolated point?

### ISSUE THREAD

**Issue by moxiaoyu100** [arangodb/arangodb#4005] opened 2017-12-12 09:29 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [✔ ] 3.2

Mode:
- [✔ ] Cluster

Storage-Engine:
- [✔ ] rocksdb

On this operating system:
- [✔ ] Linux 

### this is an AQL-related issue:
[✔ ] I'm using graph features

I now have a need, we need to get a single point of data in the data independent, this point no edges, AQL how to write?

**Comment by maxkernbach** [comment] 2017-12-12 10:07
Hello,

this is a duplicate of https://stackoverflow.com/questions/47769067/how-to-get-isolated-vertices-on-a-graph. Does this answer your question?

**Comment by maxkernbach** [comment] 2017-12-18 10:13
Closing this issue as solved. The question is answered on stackoverflow.

**Closed by maxkernbach** 2017-12-18 10:14 UTC
Labels: 1 Question, 2 Solved, 3 AQL

**Comment by moxiaoyu100** [comment] 2017-12-19 08:48
ok
