### ISSUE TITLE
VPack Error : Expecting Digit

### ISSUE THREAD

**Issue by kavin26** [arangodb/arangodb#5133] opened 2018-04-18 11:05 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [*] 3.1
- [ ] 3.2
- [ ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [*] Single-Server

Storage-Engine:
- [*] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [] Debian .deb
  - [*] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features
i got an error when it process one of text files in array,
```
`multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "zeenews_preprocessing_v2.py", line 634, in raw_data_processing
    docid = doc_query_result['_key']
KeyError: '_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "zeenews_preprocessing_v2.py", line 656, in raw_data_processing
    bindVars={'title': metadata['title'], 'type': doctype, 'updateobj': metadata})
  File "/usr/local/lib/python3.5/dist-packages/pyArango/database.py", line 178, in AQLQuery
    json_encoder = json_encoder, **moreArgs)
  File "/usr/local/lib/python3.5/dist-packages/pyArango/query.py", line 145, in __init__
    Query.__init__(self, request, database, rawResults)
  File "/usr/local/lib/python3.5/dist-packages/pyArango/query.py", line 38, in __init__
    raise QueryError(self.response["errorMessage"], self.response)
pyArango.theExceptions.QueryError: VPack error: Expecting digit (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/GeneralServer/RestHandler.cpp:191). Please report this error to arangodb.com. Errors: {'code': 500, 'errorNum': 4, 'errorMessage': 'VPack error: Expecting digit (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/GeneralServer/RestHandler.cpp:191). Please report this error to arangodb.com', 'error': True}
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "zeenews_preprocessing_v2.py", line 2752, in <module>
    pool.starmap(raw_data_processing, zip(todoprocess_itemnodes, epochtime))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 268, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
pyArango.theExceptions.QueryError: VPack error: Expecting digit (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/GeneralServer/RestHandler.cpp:191). Please report this error to arangodb.com. Errors: {'code': 500, 'errorNum': 4, 'errorMessage': 'VPack error: Expecting digit (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/GeneralServer/RestHandler.cpp:191). Please report this error to arangodb.com', 'error': True}`
```
what might be the cause of error?

**Comment by dothebart** [comment] 2018-04-20 14:51
Hm, 
thats an exception thrown inside of arangodb; but the exception location is just the HTTP-gate. 
So without the query itself its pretty hard to reproduce this. 
Can you try upgrading to 3.3 and see whether this persists?

**Comment by Simran-B** [comment] 2018-04-25 18:26
I got different VPack errors when using Curl to make requests directly to the API, but with an invalid payload such as `{` (by accident). Could that be the error source, invalid JSON?

**Comment by dothebart** [comment] 2020-09-01 13:51
Closing since we can not find out anything more about this without further feedback.

**Closed by dothebart** 2020-09-01 13:51 UTC
Labels: 1 Bug, 3 AQL

**Comment by slava-shor-emporus** [comment] 2023-05-09 15:56
I can reproduce this error. A document has to contain an IEEE 754 float representing one of the following: positive infinity, negative infinity, or not a number. Using Python you define such as: `float("+inf")`, `float("-inf")`, `float("nan")`.

Any of such values will cause an exception: `aioarango.exceptions.DocumentInsertError: [HTTP 400][ERR 600] VPackError error: Expecting digit`

**Is there any way to work around such an issue?**

_As you can guess from the exception I am using Pyhtob library [aioarango](https://aioarango.readthedocs.io/en/latest/index.html) while running ArangoDB 3.10.2 community edition via Docker on MacOS M1 (Apple silicon.)_
