### ISSUE TITLE
Optimization issue

### ISSUE THREAD

**Issue by hellomanjack** [arangodb/arangodb#7560] opened 2018-11-30 07:00 UTC
arangodb 3.3.19 rocksdb singleton
Server: 32 core 64G
Just now I want to simulate randomly select situation. So I use the following aql:
for doc in tag 
filter doc._key in (FOR node IN (for entry in tag limit 10000 return entry._key)

![image](https://user-images.githubusercontent.com/25783698/49272893-18a8c280-f4ae-11e8-971e-2fef86dd394f.png)
![image](https://user-images.githubusercontent.com/25783698/49273004-7c32f000-f4ae-11e8-810e-3712abdd8efd.png)

Then I change the alq to the following sentence. Then the result comes out quickly.
let arr =(FOR node IN (for entry in tag limit 10000 return entry._key)
  SORT RAND()
  LIMIT 10000
  RETURN node)
 for doc in tag 
filter doc._key in arr
return doc 
![image](https://user-images.githubusercontent.com/25783698/49272990-6cb3a700-f4ae-11e8-997f-e51f7883936a.png)

So i guess there might be a Optimization problem. And sure "Explaining queries" gives the difference.It is a good habbit to "explaining the aql" before use.
![image](https://user-images.githubusercontent.com/25783698/49273551-59094000-f4b0-11e8-9730-6fafef92cf89.png)
![image](https://user-images.githubusercontent.com/25783698/49273612-8950de80-f4b0-11e8-9b21-4c9f880bfa50.png)

**Comment by graetzer** [comment] 2018-12-01 00:40
so the issue is that the second query wrongly removes `FILTER doc._key in arr` ?

**Comment by hellomanjack** [comment] 2018-12-03 07:02
@graetzer My original intention is that the aql could do better for the situation i have meet.  As you mentioned,  it indeed removes the "FILTER doc._key in arr" in the "Explain".  You are right.

**Comment by graetzer** [comment] 2018-12-03 13:30
I mean you are going over all your collections multiple times, it's just not really efficient

**Comment by hellomanjack** [comment] 2018-12-03 13:53
Yes,it is.

    
        
            
                
                    
                        
                    
                    
                        
                            刘贝贝
                            
                            
                                
                                    邮箱：liubeibei2job@gmail.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制
On 12/03/2018 21:31, Simon wrote: I mean you are going over all your collections multiple times, it's just not really efficient

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/arangodb/arangodb","title":"arangodb/arangodb","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/arangodb/arangodb"}},"updates":{"snippets":[{"icon":"PERSON","message":"@graetzer in #7560: I mean you are going over all your collections multiple times, it's just not really efficient "}],"action":{"name":"View Issue","url":"https://github.com/arangodb/arangodb/issues/7560#issuecomment-443710403"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/arangodb/arangodb/issues/7560#issuecomment-443710403",
"url": "https://github.com/arangodb/arangodb/issues/7560#issuecomment-443710403",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [arangodb/arangodb] Optimization issue (#7560)",
"sections": [
{
"text": "",
"activityTitle": "**Simon**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@graetzer",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"arangodb/arangodb\",\n\"issueId\": 7560,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"arangodb/arangodb\",\n\"issueId\": 7560\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/arangodb/arangodb/issues/7560#issuecomment-443710403"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 418150952\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by dothebart** [comment] 2020-09-02 09:50
Closing as outdated with the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/).

**Closed by dothebart** 2020-09-02 09:50 UTC
Labels: 1 Question, 3 AQL
