### ISSUE TITLE
Support for running the web interface behind a reverse proxy

### ISSUE THREAD

**Issue by chris-martin** [arangodb/arangodb#1558] opened 2015-11-03 00:54 UTC
I have a docker-compose setup with a handful of databases with web interfaces (elasticsearch, influxdb, arangodb) and an nginx container acting as a reverse proxy for them, so I can get to them at `localhost:8000/elasticsearch/`, `localhost:8000/influxdb/`, `localhost:8000/arangodb/`.

e.g. the bit of nginx config for arango is

```
location /arango/ {
  proxy_pass http://arango:8529/;
}
```

The problem is, unlike the others, ArangoDB's web interface doesn't work if it's not at the root URL. `localhost:8000/arango/` redirects to `http://localhost/arango/_db/_system/_admin/aardvark/index.html` (not sure why it strips the port out).

Workaround: If I go to `http://localhost:8000/arango/_db/_system/_admin/aardvark/standalone.html`, it seems to work. I don't know if the whole interface works that way, though, as I haven't figured out how to log in yet.)

The image I'm using is `arangodb/arangodb:2.7.0`.

**Comment by dothebart** [comment] 2015-11-03 10:15
duplicate of #1477

**Closed** 2015-11-04 12:34 UTC

**Comment by dothebart** [comment] 2015-11-04 12:36
You can download and replace the changed .js file to apply this fix for you.
You do however need two location matches:
        location /arango/ {
          allow all;
          proxy_pass http://127.0.0.1:8529/;
        }
        location /_db {
           allow all;
           proxy_pass http://127.0.0.1:8529/_db;
        }

**Comment by dothebart** [comment] 2015-11-04 12:57
now visible at https://docs.arangodb.com/cookbook/MakingFoxxAppAccessible.html#configure-the-proxy-server--nginx

**Comment by xygahs0801** [comment] 2017-10-15 08:07
If I have more port use arangodb in one server?
for example 8529 and 8530.

**Comment by casdevs** [comment] 2019-02-11 15:07
it's now possible to use custom base path for the arangodb web gui by
* setting `X-Script-Name` header in the reverse proxy configuration
* using `--frontend.proxy-request-check` and `--frontend.trusted-proxy` options when starting arangod

for details, please see
https://docs.arangodb.com/3.1/Manual/ReleaseNotes/NewFeatures30.html#web-admin-interface
