### ISSUE TITLE
Web high CPU load and memory consumption 

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#1717] opened 2016-02-09 16:59 UTC
Arango 2.8.1, Chrome browser. I have multiple tabs with web interface open and after some time, some of the tabs start to eat one cpu core and memory of that tab is slowly growing. This happens quite regularly. I'm not web developer, so the only think I was able to troubleshoot is to get some outputs from browsers dev console, see pictures. Messages in logs don't stop and are coming all the time.

![1](https://cloud.githubusercontent.com/assets/13378043/12923468/2c4e59a6-cf56-11e5-828e-276217e5c545.png)
![2](https://cloud.githubusercontent.com/assets/13378043/12923469/2c50c1aa-cf56-11e5-89ed-caf0132163f9.png)

**Comment by dothebart** [comment] 2016-02-09 18:32
The graphs in the main dashboard are known to eat memory / cpu. Do you have these open? or just database / document views?

**Comment by roman1720** [comment] 2016-02-09 18:36
No graphs, in this particular tab I was only working in Collections. It starts randomly after some time when I'm not working with tab.

**Comment by baslr** [comment] 2016-02-09 23:51
Hi @roman1720,
please take heap snapshots. In the developer toolbar 
![bildschirmfoto 2016-02-10 um 00 45 32](https://cloud.githubusercontent.com/assets/1494154/12934547/a0e2abb2-cf8f-11e5-9f71-26b592e58b17.png)
first when you started the frontend and second when you feel it slows down. You can save the snapshot and attach it to this issue.

**Comment by roman1720** [comment] 2016-02-11 08:57
Yesterday it didn't occurred, strange, as before it happened multiple times in day. But today it's here again. See two links for snapshots. They are from two different tabs, but being open equally long. The bigger file is from affected tab. I hope it will help to identify issue.

https://www.dropbox.com/s/tcuykpco7txlldt/Heap-20160211T093845.zip?dl=0
https://www.dropbox.com/s/ze1tmeg7skynxyx/Heap-20160211T094941.zip?dl=0

**Comment by baslr** [comment] 2016-02-11 21:06
Hi @roman1720,

thanks for your work. To compare the allocations I need the snapshots from one tub. But I found that the Request Statistics pages leaks, so as long as you stay away / navigate away from that page the tub will survive without allocating more and more ram.

**Comment by roman1720** [comment] 2016-02-12 09:55
You are right, it's leaking from statistics page. Here are two snapshots from one tab, one without leaking before stats page is visited, the second (bigger file) after. It's affecting only me? You don't have this problems?

https://www.dropbox.com/s/d7yuiun9oqjcon6/Heap-20160212T103001.zip?dl=0
https://www.dropbox.com/s/irci06lz3jnagkk/Heap-20160212T104422.zip?dl=0

**Comment by baslr** [comment] 2016-02-13 21:38
I have only short session with the web interface. I guess every one is affected.

**Comment by razvanphp** [comment] 2016-02-13 22:10
I can confirm this, from time to time I can hear the FAN of my mac, and it's most of the times one tab of arango web interface. If I refresh it goes away. I will also try to make a snapshot when it happens next time. *subscribed*popcorn*

**Comment by baslr** [comment] 2016-02-14 03:04
You could also record a timeline for 60s or so. But first hit the trashcan icon (garbage collection)

**Comment by baslr** [comment] 2016-02-24 13:07
@razvanphp popcorntime ;)
(gc before start and stop recording for ~60sec)
I had two tabs open for at least overnight:
![bildschirmfoto 2016-02-24 um 13 40 35](https://cloud.githubusercontent.com/assets/1494154/13285698/44c66152-dafc-11e5-8c69-3d8b2c36f9aa.png)
/aardvark/standalone.html#collections 

![bildschirmfoto 2016-02-24 um 13 45 54](https://cloud.githubusercontent.com/assets/1494154/13285786/f731c9e4-dafc-11e5-952a-53a1ce8f181f.png)
/aardvark/standalone.html#query

for comparison a new / reloaded /aardvark/standalone.html#query tab
![bildschirmfoto 2016-02-24 um 13 52 23](https://cloud.githubusercontent.com/assets/1494154/13285887/e56943ee-dafd-11e5-9055-3bdaa7634e54.png)

For /aardvark/standalone.html#collections memory consumption increased by 2500%.
For /aardvark/standalone.html#query memory consumption increased by 600%.

**Comment by hkernbach** [comment] 2016-02-24 13:51
Hello, thank you for your help to track down the issue.

> For /aardvark/standalone.html#collections memory consumption increased by 2500%.
For /aardvark/standalone.html#query memory consumption increased by 600%.

Did you do a fresh reload on those views? Or was your starting point the dashboard (statistics), and then switched to #collections and #query? I also believe that the problems origin is the dashboard.

**Comment by baslr** [comment] 2016-02-24 13:59
I usually start from 127.0.0.1:8529; will do another test tonight.

**Comment by baslr** [comment] 2016-02-25 06:57
@roman1720 @hkernbach 
night is over. direct loaded collections / query; js heap is ~140 MiB and not increasing.

**Comment by uditha-atukorala** [comment] 2016-06-13 13:40
I noticed this issue as well on v2.8.9 and had a little look.

It seems like [cutOffHistory()](https://github.com/arangodb/arangodb/blob/2.8/js/apps/system/_admin/aardvark/APP/frontend/js/views/dashboardView.js#L349) is not clearing history for **pageFaults**, **systemUserTime**, **totalTime**, **dataTransfer**, **request** items due to data being ordered in date descending order. 

Not sure 06e40476f7177071fc82b957cfa455253a7d2fa7 is meant to be a fix for this issue or a fail-safe though.

**Closed** 2016-06-14 14:27 UTC
Labels: 1_Bug, front-end
