### ISSUE TITLE
Arango 3.6.5 crashing on Windows

### ISSUE THREAD

**Issue by robross0606** [arangodb/arangodb#12782] opened 2020-10-06 00:16 UTC
## My Environment

* __ArangoDB Version__:        3.6.5
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Windows Service
* __Configuration__:               Default settings
* __Infrastructure__:               own
* __Operating System__:        Windows 10 Pro Build 19041.508
* __Total RAM in your machine__:       32GB
* __Disks in use__:        500GB SSD, 124GB free
* __Used Package__:              Windows Installer

## Component, Query & Data

__Affected feature__:
The entire server crashes.

__AQL query (if applicable)__:
N/A

__AQL explain and/or profile (if applicable)__:
N/A

__Dataset__:
N/A

__Size of your Dataset on disk__:
N/A

__Replication Factor & Number of Shards (Cluster only)__:
N/A

## Steps to reproduce

1. Run unit tests
2. Arangodb.exe crashes randomly

__Problem__:
Sometimes my unit tests succeed without issue.  Other times the entire Arango service crashes with entries in the Windows Event Log.  There are zero issues reported in the Arango logs.  

```
Faulting application name: arangod.exe, version: 3.6.0.5, time stamp: 0x5f0ed1df
Faulting module name: arangod.exe, version: 3.6.0.5, time stamp: 0x5f0ed1df
Exception code: 0xc0000005
Fault offset: 0x0000000000ffad17
Faulting process id: 0x156c
Faulting application start time: 0x01d6973610be6d71
Faulting application path: C:\Program Files\ArangoDB3 3.6.5\usr\bin\arangod.exe
Faulting module path: C:\Program Files\ArangoDB3 3.6.5\usr\bin\arangod.exe
Report Id: 119f4fca-0649-4e20-93e2-4a3ca4dd5220
Faulting package full name: 
Faulting package-relative application ID: 
```

I have attached the Windows events documenting the crash:

[Arango Crash.zip](https://github.com/arangodb/arangodb/files/5330704/Arango.Crash.zip)

__Expected result__:
The database system should NOT crash out the entire server with no meaning full error logs.

**Comment by dothebart** [comment] 2020-10-06 10:13
I can't read the contents of the zip on linux.
Please use a readable plaintext file.

**Comment by mpoeter** [comment] 2020-10-06 17:11
@robross0606 do you happen to have a minidump from the crash that you can share?

**Comment by robross0606** [comment] 2020-10-06 17:14
> I can't read the contents of the zip on linux.
> Please use a readable plaintext file.

I already included the relevant text in the original ticket.  The Windows Event export is supplemental and contains basically the same information.

**Comment by robross0606** [comment] 2020-10-06 17:16
> @robross0606 do you happen to have a minidump from the crash that you can share?

@mpoeter, if one exists from the crash, I haven't been able to find it.  Arango itself gave ZERO indication that it even crashed.  There was absolutely nothing in the log files at all.  I cannot reproduce the problem consistently enough to enable special crash dumps.  It has happened maybe five times over the course of of the last couple weeks.

**Comment by mpoeter** [comment] 2020-10-06 20:07
Excellent! I had a look at the two latest dumps and both crashes seem to be caused by the same issue. Here is the stacktrace I could extract:
```
0b (Inline Function) --------`--------     arangod!arangodb::velocypack::readIntegerFixed+0x6 [c:\vm02-windows\oskar\work\arangodb\3rdparty\velocypack\include\velocypack\velocypack-common.h @ 213] 
0c 000000a9`fb5f8510 000001f5`73b21010     arangod!arangodb::velocypack::Slice::searchObjectKeyBinary<4>+0x87 [c:\vm02-windows\oskar\work\arangodb\3rdparty\velocypack\src\slice.cpp @ 603] 
```
The fautling code looks like this:
```
.text:00007FF719F2ACF0 loc_7FF719F2ACF0:                       ; CODE XREF: sub_7FF719F2AC90+19F↓j
.text:00007FF719F2ACF0                 mov     r13, [rcx]
.text:00007FF719F2ACF3                 lea     rax, ds:0[rdi*4]
.text:00007FF719F2ACFB                 add     rax, r13
.text:00007FF719F2ACFE                 mov     edx, 0
.text:00007FF719F2AD03                 add     rax, rbx
.text:00007FF719F2AD06                 mov     r10, r15
.text:00007FF719F2AD09                 mov     ebx, 3
.text:00007FF719F2AD0E                 mov     r11, r15
.text:00007FF719F2AD11                 mov     r8d, 8
.text:00007FF719F2AD17                 movzx   ebp, byte ptr [rax]   <--- crash
.text:00007FF719F2AD1A                 lea     rcx, [rax+4]
.text:00007FF719F2AD1E                 inc     rax
.text:00007FF719F2AD21                 cmp     rax, rcx
.text:00007FF719F2AD24                 cmova   ebx, edx
```
I was able to extract the register values from one of the dumps:
```
rax=000001f508c38c6a rbx=0000000000000003 rcx=000000a9fb5f8770
rdx=0000000000000000 rsi=0000000000000000 rdi=000000000000007f
rip=00007ff719f2ad17 rsp=000000a9fb5f8510 rbp=0000000000d0490b
 r8=0000000000000008  r9=0000000000d04901 r10=0000000000000000
r11=0000000000000000 r12=000000a9fb5f86d0 r13=000001f507f34163
r14=00000000000000ff r15=0000000000000000
```
What is noticable is that the address in rax is neither close to null, nor to a page boundary. To me this looks like the velocypack value is encoded incorrectly.

@robross0606 what driver do you use to talk to the DB?

**Comment by robross0606** [comment] 2020-10-06 20:13
> @robross0606 what driver do you use to talk to the DB?

This is a Node.js app using arangojs v6.14.1

**Comment by robross0606** [comment] 2020-10-11 00:08
Just crashed again.  I noticed another event in the Windows Event Log which might be useful:
```
The description for Event ID 256 from source ArangoDB cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

[feaa2] {queries} [query#694554] Internal velocypack Error thrown by type=EnumerateCollectionNode id=3 Message: Expecting type String
C:\vm02-windows\oskar\work\ArangoDB\arangod\Aql\ExecutionBlockImpl.cpp
arangodb::aql::ExecutionBlockImpl<class arangodb::aql::EnumerateCollectionExecutor>::getSome
137

The locale specific resource for the desired message is not present
```


I've also attached another crash dump.
[arangod.exe.25196.dmp.zip](https://github.com/arangodb/arangodb/files/5360427/arangod.exe.25196.dmp.zip)

**Comment by mpoeter** [comment] 2020-10-11 17:28
Thanks, this seems to confirm my suspicion that the velocypack is corrupt. Can you share the code of your tests that cause these crashes?

@dothebart any thougts?

**Comment by robross0606** [comment] 2020-10-11 17:38
Sadly, I have no idea which tests are causing the issue in our suite, and I cannot simplify or share the whole code base.

**Comment by dothebart** [comment] 2020-10-12 07:46
Hi, 
`EnumerateCollectionNode` means that you do a full collection scan without index utilization. 
It would be good, if you could share your database - can you send it to hackers at arangodb or upload it to a site? 

If you could insulate the collection where this happens this would be good. A query like 

```
let y = FOR x IN @@collection
             RETURN 1
RETURN y
```

should most probably reproduce this.

**Comment by robross0606** [comment] 2020-10-12 12:48
I could generate all the data from our unit tests and send that, but I would need a location to post it.  I'm not sure what you're suggesting for the second option.  To reiterate, _I have no idea where this happens in our code._  Arango throws no errors and reports no meaning full logs.  It simply intermittently crashes.  If it provided even a modicum of information about where this was occurring, I would happily instrument to debug it.  Our code base is thousands of lines.  Even our unit test coverage is thousands of lines across many files.

**Comment by dothebart** [comment] 2020-10-12 13:06
do you have a binary or similar that we could run?

**Comment by robross0606** [comment] 2020-10-12 13:07
No, it is a Node.js application.  We have never seen this problem during regular runtime.  Only during unit tests execution.

**Comment by robross0606** [comment] 2020-10-12 13:14
I can definitely share output from a successful run of the unit tests.  I can also do a dump of the unit tests database the next time this issue occurs.  It is intermittent so I cannot reproduce it on demand, even running the exact same suite of unit tests over and over does not reproduce the problem with any consistency.

**Comment by robross0606** [comment] 2020-10-12 14:00
We're _so_ lucky.  The crash literally _just_ occurred again right now.  Here is the crash dump.  I will capture the database output and can provide as soon as a target location is given.

**Comment by robross0606** [comment] 2020-10-12 14:13
One thing I want to put out there as a potential cause is the way we create and drop collections for unit tests.  This isn't something that happens for regular runtime, which may be why we never see problems there.  The unit tests will stand up and break down a set of unique collections for subsets of unit tests.  This is why you will see unique ID postfixes on collections which otherwise have the same name.  This is done to avoid concurrent test execution issues.  I'm wondering if perhaps something about the rapidity of that activity might be causing an issue?

**Comment by dothebart** [comment] 2020-10-12 14:26
hm, do you have a full collection scan running while you delete the collection?
```
                        <Data>[feaa2] {queries} [query#642388] Internal velocypack Error thrown by type=EnumerateCollectionNode id=3 Message: Expecting type String</Data>
                        <Data>C:\vm02-windows\oskar\work\ArangoDB\arangod\Aql\ExecutionBlockImpl.cpp</Data>
                        <Data>arangodb::aql::ExecutionBlockImpl&lt;class arangodb::aql::EnumerateCollectionExecutor&gt;::getSome</Data>
                        <Data>137</Data>
```
`getSome` is the interface to fetch a chunk of documents.

**Comment by robross0606** [comment] 2020-10-12 14:29
I honestly don't know what you mean by "a full collection scan".  It feels like you're talking at a slightly different level of semantics than most people who use Arango.  If you're referring to doing a "query" on a collection, then, no, Jest should not be doing that since the breakdown of collections doesn't happen until all tests have completed.

**Comment by dothebart** [comment] 2020-10-12 14:33
a full collection scan means that you iterate over all documents in the collection without using an index. 
Indices get added if you have filters or sorts in your AQL query. 
A full collection scan has to fetch all documents from the collection, and work with each one of them one by one. `EnumerateCollectionNode` is the element that does this.
In contrast to this a `IndexNode` would be placed, if you have a `FILTER` statement that uses an index.

**Comment by robross0606** [comment] 2020-10-12 14:36
I cannot think of a single place in our code where we're iterating over every document in a collection without a filter.

> Indices get added if you have filters or sorts in your AQL query.

I thought indexes had to be added manually.  Your comment implies indexes are added automatically if you use `FILTER` in your query?

**Comment by robross0606** [comment] 2020-10-12 14:39
Is there any way from the dump to tell the name of the collection being iterated or anything else about the original AQL?  We have a _lot_ queries here, so I could really use a little more to go on.

**Comment by dothebart** [comment] 2020-10-12 14:47
I think I found something in that crashdump using `strings` which could be the offending query: 
```
COLLECT AGGREGATE\n                maxOrdinal
```
(I may edit and add the full query if you consent?)

**Comment by robross0606** [comment] 2020-10-12 14:48
Bingo!  That's _extremely_ helpful.  I've been looking through the code trying to find places where we might have a "full collection scan" and that is one I bookmarked as a potential.

**Comment by robross0606** [comment] 2020-10-12 14:54
The problem is that this query is setting an ordinal on new (or updated) data, which means it is leveraged through many places in the code.  Sometimes, this "max ordinal" needs to be calculated across more than one collection.  The particular piece of code generating the offending query looks something like this:
```js
      // Determine the max ordinal relative to the set of collections.
      const collectionSet = new Set([collection])
      const siblingTypes = this.getOrdinalRelativeSiblings(type)
      for (const siblingType of siblingTypes) {
        collectionSet.add(await this.getCollection(siblingType, false, true))
      }
      const collectionArray = Array.from(collectionSet)

      // Find the max for each collection
      const maxOrdinalQueryParts = new Map()
      for (const i in collectionArray) {
        const key = `collectionMax${i}`
        maxOrdinalQueryParts.set(
          key,
          aql`
            LET ${aql.literal(key)} = ( FOR doc IN ${collectionArray[i]}
            COLLECT AGGREGATE
                maxOrdinal = MAX(doc.ordinal)
            return maxOrdinal == null ? 0 : maxOrdinal )[0]
            `
        )
      }

      // Get the max of all maxes across all the collections
      const maxOfMaxesQueryPart = aql`
        LET maxOfAll = MAX([${aql.literal(Array.from(maxOrdinalQueryParts.keys()).join(','))}])
      `

      // Get the resulting updated document
      const updateQueryPart = aql`
          LET doc = DOCUMENT(${doc._id})
          LET updated = (FILTER doc.ordinal != maxOfAll
                          UPDATE doc
                          WITH { ${field}: maxOfAll + 1 }
                          IN ${collection}
                          RETURN NEW)
          RETURN updated[0] ? updated[0] : doc
        `

      const maxOrdinalQueryPartsArr = Array.from(maxOrdinalQueryParts.values())
      query = aql.join([...maxOrdinalQueryPartsArr, maxOfMaxesQueryPart, updateQueryPart])

    return this.runQuery(ctx, query)
```

**Comment by dothebart** [comment] 2020-10-12 15:00
`strings arangod.exe.*.dmp | grep '"query' | less` will only show this query in the latest dump - but there its alone. 
we have several ones with `COLLECT AGGREGATE maxLength`, `FOR doc, l, path IN 1..10 INBOUND`, `FOR obj, l, p IN 1..1 INBOUND`, `UPSERT { compositeId` 
in the other dumps.

**Comment by robross0606** [comment] 2020-10-12 15:01
oh, so this isn't one consistent problem?

**Comment by dothebart** [comment] 2020-10-12 15:03
should I post the full list?

**Comment by robross0606** [comment] 2020-10-12 15:04
No, that's okay, I can grep that myself

**Comment by dothebart** [comment] 2020-10-12 15:20
at first its a memory dump. Memory is used and discarded. so this *may* be related, or have been a recently finished query, or there may be multiple copies of it around the place. 
Once that memory is re-used, the strings will be overwritten. 
So in this dump with the very one query the confidence is pretty high that this is whats executed - since its what the logging indicates, that there is a query going on while the exception is re-thrown.

**Comment by robross0606** [comment] 2020-10-12 15:24
Ahh, I see.  That one particular dump only has a single query in it, so the assumption can be made that this is the cause.  But since all the other dumps don't contain this particular "one query", we can have equally high confidence that this isn't the _only_ cause of the crashes?  Either way, I've been able to use the information in the dumps to at least pinpoint which specific functions in the code were executing across all the dumps, even if we don't have high confidence which ones causing it.

**Comment by dothebart** [comment] 2020-10-12 15:37
ok. It would be good if you could write an insulated testcase reproducing this that you could share with us, so we can better understand whats actually going on.

**Comment by robross0606** [comment] 2020-10-12 15:41
How can I write you a test case that reproduces it if I cannot reproduce it consistently and don't know which query is causing it?

**Comment by robross0606** [comment] 2020-10-12 15:52
I'm still offering to send my database content, but haven't been given a location to post it.  I cannot post it to this public location.

**Comment by Simran-B** [comment] 2020-10-28 12:02
@robross0606 You can send us a mail with the database content to hackers@arangodb.com - or is it really large? Then we can find other means to transfer it privately.

**Comment by robross0606** [comment] 2020-10-28 12:31
@Simran-B,  I have two files to upload.  Each one is about 25MB.

**Comment by Simran-B** [comment] 2020-11-11 15:47
Please check our community slack, we will send to credentials and instructions how to share the data.

**Comment by robross0606** [comment] 2020-11-11 17:08
Files have been uploaded as promised.

**Comment by Simran-B** [comment] 2020-12-09 15:55
Closing, as we couldn't reproduce the problem. Please re-open if you can reproduce locally on another OS.

**Closed by Simran-B** 2020-12-09 15:55 UTC
Labels: 1 Bug, 3 AQL, 4 Windows, Waiting User Reply
