### ISSUE TITLE
Write-ahead log REST API throwing HTTP 501 in single-server mode.

### ISSUE THREAD

**Issue by joowani** [arangodb/arangodb#4951] opened 2018-03-26 07:22 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: 
- [ ] MacOS, version:

For example:
`GET /_db/_system/_admin/wal/properties`
`GET /_db/_system/_admin/wal/transactions` 

Respond with HTTP 501 Not Implemented
This seems to happen in single-server mode only.
I started observing this issue in ArangoDB versions 3.3.3 and 3.3.4.
It works fine in 3.3.2.

**Comment by OmarAyo** [comment] 2018-03-26 18:32
Hi @joowani ,

Thank you for using ArangoDB and opening this ticket

I have tried to reproduce this issue on my local Windows machine and I was not able to reproduce it, unfortunately 

I am uploading a screenshot in case is it useful 

![image](https://user-images.githubusercontent.com/32968582/37925391-affc67ec-3134-11e8-80da-108f9fa5afae.png)

Many thanks

**Comment by joowani** [comment] 2018-03-27 01:31
That is strange. This is what I see:

![wal](https://user-images.githubusercontent.com/2701938/37941593-cfae5ee4-3123-11e8-92b2-1c7fd8f27ef4.png)

Is there a log of some sort that I could provide you to help you investigate?

**Comment by OmarAyo** [comment] 2018-03-27 20:54
Hi @joowani 

I am analyzing your issue on different version like 3.3.4, 3.3.3 and 3.3.2 but I still can not reproduce it.
Since you mentioned that request method worked in 3.3.2, could you please try also in that version and upload a screenshot here.

Please note that the **501 not implemented** error indicates that the server does not support the functionality required to fulfill the request. This is the appropriate response when the server does not recognize the request method and is not capable of supporting it for any resource - so since I can perform the request on all the above-mentioned versions I think that is not version related. 

Best.

**Comment by joowani** [comment] 2018-03-30 12:39
Hi, I am not having the issue anymore with 3.3.5. After installation of the new version I am unable to reproduce it either.

**Comment by OmarAyo** [comment] 2018-03-30 12:42
Hi @joowani 

I am happy to know that you are not facing this issue anymore. 
I am going to close this ticket, feel free to reopen it if any time for any related issues. 

Best

**Closed by OmarAyo** 2018-03-30 12:42 UTC
Labels: 1 Question, 2 Cannot Reproduce, 2 Solved, 3 API
