### ISSUE TITLE
Failed to fetch graph information: Internal Server Error

### ISSUE THREAD

**Issue by aoighost** [arangodb/arangodb#2254] opened 2017-01-11 00:48 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version:  10
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS: windows 10
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as a user
3) use database [ ] `_system` [x ] other: 
4) graph and open a graph
5) error

The following problem occurs: https://i.imgur.com/16kTHhO.png
Instead I would be expecting: 
a graph

**Comment by aoighost** [comment] 2017-01-11 04:00
New info on the error, it looks like it isn't recognising my graph has contents in it: https://i.imgur.com/dW5speV.png

**Comment by dothebart** [comment] 2017-01-12 11:54
Did you do a proper graph definition? i.e. the tiny example graphs create those. 
You also can browse the `_system`-collection `_graphs` to inspect it.

**Comment by aoighost** [comment] 2017-01-12 12:00
Running: 
`For g in _graphs
    return g`

I get
`[
  {
    "_key": "navrie",
    "_id": "_graphs/navrie",
    "_rev": "_UXIG0wi---",
    "edgeDefinitions": [],
    "orphanCollections": [
      "NetworkAddresses"
    ]
  }
]`

**Comment by aoighost** [comment] 2017-01-12 12:04
@dothebart also, this is the contents of the NetworAddresses collection

`[
  {
    "_key": "b569c0dd-3462-4814-a331-95bff4f7c676",
    "_id": "NetworkAddresses/b569c0dd-3462-4814-a331-95bff4f7c676",
    "_rev": "_UXIG0z2---",
    "NetworkAddress_Address": "8.8.8.8",
    "NetworkAddress_Type": "IPv4"
  }
]`

**Comment by dothebart** [comment] 2017-01-12 12:42
you need to have proper edge definitions, have a look at: https://docs.arangodb.com/3.1/HTTP/Gharial/Management.html for working ones. Which interface did you use to create that definition?

**Comment by aoighost** [comment] 2017-01-12 13:03
I'm using Python-Arango with Python 3, I'll look at the edges and get it fixed.

**Comment by dothebart** [comment] 2017-01-12 13:05
I actually didn't use python-arango to create graphs yet. On your creation you fail to assign the edge definitions to the graph object - if that helps.

**Comment by aoighost** [comment] 2017-01-13 07:43
Still working on fixing it, although the fact that it tosses a 500 error with such a generic message on this doesn't give me much faith in the code base as a pentester. There should be a hell of a lot better  error and contingency handling, the logging in web app is on point, but this shouldn't cause breakages in the first place.

**Comment by dothebart** [comment] 2017-02-14 14:25
Sorry to come back to you so late, 
Can you provide simple sample code reproducing this issue?

**Comment by dothebart** [comment] 2017-07-21 11:29
Hi, 
We're pleased to anounce that ArangoDB 3.2. 
Since there has been no change to this issue I will close this now.

**Closed by dothebart** 2017-07-21 11:29 UTC
Labels: 1 Question
