### ISSUE TITLE
Web UI - problem displaying collections that are being warmed up

### ISSUE THREAD

**Issue by sergionov** [arangodb/arangodb#3438] opened 2017-10-17 08:03 UTC
## My environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X] 3.2

Mode:
- [X] Cluster

Storage-Engine:
- [X] mmfiles

On this operating system:
- [ ] Linux 
  - [ ] Ubuntu .deb

We were in 3.1.27 and decided to set up a cluster, so we upgraded to 3.2.3. After that, we set up the cluster and deployed it with Docker. The config is 3 coordinators and 2 db_servers. Yesterday, we upgraded to 3.2.4.

This is an example of coordinator configuration in docker-compose file:
```
coordinator1:
  image: arangodb/arangodb
  environment:
  - ARANGO_NO_AUTH=1
  command: arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://coordinator1:8529 --cluster.my-local-info coord1  --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://agency1:8529 --log.file /var/log/arangodb3/arangod.log
  volumes:
  - ./data/c1:/var/lib/arangodb3
  - ./apps/c1:/var/lib/arangodb3-apps
  - ./logs/c1:/var/log/arangodb3
  ports: ['8629:8529']
  depends_on:
  - agency1
```

And this is an example of db server:
```
db1:
  image: arangodb/arangodb
  environment:
  - ARANGO_NO_AUTH=1
  command: arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://db1:8529 --cluster.my-local-info db1 --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://agency1:8529 --log.file /var/log/arangodb3/arangod.log
  volumes:
  - ./data/d1:/var/lib/arangodb3
  - ./logs/d1:/var/log/arangodb3
  depends_on:
  - agency1
  - coordinator1
  - coordinator2
```

### this is a web interface-related issue:
I'm using the web interface with this browser:  Chrome   running on this OS: Ubuntu 16.04
- [X] authentication is enabled?
- [X] using the cluster?
- [X] _system database?

These are the steps to reproduce:
1) open the browser and got to my local web UI
2) log in as root
3) use database [ ] `_system` [X] other: "assistant"
4) click to any collection
5) There are some pages with documents, but documents are not visible

The following problem occurs:
The web UI display various pages in collection but documents are not displayed
![captura de pantalla de 2017-10-17 09-52-05](https://user-images.githubusercontent.com/9535909/31652882-f9f0a918-b320-11e7-8270-22972300967e.png)

Instead I would be expecting: 
Documents displayed in collection view
![captura de pantalla de 2017-10-17 09-53-43](https://user-images.githubusercontent.com/9535909/31652939-2578c55c-b321-11e7-990e-52838f494346.png)

**Comment by maxkernbach** [comment] 2017-10-17 14:59
Hello, can you attach the dump of your database with arangodumb in order to reproduce the problem?

**Comment by sergionov** [comment] 2017-10-17 16:32
Sure! This is the file: 
[arango_dump.zip](https://github.com/arangodb/arangodb/files/1391832/arango_dump.zip)

**Comment by sleto-it** [comment] 2017-10-27 05:13
Hi @sergionov ,

Thank you for opening this issue. I have reproduced the problem with v. 3.2.5
We will work to find a fix

Thanks again,

**Comment by sleto-it** [comment] 2017-10-27 14:33
Hi @sergionov,

We have pushed a fix for this problem in v. 3.2.6, which has been released today
Please let us know if there is anything else we can do to help you or we can close this ticket

Many thanks,

**Comment by arochaga** [comment] 2017-10-30 10:05
Hi, I am from @sergionov team.
We just deployed a brand new ArangoDB 3.2.6 cluster with an agency of three coordinators and two databases completely from scratch. We create a collection with two documents as a test and the bug is still there. You may see in the screenshot that the two docs where stored but the WebUI does not show them.

![image](https://user-images.githubusercontent.com/6717133/32165129-0e3823b0-bd62-11e7-8cb4-b7ab117a2091.png)

**Comment by arochaga** [comment] 2017-10-30 14:21
Hi,

New info about this issue in case it is useful. When running a single instance of Arango 3.2.6 using Docker (in the same environment we are running our cluster mentioned in the previous comment), the problem is fixed and we can see the documents inside the collections.

Apparently the problem of being unable to see the documents inside a collection comes when running an Arango cluster and not with individual instances.

Thank you for your help,

**Comment by dothebart** [comment] 2017-11-06 10:10
Hi, 
This is a problem that occurs during the loading of collections. 
The UI should show a throbber while the server is warming up the collection, and load the dataset to show once thats done.

**Comment by dothebart** [comment] 2020-09-01 11:59
Hi, 
with ArangoDB 3.7 support for the MMFiles storage engine has been dropped. 
Please find the release note here:
https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/

**Closed by dothebart** 2020-09-01 11:59 UTC
Labels: 1 Feature, 3 UI
