### ISSUE TITLE
Using COLLECT/AGGREGATE/INTO on zero rows returns null.

### ISSUE THREAD

**Issue by meenie** [arangodb/arangodb#9774] opened 2019-08-20 20:03 UTC
## My Environment

* __ArangoDB Version__:  3.4.7      
* __Storage Engine__:  RocksDB            
* __Deployment Mode__: Single Server       
* __Deployment Strategy__: Manual Start (local)   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__: MacOS  10.14.5      
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__: `AGGREGATE`

__AQL query (if applicable)__:
```
for doc in [{num: 1, sum: 10}, {num: 1, sum: 20}, {num: 2, sum: 30}, {num: 2, sum: 40}, {num: 3, sum: 50}]
    filter doc.num in [11,21,31]
    
    collect nums = doc.num
    aggregate sums = sum(doc.sum)
    into group 
    
    return sums
```

__AQL explain (if applicable)__:

```
Query String:
 for doc in [{num: 1, sum: 10}, {num: 1, sum: 20}, {num: 2, sum: 30}, {num: 2, sum: 40}, {num: 3, 
 sum: 50}]
     filter doc.num in [11,21,31]
     
     collect nums = doc.num
     aggregate sums = sum(doc.sum)
     into group 
     
     return sums

Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  2   CalculationNode        1     - LET #4 = [ { "num" : 1, "sum" : 10 }, { "num" : 1, "sum" : 20 }, { "num" : 2, "sum" : 30 }, { "num" : 2, "sum" : 40 }, { "num" : 3, "sum" : 50 } ]   /* json expression */   /* const assignment */
  3   EnumerateListNode      5     - FOR doc IN #4   /* list iteration */
  4   CalculationNode        5       - LET #6 = (doc.`num` in [ 11, 21, 31 ])   /* simple expression */
  5   FilterNode             5       - FILTER #6
  6   CalculationNode        5       - LET #8 = doc.`num`   /* attribute expression */
 10   SortNode               5       - SORT #8 ASC
  7   CalculationNode        5       - LET #10 = doc.`sum`   /* attribute expression */
  8   CollectNode            5       - COLLECT nums = #8 AGGREGATE sums = SUM(#10)   /* sorted */
  9   ReturnNode             5       - RETURN sums

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   remove-collect-variables
  6   move-calculations-down

```

## Steps to reproduce

1. Run the above query
2. Notice the output is `[ null ]` instead of `[]`

__Problem__:
When using `INTO` along with an `AGGREGATE` query when all docs have been filtered out, the return of the aggregate is `null` rather than just "nothing".  If you remove the `INTO group` in the query above, then the `AGGREGATE` returns "nothing" and the result is `[]`

__Expected result__:
It should return `[]` not `[ null ]`.

**Comment by Simran-B** [comment] 2020-01-27 11:31
Can't reproduce in 3.5.4, 3.6.0 and current devel, but it does return `[ null ]` in 3.4.9 (latest).

**Comment by dothebart** [comment] 2020-09-03 11:39
Hi, 
please note that Arangodb 3.4 is EOLed.

[ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available now - hence closing this.

**Closed by dothebart** 2020-09-03 11:39 UTC
Labels: 1 Bug, 3 AQL
