### ISSUE TITLE
How to change data location?

### ISSUE THREAD

**Issue by AlexLuya** [arangodb/arangodb#5954] opened 2018-07-23 12:51 UTC
Sorry to ask such junior question,and I can't google it out

**Comment by maxkernbach** [comment] 2018-07-24 09:33
Hi @AlexLuya, 

you can set a custom database-directory path in `arangod.conf` by adjusting the line `directory = /var/lib/arangodb3` to `directory = /path/to/your/directory`.

On Ubuntu, this file is located at `/etc/arangodb3/arangod.conf` when using the standard package installation. The permissions of this directory have to be adjusted for user **arangodb**, e.g. on Ubuntu:

owner can read, write and execute:
```
chmod 700 /path/to/your/directory
```
recursively change owner of folder:
```
chown -R arangodb:arangodb /path/to/your/directory
```

**Comment by OmarAyo** [comment] 2018-07-30 07:22
Hi @AlexLuya 

Just sending a quick followup - was maxkernbach's latest message useful for you?

Looking forward to your reply

Best

**Comment by OmarAyo** [comment] 2018-08-06 08:50
Hi @AlexLuya

**Comment by OmarAyo** [comment] 2018-08-06 08:52
Hi @AlexLuya 

I am closing this issue as solved for now.
Please feel free to comment and reopen in case you have further questions.

Best,

**Closed by OmarAyo** 2018-08-06 08:52 UTC
Labels: 1 Question, 2 Solved, 3 Core, Waiting User Reply

**Comment by annguyenliaison** [comment] 2019-02-14 08:28
Hi,

I'd like to move arangodb database directory to another location as I don't want to increase the size of FileSystem.
Currently it's /opt/arangodb and I'd like to move it to /opt/apps/arangodb. Is it possible without any corruption?

Thanks,
An

**Comment by Simran-B** [comment] 2019-02-14 13:38
As long as nothing touches the data (i.e. server is fully shut down) moving the files should not pose any problem. However, I recommend to **copy** the data to the new location, change the configuration, then bring the server back up before deleting the files in the original location. You may also want to create a backup before moving anything. I don't see any reason why corruption caused by ArangoDB could occur if you move the files (as long as the server is not running), but there could be other interfering processes on your system.
