### ISSUE TITLE
Internal error of ArangoDB with "Please report this error to arangodb.com"

### ISSUE THREAD

**Issue by DeShadow** [arangodb/arangodb#3253] opened 2017-09-14 08:03 UTC
ArangoDB 3.2.2

ArangoDB returned error:
```
AQL: cannot enter V8 context (exception location:
/var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/Aql/Query.cpp:1065).
Please report this error to arangodb.com (while executing) (exception location:
/var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/RestHandler/RestCursorHandler.cpp:130).
Please report this error to arangodb.com
```

**Comment by DeShadow** [comment] 2017-09-14 08:43
I found that before many these errors was:
```
out of memory (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/lib/Basics/VelocyPackDumper.cpp:305)
```

**Comment by jsteemann** [comment] 2017-09-14 08:56
The latter one (VelocyPackDumper.cpp) is an actual out of memory error. It will occur when the OS does not provide more memory to ArangoDB when writing the JSON representation of some value into a stream.

The former errors (Query.cpp and RestCursorHandler.cpp) do occur when an AQL query tries to make use of V8 but cannot enter an unused V8 context in some reasonable time. Have there been some warnings in the logs before, such as "giving up waiting for unused V8 context after X s"? That would mean no unused V8 contexts were available for some time, and the operation timed out waiting for them. This may happen when more threads try to enter/use V8 contexts in parallel than there are available V8 contexts. The maximum number of V8 contexts is determined by the variable `--javascript.v8-contexts`, if set. If not set, then the number is determined by `--server.threads`. If not set either, then it will be the number of available/visible cores at server start. That value may or may not be appropriate for your workload. It may be sensible to increase `--javascript.v8-contexts` a bit if the logs show that operations time out waiting for unused V8 contexts.

Apart from that, the error code for the former errors is probably not right. It's currently set to "internal error", which triggers the message asking the user to report this. But I think this error is "expected" when running out of available V8 contexts, and the proper fix for will be to not to report this issue to ArangoDB, but to adjust the settings (e.g. `--javascript.v8-contexts`). The error code & message should be changed and indicate that.

**Comment by DeShadow** [comment] 2017-09-21 09:28
@jsteemann 
I reinstalled ArangoDB on my Ubuntu Server and that's why logs are lost.
Now I don't have these errors. I rewrite my code to make many small parallel operations instead of one big update or inserts. 

But the behaviour is very strange... My ArangoDB process is killed by Ubuntu every day because of `out of memory`. 
Server: 8GB RAM with 2 cores.
Data: about 1mln documents.
Operations: Every 15 minutes I make some updates and inserts operations. I have already rewritten my code to make many small inserts and updates operations (every batch is about only 10 documents) with concurrency of 4 batches in once time. But ArangoDB is killed by Ubuntu every day.

```
[559604.721767] [ 1513]    33  1513    28302       97      46      376             0 nginx
[559604.721769] [ 1514]    33  1514    28269      137      46      299             0 nginx
[559604.721770] [ 1515]    33  1515    28302      533      46      315             0 nginx
[559604.721772] [ 1516]    33  1516    28269      957      46      292             0 nginx
[559604.721773] [ 1517]    33  1517    28269      976      46      293             0 nginx
[559604.721774] [ 1518]    33  1518    28269      137      46      276             0 nginx
[559604.721776] [ 1519]    33  1519    28269      332      46      314             0 nginx
[559604.721777] [ 1520]    33  1520    28282       75      46      337             0 nginx
[559604.721778] [ 1521]    33  1521    28302      489      46      324             0 nginx
[559604.721780] [ 1522]    33  1522    28269      286      46      297             0 nginx
[559604.721781] [ 1523]    33  1523    28269      229      46      298             0 nginx
[559604.721783] [ 1524]    33  1524    28269      181      46      295             0 nginx
[559604.721789] [ 1525]    33  1525    28269      141      46      296             0 nginx
[559604.721791] [ 1526]    33  1526    28269      412      46      292             0 nginx
[559604.721793] [ 1527]    33  1527    28282      214      46      303             0 nginx
[559604.721794] [ 1528]    33  1528    28269      295      46      298             0 nginx
[559604.721795] [ 1529]    33  1529    28269      533      46      294             0 nginx
[559604.721797] [ 1530]    33  1530    28269      408      46      298             0 nginx
[559604.721798] [ 1531]    33  1531    28269      422      46      383             0 nginx
[559604.721800] [ 1532]    33  1532    28302      152      46      292             0 nginx
[559604.721801] [ 1533]    33  1533    28269      269      46      309             0 nginx
[559604.721802] [ 1534]    33  1534    28269      455      46      346             0 nginx
[559604.721804] [ 1535]    33  1535    28269     1001      46      280             0 nginx
[559604.721805] [ 1536]    33  1536    28302      824      46      293             0 nginx
[559604.721806] [ 1537]    33  1537    28302      340      46      317             0 nginx
[559604.721808] [ 1538]    33  1538    28269      476      46      330             0 nginx
[559604.721809] [ 1539]    33  1539    28269      660      46      292             0 nginx
[559604.721811] [ 1540]    33  1540    28270      129      46      309             0 nginx
[559604.721812] [ 1541]    33  1541    28269      990      46      279             0 nginx
[559604.721814] [ 1542]    33  1542    28269      149      46      287             0 nginx
[559604.721815] [ 1543]    33  1543    28269      286      46      304             0 nginx
[559604.721816] [ 1544]    33  1544    28269      482      46      299             0 nginx
[559604.721818] [ 1545]    33  1545    28269      112      46      332             0 nginx
[559604.721819] [ 1546]    33  1546    28269      674      46      292             0 nginx
[559604.721821] [ 1547]    33  1547    28269      617      46      315             0 nginx
[559604.721822] [ 1548]    33  1548    28302      147      46      292             0 nginx
[559604.721823] [ 1549]    33  1549    28269      515      46      298             0 nginx
[559604.721825] [ 1550]    33  1550    28302      147      46      313             0 nginx
[559604.721826] [ 1551]    33  1551    28302      497      46      356             0 nginx
[559604.721827] [ 1552]    33  1552    28269      516      46      276             0 nginx
[559604.721829] [ 1553]    33  1553    28302      389      46      283             0 nginx
[559604.721830] [ 1554]    33  1554    28302      431      46      375             0 nginx
[559604.721832] [ 1555]    33  1555    28269      140      46      301             0 nginx
[559604.721833] [ 1556]    33  1556    28269      162      46      364             0 nginx
[559604.721835] [ 1557]    33  1557    28269      198      46      349             0 nginx
[559604.721836] [ 1558]    33  1558    28302       81      46      407             0 nginx
[559604.721838] [ 1559]    33  1559    28269      495      46      302             0 nginx
[559604.721839] [ 1560]    33  1560    28302      512      46      300             0 nginx
[559604.721840] [ 1561]    33  1561    28269       90      46      313             0 nginx
[559604.721842] [ 1562]    33  1562    28269      112      46      323             0 nginx
[559604.721843] [ 1563]    33  1563    28302      537      46      295             0 nginx
[559604.721844] [ 1564]    33  1564    28302      255      46      285             0 nginx
[559604.721846] [ 1565]    33  1565    28269      157      46      310             0 nginx
[559604.721847] [ 1566]    33  1566    28269      140      46      297             0 nginx
[559604.721848] [ 1567]    33  1567    28269      479      46      311             0 nginx
[559604.721850] [ 1568]    33  1568    28269      121      46      336             0 nginx
[559604.721851] [ 1569]    33  1569    28269      570      46      311             0 nginx
[559604.721858] [ 1570]    33  1570    28302      124      46      314             0 nginx
[559604.721860] [ 1571]    33  1571    28269      127      46      311             0 nginx
[559604.721861] [ 1572]    33  1572    28269      370      46      317             0 nginx
[559604.721862] [ 1573]    33  1573    28269      298      46      302             0 nginx
[559604.721864] [ 1574]    33  1574    28269      735      46      315             0 nginx
[559604.721865] [ 1575]    33  1575    28269      124      46      281             0 nginx
[559604.721867] [ 1576]    33  1576    28269      532      46      294             0 nginx
[559604.721868] [ 1577]    33  1577    28269      369      46      315             0 nginx
[559604.721869] [ 1578]    33  1578    28271      491      46      315             0 nginx
[559604.721871] [ 1579]    33  1579    28269      464      46      358             0 nginx
[559604.721872] [ 1580]    33  1580    28269      649      46      301             0 nginx
[559604.721873] [ 1581]    33  1581    28269      989      46      284             0 nginx
[559604.721875] [ 1582]    33  1582    28269      622      46      308             0 nginx
[559604.721876] [ 1583]    33  1583    28269      127      46      337             0 nginx
[559604.721877] [ 1584]    33  1584    28302      255      46      346             0 nginx
[559604.721879] [ 1585]    33  1585    28269      476      46      303             0 nginx
[559604.721880] [ 1586]    33  1586    28302      126      46      361             0 nginx
[559604.721881] [ 1587]    33  1587    28269      186      46      301             0 nginx
[559604.721883] [ 1588]    33  1588    28269     1008      46      304             0 nginx
[559604.721884] [ 1589]    33  1589    28269      125      46      286             0 nginx
[559604.721885] [ 1590]    33  1590    28269      282      46      312             0 nginx
[559604.721887] [ 1591]    33  1591    32409      821      47      814             0 nginx
[559604.721888] [ 1592]    33  1592    28302      987      46      286             0 nginx
[559604.721890] [ 1593]    33  1593    28269      982      46      294             0 nginx
[559604.721891] [ 1594]    33  1594    28269      156      46      288             0 nginx
[559604.721892] [ 1595]    33  1595    28314      932      46      332             0 nginx
[559604.721894] [ 1596]    33  1596    28302      139      46      282             0 nginx
[559604.721895] [ 1597]    33  1597    28269      313      46      312             0 nginx
[559604.721897] [ 1598]    33  1598    28302      422      46      305             0 nginx
[559604.721898] [ 1599]    33  1599    28269      389      46      300             0 nginx
[559604.721899] [ 1600]    33  1600    28269      502      46      319             0 nginx
[559604.721901] [ 1601]    33  1601    28269      507      46      308             0 nginx
[559604.721902] [ 1602]    33  1602    28269      656      46      296             0 nginx
[559604.721903] [ 1603]    33  1603    28269      140      46      292             0 nginx
[559604.721905] [ 1604]    33  1604    28269      620      46      326             0 nginx
[559604.721906] [ 1605]    33  1605    28269      457      46      334             0 nginx
[559604.721908] [ 1606]    33  1606    28302      664      46      308             0 nginx
[559604.721909] [ 1680]   107  1680     7866      645      21      109             0 ntpd
[559604.721911] [ 1741]     0  1741    15142      967      31     2242             0 supervisord
[559604.721912] [ 1823]     0  1823     7657      429      18       92             0 monit
[559604.721914] [ 1848]     0  1848     4061      406      13       40             0 getty
[559604.721915] [ 8526]     0  8526    48752     9651      90     5706             0 puppet
[559604.721917] [ 7296]     0  7296    59559     3523      57     2499             0 mcollectived
[559604.721918] [29298]     0 29298    24624      316      34     5235             0 arangodb [super
[559604.721925] [29299]   999 29299  5526714  1691798    6477   206544             0 arangodb [serve
[559604.721927] [ 3846]  1002  3846   516792   224696     968     1348             0 node
[559604.721929] [19666]     0 19666     4366     1296      15        0             0 atop
[559604.721930] [ 2497]   106  2497     1638      471       9        0             0 check_ping
[559604.721932] [ 2498]   106  2498     1627      180       9        0             0 ping
[559604.721933] Out of memory: Kill process 29299 (arangodb [serve) score 832 or sacrifice child
[559604.721974] Killed process 29299 (arangodb [serve) total-vm:22106856kB, anon-rss:6752228kB, file-rss:14964kB
```

I can't find the reason of this behavior. The errors of start topic were on this server too.

**Comment by DeShadow** [comment] 2017-09-21 11:02
Why ArangoDB use so many virtual memory in my case?
<img width="1041" alt="screen shot 2017-09-21 at 14 00 16" src="https://user-images.githubusercontent.com/1763318/30692698-50f6d184-9ed5-11e7-8839-9b03aafb2679.png">

Maybe some problems because of warnings? 
```
2017-09-21T07:08:11Z [25718] WARNING {memory} /sys/kernel/mm/transparent_hugepage/enabled is set to 'always'. It is recommended to set it to a value of 'never' or 'madvise'
2017-09-21T07:08:11Z [25718] WARNING {memory} /sys/kernel/mm/transparent_hugepage/defrag is set to 'always'. It is recommended to set it to a value of 'never' or 'madvise'
2017-09-21T07:08:11Z [25718] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/enabled"'
2017-09-21T07:08:11Z [25718] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/defrag"'
2017-09-21T07:08:11Z [25718] INFO using storage engine rocksdb
2017-09-21T07:08:11Z [25718] INFO {syscall} file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2017-09-21T07:08:11Z [25718] INFO Authentication is turned on (system only), authentication for unix sockets is turned on
2017-09-21T07:08:11Z [25718] WARNING {memory} /proc/sys/vm/overcommit_memory is set to '0'. It is recommended to set it to a value of 2
2017-09-21T07:08:11Z [25718] WARNING {memory} execute 'sudo bash -c "echo 2 > /proc/sys/vm/overcommit_memory"'
2017-09-21T07:08:14Z [25845] INFO ArangoDB 3.2.3 [linux] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.0.0, OpenSSL 1.0.1f 6 Jan 2014
2017-09-21T07:08:14Z [25845] WARNING {memory} /sys/kernel/mm/transparent_hugepage/enabled is set to 'always'. It is recommended to set it to a value of 'never' or 'madvise'
2017-09-21T07:08:14Z [25845] WARNING {memory} /sys/kernel/mm/transparent_hugepage/defrag is set to 'always'. It is recommended to set it to a value of 'never' or 'madvise'
2017-09-21T07:08:14Z [25845] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/enabled"'
2017-09-21T07:08:14Z [25845] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/defrag"'
2017-09-21T07:08:14Z [25845] INFO using storage engine rocksdb
2017-09-21T07:08:14Z [25845] INFO {cluster} Starting up with role SINGLE
2017-09-21T07:08:14Z [25845] INFO {syscall} file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2017-09-21T07:08:14Z [25845] INFO Authentication is turned on (system only), authentication for unix sockets is turned on
2017-09-21T07:08:14Z [25845] WARNING {memory} /proc/sys/vm/overcommit_memory is set to '0'. It is recommended to set it to a value of 2
2017-09-21T07:08:14Z [25845] WARNING {memory} execute 'sudo bash -c "echo 2 > /proc/sys/vm/overcommit_memory"'
2017-09-21T07:08:15Z [25845] INFO using endpoint 'http+tcp://127.0.0.1:8529' for non-encrypted requests
2017-09-21T07:08:16Z [25845] INFO ArangoDB (version 3.2.3 [linux]) is ready for business. Have fun!
```

But when I executed this command the server was unstable too. That's why I returned these values to default state.

**Comment by DeShadow** [comment] 2017-09-21 11:10
Also the result of `db.news.figures()`
```
{ 
  "indexes" : { 
    "count" : 6, 
    "size" : 174998591 
  }, 
  "documentsSize" : 2494488752 
}
```

The datasize is only 2.5GB, that's why it's very strange,  that 8GB RAM maybe not enough...

**Comment by DeShadow** [comment] 2017-09-21 11:45
Sorry for spaming.
Another strange thing. I executed very strong `UPDATE` operation to remove field `src` from all documents in this collection. 
```
for n in news
filter n.src != null
update n with { src: null } in news options { keepNull: false }
```

And this query was successfully finished without `out of memory`.
<img width="1035" alt="screen shot 2017-09-21 at 14 44 19" src="https://user-images.githubusercontent.com/1763318/30694128-61d07522-9edb-11e7-964d-b2acfb64b375.png">
But the vertual memory size now is 22GB... And this size didn't decrease after execution.

**Comment by jsteemann** [comment] 2017-09-21 16:20
The OOM killer should not worry too about the virtual memory, but it will surely check the resident value and kill the process if it thinks it uses too much.
The virtual memory usage should indeed go down and not only increase. That looks wrong.
Can you share the configuration (startup parameters, changed config values) plus the name of the OS you are running ArangoDB on? And provide some details about the collections/indexes most likely used when the problem occurred plus a brief description of the workload?
Thanks!

**Comment by DeShadow** [comment] 2017-09-22 10:07
@jsteemann 
The virtual memory didn't decrease... It's seems like after update the memory isn't free. My process was killed again by OOM Killer.

OS:  Ubuntu 14.04.5 LTS
Config files and startup parameters haven't changed. They are default.

ArangoDB 3.2.3 was reinstalled clearly and data were restored by arangorestore. That's why I think there is no artefacts after upgrade.

Only one collection used with `update` and `insert` operations. Sample of document in collection:
```
{
    "_key": "59c3ac585fef6a55ca9356c9",
    "_id": "news/59c3ac585fef6a55ca9356c9",
    "_rev": "_VoTFgrm--_",
    "categoryIds": [
      "17293954"
    ],
    "date": "2017-09-21T16:12:00.000Z",
    "title": "Some title of news",
    "text": "<a few thousands symbols of news content>",
    "isRemoved": null,
    "isEdited": null,
    "isCreated": false,
    "isShow": false,
    "wasShow": true,
    "mood": "neutral",
    "sourceHref": "http://babr24.com/bur/?IDE=165284",
    "src": {
      "webimages": null,
      "domain": "babr24.com",
      "title": "<Title again>",
      "text": "<a few thousands symbols of news content>",
      "created": "2017-09-21T16:12:00+00:00",
      "path": "http://babr24.com/bur/?IDE=165284",
      "id": "59c3ac585fef6a55ca9356c9"
    },
    "newsSourceId": "262125508",
    "linkedNewsIds": [],
    "power": 0
  }
```

There is about 2k text in fields `text`.

Indexes:
```
[ 
  { 
    "fields" : [ 
      "_key" 
    ], 
    "id" : "news/0", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "primary", 
    "unique" : true 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "isRemoved", 
      "date" 
    ], 
    "id" : "news/14638348", 
    "selectivityEstimate" : 0.7288904706824451, 
    "sparse" : false, 
    "type" : "skiplist", 
    "unique" : false 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "wasShow", 
      "date" 
    ], 
    "id" : "news/68013242", 
    "selectivityEstimate" : 0.7061922445807064, 
    "sparse" : false, 
    "type" : "skiplist", 
    "unique" : false 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "date" 
    ], 
    "id" : "news/72482718", 
    "selectivityEstimate" : 0.7352122789695719, 
    "sparse" : false, 
    "type" : "skiplist", 
    "unique" : false 
  }, 
  { 
    "deduplicate" : false, 
    "fields" : [ 
      "isShow", 
      "categoryIds[*]" 
    ], 
    "id" : "news/740679920", 
    "selectivityEstimate" : 0.00003792715457843968, 
    "sparse" : false, 
    "type" : "hash", 
    "unique" : false 
  }, 
  { 
    "deduplicate" : false, 
    "fields" : [ 
      "isShowToModerator", 
      "date" 
    ], 
    "id" : "news/740679970", 
    "selectivityEstimate" : 0.7282425104453729, 
    "sparse" : false, 
    "type" : "skiplist", 
    "unique" : false 
  } 
]
```

Workload. Now the collection `news` has about 1mln documents. Every 15 minutes my Node.js server receiving new part of data (about 30MB JSON). I analize it and make some operations:
- get many news by keys (about 15k documents);
- update current news with field `isShow == true` to `isShow = false`;
- make some other application logic;
- insert new news;
- update some news with `isShow = true`

I checked my code and found that reason maybe in first line. I tried to get all news by key list (about 15k keys) and used `lookupByKeys` for it. But I think that this method is not optimized and maybe has memory leak. Yesterday evening I replaced it by cursor of query `for n in news filter n._key in @newsKeys return n`. And I think it fixed my problem. But I'm watching now for server.

**Comment by jsteemann** [comment] 2017-09-22 11:27
Thanks for the investigation. I am now also able to see increasing virtual memory when calling `db.<collection>.lookupByKeys(<big list>);`. I still need to find out why the increase happens.

**Comment by DeShadow** [comment] 2017-09-22 15:35
@jsteemann Also I found that after complex query without index, for example
```
for n in news
sort n._key desc
limit 5
return n
```
ArangoDB server get many virtual memory and doesn't return it back. Is it normal or not?

<img width="1140" alt="screen shot 2017-09-22 at 18 31 34" src="https://user-images.githubusercontent.com/1763318/30752285-85e4ba9c-9fc4-11e7-99c8-7385fa746662.png">

And also the question about warnings. Maybe I need to execute recommended commands?
```
2017-09-22T06:14:34Z [15423] WARNING {memory} /sys/kernel/mm/transparent_hugepage/enabled is set to 'always'. It is recommended to set it to a value of 'never' or 'madvise'
2017-09-22T06:14:34Z [15423] WARNING {memory} /sys/kernel/mm/transparent_hugepage/defrag is set to 'always'. It is recommended to set it to a value of 'never' or 'madvise'
2017-09-22T06:14:34Z [15423] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/enabled"'
2017-09-22T06:14:34Z [15423] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/defrag"'
2017-09-22T06:14:34Z [15423] INFO using storage engine rocksdb
2017-09-22T06:14:34Z [15423] INFO {syscall} file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2017-09-22T06:14:34Z [15423] INFO Authentication is turned on (system only), authentication for unix sockets is turned on
2017-09-22T06:14:34Z [15423] WARNING {memory} /proc/sys/vm/overcommit_memory is set to '0'. It is recommended to set it to a value of 2
2017-09-22T06:14:34Z [15423] WARNING {memory} execute 'sudo bash -c "echo 2 > /proc/sys/vm/overcommit_memory"'
2017-09-22T06:14:37Z [15550] INFO ArangoDB 3.2.3 [linux] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.0.0, OpenSSL 1.0.1f 6 Jan 2014
2017-09-22T06:14:37Z [15550] WARNING {memory} /sys/kernel/mm/transparent_hugepage/enabled is set to 'always'. It is recommended to set it to a value of 'never' or 'madvise'
2017-09-22T06:14:37Z [15550] WARNING {memory} /sys/kernel/mm/transparent_hugepage/defrag is set to 'always'. It is recommended to set it to a value of 'never' or 'madvise'
2017-09-22T06:14:37Z [15550] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/enabled"'
2017-09-22T06:14:37Z [15550] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/defrag"'
2017-09-22T06:14:37Z [15550] INFO using storage engine rocksdb
2017-09-22T06:14:37Z [15550] INFO {cluster} Starting up with role SINGLE
2017-09-22T06:14:37Z [15550] INFO {syscall} file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2017-09-22T06:14:37Z [15550] INFO Authentication is turned on (system only), authentication for unix sockets is turned on
2017-09-22T06:14:37Z [15550] WARNING {memory} /proc/sys/vm/overcommit_memory is set to '0'. It is recommended to set it to a value of 2
2017-09-22T06:14:37Z [15550] WARNING {memory} execute 'sudo bash -c "echo 2 > /proc/sys/vm/overcommit_memory"'
2017-09-22T06:14:38Z [15550] INFO using endpoint 'http+tcp://127.0.0.1:8529' for non-encrypted requests
2017-09-22T06:14:41Z [15550] INFO ArangoDB (version 3.2.3 [linux]) is ready for business. Have fun!
```

**Comment by jsteemann** [comment] 2017-09-25 15:39
@DeShadow : I don't think changing the environment/kernel settings will greatly affect how much virtual memory is retained and how/when it will be returned to the OS.
I still have to understand why `db.<collection>.lookupKeys(<big list>);` uses so much virtual memory and does not return it properly. Technically, it does not seem to be a leak in the sense of ArangoDB forgetting to free some allocated memory, but it looks like we are properly returning all memory via `delete`. However, it does not seem to get returned as expected, so I guess it is caused by some fragmentation issue or pathological case in the memory allocator. I tried running that particular case without the jemalloc allocator and it does much better then. This clearly needs more investigation.

**Comment by DeShadow** [comment] 2017-09-26 08:07
@jsteemann Thanks for information!
Also I found that my virtual memory increased for days, but slower than was before with `lookupByKeys`...
![screen shot 2017-09-26 at 11 04 38](https://user-images.githubusercontent.com/1763318/30849344-b0669c16-a2aa-11e7-8a76-384e14028151.png)
It was about 3GB Virtual Memory a few days before (when I wrote previous comment), and about 1.5GB RES. Now you can see the above screenshot.

**Comment by p30arena** [comment] 2017-10-02 07:57
This is my stats on arangod, around 4 GB of virtual memory is consumed, isn't it weird as we're still in our production environment and we're low on requests?
```
PID      USER          PR  NI    VIRT           RES         SHR    S  %CPU  %MEM     TIME+     COMMAND
27245  arangodb  20   0      3792.2m    191.0m   64.2m S  2.4       10.4          30:07.02  arangod
```

**Comment by DeShadow** [comment] 2017-10-02 09:01
@p30arena My stats after a few days. I have two servers for two projects. In one project all is good. On this server I have problems. I have many batches of inserts and update operations. Maybe it's the reason.

<img width="898" alt="screen shot 2017-10-02 at 11 59 17" src="https://user-images.githubusercontent.com/1763318/31070494-3f65d2fc-a769-11e7-82df-5c6ee3f52a70.png">

**Comment by jsteemann** [comment] 2017-10-27 14:36
We have some indications for a memory leak in the version of V8 that is bundled with ArangoDB.
A fix for this is under way. We will also recheck with adjusted configuration with JEMalloc next week.

**Comment by DeShadow** [comment] 2017-10-31 10:14
@jsteemann Thank you very mcuh for information! :)

**Comment by sleto-it** [comment] 2017-11-16 11:18
Hi all,

Version 3.2.7 has been released. Would be nice, if you have a chance, to upgrade and see if things improved with this version

Keeping this issue open

Many Thanks,

**Comment by DeShadow** [comment] 2017-11-16 14:04
@sleto-it Thanks! :) I upgraded my databases to 3.2.7. I'll report you about result :)

**Comment by dothebart** [comment] 2017-11-23 15:03
Ok, meanwhile 3.2.8 has also been released, so I think we can close this now.

**Closed** 2017-11-23 15:04 UTC
Labels: 1 Analyzing, 1 Bug, 3 Core, 3 RocksDB
