### ISSUE TITLE
Few bug reports while testing HTTP REST API for 3.4.0-rc.2

### ISSUE THREAD

**Issue by joowani** [arangodb/arangodb#7009] opened 2018-10-23 02:51 UTC
## My Environment

* __ArangoDB Version__:        3.4.0-rc.2
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Infrastructure__:               Own
* __Operating System__:        Windows 10 Docker

## Component, Query & Data

HTTP REST API

__Problems__:

Just wanted to report a few problems I've noticed while testing the REST HTTP API with 3.4.0-rc.2:

1. Inserting duplicate edge or vertex documents return status code 1202 (document not found) instead of 1210/1906.
2. Deleting an existing edge definition with "dropCollection" option does not seem to delete the collections.
3. Getting this error when trying to run NEAR aql query:
```
[HTTP 500][ERR 4] AQL: member out of range (exception location: /work/ArangoDB/arangod/Aql/AstNode.h:545). Please report this error to arangodb.com (while optimizing plan) (exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:237). Please report this error to arangodb.com
```
4. Getting **[HTTP 400][ERR 1233] edge attribute missing or invalid** when trying to update an edge document with correctly populated "_key", "_from", "_to" attributes. This did not happen in 3.3 with the same input.
5. HTTP endpoint "/_api/tasks" seems to only work via system database now. Ignore if intentional.
6. When adding a new user while creating a new database with (user "active" set to true), the default permissions used to be "rw" but now it is "none". Ignore if intentional.

**Comment by maxkernbach** [comment] 2018-10-30 16:48
Hi @joowani,

thanks for your detailed API testing and providing all of these potential bugs. I have tried to reproduce them using the latest available version 3.4.0 RC3.

1. reproducible - bug 
2. could not reproduce - I have used the **social** graph and deleted the existing edge definition **relation** with `curl -X DELETE --header 'accept: application/json' --dump - http://root@localhost:8529/_api/gharial/social/edge/relation?dropCollections=true` -> edge collection **relation** deleted
3. could not reproduce - used data + NEAR query of the [Geo tutorial ](https://docs.arangodb.com/3.4/AQL/Tutorial/Geospatial.html#find-nearby-locations) with `curl -X POST --data-binary @- --dump - http://root@localhost:8529/_api/cursor <<EOF
{ 
  "query" : "FOR loc IN NEAR(Locations, 53.35, -6.26, 3) RETURN {name: loc.name, latitude: loc.coordinate[0], longitude: loc.coordinate[1]}" 
}
EOF` -> no error
4. in my edge update test the edge attributes "_from" and "_to" got saved even when they were invalid, used **social** graph again `curl -X PATCH --header 'accept: application/json' --data-binary @- --dump - http://root@localhost:8529/_api/gharial/social/edge/relation/29186 <<EOF
{ 
  "_from": "wrong/from",
  "_to": "wrong/to"
}
EOF`
5. I was able to create a ask via another database called **example** by `curl -X POST --header 'accept: application/json' --data-binary @- --dump - http://root@localhost:8529/_db/example/_api/tasks <<EOF
{"id":"testTask3","command":"console.log('Hello from task!');","offset":10000}
EOF
`
6. reproducible - looks unintentional

**Comment by joowani** [comment] 2018-12-11 20:59
Hi @maxkernbach,

Just giving you an update after testing again with latest 3.4.0.

2. It seems I've been misspelling `dropCollections` as `dropCollection`. Was this parameter always spelled with an S at the end or did this change recently?

3. The issue still exists. To reproduce on the dashboard:
    1. Create a test database and a test collection.
    2. Insert into the collection the following documents:
        ```
        [
        {'_key': '1', 'val': 1, 'text': 'foo', 'loc': [1, 1]},
        {'_key': '2', 'val': 2, 'text': 'foo', 'loc': [2, 2]},
        {'_key': '3', 'val': 3, 'text': 'foo', 'loc': [3, 3]},
        {'_key': '4', 'val': 4, 'text': 'bar', 'loc': [4, 4]},
        {'_key': '5', 'val': 5, 'text': 'bar', 'loc': [5, 5]},
        {'_key': '6', 'val': 6, 'text': 'bar', 'loc': [5, 5]},
        ]
        ```
    3. Go to QUERIES page on the dashboard and run the following query + bind_vars:
        ```
        FOR doc IN NEAR(@collection, @latitude, @longitude)
            RETURN doc
        ```
        bind_vars: collection=test, latitude=1, longitude=1

4. Sorry I should've been clearer. Yes the gharial endpoints work correctly. I was talking about the **/_api/document/collection** endpoint. When I used this endpoint on a collection with type 3 (legacy way of managing edges?) I used to be able to update/replace edges. After 3.4 it does not work and always gives me the error **[HTTP 400][ERR 1233] edge attribute missing or invalid** even on valid documents.

**Comment by jsteemann** [comment] 2018-12-12 09:06
Sub-issue 3 fixed by PR https://github.com/arangodb/arangodb/pull/7746, targeting 3.4.1.

**Comment by Simran-B** [comment] 2018-12-13 09:12
2. Yes, it was always dropCollection<b><i>s</i></b>, see e.g. 3.0 docs: https://docs.arangodb.com/3.0/HTTP/Gharial/Management.html#drop-a-graph

4. It's not a legacy way of managing edges, it's a low-level endpoint for document management - and edges are documents. If you use this endpoint however, graph consistency for named graphs can not be guaranteed.
  
   I tried some queries against the endpoint. If I supply an object as payload:
   `{"_key": "xxx", "_from": "event/4", "_to": "event/5"}`
   using curl with eventOrder being an edge collection:
   `curl -X PUT -u root: --data-binary @- http://localhost:8530/_api/document/eventOrder?returnNew=true`
   then it fails as expected (because the endpoint [supports arrays only](https://docs.arangodb.com/3.4/HTTP/Document/WorkingWithDocuments.html)):
   ```json
   {
     "error": true,
     "errorMessage": "invalid document type",
     "code": 400,
     "errorNum": 1227
   }
   ```
   It works with this payload (object wrapped in array):
   `[{"_key": "xxx", "_from": "event/4", "_to": "event/5"}]`
   
   I also tried with a mixed payload (an edge with _key "zzz" does not exist, the other two do):
   ```json
   [
     {"_key": "zzz"},
     {"_key": "yyy"},
     {"_key": "yyy", "_from": "BAD", "_to": "BAD"},
     {"_key": "xxx", "_from": "event/4", "_to": "event/5"}
   ]
   ```
   Result:
   ```json
   [
     {
       "error": true,
       "errorNum": 1202,
       "errorMessage": "document not found"
     },
     {
       "error": true,
       "errorNum": 1233,
       "errorMessage": "edge attribute missing or invalid"
     },
     {
       "error": true,
       "errorNum": 1233,
       "errorMessage": "edge attribute missing or invalid"
     },
     {
       "_id": "eventOrder/xxx",
       "_key": "xxx",
       "_rev": "_X4ZH4mq--C",
       "_oldRev": "_X4ZGPV---_",
       "new": {
         "_key": "xxx",
         "_id": "eventOrder/xxx",
         "_from": "event/4",
         "_to": "event/5",
         "_rev": "_X4ZH4mq--C"
       }
     }
   ]
   ```

   I worked for documents if the input was valid, and failed with the appropriate error messages if the input was not correct. Thus, I can't reproduce your problem. Can you please try again and share the exact endpoint URL and the payload?

5. @joowani can you try again and see if you still have the problem with the tasks API?

6. A few things changed regarding users and permissions, but I don't know if the permissions are supposed to be "none" by default. @fceller ?

**Comment by dothebart** [comment] 2020-09-02 09:06
The version concerned in this Issue has long been EOLed, closing with the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) - please upgarde.

**Closed by dothebart** 2020-09-02 09:06 UTC
Labels: 1 Bug, 3 Graph, 3 UserManagement
