### ISSUE TITLE
Wrong metric calculation at dashboard

### ISSUE THREAD

**Issue by dagarwal82** [arangodb/arangodb#1313] opened 2015-04-21 14:11 UTC
Just after it was showing 18GB in Resident size , when I refreshed I don't see correct utilization anymore. 
I am running 2.5.2 on Linux box (Ubuntu)
![wrongmetrics](https://cloud.githubusercontent.com/assets/1272570/7254087/cb5b49c6-e80e-11e4-9fbc-5f33c619ef9d.png)

**Comment by razvanphp** [comment] 2015-04-22 15:46
Yeah, we had this too few times, donno exactly how to reproduce.

**Comment by razvanphp** [comment] 2015-05-17 23:40
![screen shot 2015-05-18 at 01 39 51](https://cloud.githubusercontent.com/assets/4599319/7672770/e5214996-fcfe-11e4-9d14-3c0b82c3a6df.png)

**Comment by fceller** [comment] 2015-05-18 07:42
It seems that the 15min average is total wrong: 

    "numberOfThreads15M":6154626155518.341

**Comment by fceller** [comment] 2015-05-18 07:49
@razvan are the correct values shown after a while (say 30min)? Or is it still broken?

**Comment by jsteemann** [comment] 2015-05-18 08:48
@razvanphp : Is it possible that the newlines are an artifact introduced by browsers? 
I am wondering where the newlines could come from, because the `statistics/short` API will return a `JSON.stringify`ed result, and this will not contain any newlines. 
When invoking the API without a browser, e.g. by using `curl -X GET http://127.0.0.1:8529/_db/_system/_admin/aardvark/statistics/short?start=...`, there don't seem to be any newlines either.
How can the newlines be reproduced?

@fceller: I agree the thread number average looks totally wrong. Will look into it.

**Comment by razvanphp** [comment] 2015-05-18 08:57
@jsteemann sorry, you are right, the JSON is valid, it was Firebug showing it wrong. So it must be the values itself that are wrong.

@fceller I don't think it gets fixed after some time, or if it does, it breaks again afterwards, because I saw this for few days on our production server. Only the restart of the server fixed this last night.

**Comment by jsteemann** [comment] 2015-05-18 10:56
I just committed a potential fix for this issue: 
d4868413df233267dcdd7f69c083fbbc9bfe6bbd

I am not sure if it actually fixes the issue, but the only obvious thing I found when looking at the code was that slightly-off format string.

**Comment by jsteemann** [comment] 2015-05-29 07:09
The above potential fix is contained in 2.6-alpha2 and 2.5.5 (probably not yet available).
I'll leave this issue open waiting for feedback on whether d486841 fixed it or not.

**Comment by fceller** [comment] 2015-06-12 10:56
@dagarwal82 @razvanphp can you confirm that this has been fixed in 2.6?

**Comment by razvanphp** [comment] 2015-06-16 16:12
I just got this in 2.6-beta1

![screen shot 2015-06-16 at 18 09 28](https://cloud.githubusercontent.com/assets/4599319/8187932/0d0f37ea-1453-11e5-9c5d-de3bd8f8fe2f.png)

Do you want some sample data before I restart it? I will also see if tomorrow it is fixed by itself.

**Comment by fceller** [comment] 2015-06-16 16:14
@razvanphp can you find out the PID of the process and do a 

    cat /proc/PID/stat

**Comment by razvanphp** [comment] 2015-06-16 16:19
````
root@bi-p-arango2:~# cat /proc/22898/stat
22898 (arangodb [super) S 16304 16304 16304 0 -1 1077944640 2794278 0 40 0 76385 4454 0 0 20 0 40 0 237876071 15380881408 2194534 18446744073709551615 4194304 28543648 140724936069056 140724936067968 140151872394939 0 2147221247 4096 17927 18446744073709551615 0 0 17 1 0 0 0 0 0 28545024 28596968 33677312 140724936070980 140724936071152 140724936071152 140724936073190 0
root@bi-p-arango2:~# cat /proc/16304/stat
16304 (arangodb [super) S 1 16304 16304 0 -1 4202560 642 3736291 0 34 0 0 104657 6430 20 0 1 0 237294636 87011328 1533 18446744073709551615 4194304 28543648 140724936069056 140724936068640 140151872408654 0 0 0 1024 0 0 0 17 3 0 0 0 0 0 28545024 28596968 33677312 140724936070980 140724936071152 140724936071152 140724936073190 0
root@bi-p-arango2:~#
````

child and supervisor

**Comment by jsteemann** [comment] 2015-06-17 10:01
Thanks for posting the file contents here. That actually revealed a problem: the process name contains whitespaces, and that makes parsing the file with the format string '%d %s .%c ...` interpret the data incorrectly. I have fixed that now so it should work with that particular file content. I didn't spot that before because when I start arangod it won't have whitespace in its process name.

**Comment by jsteemann** [comment] 2015-06-17 10:03
Fixed in current 2.5, 2.6 and devel.

**Comment by dothebart** [comment] 2015-09-03 07:53
@razvanphp can you confirm this fixed?

**Comment by razvanphp** [comment] 2015-09-03 09:42
Yes, I didn't see this for quite some time now. Thank you!

**Closed** 2015-09-03 12:24 UTC
Labels: Bug
