### ISSUE TITLE
AQL variable - Critical Bug - not working query since upgrade to 3.4 release

### ISSUE THREAD

**Issue by jan-zajic** [arangodb/arangodb#8108] opened 2019-02-05 09:22 UTC
## My Environment

* __ArangoDB Version__:       3.4.1
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               --log.output - --foxx.queues false --rocksdb.block-cache-size 2540707650 --cache.size 2117256375
* __Infrastructure__:               own
* __Disks in use__:        HDD
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__:
AQL query using REST API/AQL query using web interface

__AQL query (if applicable)__:
```
for i in xx filter i.address in ['xxx']
for v,e in 1 
	outbound i seg_xx, group_xx
	filter v.active != false and e.active != false
	let segOrGroupWithXx = {segOrGroup: v, xx: i}
	collect id=segOrGroupWithXx.segOrGroup._id into uniqueSegOrGroup
	 return {segOrGroup: uniqueSegOrGroup[0].segOrGroupWithXx.segOrGroup,  
	         xxs: uniqueSegOrGroup[*].segOrGroupWithXx.xx.address}
```

__AQL explain (if applicable)__:
```
Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
 14   IndexNode            1     - FOR i IN xx   /* hash index scan */
  5   TraversalNode        2       - FOR v  /* vertex */, e  /* edge */ IN 1..1  /* min..maxPathDepth */ OUTBOUND i /* startnode */  seg_xx, OUTBOUND group_xx
  6   CalculationNode      2         - LET #12 = ((v.`active` != false) && (e.`active` != false))   /* simple expression */
  7   FilterNode           2         - FILTER #12
  9   CalculationNode      2         - LET #14 = v.`_id`   /* attribute expression */
 13   SortNode             2         - SORT #14 ASC
  8   CalculationNode      2         - LET segOrGroupWithXx = { "segOrGroup" : v, "xx" : i }   /* simple expression */   /* collections used: i : xx */
 10   CollectNode          2         - COLLECT id = #14 INTO uniqueSegOrGroup KEEP segOrGroupWithXx   /* sorted */
 11   CalculationNode      2         - LET #16 = { "segOrGroup" : uniqueSegOrGroup[0].`segOrGroupWithXx`.`segOrGroup`, "xxs" : uniqueSegOrGroup[*].`segOrGroupWithXx`.`xx`.`address` }   /* simple expression */
 12   ReturnNode           2         - RETURN #16

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields          Ranges
 14   hash   xx           true     true        100.00 %   [ `address` ]   (i.`address` == "xxx")
  5   edge   group_xx   false    false            n/a   [ `_from` ]     base OUTBOUND
  5   edge   seg_xx   false    false            n/a   [ `_from` ]     base OUTBOUND

Traversals on graphs:
 Id   Depth   Vertex collections   Edge collections         Options                                   Filter conditions
  5   1..1                         seg_xx, group_xx   uniqueVertices: none, uniqueEdges: path   

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   remove-collect-variables
  6   use-indexes
  7   remove-filter-covered-by-index
  8   remove-unnecessary-calculations-2
  9   move-calculations-down
```
## Steps to reproduce

1. Execute Query

__Problem__:
Query: `AQL: variable not found 'segOrGroupWithXx' in executeSimpleExpression() (exception location: /work/ArangoDB/arangod/Aql/BaseExpressionContext.cpp:62). Please report this error to arangodb.com (while executing) (exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:238). Please report this error to arangodb.com`

__Expected result__:
In previous versions (2x-3.3) works fine.

**Comment by jan-zajic** [comment] 2019-02-05 09:34
This query fail:
for i in xx filter i.address in ['xxx']
for v,e in 1
outbound i seg_xx, group_xx
let segOrGroupWithXx = {segOrGroup: v, xx: i}
  collect id=segOrGroupWithXx.segOrGroup._id into uniqueSegOrGroup
  return {}

But this works:
for i in xx filter i.address in ['xxx']
for v,e in 1
outbound i seg_xx, group_xx
let segOrGroupWithXx = {segOrGroup: v, xx: i}
  collect id=segOrGroupWithXx.segOrGroup into uniqueSegOrGroup
  return {}

**Comment by Simran-B** [comment] 2019-02-05 10:07
This works as intended:

> The COLLECT statement will eliminate all local variables in the current scope. After COLLECT only the variables introduced by COLLECT itself are available.

https://docs.arangodb.com/3.4/AQL/Operations/Collect.html

segOrGroupWithXx does no longer exist after COLLECT. If you still need access to the value, then using INTO is one option.

**Comment by jan-zajic** [comment] 2019-02-05 10:12
@Simran-B i dont't think so. See my last comment: i can't access local variable inside collect, not after. But it even works - i can acces variable, but i can't access nested variable in that object. And yes we use into - if you look to original query we access only variable introduced in into after collect.

**Comment by Simran-B** [comment] 2019-02-05 14:40
I looked at this query part you posted:

```
let segOrGroupWithXx = {segOrGroup: v, xx: i}
collect id=segOrGroupWithXx.segOrGroup._id into uniqueSegOrGroup
```

The variable `segOrGroupWithXx` is no longer set after COLLECT, but you didn't reference it in the RETURN operation anyway - so pardon me! `segOrGroupWithXx.segOrGroup._id` should be accessible via the variable `id`, and the entire grouped documents via uniqueSegOrGroup.

There is indeed a bug, which causes the error you reported. This is now fixed in code, and will be shipped in version 3.4.3. Thank you for the report!

**Comment by jan-zajic** [comment] 2019-02-05 16:03
You're welcome. Exists some due date for 3.4.3 version?

**Comment by Simran-B** [comment] 2019-02-05 16:56
We normally release bug fix versions at least once every 2 weeks.

**Comment by sleto-it** [comment] 2019-02-21 23:41
Hi, version 3.4.3 has been released

I am going ahead and closing this ticket now. Will you please comment if further help is needed on this topic? (so we can reopen it)

Many thanks,

**Closed by sleto-it** 2019-02-21 23:41 UTC
Labels: 1 Bug, 2 Fixed, 3 AQL
