### ISSUE TITLE
Provide API for making HTTP requests (wrap internal.download)

### ISSUE THREAD

**Issue by myguidingstar** [arangodb/arangodb#1054] opened 2014-10-17 00:48 UTC
Looking around javascript sources in Arango and Foxx apps, I see a lot of functions under `require("internal")` but I can't find any docs for it. Afaics, only `require("internal").print` has been mentioned in doc.

**Comment by jsteemann** [comment] 2015-02-03 21:58
@pluma haven't you added the `request` module recently? I think it serves exactly this purpose. 
If what I guessed is true, can you provide some pointers on its documentation and close this issue?

**Comment by pluma** [comment] 2015-02-04 07:55
2.5 will bring the `org/arangodb/request` module, which provides a similar API to the `request` module for Node.js.

The module is documented in the 2.5 docs (in the JavaScript modules chapter).

**Closed by pluma** 2015-02-04 07:55 UTC
Labels: core, Feature

**Comment by razvanphp** [comment] 2015-03-04 11:46
Hey, what about `multipart/form-data` POST requests?

I tried it, but the `Content-Length` is wrongly calculated and appended. What I'm trying to do, is upload an image to the CDN. If I manually add the length header, it gets duplicated and the request ends up in a loop...

**Comment by pluma** [comment] 2015-03-04 12:21
The request module currently does not provide built-in support for multipart/form-data.

Could you try sending your POST request to the apropriate endpoint on http://httpbin.org/ and describe the issue you are seeing?

**Comment by razvanphp** [comment] 2015-03-04 14:54
Hmm, it seems ok, the multipart data is returned... but I get 500 from our CDN.

Here is the code snippet:
````javascript
var endpoint = "http://httpbin.org/post";
var opts = {
    method: "POST",
    headers: {
        "Host": this.getHostAndPort(endpoint),
        "Content-Type" : "multipart/form-data; boundary=4be60ee5d163"
    }
};
var body = '--4be60ee5d163\r\n'+
    'Content-Disposition: form-data; name="upload"; filename="test.png"\r\n'+
    'Content-Type: image/png\r\n\r\n'+
    file+"\r\n"+
    '--4be60ee5d163--\r\n';
var resp = download(endpoint, body, opts);
console.log(resp);
````

I tried with both `application/octet-stream` and `image/png`, no luck.
`file` variable is something like:
````
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA20AAAGLCA...
````

**Comment by razvanphp** [comment] 2015-03-20 11:12
OK, so the problem is that the upstream CDN accepts only `application/octet-stream` as upload. I managed to have the image base64 encoded in Foxx, but I don't know if (how) I can craft a POST request with boundaries and Buffer object containing binary data. Any idea?

**Comment by pluma** [comment] 2015-03-20 12:22
Do you mean multipart boundaries? You can just base64 encode the buffer (`buf.toString('base64')`) and then wrap it in a multipart message [following the spec](http://www.w3.org/Protocols/rfc1341/7_2_Multipart.html).

I assume you've seen the [request docs](https://docs.arangodb.com/ModuleRequest/README.html)? You can just specify your own `content-type` header and pass the encoded message as body.

**Comment by razvanphp** [comment] 2015-03-20 12:29
Yes, something like that, but the other way around: from base64 TO binary buffer. I will try and post here there results. Thank you!

**Comment by mchacki** [comment] 2015-03-20 12:30
Hi,

i have just tried it locally:

```
var request = require("request");
var fs = require("fs");
var opts = {
  "method" : "POST",
  "headers" : {
    "Content-Type" : "application/octet-stream"
  }
};
var file = fs.readBuffer("path/to/image.png");
var endpoint = "http://httpbin.org/post";
var resp = request.post(endpoint, opts);
```

On httpbin it seams to work, i do not know about your internal API

**Comment by razvanphp** [comment] 2015-03-20 14:00
Nope, it does not work..

What I tried:
````javascript
var input = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgA....A==';
var fileinbase64 = input.replace(/^data:image\/(png|jpg);base64,/, "");
var buffer = new Buffer(fileinbase64, 'base64');
var endpoint = "http://httpbin.org/post";
var bodyString = '--4be60ee5d163\r\n'+
    'Content-Disposition: form-data; name="upload"; filename="test.png"\r\n'+
    'Content-Type: application/octet-stream\r\n\r\n'+
    buffer+"\r\n"+
    '--4be60ee5d163--\r\n';
var opts = {
    url: endpoint,
    method: "POST",
    headers: {
        "Content-Type" : "multipart/form-data; boundary=4be60ee5d163"
    },
    body: bodyString
};
var resp = request(opts);
console.log(resp);
````
If I concatenate `buffer` (Buffer object in binary) to `bodyString` then I always get Content-Length: 0 in headers.

I think what I want is provided by the NodeJS request module:
https://github.com/request/request#multipartform-data-multipart-form-uploads

**Comment by dothebart** [comment] 2015-03-20 14:55
I tried it using these:

fs=require("fs")
var buffer=fs.read("Installation/Windows/Icons/arangodb.ico");

and monitored whats on the line using ngrep: (wireshark may also work for you)
ngrep -Wbyline host httpbin.org |less 

Here are the relevant parts of the conversation on the wire:

POST /post HTTP/1.1.
Host: httpbin.org.
Connection: Keep-Alive.
User-Agent: ArangoDB.
Accept-Encoding: deflate.
content-type: multipart/form-data; boundary=4be60ee5d163.
Content-Length: 295100.
.
--4be60ee5d163.
Content-Disposition: form-data; name="upload"; filename="test.png".
Content-Type: application/octet-stream.
.....
--4be60ee5d163--.

#################
T 54.175.222.246:80 -> 192.168.173.74:46550 [A]
HTTP/1.1 200 OK.
Server: nginx.
Date: Fri, 20 Mar 2015 14:53:22 GMT.
Content-Type: application/json.
Content-Length: 1048907.
Connection: keep-alive.
Access-Control-Allow-Origin: *.
Access-Control-Allow-Credentials: true.
.
{
  "args": {}, 
  "data": "", 
  "files": {
  "upload": "..."
  }, 
  "form": {}, 
  "headers": {
    "Accept-Encoding": "deflate", 
    "Content-Length": "295100", 
    "Content-Type": "multipart/form-data; boundary=4be60ee5d163", 
    "Host": "httpbin.org", 
    "User-Agent": "ArangoDB"
  }, 
  "json": null, 
  "origin": "80.152.136.67", 
  "url": "http://httpbin.org/post"
}

where upload in the reply and the post data were binary.

**Comment by razvanphp** [comment] 2015-03-20 14:57
So, I made it work. For the record, here is the solution:

````javascript
var input = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgA....A==';
var fileinbase64 = input.replace(/^data:image\/(png|jpg);base64,/, "");
var buffer = new Buffer(fileinbase64, 'base64');
var endpoint = "http://httpbin.org/post";
var bodyStart = '--4be60ee5d163\r\n'+
    'Content-Disposition: form-data; name="upload"; filename="test.png"\r\n'+
    'Content-Type: application/octet-stream\r\n\r\n';
var bodyEnd = '\r\n--4be60ee5d163--\r\n';

 multipartBody = Buffer.concat([
    new Buffer(bodyStart),
    buffer,
    new Buffer(bodyEnd)]
);

var opts = {
    url: endpoint,
    method: "POST",
    headers: {
        "Content-Type" : "multipart/form-data; boundary=4be60ee5d163"
    },
    body: multipartBody
};
var resp = request(opts);
console.log(resp);
````

Anyway, I think what would be nice to have is already provided by the NodeJS request module:
https://github.com/request/request#multipartform-data-multipart-form-uploads

**Comment by pluma** [comment] 2015-03-21 13:44
@razvanphp request uses an npm module to handle the multipart body generation. Sadly there doesn't seem to be any module that can build multipart bodies synchronously using buffers, so we'll probably have to implement this ourselves.

It's definitely an issue we're aware of and planning to address (either via npm or with a built-in function). Sorry about the inconvenience.
