### ISSUE TITLE
Deleted granted db's remain listed as available

### ISSUE THREAD

**Issue by fmarchal** [arangodb/arangodb#2303] opened 2017-02-06 17:23 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X] 3.1.6

On this operating system:
- [X] Linux 
  - [X] other: Archlinux

### this is a HTTP interface-related issue:
When a user is granted privileges on a database, and this database is deleted, it continues to be returned as 'available' to the privileged user:

1. User *root* creates db *deleteddb*:
	```sh
	curl -X POST --data-binary @- --dump - http://localhost:8529/_api/database --basic --user "root:" <<EOF
	{"name":"deleteddb"}
	EOF
	```
	```http
	HTTP/1.1 201 Created
	Content-Type: application/json; charset=utf-8
	Server: ArangoDB
	Connection: Keep-Alive
	Content-Length: 40

	{"result":true,"error":false,"code":201}
	```

2. User *root* grants privileges to user *myuser* on db *deleteddb*:
	```sh
	curl -X PUT --data-binary @- --dump - http://localhost:8529/_api/user/myuser/database/deleteddb --basic --user "root:" <<EOF
	{"grant":"rw"}        
	EOF
	```
	```http
	HTTP/1.1 200 OK
	Content-Type: application/json; charset=utf-8
	Server: ArangoDB
	Connection: Keep-Alive
	Content-Length: 68

	{"mydb":"rw","mydb2":"rw","deleteddb":"rw","error":false,"code":200}
	```

3. User *root* requests list of user *root*'s available db's:
	```sh
	curl -X GET --dump - http://localhost:8529/_api/user/root/database --basic --user "root:"
	```
	```http
	HTTP/1.1 200 OK
	Content-Type: application/json; charset=utf-8
	Server: ArangoDB
	Connection: Keep-Alive
	Content-Length: 93

	{"result":{"_system":"rw","deleteddb":"rw","mydb":"rw","midb":"rw"},"error":false,"code":200}
	```

4. User *root* requests list of user *myuser*'s available db's:
	```sh
	curl -X GET --dump - http://localhost:8529/_api/user/myuser/database --basic --user "root:"
	```
	```http
	HTTP/1.1 200 OK
	Content-Type: application/json; charset=utf-8
	Server: ArangoDB
	Connection: Keep-Alive
	Content-Length: 79

	{"result":{"mydb":"rw","mydb2":"rw","deleteddb":"rw"},"error":false,"code":200}
	```

5. User *root* deletes db *deleteddb*:
	```sh
	curl -X DELETE --dump - http://localhost:8529/_api/database/deleteddb --basic --user "root:"
	```
	```http
	HTTP/1.1 200 OK
	Content-Type: application/json; charset=utf-8
	Server: ArangoDB
	Connection: Keep-Alive
	Content-Length: 40

	{"result":true,"error":false,"code":200}
	```

6. User *root* requests list of user *root*'s available db's:
	```sh
	curl -X GET --dump - http://localhost:8529/_api/user/root/database --basic --user "root:"
	```
	```http
	HTTP/1.1 200 OK
	Content-Type: application/json; charset=utf-8
	Server: ArangoDB
	Connection: Keep-Alive
	Content-Length: 76

	{"result":{"_system":"rw","mydb":"rw","midb":"rw"},"error":false,"code":200}
	```

7. User *root* requests list of user *myuser*'s available db's; where *deleteddb* remains (**ERROR?**):
	```sh
	curl -X GET --dump - http://localhost:8529/_api/user/myuser/database --basic --user "root:"
	``` 
	```http
	HTTP/1.1 200 OK
	Content-Type: application/json; charset=utf-8
	Server: ArangoDB
	Connection: Keep-Alive
	Content-Length: 79

	{"result":{"mydb":"rw","mydb2":"rw","deleteddb":"rw"},"error":false,"code":200}
	``` 

Moreover, database *midb* was privileged to user *core*, both deleted long ago. Besides it remains listed as available to user *root*.
Also, database "mydb2" was privileged to user "myuser", "mydb2" was deleted but not "myuser". And "mydb2" remains as available to "myuser".
Web browser interface lists the three deleted databases too after login, but cannot access them from any user, it displays this error on screen:
```json
{"error":true,"errorNum":1228,"errorMessage":"database not found","code":404}
```
I have not observed this behaviour for non-granted databases.

**Comment by jsteemann** [comment] 2017-02-07 07:22
Partial duplicate of #2047 (should both be addressed in one go)

**Comment by hkernbach** [comment] 2017-03-13 14:09
Closing this issue because it is a duplicate of #2047 and #2368. Latest bugfix date will be 3.2 release.

**Closed by hkernbach** 2017-03-13 14:09 UTC
Labels: 1_Bug
