### ISSUE TITLE
User Functions strange issue

### ISSUE THREAD

**Issue by antokara** [arangodb/arangodb#1213] opened 2015-01-14 10:36 UTC
(ver 2.3.2)

I registered my custom function with a namespace "myFunctions::myFunction",
it worked properly for a while but then, at random times of the same exact AQL execution,
an error appeared that ..."user function runtime error: ReferenceError: myFunctions is not defined".

While this error appeared, I could see my function with
```
require("org/arangodb/aql/functions").toArray();
```
but when I tried to call it from within an AQL it failed.
If I retried a couple of times, it would finally pass. Then again at future executions it failed again.

It was fixed by recreating the same function with a different name, replacing it in the AQL and executing the AQL a couple of times. Then I reverted the function name in the AQL back to the original. Since then "unfortunately", I cannot reproduce this behavior.

If I come across this error again, I will update the issue with my new findings.
Perhaps, this can be used as a workaround in case someone else stumbles upon this strange issue.
Not sure if this issue should remain open or not.

**Comment by CoDEmanX** [comment] 2015-01-14 10:43
Are you running ArangoDB on a single machine? Did you or some automated process possibly change the database between the error and its resolution?

**Comment by antokara** [comment] 2015-01-14 10:47
it is installed on a single machine.
no such change was made between the executions that failed or passed.

**Comment by jsteemann** [comment] 2015-01-14 23:38
Please leave this issue open. It looks like the function was registered on all threads but one, so was available mostly but not always. Will look into this.

**Comment by jsteemann** [comment] 2015-01-16 08:35
I wasn't able to reproduce the issue no matter what I tried.
Is it possible that you provide the user-function code and also the AQL query that invokes it? That may help diagnose it. Thanks!

**Comment by jsteemann** [comment] 2015-01-16 12:08
After reading the AQL function execution code for several times I think I know what the problem is/was.
There are a few situations in which unexpected things may happen:

First of all, modifying outer-scope variables from an AQL user function can cause undefined behavior. Here's an example that modifies outer-scope variables `i` and `name`:
```js
require("org/arangodb/aql/functions").register("myFunctions::myFunction", function (values) {
  for (i = 0; i < values.length; ++i) {   /* accesses outer-scope variable "i" */
    name = values[i];   /* accesses outer scope variable "name" */
    if (name === "foo") return i;
  }
  return null;
});
```
The solution here is to use the `var` keyword to introduce the functions own variables.

Another potential problem (and I think you hit this one) happens when trying to register code that is not actually a function but an expression:
```js
require("org/arangodb/aql/functions").register("myFunctions::myFunction", "name = 'foo'");
```
Running such "function" (actually it's just an expression) will produce the error message that you have seen. The proper fix for this is to wrap the expression in a function body:

```js
require("org/arangodb/aql/functions").register("myFunctions::myFunction", "function () { return 'foo'; }");
```

AQL user functions were designed with the expectation that all user function code is contained in actual functions. However, this was not enforced when registering a user function. Starting with ArangoDB 2.5 this will be enforced so I strongly suggest you wrap all your expressions in simple functions as above. I have also updated the devel manual accordingly so these suggestions are contained in it.

Could you check whether one of the two above undefined-behavior scenarios were explaining the problem you have had?

**Comment by antokara** [comment] 2015-01-19 09:51
Here is my custom function:

```
/**
* Compares the Document Attribute with the value provided using the filter
*
* @param attribute string      The attribute which contains the actual value(s)
* @param operator string    The filter operator (one of self::FILTER_OP_XXX values),
* @param value string     The value (ie.   firstName) without the @ prefix
*
* @return boolean		If comparison successful or not
*/
require("org/arangodb/aql/functions").register("myFunctions::findInAttribute",
	function (attribute, operator, value) {

		function compareAttribute(
			attribute,
			operator,
			value
		) {
			if (!(value)) {
				return false;
			}

			switch (operator)
			{
				case 'eq':
					return attribute.toLowerCase()==value.toLowerCase();
					break;
				case 'neq':
					return attribute!=value;
					break;
				case 'gt':
					return attribute>value;
					break;
				case 'gte':
					return attribute>=value;
					break;
				case 'lt':
					return attribute<value;
					break;
				case 'lte':
					return attribute<=value;
					break;
				case 'contains':
					return (attribute.toLowerCase().indexOf(value.toLowerCase()) !== -1);
				break;
				case 'doesnotcontain':
					return (attribute.toLowerCase().indexOf(value.toLowerCase()) === -1);
				break;
				case 'endswith':
					return attribute.toLowerCase().indexOf(value.toLowerCase(), attribute.length - value.toLowerCase().length) !== -1;
				break;
				case 'startswith':
					return (attribute.toLowerCase().indexOf(value.toLowerCase()) === 0);
				break;
				default:
					return false;
				break;
			}
		}

		if (typeof attribute == 'array' || typeof attribute == 'object') {
			for (var langCode in attribute) {
				if (attribute.hasOwnProperty(langCode)) {
					if (compareAttribute(attribute[langCode], operator, value)) {
						return true;
					}
				}
			}
		} else if(compareAttribute(attribute, operator, value)) {
			return true;
		}
		return false;
	});
```


I declared a function inside a function because I could not find a way to call a custom function, from within another custom function. Not that I need them as two separate functions but just in case it could be reused as separate code...

I think my code does not match the situations you describe, without being 100% sure ofc.

**Comment by jsteemann** [comment] 2015-01-19 10:43
Your custom function code does not raise any of the potential problems I mentioned (i.e. not wrapping the code into a JS function, not using `var`). It looks pretty ok.
Were there any other user functions around in your database that were prone to these issues? It think the problems may have occurred also when only a single function was problematic. Could this be the case?

**Comment by antokara** [comment] 2015-01-19 10:48
at one point I had registered the function myFunctions::compareAttribute(attribute, operator, value) as it appears above and they both coexisted for a while, but could not use it from within myFunctions::findInAttribute, so I unregistered it and left myFunctions::compareAttribute the only custom user function in existence.

**Comment by antokara** [comment] 2015-01-19 10:51
Also, I would like to refer to my old issue https://github.com/triAGENS/ArangoDB/issues/974
I think with a custom function similar to the one above, the issue could be resolved without adding a native AQL function for it. This way it's flexible to developer's needs. Except if a native similar function would be allot faster, but not sure if it can be made to suit all needs;

**Comment by jsteemann** [comment] 2015-01-19 11:04
I admit I have no ideas other than above what could have caused the problems. 
Let's leave this issue open because it may reoccur. If so, please post any issues here (including the ArangoDB version the problem will occur on).
I slightly refactored the user function registration code in 2.3.5 and in 2.4.1 while trying to reproduce the problem. But I think this won't help as the error will only occur if the user function was registered but is not a JavaScript function. And as mentioned, I have no idea how this may happen other than the above.

**Comment by antokara** [comment] 2015-01-19 11:10
ok, I updated to 2.4.0. If it reoccurs I will post here along with the version, thanks!

**Closed** 2015-02-16 11:41 UTC
Labels: aql
