### ISSUE TITLE
Collection name in RETURN statement causes ArangoDB to crash

### ISSUE THREAD

**Issue by mtanvir** [arangodb/arangodb#2492] opened 2017-05-22 15:42 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1

On this operating system:
- [x] Linux 
  - [x] other: Oracle Linux 7.1

### this is an AQL-related issue:
I'm issuing AQL via:
- [x] web interface with this browser: Chrome  running on this OS: macOs 10.12.4

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:
```FOR product IN products RETURN products```

Is it really necessary to support collection names in return statement like this?
```RETURN products```

The way I read it, above is the shortcut for
```FOR product IN products RETURN product```

I was helping one of my developer learn AQL, and he mistyped the query as below
```FOR product IN products RETURN products```

Above resulted in hard crash of ArangoDB as it ran out of memory. VM has 64GB RAM and 8 cores. Products collection has about 145K documents, fairly large in size. Explain suggests it was trying to return entire product collection for each product. That exhausted available RAM very quickly and crashed the database.

I know this is a user input error, and it’s impossible to guard against all the edge cases, but I was really surprised how easy it is to crash the DB with 6 word (mistyped) AQL statement.

Apart from the shorthand expression I listed above, what other benefits are there for supporting collection-name in RETURN statements?

**Comment by jsteemann** [comment] 2017-05-22 16:11
In general collection names in an AQL query should be treated the same a list of documents from the collection. Collection names can in theory be used anywhere in an AQL expression. Using a collection name in an AQL expression will produce an array with all the documents from that collection.
A simple example:
```
FOR doc IN 1..100
  RETURN products
```
But this is not limited to `RETURN`:
```
FOR doc IN 1..100
  FILTER doc IN products
  RETURN doc
```
In most cases using a collection name in such places it indicates a typo in the query: a collection name is used somewhere where the user wanted to put a variable name. But as both collection names and variable names are valid, this is no "hard" error, so the query continues, producing presumably unexpected results.

Currently using a collection name somewhere in an expression will issue a warning, as it is most likely a typo in the query and is often (but not always) unintended from the user point of view.

With 3.2 there is a new option `--query.fail-on-warning` (currently in development) that allows aborting AQL queries when they encounter whatever warning. This will make the above query fail instantly, plus a few others for which the result will probably not be as intended.
We cannot simply disallow using collection names in expressions because that would render several queries invalid. However, using the new options users have full control starting with 3.2. They can choose either downwards-compatibility (turn option off) or guard against unintended side-effects (turn option on).

**Comment by mtanvir** [comment] 2017-05-22 16:57
Thanks for your reply. I understood what it was doing, I was trying to figure out why was it necessary from design standpoint. If user wanted an array of documents in their return statement or elsewhere in expression, they can always use LET upfront and assign entire collection if they wish. 

I'm happy that 3.2 will include an option to stop this behaviour. In the meantime I just have to hope no one mistypes the query. Hope is not a strategy though!

**Comment by jsteemann** [comment] 2017-05-30 07:11
The option `--query.fail-on-warning` has now landed officially in devel and is contained in the manual.
From the CHANGELOG:
```
* added server startup option `--query.fail-on-warning`

  setting this option to `true` will abort any AQL query with an exception if
  it causes a warning at runtime. The value can be overridden per query by
  setting the `failOnWarning` attribute in a query's options.
```
The option will be available with the next 3.2 release.

**Comment by jsteemann** [comment] 2017-06-19 16:06
Fixed via option `--query.fail-on-warning` since 3.2beta1.

**Comment by dothebart** [comment] 2017-07-21 08:45
We're pleased to anounce that ArangoDB 3.2 containing this is now available for download - Closing.

**Closed by dothebart** 2017-07-21 08:45 UTC
Labels: 2 Fixed, 3 AQL

**Comment by mtanvir** [comment] 2017-07-25 13:11
The config flag works beautifully. Many thanks! I migrated over to RocksDB engine and it has been amazing. Cheers.
