### ISSUE TITLE
cant use FLOOR and RAND in LIMIT

### ISSUE THREAD

**Issue by akhilbatra898** [arangodb/arangodb#2089] opened 2016-10-06 20:59 UTC
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ 1] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [1 ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:
### this is an AQL-related issue:

[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ 1] arangosh
- [ ] this Driver:

The following problem occurs: 
i run this command in arangosh
but it gives error
`db._query('FOR v in profiles LIMIT FLOOR(RAND()+1),1 RETURN v._key').toArray()`

Instead I would be expecting: 

a random vertex with its key

**Comment by baslr** [comment] 2016-10-06 23:25
Hi @akhilbatra898,

please have a look at #1011, #1760 and also at the documentation for `LIMIT` ( https://docs.arangodb.com/3.0/AQL/Operations/Limit.html).

It also would be helpful, when you also provide the error message.

**Comment by jsteemann** [comment] 2016-10-07 06:37
@akhilbatra898 : as @balsr pointed out, LIMIT does not support arbitrary expression as its arguments.
However, you could use
```
FOR v IN profiles SORT RAND() LIMIT 1 RETURN v._key
```
instead.

**Comment by akhilbatra898** [comment] 2016-10-07 07:13
I am aware of this way. 
But sort is expensive. For every single query sort cost will be added. And i have million nodes in database

**Comment by jsteemann** [comment] 2016-10-07 07:27
Have you actually checked if the sort is really that expensive?
It seems that `SORT RAND()` is quicker than passing an arbitrary LIMIT offset value, at least when I tried it with 1,000,000 documents:
```
arangod> time = require("internal").time; s = time(); db._query("FOR doc IN test SORT RAND() LIMIT 1 RETURN doc._key"); time() - s;
0.0009431838989257812
arangod> time = require("internal").time; s = time(); db._query("FOR doc IN test SORT RAND() LIMIT 1 RETURN doc._key"); time() - s;
0.0003871917724609375
arangod> time = require("internal").time; s = time(); db._query("FOR doc IN test SORT RAND() LIMIT 1 RETURN doc._key"); time() - s;
0.0005550384521484375
```
```
arangod> time = require("internal").time; s = time(); db._query("FOR doc IN test LIMIT @rand, 1 RETURN doc._key", { rand: Math.floor(Math.random() * 1000 * 1000) }); time() - s;
0.017254114151000977
arangod> time = require("internal").time; s = time(); db._query("FOR doc IN test LIMIT @rand, 1 RETURN doc._key", { rand: Math.floor(Math.random() * 1000 * 1000) }); time() - s;
0.01751399040222168
arangod> time = require("internal").time; s = time(); db._query("FOR doc IN test LIMIT @rand, 1 RETURN doc._key", { rand: Math.floor(Math.random() * 1000 * 1000) }); time() - s;
0.006273984909057617
```

**Comment by akhilbatra898** [comment] 2016-10-07 07:31
No i didn't try since my ram was getting full when querying for whole collection. I thought aince sorting takes nlogn. And offset will directly point to the location. 
Anyway i will try with sort now and see.
Thanks a lot for your help :-)

**Comment by jsteemann** [comment] 2016-10-07 07:32
I think a `SORT RAND() LIMIT 1` can be optimized away, so that no sort operation is actually executed.

**Comment by akhilbatra898** [comment] 2016-10-07 07:34
Thanks i will look into it

**Comment by jsteemann** [comment] 2016-11-17 11:17
Main problem solved by using `SORT RAND()`.
Actual feature request (using expressions in LIMIT) is a duplicate of #1011.

**Closed by jsteemann** 2016-11-17 11:17 UTC
Labels: 2_Question
