### ISSUE TITLE
Foxx - CORS - Can't read response headers

### ISSUE THREAD

**Issue by solisoft** [arangodb/arangodb#2149] opened 2016-11-05 17:37 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [X] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [X] MacOS, version:

## Issue

I'm trying to get X-Session-Id from my single page app which run on http://localhost:3333

````
$.ajax({
         type: 'POST',
         url: url + "auth/login",
         data: JSON.stringify({ "username": $("#username").val(), "password": $("#password").val() }),

      }).then(function(data, status, xhr) {
        console.log(xhr.getAllResponseHeaders());
      });
````

On my browser, here is the response headers
````
Access-Control-Allow-Credentials:false
Access-Control-Allow-Origin:http://localhost:3333
Access-Control-Expose-Headers:etag, content-encoding, content-length, location, server, x-arango-errors, x-arango-async-id
Connection:Keep-Alive
Content-Length:257
Content-Type:application/json; charset=utf-8
Server:ArangoDB
X-Session-Id:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1aWQiOm51bGwsImlhdCI6MTQ3ODM2NzAyNzI5MiwicGF5bG9hZCI6eyJfa2V5IjoiNTI4MTY4MTIiLCJfaWQiOiJ1c2Vycy81MjgxNjgxMiIsIl9yZXYiOiI1MjgzODE4NiIsImEiOnRydWUsImVtYWlsX2NvZGUiOiJUYlVLMXgzOWIwcjUxTmJxaGNoY3QzUGk3ZGRDZHBuNktrYUMyTEpBIiwiZm4iOiJCT05OQVVSRSIsImxuIjoiT2xpdmllciIsInVzZXJuYW1lIjoib2xpdmllckBzb2xpc29mdC5uZXQifSwiZXhwIjoxNDc4MzcwNjI3MzAxfQ.TVOx2C9_NVws1fH9LpTiAfT6FkBd-6E0dzoxk0pswpOxtoQ0U4jXH2qYOTeMf7ocod5Dg1p9kjEcDAVnFjEzrg
````

 But on my jQuery object, here what I get : 
````
Server: ArangoDB
Content-Type: application/json; charset=utf-8
Content-Length: 257
````

The problem is that I need to read `X-Session-Id` header ... to then run queries on my webservice (Foxx powered).

**Comment by jsteemann** [comment] 2016-11-07 23:12
Does the client code send the `Access-Control-Request-Headers` header? I am by no means a CORS specialist, but I think this header is required in order for the client to send the `X-Session-Id` to the server after the CORS preflight request. 
Forget this if the client does not need to send the `X-Session-Id` header to the server in a CORS request.

There is also another issue I think, caused by the whitelist of headers in the `Access-Control-Expose-Headers` header value returned by the server. `X-Session-Id` is not in that list, and I think this tells the browser that it must not access any response header that's not in that list. This includes `X-Session-Id` so the browser does not hand it to the JavaScript code.

As far as I can see the whitelist in `Access-Control-Expose-Headers` is currently hard-coded to
```
 89 std::string const StaticStrings::ExposedCorsHeaders(
 90     "etag, content-encoding, content-length, location, server, "
 91     "x-arango-errors, x-arango-async-id");
```
I haven't tried this, but there is a chance that this response header's value is changeable from your Foxx app code by using the following code in the handler:
```
res.headers["access-control-expose-headers"] = "etag, content-encoding, content-length, ..., x-session-id";
``` 
(note: maybe the case of these headers needs to be adjusted, that's unclear to me).
As I said I haven't tried this out myself. If you could check if this works that would be great. Thx!

**Comment by jsteemann** [comment] 2016-11-09 07:29
See also #2159.

**Comment by jsteemann** [comment] 2016-11-09 15:33
It looks like the `Access-Control-Expose-Headers` response header is always overwritten by the server code when the response is sent. Foxx apps currently cannot set it to a different value than the hard-coded one shown above.
I have submitted a fix for this which allows setting the header to a different value, by simply using `res.headers["access-control-expose-headers"] = ...` as for any other HTTP response header.
The fix has been pushed into 3.0, 3.1 and devel branches and will be included in the next releases (3.0.12, 3.1.1).

**Comment by solisoft** [comment] 2016-11-09 15:45
Great !!

**Comment by dothebart** [comment] 2016-11-25 14:36
3.0.12 is available for download via the regular upgrade channels - closing.

**Closed by dothebart** 2016-11-25 14:36 UTC
Labels: 1_Bug, Fixed, foxx

**Comment by solisoft** [comment] 2016-11-27 20:38
Just tested on 3.1.1 and it works fine now 👍

**Comment by jakobrosenberg** [comment] 2017-03-13 08:56
I can't get CORS to work. Is there an example for implementing this?

**Comment by pluma** [comment] 2017-03-14 01:45
@jakobrosenberg Can you open a separate issue to ask for a guide on setting up CORS with Foxx? I agree that we should have a sub-chapter or cookbook recipe for this but I don't think we do (yet). This issue is specifically about a bug in ArangoDB that prevented CORS from working at all and I would like to keep it separate.

**Comment by jakobrosenberg** [comment] 2017-03-14 07:41
@pluma No problem :)
