### ISSUE TITLE
SIGHUP should rotate the log

### ISSUE THREAD

**Issue by fceller** [arangodb/arangodb#1783] opened 2016-03-15 10:09 UTC
Under Debian 8 at least, it closes the supervisor instead.

**Comment by razvanphp** [comment] 2016-03-17 08:27
So there is nothing to do to release the log files besides restarting the server? Problem is, the server is running slowly out of disk space because of this.

Are you guys sure this is the reason of the fake used space? I was just assuming it's the log being kept open.

**Comment by fceller** [comment] 2016-03-17 09:37
@razvanphp our assumption was, that #1662 was caused by database log living in "/var/lib/arangodb". While this bug is for the informal log files living in "/var/log/arangodb".

The daemon log files should normal not grow dramatically. They only contain a few lines for each server start.

For the database log files in #1662 @ericfiala has reported that the problem has been solved. Do have any way to find out, where the space is eaten up? Is it the files in "/var/lib" or the files in /"var/log"?

**Comment by razvanphp** [comment] 2016-03-17 09:41
The space is not used, that's the problem, `du -sh /` returns 79G, while `df -h` says 255G are used.

So the difference I assumed is locked by arango keeping the **request** log files, that is huge in our case, but rotate by logrotate every night. I pasted the output of lsof to prove my theory, but I can't be sure this is the cause.

What's for sure is that our disk gets full :(

**Comment by fceller** [comment] 2016-03-17 11:08
@razvanphp that sound like a good candidate. I will fix the log rotate (SIGHUP) and create a 2.8.6.

**Comment by fceller** [comment] 2016-03-17 11:46
@razvanphp I tested under Debian 8. The bug seems to be that sending SIGHUP to the supervisor shuts down ArangoDB. So, please be careful. DO NOT send a SIGHUP to the supervisor.

Having said that warning: The requests log file is written by the ArangoDB server, not the supervisor. Sending a SIGHUP to the server (NOT the supervisor), closes the log file and reopens it again.

Can you try a "lsof +d" on the log file directory? It should show something like

```
root@germany:~# lsof +d /var/log/arangodb
COMMAND   PID     USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
arangodb 9274 arangodb    3w   REG    8,1        0 9330766 /var/log/arangodb/requests.log.daemon
arangodb 9274 arangodb    4w   REG    8,1     1212 9330880 /var/log/arangodb/arangod.log.daemon
arangod  9275 arangodb    3w   REG    8,1      778 9330882 /var/log/arangodb/requests.log
arangod  9275 arangodb    4w   REG    8,1     1980 9330885 /var/log/arangodb/arangod.log
```

Does it show any open files? If not, it can be a sign that there is indeed a removed requests.log file.

If it shows open files, can you rename this files to ".old"?

Can you then locate the ArangoDB server (not the supervisor) and send a SIGHUP to it?

Can you then redo the "lsof +d /var/log/arangodb"?

**Comment by razvanphp** [comment] 2016-03-17 12:00
```
(root@ay-p-arango1) {~} # lsof +d /var/log/arangodb
COMMAND     PID     USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
bash       3912  fkrause  cwd    DIR  202,1    12288 17041931 /var/log/arangodb
htop      36156  fkrause  cwd    DIR  202,1    12288 17041931 /var/log/arangodb
arangodb  68995 arangodb    4w   REG  202,1     3112 17041953 /var/log/arangodb/arangod.log
bash      80296  fkrause  cwd    DIR  202,1    12288 17041931 /var/log/arangodb
bash     102139  fkrause  cwd    DIR  202,1    12288 17041931 /var/log/arangodb
```

but if I do
```
(root@ay-p-arango1) {~} # lsof -u arangodb |grep 'var/log'
arangodb 40679 arangodb    3w   REG              202,1            0 17042127 /var/log/arangodb/arangod.log.requests.daemon (deleted)
arangodb 40679 arangodb    4w   REG              202,1        17088 17041956 /var/log/arangodb/arangod.log.daemon (deleted)
arangodb 68995 arangodb    3w   REG              202,1 195969208422 17039516 /var/log/arangodb/arangod.log.requests (deleted)
arangodb 68995 arangodb    4w   REG              202,1         3112 17041953 /var/log/arangodb/arangod.log
```
(btw, this is another bug, if I choose different log files for requests and arango, "arangod.log.requests.daemon" is also created, which should not happen)

It might be that our logrotate config was messed up (I just saw it) and the request log file was deleted, then arango seems to write to some "unknown" space. Maybe this needs to be treated as a bug too.

How can I identify which one is the supervisor? In `ps aux` both are called supervisor now... `/var/run/arangodb/arangod.pid` contains the PID of the server or the supervisor?

**Comment by fceller** [comment] 2016-03-17 12:05
@razvanphp if you delete an still open file, than this file still exists - but "ls" will no longer show it.

The server is the one that write the big file

    arangodb 68995 arangodb    3w   REG              202,1 195969208422 17039516 /var/log/arangodb/arangod.log.requests (deleted)

This (68995) should be the same pid that is stored in `/var/run/arangodb/arangod.pid` and correspond to the server (not supervisor) pid.

If both are equal, "kill -HUP 68995" should rotate the log file.

**Comment by razvanphp** [comment] 2016-03-17 12:13
haha, yes, that did the trick, free space got back to normal, thank you!

is the HUP thing something documented? I saw that he renames the log files with ".old" at the end, this does not work very well with logrotate, I'm not sure if the HUP should happen in `postrotate`.

This is how I would configure it:
```
kill -HUP `cat /var/run/arangodb/arangod.pid`
```

**Comment by fceller** [comment] 2016-03-17 12:21
The normal sequence should be:

rename the logfile to something else (add .old, add a date or add a number)
send the HUP

I'm not a logrotate expert, but "postrotate" sound like the right place.

**Comment by razvanphp** [comment] 2016-03-17 12:33
Until now it worked perfectly fine, because logrotate was configured in our case with `copytruncate`
(Truncate the original log file in place after creating a copy, instead of moving the old log file and optionally creating a new one.)

I fixed the wildcard problem in logrotate that deleted the file, and we should be fine. I will not send HUP since it's not needed in this case, and also because arango renames the log file itself to `name.old`, and this will interfear with logrotate.

So I don't know if there is something to improve on your side with this ticket, feel free to close it.

Thank you again!

**Comment by fceller** [comment] 2016-03-17 12:35
Still open: SIGHUP should NOT kill the supervisor.

**Closed** 2016-03-21 15:36 UTC
Labels: 1_Bug, core
