### ISSUE TITLE
"Transfer size per second" graph is misaligned except during mouse-over

### ISSUE THREAD

**Issue by instinct-vfx** [arangodb/arangodb#2857] opened 2017-07-21 11:49 UTC
I'm using the latest ArangoDB of the respective release series:
- [ x] 3.2.0

On this operating system:
- [ x] Windows, version: 

I'm using the web interface with this browser:     running on this OS:
- [x ] _system database?

I am seeing this using Chrome Version 59.0.3071.109 (Official Build) (32-bit)

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
3) use database [ x ] `_system` 
4) The transfer size per second graph is misaligned. It aligns correctly on mouse over.

See attached gif
![arango_table_alignment](https://user-images.githubusercontent.com/243828/28462378-48244fcc-6e1b-11e7-87df-f3f872f8f3ed.gif)

Instead the columns should all be aligned.

**Comment by instinct-vfx** [comment] 2017-07-21 11:51
I just double checked. This does not occure with Firefox 54.0 (32-bit)

**Comment by hkernbach** [comment] 2017-08-09 10:43
Thanks for your report.

I've tested with: Version 59.0.3071.115 (Official Build) (32-Bit) - which is slightly newer as your tested version. There I'm not able to reproduce this. Could you please re-try if this is still an issue?

Note: Also tested version 60.0.3112.90 (Official Build) (32-Bit) - current version. No misalignments there as well.

**Comment by instinct-vfx** [comment] 2017-08-09 12:53
I just looked into this again for a few minutes. It seems to be dependent on the screen resolution. What resolution did you test with? When i have my screens at native resolution i see the offset if i turn on windows' scaling feature i don't.

**Comment by hkernbach** [comment] 2017-08-09 13:23
Tried some resolutions between 1024x768 and 1920x1200. What resolution are you using?

**Comment by instinct-vfx** [comment] 2017-08-09 19:25
I think it starts beyond 1920 widths. At home i am running 2880x1620 not sure about work but i think it is 2560x1440

**Comment by hkernbach** [comment] 2017-12-04 12:43
@mpv1989 could you check that with your display?

**Comment by mpv1989** [comment] 2017-12-05 08:23
It works for 2560x1440. I can later check on my 4k display.

**Comment by mpv1989** [comment] 2017-12-07 16:47
@hkernbach I was able to reproduce this on my 4k display. Adding the following css fixed this issue.
```
.dashboard-row {
    width: 100%;
}

**Comment by hkernbach** [comment] 2017-12-07 16:53
already commited?

**Comment by mpv1989** [comment] 2017-12-08 08:09
no

**Comment by hkernbach** [comment] 2018-01-08 17:59
@mpv1989 please test your suggested patch in that branch: 
https://github.com/arangodb/arangodb/tree/bug-fix/dashboard-ui-test

Remember to rebuild the frontend using `grunt deploy` in the aardvark folder or say `make frontend` in the build folder.

**Comment by dothebart** [comment] 2018-04-26 13:46
@hkernbach @mpv1989 @mchacki can you please follow up on this so the fix can be accepted?

**Comment by hkernbach** [comment] 2018-04-26 17:10
pr opened: https://github.com/arangodb/arangodb/pull/5216

**Comment by hkernbach** [comment] 2018-10-17 09:33
PR merged. Should be fixed. If not, please re-open the issue.

**Closed by hkernbach** 2018-10-17 09:33 UTC
Labels: 1 Bug, 3 UI, 4 Windows
