### ISSUE TITLE
Error when upgrading arangoDB on linux ubuntu 16.04

### ISSUE THREAD

**Issue by kavin26** [arangodb/arangodb#3075] opened 2017-08-18 14:27 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] 3.1
- [ ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [x] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Tried to upgrade arangoDB version from `3.0.12` to `3.2` . Following are the steps i followed
Step 1 : `curl -O https://www.arangodb.com/repositories/arangodb32/xUbuntu_14.04/Release.key`
Step 2 : `sudo apt-key add - < Release.key`
Step 3 : `echo 'deb https://www.arangodb.com/repositories/arangodb32/xUbuntu_14.04/ /' | sudo tee /etc/apt/sources.list.d/arangodb.list`
Step 4 : `sudo apt-get install apt-transport-https`
Step 5 : `sudo apt-get update`
Step 6 : `sudo apt-get install arangodb3=3.2.1`
At the last step when upgrading arangoDB, an error was thrown, which read as below :
`Upgrading database files.
2017-08-18T13:58:18Z [23305] WARNING {memory} /sys/kernel/mm/transparent_hugepage/enabled is set to 'always'. It is recommended to set it to a value of 'never' or 'madvise'
2017-08-18T13:58:18Z [23305] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/enabled"'
2017-08-18T13:58:18Z [23305] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/defrag"'
2017-08-18T13:58:18Z [23305] INFO {syscall} file-descriptors (nofiles) hard limit is 1048576, soft limit is 1048576
2017-08-18T13:58:19Z [23305] ERROR error while opening database collections: got invalid indexes for collection '_statistics15' (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/MMFiles/MMFilesCollection.cpp:2004). Please report this error to arangodb.com
dpkg: error processing package arangodb3 (--configure):
 subprocess installed post-installation script returned error exit status 1
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by kavin26** [comment] 2017-08-18 14:29
Kindly give me suggestions to debug it...now i couldn't able to access the previous version too, mentioning `login failed`...

**Comment by jsteemann** [comment] 2017-08-18 14:42
Seems to be caused by upgrading from 3.0 to 3.2 without upgrading to 3.1 in-between.
The "indexes" attribute in the collections' parameter.json files then seems to be missing.

**Comment by jsteemann** [comment] 2017-08-21 08:34
Seems to be caused by upgrading from 3.0 to 3.2 without upgrading to 3.1 in-between.
The "indexes" attribute in the collections' parameter.json files then seems to be missing.

**Comment by kavin26** [comment] 2017-08-21 10:32
i'd be able to update to v3.1.27 after changing the path of repository to point arangodb31...kindly regret for replying late...issue got solved...thank you so much

**Comment by jsteemann** [comment] 2017-08-21 10:44
Still I think this is a big problem, as it's probably not too uncommon to skip a few versions when upgrading.
And upgrading should work then.

**Comment by dothebart** [comment] 2017-08-24 14:12
ArangoDB 3.2.2 containing this bugfix is available for download - thanks for reporting.

Closing.

**Closed by dothebart** 2017-08-24 14:12 UTC
Labels: 1 Bug, 2 Fixed, 3 Core
