### ISSUE TITLE
Query that crashes ArangoDB 3.0.5 server

### ISSUE THREAD

**Issue by Calrain** [arangodb/arangodb#2018] opened 2016-08-24 14:52 UTC
## my environment running ArangoDB 3.0.5
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [x] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb 16.04 LTS
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:  Chrome 52.0.2743.116 m running on this OS: Windows 10
- [ ] arangosh
- [ ] this Driver:

It is running on Azure VM running Ubuntu 16.04

I've run `db._explain('LET d = (FOR doc IN _apps FILTER doc._id == "_apps/74" RETURN MERGE(doc)) RETURN d')` and it didn't crash the server..

The AQL query in question is:
`LET d = (FOR doc IN _apps FILTER doc._id == "_apps/74" RETURN MERGE(doc)) RETURN d`
The issue can be reproduced using any dataset you have, when you query with the FILTER such that it returns a SINGLE document. It can be from either a system or a user created collection, either will crash the server.

If your internal FILTER returns 0 or 2 or more documents then it will not crash and instead will respond as expected.

If your query is just the internal component of the LET command, it will not crash the server.

When you log into arangosh after the server stops responding this is the output:
===========================================================
    arangosh (ArangoDB 3.0.5 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.2g-fips  1 Mar 2016)
    Copyright (c) ArangoDB GmbH

    Pretty printing values.
    Could not connect to endpoint 'http+tcp://127.0.0.1:8529', database: '_system', username: 'root'
    Error message: 'Could not connect to 'http+tcp://127.0.0.1:8529' 'connect() failed with #111 - Connection refused''

    127.0.0.1:8529@_system> exit
===========================================================

Resolution:
Type these two commands into the terminal:
`service arangodb3 stop`
`service arangodb3 start`

The service shows as still running, you have to forcibly stop it and start it again.

### this is a web interface-related issue:
I'm using the web interface with this browser: Chrome 52.0.2743.116 m running on this OS: Windows 10
- [x] authentication is enabled?
- [ ] using the cluster?
- [x] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as root
3) use database [x] `_system` [ ] other: 
4) click QUERIES menu
5) Type this query and click Execute
`LET d = (FOR doc IN _apps FILTER doc.mount == "/_api/gharial" RETURN MERGE(doc)) RETURN d`
(Ensure the FILTER command points to a single document that exists, e.g. it only returns 1 document)

The following problem occurs:
You may see a message saying it successfully canceled the query, you will not get a query result window.
Try running the query a few times, it will take a little while for the UI to realise the server stopped responding.

Instead I would be expecting: 
The query to return:
```
[
  [
    "(non-representable type)"
  ]
]
```
NOTE: If your internal FILTER returns 0 documents or 2 or more documents, the query works correctly.
e.g.:
Query that returns 2 or more documents:
`LET d = (FOR doc IN _apps FILTER doc.isSystem == true RETURN MERGE(doc)) RETURN d`
Result:
```
[
  [
    "(non-representable type)",
    "(non-representable type)"
  ]
]
```
Query that returns 0 documents:
`LET d = (FOR doc IN _apps FILTER doc.doesNotExist == "nothing" RETURN MERGE(doc)) RETURN d`
Result:
```
[
  []
]
```
Not an installation issue, standard install on Ubuntu 16.04 LTS

I found the issue while testing some query formats and because this one crashes the server, it probably is worth reporting.

**Comment by jsteemann** [comment] 2016-08-24 15:13
Thanks for reporting this. I just reproduced the issue in 3.0

**Comment by jsteemann** [comment] 2016-08-24 15:37
Fixed in 3.0.6 and devel

**Comment by Calrain** [comment] 2016-08-24 15:40
That was fast! Great stuff.

**Comment by dothebart** [comment] 2016-09-27 13:15
3.0.10 is available for download now.

**Closed by dothebart** 2016-09-27 13:15 UTC
Labels: 1_Bug, aql

**Comment by saliormoon** [comment] 2016-10-09 07:20
I have the same problem :
Could not connect to endpoint 'http+tcp://locahost:8531', database: '_system', username: 'root'
Error message: 'Could not connect to 'http+tcp://localhost:8531' 'connect() failed with #111 - Connection refused''
I have do the same action:
service arangodb3 stop
service arangodb3 start
but it does not work and still keeps the same problem. Could anyone give me some suggestions?

**Comment by Calrain** [comment] 2016-10-09 07:23
Did you configure it to specifically use port 8531? By default HTTP is port 8529 and SSL is port 8530.

**Comment by saliormoon** [comment] 2016-10-09 07:33
Actually, I have build a arangodb cluster with one coordinator(9.31.3.58:8531) and one agency (8.31.3.56:8529) and the agency can work normally but the coordinator can not and has the problem:
Could not connect to endpoint 'http+tcp://9.31.3.58:8531', database: '_system', username: 'root'
Error message: 'Could not connect to 'http+tcp://9.31.3.58:8531' 'connect() failed with #111 - Connection refused'
so could anyone give me a hand?

**Comment by saliormoon** [comment] 2016-10-09 09:53
I have solved the problem by myself. The cause is that I forget to update the endpoint from 127.0.0.1:8529 to 9.31.3.58:8531 in the arangod.conf. And when I update the right endpoint, it can work well.Thanks.
