### ISSUE TITLE
regexp support

### ISSUE THREAD

**Issue by OzqurYalcin** [arangodb/arangodb#7580] opened 2018-12-01 18:51 UTC
```js
    var Arango = require("arangojs").Database;
    var arangoconn = new Arango("http://username:password@localhost:8529");
    var search1 = async (key) => {
        return new Promise((resolve, reject) => {
            arangoconn.useDatabase("db").query({
                query: "FOR data IN keywords FILTER data.keyword LIKE @key RETURN data",
                bindVars: {
                    key: "%" + key + "%"
                }
            }).then(
                cursor => cursor.all()
            ).then(
                res => resolve(res),
                err => reject(err)
            );
        });
    };
    var search2 = async (key) => {
        return new Promise((resolve, reject) => {
            arangoconn.useDatabase("db").collection("keywords").byExample({
                keyword: new RegExp(key)
            }).then(
                cursor => cursor.all()
            ).then(
                res => resolve(res),
                err => reject(err)
            );
        });
    };
    var data1 = await search1("keyword");
    var data2 = await search2("keyword");
    console.log(data1);
    console.log(data2);
```
search1 functions worked fine, but search2 failed.
i think, arrangodb must support regex search as in search2 function.

**Comment by Simran-B** [comment] 2018-12-03 10:49
Duplicate of https://github.com/arangodb/arangojs/issues/582. Closing this issue here, because it's mainly about the ArangoJS driver.

**Closed by Simran-B** 2018-12-03 10:49 UTC
