### ISSUE TITLE
Db crashes when large data is inserted

### ISSUE THREAD

**Issue by arunvenkat1911** [arangodb/arangodb#17573] opened 2022-11-11 14:34 UTC
Hi Team, 

We tried to insert 5M records, the db crashed. 
Is there any settings to move the data into disk when overflow happens? 
Please help us with the solution. 

Arun.

**Comment by mpoeter** [comment] 2022-11-11 14:39
I suppose this is a duplicate of #17572

**Closed by mpoeter** 2022-11-11 14:39 UTC
