### ISSUE TITLE
cluster authentication arangodb3.1.3

### ISSUE THREAD

**Issue by hellomanjack** [arangodb/arangodb#2379] opened 2017-03-17 02:59 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [1 ] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ 1] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [1 ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [1 ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ 1] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [1 ] authentication is enabled?
- [1 ] using the cluster?
- [ 1] _system database?

These are the steps to reproduce:
1) use the dcos 1.8.8,arangodb 3.1.3. 
2) use the default json, but add the ----arangodb_jwt_secret="XXXXXX"
3) open the "Service" label.  I need to enter, but I don't know the username and password.
4) also the cluster is not stable,it runs overnight. Then i can't open the the web site according to the 
"Service" tab. But arangodb shows it's healthy.

...

The following problem occurs: [Screenshot?] 
![image](https://cloud.githubusercontent.com/assets/25783698/24027047/ce7d5930-0aff-11e7-9197-7cd284489e9c.png)
![image](https://cloud.githubusercontent.com/assets/25783698/24027069/e29a32e4-0aff-11e7-94ea-737ab77d877b.png)
![image](https://cloud.githubusercontent.com/assets/25783698/24027079/f3ea1672-0aff-11e7-9264-b9938d835493.png)
![image](https://cloud.githubusercontent.com/assets/25783698/24027093/03d150fa-0b00-11e7-9112-a1afd48086bd.png)
![image](https://cloud.githubusercontent.com/assets/25783698/24027105/1907b8ba-0b00-11e7-9b73-1a10405123ca.png)
![image](https://cloud.githubusercontent.com/assets/25783698/24027172/863b9a46-0b00-11e7-9246-315886361869.png)
![image](https://cloud.githubusercontent.com/assets/25783698/24027175/8f7f3522-0b00-11e7-95e2-7c5b96d0faa8.png)

Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by baslr** [comment] 2017-03-17 17:01
@hellomanjack can you update to the latest 3.1.x release? There are several cluster bugfixes between latest 3.1.x and 3.1.3.

**Comment by hellomanjack** [comment] 2017-03-20 02:06
@baslr thanks. I update the arangodb to the 3.1.14 now . Some bugs have been fixed. A question remains: what is the user and password for default for the web site:192.168.1.196/service/arangodb3/_db/system/admin/aardvark/index.html ?
And I am sure it is not root:null .

**Comment by m0ppers** [comment] 2017-03-20 13:00
the user is root and no password.

the problem is (and this is why it is not offered as a UI option) that our frontend will authenticate with the backend using the standard "Authentication" header. However this header is being filtered out by the dc/os reverse proxy. So ArangoDB will simply report back "Login failed".

The workaround for this is to dig a tunnel using sshuttle like so:

`sshuttle --python /opt/mesosphere/bin/python -r core@DCOS_IP INTERNAL_NETWORK/INTERNAL_NETMASK`

**Comment by hellomanjack** [comment] 2017-03-21 09:48
@m0ppers thanks for you suggestion.I will try it later.

**Comment by m0ppers** [comment] 2017-03-29 14:25
did this work for you? can we close this issue?

**Closed** 2017-04-05 09:48 UTC
Labels: 3 Cluster
