### ISSUE TITLE
Getting sub-graph result in ArangoDb

### ISSUE THREAD

**Issue by mohamadHassanHijab** [arangodb/arangodb#4981] opened 2018-03-28 08:30 UTC
I'm using ArangoDB of the respective release series: 3.1

Mode: Single-Server

On this operating system: Windows, version: 10

Kindly ask to know how to get a sub-graph result for a query in ArangoDb?

For example: If I have students nodes linked to a university node by (studyAt) edge and I need to see only the students that have ages > 21, so I need to see a sub-graph that contain only these students linked to the university node.

**Comment by dothebart** [comment] 2018-03-28 08:40
Hi, 
you can chain graph traversers in a similar way as [you can chain regular `FOR` loops for doing joins](https://docs.arangodb.com/3.3/AQL/Examples/Join.html); or you can collect the subsequent start vertices and run the traverser in a sub-query like this: https://docs.arangodb.com/3.3/AQL/Examples/CombiningQueries.html

**Comment by sleto-it** [comment] 2018-03-28 08:47
closing as duplicate of https://stackoverflow.com/questions/49529625/getting-sub-graph-result-in-arangodb

**Closed by sleto-it** 2018-03-28 08:47 UTC
Labels: 1 Question, 3 AQL, 3 Graph
