### ISSUE TITLE
AQL bind parameters not shown on edited query

### ISSUE THREAD

**Issue by davidmw** [arangodb/arangodb#4223] opened 2018-01-04 06:10 UTC
## my environment running ArangoDB
3.3.1
- [ ] Single-Server
- [ ] mmfiles
  - [ ] AWS
  - [ ] Ubuntu .deb

### this is an AQL-related issue:
I'm issuing AQL via:
- [ ] web interface with this browser:  Safari 11.0.2   running on this OS: OSX

*******

My saved query starts like this with three parameters defined.

`LET startDoc = DOCUMENT( @baseJobID )

LET outBoundDocArray = (FOR v IN 1..6 OUTBOUND startDoc moreSpecific OPTIONS {bfs: true} 
    SORT v._id
    RETURN v._id
)
    
LET thinnedJobArray = REMOVE_VALUES(outBoundDocArray, @excludeJobsArray)
LET jobArrayCount = LENGTH(thinnedJobArray)
LET shuffledJobArray = BECOME::ARRAY::SHUFFLEARRAY(thinnedJobArray)
LET maxChunkSize = @chunkSize > jobArrayCount ? jobArrayCount : @chunkSize
....`

When I need to edit this query I'll double click on the query name from the editor's Query listbox. The results will be different if I repeatedly open the query for editing in the WebUI editor.  This is an example sequence:

- First edit attempt: Only one parameter is shown in the right hand panel. It is impossible to run the query correctly due to missing parameters.
- Return to query listbox and double click on the query again. Query is loaded into the editor with all three parameters shown on the right hand panel and it is possible to run the query successfully.
- Return to the query listbox and double click on the query again. Only two parameters are shown on the right hand panel.

The exact sequence and number of parameters that display seems completely random.  I'm forced to reload the query in the editor multiple times until all my parameters appear - then I can start a successful edit and test cycle.

Additionally it should be noted that the editor seems to occasionally use hidden cached bind parameter values from previous executions of the query, while ignoring values I've entered into the parameter fields.

**Comment by hkernbach** [comment] 2018-01-15 17:41
Potential fix in PR: https://github.com/arangodb/arangodb/pull/4266
Waiting for final review.

**Comment by maxkernbach** [comment] 2018-01-31 11:36
Hi @davidmw,

this issue might have been fixed in the released version 3.3.3. Could you please recheck if the problem still occurs?

Thanks

**Comment by davidmw** [comment] 2018-01-31 20:48
Sorry, no.  Installed bottled 3.3.3 on the Mac to test.  

It does behave differently.  Repeatedly opening the query into the editor now seems to show exactly the same incomplete list of parameters.  Once I put cursor into one of the missing parameters in the code and edit the name all the parameters then pop into the right hand panel.

<img width="1372" alt="screen shot 2018-02-01 at 8 43 55 am" src="https://user-images.githubusercontent.com/3413901/35646613-369a05d0-072c-11e8-93f7-0f1a6e5c3184.png">
<img width="1370" alt="screen shot 2018-02-01 at 8 46 29 am" src="https://user-images.githubusercontent.com/3413901/35646614-36ff4f4e-072c-11e8-954d-1aa69002972d.png">

**Comment by vinaypyati** [comment] 2018-02-09 13:54
Hi @hkernbach,

Tested the issue with 3.3.3. The issue still exists and parameters on the right disappear _randomly_. 

The issue is reproducible by repeated selection of the saved query, editing of the parameters [focus on any parameter's edit label] and reopen from the saved queries. 

![image](https://user-images.githubusercontent.com/34657484/36030454-9edc51f8-0da7-11e8-9a86-d48da225da83.png)

**Comment by vinaypyati** [comment] 2018-07-20 11:55
Hi @davidmw,

I could not reproduce this issue on the latest released version 3.3.12.  Could you please check if this problem still exists on your side? Looking forward to your feedback.

Thanks

**Comment by vinaypyati** [comment] 2018-07-25 09:37
I am going ahead and closing this ticket as this issue is no longer reproduced on Linux too. Please feel free to reopen if the issue still persists or you have any further questions. Thanks.

**Closed by vinaypyati** 2018-07-25 09:37 UTC
Labels: 1 Bug, 2 Fixed, 3 AQL, 3 UI

**Comment by davidmw** [comment] 2018-07-26 04:15
Confirmed - looks like a good fix on 3.3.12
