### ISSUE TITLE
Docker Cluster with ENV Parameter ARANGO_ROOT_PASSWORD

### ISSUE THREAD

**Issue by phal0r** [arangodb/arangodb#2538] opened 2017-06-09 11:13 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [x] authentication is enabled?
- [x] using the cluster?
- [x] _system database?

## Description

Starting a cluster via docker-compose file consisting of 2 db servers, 2 coordinators and 5 agencies. All of these containers have ARANGO_ROOT_PASSWORD with the same value as env param configured. The cluster is starting successfully, but it is not possible to login with root and the set password. Are you aware of this problem or should I provide more information. There is nothing special in this setup (at least in my opinion :) )

We cannot use the arangodb starter repo as the containers need to be managed via rancher (our favourite container orchestration tool).

**Comment by phal0r** [comment] 2017-06-13 09:54
Here is the docker compose file:

```
Sure, here we go: 

```
arangodb-coordinator1:
  image: arangodb/arangodb:3.1.19
  environment:
    - ARANGO_ROOT_PASSWORD=${ARANGODB_PASSWORD}
  command: >
    --server.endpoint tcp://0.0.0.0:8529
    --server.authentication true
    --server.authentication-system-only false
    --server.jwt-secret ${ARANGO_JWT_SECRET}
    --server.statistics true
    --foxx.queues true
    --cluster.agency-endpoint tcp://arangodb-agency1:8530
    --cluster.agency-endpoint tcp://arangodb-agency2:8530
    --cluster.agency-endpoint tcp://arangodb-agency3:8530
    --cluster.agency-endpoint tcp://arangodb-agency4:8530
    --cluster.agency-endpoint tcp://arangodb-agency5:8530
    --cluster.my-address tcp://arangodb-coordinator1:8529
    --cluster.my-local-info COORD1
    --cluster.my-role COORDINATOR
    --log.level info
    
    
arangodb-agency1:
  image: arangodb/arangodb:3.1.19
  environment:
    - ARANGO_ROOT_PASSWORD=${ARANGODB_PASSWORD}
  command: >
    --server.endpoint tcp://0.0.0.0:8530
    --server.jwt-secret ${ARANGO_JWT_SECRET}
    --server.authentication true
    --server.authentication-system-only false
    --server.statistics false
    --foxx.queues false
    --agency.size 5
    --agency.supervision true
    --agency.activate true
    --agency.my-address tcp://arangodb-agency1:8530
    --log.level info
    --agency.endpoint tcp://arangodb-agency1:8530
    --agency.endpoint tcp://arangodb-agency2:8530
    --agency.endpoint tcp://arangodb-agency3:8530
    --agency.endpoint tcp://arangodb-agency4:8530
    --agency.endpoint tcp://arangodb-agency5:8530
 
 
arangodb-agency2:
  image: arangodb/arangodb:3.1.19
  environment:
    - ARANGO_ROOT_PASSWORD=${ARANGODB_PASSWORD}
  command: >
    --server.endpoint tcp://0.0.0.0:8530
    --server.jwt-secret ${ARANGO_JWT_SECRET}
    --server.authentication true
    --server.authentication-system-only false
    --server.statistics false
    --foxx.queues false
    --agency.size 5
    --agency.supervision true
    --agency.activate true
    --agency.my-address tcp://arangodb-agency2:8530
    --log.level info
    --agency.endpoint tcp://arangodb-agency1:8530
    --agency.endpoint tcp://arangodb-agency2:8530
    --agency.endpoint tcp://arangodb-agency3:8530
    --agency.endpoint tcp://arangodb-agency4:8530
    --agency.endpoint tcp://arangodb-agency5:8530
 
arangodb-agency3:
  image: arangodb/arangodb:3.1.19
  environment:
    - ARANGO_ROOT_PASSWORD=${ARANGODB_PASSWORD}
  command: >
    --server.endpoint tcp://0.0.0.0:8530
    --server.jwt-secret ${ARANGO_JWT_SECRET}
    --server.authentication true
    --server.authentication-system-only false
    --server.statistics false
    --foxx.queues false
    --agency.size 5
    --agency.supervision true
    --agency.activate true
    --agency.my-address tcp://arangodb-agency3:8530
    --log.level info
    --agency.endpoint tcp://arangodb-agency1:8530
    --agency.endpoint tcp://arangodb-agency2:8530
    --agency.endpoint tcp://arangodb-agency3:8530
    --agency.endpoint tcp://arangodb-agency4:8530
    --agency.endpoint tcp://arangodb-agency5:8530
    

arangodb-dbserver1:
  image: arangodb/arangodb:3.1.19
  environment:
    - ARANGO_ROOT_PASSWORD=${ARANGODB_PASSWORD}
  command: >
    --server.endpoint tcp://0.0.0.0:8529
    --server.authentication true
    --server.authentication-system-only false
    --server.jwt-secret ${ARANGO_JWT_SECRET}
    --server.statistics true
    --foxx.queues false
    --cluster.agency-endpoint tcp://arangodb-agency1:8530
    --cluster.agency-endpoint tcp://arangodb-agency2:8530
    --cluster.agency-endpoint tcp://arangodb-agency3:8530
    --cluster.agency-endpoint tcp://arangodb-agency4:8530
    --cluster.agency-endpoint tcp://arangodb-agency5:8530
    --cluster.my-address tcp://arangodb-dbserver1:8529
    --cluster.my-local-info DB1
    --cluster.my-role PRIMARY
    --log.level info
    

#ARANGO GROUP 2
arangodb-coordinator2:
  image: arangodb/arangodb:3.1.19
  environment:
    - ARANGO_ROOT_PASSWORD=${ARANGODB_PASSWORD}
  command: >
    --cluster.agency-endpoint tcp://arangodb-agency1:8530
    --cluster.agency-endpoint tcp://arangodb-agency2:8530
    --cluster.agency-endpoint tcp://arangodb-agency3:8530
    --cluster.agency-endpoint tcp://arangodb-agency4:8530
    --cluster.agency-endpoint tcp://arangodb-agency5:8530
    --cluster.my-address tcp://arangodb-coordinator2:8529
    --server.endpoint tcp://0.0.0.0:8529
    --server.jwt-secret ${ARANGO_JWT_SECRET}
    --server.authentication true
    --server.authentication-system-only false
    --server.statistics true
    --foxx.queues true
    --cluster.my-local-info COORD2
    --cluster.my-role COORDINATOR
    --log.level info
    
    
arangodb-agency4:
  image: arangodb/arangodb:3.1.19
  environment:
    - ARANGO_ROOT_PASSWORD=${ARANGODB_PASSWORD}
  command: >
    --server.jwt-secret ${ARANGO_JWT_SECRET}
    --server.authentication true
    --server.authentication-system-only false
    --server.statistics false
    --server.endpoint tcp://0.0.0.0:8530
    --foxx.queues false
    --agency.size 5
    --agency.supervision true
    --agency.activate true
    --agency.my-address tcp://arangodb-agency4:8530
    --log.level info
    --agency.endpoint tcp://arangodb-agency1:8530
    --agency.endpoint tcp://arangodb-agency2:8530
    --agency.endpoint tcp://arangodb-agency3:8530
    --agency.endpoint tcp://arangodb-agency4:8530
    --agency.endpoint tcp://arangodb-agency5:8530

arangodb-agency5:
  image: arangodb/arangodb:3.1.19
  environment:
    - ARANGO_ROOT_PASSWORD=${ARANGODB_PASSWORD}
  command: >
    --server.jwt-secret ${ARANGO_JWT_SECRET}
    --server.authentication true
    --server.authentication-system-only false
    --server.statistics false
    --foxx.queues false
    --agency.size 5
    --agency.supervision true
    --agency.activate true
    --agency.my-address tcp://arangodb-agency5:8530
    --server.endpoint tcp://0.0.0.0:8530
    --log.level info
    --agency.endpoint tcp://arangodb-agency1:8530
    --agency.endpoint tcp://arangodb-agency2:8530
    --agency.endpoint tcp://arangodb-agency3:8530
    --agency.endpoint tcp://arangodb-agency4:8530
    --agency.endpoint tcp://arangodb-agency5:8530

arangodb-dbserver2:
  image: arangodb/arangodb:3.1.19
  environment:
    - ARANGO_ROOT_PASSWORD=${ARANGODB_PASSWORD}
  command: >
    --cluster.agency-endpoint tcp://arangodb-agency1:8530
    --cluster.agency-endpoint tcp://arangodb-agency2:8530
    --cluster.agency-endpoint tcp://arangodb-agency3:8530
    --cluster.agency-endpoint tcp://arangodb-agency4:8530
    --cluster.agency-endpoint tcp://arangodb-agency5:8530
    --cluster.my-address tcp://arangodb-dbserver2:8529
    --server.endpoint tcp://0.0.0.0:8529
    --server.jwt-secret ${ARANGO_JWT_SECRET}
    --server.authentication true
    --server.authentication-system-only false
    --server.statistics true
    --foxx.queues false
    --cluster.my-local-info HAVDB1
    --cluster.my-role PRIMARY
    --log.level info
```

**Comment by phal0r** [comment] 2017-06-13 09:55
This setup is working. Just switching all images to 3.1.20 and 3.1.21 lets the agencies not find each other in the same environment

**Comment by kvahed** [comment] 2017-06-26 07:40
Would you please share with me the `docker log` of the containers, please.

**Comment by phal0r** [comment] 2017-07-03 22:21
@kvahed 
Yes, i need to set it up again and post the log

**Comment by dothebart** [comment] 2017-07-17 15:18
Can you try to wipe all docker processes and images in conjunction with arangodb and retry? since this worked on #2712

**Comment by phal0r** [comment] 2017-07-25 22:26
Hey @dothebart,

my company is switching the test environment to another provider, that's why I can't get back to you right now  and give feedback.

**Comment by dothebart** [comment] 2017-08-22 14:06
@phal0r have you been able to reproduce this meanwhile? or could we close this?

**Comment by phal0r** [comment] 2017-08-22 21:00
Hi @dothebart,

I checked this setup today with version 3.1.26 and it is still the same problem. The cluster spins up successfully, but i cannot login with the password passed in via env. Everything is fresh. No volume mounts, so no data can be reused.

@kvahed 
Which log do you want to see? Here is the log of the coordinators:

```

22.8.2017 22:51:00Initializing root user...Hang on...
22.8.2017 22:51:47Initializing database...Hang on...
22.8.2017 22:52:22Database initialized...Starting System...
22.8.2017 22:52:222017-08-22T20:52:22Z [1] INFO ArangoDB 3.1.26 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.1t  3 May 2016
22.8.2017 22:52:222017-08-22T20:52:22Z [1] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
22.8.2017 22:52:222017-08-22T20:52:22Z [1] INFO Starting up with role COORDINATOR
22.8.2017 22:52:292017-08-22T20:52:29Z [1] INFO {agency} ["arango/Target/MapLocalToID/COORD1"]
22.8.2017 22:52:292017-08-22T20:52:29Z [1] INFO {cluster} Fresh start. Persisting new UUID CRDN-1e348898-c8a9-4250-9fe6-7b2375bb4841
22.8.2017 22:52:292017-08-22T20:52:29Z [1] INFO Waiting for DBservers to show up...
22.8.2017 22:52:302017-08-22T20:52:30Z [1] INFO Waiting for DBservers to show up...
22.8.2017 22:52:312017-08-22T20:52:31Z [1] INFO Waiting for DBservers to show up...
22.8.2017 22:52:312017-08-22T20:52:31Z [1] INFO Found 2 DBservers.
22.8.2017 22:52:312017-08-22T20:52:31Z [1] INFO Authentication is turned on
22.8.2017 22:52:312017-08-22T20:52:31Z [1] INFO Authentication for unix sockets is turned on
22.8.2017 22:52:312017-08-22T20:52:31Z [1] INFO file-descriptors (nofiles) hard limit is 1048576, soft limit is 524288
22.8.2017 22:52:332017-08-22T20:52:33Z [1] INFO JavaScript using startup '/usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
22.8.2017 22:52:402017-08-22T20:52:40Z [1] INFO Cluster feature is turned on. Agency version: {"server":"arango","version":"3.1.26","license":"community"}, Agency endpoints: http+tcp://arangodb-agency5:8530, http+tcp://arangodb-agency1:8530, http+tcp://arangodb-agency2:8530, http+tcp://arangodb-agency3:8530, http+tcp://arangodb-agency4:8530, server id: 'CRDN-1e348898-c8a9-4250-9fe6-7b2375bb4841', internal address: tcp://arangodb-coordinator1:8529, role: COORDINATOR
22.8.2017 22:52:412017-08-22T20:52:40Z [1] INFO using heartbeat interval value '1000 ms' from agency
22.8.2017 22:52:412017-08-22T20:52:41Z [1] INFO using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
22.8.2017 22:52:462017-08-22T20:52:46Z [1] INFO Waiting for initial replication of system collections...
22.8.2017 22:52:582017-08-22T20:52:58Z [1] INFO bootstrapped coordinator CRDN-1e348898-c8a9-4250-9fe6-7b2375bb4841
22.8.2017 22:52:582017-08-22T20:52:58Z [1] INFO ArangoDB (version 3.1.26 [linux]) is ready for business. Have fun!
```
```

22.8.2017 22:50:28Initializing root user...Hang on...
22.8.2017 22:51:12Initializing database...Hang on...
22.8.2017 22:52:11Database initialized...Starting System...
22.8.2017 22:52:112017-08-22T20:52:11Z [1] INFO ArangoDB 3.1.26 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.1t  3 May 2016
22.8.2017 22:52:112017-08-22T20:52:11Z [1] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
22.8.2017 22:52:112017-08-22T20:52:11Z [1] INFO Starting up with role COORDINATOR
22.8.2017 22:52:292017-08-22T20:52:29Z [1] INFO {agency} ["arango/Target/MapLocalToID/COORD2"]
22.8.2017 22:52:292017-08-22T20:52:29Z [1] INFO {cluster} Fresh start. Persisting new UUID CRDN-f793c924-d1cc-4825-9cbc-c750530335ce
22.8.2017 22:52:292017-08-22T20:52:29Z [1] INFO Waiting for DBservers to show up...
22.8.2017 22:52:302017-08-22T20:52:30Z [1] INFO Waiting for DBservers to show up...
22.8.2017 22:52:312017-08-22T20:52:31Z [1] INFO Waiting for DBservers to show up...
22.8.2017 22:52:312017-08-22T20:52:31Z [1] INFO Found 2 DBservers.
22.8.2017 22:52:312017-08-22T20:52:31Z [1] INFO Authentication is turned on
22.8.2017 22:52:312017-08-22T20:52:31Z [1] INFO Authentication for unix sockets is turned on
22.8.2017 22:52:312017-08-22T20:52:31Z [1] INFO file-descriptors (nofiles) hard limit is 1048576, soft limit is 524288
22.8.2017 22:52:332017-08-22T20:52:33Z [1] INFO JavaScript using startup '/usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
22.8.2017 22:52:412017-08-22T20:52:41Z [1] INFO Cluster feature is turned on. Agency version: {"server":"arango","version":"3.1.26","license":"community"}, Agency endpoints: http+tcp://arangodb-agency5:8530, http+tcp://arangodb-agency1:8530, http+tcp://arangodb-agency2:8530, http+tcp://arangodb-agency3:8530, http+tcp://arangodb-agency4:8530, server id: 'CRDN-f793c924-d1cc-4825-9cbc-c750530335ce', internal address: tcp://arangodb-coordinator2:8529, role: COORDINATOR
22.8.2017 22:52:412017-08-22T20:52:41Z [1] INFO using heartbeat interval value '1000 ms' from agency
22.8.2017 22:52:422017-08-22T20:52:42Z [1] INFO using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
22.8.2017 22:52:462017-08-22T20:52:46Z [1] INFO Waiting for initial replication of system collections...
22.8.2017 22:52:592017-08-22T20:52:59Z [1] INFO bootstrapped coordinator CRDN-f793c924-d1cc-4825-9cbc-c750530335ce
22.8.2017 22:52:592017-08-22T20:52:59Z [1] INFO ArangoDB (version 3.1.26 [linux]) is ready for business. Have fun!
```

I configured for alle containers test as ARANGO_ROOT_PASSWORD to keep it simple, but the ui just says "login failed".

**Comment by phal0r** [comment] 2017-08-22 21:13
![image](https://user-images.githubusercontent.com/3658211/29587743-294ab130-878f-11e7-8860-e1146e8d0af3.png)

This is a screenshot of the xhr for authentication. There are 2 strange things:
- a bearer token with a value of null is passed
- contentType ist sent as "application/x-www-form-urlencoded", but the content is obviously application/json

**Comment by phal0r** [comment] 2017-08-22 21:21
![image](https://user-images.githubusercontent.com/3658211/29588086-76ececcc-8790-11e7-82e8-01b5e8550f22.png)

I connected to the coordinator container to confirm, that the env param is set properly.

**Comment by phal0r** [comment] 2017-08-22 21:40
I also checked 3.2.1 with the same result.

I used a http client to create a request without the above mentioned issues:
- no Authorization header
- contentType application/json

Same result. Authentication failed.

**Comment by phal0r** [comment] 2017-09-12 07:29
Checked again wit 3.2.3 and never tried before to login without a password, but it works. This is definitely not the intended behaviour imho.

In this scenario, it seems ARANGO_ROOT_PASSWORD is not used and root is created without any password at all.

**Comment by kvahed** [comment] 2017-10-06 13:41
The docker containers' `ARANGO_ROOT_PASSWORD` is not meant to be a cluster-wide password. As a matter of fact it is technically impossible to create a such cluster-wide users on basis of container startup parameters. Once the cluster is up and running one may log in to the password-less root account on any coordinator and set it's password as desired.

**Closed by kvahed** 2017-10-06 13:41 UTC
Labels: 1 Question, 3 Cluster

**Comment by B0BAI** [comment] 2021-08-14 12:17
> The docker containers' `ARANGO_ROOT_PASSWORD` is not meant to be a cluster-wide password. As a matter of fact it is technically impossible to create a such cluster-wide users on basis of container startup parameters. Once the cluster is up and running one may log in to the password-less root account on any coordinator and set it's password as desired.

Very helpful. I spent hours trying to fix it with zero luck.
