### ISSUE TITLE
Export of Collection via ArangoDB 3.03 Web Interface Results in 401 Error

### ISSUE THREAD

**Issue by sbaugher** [arangodb/arangodb#1968] opened 2016-07-27 16:16 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [X ] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [X ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser: Chrome or Firefox (latest stable) running on this OS: Linux Mint 17
- [X ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as root user
3) use database [X ] `_system` [ X] other: 
4) Open any collection.
5) Use the "Download documents as JSON file" button in upper right.
...

The following problem occurs: A new browser tab is popped with the following JSON:

{"error":true,"errorNum":401,"errorMessage":"Unauthorized","code":401}

Instead I would be expecting: 

The JSON file containing the data in the collection I attempted to export.

**Comment by jsteemann** [comment] 2016-07-28 07:06
Confirmed to not work (i.e. throws "401 unauthorized" error) in current 3.0.

In devel, there is no such error, but the download does not start either. The browser calls the following URL via HTTP GET "/_admin/aardvark/query/result/download/eyJxdWVyeSI6IkZPUiB4IGluIEBAY29sbGVjdGlvbiBSRVRVUk4geCIsImJpbmRWYXJzIjp7IkBjb2xsZWN0aW9uIjoiZSJ9fQ==", but nothing happens (in Firefox 47.0).

**Comment by hkernbach** [comment] 2016-07-28 14:13
The unauthorized bug is fixed since a few days in both branches. Chrome is fine, Firefox is broken. Will investigate.

**Comment by jsteemann** [comment] 2016-07-28 14:39
> The unauthorized bug is fixed since a few days in both branches. Chrome is fine, Firefox is broken.

Just to clarify: Firefox 47.0 still says "Unauthorized" in current 3.0 (7c557ff244918302a0d9e535f51969bc12da10d7) as I reported [here](https://github.com/arangodb/arangodb/issues/1968#issuecomment-235816455)

**Comment by hkernbach** [comment] 2016-07-28 14:55
The firefox download issue is now fixed. 
@jsteemann : We do not push a new grunt build for every bugfix. This is part of the deployment process. This could be the reason why your instance still throws unauthorized.

**Closed by hkernbach** 2016-07-28 14:55 UTC
Labels: 1_Bug, front-end

**Comment by jsteemann** [comment] 2016-07-28 15:13
@hkernbach : confirmed to work after grunt-ing the web interface files.
I'll write a comment about the fix into the changelog as it is missing there.

**Comment by hkernbach** [comment] 2016-07-28 15:14
Thank you. I'll try to remember next time.
