### ISSUE TITLE
USER root page route becomes #user/undefined when Gravatar email is set in Dashboard

### ISSUE THREAD

**Issue by monotykamary** [arangodb/arangodb#9181] opened 2019-06-03 22:46 UTC
## My Environment

* __ArangoDB Version__:        3.4.6
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server, Single Server
* __Deployment Strategy__:   Manual Start, Kubernetes
* __Configuration__:               N/A
* __Infrastructure__:               localhost and DigitalOcean
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        24GB, 8GB
* __Disks in use__:       HDD, SSD
* __Used Package__:              Ubuntu deb

## Component, Query & Data

__Affected feature__:
Accessing root user page in ArangoDB Dashboard returns route #user/undefined when any gravatar email is set.

## Steps to reproduce

1. Upgrade to version 3.4.6
2. Open ArangoDB dashboard
3. Click on USERS tab in the navigation bar -> root user
5. Set gravatar email
6. Click on USERS tab -> root user

__Problem__:
USERS page for root is not called or returned correctly when the gravatar email is set; returns full route /_db/_system/_admin/aardvark/index.html#user/undefined

![image](https://user-images.githubusercontent.com/1130103/58839280-73082300-868b-11e9-96b3-96348ef296e6.png)

__Expected result__:
Full route should return /_db/_system/_admin/aardvark/index.html#user/root

**Comment by OmarAyo** [comment] 2019-06-04 00:12
Hi @monotykamary 

Thanks for reporting this issue, I was able to reproduce it locally. Will label this ticket as a bug 

Best,

**Comment by maxkernbach** [comment] 2019-07-08 15:55
Hi @monotykamary,

I am closing this issue since version 3.4.7, which includes a fix for this issue, has been released.
In case this problem persists, please comment and we will reopen.

from the [changelog](https://github.com/arangodb/arangodb/blob/75f0a63549772966b28b4738d9930064c7e9fae9/CHANGELOG#L29):
```
* Fixed editing a user within the web UI if the user added a gravatar profile picture
```

The latest version can be found in the [download section](https://www.arangodb.com/download-major/).

**Closed by maxkernbach** 2019-07-08 15:55 UTC
Labels: 1 Bug, 2 Fixed, 3 UI
