### ISSUE TITLE
AQL error: Overfetch during constrained heap sort

### ISSUE THREAD

**Issue by Darkheir** [arangodb/arangodb#11475] opened 2020-04-20 15:25 UTC
## My Environment

* __ArangoDB Version__:       3.6.2
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Kubernetes
* __Disks in use__:                 SSD
* __Used Package__:             Docker - official Docker library

## Component, Query & Data

__Affected feature__:
AQL Query

__AQL query (if applicable)__:

```
FOR item IN objects_search_view
    SEARCH (
        item.active == true
        AND ANALYZER(item.description IN TOKENS(@tokenize_description, 'text_en'), 'text_en')
    )
    SORT TFIDF(item) DESC
    LIMIT 0, 10 RETURN item
```

__AQL explain (if applicable)__:

```
Query String (233 chars, cacheable: true):
 FOR item IN objects_search_view
     SEARCH (
         item.active == true
         AND ANALYZER(item.description IN TOKENS(@tokenize_description, 'text_en'), 'text_en')
     )
     SORT TFIDF(item, false) DESC
     LIMIT 0, 10 RETURN item

Execution plan:
 Id   NodeType            Site  Est.   Comment
  1   SingletonNode       DBS      1   * ROOT
  2   EnumerateViewNode   DBS      1     - FOR item IN objects_search_view SEARCH ((item.`active` == true) && ANALYZER((item.`description` in [ "agent", "tesla" ]), "text_en")) LET #3 = TFIDF(item, false)   /* view query with late materialization */
  4   SortNode            DBS      1       - SORT #3 DESC   /* sorting strategy: constrained heap */
 11   MaterializeNode     DBS      1       - MATERIALIZE item
  9   RemoteNode          COOR     1       - REMOTE
 10   GatherNode          COOR     1       - GATHER #3 DESC  /* parallel */
  5   LimitNode           COOR     1       - LIMIT 0, 10
  6   ReturnNode          COOR     1       - RETURN item

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   handle-arangosearch-views
  2   remove-unnecessary-calculations-2
  3   scatter-arangosearch-view-in-cluster
  4   distribute-sort-to-cluster
  5   remove-unnecessary-remote-scatter
  6   sort-limit
  7   parallelize-gather
  8   late-document-materialization-arangosearch
```

## Steps to reproduce

1. Run query above
2. Error

__Problem__:

The following error appears: 

`Overfetch during constrained heap sort. Please report this error! Try turning off the sort-limit optimizer rule to get your query working. (while executing`

__Expected result__: The query should executes and returns without any error.

__Note__: Removing the `SORT TFIDF(item) DESC` make the query work. Same with a "classic" sort like `SORT item._key DESC`

**Comment by maxkernbach** [comment] 2020-04-24 08:48
Hi @Darkheir,

As the error suggests, could you try to manually [turn off the **sort-limit** optimizer rule](https://www.arangodb.com/docs/stable/aql/execution-and-performance-optimizer.html#turning-specific-optimizer-rules-off) and check if the query works?

This query with disabled **sort-limit** can be profiled via arangosh as follows:

```
db._profileQuery(`FOR item IN objects_search_view
    SEARCH (
        item.active == true
        AND ANALYZER(item.description IN TOKENS(@tokenize_description, 'text_en'), 'text_en')
    )
    SORT TFIDF(item) DESC
    LIMIT 0, 10 RETURN item`, {'tokenize_description': 'INSERTBINDVALUE'}, {optimizer:{rules:["-sort-limit"]}} );
```

Please make sure to replace `{'tokenize_description': 'INSERTBINDVALUE'}` with the correct bind parameter value for **tokenize_description**.

**Comment by Darkheir** [comment] 2020-04-24 11:44
Indeed disabling the rule works, but it doesn't explain the issue nor fix it!

**Comment by maxkernbach** [comment] 2020-04-24 11:48
That is true, I just wanted to make sure that this rule is causing the error. Would it be possible to share a dump, that includes all involved collections?

You can send us a message to hackers@arangodb.com (this ML is not public) and attach the dump in that email. This way we can try to reproduce and find the root cause. Please reference the number of this issue in your email.

**Comment by Darkheir** [comment] 2020-04-24 12:08
I will try to reproduce it in a smaller dataset because the current one take too much space to be shared.

**Comment by Darkheir** [comment] 2020-05-05 09:43
Recreating the view fixes the error for some time until some documents are in a "dirty" state and the error appears again.

After some tests this issue seems related to a "docs out of order" error we had for quite some time on our servers. You fixed it in the 3.6.3 release: https://github.com/arangodb/arangodb/pull/11452

We will try to upgrade our servers and see if we get this "Overfetch during constrained heap sort" error again.

**Comment by maxkernbach** [comment] 2020-05-20 10:11
Hi @Darkheir,

Thanks for the update.
Did you already have a chance to upgrade and check whether it fixes the issue?

**Comment by Darkheir** [comment] 2020-05-20 10:57
We deployed on test and it seems good.

**Comment by maxkernbach** [comment] 2020-05-20 11:09
This is good news, therefore I am closing the issue for now.

In case the reported error reoccurs, please comment.

**Closed by maxkernbach** 2020-05-20 11:09 UTC
Labels: 1 Analyzing, 3 AQL, 3 ArangoSearch, 3 Optimizer, Waiting User Reply
