### ISSUE TITLE
[ERR 1478] could not determine number of documents in collection (while optimizing plan)

### ISSUE THREAD

**Issue by jeeveeyes** [arangodb/arangodb#3020] opened 2017-08-10 16:56 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [X] 3.1
- [ ] 3.2
- [ ] self-compiled devel branch

Mode:
- [X] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [X] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [X] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[X] I'm using graph features

I'm issuing AQL via:
- [X] web interface with this browser:  Chrome   running on this OS:
- [ ] arangosh
- [X] this Driver: python-arango 3.8.0

===

I am using ArangoDB 3.1.21 in 3 Node cluster environment. Each node is a Ubuntu 14.04 VM with 64 GB RAM. The cluster was started using the Arango starter tool 0.8.0 with all nodes as co-ordinators and DB Servers. All our arango access is from Python via the python-arango (https://github.com/joowani/python-arango) v 3.8.0 client library.
As part of our HA testing, when one node was brought down, we are observing the below error from Arango :

Connecting to ArangoDB at : http://10.102.93.215:8529
Initialized DB reference..
Traceback (most recent call last):
  File "adb_simple_query.py", line 39, in <module>
    if not GRAPH_NAME in [g["name"] for g in db.graphs()]:
  File "/Users/sriraamg/venvs/MYPY/lib/python2.7/site-packages/arango/database.py", line 703, in graphs
    raise GraphListError(res)
arango.exceptions.GraphListError: [HTTP 503][ERR 1478] could not determine number of documents in collection (while optimizing plan)

* All other cluster settings are the default and no tuning of the cluster was done.
* The error was reproduceable multiple times by downing different nodes each time.

Occasionally in the 1 of 3 nodes down scenario , we also see this error : VertexCollectionListError: [HTTP 400][ERR 1457] timeout in cluster operation

Any pointers on how to overcome the above error ?
Attaching the generic client program to reproduce this error.

**Comment by jeeveeyes** [comment] 2017-08-10 16:57
`
# Sample code to create some items in ArangoDB

# Client library used is python-arango lib
# https://github.com/joowani/python-arango
import arango
import time
import json

DB_HOST = "10.102.93.224"
DB_NAME = "simple-graph-db"
GRAPH_NAME = "simple-graph"
UID = "root"
PWD = "passw0rd"
DB_URL = "http://"+DB_HOST+":8529"

# Initialize the client for ArangoDB
client = arango.ArangoClient(
    protocol="http",
    host=DB_HOST,
    port=8529,
    username=UID,
    password=PWD,
    enable_logging=True
)

print "Connecting to ArangoDB at : {}".format(DB_URL)

if not DB_NAME in client.databases():
    db = client.create_database(DB_NAME)
else:
    db = client.database(DB_NAME)

assert db.name == DB_NAME
print "Initialized DB reference.."


if not GRAPH_NAME in [g["name"] for g in db.graphs()]:
    grph = db.create_graph(GRAPH_NAME)
else:
    grph = db.graph(GRAPH_NAME)

assert grph.name == GRAPH_NAME
print "Initialized graph reference.."


# Setup vertex collections
coll_names = ["Coll1","Coll2","Coll3","Coll4","Coll5"]
coll_objs = {}
coll_docs = {}
for coll_name in coll_names:

    if coll_name in grph.vertex_collections():
        coll = grph.vertex_collection(coll_name)
    else:
        coll = grph.create_vertex_collection(coll_name)
    coll_objs[coll_name] = coll
    coll_docs[coll_name] = {}
    print "Initialized collection {}...".format(coll_name)


# Populate some data
for coll_name in coll_names:
    print "Inserting into {}".format(coll_name)
    for i in range(2):
        doc_name = "doc%d"%(i,)
        doc = coll_objs[coll_name].insert({"name" : doc_name, "timestamp" : 0})
        coll_docs[coll_name][doc_name] = doc


# Execute AQL
for coll_name in coll_names:

    print "Querying {}".format(coll_name)
    qry = "FOR doc IN {} RETURN doc".format(coll_name)
    results = db.aql.execute(qry)

    for doc in results:
        print json.dumps(doc,indent=4)
        doc["timestamp"] = int(time.time())
        coll_objs[coll_name].update(doc)


print "Finding a doc ..."
cursr = coll_objs["Coll1"].find({"name":"doc1"})
while True:
  try:
      doc = cursr.next()
      print "Doc {} timestamp {}".format(doc["name"],doc["timestamp"])

      #print "Deleting found doc..."
      #coll_objs["Coll1"].delete({"name":"doc1"})
  except:
      break


# Setup edges

edge_data = [("Coll1","Coll2"),
             ("Coll2","Coll3"),
             ("Coll3","Coll4")]

edge_colls = {}
for from_coll,to_coll in edge_data:
    name = from_coll + "_ref_" + to_coll
    edge_colls[name] = grph.create_edge_definition(name=name,                                                                               from_collections = [from_coll],
                                                  to_collections = [to_coll])

def add_edge(from_coll_name,from_doc_name,to_coll_name,to_doc_name,info={}):
    edge_coll = edge_colls[from_coll_name + "_ref_" + to_coll_name]
    final_info = {"_from" : coll_docs[from_coll_name][from_doc_name]["_id"],
                  "_to" : coll_docs[to_coll_name][to_doc_name]["_id"]}
    final_info.update(info)
    return edge_coll.insert(final_info)


print "Adding edges..."

print add_edge("Coll1","doc0","Coll2","doc0",{"lhs":"rhs"})
print add_edge("Coll1","doc1","Coll2","doc1",{"lhs":"rhs"})
print add_edge("Coll2","doc0","Coll3","doc0",{"lhs":"rhs"})
print add_edge("Coll2","doc1","Coll3","doc1",{"lhs":"rhs"})

print "Doing graph traversal.."

qry = """
      WITH Coll1,Coll2,Coll3
        FOR d1 IN @@col1
          FOR d2 IN OUTBOUND d1 @@edge_col1
            FOR d3 IN OUTBOUND d2 @@edge_col2
              RETURN d3"""


cursr = db.aql.execute(qry,bind_vars={
                             "@col1" : "Coll1",
                             "@edge_col1" : "Coll1_ref_Coll2",
                             "@edge_col2" : "Coll2_ref_Coll3"})
while True:
  try:
      vertex = cursr.next()
      print "Key {} Name {}".format(vertex["_key"],vertex["name"])
  except:
      break
`

**Comment by jeeveeyes** [comment] 2017-08-10 17:00
We are seeing the below errors in different points of time in a 1 node down scenario :

**Comment by fceller** [comment] 2017-08-12 20:56
We will try to reproduce this.

**Comment by fceller** [comment] 2017-08-12 20:56
@jeeveeyes would it be possible for you to test 3.2 in the meantime?

**Comment by jeeveeyes** [comment] 2017-08-13 12:22
@fceller , Thanks for responding to this issue. 

I originally posted about this issue on the ArangoDB cluster slack forum and @jsteemann too suggested that we try 3.1.27 and 3.2.0.

**Subsequently we tried both the above versions. Unfortunately we are observing a mix of issues during 1-node-down scenario as listed down **

- Error codes thrown during various DB access operations
     -- [ERR 1478] could not start all traversal engines : timeout in cluster operation (while executing)
    -- [ERR 1478] could not determine number of documents in collection (while optimizing plan)
    -- [ERR 1457] timeout in cluster operation
    -- [ERR 1465] cluster internal HTTP connection broken

-  When we try even a simple AQL query through the query page in the UI ( "FOR doc IN vertcoll RETURN doc" ) , we find that the results are not consistent. It does'nt work for most of the iterations and returns the document few times. For the occasions where it fails, it does not return any useful error message or error code.

- We observe failure in various operations at different times i.e any operation like listing collection, listing graphs, reading documents, filtering documents, updating documents could fail at any time.

- Some collections seem to be crippled i.e when we click on them in the UI , a ping-pong animation wait screen is shown.

- HTTP connections to node A appear frozen when node B or C is brought down. The connection remains open for some time and response is returned only when we bring B or C up again. I.e  clients connected to the nodes NOT brought down are affected or timing out.

- We definitely see some decrease in response times for queries from a cluster vs standalone ArangoDB instance.

- We tried simulating 1 node down using a variety of means and cluster behaviour is same. 
  -- Terminating arango processes ( kill -9 ) 
  -- Graceful shutdown using the stop command to arango starter tool
  -- Powering off the node

- Please point us to documentation which says what might work and not work in a 3 node cluster environment when one of the nodes is down. We are not sure what is expected to work and what is not supported to work.

- However, we did find that cluster replication works fine wherein any create / delete is properly propagated to other node that is up.

**Comment by fceller** [comment] 2017-08-13 12:57
@jeeveeyes thanks for the detailed description. For my understanding because I cannot see it in the python code: Are creating the collections with replication factor 1 or 2 (see synchronous replication in https://docs.arangodb.com/3.2/Manual/Administration/Replication/)

**Comment by jeeveeyes** [comment] 2017-08-13 16:27
@fceller , as can be seen from above Python code , the Vertex collections are created using the graph.create_vertex_collection() API ( https://github.com/joowani/python-arango/blob/master/arango/graph.py ). 

This API  internally calls the Arango gharial HTTP API to create a vertex collection  (https://docs.arangodb.com/devel/HTTP/Gharial/Vertices.html)

i.e the actual call vertex create call is 

POST /_api/gharial/{graph-name}/vertex/{collection-name}

Does above call support replication_factor ? I could not see it documented in the above Vertices.html doc page.

I could only see replicationFactor in the normal _api/collection (https://docs.arangodb.com/devel/HTTP/Collection/Creating.html) API.  I could see that the default is '1' which means NO replication.

Does this default apply to vertex collections too ?

**Comment by jeeveeyes** [comment] 2017-08-14 06:37
I looked at the Gharial HTTP API implementation and could see that a replication factor is accepted while POSTing to create the graph -

https://github.com/arangodb/arangodb/blob/devel/js/apps/system/_api/gharial/APP/gharial.js

```
router.post('/', function (req, res) {
  const waitForSync = Boolean(req.queryParams.waitForSync);
  let g;
  try {
    if (isEnterprise && req.body.isSmart === true) {

	<SNIP>

    } else {
      if (req.body.options && req.body.options.numberOfShards && cluster.isCluster()) {
        const numberOfShards = req.body.options.numberOfShards || 1;
        **const replicationFactor = req.body.options.replicationFactor || 1;**
        g = Graph._create(
          req.body.name,
          req.body.edgeDefinitions,
          req.body.orphanCollections,
          {waitForSync, numberOfShards, replicationFactor}
        );
      } else if (req.body.options && req.body.options.replicationFactor && cluster.isCluster()) {
        const numberOfShards = req.body.options.numberOfShards || 1;
        **const replicationFactor = req.body.options.replicationFactor || 1;**
        g = Graph._create(
          req.body.name,
          req.body.edgeDefinitions,
          req.body.orphanCollections,
          {waitForSync, numberOfShards, replicationFactor}
        );
      } else {
        g = Graph._create(
          req.body.name,
          req.body.edgeDefinitions,
          req.body.orphanCollections,
          {waitForSync}
        );
      }
    }
  } catch (e) {

  <SNIP>

  .summary('Creates a new graph')
  .description('Creates a new graph object');

```

====

However , that replication option parameter is not documented in the man page for the graph creation API -

https://docs.arangodb.com/devel/HTTP/Gharial/Management.html

```
POST /_api/gharial

The creation of a graph requires the name of the graph and a definition of its edges. See also edge definitions.

A JSON object with these properties is required:

    orphanCollections: An array of additional vertex collections.
    edgeDefinitions: An array of definitions for the edge
    name: Name of the graph.
    isSmart: Define if the created graph should be smart. This only has effect in Enterprise version.
    options:
        smartGraphAttribute: The attribute name that is used to smartly shard the vertices of a graph. Every vertex in this Graph has to have this attribute. Cannot be modified later.
        numberOfShards: The number of shards that is used for every collection within this graph. Cannot be modified later.

```

Is something missing here ? 
We should be able to specify the replication factor on a per-vertex-collection level OR globally at the time of creating the graph itself. 
Is the replication factor intentionally undocumented for vertex collections or graphs ?

**Comment by fceller** [comment] 2017-08-14 07:30
I will check check. As a work around: you can create the collection (document and edge) beforehand and specify the replication in the create method.

**Comment by jeeveeyes** [comment] 2017-08-14 10:55
I changed my code to create collections with desired replication factor.
Since we have a 3-node setup , we tried both with replication factor of 2 and 3.
We could see that the UI collection page reflects the number 2 or 3 that we created the collection with.

However, regardless of value 2 or 3 , we still see the below error -

```
[ERR 1478] could not start all traversal engines : could not connect to server (while executing)
```

We tried above test with ArangoDB 3.2.0 and our client was always connecting to node A 8529 port. We tried making node B or node C as down to induce the failure.

**Comment by jeeveeyes** [comment] 2017-08-22 07:16
Hello, are there any updates on this issue ? 

Please let us know if we need to try any other combination of startup parameters , timeouts etc for each node.

**Comment by kunalak** [comment] 2017-11-05 11:50
@jeeveeyes Were you able to try out with the latest version i.e. 3.2.6? Also, can you please share the updated/latest Test code where you have specified the replication factor ? (the 3.2.6 release also fixed _api/gharial to accept cluster options for collection creation)

**Comment by jeeveeyes** [comment] 2017-11-07 17:20
Hi @kunalak ,

As suggested, we tried v3.2.6 with a 3-node VM setup and have the below observations:
We just did simple tests wherein CRUDs were in progress using HTTP API on the node A's 8529 port while we did either node B or node C down. 

- With default replication factor 
 we observed below exception when one node was down
```
   arango.exceptions.DocumentInsertError: [HTTP 400][ERR 1465] cluster internal HTTP connection     broken
```

- With replication_factor set to 2 (while creating the collections)
 we observed below strange error

```
arango.exceptions.DocumentInsertError: [HTTP 501][ERR 9] '' not implemented
```
  Sometimes when node B was down , the HTTP clients sort of froze and did not resume transactions until node B was brought up.

- With replication factor set to 3,
  we observed below error

```
DocumentGetError: [HTTP 503][ERR 1478] AQL: backend unavailable, cluster node: 'PRMR-cf65449e-9dce-4934-9602-400372925535', shard: 's5010092'
```

This time with one node down, the rest of the nodes froze and UI too stopped responding.
Bringing up all three nodes back online did not restore system health.

There were some iterations where node down and up worked fine. But it was not consistent when we repeated the same test again.

The replication factor configuration was done in our internal test suite and not in the script I shared earlier.

**Comment by kunalak** [comment] 2017-11-08 17:48
The first error with replication factor 1 is correct behavior - since the DB server node (A or B or C whichever was taken down ) that holds the shard where the data is being written is downed, the insert operation will fail although there are other DBServers available. This is to protect consistency in case of replication 1. had there been more shards on other DBservers, the operation would have continued for the data inserts relevant to those shards but still fail for the shard whose DBServer is down. 

For cluster, we would always recommend replication factor of 2 (or 3 is better) for resiliency HA needs.

**Comment by kunalak** [comment] 2017-11-17 20:36
@jeeveeyes can we close this issue , please? (since we have tested both these out in your isolated environment and on my end as well and confirmed to work).

We will discuss specific environment/questions over email separately.

**Comment by dothebart** [comment] 2017-11-21 16:17
Ok, we will close this now.

**Closed by dothebart** 2017-11-21 16:17 UTC
Labels: 1 Bug, 3 Cluster, 3 Graph, Waiting User Reply

**Comment by jeeveeyes** [comment] 2017-11-29 09:10
Can you also clarify if replication factor is required to be tuned for graphs too ?

image

As can be seen above , for a simple graph, the default replication_factor is 1.
I could not locate the Arango REST API to set that replication_factor for a graph while creating it or as a PUT of the properties.

**Comment by dothebart** [comment] 2017-11-29 09:30
Hi, 
its mapped via: https://docs.arangodb.com/3.2/HTTP/Gharial/Management.html#create-a-graph 'replicationFactor' and controls the total number of copies of the shards in the cluster

**Comment by kunalak** [comment] 2017-11-29 19:08
@jeeveeyes @dothebart  ...and once the replication factor is changed for the Graph, it applies to "all" the collections of the associated with the graph.
