### ISSUE TITLE
Feature Request (from Google Groups): DATE handling 

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#317] opened 2012-12-09 22:22 UTC
I took the liberty to create a feature request out of this discussion: https://groups.google.com/forum/?fromgroups=#!topic/arangodb/3Wt4c44mc0I

Excerpt:
2) ArangoDB Server provides date handling functionality.

a) As date is a special type, I believe it could be handled that way. This can be provided by defining attributes in a collection as of special type 'date'. This could look like this:
     
```
db.myCollection.defineAttributeType('my.attribute', 'date');  
// This would for example set the nested attribute 'attribute' as a date field.
```

... for a nested document attribute inside a list, it could be:

```
db.myCollection.defineAttributeType('my[*].attribute', 'date');
  // This would for example set the nested attribute 'attribute' as a date field. ```
``` 
... or for a list that would contain dates:

```
db.myCollection.defineAttributeType('my[*]', 'date');
  // This would for example set the contents of a list as a date field
```
... mixing both could also be possible. So one could have a list of direct values and nested ones:

```
 {"my":[{"attribute":"2012-11-30T22:24:32.43Z"}, "2012-11-30T22:24:32.43Z"]}
```

b) The user would pass datetime strings like { "my":{"attribute":"2012-11-30T22:24:32.43Z"}} or maybe other formats like  { "my":{"attribute":"2012-11-30"}}... etc

      Internally, ArangoDB would convert and store those as timestamps.
      Knowing that it's a date field, it would automatically convert the datetime strings to timestamps for storing.

      That way, no special JSON handling is required by either the server or the client.
      Error handling: if the datetime string would have invalid data, the operation should be rejected.

c) With those would of course come some datetime functions to query (AQL)
      Simple queries  would probably not need anything special, as they are limited anyway.
      AQL queries:

```
DATE_MATH ("{mathcommand like add || subtract}", {date field to operate on, or a value}, {the modifying value , or a string like INTERVAL 1 WEEK'} );
 // Function to do math on a field or value
```
```
DATE_CURRENT (); Gets current date on server.
```

...maybe  more, that I haven't thought of just yet. But you get the idea :)
  

What do you think?

**Comment by neandrake** [comment] 2015-03-20 03:24
Would supporting BSON as storage type be beneficial here? That format supports defining date fields as well as binary (Issue #107) in addition to other types which might be beneficial such as 32/64bit integers, 64bit floating point (Issue #555) and regular expressions.

I imagine getting BSON to work with the v8 engine might be tricky, since it supports more things than the javascript language itself does.

**Comment by rizkyramadhan** [comment] 2015-06-14 16:31
Any update on this ?

**Comment by CoDEmanX** [comment] 2015-08-29 16:21
This discussion looks a bit rusty, and I'm not sure when the `DATE_*()` functions became [available in AQL](https://docs.arangodb.com/Aql/DateFunctions.html). I have the feeling though that they didn't exist when this discussion started.

There's no `DATE_ADD()`, but the following should work:

    // to UTC, not sure if DATE_ISO8601() would be equally fast...
    LET date = DATE_TIMESTAMP("2015-10-24 18:30+0200")
    
    LET Y = DATE_YEAR(date)
    LET M = DATE_MONTH(date)
    LET D = DATE_DAY(date)
    LET h = DATE_HOUR(date)
    LET m = DATE_MINUTE(date)
    LET s = DATE_SECOND(date)
    LET ms = DATE_MILLISECOND(date)
    
    
    RETURN {
        date: DATE_ISO8601(date),
        "date+3_days": DATE_ISO8601(Y, M, D+3, h, m, s, ms)
    }

This is basically how it's done in JavaScript AFAIK (`.setDay(.getDay()+2))`), e.g. by moment.js timezone.

Note that the client is responsible for either sending the correct UTC timestamp, or an ISO 8601 string with the correct timezone offset included. When the client moves from DST to regular time, then that's a shift of -1 to the offset (Germany: GMT+2 to GMT+1). If this isn't done by the client, then the calculated UTC time will be off by 1 hour. It's probably better to use UTC time in the first place on both sides. `new Date().toISOString()` in JavaScript returns an ISO 8601 string in Zulu (=UTC+0 / GMT+0 / world-) time anyway - granted the time and timezone offset is correctly set up on the client's machine.

**Comment by CoDEmanX** [comment] 2015-08-30 04:17
WIP patch for extra date functions:
https://gist.github.com/CoDEmanX/1c7bfd266ad70da2d641

```js
LET date = DATE_NOW()

RETURN {
    dayOfYear: DATE_DAYOFYEAR(date),
    weekDate: DATE_ISOWEEK(date),
    firstApril: DATE_CALC("2015-03-31", "day", 1),
    xmas2011: DATE_CALC("2015-12-24", "years", -4)
}
/* [
  {
    "dayOfYear": 242,
    "weekDate": 35,
    "firstApril": "2015-04-01T00:00:00.000Z",
    "xmas2011": "2011-12-24T00:00:00.000Z"
  }
] */
```

There's a bug I can't seem to figure out: if I pass DATE_CALC() the result of another data function, such as DATE_NOW(), then an empty object `{}` is returned. It works fine for date strings and numbers however.

**Comment by CoDEmanX** [comment] 2015-08-30 19:12
Figured it out, my `DATE_CALC()` needs to explicitly return an ISO string, not a date object.

```js
LET date = DATE_NOW()

RETURN {
    dayOfYear: DATE_DAYOFYEAR(date),
    weekDate: DATE_ISOWEEK(date),
    dayAfterTomorrow: DATE_CALC(date, "days", 2),
    lastDayFeb2015: DATE_CALC(DATE_CALC("2015-02", "month", 1), "day", -1),
    lastDayFeb2016: DATE_CALC(DATE_CALC("2016-02", "month", 1), "day", -1),
    xmasFourYearsAgo: DATE_CALC(DATE_TIMESTAMP(DATE_YEAR(date), 12, 24), "years", -4),
    leapyear: DATE_LEAPYEAR(date),
    leapyear2016: DATE_LEAPYEAR("2016")
}
/* [
  {
    "dayOfYear": 242,
    "weekDate": 35,
    "dayAfterTomorrow": "2015-08-31T15:17:52.397Z",
    "lastDayFeb2015": "2015-02-28T00:00:00.000Z",
    "lastDayFeb2016": "2016-02-29T00:00:00.000Z",
    "xmasFourYearsAgo": "2011-12-24T00:00:00.000Z",
    "leapyear": false,
    "leapyear2016": true
  }
] */
```

Here's a patch including unit tests (did not actually run them...), documentation and syntax highlighting in aardvark (app.js.gz / app.min.js.gz need to be rebuilt):
https://gist.github.com/CoDEmanX/9a0f61d02a8ecbb127f4

Not sure what to do about `DATE_DIFF()`... in MySQL, the number of days between the dates is returned. Only the date part is considered (i.e. time is ignores). I'm not sure what MySQL returns for `DATEDIFF("2014-12-31T23:59:59.999Z", "2015-01-01T00:00:00.000Z")`, it's oly 1ms but on two different days (UTC+0). Does/should it return 1, 0 or 1/864e5? A possible AQL solution would be:

```js
LET date1 = "2014-12-31T23:59:59.999Z"
LET date2 = "2015-01-01T00:00:00.000Z"
LET t1 = DATE_TIMESTAMP(DATE_YEAR(date1), DATE_MONTH(date1), DATE_DAY(date1))
LET t2 = DATE_TIMESTAMP(DATE_YEAR(date2), DATE_MONTH(date2), DATE_DAY(date2))
RETURN {diff: (t1 - t2) / 864e5} // {"diff": -1}
```

Would be easy to make a shortcut for this, if it's really the way it should work. I can also think of a fancier version that takes an additional parameter to specify the target unit (years, months, days, hours, ...). And perhaps an additional parameter to control whether fractions shall be returned or not. It would be easy to achieve a query like "true if difference between A and B is < 24 hours" with both of the latter: `DATE_DIFF(A, B, "hours", true) < 24` (or `"days"` and `< 1`).

**Comment by jsteemann** [comment] 2015-08-31 07:33
@CoDEmanX : is the patch still WiP? If yes, please take your time and let us know when/if you want us to merge it. Thanks for the work!

**Comment by CoDEmanX** [comment] 2015-08-31 08:42
Yes, I would consider it WIP and I'd like to hear some thoughts about the code.

I already improved `DATE_CALC()` locally to use a dictionary lookup to determine the getters and setters for the given time unit (which I renamed to *interval*). That should be faster than the current switch monster, and is definitely shortly in terms of code length. It's slightly harder to follow though, because the lookup object is at the beginning of the file and I later reference the getter and setter names like `m[1]` - which is a bit cryptic. Destructuring would massively improve the readability. Will update as destructuring assignment becomes available in V8.

Furthermore, I added `DATE_QUARTER()`, a straightforward calculation but still handy. I also took a shot at the described `DATE_DIFF()`, but I'm having trouble with the overall design. Some quick tests showed unexpected results, which may or may not be caused by the fact that [JS ignores leap seconds ](http://www.ecma-international.org/ecma-262/6.0/#sec-time-values-and-time-range). I also found some hints about timezone trouble if you are +/- 12 hours ahead or behind UTC and do not know yet if it applies if `Date.UTC` is used. `DATE_DIFF("2015-05-06", DATE_CALC("2014-05-06", "day", -1), "years")` and similar calculations should eventually return the "age", 1 year in the example, regardless of timezone, DST and leap years. If that is possible without handling leap seconds, I'm not so sure.

**Comment by jsteemann** [comment] 2015-08-31 09:39
I think leap seconds need to be ignored because the underlying JS operations don't support them.
And if they're entirely ignored by all functions that handle dates, I think they shouldn't cause further problems in calculations. 

Directly referring to a leap second date value would then need to be considered an invalid date, as suggested by the following JS:
```
> new Date("2015-06-30T23:59:59Z").toISOString(); /* regular date */
2015-06-30T23:59:59.000Z
> new Date("2015-06-30T23:59:60Z").toISOString(); /* leap second date */
JavaScript exception: RangeError: Invalid time value
!new Date("2015-06-30T23:59:60Z").toISOString();
!                                 ^
stacktrace: RangeError: Invalid time value
  at Date.toISOString (native)
  at <shell command>:1:34
```

Apart from that, all date functions should work with UTC internally, and also assume UTC if no timezone is specified. I think your functions all do this. I think then they should be reasonably safe to use for UTC at least. My assumption is that this should work with other timeszones too, provided the JS Date implementation handles them correctly. I am not aware of any issues with +/12 hours timezones, but I haven't searched for this yet. Is there any specific issue?

I would leave the ISO 8601 periods for later, in order to make the changes more manageable (diff becomes smaller).

**Comment by CoDEmanX** [comment] 2015-08-31 10:12
Huh, I didn't know it would reject the second 60 in a string. It does accept it if the constructor is called with numbers, but will actually overflow to minutes - so that it's not referring to the leap second. We should be safe indeed.

I also believe that it should work with other timezones, because MAKE_DATE() creates UTC Date objects with Zulu time and thus it should be impossible to run into trouble as long as setUTC*() and getUTC*() are used, and toISOString() returned if needed (Zulu-time time string).

The trouble with timezones like Brazil seems to originate from rounding a date difference. The 12 hours offset places it exactly on UTC noontime (12:00). The rounding may go in the wrong direction it seems, leading to off-by-one errors. But this might be a matter of picking the right rounding function (ceil, floor, round). I need to check again if they used 12:00:00+1200 or 00:00:00+1200.

**Comment by CoDEmanX** [comment] 2015-09-02 16:22
When it comes to date differences, I really don't know what users expect under certain conditions. MySQL's `DATEDIFF()` ignores the time portion and returns the number of days.

If we want to let the user specify the desired time unit however, should all greater units be taken into account up to the specified one, and the rest ignored? Like, if diff in minutes is requested, should the seconds and milliseconds of both input dates be ignored? 2014-03-02 16:17:~~18.987~~

Ignoring them would lead to integer results, and decimal fractions otherwise. Such fractions are problematic if months or years are requested as output time unit, because it can't be easily calculated:

Time unit | equivalent | in milliseconds
------------|---------------|--------------------
1 second | 1000 ms | 1000ms
1 minute | 60 seconds (JS doesn't care about leap seconds) | 60,000
1 hour | 60 minutes | 3,600,000
1 day | 24 hours (no 23/25h days in UTC time) | 86,400,000
1 week | 7 days | 604,800,000
1 month | **28, 29, 30 or 31 days!** | from 2,419,200,000 to 2,678,400,000
1 year | **365 or 366 days** | from 31,536,000,000 to 31,622,400,000

Using average ms per month / year would certainly give unexpected results, because +1 year and 2 days may still be <1 year depending on the date. I'm not sure yet if there's an easy way in JS to safely determine month/year diff with fractions, but I doubt it. One would probably need to handle the individual date components and accumulate the ms per months depending on which month it is and if it's a leap year.

Furthermore, a user might expect the dates 2015-01-01 and 2016-01-01 to have a difference of 1 year (think age calculation). That's not correct IMO, because the year isn't complete if it's the same day. It only is, if the first date has time 00:00:00 and the second 24:00:00 - which is effectively the next day. This could be pointed out in the documentation however ("add one day / 24 hours if...").

Adding or subtracting ISO durations from a given date shouldn't be as problematic, because a point in time is known and changes are applied in relation to that time natively by JS (+1 month is +28..31 days, so a month as expected and not a fixed amount of days such as 30).

**Comment by friday** [comment] 2015-09-02 17:07
Nice work! @CoDEmanX :)

Could you elaborate on how 2015-01-01 + 1 year makes 2016-01-02? I can't see that making sense semantically or mathematically.

**Comment by CoDEmanX** [comment] 2015-09-02 17:48
2015-01-01 + 1 year needs to be 2016-01-01 and 2016-01-01 -1 year 2015-01-01 of course. `DATE_CALC()` should already do that. But that's Date + Duration.

What I mean is the expected result of `DATE_DIFF(Date1, Date2, "years")` if the input is 2016-01-01 and 2015-01-01 respectively. Is the difference a year? I say no, because the year isn't complete. It has 365 (366) days, with the last day *included*. Hence, the 24 hours of the last day are also included. If you start at 2015-01-01 (which is 00:00:00.000) and go to 2016-01-01 (also 00:00:00.000), then 86,399,999 ms are missing of that last day to complete the year, no? The day ends the moment 2016-01-01 23:59:59.999 is over to **24**:00:00.000, which is 2016-01-**02** 00:00:00.000 - or am I overthinking this?

**Comment by friday** [comment] 2015-09-02 19:38
I thought it was more appropriate to continue the discussion as comments to [your patch](https://gist.github.com/CoDEmanX/1c7bfd266ad70da2d641). Maybe a separate issue would be even better for keeping history though? This issue seems to deal more with types, validation and formatters than just date functions.

**Comment by jsteemann** [comment] 2015-09-03 08:07
@CoDEmanX : to summarize the latest concerns regarding `DATE_DIFF()`, is the problem that the unit `year` has does not correspond to a fixed number of days or seconds? I.e. how many days a year has depends on whether the date range in question contains leap years or not. 

The same would be true for months, e.g. for `DATE_DIFF("2014-02-28", "2014-03-28", "months")`: is the expected result the value `1` (because one calendar month elapsed) or 0.9xx because a month is 30.x days on average? 

MySQL's `DATEDIFF` will elegantly ignore all these issues it only returns days (which always have the same length, at least when leap seconds are ignored) and does not take into account the time part. Maybe it's worth getting as simple as that in AQL, too.

**Comment by friday** [comment] 2015-09-03 16:59
A solar year is 365.2422 days, making an average solar month 365.2422 / 12 = 30,43685 days. Using those numbers to calculate the diff would ensure not accumulating errors if the span is very long between the dates, but comparisons between short spans (especially around february) would have a significant margin of error. Does this method have to be accurate however? If I wanted to get accurate measures I would not use month or year as a units, and if this is over engineered for accuracy and I just `ROUND()` it anyway the accuracy would cost me cpu time.

If mimicking MySQL's `DATEDIFF`, you would also need something like their `TIMEDIFF` for more precise data.

Also, MySQL are doing `date1 - date2` instead of `date2 - date1`. I would prefer the more standardized and intuitive `date2 - date1`.

**Comment by CoDEmanX** [comment] 2015-09-03 18:41
@jsteemann: I could make it accept days..ms as output time unit only, but I would like to allow for months and years too, because I see a demand for that (especially age calculation).

@friday: there should be a way that isn't too cpu-intense and still be accurate. It's just some brainwork to figure it out. I also prefer `date2 - date1`, because you get negative values too easily the other way around and it's probably not what you want (I don't want to return an absolute number either).

**Comment by CoDEmanX** [comment] 2015-09-03 23:07
moment.js seems to be doing it correctly from what I can tell:
**Test**: [codepen.io](http://codepen.io/simran/pen/jbEmQB)

If this proves to be correct, the entire library could either be added, or the essential parts be taken out and integarted directly into ArangoDB (it's MIT-licensed).

**Comment by jsteemann** [comment] 2015-09-04 08:52
@CoDEmanX : :+1: for `date2 - date1`.

moment.js may be a solution. Does it have any dependencies? By the way, the codepen test linked above only produces `NaN` values in my Firefox 40.0.3.

**Comment by CoDEmanX** [comment] 2015-09-04 11:18
It has a lot dev dependencies, but no runtime dependencies it seems.

I fixed the pen for Firefox, it didn't like timezone offsets (trailing Zs) if no hours and minutes are given - which is a bit odd. I'm now creating moment objects in UTC time explicitly, to exclude DST changes.

Another question that came up when I looked at the code of AQL_LIKE: there's a Regex cache, that is apparently never cleared. Doesn't it mean that if a user runs thousands of different like queries, that the server will use more and more memory for the cache without ever releasing it? Isn't that a problem if the arangod runs for a year straight?

I wonder if ES6 weaksets will help. The GC would be allowed to get rid of cache entries, but will it do so eventually, or rather early? If it cleaned the cache shortly after its creation, then it would render the cache useless...

**Comment by friday** [comment] 2015-09-04 11:56
I tried to make an equivalent to moments `diff()`. Unless you need anything else from moment.js, perhaps my example can be used as a starting point? https://gist.github.com/CoDEmanX/1c7bfd266ad70da2d641#gistcomment-1566640

**Comment by CoDEmanX** [comment] 2015-09-04 13:05
Good work @friday! Looks good to me.

moment.js has a lot of nice features, but I don't think we really need them server-side. While it may seem good to have a `.humanize()` for durations in AQL to output something like `3 years, 14 days`, it doesn't really belong on the server. A JS client can easily use moment.js to do that and reduce the load of the server.

And it's not really useful anyway to send pretty-printed data around - see StackOverflow for example: post dates are nicely formatted, but lack precision. You can hover them though to reveal the actual timestamp for a precise point in time if you really care to know. My points: it gives more options to the client if the "raw" date is transmitted.

The only advantage I see in having a full moment.js on the server is that date formatting becomes client independent. If you use Python for instance, then you can't use moment.js and need to find a replacement. If there's no good replacement, then you'll have to come up with your implementation - which is not all that trivial as we saw.

**Comment by CoDEmanX** [comment] 2015-09-09 08:37
@jsteemann: We could use your input in our discussion, first post contains a summary:
https://github.com/CoDEmanX/ArangoDB/issues/1#issue-105221498

It doesn't need to be a code review yet, it's rather about **how** things **should work**.

**Comment by jsteemann** [comment] 2015-12-02 16:16
I will close this issue now, as with ArangoDB 2.7 the following AQL date functions have been added. Quoting from the CHANGELOG:

  * `DATE_DAYOFYEAR(date)`: Returns the day of year number of *date*.
    The return values range from 1 to 365, or 366 in a leap year respectively.

  * `DATE_ISOWEEK(date)`: Returns the ISO week date of *date*. 
    The return values range from 1 to 53. Monday is considered the first day of the week. 
    There are no fractional weeks, thus the last days in December may belong to the first 
    week of the next year, and the first days in January may be part of the previous year's
    last week.

  * `DATE_LEAPYEAR(date)`: Returns whether the year of *date* is a leap year.

  * `DATE_QUARTER(date)`: Returns the quarter of the given date (1-based):
    * 1: January, February, March
    * 2: April, May, June
    * 3: July, August, September
    * 4: October, November, December

  - `DATE_DAYS_IN_MONTH(date)`: Returns the number of days in *date*'s month (28..31).
    
  * `DATE_ADD(date, amount, unit)`: Adds *amount* given in *unit* to *date* and
    returns the calculated date.

    *unit* can be either of the following to specify the time unit to add or
    subtract (case-insensitive):
    - y, year, years
    - m, month, months
    - w, week, weeks
    - d, day, days
    - h, hour, hours
    - i, minute, minutes
    - s, second, seconds
    - f, millisecond, milliseconds

    *amount* is the number of *unit*s to add (positive value) or subtract
    (negative value).

  * `DATE_SUBTRACT(date, amount, unit)`: Subtracts *amount* given in *unit* from
    *date* and returns the calculated date.
    
    It works the same as `DATE_ADD()`, except that it subtracts. It is equivalent
    to calling `DATE_ADD()` with a negative amount, except that `DATE_SUBTRACT()`
    can also subtract ISO durations. Note that negative ISO durations are not
    supported (i.e. starting with `-P`, like `-P1Y`).

  * `DATE_DIFF(date1, date2, unit, asFloat)`: Calculate the difference
    between two dates in given time *unit*, optionally with decimal places.
    Returns a negative value if *date1* is greater than *date2*.

  * `DATE_COMPARE(date1, date2, unitRangeStart, unitRangeEnd)`: Compare two
    partial dates and return true if they match, false otherwise. The parts to
    compare are defined by a range of time units.
    
    The full range is: years, months, days, hours, minutes, seconds, milliseconds.
    Pass the unit to start from as *unitRangeStart*, and the unit to end with as
    *unitRangeEnd*. All units in between will be compared. Leave out *unitRangeEnd*
    to only compare *unitRangeStart*.

  * `DATE_FORMAT(date, format)`: Format a date according to the given format string.
    It supports the following placeholders (case-insensitive):
    - %t: timestamp
    - %z: ISO date (0000-00-00T00:00:00.000Z)
    - %w: day of week (0..6)
    - %y: year (0000..9999)
    - %m: month (01..12)
    - %d: day (01..31)
    - %h: hour (00..23)
    - %i: minute (00..59)
    - %s: second (00..59)
    - %f: millisecond (000..999)
    - %x: day of year (001..366)
    - %k: ISO week date (01..53)
    - %l: leap year (0 or 1)
    - %q: quarter (1..4)
    - %a: days in month (28..31)
    - %n: English name of month (January..December)
    - %o: abbreviated English name of month (Jan..Dec)
    - %e: English name of weekday (Sunday..Saturday)
    - %g: abbreviated English name of weekday (Sun..Sat)
    - %%: literal %

**Closed by jsteemann** 2015-12-02 16:16 UTC
Labels: 3_Feature, api

**Comment by CoDEmanX** [comment] 2015-12-02 17:09
The format options of DATE_FORMAT() are actually outdated, up-to-date list in the [docs](https://docs.arangodb.com/Aql/DateFunctions.html).

**Comment by jsteemann** [comment] 2015-12-02 17:28
I copied those from the 2.7 CHANGELOG, and the list from 2.7 indeed deviates from the one in devel.
I'll update the list in 2.7, as the devel list seems to be the up-to-date one. Thanks for the note.

**Comment by CoDEmanX** [comment] 2015-12-02 17:56
Looks like something went wrong with my PR https://github.com/arangodb/arangodb/pull/1489/files
but no one complained so far plus it's correct in the docs :+1:

**Comment by jsteemann** [comment] 2015-12-03 08:45
@CoDEmanX : so are you saying everyhing's ok and the current codebase is as it should be?

**Comment by CoDEmanX** [comment] 2015-12-03 09:31
Yeah, everything's tidied up.

**Comment by jsteemann** [comment] 2015-12-03 09:57
thx for the confirmation
