### ISSUE TITLE
Deadlock by unavailable V8-Context vs. Collection locks

### ISSUE THREAD

**Issue by danielmalmq** [arangodb/arangodb#2381] opened 2017-03-18 17:17 UTC
I am seeing some strange issues in arango where I the database becomes unresponsive. The logs say nothing of importance and I keep getting timeout after a few concurrent script executions. 

Issue is reproducable by running the script (https://gist.github.com/danielmalmq/f5c1b5459414ece86ad9823c62b242cb) a couple of times concurrently, a jmeter execution of 10 concurrent requests kills arango after a few seconds. Once it becomes unresponsive I have to kill arangos processes and restart it.

Reproducable in 3.1 & 3.2.alpha2, on both windows and ubuntu.

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [*] 3.1
- [*] 3.2 pre-releases: 3.2.alpha2
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [*] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [*] Windows, version: 10
- [ ] MacOS, version:

### this is an AQL-related issue:
[*] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [*] this Driver: https://github.com/arangodb/arangodb-php/tree/devel/lib/ArangoDBClient

For ease of use I extended the driver with a collection param in its GraphHandler hasVertex:
```
    public function hasVertex($graph, $vertexId, $collection = null)
    {
        try {
            // will throw ServerException if entry could not be retrieved
            if (isset($collection))
                $this->getVertex($graph, $vertexId, array(), $collection);
            else
                $this->getVertex($graph, $vertexId);

            return true;
        } catch (ServerException $e) {
            // we are expecting a 404 to return boolean false
            if ($e->getCode() === 404) {
                return false;
            }

            // just rethrow
            throw $e;
        }
    }
```

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:
```
FOR p IN 1..2 OUTBOUND "' . $user->getHandle() . '"
  GRAPH \'Graph\' 
  
  FILTER LEFT(p._id, 15) == "PostCollection/"
    SORT p.time DESC
  
    COLLECT post = p
    SORT post.time DESC
    LIMIT 100
    
    LET poster = FIRST (
        FOR user IN 1..1 OUTBOUND post PostToUserCollection LIMIT 1 RETURN user
    )
    
    RETURN {post, poster}
```

The issue can be reproduced using this dataset:
https://gist.github.com/danielmalmq/f5c1b5459414ece86ad9823c62b242cb

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.
https://gist.github.com/danielmalmq/f5c1b5459414ece86ad9823c62b242cb

**Comment by jsteemann** [comment] 2017-03-20 12:58
I was able to reproduce the problem, and it seems to be caused by the following situation:
- there are several server threads that try to insert data into the vertex or edge collections. these threads have already acquired a V8 context for JavaScript execution and now try to acquire a lock on the vertex/edge collection for the insertion.
- there is at least one server thread that executes the AQL traversal query. it has already acquired the locks for the collections, but now needs to acquire a V8 context because it is executed some JavaScript code inside the AQL (that is presumably for the `LEFT` function).
- all available V8 contexts are in use, so the AQL query cannot acquire a V8 context and cannot make progress. The query blocks the other operations however, which have used the V8 contexts already.

So it's a deadlock. 

The insertion operations that wait on the collection locks will abort after 15 minutes by default, but by then the PHP client will have already disconnected with a timeout error. In ArangoDB version 3.2, this timeout is 10 minutes. And in 3.2 the operations that wait for an unused V8 context will also abort after 2 minutes, so the locks are resolved a bit earlier there. In 3.2 the number of available V8 contexts is also dynamic, so the server can create additional V8 contexts when needed. All of these measures should mitigate the problem in 3.2.

Some further mitigation workarounds that should work in 3.1 and 3.2 alike:
- modify the AQL traversal query to not use a V8 context. This should be possible by changing the query part `FILTER LEFT(p._id, 15) == "PostCollection/"` to `FILTER IS_SAME_COLLECTION("PostCollection", p._id)`. This measure alone should eliminate the deadlock.
- increase the number of available V8 contexts in the server by increasing the server startup option `--javascript.v8-contexts`. If the number of v8 contexts is higher than the number of concurrently executing client requests, then the deadlock situation should be avoided as well. But please note that each V8 context will consume some memory so the number of contexts cannot be increased arbitrarily.

**Comment by dothebart** [comment] 2017-07-25 07:37
ArangoDB 3.2 is now available for download. 
It now can dinamically spawn V8 contexts up to a configureable limit (RAM constratins)

Closing.

**Closed by dothebart** 2017-07-25 07:37 UTC
Labels: 3 Core
