### ISSUE TITLE
AQL statement not working in 3.3.1 when upgraded from 3.2.10

### ISSUE THREAD

**Issue by RHSman** [arangodb/arangodb#4197] opened 2018-01-02 21:29 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.2.10
- [ ] 3.3

Mode:
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
  - [ ] docker - official docker library

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] Foxx

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

```js
for s in skills
    for sny in s.synonyms
        let snys_1 = (FOR doc IN FULLTEXT(experience, "description", sny)
            RETURN {exp_id: doc._id, description: doc.description, synonym: sny,
            skill: s.skill_name, desc_xpath: doc.desc_meta, title_xpath: doc.title_meta})
        for a in snys_1
            collect description = a.description into syns_group
            return {synonym: syns_group[*].sny, skill: syns_group[*].s,
            desc_meta: syns_group[*].snys_1[*].desc_xpath, title_meta: syns_group[*].snys_1[*].title_xpath,
            description: description }
```

The issue can be reproduced using this dataset:

Create 2 collections: skills and experience. Experience needs a fulltext index on the description column
[data.zip](https://github.com/arangodb/arangodb/files/1598728/data.zip)

```
arangoimp --file "skills.jsonl" --type json --collection "skills" --batch-size 33554432 --create-collection true
arangoimp --file "experience.jsonl" --type json --collection "experience" --batch-size 33554432 --create-collection true
```

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"})` statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### Foxx
This originates in a Foxx service but shows itself in AQL

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...root
3) use database [ ] `_system`
4) run AQL query above
5) on 3.2.10, this will return records
6) on 3.3.1 it will return 'Bad Parameter'
7) the problematic part seems to be (`FOR doc IN FULLTEXT(experience, "description", sny`) and the syn which if hardcoded with a value return records
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by terry124** [comment] 2018-01-03 06:10
K in

**Comment by terry124** [comment] 2018-01-03 07:09
Hi

**Comment by Simran-B** [comment] 2018-01-03 08:44
@RHSman can you post the execution plans from both 3.2.10 and 3.3.1? I expect a difference there because of some incorrect optimization in 3.3.x

**Comment by jsteemann** [comment] 2018-01-03 11:07
Got it reproduced in 3.3

**Comment by RHSman** [comment] 2018-01-03 11:08
Sorry, I’m away from computer currently. Good luck and glad you have
reproduced.

**Comment by jsteemann** [comment] 2018-01-03 12:53
No worries.

**Comment by jsteemann** [comment] 2018-01-03 13:46
Fixed in https://github.com/arangodb/arangodb/pull/4207

**Comment by maxkernbach** [comment] 2018-01-09 12:48
Version 3.3.2 containing the fix is released.
Please reopen this issue if the bug still occurs.

Thanks

**Closed by maxkernbach** 2018-01-09 12:48 UTC
Labels: 1 Bug, 2 Fixed, 3 AQL
