### ISSUE TITLE
ServerException: RestHandler/RestCursorHandler.cpp:279

### ISSUE THREAD

**Issue by xyzsada** [arangodb/arangodb#9862] opened 2019-08-30 07:04 UTC
## My Environment

* __ArangoDB Version__:        3.5.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Master/Slave
* __Deployment Strategy__:   Manual Start
* __Configuration__:               none
* __Infrastructure__:               own
* __Operating System__:        CentOS Linux release 7.3.1611 (Core)
* __Total RAM in your machine__:        16Gb
* __Disks in use__:        SSD
* __Used Package__:              yum

## Component, Query & Data

__Affected feature__:
AQL query using with php driver

__AQL query (if applicable)__:

FOR n IN 1..1 INBOUND @parent_id child_of FILTER n != null
SORT n.display_order
RETURN {
    "node": n,
    "fff": (
        FOR f IN fffs
            FILTER f._id == n.o_id || f._id == n.e_id
            RETURN f
    ),
    "ppp": (
        FOR p IN ppps
            FILTER p._id == n.o_id || p._id == n.e_id
            RETURN p
    ),
    "mmm": (
        FOR m IN mmms
            FILTER m._id == n.o_id || m._id == n.e_id
            RETURN m
    )
}

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

$statement = new ArangoStatement($connection, ['query' => $query]);
$statement->bind('parent_id', $parent_id);
$cursor = $statement->execute();

__Problem__:

ArangoDBClient\ServerException: 4 Expecting type String (while executing) (exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:279). Please report this error to arangodb.com

__Expected result__:

"$statement->execute()" returns a cursor.

**Comment by jsteemann** [comment] 2019-08-30 07:13
Thanks for reporting this.
The issue seems to be data-dependent.
Is it possible to specify the value of `$parent_id` when the query is started, plus a minimal dataset for reproduction? Thanks

**Comment by xyzsada** [comment] 2019-08-30 09:12
[dump.zip](https://github.com/arangodb/arangodb/files/3559149/dump.zip)
I think it fails when there is a '||' condition in the FILTER.
parent_id = 'nodes/4029727'

**Comment by jsteemann** [comment] 2019-08-30 09:15
Thanks, that helps reproducing it! Analyzing now...

**Comment by jsteemann** [comment] 2019-08-30 10:12
Fixed via the above PRs. The fix is expected to land in 3.5.1

**Comment by xyzsada** [comment] 2019-08-30 10:21
Thanks a lot!

**Comment by Simran-B** [comment] 2019-08-30 10:44
Please keep this issue open, we will close it when 3.5.1 gets released. Thanks!

**Comment by xyzsada** [comment] 2019-09-02 01:15
ok, I'm waiting.

**Comment by darkfrog26** [comment] 2019-09-10 15:30
I just ran into this as well. Any ETA on when this will be rolled out?

**Comment by darkfrog26** [comment] 2019-09-10 15:36
This should really be deployed as a hotfix ASAP since it is creating production issues for your users.

**Comment by dothebart** [comment] 2019-09-10 15:43
Hi,
if you want to get notified to new releases being available, please subscribe to:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/arangodb-announce

If you want to discuss about release dates etc. for better synchronizing your releases etc. please have a look at our subscriptions: https://www.arangodb.com/subscriptions/

The release cycle usually goes like this:

   1) add tag to git
   2) build release packages
   3) thoroughly test the release and the packages (maybe go back to 1) )
   4) publish

Also this issue will be closed once the fix is available in a published ArangoDB-Version.

**Comment by darkfrog26** [comment] 2019-09-10 15:47
@dothebart, I understand all of this, but since this bug has no workaround and is one-liner fix, a hotfix seems reasonable.

**Comment by maxkernbach** [comment] 2019-10-09 12:06
Hi @xyzsada and @darkfrog26,

Version 3.5.1, which includes for this issue, has just been released.

From the [changelog](https://github.com/arangodb/arangodb/blob/345a06ade456252321f2b465df032baae0110bed/CHANGELOG#L179):

> * Fixed issue #9862: ServerException: RestHandler/RestCursorHandler.cpp:279
> 
>   This fixes an issue with the RocksDB primary index IN iterator not resetting its
>   internal iterator after being rearmed with new lookup values (which only happens
>   if the IN iterator is called from an inner FOR loop).

Please find the latest release in the [download section](https://www.arangodb.com/download-major/).

**Closed by maxkernbach** 2019-10-09 12:06 UTC
Labels: 1 Bug, 2 Fixed, 3 AQL
