### ISSUE TITLE
Add Format button into administration

### ISSUE THREAD

**Issue by gurisko** [arangodb/arangodb#12721] opened 2020-09-28 23:08 UTC
This is a feature request.

It would be nice to have a "Format" button in Queries Editor that would format the provided query. I often copy queries from application logs that were generated automatically.

**Comment by maxkernbach** [comment] 2020-09-30 10:31
Hi @gurisko,

Thanks for reporting. I am closing this issue as a duplicate of https://github.com/arangodb/arangodb/issues/12075 (same Feature request).

**Closed by maxkernbach** 2020-09-30 10:31 UTC
