### ISSUE TITLE
WAL recovery finished successfuly

### ISSUE THREAD

**Issue by 357589873** [arangodb/arangodb#4894] opened 2018-03-20 06:57 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [ ] 3.3
- [-- ] self-compiled devel branch

Mode:
- [-- ] Cluster
- [ ] Single-Server

Storage-Engine:
- [-- ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [-- ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ---] other:centos
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[-- ] I'm using graph features

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
![image](https://user-images.githubusercontent.com/9959634/37639876-10acd374-2c4e-11e8-90bd-361488914065.png)

when I start arangodb(I use this command "./arangod --configuration /home/name/arangodb/etc/arangodb3/arangod.conf"),it recovery tmp file.When successully loaded,it stop in this step,and can not using endpoint.8529 port is unuseful. and I am using self compiled version,3.1.11 from source code.

Instead I would be expecting: 
2018-03-20T06:23:41Z [32371] INFO Authentication is turned on
2018-03-20T06:23:41Z [32371] INFO Authentication system only
2018-03-20T06:23:41Z [32371] INFO Authentication for unix sockets is turned on
2018-03-20T06:23:41Z [32371] INFO file-descriptors (nofiles) hard limit is 20480, soft limit is 20480
2018-03-20T06:23:41Z [32371] INFO JavaScript using startup '/home/pixiu/arangodb/usr/share/arangodb3/js', application '/home/pixiu/arangodb/var/lib/arangodb3-apps'
2018-03-20T06:23:43Z [32371] INFO using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
2018-03-20T06:23:46Z [32371] INFO Please note that a new bugfix version '3.1.28' is available
2018-03-20T06:23:46Z [32371] INFO Please note that a new minor version '3.3.4' is available
2018-03-20T06:23:46Z [32371] INFO ArangoDB (version 3.1.11 [linux]) is ready for business. Have fun!

### this is an installation-related issue:
I delete the /home/pixiu/arangodb/var/lib/arangodb3/journals/ files,and it works. So I wonder if it is a bug.

**Comment by dothebart** [comment] 2018-03-28 09:30
This is intended behaviour. Data first gets written into the WAL files, and is later on moved into their respective database files. This way arangodb can do linear writes without needing too many memory maps at once and potentially distributing writes across the disk.  Please have a look at the manual for more detailed description of the mechanism:
https://docs.arangodb.com/3.3/Manual/Administration/Configuration/Wal.html

**Comment by maxkernbach** [comment] 2018-04-09 12:14
Hi @357589873,

do you have additional questions or can we consider this issue as solved?

**Comment by maxkernbach** [comment] 2018-04-23 12:48
I am closing this issue as solved for now.
Please feel free to comment and reopen in case you have further questions.

**Closed by maxkernbach** 2018-04-23 12:48 UTC
Labels: 1 Question, 2 Solved, 3 Cluster, 3 MMFiles, Waiting User Reply
