### ISSUE TITLE
Rapid Document Write through FOXX causes timeout

### ISSUE THREAD

**Issue by riverdusty** [arangodb/arangodb#1803] opened 2016-04-14 12:18 UTC
I think this is a unique situation but would like to get feedback.
I'm doing some data mining project and I create documents dynamically and write them to ArangoDB through FOXX. I need to do this one at a time so that my app can get the created _key from arango and assign it to that bit of data.
When I do this I can write to ArangoDB at about 300 posts per second. Yay!
After around 16000 documents ArangoDB times out. I then have to wait for 5 minutes (or restart Arango) to continue the process.
I've tried playing with index bucket size and journal size but the result is always the same.
I'm running ArangoDB 2.8.4 on Mac OS X.
Documents are tiny but I have nearly a million of them:

``` javascript
{
    "_from" : "foxxapp_datacol/2073050929375",
    "history" : {
        "2016-03-31" : 2
    },
    "rating" : 10,
    "popularity" : 2,
    "_key" : "2262876573202",
    "_to" : "foxxapp_datacol/2087500641663"
}
```

**Comment by dothebart** [comment] 2016-04-14 13:23
you're not by accident using the homebrew version compiled with clang?

**Comment by riverdusty** [comment] 2016-04-14 14:00
That is a strong possability. I can't remember how I initially installed ArangoDB but it may well have been using brew. 
I should perhaps try the downloaded binary?
Anything I can try/do?

**Comment by dothebart** [comment] 2016-04-14 14:08
With el capitans clang release ArangoDB performance on MacOSX came to a grinding halt, which is why the package strongly sugests to use gcc instead. You can try either that and rebuild ArangoDB, 
Or download one of the binary packages available on https://arangodb.com/downloads and retry with those.

**Comment by riverdusty** [comment] 2016-04-14 14:12
Looks like I'll have to wait. That link shows me ```[php snippet=3]```
Someone doing site maintenance?
When I do get it right, I'll come back with whether it worked.

**Comment by dothebart** [comment] 2016-04-14 14:22
ooouuups, fixed. Thanks for reporting.

**Comment by riverdusty** [comment] 2016-04-14 15:27
Ok, using the downloaded version, set up my FOXX app and began writing.
16340 document(s) and it stops. I checked logs and nothing.
Just times out. Any more ideas?!

I can enable sync and let it run over night. Enabling Sync has a massive performance impact (Obviously).

**Comment by Simran-B** [comment] 2016-04-14 15:43
How is the disk activity during the first 10k writes and how shortly before
the timeout? Does it constantly grow to a point at which it would have to
sync more data to disk than the storage device is capable of? How is the
RAM utilization at the same time? Does the OS start to swap at some point
because of insufficient main memory?

I can imagine that there's a point at which the server should reject writes
because of high load, instead of accepting them and eventually fail.

**Comment by riverdusty** [comment] 2016-04-14 19:02
> Does it constantly grow to a point at which it would have to sync more data to disk than the storage device is capable of?

I presume you mean in terms of performance, but i doubt this as my latest test slows the write speed to one tenth (about 10 documents a second) and it still times out after around 16 000 documents. It just takes longer.

I will run tests for ram and disk utilization and get back. 
FYI: The machine does have 8GB of ram.

**Comment by Simran-B** [comment] 2016-04-14 21:26
Okay, so it's apparently not the SSD/HDD that chokes on the data, but the database. We will investigate this further.

Is there any chance that you provide us with the data to try to reproduce the error?
Even if not, please describe the data and your setup in more detail (total size of data to write in gigabytes, average document size and structure, what secondary indexes you created...)

**Comment by pluma** [comment] 2016-04-15 09:44
@riverdusty If you're using Foxx with Model and Repository, try using raw schemas and collections.

You can pass a joi schema directly to the `bodyParam` method instead of a Foxx Model and it will pass on the validated object instead of a Foxx Model instance. You can then write that to the collection directly (if you don't know how to get a reference to the collection, just use the `collection` property of the Foxx Repository instance).

When using Model and Repository there is some overhead wrapping and unwrapping the document as it travels through Foxx. That shouldn't explain the magnitude of slowdown you're experiencing but it might magnify the underlying performance problem.

**Comment by riverdusty** [comment] 2016-04-15 11:08
Interesting. 
Mac OS X My Virtual Memory (From the Web Interface) sits around 6GB.
Windows VM sits at 0.2GB.

I just ran this against ArangoDB 2.8.7 on Windows Server 2008r2 x64.
It didn't do a time out and my 15-min-avg Virtual Size was 0.18.

Also, where is my prevous message? (sigh, I blame South African Internet).

Anyway, @pluma I don't get a slowdown. I get a sudden stop. One second posting 300 docs, next nothing, just stops. Always around 16000 document mark, which leads me to think its Virtual Size limit.

@Simran-B data is what I posted in the first post, with only key's changing.
Its a standard edge collection:
ID 	Type 	Unique 	Sparse 	Selectivity Est. 	Fields
0 	primary 	true 	false 	100.00% 	_key
3730254115 	edge 	false 	false 	100.00% 	_from, _to

The behaviour happens with a document collection as well, so I doubt its a collection specific thing.

Figures from the Windows setup that completed.
Type 	Count 	Size 	Info
Datafiles 	1 	32 MB 	
Journals 	1 	32 MB 	
Compactors 	0 	0 B 	
Shape files 	0 	0 B 	
Indexes 	1 	4.4 MB 	
Type 	Count 	Info
Shapes 	2130 	
Attributes 	8 	
Uncollected 	12737 	
References 	0 	
Type 	Count 	Size 	Deletion 	Info
Alive 	46095 	60.05 MB 	- 	
Dead 	0 	0 B 	0 	

58832 document(s)

**Comment by riverdusty** [comment] 2016-04-15 16:32
Figures from the same collection with the same docs (Identicle) but on the Mac.

Type 	Count 	Size 	Info
Datafiles 	2 	64 MB 	
Journals 	1 	32 MB 	
Compactors 	0 	0 B 	
Shape files 	0 	0 B 	
Indexes 	1 	4.4 MB 	
Type 	Count 	Info
Shapes 	2234 	
Attributes 	8 	
Uncollected 	6866 	
References 	0 	
Type 	Count 	Size 	Deletion 	Info
Alive 	51966 	67.78 MB 	- 	
Dead 	0 	0 B 	0

**Comment by pluma** [comment] 2016-04-25 15:55
I've added a dummy app based on the description: [foxxapp1803.zip](https://github.com/arangodb/arangodb/files/234901/foxxapp1803.zip)

**Comment by pluma** [comment] 2016-06-17 13:18
Have you been able to reproduce this issue with ArangoDB 3.0.0-rc2? We haven't been able to reproduce the problem with the provided dummy service so I'm not sure whether the underlying issue is still present.

**Comment by khamin** [comment] 2016-12-05 13:14
Hi,

seems I got the same issue on 3.1.3 (both brew and official packages).

**Comment by dothebart** [comment] 2020-09-01 10:32
This was related to the MMFiles storage engine, which isn't supported anymore. 
Closing.

**Closed by dothebart** 2020-09-01 10:32 UTC
Labels: 1 Bug, 3 Foxx, 4 MacOSX, performance
