### ISSUE TITLE
Executing AQL using java driver on an index returns null

### ISSUE THREAD

**Issue by srini6teen** [arangodb/arangodb#2137] opened 2016-11-01 12:27 UTC
Hi, 
I am using the Java driver 4.0.0 and DB version 3.1. When I try to query, using FILTER on any of the index, the ArangoCursor returns with a  null element. Tried using Vpack and POJO. Neither of them work.

**Comment by mpv1989** [comment] 2016-11-02 10:02
duplicate of [https://github.com/arangodb/arangodb-java-driver/issues/66](https://github.com/arangodb/arangodb-java-driver/issues/66)

**Closed by mpv1989** 2016-11-02 10:02 UTC
