### ISSUE TITLE
ArangoDB keeps restarting while executing query

### ISSUE THREAD

**Issue by deiks** [arangodb/arangodb#12142] opened 2020-07-07 07:25 UTC
## My Environment

* __ArangoDB Version__:        3.6.4
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:        Debian 10
* __Total RAM in your machine__:        16Gb
* __Disks in use__:        SSD
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

        ....

	FOR tct IN combinations_tags
		FILTER tct._to == combination_props._id
                FOR t IN 0..255 INBOUND tct._from tags_tags 
					
			//	return t /*
			COLLECT combs = combination_props._id, 
					domains = combination_props.domains,
					tag = t._id 
											
											
			return domains /*
        
        ......

__AQL explain (if applicable)__:

This is explain WITH collect path:

```
 31   IndexNode                      360         - FOR tct IN tags_combinations_tags   /* edge index scan, index only, projections: `_from` */    
 19   CalculationNode                360           - LET #25 = tct.`_from`   /* attribute expression */   /* collections used: tct : tags_combinations_tags */
 20   TraversalNode       63546690272450           - FOR t  /* vertex */ IN 0..255  /* min..maxPathDepth */ INBOUND #25 /* startnode */  tags_tags_tags
 23   CalculationNode     63546690272450             - LET #33 = t.`_id`   /* attribute expression */
 24   CollectNode         50837352217960             - COLLECT combs = #29, domains = #31, tag = #33   /* hash */
 28   SortNode            50837352217960             - SORT combs ASC, domains ASC, tag ASC   /* sorting strategy: standard */
 34   SubqueryEndNode     50837352217960       - RETURN  domains ) /* subquery end */
```

and this is WITHOUT:

```
 28   SubqueryStartNode               36       - LET comb_users = ( /* subquery begin */
 15   CalculationNode                 36         - LET combination_props = DOCUMENT(tec.`_from`)   /* simple expression */   /* collections used: tec : tags_entities_combinations */
 26   IndexNode                      360         - FOR tct IN tags_combinations_tags   /* edge index scan, index only, projections: `_from` */    
 19   CalculationNode                360           - LET #22 = tct.`_from`   /* attribute expression */   /* collections used: tct : tags_combinations_tags */
 20   TraversalNode       63546690272450           - FOR t  /* vertex */ IN 0..255  /* min..maxPathDepth */ INBOUND #22 /* startnode */  tags_tags_tags
 29   SubqueryEndNode     63546690272450       - RETURN  t ) /* subquery end */
```

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__: I'm having issue with part of query and in my case if I uncomment *return t* I will get output normally, but if try to *return domains*, or any other collected group, then Arangodb restarts.

And the same happening even after setting: vm.max_map_count

__Expected result__:

**Comment by Simran-B** [comment] 2020-08-12 12:09
@deiks How deep is your graph? The traversal max depth is pretty high. Can you check whether the server gets killed by OS because of an out of memory issue?

**Comment by deiks** [comment] 2020-08-31 07:57
Hi @Simran-B  

Not sure, downgraded to 3.5.5 and it worked but it worked as well (with 3.6) on other servers and local environments. So only this server was problematic.

**Comment by Simran-B** [comment] 2020-09-09 10:57
@deiks Do you mean the physical server or the specific deployment? Does it also restart on the same hardware if you restore a dump into a fresh instance?

**Comment by Simran-B** [comment] 2020-09-23 11:17
Closing as it is apparently not reproducible.

**Closed by Simran-B** 2020-09-23 11:17 UTC
Labels: 1 Analyzing, 3 AQL, 3 Optimizer, Waiting User Reply
