### ISSUE TITLE
ArangoDB 2.3.1 won't store 2^62 or 10^18 - 1 correctly

### ISSUE THREAD

**Issue by morsdatum** [arangodb/arangodb#1185] opened 2014-12-12 10:25 UTC
Try to store a document with big number as 10^18 - 1 or 2^62 , the server responded the query of that document with values of 1000000000000000000 & 4611686018427388000  in regard to excepted values of 999999999999999999 and 4611686018427387904. Either results query thru python driver or ArangoDB server web interface.

**Comment by baslr** [comment] 2015-01-14 13:45
@jsteemann any update regarding the number is differently returned at different ArangoDB API endpoints?

**Comment by baslr** [comment] 2015-01-20 14:37
this affects also ArangoDB 2.4
![bildschirmfoto 2015-01-20 um 14 32 01](https://cloud.githubusercontent.com/assets/1494154/5818962/b6c0663a-a0b1-11e4-8ef8-5da5178bc368.png)
![bildschirmfoto 2015-01-20 um 14 32 13](https://cloud.githubusercontent.com/assets/1494154/5818966/c30511c0-a0b1-11e4-9c9b-6b226dc96e8e.png)

**Comment by baslr** [comment] 2015-01-30 19:41
@jsteemann @fceller dont want to annoy, but any update?
This is a read consistency issue.

**Comment by jsteemann** [comment] 2015-02-03 09:45
This has the same root cause as issue #1230.

**Comment by jsteemann** [comment] 2015-02-24 11:17
The *it returns different floats* issue should be fixed in 2.5.

The limited precision of IEEE754 binary floating point numbers will remain. That means there still won't be arbitrary precision for values such as `10^18 - 1` (which will still have the same representation as `10^18`).

**Closed by jsteemann** 2015-02-24 11:17 UTC
Labels: Bug, core
