### ISSUE TITLE
Support TLS 1.2 in HTTP client

### ISSUE THREAD

**Issue by oastashev** [arangodb/arangodb#1974] opened 2016-08-01 11:13 UTC
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [x] 3.0.3

On this operating system:
- [x] Linux (Ubuntu 14.04)
  - [x] docker - official docker library
### Foxx

These are the steps to reproduce:

run script

```
var request = require('@arangodb/request');
var response = request.get('https://api.passslot.com/v1');
console.log(response);
```

The following problem occurs: 

```
{
  "statusCode": 500,
  "status": 500,
  "message": "Could not connect to 'http+ssl://api.passslot.com:443' 'SSL: during SSL_connect: 0 - Success'",
  "headers": {}
}
```

Instead I would be expecting: 
Success status

NOTE: node's (v6.3.1)  **unirest** (0.5.0) works fine.

**Comment by dothebart** [comment] 2016-08-01 12:40
most probably https://github.com/arangodb/arangodb/commit/4a7e54e215e13b12792f1a01d25795455e708071 needs to be adopted for the http client in order to get this working.

Side note @oastashev due to the synchroneous nature of FOXX, you should think twice before doing http requests from FOXX to external services.

**Comment by dothebart** [comment] 2016-08-05 09:42
Wireshark says: ArangoDB does TLS 1.0; Curl does TLS 1.2. have to find out how to initialize openssl so it starts the TLS 1.2 connection negotiation.

**Comment by oastashev** [comment] 2016-08-08 09:45
Tested with 3.0.4 without success :( Got the same error.

Side note @dothebart Foxx is just example. Mentioned code is run as test script... 

For our project connectivity with third-party service is business critical feature. At the moment we have to use http bridge written on node+unirest.

**Comment by dothebart** [comment] 2016-08-08 11:17
thats been expected, as we didn't find a fix yet. The OpenSSL API documentation is not all clear what we're doing wrong here. So far trial & error didn't bring a valid solution.

**Comment by solisoft** [comment] 2016-09-03 18:34
+1 for TLS1.2 ! Stripe refuse to Work on version < 1.2

**Comment by irelandpaul** [comment] 2016-10-22 00:29
Is there any update on this? I was in the process of building my services with Foxx then looked this up and saw 1.2 was not supported. Now I'm stopped as this is a breaking issue for us.

**Comment by solisoft** [comment] 2016-10-22 07:31
@irelandpaul my work around was to use an https rails app as proxy ... so foxx do a https request on my rails app, my rails app do a https request to stripe and return son to my foxx service

**Comment by jsteemann** [comment] 2016-11-17 13:43
I debugged this down to the actual SSL connect. The problem is that the SSL_connect() to the specified endpoint fails with a return value of 0. Debugging further it seems that SSL_connect() fails with OpenSSL-internal error "SSL_ERROR_SYSCALL". From its docs:

           Some I/O error occurred.  The OpenSSL error queue may contain more
           information on the error.  If the error queue is empty (i.e.
           ERR_get_error() returns 0), ret can be used to find out more about
           the error: If ret == 0, an EOF was observed that violates the
           protocol.  If ret == -1, the underlying BIO reported an I/O error
           (for socket I/O on Unix systems, consult errno for details).

The problem is that `ret == 0` here, which just means `an EOF was observed that violates the protocol`.
I tried with various ciphers and SSL options, but to no avail yet.

strace-ing the connect just shows that after the initial handshake (write -> read) the connection is closed.
When doing the same with curl, this does not happen. curl sends a different handshake to the server though. The handshake data is binary of course, so it's unclear what the actual difference is.

**Comment by baslr** [comment] 2017-04-06 16:14
@oastashev Good news. I probably hunted down the cause why ArangoDB can't connect.

**Comment by baslr** [comment] 2017-04-11 11:14
@solisoft with ArangoDB v3.1.18 you can connect to stripe via TLS 1.2.

**Comment by solisoft** [comment] 2017-04-11 13:13
Great I'll have a look :) 👍

**Comment by sajeevpr** [comment] 2017-04-21 07:56
I tested this. But not working. Getting the below error.

Could not connect to http+ssl://host:port SSL: during SSL_connect: 0 - Success headers {}

Regards,
Sajeev

**Comment by jsteemann** [comment] 2017-04-21 08:15
@sajeevpr : how do you connect exactly? are you using the request module and which configuration/URL?

**Comment by sajeevpr** [comment] 2017-04-21 08:45
@jsteeman,  

  I am using like this.

const request = require("@arangodb/request");
var response = request({
      method:'get',
      url: 'https://host:8529/_db/db1/core',
      auth: {bearer: token}
});

Regards,
Sajeev

**Comment by baslr** [comment] 2017-04-21 08:57
@sajeevpr you are connection to arangod right? Can you share arangods ssl config?

**Comment by sajeevpr** [comment] 2017-04-21 09:01
@baslr,
    Yes.
Started Arangodb with--ssl.keyfile server.pem --ssl.protocol 5

Regards,
Sajeev

**Comment by baslr** [comment] 2017-04-21 09:03
Thanks. I will have a look later this day and report back.

**Comment by jsteemann** [comment] 2017-04-21 10:14
@baslr : thanks!

**Comment by baslr** [comment] 2017-04-21 20:46
@sajeevpr found the problem.

**Comment by baslr** [comment] 2017-04-21 20:46
Its actually funny because you can patch it by yourself in an JavaScript file :-)

**Comment by sajeevpr** [comment] 2017-04-26 04:03
Thank you

**Comment by dothebart** [comment] 2017-05-03 11:39
3.1.19 is available for download - closing. Feel free to comment if the issue persists.

**Closed by dothebart** 2017-05-03 11:39 UTC
Labels: 1 Feature, 3 Documentation
