### ISSUE TITLE
Unable to write in query editor in firefox developer edition

### ISSUE THREAD

**Issue by dilipvamsi** [arangodb/arangodb#5330] opened 2018-05-11 16:30 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [x] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [x] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

While I'm trying to write in the query editor in **Mozilla Firefox 61.0 (firefox-developer-edition)** the cursor was behaving weirdly and also writing random things.

That may be because of this error which is raised while I trying to type in the query editor.
```
 [Show/hide message details.] Error: Permission denied to access property "apply"[Learn More] libs.js:2:22631
trigger
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:2:22631
trigger/<
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:2:28484
each
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:1:21320
each
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:1:19255
trigger
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:2:28463
aa.fn[b]
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:3:15792
focus
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:21:27870
initAce/<
http://localhost:8529/_db/sample/_admin/aardvark/app.js:11:30652
d._signal
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:59:14273
this.onChange
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:62:26451
<anonymous> self-hosted:986:17 d._signal
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:59:14273
this.applyDelta
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:61:31059
this.remove
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:61:29579
this.remove
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:63:3087
this.remove
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:64:29054
exec
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:64:5851
g/<
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:63:25269
d._dispatchEvent
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:59:14150
this.exec
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:63:25618
this.$callKeyboardHandlers
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:59:26073
this.onCommandKey
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:59:26406
this.onCommandKey
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:64:25976
<anonymous> self-hosted:988:17 d
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:58:15967
b.addCommandKeyListener/<
http://localhost:8529/_db/sample/_admin/aardvark/libs.js:58:19329
```
Thanks,
Dilip Vamsi

**Comment by Simran-B** [comment] 2018-05-14 09:04
What exact version of ArangoDB and what OS are you using? I can't see that error in Firefox Dev. Ed. 61.0b4 (64-Bit) and everything functions as expected.

**Comment by dilipvamsi** [comment] 2018-05-15 13:14
Hi @Simran-B 
I'm using [manjaro linux](https://manjaro.org/)
I have installed arangodb using [arangodb aur](https://aur.archlinux.org/packages/arangodb/) which installs 3.3.8 version.
I'm using firefox-developer-edition 61.0b2-1 provided in manjaro repos.

Thanks,
Dilip Vamsi.

**Comment by hkernbach** [comment] 2018-08-07 11:01
No similiar issues have been reported in the latest months. Closing this issue for now since we could not reproduce it using the same ArangoDB version and browser.

**Closed by hkernbach** 2018-08-07 11:01 UTC
Labels: 2 Cannot Reproduce, 3 AQL, 3 UI
