### ISSUE TITLE
arangodb tool used to create cluster, doesn't yield control to shell 

### ISSUE THREAD

**Issue by hisoumit** [arangodb/arangodb#3895] opened 2017-12-05 13:22 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [*] 3.2
- [ ] self-compiled devel branch

Mode:
- [*] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [*] AWS
  - [ ] Azure
  - [*] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [*] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[*] I'm using graph features

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.
Objective is to create a arangod cluster using the tool arangodb:

Using Arangodb version : 3.2.6

Scenario 1:

1- In the master node :  run command  ' arangodb start '
2- In the slave nodes : run command ' arangodb start --starter.join <master_ip> '
3- Observe that the control is not yield back to the shell

Trace:
what actually happened:
arangodb start --starter.join 10.102.28.217
2017/12/05 05:13:11 Starting arangodb version 0.10.2, build 7f0affe in the background
2017/12/05 05:13:11 Waiting for starter API to be available...

Scenario 2:

1- In the master node :  run command  ' arangodb start '
2- In the slave nodes : run command ' arangodb start --starter.join <master_ip> & '
3- Observe that the control is not yield back to the shell, until you press Enter key for keyboard input.

Trace:
what actually happened:
arangodb start --starter.join 10.102.28.217 &
[1] 1864
root@centralmsvm:~# 2017/12/05 05:15:49 Starting arangodb version 0.10.2, build 7f0affe in the background
2017/12/05 05:15:49 Waiting for starter API to be available...

what you expected to happen:
The control should be yield back to the shell

**Comment by dothebart** [comment] 2017-12-05 14:05
Hi, 
the starter isn't meant to be used with DC/OS, its probably not what you did in first place, right?

**Comment by dothebart** [comment] 2017-12-05 14:10
In general you want to say that https://github.com/arangodb-helper/arangodb#starting--stopping-in-detached-mode doesn't work for you?

**Comment by hisoumit** [comment] 2017-12-07 07:22
Using the below cloud image:
3.13.0-116-generic
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

**Comment by hisoumit** [comment] 2017-12-07 07:23
The arangodb starter tool works but it is expected that the control should be released and the tool should run in the background, but that is not happening.

**Comment by dothebart** [comment] 2017-12-07 14:40
Hi, 
did you specify the options mentioned in the documentation I've posted?

**Comment by sebastienpattyn93** [comment] 2017-12-15 14:03
I'm having the exact same issue. I am able to make it work if I start it first(not as a backgroundprocess). Then stop it and restart it with `arangodb start --starter.join` . The problem is that we have to automate this so there is no manual interaction possible. 

I tried it with the `--starter.wait` but I still got the same issue

**Comment by hisoumit** [comment] 2018-02-06 02:28
@dothebart Tried out all options present in the documentation, also tried with latest arangodb , still the issue persists.

**Comment by hkernbach** [comment] 2018-02-22 17:30
@hisoumit @sebastienpattyn93 Yep it seems to be a bug. Running `arangodb start` with parameter `starter.join` is not putting the starter into background mode. Original issue in the arangodb starter repository here: https://github.com/arangodb-helper/arangodb/issues/112#issuecomment-367757379

**Comment by sleto-it** [comment] 2018-07-10 19:51
Hi all,

This bug has been fixed in the _Starter_ version 0.12.0, which is included in ArangoDB in version 3.3.11, and will be included in version 3.2.16 as well

Closing. Please let us know if the issue persists

Many thanks,

**Closed by sleto-it** 2018-07-10 19:51 UTC
Labels: 1 Bug, 1 Question, 3 Cluster, 3 Starter
