### ISSUE TITLE
Query import via UI does not seem to work when not in the _system database

### ISSUE THREAD

**Issue by neunhoef** [arangodb/arangodb#2596] opened 2017-06-16 18:57 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1

On this operating system:
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as whatever user
3) use database [ ] `_system` [x] other: 
4) click to import queries from a json document

The following problem occurs: Error message "Query error: queries could not be imported." without any further answer.
Instead I would be expecting: That it either works or I get told to go to the _system database instead.

**Comment by jsteemann** [comment] 2017-08-07 07:57
@hkernbach: has this issue been fixed in 3.2? If yes, please assign the "Fixed" label to this issue. Thanks!

**Comment by maxkernbach** [comment] 2017-08-09 11:19
The issue is fixed in 3.2. It was tested with different user/database than root/_system, authentication and cluster usage.

**Comment by jsteemann** [comment] 2017-08-11 09:30
3.2.1 has been released and is [available for download](https://www.arangodb.com/download-major/).

**Closed by jsteemann** 2017-08-11 09:30 UTC
Labels: 1 Bug, 2 Fixed, 3 Front-End
