### ISSUE TITLE
skip list index - Expecting type Array error when importing data

### ISSUE THREAD

**Issue by schroedingerdb** [arangodb/arangodb#2158] opened 2016-11-08 14:08 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.0.10

On this operating system:
- [ ] Linux 
  - [x] Ubuntu .deb

I'm issuing AQL via:
- [x] arangosh

Hello,

I have a problem with skiplist index.

Here my collection schema:
db._create('test-collection',{ waitForSync : true, numberOfShards: 6, shardKeys: ["_key"], journalSize: 536870912 })
db.test-collection.ensureIndex({ type: "skiplist", fields: [ "value1", "value2" ], sparse: false });

version 3.0.10
cluster mode with 3 nodes ( 3 x agent, 3 x database primary, 1 coordinator)
ubuntu14.04
MemTotal:       74223880 kB (per server)

```
$ ls -s /data.csv
file size: 54245168 (~52G) data.csv
```
I try to import my csv file many times (delete all data and start a fresh cluster setup) but after 42% I get this error:

```
$arangoimp --file /data.csv --type csv --collection test-collection --server.database test-db --server.endpoint
tcp://server1:8530 --on-duplicate ignore --server.password ""
Connected to ArangoDB 'http+tcp://server1:8530', version 3.0.10, database: 'test-
db', username: 'root'
----------------------------------------
database:
test-db
collection:
test-collection
create:
no
source filename:
/data.csv
file type:
csv
quote:
"
separator:
connect timeout:
5
request timeout:
1200
----------------------------------------
Starting CSV import...
2016-11-07T08:35:21Z [20518] INFO processed 1666416640 bytes (3%) of input file
2016-11-07T08:48:05Z [20518] INFO processed 3332833280 bytes (6%) of input file
2016-11-07T09:01:15Z [20518] INFO processed 4999249920 bytes (9%) of input file
2016-11-07T09:14:40Z [20518] INFO processed 6665666560 bytes (12%) of input file
2016-11-07T09:28:28Z [20518] INFO processed 8332083200 bytes (15%) of input file
2016-11-07T09:42:38Z [20518] INFO processed 9998499840 bytes (18%) of input file
2016-11-07T09:56:40Z [20518] INFO processed 11664883712 bytes (21%) of input file
2016-11-07T10:10:43Z [20518] INFO processed 13331300352 bytes (24%) of input file
2016-11-07T10:25:10Z [20518] INFO processed 14997716992 bytes (27%) of input file
2016-11-07T10:39:34Z [20518] INFO processed 16664133632 bytes (30%) of input file
2016-11-07T10:54:10Z [20518] INFO processed 18330550272 bytes (33%) of input file
2016-11-07T11:09:36Z [20518] INFO processed 19996966912 bytes (36%) of input file
2016-11-07T11:26:44Z [20518] INFO processed 21663350784 bytes (39%) of input file
2016-11-07T11:54:10Z [20518] INFO processed 23329767424 bytes (42%) of input file
2016-11-07T12:04:40Z [20518] ERROR error message:
Expecting type Array (exception location:
/usr/src/packages/BUILD/arangod/HttpServer/HttpHandler.cpp:157).
Please report this error to arangodb.com
```
When I use persistent index then it works.

Regards, Jens

**Comment by schroedingerdb** [comment] 2016-11-08 14:19
My hope was that I forget to increase some skiplist index limits or settings.

**Comment by schroedingerdb** [comment] 2016-11-08 15:32
I tried it again and have some more details. See my attachments.
![skiplist-bug-import-log](https://cloud.githubusercontent.com/assets/5195686/20104601/e48260a4-a5ce-11e6-98da-118a0a52c770.png)
![skiplist-bug-server-monitoring](https://cloud.githubusercontent.com/assets/5195686/20104815/a9b3bfbc-a5cf-11e6-807d-47fe7911a25f.png)

What you can see here is the mem_free value. It is some minutes before the error comes nearly zero,
but really free ram is ~28GB per node. So my system has enough RAM to store/import more data.

```
$free -m
             total       used       free     shared    buffers     cached
Mem:         64420      64158        262          0         72      27902
-/+ buffers/cache:      36183      28236
Swap:         7695       1117       6578
```

I don't know what the problem is.

What I also recognize is that one sever has little bit less RAM than the rest.
```
server blue:   MemTotal:       74223880 kB
server red:    MemTotal:       65966348 kB
server yellow: MemTotal:       74223880 kB
```

**Comment by fceller** [comment] 2016-11-08 15:52
It could be some timeout problem with a very misleading error message. To identify the problem, it would be helpful, if you could do one of the following experiments:

(a) Do not create the skip-list before importing but after importing. Could you note the memory usage after the import and after the ensureIndex?

(b) Start "arangoimp" with `--server.request-timeout 7200`

That should help us to narrow down the problem.

**Comment by schroedingerdb** [comment] 2016-11-08 15:58
Thank you Frank. I will test (a) and (b) and post my results later ..

**Comment by jsteemann** [comment] 2016-11-09 07:13
Probably same root cause as #2133

**Comment by schroedingerdb** [comment] 2016-11-09 08:27
(a) 
data completely imported without skiplist index

```
root@red:~# free -m
             total       used       free     shared    buffers     cached
Mem:         64420      64111        309          0        212      38477
-/+ buffers/cache:      25421      38999
Swap:         7695       1065       6630


root@blue:~# free -m
             total       used       free     shared    buffers     cached
Mem:         72484      72113        370          0        204      46493
-/+ buffers/cache:      25415      47068
Swap:         7695        984       6711


root@yellow:~# free -m
             total       used       free     shared    buffers     cached
Mem:         72484      72216        268          0        257      46626
-/+ buffers/cache:      25332      47151
Swap:         7695       1312       6383
```

**Comment by fceller** [comment] 2016-11-09 11:42
Ok, that is good for the beginning. There should also be free space for the index. Let's see how the situation looks like after the index creation.

**Comment by jsteemann** [comment] 2016-11-09 14:16
Just fixed an error in 3.0 that led to the "Expecting type Array" error message, which is totally misleading for end users. Now a proper error message will be displayed when the import fails in case of inter-server communication timeouts etc. Still it is unclear why the import aborts at some point.

**Comment by sm-jens-schroeder** [comment] 2016-11-09 15:37
I changed my github account from @schroedingerdb to @sm-jens-schroeder

Index creation is still running

```
root@red:~# free -m
             total       used       free     shared    buffers     cached
Mem:         64420      64153        266          0        156      37639
-/+ buffers/cache:      26357      38063
Swap:         7695       1620       6075

root@blue:~# free -m
             total       used       free     shared    buffers     cached
Mem:         72484      72209        274          0         53      33205
-/+ buffers/cache:      38950      33533
Swap:         7695       6705        990

root@yellow:/var/lib# free -m
             total       used       free     shared    buffers     cached
Mem:         72484      72186        297          0        208      45793
-/+ buffers/cache:      26184      46299
Swap:         7695       1811       5884
```

**Comment by sm-jens-schroeder** [comment] 2016-11-10 08:05
still running
100% swapping
and some errors

```
$tail -f /mnt/data01/arangodb-log/arangodb-db-primary.log
2016-11-10T02:05:23Z [8405] ERROR {replication} insertLocal: dropping follower DBServer001 for shard s100018
2016-11-10T02:24:13Z [8405] ERROR {replication} insertLocal: dropping follower DBServer001 for shard s100021

$tail -f /mnt/data01/arangodb-log/arangodb-coord.log
2016-11-09T23:04:04Z [8477] WARNING {queries} slow query: 'FOR s in @@collection FILTER s.time >= @start  FILTER s.clusterId == @clusterId SORT s.time desc LIMIT 1 RETURN s', took: 13.440424
2016-11-09T23:05:43Z [8477] WARNING {queries} slow query: 'FOR s in @@collection FILTER s.time >= @start  FILTER s.clusterId == @clusterId SORT s.time desc LIMIT 1 RETURN s', took: 12.555045
```

```
root@red:~# free -m
             total       used       free     shared    buffers     cached
Mem:         64420      64148        271          0        110      29609
-/+ buffers/cache:      34428      29992
Swap:         7695       7695          0

root@blue:~# free -m
             total       used       free     shared    buffers     cached
Mem:         72484      72200        284          0        100      29274
-/+ buffers/cache:      42824      29659
Swap:         7695       7695          0

root@yellow:/var/lib# free -m
             total       used       free     shared    buffers     cached
Mem:         72484      72142        341          0        129      31997
-/+ buffers/cache:      40016      32468
Swap:         7695       7695          0
```

**Comment by sm-jens-schroeder** [comment] 2016-11-10 08:42
just to clarify. My use case is: 
import a ~52GB csv file to a 200GB RAM cluster with skiplist index

column 1 => unsigned int
column 2 => unsigned bigint as string
cloumn 3 => unsigned int
```
$head -n5 data.csv
1163939289,"10138960510791864749",76
1163939289,"4697395135255654639",76
1163939289,"13652140458695133512",76
1163939289,"11977766875489981563",76
1163939289,"5855928334991370181",76
```
schema:
```
db._create('test-collection',{ waitForSync : true, numberOfShards: 6, shardKeys: ["_key"], journalSize: 536870912 })
db.test-collection.ensureIndex({ type: "skiplist", fields: [ "value1", "value2" ], sparse: false });
```

**Comment by sm-jens-schroeder** [comment] 2016-11-10 15:34
Hey,

I think I will stop the test, because I'm running out of time. 
1 Day waiting for the index creation is unfortunately too long for me. 
And there are some other reasons to stop testing the skiplist index.

@fceller @jsteemann Is it okay when I close the issue?

Regards, Jens

**Comment by jsteemann** [comment] 2016-11-10 15:50
@sm-jens-schroeder : I would prefer leaving this issue open. Of course you don't need to continue looking into this issue and try reproducing it anymore. 
But we should leave the issue open because something is not working as expected and we still need to fix it.
 
Thanks for the time you spent analyzing this!

**Comment by sm-jens-schroeder** [comment] 2016-11-10 15:56
Ok, I will let it open and thanks also to you!

**Comment by jsteemann** [comment] 2016-11-17 09:17
Seems like a duplicate of #2078

**Comment by neunhoef** [comment] 2017-03-01 10:14
Do we know whether this problem persists in 3.1? Do we have the data to try it out?

**Comment by dothebart** [comment] 2017-07-21 11:33
I'm closing this due to inactivity. 
Nb, We're pleased to anounce that ArangoDB 3.2 containing lots of improvements to the clustering.

**Closed by dothebart** 2017-07-21 11:33 UTC
Labels: 1 Bug, 3 Cluster, 3 Core
