### ISSUE TITLE
build Binary install   arangodb.sh  install error

### ISSUE THREAD

**Issue by zhenruyan** [arangodb/arangodb#3179] opened 2017-08-31 18:19 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [x] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [x] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 
![deepinscreenshot_select-area_20170901020912](https://user-images.githubusercontent.com/9253251/29938206-9b05a708-8eba-11e7-9e90-2720f85292d5.png)

I compiled the general binary installation package and wanted to install it on any Linux system

![deepinscreenshot_deepin-terminal_20170901021301](https://user-images.githubusercontent.com/9253251/29938367-1efdbe6a-8ebb-11e7-9187-8741299bd0c6.png)

After installation

![deepinscreenshot_select-area_20170901021409](https://user-images.githubusercontent.com/9253251/29938449-5231cac4-8ebb-11e7-8c42-434b8063e856.png)

Enter directory

![deepinscreenshot_deepin-terminal_20170901021521](https://user-images.githubusercontent.com/9253251/29938483-7186fcdc-8ebb-11e7-9bc2-0959b9dd3fd4.png)

You can see that it has been installed in the home directory (not installed by the root user)

![deepinscreenshot_select-area_20170901021839](https://user-images.githubusercontent.com/9253251/29938602-ec9b2a4c-8ebb-11e7-8645-21dfc364e057.png)

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by dothebart** [comment] 2017-09-01 08:29
Hi, you can edit arangod.conf and specify the correct js directory path there.

**Comment by zhenruyan** [comment] 2017-09-01 11:49
mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make package


Multiple packages will be generated

What I want is to generate generic binary packages

**Comment by zhenruyan** [comment] 2017-09-01 12:00
Thank you for your prompt to successfully install and run
![deepinscreenshot_deepin-terminal_20170901195751](https://user-images.githubusercontent.com/9253251/29968796-e0094a90-8f4f-11e7-9cc5-5986d44002ea.png)

Can I get an official license to download a generic installation package?

**Comment by dothebart** [comment] 2017-09-01 12:03
The best way to achieve this is to use a snap package, since its portable in its ecosystem.

**Comment by zhenruyan** [comment] 2017-09-01 12:09
I quite agree with you
But few people use snap in China
More people adapting to tar xvf
./bin runs in a way
And more convenient operation and maintenance

**Comment by dothebart** [comment] 2017-09-01 12:20
well, but that way you end up with links to wrong libc/openssl whatever libs, thus we don't provide this. 

You can however easily extract the tar from the distribution package of your choice:

    ar vx  /arangodb3-3.2.2-1_amd64.deb

Please note that you have to add the /etc files afterwards.

**Comment by zhenruyan** [comment] 2017-09-01 12:23
Thank you for reminding me

**Comment by dothebart** [comment] 2017-09-01 12:36
If you extract that tarball you've built everything will go to /usr/local, and the installation will work out of the box. 

If you want to do that in your home directory you have to edit the configuration file - which I think is fair enough.

**Comment by zhenruyan** [comment] 2017-09-01 12:52
Such is the case

I'm used to installing and running under ~/usr

**Comment by dothebart** [comment] 2017-09-01 13:30
I'd like to close this as duplicate of #1580. The configuration generated by the build process is accurate for a toplevel install and can be easily adjusted to work with a home directory based install.

**Closed by dothebart** 2017-09-01 13:30 UTC
