### ISSUE TITLE
How to fix these errors? when I use 3.1.4 docker image to setup a cluster, and use it to store a two shards graph, coordinator web get stuck...

### ISSUE THREAD

**Issue by brucejee** [arangodb/arangodb#2231] opened 2016-12-22 03:39 UTC
### Problem
How to fix these errors? when I use 3.1.4 docker image to setup a cluster, and use it to store a two shards graph. Coordinator web UI get stuck, I don't know how to fix this? Can you help me?
When I don't use shard I work ok first, but after 6 million docs import into a collection, i import more docs, it failed, I have 10 million docs.
I want to test read write performance when data reach 10 million docs.

### 192.168.1.81
2016-12-22T03:32:00Z [1] ERROR {cluster} ClusterComm::performRequests: got no answer from shard:s100021:/_db/_system/_api/collection/s100021/count with error 4
2016-12-22T03:32:00Z [1] ERROR Service "/_admin/aardvark" encountered error 500 while handling GET http://192.168.1.81/_db/_system/_admin/aardvark/statistics/short?count=2
2016-12-22T03:32:00Z [1] ERROR ArangoError: could not determine number of documents in collection (while optimizing plan)
2016-12-22T03:32:00Z [1] ERROR     at Error (native)
2016-12-22T03:32:00Z [1] ERROR     at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:81:16)
2016-12-22T03:32:00Z [1] ERROR     at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:90:45)
2016-12-22T03:32:00Z [1] ERROR     at computeStatisticsRaw (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:129:21)
2016-12-22T03:32:00Z [1] ERROR     at computeStatisticsShort (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:318:3)
2016-12-22T03:32:00Z [1] ERROR     at Route._handler (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:520:18)
2016-12-22T03:32:00Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:385:15)
2016-12-22T03:32:00Z [1] ERROR     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:9378:25
2016-12-22T03:32:00Z [1] ERROR     at Middleware.router.use (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:405:3)
2016-12-22T03:32:00Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:387:15)
2016-12-22T03:32:55Z [1] ERROR {cluster} ClusterComm::performRequests: got no answer from shard:s100021:/_db/_system/_api/collection/s100021/count with error 4
2016-12-22T03:32:55Z [1] ERROR Service "/_admin/aardvark" encountered error 500 while handling GET http://192.168.1.81/_db/_system/_admin/aardvark/statistics/short?count=2
2016-12-22T03:32:55Z [1] ERROR ArangoError: could not determine number of documents in collection (while optimizing plan)
2016-12-22T03:32:55Z [1] ERROR     at Error (native)
2016-12-22T03:32:55Z [1] ERROR     at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:81:16)
2016-12-22T03:32:55Z [1] ERROR     at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:90:45)
2016-12-22T03:32:55Z [1] ERROR     at computeStatisticsRaw (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:129:21)
2016-12-22T03:32:55Z [1] ERROR     at computeStatisticsShort (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:318:3)
2016-12-22T03:32:55Z [1] ERROR     at Route._handler (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:520:18)
2016-12-22T03:32:55Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:385:15)
2016-12-22T03:32:55Z [1] ERROR     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:9378:25
2016-12-22T03:32:55Z [1] ERROR     at Middleware.router.use (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:405:3)
2016-12-22T03:32:55Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:387:15)

2016-12-22T03:33:30Z [1] ERROR {cluster} ClusterComm::performRequests: got no answer from shard:s100018:/_db/_system/_api/collection/s100018/count with error 4
2016-12-22T03:33:30Z [1] WARNING catch error in historian: ArangoError: could not determine number of documents in collection (while optimizing plan)\n    at Error (native)\n    at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:81:16)\n    at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:90:45)\n    at lastEntry (/usr/share/arangodb3/js/server/modules/@arangodb/statistics.js:109:19)\n    at Object.exports.historian (/usr/share/arangodb3/js/server/modules/@arangodb/statistics.js:456:19)\n    at eval (eval at undefined, <anonymous>:3:54)\n    at eval (eval at undefined, <anonymous>:3:70)
2016-12-22T03:34:25Z [1] ERROR {cluster} ClusterComm::performRequests: got no answer from shard:s100021:/_db/_system/_api/collection/s100021/count with error 4
2016-12-22T03:34:25Z [1] ERROR Service "/_admin/aardvark" encountered error 500 while handling GET http://192.168.1.81/_db/_system/_admin/aardvark/statistics/short?count=2
2016-12-22T03:34:25Z [1] ERROR ArangoError: could not determine number of documents in collection (while optimizing plan)
2016-12-22T03:34:25Z [1] ERROR     at Error (native)
2016-12-22T03:34:25Z [1] ERROR     at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:81:16)
2016-12-22T03:34:25Z [1] ERROR     at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:90:45)
2016-12-22T03:34:25Z [1] ERROR     at computeStatisticsRaw (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:129:21)
2016-12-22T03:34:25Z [1] ERROR     at computeStatisticsShort (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:318:3)
2016-12-22T03:34:25Z [1] ERROR     at Route._handler (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:520:18)
2016-12-22T03:34:25Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:385:15)
2016-12-22T03:34:25Z [1] ERROR     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:9378:25
2016-12-22T03:34:25Z [1] ERROR     at Middleware.router.use (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:405:3)
2016-12-22T03:34:25Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:387:15)
2016-12-22T03:34:34Z [1] ERROR {cluster} ClusterComm::performRequests: got no answer from shard:s100021:/_db/_system/_api/collection/s100021/count with error 4
2016-12-22T03:34:35Z [1] ERROR JavaScript exception in file '/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js' at 81,16: ArangoError 1478: could not determine number of documents in collection (while optimizing plan)
2016-12-22T03:34:35Z [1] ERROR !  var result = AQL_EXECUTE(this._query, this._bindVars, opts);
2016-12-22T03:34:35Z [1] ERROR !  

### 192.168.1.76
2016-12-22T03:30:11Z [1] ERROR {cluster} ClusterComm::performRequests: got no answer from shard:s100018:/_db/_system/_api/collection/s100018/count with error 4
2016-12-22T03:30:11Z [1] WARNING catch error in historian: ArangoError: could not determine number of documents in collection (while optimizing plan)\n    at Error (native)\n    at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:81:16)\n    at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:90:45)\n    at lastEntry (/usr/share/arangodb3/js/server/modules/@arangodb/statistics.js:109:19)\n    at Object.exports.historian (/usr/share/arangodb3/js/server/modules/@arangodb/statistics.js:456:19)\n    at eval (eval at undefined, <anonymous>:3:54)\n    at eval (eval at undefined, <anonymous>:3:70)
2016-12-22T03:30:21Z [1] ERROR Couldn't read statistics response: undefined
2016-12-22T03:30:21Z [1] ERROR Service "/_admin/aardvark" encountered error 500 while handling GET http://192.168.1.76:18531/_db/_system/_admin/aardvark/statistics/coordshort
2016-12-22T03:30:21Z [1] ERROR SyntaxError: Unexpected token u in JSON at position 0
2016-12-22T03:30:21Z [1] ERROR     at Object.parse (native)
2016-12-22T03:30:21Z [1] ERROR     at coordinators.map.e (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:504:19)
2016-12-22T03:30:21Z [1] ERROR     at Array.map (native)
2016-12-22T03:30:21Z [1] ERROR     at Route._handler (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:499:39)
2016-12-22T03:30:21Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:385:15)
2016-12-22T03:30:21Z [1] ERROR     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:9378:25
2016-12-22T03:30:21Z [1] ERROR     at Middleware.router.use (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:405:3)
2016-12-22T03:30:21Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:387:15)
2016-12-22T03:30:21Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
2016-12-22T03:30:21Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
2016-12-22T03:30:31Z [1] ERROR Couldn't read statistics response: undefined
2016-12-22T03:30:31Z [1] ERROR Service "/_admin/aardvark" encountered error 500 while handling GET http://192.168.1.76:18531/_db/_system/_admin/aardvark/statistics/coordshort
2016-12-22T03:30:31Z [1] ERROR SyntaxError: Unexpected token u in JSON at position 0
2016-12-22T03:30:31Z [1] ERROR     at Object.parse (native)
2016-12-22T03:30:31Z [1] ERROR     at coordinators.map.e (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:504:19)
2016-12-22T03:30:31Z [1] ERROR     at Array.map (native)
2016-12-22T03:30:31Z [1] ERROR     at Route._handler (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:499:39)
2016-12-22T03:30:31Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:385:15)
2016-12-22T03:30:31Z [1] ERROR     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:9378:25
2016-12-22T03:30:31Z [1] ERROR     at Middleware.router.use (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:405:3)
2016-12-22T03:30:31Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:387:15)
2016-12-22T03:30:31Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
2016-12-22T03:30:31Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
2016-12-22T03:31:25Z [1] ERROR {cluster} ClusterComm::performRequests: got no answer from shard:s100005:/_db/_system/_api/collection/s100005/count with error 4
2016-12-22T03:31:25Z [1] ERROR {cluster} ClusterComm::performRequests: got no answer from shard:s100005:/_db/_system/_api/collection/s100005/count with error 4
2016-12-22T03:31:25Z [1] ERROR {cluster} ClusterComm::performRequests: got no answer from shard:s100005:/_db/_system/_api/collection/s100005/count with error 4
2016-12-22T03:31:35Z [1] ERROR Couldn't read statistics response: undefined
2016-12-22T03:31:35Z [1] ERROR Service "/_admin/aardvark" encountered error 500 while handling GET http://192.168.1.76:18531/_db/_system/_admin/aardvark/statistics/coordshort
2016-12-22T03:31:35Z [1] ERROR SyntaxError: Unexpected token u in JSON at position 0
2016-12-22T03:31:35Z [1] ERROR     at Object.parse (native)
2016-12-22T03:31:35Z [1] ERROR     at coordinators.map.e (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:504:19)
2016-12-22T03:31:35Z [1] ERROR     at Array.map (native)
2016-12-22T03:31:35Z [1] ERROR     at Route._handler (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:499:39)
2016-12-22T03:31:35Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:385:15)
2016-12-22T03:31:35Z [1] ERROR     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:9378:25
2016-12-22T03:31:35Z [1] ERROR     at Middleware.router.use (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:405:3)
2016-12-22T03:31:35Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:387:15)
2016-12-22T03:31:35Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
2016-12-22T03:31:35Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:383:7)

**Comment by brucejee** [comment] 2016-12-22 04:09
I change batch import size from 50 to 10, web ui can response now.

**Comment by brucejee** [comment] 2016-12-22 05:25
Oh, my god, the same problem after i import , every thing get stuck, not only the web UI but also the import process. I think the cluster is not mature now. Not ready for production.

When i stop the import process, this web ui recover for a few minutes, it's not a good experience.

![image](https://cloud.githubusercontent.com/assets/5820173/21415998/12261a58-c84a-11e6-83e8-1573615e62fd.png)

**Comment by brucejee** [comment] 2016-12-22 06:11
So many errors, i don't know what's wrong? I have no idea to fix it.

2016-12-22T06:09:55Z [1] ERROR Service "/_admin/aardvark" encountered error 500 while handling GET http://192.168.1.76:18531/_db/_system/_admin/aardvark/statistics/coordshort
2016-12-22T06:09:55Z [1] ERROR SyntaxError: Unexpected token u in JSON at position 0
2016-12-22T06:09:55Z [1] ERROR     at Object.parse (native)
2016-12-22T06:09:55Z [1] ERROR     at coordinators.map.e (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:504:19)
2016-12-22T06:09:55Z [1] ERROR     at Array.map (native)
2016-12-22T06:09:55Z [1] ERROR     at Route._handler (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:499:39)
2016-12-22T06:09:55Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:385:15)
2016-12-22T06:09:55Z [1] ERROR     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:9378:25
2016-12-22T06:09:55Z [1] ERROR     at Middleware.router.use (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:405:3)
2016-12-22T06:09:55Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:387:15)
2016-12-22T06:09:55Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
2016-12-22T06:09:55Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
2016-12-22T06:09:55Z [1] ERROR Couldn't read statistics response: undefined
2016-12-22T06:09:55Z [1] ERROR Service "/_admin/aardvark" encountered error 500 while handling GET http://192.168.1.76:18531/_db/_system/_admin/aardvark/statistics/coordshort
2016-12-22T06:09:55Z [1] ERROR SyntaxError: Unexpected token u in JSON at position 0
2016-12-22T06:09:55Z [1] ERROR     at Object.parse (native)
2016-12-22T06:09:55Z [1] ERROR     at coordinators.map.e (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:504:19)
2016-12-22T06:09:55Z [1] ERROR     at Array.map (native)
2016-12-22T06:09:55Z [1] ERROR     at Route._handler (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:499:39)
2016-12-22T06:09:55Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:385:15)
2016-12-22T06:09:55Z [1] ERROR     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:9378:25
2016-12-22T06:09:55Z [1] ERROR     at Middleware.router.use (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/statistics.js:405:3)
2016-12-22T06:09:55Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:387:15)
2016-12-22T06:09:55Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:383:7)
2016-12-22T06:09:55Z [1] ERROR     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:383:7)

**Comment by brucejee** [comment] 2016-12-22 07:08
**I have to give up to test cluster, I have spent a week, there is no result, so sad.**

**Comment by brucejee** [comment] 2016-12-22 08:14
What's wrong with this? I have only one instance now.
![image](https://cloud.githubusercontent.com/assets/5820173/21419241/83d4a9f0-c861-11e6-81dd-ccfd4979a010.png)
![image](https://cloud.githubusercontent.com/assets/5820173/21419285/b5666d96-c861-11e6-91d8-e5162e3faefc.png)

**Comment by m0ppers** [comment] 2017-01-12 13:00
This is not supposed to happen.

We are currently analysing your problem. We were finally able to reproduce your situation at least partly in one of our test setups. However the bug seems to be buried deep inside arangodb and it is not easily reproducable. Analysing the bug will take some time.

Thanks for your report! We had holiday season. Sorry for coming back to you so late.

**Comment by brucejee** [comment] 2017-01-13 06:20
The problem is the same as issue [2265](https://github.com/arangodb/arangodb/issues/2265)?

**Comment by m0ppers** [comment] 2017-02-01 10:16
We are currently preparing a 3.1.10 release containing numerous fixes for cluster problems including this one. We expect a release by the end of the week or so. Your other issues were also addressed. Hopefully we found everything :)

**Comment by m0ppers** [comment] 2017-02-06 09:30
Could you retry with the just released 3.1.10 release?

**Comment by brucejee** [comment] 2017-02-06 13:23
No,  we have Spring Festival, I will retry later and report back.

**Comment by castiel** [comment] 2017-02-16 10:47
I had the same issue(and some others) with 3.1.9 and 3.1.10 helped resolve it.

**Comment by neunhoef** [comment] 2017-03-01 10:05
Seems to be fixed by 3.1.10 and beyond.

**Closed by neunhoef** 2017-03-01 10:05 UTC
Labels: 1_Bug, cluster
