### ISSUE TITLE
ArangoDB 3.1.11 cluster crashing under load

### ISSUE THREAD

**Issue by aznwarmonkey** [arangodb/arangodb#2329] opened 2017-02-25 11:11 UTC
Currently I have a Spark Streaming application leveraging  java arangodb driver V4.10 to do ingestions to an Arango cluster V3.1.11.  I noticed that under load, my arango cluster crashes.  Below is the details.  I have tried insertDocuments and importDocuments which yielded the same issue.  Do you guys know what could be causing the error and how to address it?

```bash
2017-02-25T10:54:42Z [23648] ERROR synchronizeOneShard: long call to syncCollection for shard s5100370 {"barrierId":"10395295","lastLogTick":"10393864","collections":[{"id":"1100092","name":"s5100370"}]} start time:  Sat Feb 25 2017 05:54:34 GMT-0500 (EST) end time:  Sat Feb 25 2017 05:54:41 GMT-0500 (EST)
2017-02-25T10:54:42Z [23648] INFO {replication} connected to master at tcp://osdi-01:8529, id 267112631259636, version 3.1, last log tick 10399704
2017-02-25T10:54:43Z [23648] INFO {replication} connected to master at tcp://osdi-01:8529, id 267112631259636, version 3.1, last log tick 10401001
2017-02-25T10:54:44Z [23648] INFO {replication} connected to master at tcp://osdi-01:8529, id 267112631259636, version 3.1, last log tick 10402043
2017-02-25T10:55:53Z [23648] INFO {replication} connected to master at tcp://osdi-02:8529, id 224848527284382, version 3.1, last log tick 9889347
2017-02-25T10:55:54Z [23648] INFO {replication} connected to master at tcp://osdi-02:8529, id 224848527284382, version 3.1, last log tick 9890210
2017-02-25T10:59:31Z [23648] INFO {replication} connected to master at tcp://osdi-01:8529, id 267112631259636, version 3.1, last log tick 10660915
2017-02-25T10:59:36Z [23648] INFO {replication} connected to master at tcp://osdi-01:8529, id 267112631259636, version 3.1, last log tick 10663374
2017-02-25T10:59:36Z [23648] INFO {replication} connected to master at tcp://osdi-01:8529, id 267112631259636, version 3.1, last log tick 10663374
2017-02-25T10:59:39Z [23648] INFO {replication} connected to master at tcp://osdi-01:8529, id 267112631259636, version 3.1, last log tick 10669851
2017-02-25T10:59:39Z [13522] ERROR {cluster} ClusterComm::performRequests: got no answer from shard:s5100273:/_db/OSDI/_api/document?collection=s5100273&waitForSync=false&returnNew=false&returnOld=false with error 4
2017-02-25T10:59:39Z [24784] INFO ArangoDB 3.1.11 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.1e-fips 11 Feb 2013
2017-02-25T10:59:39Z [24784] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
2017-02-25T10:59:39Z [24784] INFO Starting up with role PRIMARY
2017-02-25T10:59:39Z [24784] INFO file-descriptors (nofiles) hard limit is 96000, soft limit is 96000
2017-02-25T10:59:39Z [24784] INFO running WAL recovery (1 logfiles)
2017-02-25T10:59:39Z [24784] INFO replaying WAL logfile '/data/data/arango/db/journals/logfile-13670779.db' (1 of 1)
2017-02-25T10:59:45Z [24784] INFO WAL recovery finished successfully
2017-02-25T10:59:46Z [13522] ERROR {cluster} cannot create connection to server 'PRMR-4ca5c6f0-48a9-459a-95b8-2cfa2a7ea89e' at endpoint 'tcp://osdi-m:8529'
2017-02-25T10:59:46Z [13522] ERROR {cluster} cannot create connection to server 'PRMR-4ca5c6f0-48a9-459a-95b8-2cfa2a7ea89e' at endpoint 'tcp://osdi-m:8529'
2017-02-25T10:59:46Z [13522] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s5100310:/_db/OSDI/_api/collection/s5100310/count
2017-02-25T10:59:46Z [13522] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s5100307:/_db/OSDI/_api/collection/s5100307/count
2017-02-25T10:59:46Z [13522] ERROR {cluster} cannot create connection to server 'PRMR-4ca5c6f0-48a9-459a-95b8-2cfa2a7ea89e' at endpoint 'tcp://osdi-m:8529'
2017-02-25T10:59:46Z [13522] ERROR {cluster} cannot create connection to server 'PRMR-4ca5c6f0-48a9-459a-95b8-2cfa2a7ea89e' at endpoint 'tcp://osdi-m:8529'
2017-02-25T10:59:46Z [13522] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s5100310:/_db/OSDI/_api/collection/s5100310/count
2017-02-25T10:59:46Z [13522] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s5100307:/_db/OSDI/_api/collection/s5100307/count
2017-02-25T10:59:46Z [13522] ERROR {cluster} cannot create connection to server 'PRMR-4ca5c6f0-48a9-459a-95b8-2cfa2a7ea89e' at endpoint 'tcp://osdi-m:8529'
2017-02-25T10:59:46Z [13522] ERROR {cluster} cannot create connection to server 'PRMR-4ca5c6f0-48a9-459a-95b8-2cfa2a7ea89e' at endpoint 'tcp://osdi-m:8529'
2017-02-25T10:59:46Z [13522] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s5100310:/_db/OSDI/_api/collection/s5100310/count
2017-02-25T10:59:46Z [13522] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s5100307:/_db/OSDI/_api/collection/s5100307/count
2017-02-25T10:59:46Z [13522] ERROR {cluster} cannot create connection to server 'PRMR-4ca5c6f0-48a9-459a-95b8-2cfa2a7ea89e' at endpoint 'tcp://osdi-m:8529'
2017-02-25T10:59:46Z [13522] ERROR {cluster} cannot create connection to server 'PRMR-4ca5c6f0-48a9-459a-95b8-2cfa2a7ea89e' at endpoint 'tcp://osdi-m:8529'
2017-02-25T10:59:46Z [13522] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s5100310:/_db/OSDI/_api/collection/s5100310/count
2017-02-25T10:59:46Z [13522] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s5100307:/_db/OSDI/_api/collection/s5100307/count
2017-02-25T10:59:47Z [13522] ERROR {cluster} cannot create connection to server 'PRMR-4ca5c6f0-48a9-459a-95b8-2cfa2a7ea89e' at endpoint 'tcp://osdi-m:8529'
2017-02-25T10:59:47Z [13522] ERROR {cluster} cannot create connection to server 'PRMR-4ca5c6f0-48a9-459a-95b8-2cfa2a7ea89e' at endpoint 'tcp://osdi-m:8529'
2017-02-25T10:59:47Z [13522] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s5100310:/_db/OSDI/_api/collection/s5100310/count
2017-02-25T10:59:47Z [13522] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s5100307:/_db/OSDI/_api/collection/s5100307/count
2017-02-25T10:59:47Z [24784] INFO JavaScript using startup '//usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
2017-02-25T10:59:49Z [13522] ERROR {cluster} cannot create connection to server 'PRMR-4ca5c6f0-48a9-459a-95b8-2cfa2a7ea89e' at endpoint 'tcp://osdi-m:8529'
2017-02-25T10:59:49Z [13522] ERROR {cluster} cannot create connection to server 'PRMR-4ca5c6f0-48a9-459a-95b8-2cfa2a7ea89e' at endpoint 'tcp://osdi-m:8529'
2017-02-25T10:59:49Z [13522] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s5100310:/_db/OSDI/_api/collection/s5100310/count
2017-02-25T10:59:49Z [13522] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s5100307:/_db/OSDI/_api/collection/s5100307/count
2017-02-25T10:59:52Z [13522] ERROR {cluster} cannot create connection to server 'PRMR-4ca5c6f0-48a9-459a-95b8-2cfa2a7ea89e' at endpoint 'tcp://osdi-m:8529'
2017-02-25T10:59:52Z [13522] ERROR {cluster} cannot create connection to server 'PRMR-4ca5c6f0-48a9-459a-95b8-2cfa2a7ea89e' at endpoint 'tcp://osdi-m:8529'
2017-02-25T10:59:52Z [13522] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s5100310:/_db/OSDI/_api/collection/s5100310/count
2017-02-25T10:59:52Z [13522] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s5100307:/_db/OSDI/_api/collection/s5100307/count
2017-02-25T10:59:54Z [24784] INFO Cluster feature is turned on. Agency version: {"server":"arango","version":"3.1.11","license":"community"}, Agency endpoints: http+tcp://osdi-02:25001, http+tcp://osdi-m:25001, http+tcp://osdi-01:25001, server id: 'PRMR-4ca5c6f0-48a9-459a-95b8-2cfa2a7ea89e', internal address: tcp://osdi-m:8529, role: PRIMARY
2017-02-25T10:59:54Z [24784] INFO using heartbeat interval value '1000 ms' from agency
2017-02-25T10:59:54Z [24784] INFO using endpoint 'http+tcp://osdi-m:8529' for non-encrypted requests
2017-02-25T10:59:54Z [24784] INFO bootstrapped DB server PRMR-4ca5c6f0-48a9-459a-95b8-2cfa2a7ea89e
2017-02-25T11:00:01Z [24784] INFO ArangoDB (version 3.1.11 [linux]) is ready for business. Have fun!
```

**Comment by kvahed** [comment] 2017-02-28 10:43
Do you have the logs from all machines for us please? Plus please give us a rough idea of the hardware, the setup (#agents, #coordinators, #db servers), RAM, #CPU, OS, container? That's really where we have a chance of trying to make sense of the problem. Many thanks in advance.

**Comment by idlefella** [comment] 2017-02-28 12:47
I made the same experience today with 3.1.11, but in a single server setup. It's reproducable by starting an arangodb server instance with `docker run -d -e ARANGO_NO_AUTH=1 --name arangodb -p 8529:8529 arangodb:3.1.11` and inserting many documents in parallel using the arangodb-java-driver-async driver in java (I used 10 threads). The docker container stops without leaving a log message. Can you tell me how I can help you debugging this error?

**Comment by idlefella** [comment] 2017-02-28 13:29
Just investigated more closely when it happens. I found out that flooding the database with insertDocument requests (not waiting the callback function) makes arangodb crash. It's definitely not a proper use of the java driver, but maybe it might be of interest to catch this error.

```java
while(true) {
    BaseDocument doc = new BaseDocument();
    doc.addAttribute("name", getRandomString());
    this.arangodb.db("test").collection("testCollection").insertDocument(doc);
}
```

**Comment by aznwarmonkey** [comment] 2017-02-28 13:54
I am currently running 3 coordinators, 3 db servers, and 3 agencies on bare metal.  Each machines specs:

- 256GB RAM
- 32 cores
- CENTOS 6.8

I run my service using supervisor.  Below is the command i use for each of the 3 nodes.  Also i have attached the logs for each of the machines after running for about 20 mins under load.

[arangod-01.txt](https://github.com/arangodb/arangodb/files/806936/arangod-01.txt)
[arangod-02.txt](https://github.com/arangodb/arangodb/files/806937/arangod-02.txt)
[arangod-m.txt](https://github.com/arangodb/arangodb/files/806938/arangod-m.txt)

Server 1
```bash
# start agency
/usr/sbin/arangod --server.endpoint tcp://0.0.0.0:25001 --agency.my-address tcp://%(host_node_name)s:25001 --server.authentication false --agency.size 3 --agency.supervision true --agency.activate true  --database.directory /data/data/arango/agency

# start db server
/usr/sbin/arangod --server.authentication=false --server.endpoint tcp://%(host_node_name)s:8529 --cluster.my-address tcp://%(host_node_name)s:8529 --cluster.my-local-info %(host_node_name)s-db --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://osdi-m:25001 --cluster.agency-endpoint tcp://osdi-01:25001 --cluster.agency-endpoint tcp://osdi-02:25001 /data/data/arango/db

# start coordinator
/usr/sbin/arangod --server.authentication=false --server.endpoint tcp://%(host_node_name)s:8530 --cluster.my-address tcp://%(host_node_name)s:8530 --cluster.my-local-info %(host_node_name)s-coordinator --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://osdi-m:25001 --cluster.agency-endpoint tcp://osdi-01:25001 --cluster.agency-endpoint tcp://osdi-02:25001 /data/data/arango/coordinator
```

Server 2
```bash
# start agency
/usr/sbin/arangod --server.endpoint tcp://0.0.0.0:25001 --agency.my-address tcp://%(host_node_name)s:25001 --server.authentication false --agency.size 3 --agency.supervision true --agency.activate true  --database.directory /data/data/arango/agency

# start db server
/usr/sbin/arangod --server.authentication=false --server.endpoint tcp://%(host_node_name)s:8529 --cluster.my-address tcp://%(host_node_name)s:8529 --cluster.my-local-info %(host_node_name)s-db --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://osdi-m:25001 --cluster.agency-endpoint tcp://osdi-01:25001 --cluster.agency-endpoint tcp://osdi-02:25001 /data/data/arango/db

# start coordinator
/usr/sbin/arangod --server.authentication=false --server.endpoint tcp://%(host_node_name)s:8530 --cluster.my-address tcp://%(host_node_name)s:8530 --cluster.my-local-info %(host_node_name)s-coordinator --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://osdi-m:25001 --cluster.agency-endpoint tcp://osdi-01:25001 --cluster.agency-endpoint tcp://osdi-02:25001 /data/data/arango/coordinator
```

Server 3
```bash
# start agency
/usr/sbin/arangod --server.endpoint tcp://0.0.0.0:25001 --agency.my-address tcp://%(host_node_name)s:25001 --server.authentication false --agency.size 3 --agency.supervision true --agency.activate true --agency.endpoint tcp://osdi-m:25001 --agency.endpoint tcp://osdi-01:25001 --agency.endpoint tcp://osdi-02:25001 --database.directory /data/data/arango/agency

# start db server
/usr/sbin/arangod --server.authentication=false --server.endpoint tcp://%(host_node_name)s:8529 --cluster.my-address tcp://%(host_node_name)s:8529 --cluster.my-local-info %(host_node_name)s-db --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://osdi-m:25001 --cluster.agency-endpoint tcp://osdi-01:25001 --cluster.agency-endpoint tcp://osdi-02:25001 /data/data/arango/db

# start coordinator
/usr/sbin/arangod --server.authentication=false --server.endpoint tcp://%(host_node_name)s:8530 --cluster.my-address tcp://%(host_node_name)s:8530 --cluster.my-local-info %(host_node_name)s-coordinator --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://osdi-m:25001 --cluster.agency-endpoint tcp://osdi-01:25001 --cluster.agency-endpoint tcp://osdi-02:25001 /data/data/arango/coordinator
```

Here's the java code I am using to do ingestion.  This is using the java driver 4.10 (latest) in a SPARK 1.6 environment


```java
	@SuppressWarnings("serial")
	@Override
	public void call(JavaPairRDD<String, Iterable<List<BaseDocument>>> pArg0) throws Exception {

		pArg0.foreachPartition(new VoidFunction<Iterator<Tuple2<String, Iterable<List<BaseDocument>>>>>() {

			@Override
			public void call(Iterator<Tuple2<String, Iterable<List<BaseDocument>>>> pArg0) throws Exception {

				final Map<String, List<BaseDocument>> documentMapping = new HashMap<String, List<BaseDocument>>();

				// some work to populate map

				final ArangoDB.Builder builder = new ArangoDB.Builder();
				for (int i = 0; i < fArangoDBServers.length; i++) {
					builder.host(fArangoDBServers[i], fArangoDBPort[i]);
				}

				final ArangoDB arangoDB = builder.build();
				final ArangoDatabase database = arangoDB.db(fArangoDBDatabaseName);

				try {
					for (final String types : documentMapping.keySet()) {
						int countNodes = 0;
						final long t1 = System.currentTimeMillis();
						final ArangoCollection collection = getCollection(types, database);
						final List<BaseDocument> documents = documentMapping.get(types);
						collection.importDocuments(documents);

						final long t2 = System.currentTimeMillis();
						LOGGER.info("Ingestion time:\t" + (t2 - t1) + " SIZE:\t" + countNodes);
					}
				} finally {
					arangoDB.shutdown();
				}
			}
		});
	}
```

**Comment by neunhoef** [comment] 2017-03-01 15:05
@idlefella I tried to reproduce these problems, first with the single server running in a Docker container exactly as you describe. So far, I have not been able to crash it, even with considerably more than 10 threads. What would be useful is more details on your setup:
  - host operating system
  - Docker daemon version
  - underlying filesystem for Docker (depends on Linux distribution, for example Debian uses aufs which has known problems)
  - underlying filesystem of the OS (we know that bttrfs has issues!)
  - size of the machine (number of cores and memory)
  - the exact Java client problem leading to a crash
  - the output of `docker inspect` of the crashed container (might indicate an error code)
  - the output of `docker logs` of the crashed container
Once we can reproduce this crash, we can fix it. Once single server is working, cluster can follow.

**Comment by idlefella** [comment] 2017-03-01 15:49
Hi @neunhoef 

Here are the infos:
- OS: Ubuntu 16.04.2 LTS xenial
- Kernel: 4.4.0-62-generic #83-Ubuntu SMP
- The docker storage driver is **aufs**
- The underlying filesystem is **ext4**
- Tested with
  - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  - 32GB of RAM
- Java: openjdk version "1.8.0_121"

I created a small project with which I'm able to crash it: https://github.com/trivo-ch/arangodb-crasher

**Docker inspect output**
```
[
    {
        "Id": "b9b1e8feeade667a662e76c552bbd2566f6bdcde411c3b540fb71a588c710b7a",
        "Created": "2017-03-01T15:33:17.229800849Z",
        "Path": "/entrypoint.sh",
        "Args": [
            "arangod"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 139,
            "Error": "",
            "StartedAt": "2017-03-01T15:33:17.595612887Z",
            "FinishedAt": "2017-03-01T15:35:42.429559504Z"
        },
        "Image": "sha256:5aacf198141660cdf398d51e668dc4a18e1d70a346c94094abdda1d72f919a03",
        "ResolvConfPath": "/var/lib/docker/containers/b9b1e8feeade667a662e76c552bbd2566f6bdcde411c3b540fb71a588c710b7a/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/b9b1e8feeade667a662e76c552bbd2566f6bdcde411c3b540fb71a588c710b7a/hostname",
        "HostsPath": "/var/lib/docker/containers/b9b1e8feeade667a662e76c552bbd2566f6bdcde411c3b540fb71a588c710b7a/hosts",
        "LogPath": "/var/lib/docker/containers/b9b1e8feeade667a662e76c552bbd2566f6bdcde411c3b540fb71a588c710b7a/b9b1e8feeade667a662e76c552bbd2566f6bdcde411c3b540fb71a588c710b7a-json.log",
        "Name": "/arangodb",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "8529/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8529"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "11e45ce621ca8e476a48ca9399e01764d39f73b8676edc37a49281c99e551838",
                "Source": "/var/lib/docker/volumes/11e45ce621ca8e476a48ca9399e01764d39f73b8676edc37a49281c99e551838/_data",
                "Destination": "/var/lib/arangodb3",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "146cde47821c630c2ebe05d779238437732acf33a0778738be7cd792c6fb5e1c",
                "Source": "/var/lib/docker/volumes/146cde47821c630c2ebe05d779238437732acf33a0778738be7cd792c6fb5e1c/_data",
                "Destination": "/var/lib/arangodb3-apps",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "b9b1e8feeade",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8529/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "ARANGO_NO_AUTH=1",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "ARCHITECTURE=amd64",
                "DEB_PACKAGE_VERSION=1",
                "ARANGO_VERSION=3.1.11",
                "ARANGO_URL=https://www.arangodb.com/repositories/arangodb31/Debian_8.0",
                "ARANGO_PACKAGE=arangodb3-3.1.11-1_amd64.deb",
                "ARANGO_PACKAGE_URL=https://www.arangodb.com/repositories/arangodb31/Debian_8.0/amd64/arangodb3-3.1.11-1_amd64.deb",
                "ARANGO_SIGNATURE_URL=https://www.arangodb.com/repositories/arangodb31/Debian_8.0/amd64/arangodb3-3.1.11-1_amd64.deb.asc"
            ],
            "Cmd": [
                "arangod"
            ],
            "ArgsEscaped": true,
            "Image": "arangodb:3.1.11",
            "Volumes": {
                "/var/lib/arangodb3": {},
                "/var/lib/arangodb3-apps": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "66a418971c9716be6ad031cdfa4983c8fc8095e4754fcf49e929210a99f0abe5",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": null,
            "SandboxKey": "/var/run/docker/netns/66a418971c97",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "3c074b40ec1cf69393d6e9008d084169ba94cebf49bf4ef847651b1c1ba77c21",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]
```
**Output of docker logs**
```
Initializing database...Hang on...
Database initialized...Starting System...
2017-03-01T15:33:22Z [1] INFO ArangoDB 3.1.11 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.1t  3 May 2016
2017-03-01T15:33:22Z [1] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
2017-03-01T15:33:22Z [1] INFO Starting up with role SINGLE
2017-03-01T15:33:22Z [1] INFO file-descriptors (nofiles) hard limit is 1048576, soft limit is 1048576
2017-03-01T15:33:22Z [1] INFO JavaScript using startup '/usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
2017-03-01T15:33:22Z [1] INFO using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
2017-03-01T15:33:22Z [1] INFO Please note that a new bugfix version '3.1.12' is available
2017-03-01T15:33:22Z [1] INFO ArangoDB (version 3.1.11 [linux]) is ready for business. Have fun!
2017-03-01T15:33:43Z [1] INFO created application directory '/var/lib/arangodb3-apps/_db/test' for database 'test'
```
It crashes silently. It takes about 1 minute of inserting documents.

**Client error log**
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building arangodb-crasher 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ arangodb-crasher ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.net.SocketException: Connection reset
	at com.arangodb.internal.velocystream.Connection.writeIntern(Connection.java:212)
	at com.arangodb.internal.velocystream.ConnectionAsync.write(ConnectionAsync.java:89)
	at com.arangodb.internal.velocystream.CommunicationAsync.send(CommunicationAsync.java:159)
	at com.arangodb.internal.velocystream.CommunicationAsync.execute(CommunicationAsync.java:117)
	at com.arangodb.internal.velocystream.CommunicationAsync.execute(CommunicationAsync.java:46)
	at com.arangodb.internal.ArangoExecutorAsync.execute(ArangoExecutorAsync.java:53)
	at com.arangodb.ArangoCollectionAsync.insertDocument(ArangoCollectionAsync.java:83)
	at ch.trivo.ArangoDBCrasher.main(ArangoDBCrasher.java:33)
	... 6 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.arangodb.internal.velocystream.Connection.writeIntern(Connection.java:210)
	... 13 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:50 min
[INFO] Finished at: 2017-03-01T16:35:43+01:00
[INFO] Final Memory: 27M/3833M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (default-cli) on project arangodb-crasher: An exception occured while executing the Java class. null: InvocationTargetException: java.net.SocketException: Connection reset -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
I hope this helps. Let me know if I can provide more infos/logs.

**Comment by neunhoef** [comment] 2017-03-02 07:52
Thanks for this. The exit code 139 = 128+11 means that the arangod process crashed with a segmentation violation. We need to get to the bottom of this. We will investigate today, also thanks for the code.

**Comment by neunhoef** [comment] 2017-03-02 10:22
Sorry, I have tried to run this on different machines for more than an hour each and no crash occurred. I am running the exact same Docker image, your code and the very same configuration. I have tried 127.0.0.1 and the Docker IP address. I am slowly running out of ideas how to replicate the crash.
Is it at all possible that your machine has a faulty memory bank? Have you ever run a memory test like memtester on it?

**Comment by dothebart** [comment] 2017-03-17 15:33
Hi, any news on this? or can we close this issue?

**Comment by idlefella** [comment] 2017-03-18 08:42
Hi @dothebart, @neunhoef 
I was quite busy with other stuff. Since we want to evaluate the graph performance of arangodb I will run the performance test on another machine and see if it's a problem with my machine (broken memory?) or the same problem still arises. I'll give you an update asap.

**Comment by idlefella** [comment] 2017-04-03 15:00
I had finally time to rerun this test on another machine (VM). There arangodb didn't crash. It's quite weird. I also ran memtest on my local machine but didn't find a memory error. So I can't tell you why it crashes on locally. Maybe you can close this issue as long as it doesn't affect somebody else?

**Comment by dothebart** [comment] 2017-04-03 15:41
Ok, feel free to keep us informed if you're able to reproduce again.

**Closed by dothebart** 2017-04-03 15:41 UTC
Labels: 3 Cluster
