### ISSUE TITLE
Unable to relaunch single-server cluster

### ISSUE THREAD

**Issue by nlac** [arangodb/arangodb#1334] opened 2015-05-15 07:41 UTC
Hi guys,
let me report an other issue faced with when tried to relaunch a single server cluster, after arangod crashed. 

After made sure that no old processes stucked and restarted arangod, got the following on the UI:
```Remote Address:127.0.0.1:8529
Request URL:http://127.0.0.1:8529/_db/_system/_admin/aardvark/cluster/relaunch?_=1431672768081
Request Method:GET
Status Code: 409 Conflict
Response: "Unable to relaunch cluster"```

In the log (debug-level):
```2015-05-15T06:53:10Z [7276] DEBUG [C:\cygwin64\home\jenkins\ArangoDB-2.5.3\lib\Rest\EndpointIp.cpp:284] connecting to ip endpoint 'tcp://127.0.0.1:8530'
2015-05-15T06:53:11Z [7276] ERROR bootstrapping DB servers failed: Could not connect to 'tcp://127.0.0.1:8530' 'connect() failed with #10061 - No connection could be made because the target machine actively refused it.```

Please find all details (logs/config/steps) here http://nlacsoft.net/public/arango/restart_cluster_fails.zip

**Comment by fceller** [comment] 2015-06-12 10:54
@neunhoef can you checj if this can by reproduced with 2.6?

**Comment by neunhoef** [comment] 2015-06-12 11:46
I cannot reproduce this with 2.6.dev on my Linux machine. In my case the cluster starts OK, when I click "Relaunch". I do get the same errors and warnings as found in the log file, since these are triggered by the UI that first tries to see whether a cluster is still running. The processes are gone, so the health check fails and that produces the warnings. 
Strangely enough I cannot see the efforts to relaunch the cluster in the log files.
Did you reload the browser page (after the restart of the initial dispatcher server)?
Did you get the option to Relaunch (one of three buttons)?
Did you hit "Relaunch"?

**Comment by nlac** [comment] 2015-06-12 14:57
Thanks for the investigation! I'm not 100% sure that i reloaded the page in the browser but i am that i hit the "Relaunch" button - i think the transaction captured in my Chrome's console proves it that i pasted above. The server responded it with a 409.

**Comment by dothebart** [comment] 2015-06-24 08:23
this should work with 2.6.0 final; can we close this?

**Comment by neunhoef** [comment] 2015-06-24 11:11
Yes, we can close this.

**Closed** 2015-06-24 11:48 UTC
Labels: Bug, core
