### ISSUE TITLE
Windows 10 - Installer recognized as trojan (Win32/Fuerboos.A!cl) by Defender 

### ISSUE THREAD

**Issue by stephanbruny** [arangodb/arangodb#4170] opened 2017-12-27 15:38 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

On this operating system:
- [x] Windows, version: 10 Home (1709)

### this is an installation-related issue:

The current (27. december 2017) .exe-installer will cause an Windows Defender alert, when downloaded, or executed.
The file (or parts thereof) will be indicated as a trojan (Win32/Fuerboos.A!cl) and the installation cannot be finished.

**Comment by sleto-it** [comment] 2017-12-27 18:56
Hi @stephanbruny,

Thanks for opening this ticket. I was not able to reproduce the exact message you get doing some quick tests on my Win 10 machine

Please could you let us know version information of your windows defender (you can take a screenshot after searching "windows defender setting" on your pc). Please also let us know the exact windows build you are using (search "system information")

Can be related to the fact that the .exe is not signed, https://github.com/arangodb/arangodb/issues/1082

As possible temporary workaround, please know that there is a zip package as well (just unzip it somehwere and then from a command line start `arangod` or `arangodb` - depending on your needs)

Thanks,

**Comment by Simran-B** [comment] 2017-12-28 00:43
@sleto-it I know from my personal experience that various antivirus software including Windows Defender and SmartScreen frequently detect ArangoDB installers as malware. This is mostly caused by the generic heuristic that recognizes patterns like unpacking compressed/encrypted executable and starting it as service that listens for incoming requests in combination with a "rare" binary (which it is for every new release). After a while, that should stop happening, once it is not considered a rare binary anymore.

**Comment by dothebart** [comment] 2018-04-26 15:31
Hi, 
since this occurs now and then and can only be solved by signing windows installer packages (which is on our roadmap) and we already have https://github.com/arangodb/arangodb/issues/1082 for this I will close this as duplicate.

**Closed by dothebart** 2018-04-26 15:31 UTC
Labels: 3 Packaging, 4 Windows
