### ISSUE TITLE
arangorestore fails when runs from code (e.g. `Process` in java)

### ISSUE THREAD

**Issue by VladoDemcak** [arangodb/arangodb#4063] opened 2017-12-16 11:31 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2.9

Mode:
- [x] Single-Server

Storage-Engine:
- [x] mmfiles

On this operating system:
- [x] Windows, version: 10

These are the steps to reproduce:
1) create arangodump
2) use arangorestore
3) connect to arango with client while arangorestore is in progress
4) error should occurrs

The following problem occurs:
```
11430 [main] INFO  com.accenture.vasp.services.arangodb.tools.ArangoInitializator  - dumpfile: {"database":"xxxxxxx","lastTickAtDumpStart":"31600"}
Creating database 'xxxxxxx'
Server version: 3.2.9
# Connected to ArangoDB 'http+tcp://127.0.0.1:8529'
# Re-creating document collection '_appbundles'...
# Loading data into document collection '_appbundles'...
# Re-creating document collection '_aqlfunctions'...
# Loading data into document collection '_aqlfunctions'...
# Re-creating document collection '_frontend'...
# Loading data into document collection '_frontend'...
# Re-creating document collection '_graphs'...
# Loading data into document collection '_graphs'...
# Re-creating document collection '_modules'...
2017-12-16T11:20:53Z [233] ERROR got error from server: HTTP 409 (Conflict): ArangoError 1207: duplicate name
Processed 4 collection(s), read 9200 byte(s) from datafiles, sent 3 batch(es)
```
Instead I would be expecting: 
Since we have collections also b/c of this error the arangorestore will not import data and database is not usable. 

We have spotted this happens when client (e.g. `arango-java-driver`) connects to database. Since we are using docker-compose we are unable to "hide" port for clients (or some workaround) while arangorestore is running. 

I was trying to find more details but this is my assumption. When I run arangorestore without clients it works well and error rate is 0%. But with client it fails but very unpredictable. I guess when client boots quickly (when arangorestore is in progress) this error occurred. When client runs slowly (at bootstrap phase) arangorestore finished fine and imported all data.  

Is it possible to do something like "lock" for arangorestore process? 

Anyway **this is just my assumption and I may be wrong**. Since there is a problem with modules collection I took a look into that file. I formatted json below for better debugging. This is content of  `_modules_xyz.structure.json` (data file is empty) - generated by `arangodump`
```
{
	"indexes" : [],
	"parameters" : {
		"allowUserKeys" : true,
		"cid" : "134",
		"count" : 0,
		"deleted" : false,
		"doCompact" : true,
		"id" : "134",
		"indexBuckets" : 8,
		"indexes" : [{
				"fields" : ["_key"],
				"id" : "0",
				"selectivityEstimate" : 1,
				"sparse" : false,
				"type" : "primary",
				"unique" : true
			}
		],
		"isSmart" : false,
		"isSystem" : true,
		"isVolatile" : false,
		"journalSize" : 1048576,
		"keyOptions" : {
			"allowUserKeys" : true,
			"lastValue" : 0,
			"type" : "traditional"
		},
		"name" : "_modules",
		"numberOfShards" : 1,
		"planId" : "134",
		"replicationFactor" : 2,
		"shardKeys" : ["_key"],
		"shards" : {},
		"status" : 3,
		"type" : 2,
		"version" : 6,
		"waitForSync" : false
	}
}

```

**Comment by maxkernbach** [comment] 2018-01-02 13:47
Hello,

i tried to reproduce your problem by reading + writing documents and collections using the arango-java-driver on a single server while arangorestore is in progress. This error did not occur for me though.

Are you using a single-server or cluster? I am asking because single-server is listed but the generated arangodump file contains **"replicationFactor" : 2**, which implies the use of a cluster. In the case of a cluster how many agents, db-servers and coordinator do you use? Which operations does your client perform (read, write, read + write)?

**Comment by VladoDemcak** [comment] 2018-01-02 16:51
Hi @maxkernbach, 
thanks for investigation. I highly appreciate your effort you put into this issue.

We are using single server. I have no idea why the replicationFactor is set to value 2. 

Honestly there is possibility we have wrong configuration but I am not aware of any misconfiguration. However we are using docker arango v.3.2.9 (this happens with mentioned version). We use only "NO_AUTH" set to 1. 

Maybe important note. We are using [arangochair ](https://www.arangodb.com/2017/03/arangochair-tool-listening-changes-arangodb/) which starts on startup in a second thread. But I did not notice failure when I ran only arango. As I said this happens when I run `docker-compose` with multiple clients. 

We will try to update do `3.3.1` and let you know if the issue remains. 

Just in case - We use this arangodump
```
arangodump --output-directory "somedir" --include-system-collections true --overwrite true --server.database "xxxxxx" 
```

and this arangorestore
```
arangorestore --input-directory "somedir" --include-system-collections true --server.database "xxxxxx" --create-collection true
````

**Comment by VladoDemcak** [comment] 2018-01-03 08:04
@maxkernbach  Also maybe another important note is we are using `ProcessBuilder` which creates `Process` that runs from java application in order to perform initialization of a database (dumped with `arangodump`). 

Tried to upgrade to `3.3.1` and this issue happens all the time. With or without clients. so I tried to start `arangorestore` manually and also with `Process`. Manually worked every time but from code didn't. So I think this issue is about "using Process" from java application to run `arangorestore`.

Worked
```
arangorestore --create-database=true --server.database=xxxx --input-directory=/somedir --server.password="" --create-collection=true --include-system-collections=true
```

Didnt work
```
 new ProcessBuilder(
                    "arangorestore",
                    "--create-database=true",
                    "--server.database=xxxx",
                    "--input-directory=/somedir",
                    "--server.password=\"\"",
                    "--create-collection=true",
                    "--include-system-collections=true"
            ).inheritIO()
             .start()
             .waitFor();
```

**Comment by VladoDemcak** [comment] 2018-01-03 09:14
New observation I found.
Adding `Thread.sleep` right befor `Process.start` fixes the issue. However it's kind of weird b/c `arangod` opened port `8529` and allowed to use `arangorestore` for `Process` but seems like something has not been initialized yet.

**Comment by jsteemann** [comment] 2018-01-03 09:20
For reference: "replicationFactor" does not play a role in single-server mode. It is only used in cluster context. When set for a collection in single-server mode, the value of "2" will be ignored.

**Comment by jsteemann** [comment] 2018-01-03 09:25
It looks like you are using arangodump and arangorestore from/to the same database (at least the values of `--server.database` seem to match, and there is no `--server.endpoint` value). If dump & restore are run on the same machine, this would overwrite the contents of an existing database with the contents from the dump, which may cause conflicts. Is that intentional, or just a side-effect of putting the commands together for this Github issue?

**Comment by VladoDemcak** [comment] 2018-01-03 09:50
hi @jsteemann  thanks for comment.
IT's not on the same machine (it's totally new docker container) we are using `arangodump` in docker container which has `databaseName` and we do a backup of db generated via `arangodump`. 

Then we take _clean docker container_ (without `databaseName`) and we use `arangorestore` with previously generated data with java `Process` immediately when port `8529` is accessible. And the issue happens.

Few minutes ago I tried to add `Thread.sleep` with 10seconds and worked well. 
But with 3 or 5 seconds and I've got:
```
Creating database 'databaseName'
Server version: 3.3.1
# Connected to ArangoDB 'http+tcp://127.0.0.1:8529'
# Re-creating document collection '_appbundles'...
# Loading data into document collection '_appbundles'...
# Re-creating document collection '_aqlfunctions'...
# Loading data into document collection '_aqlfunctions'...
# Re-creating document collection '_frontend'...
# Loading data into document collection '_frontend'...
# Re-creating document collection '_graphs'...
# Loading data into document collection '_graphs'...
# Re-creating document collection '_modules'...
# Loading data into document collection '_modules'...
# Re-creating document collection '_routing'...
# Loading data into document collection '_routing'...
# Re-creating document collection 'vertices-xxxxx'...
2018-01-03T09:28:42Z [8] ERROR duplicate collection identifier 159 for name 'vertices-xxxxx'
2018-01-03T09:28:42Z [149] ERROR got error from server: HTTP 500 (Internal Server Error): ArangoError 1005: duplicate collection identifier 159 for name 'vertices-xxxxx'
Processed 6 collection(s), read 9912 byte(s) from datafiles, sent 3 batch(es)
12664 [main] ERROR xxxxx.ArangoInitializator  - arangorestore installation failed
``` 

Is it possible arango needs few seconds to perform some initialization in the background (another things ) even though port `8529` is open and database seems to be ready?

Regardin `server.endpoint` parameter. I guess `server.endpoint` there is no needs to use this param. In the documentaion there is a node `The default endpoint for ArangoDB is tcp://127.0.0.1:8529 or tcp://localhost:8529.` and we are ok with default settings.

**Comment by jsteemann** [comment] 2018-01-03 10:02
Yes, if there is a conflict in `_modules` collection, then this is likely caused by the following:
- restore starts to load data into the database. At some point it will insert some data in `_modules`. These documents will have the same keys are present in the dump.
- when some other operation is populating the `_modules` collection at the very same time (and with the same key), the conflict may arise. I have to check what actions actually populate `_modules`.

**Comment by jsteemann** [comment] 2018-01-03 10:05
As far as I can see, there is a `defineModule` function, but it seems it is not called from inside ArangoDB itself. Is it possible that you have any client- or server-side code that calls it explicitly?

**Comment by VladoDemcak** [comment] 2018-01-03 10:17
The `_modules` collection is not very important (at least for this time) so I threw it away and in `v3.2.9` the issue disappeared. 

But the problem now in `3.1,1`  is also with our custom collection `vertices-xxxxx` I mentioned in the last comment.

Regarding `explicitly calls`. We are using `arangochair` which may potentially call arango (arangochair also listens for changes in  `vertices-xxxxx`) and arangochair is running as an another process. Except arangochair we use only `arango-java-driver` for accessing arangodb and these clients don't call module things. As far as I know (but definitely not explicitly).

**Comment by terry124** [comment] 2018-01-03 10:25
K

**Comment by terry124** [comment] 2018-01-03 10:26
K

**Comment by jsteemann** [comment] 2018-01-03 10:34
I have checked the Java driver and arangochar, and both do not seem to write into `_modules` at all. 

Is the dump from 3.3 as well? I would guess the dump imported into 3.3 has been created with 3.2?
Can you try restoring a dump created with 3.3 and check if that works?

**Comment by VladoDemcak** [comment] 2018-01-03 10:44
I tried dump generated with `3.2.9` in docker container with `3.3.1` manually without issues. All data looked fine no errors. Then I did dump with `3.3.1` and tried `arangorestore` as usual. But the issue remains. 

Also I tried sleep with 9sec but arangorestore was not able to create our custom collection. But with 10sec it worked. It's really weird but with 10sec sleep after opening port it doesnt fail. I will try to turn off arangochair in order to check if it has any impact on `arangorestore`.

**Comment by VladoDemcak** [comment] 2018-01-03 12:26
We've implemented another approach how to use java `ProcessBuilder` and `Process` without sleeping for 10 seconds.

When `arangorestore` fails we just drop the database defined as a parameter in `arangorestore` and wait 2seconds and try again. I tried multiple times and `arangorestore` was able to initialize database. Check logs below:


```
8697 [main] INFO  xxxxxxxx.ArangoInitializator  - dumpfile: {"database":"xxxxxxxx","lastTickAtDumpStart":"61179"}
Creating database 'xxxxxxxx'
Server version: 3.3.1
# Connected to ArangoDB 'http+tcp://127.0.0.1:8529'
# Re-creating document collection '_appbundles'...
# Loading data into document collection '_appbundles'...
# Re-creating document collection '_aqlfunctions'...
# Loading data into document collection '_aqlfunctions'...
# Re-creating document collection '_frontend'...
# Loading data into document collection '_frontend'...
# Re-creating document collection '_graphs'...
# Loading data into document collection '_graphs'...
# Re-creating document collection '_modules'...
# Loading data into document collection '_modules'...
# Re-creating document collection '_routing'...
# Loading data into document collection '_routing'...
# Re-creating document collection 'vertices-xxxxxxxx'...
2018-01-03T12:15:25Z [8] ERROR duplicate collection identifier 159 for name 'vertices-alerts'
2018-01-03T12:15:25Z [157] ERROR got error from server: HTTP 500 (Internal Server Error): ArangoError 1005: duplicate collection identifier 159 for name 'vertices-xxxxxxxx'
Processed 6 collection(s), read 9912 byte(s) from datafiles, sent 3 batch(es)
8932 [main] INFO  xxxxxxxx.ArangoInitializator  - Attempt #1 arangorestore failed. Next attempt in 2 seconds.
Creating database 'xxxxxxxx'
Server version: 3.3.1
# Connected to ArangoDB 'http+tcp://127.0.0.1:8529'
# Re-creating document collection '_appbundles'...
# Loading data into document collection '_appbundles'...
# Re-creating document collection '_aqlfunctions'...
# Loading data into document collection '_aqlfunctions'...
# Re-creating document collection '_frontend'...
# Loading data into document collection '_frontend'...
# Re-creating document collection '_graphs'...
# Loading data into document collection '_graphs'...
# Re-creating document collection '_modules'...
# Loading data into document collection '_modules'...
# Re-creating document collection '_routing'...
# Loading data into document collection '_routing'...
# Re-creating document collection 'vertices-xxxxxxxx'...
# Loading data into document collection 'vertices-xxxxxxxx'...
... omitted logs for other collections
Processed 25 collection(s), read 17906537 byte(s) from datafiles, sent 14 batch(es)
12323 [main] INFO  xxxxxxxx.ArangoInitializator  - arangorestore installation finished successfully
```

**Comment by dothebart** [comment] 2018-01-03 12:29
Hi, 
did you know that the docker container offers a way to auto-import dumps on startup of a derived container? Sample code can be found here - https://github.com/arangodb/arangodb-docker/tree/official/test-user-scripts ; The script implementing this feature inside the docker entrypoint is here: 
https://github.com/arangodb/arangodb-docker/blob/official/docker-entrypoint33.sh#L93

**Comment by VladoDemcak** [comment] 2018-01-03 12:37
@dothebart thanks I didn't know about this. I will definitely check it.

But we have our custom `ArangoInitializator` which has 2 different ways how to create and init database. 

1. way is our custom which uses arango's APIs
2. way is to use `arangorestore`

**Comment by dothebart** [comment] 2018-01-03 12:43
as you can see in these lines you can also use javascript/arangosh functionality or bash scripts to be run for 1)

**Comment by VladoDemcak** [comment] 2018-01-03 13:28
@dothebart you are right. However we need to use `http api` otherwise we would fight with docker volumes (tricky with [testcontainers](https://testcontainers.org) for unit testing) ...

**Comment by jsteemann** [comment] 2018-01-03 14:21
Ok, thanks. I have reproduced it locally.

**Comment by VladoDemcak** [comment] 2018-01-03 14:43
@jsteemann that's cool! Do we know where is the problem?

**Comment by jsteemann** [comment] 2018-01-05 15:46
@VladoDemcak : the reason for this is probably that the dump contains the collection ids, and that the restore tries to reuse them, which leads to id conflicts with other collections when the collections are re-created on restore. Actually the restore should **not** reuse collection ids at all. It looks like there is some bug in the REST handler used by the restore, which will lead to ids not being reused only for system collections. But actually it should not reuse collection ids at all.

**Comment by jsteemann** [comment] 2018-01-05 15:47
Commit 75953d69e8b0c13a4884001999dcd7c36907031f has made it work in the cases that I tested.

**Comment by VladoDemcak** [comment] 2018-01-07 14:07
@jsteemann sure we  will wait for new `3.3.3` release and I will re-test this issue.

**Comment by jsteemann** [comment] 2018-01-08 07:08
Thanks!

**Comment by VladoDemcak** [comment] 2018-01-08 11:50
I did tests and looks like it works without any problems. 

We can close this issue, I guess. Thanks for the fix!

**Comment by sleto-it** [comment] 2018-01-08 18:31
cool, thanks. Closing

**Closed by sleto-it** 2018-01-08 18:31 UTC
Labels: 1 Bug, 2 Fixed
