### ISSUE TITLE
Why does `arangosh` throw an error while trying to address the collection after truncating it?

### ISSUE THREAD

**Issue by mohamed-barakat** [arangodb/arangodb#3667] opened 2017-11-11 10:50 UTC
Why does `arangosh` throw an error while trying to address the collection after truncating it?

```
127.0.0.1:8529@example> col = db.examples
[ArangoCollection 47449, "examples" (type document, status loaded)]

127.0.0.1:8529@example> db.examples
[ArangoCollection 47449, "examples" (type document, status loaded)]

127.0.0.1:8529@example> db._truncate(col)

127.0.0.1:8529@example> db.examples
2017-11-11T10:43:55Z [74222] ERROR JavaScript exception in file '/usr/local/opt/arangodb/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 97,7: ArangoError 11: forbidden
2017-11-11T10:43:55Z [74222] ERROR !      throw error;
2017-11-11T10:43:55Z [74222] ERROR !      ^

127.0.0.1:8529@example>
```

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [x] MacOS, version: 10.12.6

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [x] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by jsteemann** [comment] 2017-11-13 08:29
When I try the obvious for reproduction, I am not getting that error:
```
127.0.0.1:8529@_system> db._createDatabase("examples");
true

127.0.0.1:8529@_system> db._useDatabase("examples");
true

127.0.0.1:8529@examples> db._create("examples");
[ArangoCollection 129, "examples" (type document, status loaded)]

127.0.0.1:8529@examples> db.examples;
[ArangoCollection 129, "examples" (type document, status loaded)]

127.0.0.1:8529@examples> col = db.examples;
[ArangoCollection 129, "examples" (type document, status loaded)]

127.0.0.1:8529@examples> db._truncate(col);

127.0.0.1:8529@examples> db.examples;
[ArangoCollection 129, "examples" (type document, status loaded)]
```
I tried with 3.2.6 and both RocksDB and MMFiles engine, but to no avail.
Could you provide a bit more info on how this collection has been created, what permissions had been assigned etc? Thanks!

**Comment by mohamed-barakat** [comment] 2017-11-17 08:26
Here is the whole session:

```
$ arangosh --server.username root@example --server.database example --server.password xyz

                                       _
  __ _ _ __ __ _ _ __   __ _  ___  ___| |__
 / _` | '__/ _` | '_ \ / _` |/ _ \/ __| '_ \
| (_| | | | (_| | | | | (_| | (_) \__ \ | | |
 \__,_|_|  \__,_|_| |_|\__, |\___/|___/_| |_|
                       |___/

arangosh (ArangoDB 3.2.0 [darwin] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.0.0, OpenSSL 1.0.2l  25 May 2017)
Copyright (c) ArangoDB GmbH

Pretty printing values.
Connected to ArangoDB 'http+tcp://127.0.0.1:8529' version: 3.2.0 [server], database: 'example', username: 'root@example'

Please note that a new bugfix version '3.2.5' is available
Type 'tutorial' for a tutorial or 'help' to see common examples
127.0.0.1:8529@example> db._create("good");
[ArangoCollection 3844142, "good" (type document, status loaded)]

127.0.0.1:8529@example> db.good;
[ArangoCollection 3844142, "good" (type document, status loaded)]

127.0.0.1:8529@example> col = db.good;
[ArangoCollection 3844142, "good" (type document, status loaded)]

127.0.0.1:8529@example> db._truncate(col);

127.0.0.1:8529@example> db.good;
2017-11-17T08:25:12Z [2364] ERROR JavaScript exception in file '/usr/local/opt/arangodb/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 97,7: ArangoError 11: forbidden
2017-11-17T08:25:12Z [2364] ERROR !      throw error;
2017-11-17T08:25:12Z [2364] ERROR !      ^

127.0.0.1:8529@example>
```

**Comment by jsteemann** [comment] 2017-11-17 10:08
I can't reproduce that behavior with current 3.2 (3.2.6 and 3.2.7). The above output indicates that you were using 3.2.0. So chances are that this was a bug in 3.2.0 that has been fixed in the meantime. Can you give a newer version a try?

**Comment by mohamed-barakat** [comment] 2017-11-17 16:24
Thank you very much Jan, the error disappeared with 3.2.7 :)

```
arangosh --server.username root@example --server.database example --server.password xyz

                                       _
  __ _ _ __ __ _ _ __   __ _  ___  ___| |__
 / _` | '__/ _` | '_ \ / _` |/ _ \/ __| '_ \
| (_| | | | (_| | | | | (_| | (_) \__ \ | | |
 \__,_|_|  \__,_|_| |_|\__, |\___/|___/_| |_|
                       |___/

arangosh (ArangoDB 3.2.7 [darwin] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2m  2 Nov 2017)
Copyright (c) ArangoDB GmbH

Pretty printing values.
Connected to ArangoDB 'http+tcp://127.0.0.1:8529' version: 3.2.7 [server], database: 'example', username: 'root@example'

Type 'tutorial' for a tutorial or 'help' to see common examples
127.0.0.1:8529@example> db.good;
[ArangoCollection 3844142, "good" (type document, status unloaded)]

127.0.0.1:8529@example> col = db.good
[ArangoCollection 3844142, "good" (type document, status unloaded)]

127.0.0.1:8529@example> db._truncate(col);

127.0.0.1:8529@example> db.good;
[ArangoCollection 3844142, "good" (type document, status loaded)]

127.0.0.1:8529@example>
```

**Closed** 2017-11-17 16:24 UTC
Labels: 2 Cannot Reproduce, 3 Cluster, Waiting User Reply
