### ISSUE TITLE
[BUG] Get Recent Doc By Date (in a subquery)

### ISSUE THREAD

**Issue by p30arena** [arangodb/arangodb#12835] opened 2020-10-11 07:29 UTC
## My Environment

* __ArangoDB Version__:        3.7.2
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Operating System__:        CentOS 7
* __Total RAM in your machine__:        8Gb
* __Disks in use__:        HDD

## Component, Query & Data

__AQL query __:
```
FOR s IN crawler_sites
        LET last_crawl_log = FIRST(FOR lc IN crawler_logs
          FILTER s._key == lc.siteId AND lc.is_single_product != true
          SORT lc.begin DESC
          LIMIT 1
          RETURN UNSET(lc, "failedAPIOperations", "links")
        )
        SORT last_crawl_log.begin ASC
      RETURN {
        siteId: s._key,
        link: s.link,
        begin: last_crawl_log.begin
      }
```

__Problem__:

I need to sort "websites" based on their recent crawl date.
when in the loop, last_crawl_log is assigned by a date older than the recent date.
but if I run the subquery as a separate query, last_crawl_log  is assigned correctly.

to correct the query I changed it to:
__AQL query __:

```
FOR s IN crawler_sites
        LET last_crawl_log_max_date = FIRST(FOR lc IN crawler_logs
          FILTER s._key == lc.siteId AND lc.is_single_product != true
          COLLECT AGGREGATE max_date = MAX(lc.begin)
          RETURN max_date
        )
        LET last_crawl_log = FIRST(FOR lc IN crawler_logs
          FILTER lc.begin == last_crawl_log_max_date
          LIMIT 1
          RETURN UNSET(lc, "failedAPIOperations", "links")
        )
        SORT last_crawl_log.begin ASC
      RETURN {
        siteId: s._key,
        link: s.link,
        begin: last_crawl_log.begin
      }
```

**Comment by goedderz** [comment] 2020-10-12 08:58
Hi @p30arena, thanks for reporting!

This is probably a duplicate of https://github.com/arangodb/arangodb/issues/12693. Could you try and turn off the optimizer rule `splice-subqueries`? See https://www.arangodb.com/docs/stable/aql/execution-and-performance-optimizer.html#turning-specific-optimizer-rules-off how to do that. If that works around your problem it would reassure my guess, or otherwise disprove it.

If this is indeed the same bug, I can already tell you that it is already fixed and the fix will be available in 3.7.3.

Best,

Tobias

**Comment by p30arena** [comment] 2020-10-12 12:18
@goedderz 
Hi Tobias!
Yes, that's the issue.

![image](https://user-images.githubusercontent.com/1261332/95745638-4f52e500-0ca2-11eb-9fd8-e7a215fc0855.png)

**Comment by p30arena** [comment] 2020-10-12 12:24
Duplicate of #12693

**Closed** 2020-10-12 12:23 UTC
