### ISSUE TITLE
Auto-register Foxx Model lifecycle events in Foxx Repository

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1257] opened 2015-02-26 06:57 UTC
I’m trying to add an updatedAt field to my model and have a couple of questions.

```
Foxx.Model.extend({
  schema: {
    name: Joi.string().trim(),
    updatedAtTimestamp: Joi.date()
  },
```

I think the model should be responsible for setting updatedAtTimestamp. I tried overwriting the model’s `set` method, but it seems that the repository calls `set` too late for my purpose.

Next, try it with a `beforeSave` hook. But where? The documentation for Backbone’s extend suggests to define an `initialize` function. However, initialize is never called. Is extend perhaps from an older version of Backbone? Would it make sense to upgrade to the latest version of extend for the next version of ArangoDB?

Anyways, implementing a constructor for my model instead
```
  constructor: function() {
    this.on('beforeUpdate', (data) => data.updatedAtTimestamp = Date.now());
    Foxx.Model.apply(this, arguments);
  }
```
Now isn’t it a bit weird to have the EventEmitter (my model) register itself as listener? I think it would be nicer if I could just implement a beforeSave method on my model and the repository would automatically call it if it exists.

I also find it unintuitive that my beforeUpdate handler can’t use this.set and has to modify the passed-in data instead (and thereby bypassing schema validation).

And then I noticed that several methods on Foxx.Repository are not emitting any of the lifecycle events:
- updateById
- replace
- replacebyId

I think all three methods should emit the same events as update does.

**Comment by pekeler** [comment] 2015-02-26 07:00
Consider an implementation of Repository.update like this
```
  update: function (model, data) {
    'use strict';
    model.set(data); // do this first so lifecycle methods on model have latest values
    model.beforeUpdate && model.beforeUpdate();
    model.beforeSave && model.beforeSave();
    if (model.isValid) {
      var id = model.get("_id") || model.get("_key"),
        id_and_rev = this.collection.update(id, model.forDB());
      model.set(id_and_rev);
      model.afterUpdate && model.afterUpdate();
      model.afterSave && model.afterSave();
      return model;
    } else {
      // do something about the validation error
    }
  },
```
It would allow me to implement my model like
```
Foxx.Model.extend({
  schema: {
    name: Joi.string().trim(),
    updatedAtTimestamp: Joi.date()
  },
  beforeUpdate: function() {
    this.set({updatedAtTimestamp: Date.now()});
  }
```

**Comment by pluma** [comment] 2015-02-26 23:36
For context: see #1096 for the original discussion of the lifecycle events.

**Comment by pekeler** [comment] 2015-02-27 17:34
Thanks @pluma - I've read the PR and the discussion on Google Groups. Doesn't really change any of my questions/feedback, though.

The original Google Groups discussion mentions emitting events from Repository.replace and Repository.replaceById. I wonder why this wasn't included in the implementation.

@moonglum @sarhugo do you have any feedback?

**Comment by pekeler** [comment] 2015-02-27 17:43
Here's my latest model
```
var Model = Foxx.Model.extend({
  schema: {
    name: Joi.string().trim(),
    createdAtTimestamp: Joi.number().integer(),
    updatedAtTimestamp: Joi.number().integer()
  },
  constructor: function() {
    this.on('beforeUpdate', (data) => data.updatedAtTimestamp = Date.now());
    this.on('beforeCreate', () => {
      var now = Date.now();
      this.set({createdAtTimestamp: now, updatedAtTimestamp: now});
    });
    Foxx.Model.apply(this, arguments);
  }
});
```
which I think demonstrates that the beforeUpdate usecase is a bit inconsistent with beforeCreate. And this only works as long as my controller only uses repository.save and repository.update (because replace, replaceById, and updateById don't emit events).

Or am I doing this all wrong? :)

**Comment by pluma** [comment] 2015-02-28 01:15
@pekeler That wasn't really intended as an answer, just as additional context for this issue.

I agree that having an event emitter per-instance isn't exactly super useful for most use cases.

**Comment by pluma** [comment] 2015-05-06 10:16
Fixed via #1287.

**Comment by pekeler** [comment] 2015-05-06 16:17
@pluma I don't quite understand how making the Repository emit the same events as the model is helpful. Are you suggesting the model should subscribe to the repository events instead of its own?

**Comment by pluma** [comment] 2015-05-06 16:23
@pekeler If you want to listen to all models, you can just listen to the repository. The repository emits lifecycle events for all models.

In other words: instead of doing `this.on('beforeSave', fn)` in the constructor you can do `repo.on('beforeSave', fn)` once. Listening to yourself is a bit of an anti-pattern, especially if you have to do it in the constructor. Because there's no sane way to have the model *types* themselves be event emitters and handle sub-types (i.e. `extend`) properly, the event emitter is on the repos instead of the model types.

**Comment by sarhugo** [comment] 2015-05-06 16:36
Sorry the delay of my response, I was with another projects. The Repository as an emitter for its models (as @pluma suggested and implemented in #1287 ) was the needed step and I think solves the problem mentioned by @pekeler .
I agree than having the model listen to himself is an antipattern but every improvement may start with some wrong implementation ;)

**Comment by pekeler** [comment] 2015-05-06 16:46
Sorry, I'm still a little confused. The event handlers, for example beforeCreate for setting calculated default values on new model instances, belong to the model's responsibility. I think what you're suggesting is that somewhere in my model's module I do `repo.on('beforeCreate', someStaticMethodInTheModelsModule)`. I agree that this solves the problem of listening to itself, but the cost is that the model knows about the repository (and since the repository know about the model, we created a circular dependency).

**Comment by pluma** [comment] 2015-05-06 16:55
You can put `repo.on('beforeCreate', someStaticMethodInTheModelsModule)` wherever you want. I would recommend putting it in the code that also tells the repo what model to use.

I guess the coupling could be further reduced by having static methods on the model and auto-registering them with the repo when the repo is initialized. At initialization, the repo already needs to know about the model type, so that would add no additional coupling.

Example:

```js
var MyModel = Foxx.Model.extend({
  schema: ...
}, {
  beforeSave: function (model) {
    if (!model.validate()) throw new Error('Not valid!');
  }
});
var repo = new MyRepo(myCollection, {model: MyModel});
var invalid = new MyModel({invalid: 'data'});
repo.save(invalid); // throws
```

**Comment by pekeler** [comment] 2015-05-06 17:14
@pluma yes, auto-registering would be ideal IMO. So, all I'd need to do is add a beforeSave method to my model and it'll be automatically called before every save. This would be similar to what I suggested in my second comment from Feb 26 on this issue.

**Comment by pluma** [comment] 2015-05-07 13:45
@pekeler Can you try the devel version and see whether that solves your problem? The example I proposed should work now.

**Closed** 2015-05-07 13:44 UTC
Labels: Feature, foxx

**Comment by pekeler** [comment] 2015-05-07 16:06
The latest devel doesn't build for me right now (undefined symbols for RestSimpleHandler). So I just looked at the implementation of the latest repository.js and it looks good :+1:

**Comment by Soultripper** [comment] 2016-01-25 21:28
Hi,

I just wanted to come back to this, as I noticed the OP mentioned about the following events not being emitted:

* updateById
* replace
* replacebyId

But no-one seem to address this. I am writing an data import Foxx service, and often I just want to replace the whole model with the new changes from the 3rd party. I then want to run a transformation of that data to upsert another normalised graph model based on the latest version.

Therefore, if there entity already exists, I perform a `PUT` operation which uses the `replaceById` function.

I was hoping before a `afterUpdate` event to be emitted so I can then run the AQL upsert query.

Are these functions likely to call emit events in the near future? And if not, can I ask why so I understand the thinking behind it.

Thanks

**Comment by pluma** [comment] 2016-01-25 22:03
@Soultripper thanks for your interest.

For `updateById` (and other methods that don't operate on model instances) this is by design. These methods are an example for where the repository/model abstraction in Foxx breaks down. For `replace` and `replaceById` an event could probably be emitted.

I wouldn't recommend relying on the event logic and the model/repository abstraction too much. While they will continue to be supported in 2.x the upcoming new version of Foxx (currently targeting ArangoDB 3.0) will do away with repositories and embrace the underlying collections API instead (there will still be a mechanism for schema validation but with less overhead)..
