### ISSUE TITLE
Offset problems

### ISSUE THREAD

**Issue by welovelain** [arangodb/arangodb#2928] opened 2017-08-02 09:33 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1

Mode:
- [x ] Single-Server

On this operating system:

  - [x ] Fedora .rpm

I'm issuing AQL via:
- [x ] web interface with this browser:     running on this OS: Fedora
- [ x] this Driver: 4.1.10

The following problem occurs: 

I have next query:
FOR c IN users_categories
FILTER c._key == @catID
    FOR u IN c.users 
        FOR u2 IN users FILTER u == u2._key 
        LIMIT 0, 4
        RETURN u2
        
It returns 4 results, as planned. (I have 4 records)
If I set LIMIT 1, 4 it returns only 2 records. The second record is skipped, even though offset is set only to 1.

If I have only 2 records to show, LIMIT 1, 1 shows no records at all. Somehow it skips the second record in this query.

**Comment by jsteemann** [comment] 2017-08-02 09:39
Which exact ArangoDB version do you use? 
Others have reported bugs that look somewhat similar: #2889 and #2879 
I will check whether they have the same root cause as the issue you reported.

**Comment by welovelain** [comment] 2017-08-02 09:41
I use 3.1.10, but I tried it on 3.1.26 with the same behavior.

**Comment by jsteemann** [comment] 2017-08-02 12:06
It seems this issue is about a simliar problem as in #2879, but it is not fixed by the bugfix for #2879. 
I have pushed a separate bugfix for it in a PR (https://github.com/arangodb/arangodb/pull/2931).
If all tests pass, this PR and thus the bugfix should be included in release 3.1.27

**Comment by jsteemann** [comment] 2017-08-07 07:34
3.1.27 has been released and is available for download now:
https://www.arangodb.com/repositories/archive/arangodb31/

**Closed by jsteemann** 2017-08-07 07:34 UTC
Labels: 1 Bug, 2 Fixed, 3 AQL
