### ISSUE TITLE
`--starter.wait` hangs even though arango is up

### ISSUE THREAD

**Issue by MrCreosote** [arangodb/arangodb#9997] opened 2019-09-12 02:16 UTC
## My Environment

* __ArangoDB Version__:        3.5.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               Nothing special
* __Infrastructure__:               My laptop
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        10Gb in VM, 32GB total
* __Disks in use__:        SSD
* __Used Package__:             tar

## Component, Query & Data

__Affected feature__:
arangodb

__AQL query (if applicable)__:
n/a

__AQL explain (if applicable)__:
n/a

__Dataset__:
n/a
__Size of your Dataset on disk__:
n/a

__Replication Factor & Number of Shards (Cluster only)__:
n/a

## Steps to reproduce

1. Start arangodb with `start --starter.wait`:
```
~/arango/3.5.0/bin$ ./arangodb start --server.arangod=../usr/sbin/arangod --starter.wait --starter.mode single --starter.data-dir ~/arango/data
2019-09-11T19:10:46-07:00 |INFO| Starting arangodb version 0.14.12, build bbe2973 in the background component=arangodb
2019-09-11T19:10:46-07:00 |INFO| Waiting for starter API to be available... component=arangodb
2019-09-11T19:10:46-07:00 |INFO| Waiting for database instances to be available... component=arangodb
```

2. At this point `arangodb` hangs indefinitely.
3. Curl the service to ensure it's running:
```
curl http://localhost:8529/ -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8529 (#0)
> GET / HTTP/1.1
> Host: localhost:8529
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< X-Content-Type-Options: nosniff
< Location: /_db/_system/_admin/aardvark/index.html
< Server: ArangoDB
< Connection: Keep-Alive
< Content-Type: application/json; charset=utf-8
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

4. Remove the `--starter-wait` option:
```
~/arango/3.5.0/bin$ ./arangodb start --server.arangod=../usr/sbin/arangod  --starter.mode single --starter.data-dir ~/arango/data
2019-09-11T19:13:06-07:00 |INFO| Starting arangodb version 0.14.12, build bbe2973 in the background component=arangodb
2019-09-11T19:13:06-07:00 |INFO| Waiting for starter API to be available... component=arangodb
~/arango/3.5.0/bin$ 
```

5. `arangodb` returns immediately
6. curl results in the same as above

__Problem__:
`arangodb start --starter.wait` hangs even while the server is up

__Expected result__:
The command returns

**Comment by dothebart** [comment] 2020-09-04 09:00
This behaviour seems to have been fixed with later Arangodb releases, can't reproduce:
```
willi@bruecklinux:/tmp/arangodb3-3.6.4/bin$ ./arangodb start --server.arangod=../usr/sbin/arangod --starter.wait --starter.mode single --starter.data-dir /tmp/abc
2020-09-04T10:58:34+02:00 |INFO| Starting arangodb version 0.14.14, build 598e7d7 in the background component=arangodb
2020-09-04T10:58:34+02:00 |INFO| Waiting for starter API to be available... component=arangodb
2020-09-04T10:58:34+02:00 |INFO| Waiting for database instances to be available... component=arangodb
2020-09-04T10:58:34+02:00 |INFO| Database instances are available. component=arangodb
```
and:
```
willi@bruecklinux:/tmp/arangodb3-3.6.4/bin$ ps -eaf |grep arangod  |grep 8529
willi    2946313 2944827  1 10:57 pts/4    00:00:00 /tmp/arangodb3-3.6.4/usr/sbin/arangod -c /tmp/xxx/single8529/arangod.conf --database.directory /tmp/xxx/single8529/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /tmp/xxx/single8529/apps --log.file /tmp/xxx/single8529/arangod.log --log.force-direct false --javascript.copy-installation true --foxx.queues true --server.statistics true
```
Hence closing as fixed. 

Please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.

**Closed by dothebart** 2020-09-04 09:00 UTC
Labels: 3 Starter
