### ISSUE TITLE
Internal Error on use of simple REPLACE_NTH query

### ISSUE THREAD

**Issue by arango-db-us3r** [arangodb/arangodb#13669] opened 2021-03-09 21:04 UTC
## My Environment

* __ArangoDB Version__:        3.7.9
* __Storage Engine__:             RocksDB
* __Deployment Mode__:        Single Server
* __Deployment Strategy__:  ArangoDB Starter in Docker
* __Configuration__:               No extra configuration
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__: 16GB
* __Disks in use__:        SSD
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__:
AQL query using web interface and python driver

__AQL query (if applicable)__:
```
FOR doc IN temp
RETURN REPLACE_NTH(doc.v, 0, 0, 0)

```
__AQL explain and/or profile (if applicable)__:
```
Query String (50 chars, cacheable: true):
 for doc in temp
 return REPLACE_NTH(doc.v, 0, 0, 0)

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode      1     - FOR doc IN temp   /* full collection scan, projections: `v` */
  3   CalculationNode              1       - LET #1 = REPLACE_NTH(doc.`v`, 0, 0, 0)   /* simple expression */   /* collections used: doc : temp */
  4   ReturnNode                   1       - RETURN #1

Indexes used:
 none

Functions used:
 Name          Deterministic   Cacheable   Uses V8
 REPLACE_NTH   true            true        false  

Optimization rules applied:
 Id   RuleName
  1   reduce-extraction-to-projection
```
__Dataset__:
Empty dataset that gets populated by creating empty collection, temp, and inserting the entry {v:[1]} into it

__Size of your Dataset on disk__:
0b

## Steps to reproduce

1. Create empty collection, `temp`
2. Run simple insertion: `INSERT {v:[1]} INTO temp`
3. Run above query

__Problem__:
Query does not finish, giving the generic error: `Query: Expecting Array slice (while executing) (exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:320). Please report this error to arangodb.com`

__Expected result__:
Query to finish without error and return the value [ [ 0 ] ]

**Comment by Simran-B** [comment] 2021-03-10 15:45
Duplicate of #13632

**Closed by Simran-B** 2021-03-10 15:45 UTC
