### ISSUE TITLE
Data Loss - Plus a couple of other issues/bugs

### ISSUE THREAD

**Issue by p30arena** [arangodb/arangodb#3376] opened 2017-10-05 11:12 UTC
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2.3

This one might be related to [issue 3226](https://github.com/arangodb/arangodb/issues/3226)
But I made sure that the keys on both databases are different and don't collide, so better forget about that issue.
-- I did not do a full restart after fixing db keys.
-- I deleted dev db, then created a new empty one, with collection keys starting from 1.

I had a doc on production with key 16315018.
You can see in the video, that page 2 of businesses is not shown caused by this error:

http://localhost:12000/_db/yabco/_api/cursor
Status Code:202 Accepted

REQ:
`{"query":"FOR x IN @@collection LET att = APPEND(SLICE(ATTRIBUTES(x), 0, 25), \"_key\", true) LIMIT @offset, @count RETURN KEEP(x, att)","bindVars":{"@collection":"business","offset":10,"count":10}}`

http://localhost:12000/_db/yabco/_api/job/150649301542154
Status Code:201 Created

RES:
`"warnings":[{"code":1542,"message":"invalid argument type in call to function 'ATTRIBUTES()'"},{"code":1542,"message":"invalid argument type in call to function 'SLICE()'"},{"code":1542,"message":"invalid argument type in call to function 'KEEP()'"}]`

**and the doc is wiped out!**
When I want to recreate it, theres an error because of indexes,
I delete the index,
Try to recreate it, I fail.

Just watch the video:

https://youtu.be/q4pLcAcW0hU

Hopefully I had a backup of the db at 7 am, this disaster happened around 12.

**Comment by baslr** [comment] 2017-10-05 12:37
@p30arena is it possible to share the original collection files to investigate the root cause?

**Comment by baslr** [comment] 2017-10-05 12:43
@p30arena when you filtering for the `_key` attribute you have to enclose the _key with double ticks `"16315018"`.

**Comment by p30arena** [comment] 2017-10-05 16:57
@baslr https://ufile.io/ghb8v

I can give arangodb's core team root access to my vps **only if needed**.

**Comment by baslr** [comment] 2017-10-05 19:25
@p30arena thanks. I will have a look.
Is it possible to share the original database files e.g. the databases directory or the rocksdb directory with which the error occurs?

**Comment by p30arena** [comment] 2017-10-06 06:51
@baslr 
Here it is: https://ufile.io/5lh2o

**Comment by baslr** [comment] 2017-10-06 11:04
@p30arena thanks.

I started ArangoDB v3.2.3 and pointing it to your arangodb3 directory. I can access the `business` collection in the `yabco` database and filter for and open the document with _key `'16315018'`. With a probability bordering on certainty the problem is not the arangodb3 directory but maybe a hardware / software problem beyond the scope of ArangoDB.

**Comment by p30arena** [comment] 2017-10-06 11:17
@baslr 
This is my production db, I told before and showed it in the video, I recreated the doc.
Because of these instabilities I take backups every 8 hours, the first link was my backup.
The second one is the data after restoration.

Also I've reported 3 different bugs, I don't know what is confusing you.

1- Second page of the business collection is not shown, You can see the errors in the first msg and in the video.
2- When the data is lost, Indexes are still there, I must delete the indexes so I can recreate the doc with the _key 16315018.
3- I can't recreate the index, because of duplication of data apparently?! but there are no duplicates.

**Comment by baslr** [comment] 2017-10-06 12:48
@p30arena so there is no dump of the database directory before deletion of _key `'16315018'` to have a look at file level what data is there for _key `'16315018'`?

**Comment by p30arena** [comment] 2017-10-06 13:27
@baslr Can you find accesses to the doc from the logs?
or can you tell me how to do that?
Unfortunately auditing is only available in enterprise edition.

**Comment by p30arena** [comment] 2017-10-06 16:48
> @p30arena so there is no dump of the database directory before deletion of _key '16315018' to have a look at file level what data is there for _key '16315018'?

no its not available.
I also rechecked our code base, we have no code for deleting a business.

**Comment by p30arena** [comment] 2017-10-06 18:15
I'm going for a restart,
lets see what happens next.

```
service arangodb3 stop
Stopping arangodb3 (via systemctl):                        [  OK  ]
```

it took about 10 seconds.

`service arangodb3 start`

it took a second.

```
service arangodb3 status

● arangodb3.service - ArangoDB database server
   Loaded: loaded (/usr/lib/systemd/system/arangodb3.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-10-06 18:11:03 GMT; 18s ago
  Process: 6698 ExecStartPre=/bin/chmod 700 /var/lib/arangodb3-apps (code=exited, status=0/SUCCESS)
  Process: 6696 ExecStartPre=/bin/chown -R arangodb:arangodb /var/lib/arangodb3-apps (code=exited, status=0/SUCCESS)
  Process: 6693 ExecStartPre=/bin/chmod 700 /var/lib/arangodb3 (code=exited, status=0/SUCCESS)
  Process: 6691 ExecStartPre=/bin/chown -R arangodb:arangodb /var/lib/arangodb3 (code=exited, status=0/SUCCESS)
  Process: 6688 ExecStartPre=/bin/chmod 700 /var/log/arangodb3 (code=exited, status=0/SUCCESS)
  Process: 6686 ExecStartPre=/bin/chown -R arangodb:arangodb /var/log/arangodb3 (code=exited, status=0/SUCCESS)
  Process: 6684 ExecStartPre=/usr/bin/install -g arangodb -o arangodb -d /var/run/arangodb3 (code=exited, status=0/SUCCESS)
  Process: 6683 ExecStartPre=/usr/bin/install -g arangodb -o arangodb -d /var/tmp/arangodb3 (code=exited, status=0/SUCCESS)
 Main PID: 6700 (arangod)
   Memory: 522.3M
   CGroup: /system.slice/arangodb3.service
           └─6700 /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb3/arangod.pid --temp.path /var/tmp/arangodb3 --log.foreground-tty true

Oct 06 18:11:03 srv39568.screweb.com arangod[6700]: 2017-10-06T18:11:03Z [6700] WARNING {memory} /sys/kernel/mm/transparent_hugepage/enabled is set to 'always'. It is rec...r 'madvise'
Oct 06 18:11:03 srv39568.screweb.com arangod[6700]: 2017-10-06T18:11:03Z [6700] WARNING {memory} /sys/kernel/mm/transparent_hugepage/defrag is set to 'always'. It is reco...r 'madvise'
Oct 06 18:11:03 srv39568.screweb.com arangod[6700]: 2017-10-06T18:11:03Z [6700] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/enabled"'
Oct 06 18:11:03 srv39568.screweb.com arangod[6700]: 2017-10-06T18:11:03Z [6700] WARNING {memory} execute 'sudo bash -c "echo madvise > /sys/kernel/mm/transparent_hugepage/defrag"'
Oct 06 18:11:03 srv39568.screweb.com arangod[6700]: 2017-10-06T18:11:03Z [6700] INFO using storage engine mmfiles
Oct 06 18:11:03 srv39568.screweb.com arangod[6700]: 2017-10-06T18:11:03Z [6700] INFO {cluster} Starting up with role SINGLE
Oct 06 18:11:03 srv39568.screweb.com arangod[6700]: 2017-10-06T18:11:03Z [6700] INFO {syscall} file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
Oct 06 18:11:03 srv39568.screweb.com arangod[6700]: 2017-10-06T18:11:03Z [6700] INFO Authentication is turned on (system only), authentication for unix sockets is turned on
Oct 06 18:11:05 srv39568.screweb.com arangod[6700]: 2017-10-06T18:11:05Z [6700] INFO using endpoint 'http+tcp://127.0.0.1:8529' for non-encrypted requests
Oct 06 18:11:08 srv39568.screweb.com arangod[6700]: 2017-10-06T18:11:08Z [6700] INFO ArangoDB (version 3.2.3 [linux]) is ready for business. Have fun!
Hint: Some lines were ellipsized, use -l to show in full.
```

The DB Server is breathing fresh air right now.

**Comment by p30arena** [comment] 2017-10-06 18:32
I'm trying to gather clues.

I can see that DOC 16315018 was somehow corrupted,
I couldn't query it, but when was exploring pages, on 2nd page, I received error:

`invalid argument type in call to function 'ATTRIBUTES()`

and this is the query:

`FOR x IN @@collection LET att = APPEND(SLICE(ATTRIBUTES(x), 0, 25), \"_key\", true) LIMIT @offset, @count RETURN KEEP(x, att)`

So what was in x that caused the error?

Then I tried to recreate 16315018, I got an error, it says its there and I can not make  a dup.
What?
I delete the index on _key attr, then I try again, its successful.

So the doc was purged somehow?! but the indexes were still there.
So the query contained a doc that was pointing to some VOID space.

I can show you a more interesting Video that shows another **BUG**:

https://youtu.be/RNS7700XlWU

**Comment by baslr** [comment] 2017-10-09 00:39
@p30arena your advertising bug is not a bug.

![bildschirmfoto 2017-10-09 um 02 35 35](https://user-images.githubusercontent.com/1494154/31322560-8ed31f30-ac9a-11e7-8486-7e7bea0c99e9.png)

You could switch to https://en.wikipedia.org/wiki/UBlock_Origin.

**Comment by p30arena** [comment] 2017-10-09 07:03
@baslr  haha It was due to AdBlocker, what a nasty extension 😸

**Comment by baslr** [comment] 2017-10-09 13:38
@p30arena 
regarding your data loss issue here, was it a fresh arangod installation or does the arangod experienced a double restore as in #3226?

**Comment by p30arena** [comment] 2017-10-09 15:43
@baslr It was a fresh installation, then an arangorestore...

**Comment by p30arena** [comment] 2017-10-11 16:13
@baslr Do you suggest I clear the whole data, and restore it again?

**Comment by baslr** [comment] 2017-10-11 17:01
@p30arena 
yes, do a clean reinitialization of the database.

If this problem occurs again, please do a copy of the database directory before everything else so we can investigate the database files.

**Comment by baslr** [comment] 2017-10-12 13:51
@p30arena I close this issue now. If the error appears again please reopen the issue and we will happy to investigate.

**Closed by baslr** 2017-10-12 13:51 UTC
Labels: 2 Cannot Reproduce
