### ISSUE TITLE
Unit Test is broken in 2.6a3

### ISSUE THREAD

**Issue by omarsmak** [arangodb/arangodb#1377] opened 2015-06-15 13:12 UTC
Whenever I try to run mocha unit test runner from either the frontend or the cmd line, this errors shown in the logs:

```javascript
2015-06-15T13:02:56Z [602] ERROR Error in foxx route '{ "match" : "/foxxes/tests", "methods" : [ "post" ] }': '[ArangoError 3103: failed to invoke module
2015-06-15T13:02:56Z [602] ERROR File: /foxx_apps/_db/_system/vn/api/APP/test/example.js]', Stacktrace: [ArangoError 3103: failed to invoke module
2015-06-15T13:02:56Z [602] ERROR File: /foxx_apps/_db/_system/vn/api/APP/test/example.js]
2015-06-15T13:02:56Z [602] ERROR   at [object Object].Module.run (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/common/bootstrap/modules.js:1417:20)
2015-06-15T13:02:56Z [602] ERROR   at ArangoApp.loadAppScript (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/foxx/arangoApp.js:417:26)
2015-06-15T13:02:56Z [602] ERROR   at /usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/foxx/mocha.js:91:33
2015-06-15T13:02:56Z [602] ERROR   at Array.forEach (native)
2015-06-15T13:02:56Z [602] ERROR   at Object.runMochaTests [as run] (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/foxx/mocha.js:88:11)
2015-06-15T13:02:56Z [602] ERROR   at Object.runTests (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/foxx/manager.js:777:45)
2015-06-15T13:02:56Z [602] ERROR   at /usr/local/Cellar/arangodb/HEAD/share/arangodb/js/apps/system/_admin/aardvark/APP/foxxes.js:279:26
2015-06-15T13:02:56Z [602] ERROR   at Object.res.action.callback (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/foxx/internals.js:101:5)
2015-06-15T13:02:56Z [602] ERROR   at /usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/foxx/routing.js:324:19
2015-06-15T13:02:56Z [602] ERROR   at execute (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/actions.js:1318:7)
2015-06-15T13:02:56Z [602] ERROR   at next (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/actions.js:1335:7)
2015-06-15T13:02:56Z [602] ERROR   at routingInfo.middleware.push.action.callback (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/foxx/controller.js:639:53)
2015-06-15T13:02:56Z [602] ERROR   at execute (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/actions.js:1318:7)
2015-06-15T13:02:56Z [602] ERROR   at next (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/actions.js:1335:7)
2015-06-15T13:02:56Z [602] ERROR   at routingInfo.middleware.push.action.callback (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/foxx/controller.js:603:13)
2015-06-15T13:02:56Z [602] ERROR   at execute (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/actions.js:1318:7)
2015-06-15T13:02:56Z [602] ERROR   at next (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/actions.js:1335:7)
2015-06-15T13:02:56Z [602] ERROR   at [object Object]:386:5
2015-06-15T13:02:56Z [602] ERROR   at execute (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/actions.js:1318:7)
2015-06-15T13:02:56Z [602] ERROR   at next (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/actions.js:1335:7)
2015-06-15T13:02:56Z [602] ERROR   at routingInfo.middleware.push.action.callback (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/foxx/controller.js:639:53)
2015-06-15T13:02:56Z [602] ERROR   at execute (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/actions.js:1318:7)
2015-06-15T13:02:56Z [602] ERROR   at next (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/actions.js:1335:7)
2015-06-15T13:02:56Z [602] ERROR   at routingInfo.middleware.push.action.callback (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/foxx/controller.js:639:53)
2015-06-15T13:02:56Z [602] ERROR   at execute (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/actions.js:1318:7)
2015-06-15T13:02:56Z [602] ERROR   at next (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/actions.js:1335:7)
2015-06-15T13:02:56Z [602] ERROR   at routingInfo.middleware.push.action.callback (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/foxx/controller.js:603:13)
2015-06-15T13:02:56Z [602] ERROR   at execute (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/actions.js:1318:7)
2015-06-15T13:02:56Z [602] ERROR   at next (/usr/local/Cellar/arangodb/HEAD/share/arangodb/js/server/modules/org/arangodb/actions.js:1335:7)
2015-06-15T13:02
```

Using the following platform:
MacOX 10.9
ArangoDB 2.6a3 (DEV mode)

I found this issue has been reported here (https://github.com/arangodb/arangodb/issues/1366), but I am not sure if both tickets are indeed, the same error.

Thanks

**Comment by pluma** [comment] 2015-06-16 07:32
That sounds like a problem with the test itself. Can you run the file through jshint and see if it complains about any syntax errors?

Either way, the frontend should be showing the root cause, not the "failed to run module" exception.

**Comment by pluma** [comment] 2015-06-16 07:33
Just a note: #1366 is about ArangoDB's own tests, not the test runner itself. The two issues are unrelated.

**Comment by omarsmak** [comment] 2015-06-16 08:52
Hi Alan,

I just ran jshint against the unit test file, it didn't show any syntax errors. By the way, this unit test file was generated by the new app creation scaffolding within 2.6a3. It created the following unit test file under '/test/example.js' :
```javascript
/*global describe, it */
'use strict';
var expect = require('chai').expect;

describe('science', function () {
  it('works', function () {
    expect(true).to.not.equal(false);
  });
});
```

And this is the generated manifest:
```
{
  "name": "TesAppd",
  "description": "sdsds",
  "author": "Omar",
  "version": "0.0.1",
  "license": "Apache 2",
  "controllers": {
    "/" : "router.js"
  },
  "scripts": {
    "setup": "scripts/setup.js",
    "teardown": "scripts/teardown.js"
  },
  "tests": "test/**/*.js"
}
```

**Comment by pluma** [comment] 2015-06-16 09:41
Weird. I can't reproduce the issue with the current devel branch.

Could you upload the zip bundle of your generated app somewhere?

**Comment by omarsmak** [comment] 2015-06-16 10:03
Yes sure, I have shared it on my Dropbox (https://www.dropbox.com/s/10gooys0fdrgcn8/app.zip?dl=0). Not that you will need 2.6-alpha3, most probably be the devel branch is ahead of the latest unstable public release which is 2.6-alpha3

**Comment by pluma** [comment] 2015-06-16 11:44
Yeah, it's not reproducible in devel. I'll see whether I can reproduce it with 2.6-alpha3.

**Comment by omarsmak** [comment] 2015-06-22 10:21
Apparently the issue was from 'chai' package. I tried to install chai package locally in the app's folder (created node_modules folder) and it worked fine afterwards. It looks Arango doesn't require the correct 'chai' package. 

By the way, I have installed the latest version, 2.6, unfortunately  the same error was there as well. I have tried it as well on a fresh Ubuntu 14.04 DigitalOcean instance, the same error was replicable there as well.

**Comment by pluma** [comment] 2015-07-01 14:47
I can't reproduce the problem in the 2.6 branch nor the devel branch.

**Comment by pisaruk** [comment] 2015-07-01 21:16
I am facing the same issue now in Ubuntu 12.04 with ArangoDB 2.6.1

**Comment by omarsmak** [comment] 2015-07-01 21:23
@pluma did you make sure not to have the `node_module` folder inside the app folder? There is something wrong about `require('chai')` I guess. 

For now the workaround is to install the chai locally into the  `node_module` folder

**Comment by pluma** [comment] 2015-07-01 23:19
@omarsmak yes, though I've only tried local builds, not the official releases. Maybe something went wrong during packaging (as with swagger). Can you post what the dirtree of your ArangoDB's `js/node/node_modules/chai` folder looks like?

**Comment by omarsmak** [comment] 2015-07-01 23:37
Yep sure, here is the output from my terminal:
```
Omars-MacBook-Pro:chai omaral-safi$ ls -R
CONTRIBUTING.md		bower.json		karma.sauce.js		sauce.browsers.js
History.md		chai.js			lib
README.md		index.js		node_modules
ReleaseNotes.md		karma.conf.js		package.json

./lib:
chai	chai.js

./lib/chai:
assertion.js	config.js	interface	utils

./lib/chai/interface:
assert.js	expect.js	should.js

./lib/chai/utils:
addChainableMethod.js		getName.js			objDisplay.js
addMethod.js			getPathInfo.js			overwriteChainableMethod.js
addProperty.js			getPathValue.js			overwriteMethod.js
flag.js				getProperties.js		overwriteProperty.js
getActual.js			hasProperty.js			test.js
getEnumerableProperties.js	index.js			transferFlags.js
getMessage.js			inspect.js			type.js

./node_modules:
assertion-error	deep-eql

./node_modules/assertion-error:
History.md	README.md	index.js	package.json

./node_modules/deep-eql:
History.md	index.js	lib		package.json
README.md	karma.conf.js	node_modules

./node_modules/deep-eql/lib:
eql.js

./node_modules/deep-eql/node_modules:
type-detect

./node_modules/deep-eql/node_modules/type-detect:
History.md	README.md	index.js	lib		package.json

./node_modules/deep-eql/node_modules/type-detect/lib:
type.js
```

And ArangoDB's installation location on my machine:
```
Omars-MacBook-Pro:chai omaral-safi$ pwd
/usr/local/Cellar/arangodb/2.6.0/share/arangodb/js/node/node_modules/chai
```

**Comment by pluma** [comment] 2015-07-02 10:39
Okay, confirmed that it's a bug with the release package bundler. The "core" folder is missing from the chai module.

**Comment by fceller** [comment] 2015-07-03 15:05
@pluma I believe that the problem is elsewhere. If you check out 2.6 you see that "core" is also missing:

```
> ls -l
total 512
-rw-r--r--  1 fceller  staff    9438 16 Mai 22:09 CONTRIBUTING.md
-rw-r--r--  1 fceller  staff   37434 10 Jun 15:25 History.md
-rw-r--r--  1 fceller  staff    5275 10 Jun 15:25 README.md
-rw-r--r--  1 fceller  staff   29773 10 Jun 15:25 ReleaseNotes.md
-rw-r--r--  1 fceller  staff     470 10 Jun 15:25 bower.json
-rw-r--r--  1 fceller  staff  139497 10 Jun 15:25 chai.js
-rw-r--r--  1 fceller  staff      40 16 Mai 22:09 index.js
-rw-r--r--  1 fceller  staff     625 16 Mai 22:09 karma.conf.js
-rw-r--r--  1 fceller  staff    1201 16 Mai 22:09 karma.sauce.js
drwxr-xr-x  4 fceller  staff     136 10 Jun 15:25 lib
drwxr-xr-x  4 fceller  staff     136 16 Mai 22:09 node_modules
-rw-r--r--  1 fceller  staff    2092 10 Jun 15:25 package.json
-rw-r--r--  1 fceller  staff    1798 16 Mai 22:09 sauce.browsers.js
```

So I assume it has never been checked in.

**Comment by fceller** [comment] 2015-07-03 15:08
Even a reinstall does not fix the problem:

```
fceller@langenfeld:~/1_ArangoDB/ArangoDB-2.6/js/node> rm -rf node_modules/chai
fceller@langenfeld:~/1_ArangoDB/ArangoDB-2.6/js/node> npm install chai
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json glob@3.2.3 No README data
npm WARN package.json js-yaml@3.3.1 No bin file found at bin/js-yaml.js
npm WARN package.json mocha@2.2.5 No bin file found at ./bin/mocha
npm WARN package.json mocha@2.2.5 No bin file found at ./bin/_mocha
npm WARN package.json coffee-script@1.9.3 No bin file found at ./bin/coffee
npm WARN package.json coffee-script@1.9.3 No bin file found at ./bin/cake
npm WARN package.json jshint@2.8.0 No bin file found at ./bin/jshint
npm WARN package.json semver@4.3.6 No bin file found at ./bin/semver
chai@2.3.0 node_modules/chai
├── assertion-error@1.0.0
└── deep-eql@0.1.3 (type-detect@0.1.1)
fceller@langenfeld:~/1_ArangoDB/ArangoDB-2.6/js/node> ls -l node_modules/chai/
total 512
-rw-r--r--  1 fceller  staff    9438 22 Mär 19:28 CONTRIBUTING.md
-rw-r--r--  1 fceller  staff   37434 26 Apr 18:05 History.md
-rw-r--r--  1 fceller  staff    5275 26 Apr 18:05 README.md
-rw-r--r--  1 fceller  staff   29773 26 Apr 18:17 ReleaseNotes.md
-rw-r--r--  1 fceller  staff     470 26 Apr 18:04 bower.json
-rw-r--r--  1 fceller  staff  139497 26 Apr 18:04 chai.js
-rw-r--r--  1 fceller  staff      40 26 Nov  2014 index.js
-rw-r--r--  1 fceller  staff     625 26 Nov  2014 karma.conf.js
-rw-r--r--  1 fceller  staff    1201 26 Nov  2014 karma.sauce.js
drwxr-xr-x  4 fceller  staff     136  3 Jul 17:06 lib
drwxr-xr-x  4 fceller  staff     136  3 Jul 17:06 node_modules
-rw-r--r--  1 fceller  staff    2136  3 Jul 17:06 package.json
-rw-r--r--  1 fceller  staff    1798 26 Nov  2014 sauce.browsers.js
```

@pluma can you advise?

**Comment by pluma** [comment] 2015-07-03 16:25
@fceller the core folder is in node_modules/chai/lib/chai/core, not node_modules/chai/core.

Apparently someone added "core" to the .gitignore file. I've added the missing core folders manually to the devel and 2.6 branch (2.6 uses chai 2.x, devel uses chai 3.x). We should also go through the gitignore file and make sure all the ignored paths are as specific as possible. Having blanket bans on generic names like "core" is an extremely bad idea and I'm certain this will bite us again in the future if we don't fix it now.

I'm not even sure why "core" is in the list, as none of the build steps seem to generate any artefacts with that name.

**Closed by pluma** 2015-07-03 16:25 UTC
Labels: front-end

**Comment by fceller** [comment] 2015-07-03 16:30
@pluma ok, thats explains it. The comment suggested js/node/node_modules/chai/core

Agreed, we should have a careful look at the .gitignore

**Comment by komatzu** [comment] 2017-08-16 14:04
Also this is an old ticket I am experiencing the same behavior now using the latest Docker image (ArangoDB 3.2.1)  and the foxx sample app (i.e. creating a new foxx service via the web interface and running the test). Calling 
` curl -s -X POST http://localhost:8529/_api/foxx/tests/?mount=/example`
I get:
```
{
  "error": true,
  "errorNum": 3103,
  "errorMessage": "failed to invoke module\nFile: /usr/share/arangodb3/js/node/node_modules/chai/lib/chai.js",
  "code": 400
}
```
Installing npm and checking /usr/share/arangodb3/js/node with `npm ls` I see many missing dependencies. Including expect.js which is needed by the sample test :
`npm ERR! missing: expect.js@0.3.1`
After fixing this with `npm install` the test runs fine:
```
{
  "stats": {
    "suites": 1,
    "tests": 1,
    "passes": 1,
    "pending": 0,
    "failures": 0,
    "start": "2017-08-16T13:50:55.196Z",
    "end": "2017-08-16T13:50:55.199Z",
    "duration": 3
  },
  "tests": [
    {
      "title": "works",
      "fullTitle": "science works",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    }
  ],
  "pending": [],
  "failures": [],
  "passes": [
    {
      "title": "works",
      "fullTitle": "science works",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    }
  ]
}
```
Is there a chance that this gets fixed in the latest Docker image? thx

**Comment by dothebart** [comment] 2017-08-21 11:23
Hi, 
We've migrated away from expect.js since it was troublesome with the Apple code signing facilities (they would outright crash or remain stuck forever), and we also have the very similar chai.expect shipping.

In case of needing some inspiration, his is one of the commits removing our test dependencies to expect.js:

https://github.com/arangodb/arangodb/commit/ed71952418d8b6ed603afe0c30c653ddd9ace7df

So you can see its straight forward to get rid of it.

**Comment by pluma** [comment] 2017-08-22 15:59
@komatzu If replacing expect.js with chai is not an option, please consider bundling expect.js with your service by installing it with npm or yarn and including the node_modules folder in the service bundle.

**Comment by komatzu** [comment] 2017-08-22 16:21
@pluma Thx for the hint. I tried something like this, i.e. bundling chai via npm. But this produced a strange behavior: a lot of the `curl -s -X POST http://localhost:8529/_api/foxx/tests/?mount=/example` calls let to the correct response. But once in a while the error message showed up again. It looked like arango **not always** used the bundled one, but sometimes the default (broken) one.
Now I end up building my own docker image with a proper module setup :) in the default directory.
