### ISSUE TITLE
Ran into a small upgrade issue (3.1 -> 3.2)

### ISSUE THREAD

**Issue by Queatz** [arangodb/arangodb#3204] opened 2017-09-05 02:57 UTC
wanted to bring it to attention in case someone else runs into this when trying to start the service:

```
● arangodb3.service - ArangoDB database server
   Loaded: loaded (/lib/systemd/system/arangodb3.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-09-04 21:51:37 CDT; 5s ago
  Process: 4519 ExecStartPre=/usr/bin/chmod 700 /var/log/arangodb3 (code=exited, status=203/EXEC)
  Process: 4518 ExecStartPre=/usr/bin/chown -R arangodb:arangodb /var/log/arangodb3 (code=exited, status=0/SUCCESS)
  Process: 4517 ExecStartPre=/usr/bin/install -g arangodb -o arangodb -d /var/run/arangodb3 (code=exited, status=0/SUCCESS)
  Process: 4516 ExecStartPre=/usr/bin/install -g arangodb -o arangodb -d /var/tmp/arangodb3 (code=exited, status=0/SUCCESS)
```

Running

```
ln /bin/chmod /usr/bin/chmod
ln /bin/chown /usr/bin/chown
```
solved it for me.

**Comment by dothebart** [comment] 2017-09-05 07:42
Hi, 
This is a duplicate of #3197 which will be fixed with the next release. 
I will close this issue - thanks for reporting.

**Closed by dothebart** 2017-09-05 07:42 UTC
