### ISSUE TITLE
Arangorestore from a single VM to Kubernetes cluster not working. 

### ISSUE THREAD

**Issue by AbbasHallal** [arangodb/arangodb#14610] opened 2021-08-09 13:44 UTC
[arangorestore.log](https://github.com/arangodb/arangodb/files/6967728/arangorestore.log)
## My Environment

* __ArangoDB Version__:  3.7.12
* __Storage Engine__: RocksDB
* __Deployment Mode__: Cluster
* __Deployment Strategy__: Kubernetes
* __Configuration__: 3 agents, 2 coordinators and 2 db servers.
* __Infrastructure__:   Openshift
* __Operating System__:  Red Hat Enterprise Linux
* __Total RAM in your machine__:  8 cores 10 GB of RAM
* __Disks in use__:  SSD
## Component, Query & Data

__Affected feature__:
I have an ArangoDB instance running on a VM and a replica for it running on another VM.
On Kubernetes, we have an ArangoDB cluster 3 agents, 2 coordinators and 2 DB servers.
I took a logical dump from the VM and I am trying to restore it in the cluster.
Here are the commands used:
`arangodump --server.endpoint tcp://127.0.0.1:8530 --server.username root --server.password XXX--include-system-collections true --server.database dbname --output-directory "/data/backups/backup-dev/dbname" --overwrite true`

`arangorestore --server.endpoint ssl://coord.endpoint:443 --server.username root --server.database dbname --server.password XXX --create-database true --create-collection true --import-data true --include-system-collections true --replication-factor 2 --number-of-shards 2 --input-directory "/data/backups/backup-dev/dbname" --log.level "debug" --threads 4 --progress true --overwrite false --force true --server.connection-timeout 3600 --server.request-timeout 3600`

Arango deployment file:

```
apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "arangodb-cluster"
spec:
  mode: Cluster
  environment: Development #run a deployment on a small number of nodes
  externalAccess:
         type: None
  tls:
    caSecretName: None
  agents:
    count: 3
    args:
      - --log.level=debug
    storageClassName: glusterfs
    resources:
      requests:
        storage: 20Gi
  dbservers:
    count: 2
    storageClassName: glusterfs
    resources:
      requests:
        storage: 128Gi
  coordinators:
    count: 2
    image: 

"arangodb/arangodb:3.7.12"
```

 
__Size of your Dataset on disk__: 28 GB

Replication Factor: 2
Number of Shards (Cluster only)__: 2

__Problem__:
The restore process from the VM to the Kubernetes cluster is hanging at random points and no further progress is achieved as showing in the attached screenshots.  The dump process was done successfully but still the arangorestore not able to complete successfully.
Found an error on line 2500, 
`2021-08-10T10:14:09Z [88347] ERROR [3a30c] {threads} exception caught in thread 'Worker': Expecting digit`
`2021-08-10T10:14:09Z [88347] WARNING [6784f] {threads} caught exception in thread 'Worker': Expecting digit`

![image (2)](https://user-images.githubusercontent.com/63394972/128716104-369b7537-305e-4ded-83b3-b4976fd4b0b0.png)
![image (3)](https://user-images.githubusercontent.com/63394972/128716110-48e1f609-8c97-4052-956c-3f70888239ef.png)
[arango-debug_logs.zip](https://github.com/arangodb/arangodb/files/7038394/arango-debug_logs.zip)

**Comment by AbbasHallal** [comment] 2021-08-12 13:24
Hello! 
Any updates here?

**Comment by kvahed** [comment] 2021-08-18 09:35
@AbbasHallal I asked to please upload the log files. We try our best to help community users. But without complete information, don't know how to help. Upload the  debug logs from all coordinators, database servers (crdn/prmr) instances, please.

**Comment by AbbasHallal** [comment] 2021-08-24 10:13
[arango-debug_logs.zip](https://github.com/arangodb/arangodb/files/7038388/arango-debug_logs.zip)

**Comment by AbbasHallal** [comment] 2021-08-24 10:16
hello @kvahed, As disccussed before we are trying to restore a dump from single machine into a cluster of 2 DB servers, 2 coordinators and 3 agents. 
I added the log files. Please let me know if you need further actions from my side.

**Comment by givtnl** [comment] 2021-10-01 17:01
@AbbasHallal This is a possible duplicate of my ticket https://github.com/arangodb/arangodb/issues/14827
Maybe you can check whether you have the same setup as I have.

**Closed** 2022-01-27 13:48 UTC
Labels: 3 Cluster, 1 Analyzing, 3 ImportExport
