### ISSUE TITLE
The query returns an empty array when it should return one element

### ISSUE THREAD

**Issue by lazharichir** [arangodb/arangodb#6518] opened 2018-09-16 18:04 UTC
## My Environment

* __ArangoDB Version__:        3.3.14 
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               default
* __Infrastructure__:               macbook pro i9
* __Operating System__:        MacOS 10.13.4
* __Used Package__:              homebrew

## Component, Query & Data

__Affected feature__:
AQL query

__AQL query (if applicable)__:
```
FOR topic IN topics
    FILTER topic.external.wikidata == 20489079
    RETURN topic
```

__AQL explain (if applicable)__:
```
Query string:
 FOR topic IN topics
     FILTER topic.external.wikidata == 20489079
     RETURN topic

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  6   IndexNode       775825     - FOR topic IN topics   /* persistent index scan */
  5   ReturnNode      775825       - RETURN topic

Indexes used:
 By   Type         Collection   Unique   Sparse   Selectivity   Fields                    Ranges
  6   persistent   topics       false    true             n/a   [ `external.wikidata` ]   (topic.`external`.`wikidata` == 20489079)

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
```

__Dataset__:
My `topics` collection has several fields as follows:
- labels
-- en
- descriptions
-- en
- external
-- wikidata
-- enwiki
- updated
- created 

I have 15,516,509 topics in the collection, and it is loaded.

__Indexes__:
```
> db.topics.getIndexes()

[
  {
    "fields" : [
      "_key"
    ],
    "id" : "topics/0",
    "selectivityEstimate" : 1,
    "sparse" : false,
    "type" : "primary",
    "unique" : true
  },
  {
    "deduplicate" : true,
    "fields" : [
      "external.wikidata"
    ],
    "id" : "topics/276522634",
    "sparse" : true,
    "type" : "persistent",
    "unique" : false
  },
  {
    "deduplicate" : true,
    "fields" : [
      "external.enwiki"
    ],
    "id" : "topics/276523255",
    "sparse" : true,
    "type" : "persistent",
    "unique" : false
  },
  {
    "deduplicate" : true,
    "fields" : [
      "labels.en"
    ],
    "id" : "topics/276573150",
    "sparse" : false,
    "type" : "persistent",
    "unique" : false
  },
  {
    "fields" : [
      "labels.en"
    ],
    "id" : "topics/276574441",
    "minLength" : 3,
    "sparse" : true,
    "type" : "fulltext",
    "unique" : false
  }
]
```

__Problem__:

The above queries do not return anything (empty array) instead of returning the below document which clearly exists in the collection as per screenshots.

The same goes with `FILTER topic.label.en == "Two eagles"` or for other documents with `FILTER topic.external.enwiki == "China"`. Using the FULLTEXT() query on `labels.en` works and returns documents as expected.

Perhaps it has to do with the nexted document fields (`labels`, then `en`)? 

__Expected result__:

The proof the requested document actually exists:

<img width="1494" alt="screen shot 2018-09-16 at 19 56 24" src="https://user-images.githubusercontent.com/12215372/45599395-399f6280-b9eb-11e8-86da-1fded35e41bc.png">

<img width="396" alt="screen shot 2018-09-16 at 19 56 40" src="https://user-images.githubusercontent.com/12215372/45599396-3dcb8000-b9eb-11e8-9448-1d9ab75faf51.png">

**Comment by lazharichir** [comment] 2018-09-17 08:48
Just deleted one index and recreated it - it seems to work! I also shut down, restarted it and reloaded the collection and it worked. Recreating the other persistent indexes for this collection to see for the other ones.

I have many documents so it takes time.

**Comment by lazharichir** [comment] 2018-09-20 15:30
Fixed by recreating indexes...

**Comment by jsteemann** [comment] 2018-09-20 15:47
Mmmmh... It's good that it works now, but actually it should have already worked on the first attempt.
Is the dataset publicly available so we can also try to reproduce the issue?

**Comment by Simran-B** [comment] 2018-09-25 17:55
Did you upgrade ArangoDB between the import of the data and the problem? Do you remember the versions?

**Comment by OmarAyo** [comment] 2018-10-15 14:59
Hi @lazharichir 

Just sending a quick followup - how things are going? Did you have the chance to have a look at Simran's questions?

May you provide us with a status update

Best,

**Comment by maxkernbach** [comment] 2018-10-23 08:41
Since we are not able to reproduce without the preprocessed dataset and the problem did not reoccur, I am closing this issue for now.

Please feel free to reopen the issue by adding a new comment.

**Closed by maxkernbach** 2018-10-23 08:41 UTC
Labels: 1 Question, 2 Cannot Reproduce, 3 AQL, Waiting User Reply
