### ISSUE TITLE
Aardvark: Paging collections sometimes fails

### ISSUE THREAD

**Issue by oliverhausler** [arangodb/arangodb#11526] opened 2020-05-01 18:02 UTC
Listing collection entities not properly working in Aardvark in 3.6.2. It seems, when the underlying collection changes, paging becomes messed up. I am sometimes seeing empty pages, sometimes the wrong result.

**Comment by dothebart** [comment] 2020-05-28 06:39
ok, I think this is a duplicate of https://github.com/arangodb/arangodb/issues/11636 - since if there is a proxy inbetween making the transport unreliable this is probably going to happen.

**Closed by dothebart** 2020-05-28 06:39 UTC
Labels: 3 UI
