### ISSUE TITLE
Replication applier error: internal error

### ISSUE THREAD

**Issue by gauravkumar37** [arangodb/arangodb#2006] opened 2016-08-21 13:17 UTC
I'm using the latest ArangoDB of the respective release series:
Master running v2.8.10
Slave running v2.8.11

On this operating system:
CentOS 6.2 x64
### This is an async replication related issue:

I have a master and a slave DB and using async replication. Roughly once in a day or two, I am seeing this error on the slave and the replication applier stops until I restart it.
Replication applier start on slave:

```
require("org/arangodb/replication").applier.properties({
    endpoint: "tcp://xx.xx.xx.xx:8529",
    username: "xx",
    password: "xxxx",
    autoStart: true,
    autoResync: false,
    requireFromPresent: true,
    autoResyncRetries: 2,
    includeSystem: false,
    ignoreErrors: 100,
    connectTimeout: 20000,
    requestTimeout: 20000,
    verbose: true,
    incremental: true,
    restrictType: "include",
    restrictCollections: [ "coll1" ]
});
```

Slave logs:

```
2016-08-21T17:14:04 [12882] WARNING replication applier error: internal error, offending marker: {"tick":"136184909018903","type":2300,"database":"54192933","cid":"26090461981477","cname":"coll1","tid":"136184793151255","key":"6aea3d2650f38c6892c04eeacd3ff667","rev":"136184908953367","data":{"_key":"6aea3d2650f38c6892c04eeacd3ff667","_rev":...
2016-08-21T17:14:04 [12882] ERROR replication applier error for database 'prod': internal error, offending marker: {"tick":"136184909018903","type":2300,"database":"54192933","cid":"26090461981477","cname":"coll1","tid":"136184793151255","key":"6aea3d2650f38c6892c04eeacd3ff667","rev":"136184908953367","data":{"_key":"6aea3d2650f38c6892c04eeacd3ff667","_rev":...
2016-08-21T17:14:04 [12882] INFO stopped replication applier for database 'prod'
```

I did not find any logs on the master.
What could be the issue?

**Comment by jsteemann** [comment] 2016-08-25 12:25
I have looked it up in the source, and an "internal error" can be thrown for a document insert/update operation whenever an unknown exception is raised. "unknown exception" here means "non-ArangoDB-specific exceptions". "unknown exceptions" here includes all C++ standard exceptions that may be thrown in out-of-memory situations.
I have added some more diagnostics in the 3.0 and devel branches that may provide more context in the logs if such errors occur.

**Comment by gauravkumar37** [comment] 2016-08-25 15:07
Thanks @jsteemann. I will try the release after this commit is merged.
Kindly let me know any possible debugging or tweaks that I can apply at my end to resolve this error. It is now happening almost daily.

**Comment by jsteemann** [comment] 2016-08-26 09:06
Just added a (hopefully more) diagnostic error message in the 2.8 branch if this error occurs. Hopefully this message reveals the root cause of the problem.

**Comment by gauravkumar37** [comment] 2016-09-07 04:01
@jsteemann 
I noticed v3.0.6 and v3.0.7 were released 5 and 2 days ago respectively. Is there a plan to release v2.8.12 as well?

**Comment by dothebart** [comment] 2016-09-07 07:52
Yes, we are going to do a 2.8 bugfix release in the next days. If you need this urgent, feel free to build it yourselves from the 2.8 branch; The build infrastructure for building RPMS can be found here: https://build.opensuse.org/project/show/home:fceller2

**Comment by gauravkumar37** [comment] 2016-09-07 07:56
Thanks @dothebart for the update. Will wait for the official bugfix release.

**Comment by dothebart** [comment] 2016-11-25 14:28
3.0.12 is available for download via the regular upgrade channels - closing.

**Closed by dothebart** 2016-11-25 14:28 UTC
Labels: core, Fixed
