### ISSUE TITLE
Can't turn off --server.authentication-system-only

### ISSUE THREAD

**Issue by bubnenkoff** [arangodb/arangodb#1877] opened 2016-06-17 19:57 UTC
Latest Windows Beta-2 version
```
C:\Program Files\ArangoDB 3.0.0\bin>arangod.exe --server.authentication-system-only
2016-06-17T19:55:43Z [5976] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
2016-06-17T19:55:43Z [5976] ERROR cannot open datafile 'C:\Program Files\ArangoDB 3.0.0\bin\../var/lib/arangodb3\journals\logfile-3.db': '\xCE\xF2\xEA\xE0\xE7\xE0\xED\xEE \xE2 \xE4\xEE\xF1\xF2\xF3\xEF\xE5.\r\n'
2016-06-17T19:55:43Z [5976] ERROR unable to open logfile 'C:\Program Files\ArangoDB 3.0.0\bin\../var/lib/arangodb3\journals\logfile-3.db': system error
2016-06-17T19:55:43Z [5976] FATAL could not inspect WAL logfiles: system error

C:\Program Files\ArangoDB 3.0.0\bin>
```

**Comment by jsteemann** [comment] 2016-06-20 07:16
Looks like there is an error when starting/restarting ArangoDB.
The errors indicate there is a problem reading the WAL logfiles, but I don't see anything authentication-related in the output, so I don't think the problem is related to it (additionally `--server.authentication-system-only` has a default value of true anyway). Or does the error go away when not specifying the parameter at startup?
Can you try starting ArangoDB with the following parameters to get more diagnostics?
`--log.force-direct true --log.level trace`
That may provide additional information. Thanks!

**Comment by jsteemann** [comment] 2016-06-20 08:17
Can you also check the file permissions for the directory `C:\Program Files\ArangoDB 3.0.0\bin\../var/lib/arangodb3\journals\`? 
From the output above it looks like you started arangod manually from the command-line. Does this command run with the same privileges as the ArangoDB service (that is, if you ran it as a service before)? In this case running it with administrative privileges may help.

**Comment by dothebart** [comment] 2016-07-14 15:00
Hi, 
Any news on this? or can we close this?

**Closed** 2016-08-05 12:22 UTC
