### ISSUE TITLE
The transaction definition is too ugly

### ISSUE THREAD

**Issue by zhuxiujia** [arangodb/arangodb#5375] opened 2018-05-17 08:18 UTC
The transaction definition is too ugly, no mongo4.0  start_transaction(),s.commit_transaction(),s.abort_transaction()     is useful.
I'm sure most developers don't like the way you define transactions.
Most server developers prefer similar SQL  start > commit>rollback   model

**Comment by dothebart** [comment] 2018-05-25 15:03
But we got beautify AQL instead ;-)
Yes, having a more conventional way of working with transactions has been a long standing whish, and we will get them eventually. 
I will close this issue as a duplicate of https://github.com/arangodb/arangodb/issues/471

**Closed by dothebart** 2018-05-25 15:03 UTC
