### ISSUE TITLE
Traversal broken

### ISSUE THREAD

**Issue by rm-minus-r-star** [arangodb/arangodb#14122] opened 2021-05-03 06:01 UTC
## My Environment

* __ArangoDB Version__:        3.7.5
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   
* __Configuration__:               Single
* __Infrastructure__:               Install on GCP VM
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        128 GB
* __Disks in use__:        HDD
* __Used Package__:              Ubuntu .deb
* 
## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
```
LET J0 = (
    FOR junction in junctions
        FILTER HAS (junction['centerline_aliases'], '11929684')
           AND junction['centerline_aliases']['11929684'] == 0
    RETURN {
        'pfi': TO_NUMBER('11929684')
        , 'seq 0': junction['_id']
    }
)

FOR zp in J0
    FOR v, e, p IN 1 OUTBOUND zp['seq 0'] GRAPH 'Roads'
        PRUNE v['tr_road PFI'] != zp['pfi']
          AND NOT HAS(v['centerline_aliases'], TO_STRING(zp['pfi']))
    RETURN {
        'pfi': zp['pfi']
        , 'v0': p.vertices
    }
```

__AQL explain and/or profile (if applicable)__:
Not available

__Dataset__:
See detail in expected result below

__Size of your Dataset on disk__:
3-4 GB

__Replication Factor & Number of Shards (Cluster only)__:
N/A

## Steps to reproduce

1. Run the query

__Problem__:
"Query: AQL: missing variable #4 (zp) for node #11 (TraversalNode) while planning registers (exception location: /workl/Arangod/Aql/RegisterPlan.cpp:138. Please report this error to arangodb.com (while optimizing plan)(exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:311). Please report this error to arangodb.com"

__Expected result__:
Query above extracts a single point in the first stage:
_id:junctions/0356412
_rev:_cJOLQ9m---
_key:0356412
_type                    :  junctions
centerline_aliases:
    11929425 : 11
    11929684 : 0
    11929684 : 0

and yields: 
([
  {
    "pfi": 11929684,
    "seq 0": "junctions/0356412"
  }
]

I expect it to be able to traverse to
_id:centerlines/11929684-0001
_rev:_cI7br_K---
_key:11929684-0001
_type	:	centerlines		
PFI	        :	11929684		
seq	        :	1

via the edge 
_id:road_segments/01329975
_rev:_cQ994AK--E
_key:01329975
_from:junctions/0356412
_to:centerlines/11929684-0001

I *have* been able to execute similar queries recently. The system seems to have just spontaneously broken -- I can't execute a traversal query no matter what I do. The example above is a drastically scaled-down version of the problem.

![Screenshot from 2021-05-03 14-58-45](https://user-images.githubusercontent.com/40910389/116845186-7a922700-ac28-11eb-92c5-43223d9a38f7.png)

**Comment by jsteemann** [comment] 2021-05-03 06:22
Preliminary analysis: the problem seems to be caused by a specific optimizer rule (`inline-subqueries`). At least when turning the optimizer rule off it seems to work.
As a workaround, you could start the server with startup option `--query.optimizer-rules "-inline-subqueries"` until there is a proper fix.

**Comment by jsteemann** [comment] 2021-05-03 07:26
Fixed via https://github.com/arangodb/arangodb/pull/14124
The bugfix should become available in 3.7.12.
There are two workarounds to avoid this error:
1) disable the inline-subqueries optimizer rule, as noted above
2) avoid PRUNE conditions

Any of the two should remedy the problem, as the issue only occurs when a PRUNE condition refers to a variable from an inline subquery.

**Comment by rm-minus-r-star** [comment] 2021-05-03 10:11
Starting the server with `sudo arangod -query.optimizer-rules "-inline-subqueries"` indeed helps the problem.

I tried adding the following, thinking it would do the same thing for the auto-started service

```
[query]
optimizer-rules = "-inline-subqueries"
```

But it failed with

May 03 07:02:12 vic-transport arangod[5880]: 2021-05-03T07:02:12Z [5880] WARNING [aa52f] {queries} cannot enable unknown optimizer rule '"-inline-subqueries"'

**Comment by jsteemann** [comment] 2021-05-03 10:14
It looks the quotes are somewhat in the way.
Can you try removing the quotes from the config file for the option?

**Comment by rm-minus-r-star** [comment] 2021-05-03 10:38
Yes, removing the quotes works. I should have tried that.

**Comment by maxkernbach** [comment] 2021-06-28 15:18
Hi @rm-minus-r-star,

Version 3.7.12, which includes a fix for this issue, has been released.

Could you please upgrade and let us know whether your query succeeds without manually disabling the optimizer rule `"-inline-subqueries"`?

**Closed** 2021-07-07 14:55 UTC
Labels: 1 Bug, 2 Fixed, 3 AQL, 3 Graph, Waiting User Reply
