### ISSUE TITLE
The Performance degradation with splice-subqueries

### ISSUE THREAD

**Issue by dvzubarev** [arangodb/arangodb#11358] opened 2020-03-31 17:43 UTC
## My Environment

* __ArangoDB Version__:        3.6.0, 3.6.2, 3.7.0-20200328
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               none
* __Infrastructure__:               own
* __Operating System__:        Debian 10
* __Total RAM in your machine__:        64Gb
* __Disks in use__:        SSD
* __Used Package__:             Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
```
for d in @@coll
filter d._key in @ids

let sents = (
    for sent in d.text.sents
    let words = (
        for w in sent
        return w.i
        )
    return {"ws": words}
    )
return {"sents": sents, "id": d._key}
```
[Debug packages](https://mega.nz/#F!CkYTmSKB!0CJxG0tAWT4L08xxr0oRAQ)

<details>
  <summary>Bind vars</summary>

` @coll = temp `

```
ids = ["1002595df157","1002ceccb96c","10043116c4a9","1004e69a45f","1006425b8ec8","10085fb7e5ff","1009d8f92601","100b85ad1e23","100d75e8c7bc","100d7f7e4130","100e62169385","100ea9ed2ed9","100f29bc6f64","100f9cea042a","1017f66f1407","101905d2bc00","101989d8272d","101cd43734e0","101d3101ea37","101db64c975f","101f24f93547","101fcd47c0ed","102078c00f84","1021779ed1b0","10243510e7a5","10253d860d8","102670edd31d","1028134d2bea","102ae8b1c471","102d3d09c5f5","102d45fe11cd","102f02c7d6fe","102f35cac9b8","1030fc688b2d","1034bddb58c6","1037ad0b3f7b","10394bb831f5","103adce7289f","103c6a61e38a","1040ff41bcf2","104475c35a5","10498bb5b29c","104b02beacd4","104b26bb8017","104bd0f0efab","104e5de21046","104fcba134d8","10514e5cddc6","105623e8d29e","10565d6d3910","1057b83c2c07","1058d042e79a","105bb3084ba1","105c748f8499","105c803b1720","105d729ead7f","106051cdd8c9","106162a2d63f","10672ac36444","106a5e8b06e8","106bd18fe952","106e1a7699ee","106f5a1c3eac","1072a074af04","1073f380ea11","1075ec3a5692","1078772e1cc9","107b10194014","107cae8c8c47","107f079db653","107f5b4fb977","107f7b9d4e7d","1080aabe9609","10823ee6ce2d","1087194a89fd","108a4396411e","108ab6aa4254","108c6cfd2c64","108cc5a45d57","108e5241087d","10923e0645a6","10928fcc736","1092f3214d68","1093a988dd60","1098a2bf7efd","109a5bc04a5d","109bcb563b26","10a0ca69ee8a","10a21cfc72e3","10a22a16bb","10a351ee0c76","10a6cf3a9d36","10a6e77f661","10a8f3bf6ad3","10aedaf809bc","10b097ee41ed","10b1f14735ea","10b2e529c242","10b32201da02","10b4512dd8fb","10b8bac560e9","10b8cfd29b27","10bbf358e7b1","10bcb5a824d4","10bd60004d2c","10be40ca2adb","10be525381f9","10c038fb1511","10c30705c840","10c3c3972eda","10c6fcf19dca","10ca6c8ba67b","10cc79dedea6","10cdab46a53","10ce11c905e4","10d371170360","10d469304570","10d8f21672f1","10df712bd0d3","10e1a03001e5"]
  ```

</details>

__Dataset__:

[coll.tar](https://mega.nz/#F!CkYTmSKB!0CJxG0tAWT4L08xxr0oRAQ)
This is the subset of a collection, but still the issue is reproducible on this small subset.

__Size of your Dataset on disk__:
30MiB compressed

## Steps to reproduce

I executed the query with various versions of arangodb and with turned off/on `splice-subqueries`:
`+splice-subqueries` I changed nothing in arangodb settings.
`-splice-subqueries` I added to arangodb cmdline options `--query.optimizer-rules "-splice-subqueries"`

__Problem__:

The query execution time with `+splice-subqueries` is  is 8 times higher than with `-splice-subqueries`
|        version | -splice-subqueries | +splice-subqueries |
|----------------|--------------------|--------------------|
|          3.6.0 |            0.21993 |                  - |
|          3.6.2 |            0.55766 |            4.01306 |
| 3.7.0-20200328 |            0.92362 |            4.18023 |

Also the performance for `-splice-subqueries` seems to decrease as well from v3.6.0 to v3.7.0.

For your convenience, I saved profiling results for 3.6.0 and 3.7.0 versions: 

<details>
  <summary>v3.6.0 -splice-subqueries</summary>

```

Query String (220 chars, cacheable: false):
 for d in @@coll
 filter d._key in @ids
 let sents = (
     for sent in d.text.sents
     let words = (
         for w in sent
         return w.i
         )
     return {"ws": words}
     )
 return {"sents": sents, "id": d._key}


Execution plan:
 Id   NodeType            Calls    Items   Runtime [s]   Comment
  1   SingletonNode           1        1       0.00000   * ROOT
 18   IndexNode               1      120       0.00616     - FOR d IN c2000_analyzed   /* primary index scan */
 15   SubqueryNode            1      120       0.20987       - LET sents = ...   /* subquery */
  5   SingletonNode         120      120       0.00002         * ROOT
  6   CalculationNode       120      120       0.00101           - LET #11 = d.`text`.`sents`   /* attribute expression */   /* collections used: d : c2000_analyzed */
  7   EnumerateListNode     122    45795       0.00503           - FOR sent IN #11   /* list iteration */
 12   SubqueryNode          122    45795       0.16783             - LET words = ...   /* subquery */
  8   SingletonNode       45795    45795       0.00723               * ROOT
  9   EnumerateListNode   45796   416362       0.04674                 - FOR w IN sent   /* list iteration */
 10   CalculationNode     45796   416362       0.05454                   - LET #13 = w.`i`   /* attribute expression */
 11   ReturnNode          45796   416362       0.02453                   - RETURN #13
 13   CalculationNode       122    45795       0.03050             - LET #15 = { "ws" : words }   /* simple expression */
 14   ReturnNode            122    45795       0.00353             - RETURN #15
 16   CalculationNode         1      120       0.00388       - LET #17 = { "sents" : sents, "id" : d.`_key` }   /* simple expression */   /* collections used: d : c2000_analyzed */
 17   ReturnNode              1      120       0.00000       - RETURN #17

Indexes used:
 By   Name      Type      Collection       Unique   Sparse   Selectivity   Fields       Ranges
 18   primary   primary   c2000_analyzed   true     false       100.00 %   [ `_key` ]   (d.`_key` in [ "1002595df157", "1002ceccb96c", "10043116c4a9", "1004e69a45f", "1006425b8ec8", "10085fb7e5ff", "1009d8f92601", "100b85ad1e23", "100d75e8c7bc", "100d7f7e4130", "100e62169385", "100ea9ed2ed9", "100f29bc6f64", "100f9cea042a", "1017f66f1407", "101905d2bc00", "101989d8272d", "101cd43734e0", "101d3101ea37", "101db64c975f", ... ])

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2

Query Statistics:
 Writes Exec   Writes Ign   Scan Full   Scan Index   Filtered   Exec Time [s]
           0            0           0          120          0         0.22154

Query Profile:
 Query Stage           Duration [s]
 initializing               0.00000
 parsing                    0.00019
 optimizing ast             0.00017
 loading collections        0.00001
 instantiating plan         0.00007
 optimizing plan            0.00097
 executing                  0.21993
 finalizing                 0.00017

```
</details>

<details>
  <summary>v3.7.0 +splice-subqueries</summary>

```
Query String (219 chars, cacheable: false):
 for d in @@coll
 filter d._key in @ids
 let sents = (
     for sent in d.text.sents
     let words = (
         for w in sent
         return w.i
         )
     return {"ws": words}
     )
 return {"sents": sents, "id": d._key}

Execution plan:
 Id   NodeType            Calls    Items   Runtime [s]   Comment
  1   SingletonNode           1        1       0.00000   * ROOT
 18   IndexNode               1      120       0.01614     - FOR d IN c2000_analyzed   /* primary index scan */
 19   SubqueryStartNode       1      240       0.00494       - LET sents = ( /* subquery begin */
  6   CalculationNode         1      240       0.00391         - LET #11 = d.`text`.`sents`   /* attribute expression */   /* collections used: d : c2000_analyzed */
  7   EnumerateListNode      46    45915       0.01429         - FOR sent IN #11   /* list iteration */
 21   SubqueryStartNode     153    91710       0.73005           - LET words = ( /* subquery begin */
  9   EnumerateListNode     540   462277       2.17631             - FOR w IN sent   /* list iteration */
 10   CalculationNode       540   462277       0.06732               - LET #13 = w.`i`   /* attribute expression */
 22   SubqueryEndNode       122    45915       1.07250               - RETURN  #13 ) /* subquery end */
 13   CalculationNode       122    45915       0.01446           - LET #15 = { "ws" : words }   /* simple expression */
 20   SubqueryEndNode         1      120       0.07983           - RETURN  #15 ) /* subquery end */
 16   CalculationNode         1      120       0.00044       - LET #17 = { "sents" : sents, "id" : d.`_key` }   /* simple expression */   /* collections used: d : c2000_analyzed */
 17   ReturnNode              1      120       0.00001       - RETURN #17

Indexes used:
 By   Name      Type      Collection       Unique   Sparse   Selectivity   Fields       Ranges
 18   primary   primary   c2000_analyzed   true     false       100.00 %   [ `_key` ]   (d.`_key` in [ "1002595df157", "1002ceccb96c", "10043116c4a9", "1004e69a45f", "1006425b8ec8", "10085fb7e5ff", "1009d8f92601", "100b85ad1e23", "100d75e8c7bc", "100d7f7e4130", "100e62169385", "100ea9ed2ed9", "100f29bc6f64", "100f9cea042a", "1017f66f1407", "101905d2bc00", "101989d8272d", "101cd43734e0", "101d3101ea37", "101db64c975f", ... ])

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
  4   splice-subqueries

Query Statistics:
 Writes Exec   Writes Ign   Scan Full   Scan Index   Filtered   Exec Time [s]
           0            0           0          120          0         4.25288

Query Profile:
 Query Stage           Duration [s]
 initializing               0.00000
 parsing                    0.00022
 optimizing ast             0.00017
 loading collections        0.00002
 instantiating plan         0.00008
 optimizing plan            0.06959
 executing                  4.18023
 finalizing                 0.00255
```

</details>

<details>
  <summary>v3.7.0 -splice-subqueries</summary>

```
Query String (219 chars, cacheable: false):
 for d in @@coll
 filter d._key in @ids
 let sents = (
     for sent in d.text.sents
     let words = (
         for w in sent
         return w.i
         )
     return {"ws": words}
     )
 return {"sents": sents, "id": d._key}

Execution plan:
 Id   NodeType            Calls    Items   Runtime [s]   Comment
  1   SingletonNode           1        1       0.00001   * ROOT
 18   IndexNode               1      120       0.00598     - FOR d IN c2000_analyzed   /* primary index scan */
 15   SubqueryNode            1      120       0.90786       - LET sents = ...   /* subquery */
  5   SingletonNode         120      120       0.00012         * ROOT
  6   CalculationNode       120      120       0.00095           - LET #11 = d.`text`.`sents`   /* attribute expression */   /* collections used: d : c2000_analyzed */
  7   EnumerateListNode     122    45795       0.00681           - FOR sent IN #11   /* list iteration */
 12   SubqueryNode          122    45795       0.84327             - LET words = ...   /* subquery */
  8   SingletonNode       45795    45795       0.02813               * ROOT
  9   EnumerateListNode   45796   416362       0.38960                 - FOR w IN sent   /* list iteration */
 10   CalculationNode     45796   416362       0.08632                   - LET #13 = w.`i`   /* attribute expression */
 11   ReturnNode          45796   416362       0.28617                   - RETURN #13
 13   CalculationNode       122    45795       0.05029             - LET #15 = { "ws" : words }   /* simple expression */
 14   ReturnNode            122    45795       0.00399             - RETURN #15
 16   CalculationNode         1      120       0.00973       - LET #17 = { "sents" : sents, "id" : d.`_key` }   /* simple expression */   /* collections used: d : c2000_analyzed */
 17   ReturnNode              1      120       0.00001       - RETURN #17

Indexes used:
 By   Name      Type      Collection       Unique   Sparse   Selectivity   Fields       Ranges
 18   primary   primary   c2000_analyzed   true     false       100.00 %   [ `_key` ]   (d.`_key` in [ "1002595df157", "1002ceccb96c", "10043116c4a9", "1004e69a45f", "1006425b8ec8", "10085fb7e5ff", "1009d8f92601", "100b85ad1e23", "100d75e8c7bc", "100d7f7e4130", "100e62169385", "100ea9ed2ed9", "100f29bc6f64", "100f9cea042a", "1017f66f1407", "101905d2bc00", "101989d8272d", "101cd43734e0", "101d3101ea37", "101db64c975f", ... ])

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2

Query Statistics:
 Writes Exec   Writes Ign   Scan Full   Scan Index   Filtered   Exec Time [s]
           0            0           0          120          0         0.92590

Query Profile:
 Query Stage           Duration [s]
 initializing               0.00000
 parsing                    0.00020
 optimizing ast             0.00016
 loading collections        0.00001
 instantiating plan         0.00008
 optimizing plan            0.00082
 executing                  0.92362
 finalizing                 0.00099
```

</details>

__Expected result__:
I wouldn't expect such performance hit when enabling `splice-subqueries`. Is it inevitable for this type of queries (nested subqueries?) or it can be tuned somehow?

**Comment by mchacki** [comment] 2020-04-02 05:50
Hi @dvzubarev thank you for reporting this.

I can confirm the above results on my development environment.
Thank you very much for the high detail and effort you put into this, makes our job in fixing this much easier.

We have two issues in this ticket actually:
1) Splicing subquery is slower in your case than non-splicing the subquery. We have evidence that due to how AQL internally handles variables we copy much more data than necessary. This is a larger change in the internals, we have a plan on how to fix this and focus on getting this into 3.7.0 GA. 
2) Non-Splicing in 3.6 is faster than in 3.7 this is not desired and I think I accidentally disabled an optimization here in some place, i am checking on it and keep you posted. This is a rather quick fix in comparison to 1)

**Comment by ysmu** [comment] 2020-04-05 21:05
Could my issue https://github.com/arangodb/arangodb/issues/10853 be related to this issue? I just checked and it looks like it's still happening in 3.6.2. I'll happily wait for 3.7 if it's hard to get it fixed in 3.6.x :)

**Comment by goedderz** [comment] 2020-04-14 11:09
Hi @ysmu,

you are right, these are related. We are currently working on improvements for 3.7.

This is not a simple bug that can be fixed, but a rework of a basic functionality in AQL. It existed before spliced subqueries, but now needs to be adapted to better cover the way spliced subqueries work, in contrast to classic subqueries.

These changes will not make it into 3.6, as they are too extensive.

Best,

Tobias

**Comment by dothebart** [comment] 2020-09-02 15:29
Hi, 
please note [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) - hence closing this. If you have further similar issues with ArangoDB 3.7 don't hesitate to open a new issue.

**Closed by dothebart** 2020-09-02 15:29 UTC
Labels: 1 Analyzing, 3 AQL, performance
