### ISSUE TITLE
Setup / Installation: Failed to initialize database password

### ISSUE THREAD

**Issue by jim1001** [arangodb/arangodb#11500] opened 2020-04-25 21:31 UTC
## My Environment

* __ArangoDB Version__:        3.6.3
* __Storage Engine__:             Default
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Default
* __Infrastructure__:               own
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        16GB

## Component, Query & Data

__Affected feature__:
Installation

## Steps to reproduce

1.  Run installer with default settings

__Problem__:
 Error window pops up "Failed to initialize database password"

__Expected result__:
Program installs

Windows Event Log shows error:

```
[33860] {startup} writing VERSION file 'C:\ProgramData\ArangoDB\VERSION-1' failed: Permission denied
C:\vm02-windows\oskar\work\ArangoDB\arangod\VocBase\Methods\Version.cpp
arangodb::methods::Version::write
196
```

However the VERSION-1 file has been written to this location so don't understand the message.
I ran installer .exe as Administrator and am able to write files to C:\ProgramData\ArangoDB

Here is contents of  VERSION-1 file:
`{"version":30603,"tasks":{"createSystemCollectionsAndIndices":true,"createSystemStatisticsDBServer":true}}`

Here is contents of arangod.log file:
```
2020-04-25T20:59:08Z [18736] INFO [43396] {authentication} Jwt secret not specified, generating...
2020-04-25T20:59:08Z [18736] INFO [144fe] using storage engine 'rocksdb'
2020-04-25T20:59:08Z [18736] INFO [24783] created database directory 'C:\ProgramData\ArangoDB'
2020-04-25T20:59:08Z [18736] INFO [3844e] {authentication} Authentication is turned on (system only)
2020-04-25T20:59:08Z [18736] INFO [e6460] created base application directory 'C:\ProgramData\ArangoDB-apps\_db'
2020-04-25T20:59:09Z [18736] WARNING [7f5c9] cannot rename saved file 'C:\ProgramData\ArangoDB\VERSION-1.tmp' to 'C:\ProgramData\ArangoDB\VERSION-1': Permission denied
2020-04-25T20:59:09Z [18736] ERROR [33860] {startup} writing VERSION file 'C:\ProgramData\ArangoDB\VERSION-1' failed: Permission denied
2020-04-25T20:59:09Z [18736] FATAL [2eb08] Database '_system' initialization failed (Permission denied). Please inspect the logs from the initialization procedure and try starting the server again.
```

Grateful for any help - thanks.

**Comment by dothebart** [comment] 2020-04-27 09:04
Hi, 
whats the timestamp of this ready existing file in comparison to the logfile? Is the mentioned temp-file still there? Can you screenshot the file permissions of that file?
Whats your special environment? AD/Domain login? Any filesystem specialities? VM System? Mounted filesytems?

**Comment by jim1001** [comment] 2020-04-27 10:25
Thanks for reply.

> whats the timestamp of this ready existing file in comparison to the logfile?

VERSION-1
Date created/modified/accessed: 25/04/2020 21:59:09

arangod.log
Date created/modified/accessed : 25/04/2020 21:59:09

>  Can you screenshot the file permissions of that file?

![image](https://user-images.githubusercontent.com/16447481/80360285-04215300-8877-11ea-9e20-6b17df4fc8c8.png)

Using Git Bash:
`-rw-r--r-- 1 <my-usernane> 1049089 107 Apr 25 21:59 VERSION-1`

I am an Administrator on the machine

>AD/Domain login? 

Yes, in an AD

> VM System? 

No

> Mounted filesytems?

There is a network drive connected although I wasn't knowlngly using it for this installation 

Hope that helps to find the problem.

**Comment by jim1001** [comment] 2020-04-29 10:09
I'd be grateful for any help when possbile based on the further information provided. Please let me know if you need any extra diagnostics - thank you.

**Comment by dothebart** [comment] 2020-09-03 12:36
closing as a duplicate of https://github.com/arangodb/arangodb/issues/11041 

Please note [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.

**Closed by dothebart** 2020-09-03 12:36 UTC
Labels: 1 Bug, 4 Windows
