### ISSUE TITLE
After droping, database name still present in selection list

### ISSUE THREAD

**Issue by msukhov** [arangodb/arangodb#2368] opened 2017-03-10 10:47 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1

On this operating system:
- [ ] Linux 
  - [x] RedHat .rpm

### this is a web interface-related issue:
I'm using the web interface with this browser: Google Chrome    running on this OS: Windows 7 x64
- [x] authentication is enabled?
- [ ] using the cluster?
- [x] _system database?

These are the steps to reproduce:
1) open the browser on http://server.db:8529
2) log in as root
3) create user `test`
4) create datadase `data` with owner `test`
5) relogin as `test` and selest `data` database
6) relogin as `root`
7) delete `data` database
8) relogin as `test`

After these steps `data` database still present in list of all databases for selection:
![image](https://cloud.githubusercontent.com/assets/6313693/23792406/30ca1a66-05a0-11e7-889c-945150dafa2f.png)

**Comment by msukhov** [comment] 2017-03-10 10:59
And deleted database still present in permission tab of user profile:
![image](https://cloud.githubusercontent.com/assets/6313693/23792849/1a159ece-05a2-11e7-8943-89455e90512e.png)

**Comment by hkernbach** [comment] 2017-03-13 14:08
Thanks for spotting. Closing this issue because it is a duplicate of #2047 and #2303. Latest bugfix date will be 3.2 release.

**Closed by hkernbach** 2017-03-13 14:08 UTC
