### ISSUE TITLE
Non-Root User Queries are not being saved - Wiped on page refresh

### ISSUE THREAD

**Issue by rogueSF** [arangodb/arangodb#5831] opened 2018-07-10 18:59 UTC
## My Environment

* __ArangoDB Version__:       3.3.11
* __Storage Engine__:            MMFiles
* __Deployment Mode__:       Single Server
* __Configuration__:               Nothing too special
* __Infrastructure__:               Own
* __Operating System__:        Debian 9
* __Used Package__:              Debian Jesse .deb

## Component, Query & Data

__Affected feature__:              AQL Query Using Interface

## Steps to reproduce

1.  Login as non root user
2.  Create a new query
3.  Save As > Give query name
4.  Validate query is saved
5.  Refresh the page

__Problem__:
Queries are not being saved to non-root user accounts

__Expected result__:
Queries save and are available to use on refresh

EXTRA:
    I've seen this issue fixed and closed multiple times it seems.  I've tried some of the previous mitigations such as saving them using the "save as" over "save" as well as trying to save them under the root user account to be made available to all other users (I think this is expected behavior?)

I can get queries to save and persist a page refresh when using the root user, however, the queries are still not usable by non-privileged accounts.

**Comment by Simran-B** [comment] 2018-07-10 19:54
I can confirm that there is an issue with saved queries for non-root users **in the `_system` database**.

None of the default and user saved queries show in the `_system` DB, but they do in other user-created databases (the list is always empty).

For the user `root` all queries saved by this user show in `_system` as well as user-created DBs.

**Comment by Simran-B** [comment] 2018-08-06 21:46
@hkernbach Still in lastest devel and a fresh build of Aarkvark. The problem seems to occur if the non-root user has **Access** permissions to the _system db as opposed to **Administrate**. This should mean read-only access, but the entire saved queries list is empty with Access permission.

Saving does seem to work somewhat. If you save a query, it will be listed (but not the default queries). F5 and it is gone. If you then change the permission to Administrate for the user, you should see the default  queries as well as the one you Schrödinger-saved. (However, some other queries I "saved" before were gone, which seems a bit fishy.)

I'm not sure how permissions are supposed to work for the _users system collection server-side. But there's definitely something strange about this, because writes seem to somehow work if only read permissions are given, but reading appears to be denied. This might be a arangod bug and the UI not handling permission issues well (if reading or writing fails I would expect some kind of error message).

**Comment by hkernbach** [comment] 2018-08-06 21:52
Thanks for the detailed message. Will check tomorrow.

**Comment by sleto-it** [comment] 2018-08-18 14:07
Hi,

Just a quick message to inform that v.3.3.14, which contains the fix for this problem, has been released

I am going ahead and closing this issue now. Please comment, if needed, and we will reopen it

Thanks again for reporting this bug,

**Closed by sleto-it** 2018-08-18 14:07 UTC
Labels: 1 Bug, 2 Fixed, 3 UI
