### ISSUE TITLE
Persistent Index not returning data

### ISSUE THREAD

**Issue by Kent767** [arangodb/arangodb#2120] opened 2016-10-18 17:44 UTC
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: Server 2012 R2
- [ ] MacOS, version:
### this is an AQL-related issue:

[x] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

I have a collection "Invoice" 
I recently loaded a substantial amount of data to it, and subsequently created 3 persistent indexes
  InstallationId, Id (Unique, Sparse)
  InstallationId (Sparse)
  Id (Sparse)

//this returns the document I'd expect to see
for i in Invoice 
filter i.InstallationId == "22adf7f9-6220-4fd6-8f43-be3da9976166" and i.Id == "1234"
limit 0, 1
return i

//this returns no data
for i in Invoice 
filter i.InstallationId == "22adf7f9-6220-4fd6-8f43-be3da9976166" 
limit 0, 1
return i

**Comment by Kent767** [comment] 2016-10-18 17:48
this feels like it may be a dupe of #2118

**Comment by Kent767** [comment] 2016-10-18 18:33
it also doesn't seem to be 100% across the index, I was able to query for other values of "InstallationId" and it was able to pull records using the same index i'm having the issue with

**Comment by jsteemann** [comment] 2016-10-25 15:14
I have tried reproducing the above steps with 3.0.10 but to no avail. Can you provide any further information on how this can be reproduced? AFAIK this is not a dupe of Issue #2118, because that issue did affect the 3.1 & devel branches only.

**Comment by Kent767** [comment] 2016-10-25 15:16
unfortunately, I can't really provide much more information, other than the steps I took.  In the situation I had, there were probably 30 collections that I had created similar indexes, and only one of those, i noticed the issue on.  So it's definitely not a 100% thing.. i've since reloaded the environment to work around the issue.

**Comment by jsteemann** [comment] 2016-10-25 15:28
Ok, thanks anyway for confirming. I'll try reproducing somehow.

**Comment by dothebart** [comment] 2017-02-14 15:23
We have not been able to reproduce this by now - Closing.
Thanks for your contribution.

**Closed by dothebart** 2017-02-14 15:23 UTC
