### ISSUE TITLE
ArangoDb Coordinator and DbServer 3.1.16 unexpected exit

### ISSUE THREAD

**Issue by normanuber** [arangodb/arangodb#2398] opened 2017-03-27 21:13 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ X ] 3.1.16

On this operating system:
- [ ] Linux 
  - [ X ] Debian .deb

I submitted my debug logs in private. 
DbServer exits unexpectedly without an error being written to the log file. My guess is a segfault.

Coordinator also has this problem.

**Comment by fceller** [comment] 2017-03-29 07:51
Investigating private logs. We will report the findings here.

**Comment by normanuber** [comment] 2017-03-29 20:20
Sent over the core dump as it looks like my guess was correct.

**Comment by fceller** [comment] 2017-03-31 07:41
Currently trying to reproduce.

**Comment by sleto-it** [comment] 2018-07-30 14:23
Hi all - 3.1 is EOL now

Is this issue still happening with version 3.3.13?

Many Thanks,

**Comment by maxkernbach** [comment] 2018-08-21 08:37
Closing this issue since 3.1 is EOL and no similar issue was reported with the current version.

Please feel free to comment if the problem persists using 3.3.14 and we will reopen this ticket.

**Closed by maxkernbach** 2018-08-21 08:37 UTC
Labels: 1 Bug, 3 Cluster, 3 Core, Waiting User Reply
