### ISSUE TITLE
arangob benchmarking in mode "aqlinsert" fails and destroys the cluster (v2.5.2)

### ISSUE THREAD

**Issue by nlac** [arangodb/arangodb#1320] opened 2015-04-27 11:57 UTC
Hi guys,
i tested the following scenario on Windows 8.1, with a newly installed arangoDB:
- created and started a single-node cluster on localhost with 1 coordinator + 2 dbserver
- ran the following benchmark:
```arangob --server.endpoint tcp://127.0.0.1:8530 --collection "aqlinsert_test" --async true --concurrency 4 --log.level "debug" --test-case "aqlinsert" --requests 50000```

As a result, the single server cluster has been stopped working: on 127.0.0.1:8529 got the very first single-multi cluster select + a "shutdown cluster" button on the UI. On 127.0.0.1:8530 the UI stopped responding - couldn't browse the db any more.

Please find all related info (logs, config files) zipped here http://nlacsoft.net/public/arango/arango_logs.zip

I'm wondering what did i wrong or what restrictions/consequences may it has for production use. My company really intends to use the cluster and it is critical to avoid any data loss. Unfortunately we have similar experiences testing our app with multi-server cluster, on Linux, applying concurent aql reads-writes.

**Comment by nlac** [comment] 2015-04-27 13:20
sorry the link to the logs was wrong, the correct one is  http://nlacsoft.net/public/arango/benchmark_fails.zip

**Comment by neunhoef** [comment] 2015-04-28 22:55
Problem confirmed and reproduced. Is not Windows specific. I am on the case.

**Comment by nlac** [comment] 2015-04-29 06:43
Thank you! It's good to hear that it could be reproduced.

**Comment by neunhoef** [comment] 2015-04-29 07:48
I just committed a fix in the devel branch which fixes the immediate problem. A deadlock in the cluster happened. However, now there is another one, which has to do with locking in the individual shards. I believe that I understand the problem and am now thinking and discussing with my colleagues to how to fix this. I wll post progress here.

**Comment by nlac** [comment] 2015-04-29 16:02
I much appreciate your effort and can't wait to test the next release on our environment!

**Comment by neunhoef** [comment] 2015-04-30 05:11
Second problem had to do with locking on thee shards. I have solved this as well in the devel branch. Then I got a little thread-explosion (>1000 threads). Now there are in the cluster two independent Dispatcher queues, one for the standard queries and one for the cluster-internal AQL queries. This is also in devel.
All these changes will go into the next minor release, which is due later this week or next week at the latest. Once this is out, I will close this issue.
Thanks for reporting.

**Comment by neunhoef** [comment] 2015-04-30 05:15
One more comment: When you do "--async true" in arangob, then it creates lots of queries and the server comes back with a result directly after it has put it into the input queue. This leads to the outcome that at some stage the queues are completely full. Once this happens, the server (rightfully) returns an HTTP 500 result. This is why you will still see some warnings if you run arangob as you suggested. Also, the server will still have to work for some time after arangob terminates. This even happens in the single server case. As far as I see this is intended behaviour.

**Comment by nlac** [comment] 2015-04-30 06:56
That's great!! I would have some questions about the last comment: is the input queue's size fixed or is it configurable (or maybe auto-sized depending from the available memory)? May that HTTP 500 (due to overfilling the input queue) case occur in a practical case of production use?

**Comment by neunhoef** [comment] 2015-04-30 07:44
The queue size can be configured with the command line option (or configuration file)
   --scheduler.maximal-queue-size <int32>
and the default is 8192. I would imagine that this is plenty for any practical case in production. If one really sends so many asynchronous requests, there is probably some other problem underlying.

**Comment by nlac** [comment] 2015-04-30 08:33
Clear, thanks!

**Comment by nlac** [comment] 2015-05-07 20:14
Hi @neunhoef, 
does v2.5.3 contain all the fixes related to the bug? By my first test the original issue is still recent.

**Comment by nlac** [comment] 2015-05-08 08:27
Actually, the benchmark script in the first comment fails for a *non-cluster case also*, running it right after a clean installation of 2.5.3.
Output:
```
Total number of operations: 50000, keep alive: yes, async: yes, batch size: 0, concurrency level (threads): 4
Test case: aqlinsert, complexity: 1, database: '_system', collection: 'aqlinsert_test'
Total request/response duration (sum of all threads): 72.845267 s
Request/response duration (per thread): 18.211317 s
Time needed per operation: 0.000365 s
Time needed per operation per thread: 0.001462 s
Operations per second rate: 2736.664880
Elapsed time since start: 18.270414 s

WARNING: 19333 arangob request(s) failed!!
```

In the _system/aqlinsert_test collection, there are 30667 documents inserted, can be browsed on http://127.0.0.1:8529.

**Comment by jsteemann** [comment] 2015-05-08 08:44
Maybe this is because of `--async true`. Setting it to `true` means that the operation is queued on the server. The server will only queue up to `--scheduler.maximal-queue-size` operations. If the queue is full, further requests will be rejected by the server, leading to operations failing. Can you check whether it is working when setting `--async` to `false` and if it is, increase the queue size?

**Comment by nlac** [comment] 2015-05-08 09:22
Thanks, just tried the case with increasing the maximal-queue-size to 131072 (set it in arangod.conf, in [scheduler] section). The benchmark in non-cluster mode has been succeeded, everything was fine, no errors, GUI worked, that's nice! 

In single-server cluster (1 coord. + 2 dbserv.) the benchmark didn't reported any error on the console, but the cluster shut down.

Then i decreased the --request parameter from 50k to 5k, for the first run everything was ok (no error, i could browse the GUI), then after a second run the cluster shut down again. That time some of this types of warnings logged:
`2015-05-08T09:00:15Z [5276] WARNING while trying to unregister query 4100091184from shard: s1000384communication failed: Error reading from: 'tcp://127.0.0.1:8629' 'timeout during read'`
and
`2015-05-08T09:00:43Z [4840] INFO Could talk to tcp://127.0.0.1:8629`
`2015-05-08T09:05:25Z [4840] INFO Could talk to tcp://127.0.0.1:8630`

Seems like the maximal-queue-size = 131072 still too small for a parallel 5k-request aql benchmark. Is there someting else i may vary in the configuration to stabilize the cluster?

**Comment by jsteemann** [comment] 2015-05-08 09:27
Thanks for confirming non-cluster works fine with adjusted queue size. @neunhoef : any idea about the test results when running in cluster?

**Comment by nlac** [comment] 2015-05-14 08:00
I repeated the second test case, please find the logs/configs/steps here http://nlacsoft.net/public/arango/benchmark_fails_2.5.3.zip

Please let me know if i can help more.

**Comment by nlac** [comment] 2015-05-14 08:20
@jsteemann i can confirm that with setting of async=false the benchmark works without issues with the original --request=50000 setting (this the benchmark takes a lot more time of course since all ops waits for writing to disk).

**Comment by jsteemann** [comment] 2015-05-15 07:20
@neunhoef : any idea about the cluster test results?

**Comment by neunhoef** [comment] 2015-05-15 07:28
Will look tomorrow (San Francisco time).

**Comment by fceller** [comment] 2015-06-12 10:54
@neunhoef has this been solved?

**Comment by neunhoef** [comment] 2015-06-12 12:07
This is fixed in 2.6.dev in the following sense. In the cluster - as in the single server case - if you overload the DB with async requests beyond its queue size, then it immediately answers some requests with HTTP 500. I do not really see a good way to fix this, or, to put it differently, I think this is intended behaviour.
If you run your original benchmark on a cluster in which the coordinator has set
  --scheduler.maximal-queue-size 100000
(where 100000 almost certainly just needs to be a bit larger than 50000), then it works. In 2.6 there is a separate queue for cluster-internal requests and so there is no additional contention.

**Closed** 2015-06-12 12:10 UTC
Labels: Bug, core

**Comment by nlac** [comment] 2015-06-12 15:11
Very good news, thank you! Is the working fix already recent in the 2.6 alpha 3 tag (= the most recent downloadable binaries) or just in the latest devel branch?

**Comment by neunhoef** [comment] 2015-06-12 15:12
I did test todays devel but I am pretty sure that the alpha release already works.

Am 12. Juni 2015 17:11:05 MESZ, schrieb nlac <notifications@github.com>:

**Comment by nlac** [comment] 2015-06-15 21:15
I just quickly tested v2.6a3 in cluster mode and discovered a very interesting thing. 

When i tested the cluster with the default arangod config + the increased ```scheduler.maximal-queue-size```, the result was more or less the same as experienced with the older versions: everything was slow, the GUI has frozen, got back the "Please select a cluster scenario" screen. In the log i could see such things: ```2015-06-15T20:41:12Z [6884] WARNING while trying to unregister query 25161541252from shard: s5000111communication failed: Error reading from: 'tcp://127.0.0.1:8629' 'timeout during read'``. I could easily get arangod to crash with "arangod.exe has stopped working" windows dialog, with two benchmarks after each other.

BUT then i restarted the server with an increased ```server.threads``` setting (4 -> 16) and everything seems like OK for so...: the GUI is responsive even during the benchmarks, benchmarks run with after each other with no data loss, arangodb doesn't crash...

It really gives me and my company hope:) i'll let you know what we'll experience with the new v2.6, driving by our application.
Thank you all for the hard work!
