### ISSUE TITLE
Cannot use null or empty string as bind value

### ISSUE THREAD

**Issue by Queatz** [arangodb/arangodb#4582] opened 2018-02-14 03:01 UTC
I dug into why I was getting this error sporadically (java driver):

`AQL: no value specified for declared bind parameter 'person' (while parsing)`

It seems to be because I was passing in the bind value as `null` (which I assume should be ok?) I went to the Web Interface and tried binding with `null`, which seemed fine, however empty string `""` gives "Bind Parameter: ["person"] not defined."

It seems like the only way to get around this is to check in advanced have two query strings, with and without the bind parameter, however that's not an ideal solution.

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2.11
- [ ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [X] Single-Server

Storage-Engine:
- [ ] mmfiles
- [X] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [X] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [X] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[X] I'm using graph features

I'm issuing AQL via:
- [X] web interface with this browser:     running on this OS:
- [ ] arangosh
- [X] this Driver: java

**Comment by maxkernbach** [comment] 2018-02-14 13:00
Hi @Queatz,

thanks for reporting the bug. Using `null` as a bind parameter returns you error `AQL: no value specified for declared bind parameter 'person' (while parsing)` as you described. You can use an empty string bind parameter `""` as a workaround. We are going to investigate on using an empty string on the Web Interface.

I close this issue and move it to the [java-driver repository](https://github.com/arangodb/arangodb-java-driver/issues/176).

**Closed by maxkernbach** 2018-02-14 13:00 UTC
Labels: 3 AQL, 3 Java

**Comment by pilot4u** [comment] 2018-03-08 21:11
I started getting this error, when executing my Foxx service:
AQL: no value specified for declared bind parameter 'lat' (while parsing)

my query:
for rest in Rest
let dist = distance(rest.location.geo[0],rest.location.geo[1], @lat, @lng) 
sort dist
return MERGE(rest,{distance:dist})

query parameters:
{"lng":31.749314,"lat":34.9937314}
this issue started today after I upgraded from version 3.3.3 to version 3.3.4

the same query is running OK using arangosh , and arangojs driver.
but when running on Foxx service receiving described error

might it be related to this bug fix, which should be implemented for inner js @arrangodb ?

**Comment by jsteemann** [comment] 2018-03-09 08:21
I just tried the same query from the web interface and from inside a Foxx service.
The results were identical in both cases.
I also tried the query with and without having a geo index present on the `location.geo` attribute.

As we have trouble reproducing the problem, can you post the exact code you are using to invoke the query from inside the Foxx service? Thanks!

**Comment by pilot4u** [comment] 2018-03-09 11:44
This query works within web interface, but throws error (mentioned below) when executed within Foxx service.
relevant code section which is executed within Foxx service:
        console.log(`executing query: ${query} with params: ${JSON.stringify(params)}`);
        let result;
        try{
                result = _db._query(query, params);
                console.log(`result: ${JSON.stringify(result)}`);
        } catch(e){
                console.error(`exception: ${JSON.stringify(e)}`);
        }

log output:

2018-03-09T11:42:23Z [45786] INFO executing query: for rest in Restaurant let dist = distance(rest.location.geo[0],rest.location.geo[1], @lat, @lng) sort dist return MERGE(rest,{distance:dist}) with params: {"lat":34.9937314,"lng":31.749314}
2018-03-09T11:42:23Z [45786] ERROR exception: {"errorNum":1551,"errorMessage":"AQL: no value specified for declared bind parameter 'lat' (while parsing)"}

**Comment by jsteemann** [comment] 2018-03-09 12:01
Ok, two questions back:
* in your code you use `_db`. What exactly is it? Is that the same as`require("@arangodb").db` or some wrapper for it. If a wrapper, then could you please check if it passes on all arguments from its `_query` function to `require("@arangodb")._query`?
* what (JavaScript) types do `params.lat` and `params.lng` have? Above it looks like they are JavaScript `Number`s, but it's hard to tell exactly from here. Can you try finding out about the types, and also try if the query works when replacing the values of `params.lat` and `params.lng` with plain hard-coded numbers? This should definitely work.

**Comment by pilot4u** [comment] 2018-03-09 14:44
_db = require("@arangodb").db;

params.lat and params.lng are JS numbers
this query works if lat and lng are provided within it's body, but it's insecure according to arangoDb's docs: [AvoidingInjection](https://docs.arangodb.com/3.3/Cookbook/AQL/AvoidingInjection.html)
as well I have the same problem with all queries that are executed using `require("@arangodb").db._query` function and has parameters.
this urged me to post my issue, because I suspect that it point on a bug within _query function execution cycle, which might be related with following bug fix

**Comment by pilot4u** [comment] 2018-03-09 15:43
as well I use "@arangodb/foxx/graphql"
and passing the args value to params as is.
which might causing this issue.
because string serialization and destabilization, solves this issue:

let strParams = JSON.stringify(params);
console.log(strParams);
let parsedParams = JSON.parse(strParams);
return _db._query(query, parsedParams);

I suspect that args might include some prefix which eliminated by serialization and destabilization, 
but it's still weird issue because graphql resolver args should contain js dict.
