### ISSUE TITLE
Droping a Graph

### ISSUE THREAD

**Issue by XescuGC** [arangodb/arangodb#1456] opened 2015-08-24 23:53 UTC
I've found some issue trying to delete a graph, for more information of this issue you can follow this [issue](https://github.com/arangodb/arangojs/issues/30) on the arangojs project.

**Comment by mchacki** [comment] 2015-08-25 07:05
Hi @XescuGC thanks for reporting it.
In order to reproduce this issue i need some more information:
1) Which version of ArangoDB are you using? 
2) Could you give me the description of your graph? (EdgeCollections with their from and to collections and other vertex collections) (i do not need the stored data)

best
Michael

**Comment by XescuGC** [comment] 2015-09-03 17:04
Sorry for the delay :cry: 

> 1) Which version of ArangoDB are you using? 

ArangoDB 2.6.5 64bit

> 2) Could you give me the description of your graph? (EdgeCollections with their from and to collections and other vertex collections) (i do not need the stored data)

Well it's a simple Graph, i'll use an example:

I have 2 collections that work as Vertex, collection A with 12k docs, and collection B with 4k docs, and the edge collection E is about 115k docs. The E collection goes from A to B, each doc of A may have up to 12 edges (or more) pointing to different B docs.

**Comment by mchacki** [comment] 2015-09-17 09:41
Hi @XescuGC 
also sorry for the delay.
I am sorry i am still not able to reproduce your problem ;(

Could you send me the result of
```
arangosh> db._graphs("<graphname>")
```

maybe something in the definition is in a broken state.

**Comment by dothebart** [comment] 2015-10-01 15:45
closing this because of feedback missing.

**Closed by dothebart** 2015-10-01 15:45 UTC
Labels: api, Bug, graph
