### ISSUE TITLE
Two or more deeply nested structures fail to update, instead are replaced with `(non-representable type)` and all child structures truncated

### ISSUE THREAD

**Issue by hallicarnassus** [arangodb/arangodb#4751] opened 2018-03-05 06:05 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run the AQL explain function and it didn't shed more light on this.

**AQL Query Used:**
`FOR doc IN MyCollection
    LET one_name_a = SUBSTRING(doc.sub_1.sub_12.sub_A.longName, 0, 5)
    LET one_name_z = SUBSTRING(doc.sub_1.sub_12.sub_Z.longName, 0, 5)
    LET one_type_a = SUBSTRING(doc.sub_1.sub_12.sub_A.typeID, 6, 4)
    LET one_type_z = SUBSTRING(doc.sub_1.sub_12.sub_Z.typeID, 6, 4)

    LET two_name_a = SUBSTRING(doc.sub_2.sub_22.sub_A.longName, 0, 5)
    LET two_name_z = SUBSTRING(doc.sub_2.sub_22.sub_Z.longName, 0, 5)
    LET two_type_a = SUBSTRING(doc.sub_2.sub_22.sub_A.typeID, 6, 4)
    LET two_type_z = SUBSTRING(doc.sub_2.sub_22.sub_Z.typeID, 6, 4)
    
    UPDATE doc WITH {
        "sub_1":{
            "sub_12":{
                "sub_A":{
                    "Name": one_name_a,
                    "typeID": one_type_a
                },
		"sub_Z":{
                    "longName": one_name_z,
                    "typeID": one_type_z
                }
            }
        },
	"sub_2":{
            "sub_22":{
                "sub_A":{
                    "Name": two_name_a,
                    "typeID": two_type_a
                },
		"sub_Z":{
                    "longName": two_name_z,
                    "typeID": two_type_z
                }
            }
        }
    } IN MyCollection`

**Initial Document Structure:** 
`{
	"sub_1": {
		"sub_12":{
			"sub_A": "ABCDE-4ABC-00001"}
		}
	},
	"sub_2": {
		"sub_22":{
			"sub_A": "FGHIJ-7KLM-00002"}
		}
	}
}`

**Intended Result:**
`{
	"sub_1": {
		"sub_12":{
			"sub_A": "ABCDE-4ABC-00001",
			"one_name_A":"ABCDE",
			"one_name_Z":"4ABC"}
		}
	},
	"sub_2": {
		"sub_22":{
			"sub_A": "FGHIJ-7KLM-00002",
			"two_name_A": "FGHIJ",
			"two_name_Z": "7KLM"
		}
	}
}
`

The first nested structure `sub_1` will update fine, however the second structure will update intermittent records, where any fields which do not update result in the nested structure to become truncated and replaced with `(non-representable type)`. 

Eg: 
`{
	"sub_1": {
		"sub_12":{
			"sub_A": "ABCDE-4ABC-00001",
			"one_name_A":"ABCDE",
			"one_name_Z":"4ABC"}
		}
	},
	"sub_2": (non-representable type)
}
`

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [x] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

**Comment by jsteemann** [comment] 2018-03-05 08:13
Based on the above data, I just tried the following, but it does not show the problem:
```js
db._drop("MyCollection"); 
db._create("MyCollection"); 
db.MyCollection.insert({ "sub_1": { "sub_12":{ "sub_A": "ABCDE-4ABC-00001"}  }, "sub_2": { "sub_22":{ "sub_A": "FGHIJ-7KLM-00002"} } }); 

q = `
FOR doc IN MyCollection 
  LET one_name_a = SUBSTRING(doc.sub_1.sub_12.sub_A.longName, 0, 5) 
  LET one_name_z = SUBSTRING(doc.sub_1.sub_12.sub_Z.longName, 0, 5) 
  LET one_type_a = SUBSTRING(doc.sub_1.sub_12.sub_A.typeID, 6, 4) 
  LET one_type_z = SUBSTRING(doc.sub_1.sub_12.sub_Z.typeID, 6, 4)  
  LET two_name_a = SUBSTRING(doc.sub_2.sub_22.sub_A.longName, 0, 5) 
  LET two_name_z = SUBSTRING(doc.sub_2.sub_22.sub_Z.longName, 0, 5) 
  LET two_type_a = SUBSTRING(doc.sub_2.sub_22.sub_A.typeID, 6, 4)
  LET two_type_z = SUBSTRING(doc.sub_2.sub_22.sub_Z.typeID, 6, 4)
  UPDATE doc WITH {"sub_1":{"sub_12":{"sub_A":{"Name": one_name_a,"typeID": one_type_a }, "sub_Z":{ "longName": one_name_z, "typeID": one_type_z }}},"sub_2":{"sub_22":{"sub_A":{"Name": two_name_a,"typeID": two_type_a}, "sub_Z":{"longName": two_name_z,"typeID": two_type_z}}} } IN MyCollection
`; 
db._query(q); 
db.MyCollection.toArray();
```
The problem here is that there are probably some initial data missing. For example, the AQL query refers to attributes named `typeID` and `longName`, which are not even present in the initial document structure shown. Is it possible to provide a slightly more extended use case which shows the problem in some self-contained way? Thanks!

**Comment by OmarAyo** [comment] 2018-03-16 12:00
Hi @hallicarnassus 

Can you please give us a feedback on this ticket? 

Best,

**Comment by maxkernbach** [comment] 2018-04-09 15:00
Hi @hallicarnassus,

we could not reproduce your problem with the given information and have not received any feedback for over one month. I am closing this issue for now.

Please feel free to reopen this issue in case the problem persists and provide a more detailed use case.

**Closed by maxkernbach** 2018-04-09 15:00 UTC
Labels: 3 AQL, Waiting User Reply
