### ISSUE TITLE
Arangoimp with error `ERROR cluster internal HTTP connection broken`

### ISSUE THREAD

**Issue by lidaling** [arangodb/arangodb#5340] opened 2018-05-14 07:29 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- 3.3.8

Mode:
- Cluster [3 nodes]

Storage-Engine: 
-  rocksdb 

On this operating system:
  - kvm centos7  with  2 cores and 8 GB RAM

#### datafile

- 20GB 
- 100m records

command is
> nohup arangoimp --threads 4 --file ./180504_trans_100m.csv --type tsv --collection trans --create-collection true --server.database test --server.username test --server.password dtise123 --batch-size 4194304 > ./log &

#### error message

```
capping --threads value to 2
Connected to ArangoDB 'http+tcp://127.0.0.1:8529', version 3.3.8, database: 'test', username: 'test'
----------------------------------------
database:               test
collection:             trans
create:                 yes
source filename:        ./180504_trans_100m.csv
file type:              tsv
separator:
threads:                2
connect timeout:        5
request timeout:        1200
----------------------------------------
Starting TSV import...
2018-05-14T02:44:54Z [24374] INFO processed 609779712 bytes (3%) of input file
2018-05-14T02:48:02Z [24374] INFO processed 1219526656 bytes (6%) of input file
2018-05-14T03:00:17Z [24374] INFO processed 1829273600 bytes (9%) of input file
2018-05-14T03:19:03Z [24374] INFO processed 2439020544 bytes (12%) of input file
2018-05-14T03:33:07Z [24374] INFO processed 3048767488 bytes (15%) of input file
2018-05-14T03:45:12Z [24374] INFO processed 3658514432 bytes (18%) of input file
2018-05-14T03:56:37Z [24374] INFO processed 4268261376 bytes (21%) of input file
2018-05-14T04:06:29Z [24374] INFO processed 4878008320 bytes (24%) of input file
2018-05-14T04:27:30Z [24374] INFO processed 5487755264 bytes (27%) of input file
2018-05-14T05:02:02Z [24374] INFO processed 6097502208 bytes (30%) of input file
2018-05-14T06:07:27Z [24374] INFO processed 6707281920 bytes (33%) of input file

2018-05-14T06:34:21Z [24374] ERROR error message(s):
2018-05-14T06:34:21Z [24374] ERROR cluster internal HTTP connection broken
2018-05-14T06:34:21Z [24374] ERROR cluster internal HTTP connection broken
2018-05-14T06:34:21Z [24374] ERROR cluster internal HTTP connection broken
...
```

How to fix it.
Thanks

**Comment by maxkernbach** [comment] 2018-05-14 09:42
Hi @lidaling,

thanks for reporting, this is a known issue. I am closing this issue as a duplicate of #4912. Could you try the suggested workaround by dothebart?

> The core of this problem is that the coordinator isn't patient enougf with the DB-Server, which may be I/O bound. ArangoImp tries to run two parallel threads, which you can set with --threads 1. You can further reduce the stress by reducing the --batch-size to a value like 512000 which should serve as a proper workaround for the time being.
We're currently investigating howto fix this issue on the serverside too.

**Closed by maxkernbach** 2018-05-14 09:42 UTC
Labels: 3 Cluster, 3 ImportExport
