### ISSUE TITLE
aql regex "\s" key does not work

### ISSUE THREAD

**Issue by iduchy** [arangodb/arangodb#7855] opened 2018-12-25 15:01 UTC
## My Environment

* __ArangoDB Version__:       3.4.0
* __Storage Engine__:            RocksDB
* __Deployment Mode__:      Single Server
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__: AQL query using web interface
__AQL query__: for pattern in ["\s", " "] return regex_test(" ", pattern)
__AQL result__: [false, true]

__Problem__: "\s" regex pattern does not wok 
__Expected result__: [true, true]

**Comment by Simran-B** [comment] 2018-12-26 21:38
3.3 also affected. It seems to work if you escape the backslash:

    FOR pattern IN ["\\s", " "] RETURN REGEX_TEST(" ", pattern)

In Arangosh, you need to escape backslashes for the shell also:

    FOR pattern IN ["\\\\s", " "] RETURN REGEX_TEST(" ", pattern)

Curl under Windows:

    echo {"query":"FOR pattern IN ['\\\\s', ' '] RETURN REGEX_TEST(' ', pattern)"} | curl -u root: --data-binary @- http://localhost:8529/_api/cursor | jq ".result"

(`\\\\s` is true, `\\s` is false, `\s` is null - silent error?)

`REGEX_TEST("\n", "\n")` and `REGEX_TEST("\n", "\\n")` both return `true`, same goes for `\t` (one or two backslashes). JSON supports such encoded line breaks and tabs directly. But shouldn't it be supported without escaped backslash in AQL? It's not fully clear to me what the intended behavior is. Do we need to change something in AQL or the documentation?

**Comment by iduchy** [comment] 2018-12-28 18:08
- JS: new RegExp("\\s") or /\s/; 
- Python: re.compile('\\s') or re.compile(r'\s')
Logic says it should be REGEX_TEST("\\s", " "), where regexp compiled within the function with the string argument and adding some ecranning key as /.../ in js or r in Python to use it nicely

**Comment by dothebart** [comment] 2020-09-02 10:53
With the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) I'm closing tihs as solved.

**Closed by dothebart** 2020-09-02 10:53 UTC
Labels: 1 Bug, 3 AQL
