### ISSUE TITLE
3.2 graph filter + options

### ISSUE THREAD

**Issue by ile** [arangodb/arangodb#3459] opened 2017-10-19 03:30 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Single-Server

Storage-Engine: 
- haven't checked/don't know

On this operating system:
  - [x] Ubuntu .deb

### this is an AQL-related issue:
- [x] I'm using graph features

I'm issuing AQL via:
- [x] this Driver: arangojs

The AQL query in question is:

```
FOR v, e, p in OUTBOUND @from GRAPH @graphName OPTIONS { bfs: true } FILTER p.vertices[1]._id == @v2 RETURN v._key
```

With this the filtering doesn't seem to happen. 

With `OPTIONS` removed it seems to happen:

```
FOR v, e, p in OUTBOUND @from GRAPH @graphName OPTIONS { bfs: true } FILTER p.vertices[1]._id == @v2 RETURN v._key
```

values:

```
{ graphName: 'somegraph',
     from: 'users/me',
     v2: 'items/someitem' }
```

**Comment by ile** [comment] 2017-10-19 03:31
I haven't looked further into this, I just removed OPTIONS and it seemed to work.

OPTIONS would work in 3.1.

**Comment by OmarAyo** [comment] 2018-04-26 15:07
Hi @ile,

Sorry for the delay, unlucky I've not been able to reproduce it 
Could you please send us a short feedback about this ticket so I can continue working on it.

Best

**Comment by OmarAyo** [comment] 2018-06-15 12:50
Hi @ile 

Just sending a quick followup - how things are going? 

Please note that version 3.3.10 is available

**Comment by maxkernbach** [comment] 2018-07-10 09:53
Hi @ile, 

im am closing this issue for now as we could not reproduce it and have not received any feedback for a few months. Please feel free to comment and reopen in case this problem persists.

**Closed by maxkernbach** 2018-07-10 09:53 UTC
Labels: 3 AQL, 3 Graph, Waiting User Reply
