### ISSUE TITLE
Frontend shows already deleted databases during login

### ISSUE THREAD

**Issue by fdsg-tk** [arangodb/arangodb#2442] opened 2017-04-20 15:25 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ X] 3.1 (3.1.18)
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [X] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser: Firefox 52   running on this OS: Windows
- [X ] authentication is enabled?
- [ ] using the cluster?
- [X] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as root

The following problem occurs:
When you are initially logging into the frontend, you can select databases which have already been deleted from arangodb. 
If you do, an error appears: "database not found" (which is totally correct).
This does not happen, when you are already logged in and want to switch to another database. 
In this case, only existing databases are shown.

**Comment by hkernbach** [comment] 2017-04-25 07:42
Thanks for the report. This is not a front-end issue. The origin of the issue is: #2047 
Anyway: I've included a momentary workaround (3.1 and devel branches). Now only valid databases will be shown, but still #2047 needs to be resolved.

**Comment by dothebart** [comment] 2017-05-03 11:40
3.1.19 is available for download - closing. Feel free to comment if the issue persists.

**Closed by dothebart** 2017-05-03 11:40 UTC
Labels: 1 Bug, 2 Fixed, 3 Front-End
