### ISSUE TITLE
Hard crash in query for pagination

### ISSUE THREAD

**Issue by rynmsh** [arangodb/arangodb#3408] opened 2017-10-12 18:22 UTC
## my environment running ArangoDB
Test on 3.0.8 (docker), latest build in docker - then tried installing through home brew. All same results. On macOS. 

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine: (tried both)
- [x] mmfiles
- [x] rocksdb

On this operating system:
- [x] docker - official docker library
- [x] MacOS, version: 10.12.6

### this is an AQL-related issue:
[x] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [x] this Driver:javascript

The issue can be reproduced using this dataset:

https://gist.githubusercontent.com/rynmsh/d4192d6edcc0f8a2d4a3263a496f4a13/raw/6128c6b85a48ac48a150b0d7b5ebac637319be01/useragents-data.json

These are the steps to reproduce:
1) Restore the data above to a collection
2) Run query below

LET agents = (
    FOR agent IN UserAgent 
    RETURN agent
)

RETURN {
    total: COUNT(agents),
    paged: (
        FOR i IN agents 
        LIMIT 1000, 15
        RETURN i
    )
}

I'm getting these results returned back - then the server crashes

[
  {
    "total": 2303,
    "paged": [
      "(non-representable type)",
      "(non-representable type)",
      "(non-representable type)",
      "(non-representable type)",
      "(non-representable type)",
      "(non-representable type)",
      "(non-representable type)",
      "(non-representable type)",
      "(non-representable type)",
      "(non-representable type)",
      "(non-representable type)",
      "(non-representable type)",
      "(non-representable type)",
      "(non-representable type)",
      "(non-representable type)"
    ]
  }
]

...

The following problem occurs: [Screenshot?] 
The arango server hard crashes - in the docker logs I only see this
"grabbing logs: invalid character '\x00' looking for beginning of value"

**Comment by jsteemann** [comment] 2017-10-12 19:26
Just tried to reproduce with current 3.2 (3.2.4) and latest 3.0 (3.0.12) on Linux (have no access to MacOS) and was not able to reproduce the problem.
Now trying 3.0.8.

**Comment by jsteemann** [comment] 2017-10-12 19:36
Have now tried with 3.0.8 on Linux (still no access to MacOS), and still am not able to reproduce the problem.
Maybe it is specific to the combination of MacOS & Docker.

**Comment by jsteemann** [comment] 2017-10-12 19:36
Any chance you can check with current 3.0 (3.0.12) or current 3.2 (3.2.4)?

**Comment by rynmsh** [comment] 2017-10-13 11:54
I'll run those versions now and test. Is there I way I can edit config to turn verbose logging on when running as docker container?

**Comment by jsteemann** [comment] 2017-10-13 14:18
AFAIK you can turn on verbose logging by passing extra ArangoDB config arguments to `docker run`, e.g.:
```docker run -e ARANGO_NO_AUTH=1 arangodb/arangodb --log.level=trace```

**Comment by rynmsh** [comment] 2017-10-13 15:06
Currently running latest version (docker) with verbose logging on. Variable results here, first attempt the container just crashed, nothing written to logs. 

Created collection 'UserAgent', imported data, ran query, crash. 

Second attempt, created collection called 'useragent', ran query and got these results, ran this 2 more times, on the 3rd attempt the server crashed. 
`
[{
    "total": 1921,
    "paged": [ 
"(non-representable type)",
"(non-representable type)",
      "(non-representable type)",
      { this was an actual result, just removed it for this example }
}
]
`

**Comment by rynmsh** [comment] 2017-10-13 15:17
Have just tested this on our dev arango server instance, its an AWS AMI for version 3.0.8. 

Arango instance crash, I then logged into the box to try restart the service. 

FATAL could not open shutdown file '/vol/data/standalone/SHUTDOWN': internal error

**Comment by jsteemann** [comment] 2017-10-13 15:42
Ok, finally got it reproduced locally.

**Comment by rynmsh** [comment] 2017-10-13 15:48
Ok awesome, FYI I just tried this using the latest AMI available and got same result

**Comment by jsteemann** [comment] 2017-10-13 16:52
Fixed the issue in the above commits. There are also PRs for each branch.

**Comment by jsteemann** [comment] 2017-10-19 14:28
This problem has been fixed in 3.2.5, which is available for download.

**Closed by jsteemann** 2017-10-19 14:28 UTC
Labels: 1 Bug, 2 Fixed, 3 AQL
