### ISSUE TITLE
Index on array not created

### ISSUE THREAD

**Issue by oliverhausler** [arangodb/arangodb#11691] opened 2020-05-26 15:23 UTC
3.6.2

Using the JS driver
```
	await db
		.collection('users')
		.createPersistentIndex(['handles[*]'], { unique: true, sparse: false })
```
returns
```
{
  "deduplicate": true,
  "fields": [
    "handles[*]"
  ],
  "id": "users/6200610",
  "inBackground": false,
  "isBuilding": true,
  "isNewlyCreated": false,
  "name": "idx_1667589750212526080",
  "sparse": false,
  "type": "persistent",
  "unique": true,
  "error": false,
  "code": 200
}
```

Then nothing happens. The index seems to be `isBuilding` but is not returned:

![image](https://user-images.githubusercontent.com/8090341/82918828-41930200-9f43-11ea-9874-cd0c53335b9f.png)

We are running in cluster mode, it works fine on a single machine.

**Comment by Simran-B** [comment] 2020-05-27 10:23
Hi @oliverhausler,

it is expected that `getIndexes()` doesn't return the index definition after you just created it as long as building the index happens. It should appear once the index is ready.

> Indexes that are still in the build process will not be visible via the ArangoDB APIs.

https://www.arangodb.com/docs/stable/indexing-index-basics.html#behavior

Does the index show up eventually or not at all, with close to no resource utilization?

**Comment by oliverhausler** [comment] 2020-05-27 12:36
Hi @Simran-B,

It doesn't show up at all, even after 2 days.

I can't say much about resource utilization as there are only around 100 documents. So I would think it should be close to instant.

**Comment by Simran-B** [comment] 2020-05-27 20:33
I see, and yes, I would also expect it to finish within seconds.

What if you drop the index in arangosh and re-create it? Does that not work either, reproducibly?

**Comment by lnogol** [comment] 2020-05-27 20:40
I tried this

- reduced `replicationFactor` to 1 so it's "easier" for the DB
![image](https://user-images.githubusercontent.com/22595961/83069087-9d57ab00-a069-11ea-852d-c54f7a9886c8.png)
![image (1)](https://user-images.githubusercontent.com/22595961/83069130-aba5c700-a069-11ea-8ec4-12c5da66106c.png)
- created the index again
![image (2)](https://user-images.githubusercontent.com/22595961/83069156-b8c2b600-a069-11ea-9fb3-0d384339e01b.png)

The CLI is stuck. Index is not visible in the UI and arangosh `getIndexes()`. I see no logs from any of the 3 cluster components.

I have an agency dump that I can send somewhere if needed.

> What if you drop the index in arangosh and re-create it?

can't be dropped because apparently it wasn't even created

when I try anyway (using the returned `id` from the previous attempt, first post) 

```sh
db._useDatabase('attach')
db._collection('users').dropIndex('users/6225560')
```

I get `false`

**Comment by oliverhausler** [comment] 2020-05-27 20:42
@lnogol is my team-mate, same problem.

**Comment by maxkernbach** [comment] 2020-06-03 14:25
Hi @oliverhausler, @lnogol,

Would it be possible to share a database dump of the affected database "attach" (using [arangodump](https://www.arangodb.com/docs/stable/programs-arangodump.html))?

You can send us a message to hackers@arangodb.com (this ML is not public) and attach the dump in that email. This way we can try to reproduce and find the root cause. Please reference the number of this issue in your email.

**Comment by oliverhausler** [comment] 2020-06-03 20:42
@maxkernbach Thanks for the offer to help. We just trashed the cluster and set it up from scratch. The index built immediately. Maybe @lnogol has a dump of the previous installation, still.

**Comment by Simran-B** [comment] 2020-06-24 12:14
@oliverhausler was the original cluster where the problem occurred upgraded at some point, e.g. 3.5.x -> 3.6.2 or maybe even 3.4.x -> 3.6.2?

**Comment by oliverhausler** [comment] 2020-06-24 20:11
Not that I know. It was a fresh install on 3.6.2 I believe.
@lnogol Can you confirm please.

We're on 3.6.4 now but made a fresh install. The index worked right away in 3.6.4. Not sure if we were lucky, something was corrupted in our previous install or this has been fixed  in the meantime.

**Comment by lnogol** [comment] 2020-07-02 22:02
fresh install `3.6.2` - didn't work
fresh install `3.6.4` (current) - works

**Comment by Simran-B** [comment] 2020-08-19 11:30
@oliverhausler @lnogol While the cause is still unclear, I'll close the issue for now as we don't know how to reproduce the issue. Please re-open should the problem occur again. An agency dump might be relevant in that case, to see if there's something fishy which might cause the index creation to be ignored silently.

**Closed by Simran-B** 2020-08-19 11:30 UTC
Labels: 1 Question, 3 API, 3 Index, Waiting User Reply
