### ISSUE TITLE
Unexpectedly slow & strange wake up time

### ISSUE THREAD

**Issue by MartinBrugnara** [arangodb/arangodb#2229] opened 2016-12-19 17:28 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 2.8

On this operating system:
- [x] Linux 
  - [x] other: docker (`FROM  openjdk:8`)

### Issue:
I need to know when the system is fully loaded, to then run some  queries from gremlin.
To do that I am waiting until `http://localhost:8529/_db/_system/_admin/aardvark/standalone.html` returns `200` and the I force the load of my nodes and edges via
```
curl -s "http://localhost:8529/_api/collection/V/properties"
curl -s "http://localhost:8529/_api/collection/E/properties" 
```

All works fine unless the **dataset** is not **very small**, with 64MB JSON dataset (on disk) works fine.
With a 1.6K JSON file it takes **520 seconds** to wake up (with the data loaded).

I've attached the dataset and the _arangod.conf_.
[issue.zip](https://github.com/arangodb/arangodb/files/661694/issue.zip)

[EDIT] the attached dataset has a typo (double ,) inside. The one used for test not.

The server is started with
```
arangod --server.disable-authentication="true" --server.disable-statistics true --daemon --pid-file /etc/arangodb/arang
```

Am I missing something?

**Comment by jsteemann** [comment] 2016-12-20 07:43
It is expected that arangod can load these data in a fraction of a second.
Can you provide the collection definitions as well as the dataset? The attached JSON file leaves room for interpretation because it's unclear how data from this file got imported into the two collections.

Dumping the two collections with arangodump would be ideal, because that would include both collection definitions and data in an unambiguous format. Thanks!

Re the wake-up time: my understanding of your issue description is that the wake-up time that you measured is the time between server start and the return of the last curl command (the one that loads collection `E`). Do you know how long each of the three curl commands took? My expectation is that none of the latter two (that load the collections) should take a significant amount of time. So it's probably the first curl command that waits until the server is up and running without the collections being loaded. Can you confirm this is the case?

**Comment by MartinBrugnara** [comment] 2016-12-22 15:59
Hi, I am attaching the dump obtained via `arangodump --output-directory`.
[0p-dump.tgz.zip](https://github.com/arangodb/arangodb/files/669160/0p-dump.tgz.zip)


Yes it is **only** the first command that waits `http://localhost:8529/_db/_system/_admin/aardvark/standalone.html`.



> It is expected that arangod can load these data in a fraction of a second.

It actually takes 40sec to answer the first curl call for any dataset we tested, except for the one attached.

**Comment by MartinBrugnara** [comment] 2017-01-02 14:56
Yeah, the intuition behind waiting for the first curl is exactly the one to wait for Arango to be fully ready. *But* the strange thing is that in our settings it takes so much time only with very small dataset (like the one attached), and it's faster with bigger ones.

We tried to collect further informations we got tons of log lines like the following ones. When it stops dumping line like those it starts and answers 200 to curl.
```
2017-01-02T15:58:27Z [9] ERROR cannot rename dropped collection '_users' from '/var/lib/arangodb/databases/database-89431/collection-417111' to '/var/lib/arangodb/databases/database-89431/deleted-417111': system error
2017-01-02T15:58:57Z [9] WARNING unable to remove collection directory '/var/lib/arangodb/databases/database-89431/collection-417111'
2017-01-02T15:58:57Z [9] WARNING forcefully deleting collection directory '/var/lib/arangodb/databases/database-89431/collection-417111'
2017-01-02T15:58:57Z [9] ERROR cannot rename dropped collection '_graphs' from '/var/lib/arangodb/databases/database-89431/collection-2252119' to '/var/lib/arangodb/databases/database-89431/deleted-2252119': system error
2017-01-02T15:59:27Z [9] WARNING unable to remove collection directory '/var/lib/arangodb/databases/database-89431/collection-2252119'
2017-01-02T15:59:27Z [9] WARNING forcefully deleting collection directory '/var/lib/arangodb/databases/database-89431/collection-2252119'
2017-01-02T15:59:27Z [9] ERROR cannot rename dropped collection '_modules' from '/var/lib/arangodb/databases/database-89431/collection-2383191' to '/var/lib/arangodb/databases/database-89431/deleted-2383191': system error
``` 

We double checked permissions: the user is set to be `arango` and permissions to `777`.

We do not have any Foxx app.

Thanks
Maritn

**Comment by jsteemann** [comment] 2017-01-02 16:37
The above output is from the WAL recovery phase. It looks like it tries to rename/remove collection directories during recovery, and it tries for 30 seconds before giving up. There is an up-to-30-seconds wait before rename/remove gives up. So these waits are to blame for the long startup times you are encountering. 
I am not sure why the rename/remove fails as the log output only reveals "system error".

To find out, can you try again but between steps 3 and 4 execute the following command inside the docker container and copy the output: `ls -alR /var/lib/arangodb/databases/`. After that, start the container normally using step 4. This should produce the same errors, but together with the output from `ls` it may indicate what the problem is.

Can you post the output from the `ls` command and the WAL logfile recovery errors here so we can check it? Thanks!

**Comment by MartinBrugnara** [comment] 2017-01-03 13:51
Here comes the files as requested...

[arango.databases.ls.txt](https://github.com/arangodb/arangodb/files/682313/arango.databases.ls.txt)
[arangodb.log.txt](https://github.com/arangodb/arangodb/files/682312/arangodb.log.txt)

**Comment by m0ppers** [comment] 2017-01-03 17:17
We are currently investigating into different directions to tackle this problem. A few questions from my side:

1. What do you mean with `other: docker (FROM openjdk:8)`? Are you using your own docker container? If so, can you provide us with the Dockerfile?
2. On which host system are you running docker? We had several issues with mac as a host system for docker.
3. How did you start the docker container? i.e. the complete docker cmdline.

**Comment by MartinBrugnara** [comment] 2017-01-15 22:48
Sure here they come:

1. http://pastebin.com/h5XNGvwJ
It's a fork of the official one (arangodb/arangodb-docker) with the addition of gremlin 2 and go**.

1. Experienced both on a srv and on a small dev machine 
  - Host 1:
Ubuntu 14.04.4 LTS
Linux sleepy 3.13.0-86-generic #131-Ubuntu SMP Thu May 12 23:33:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
2 x Intel(R) Xeon(R) CPU E5-2420 0 @ 1.90GHz
128G ram
     - Docker version 1.11.1, build 5604cbe

   - Host 2:
OSX 10.12
8GB ram
     - Docker for Mac 1.13 beta (different build)

1. Starting command is the classic `docker run --rm ` with some `-e` and `-v` we need.
If you want I can generate an example but I think what you really want is the init scripts:
  - arangodb-init.sh http://pastebin.com/6GPCc67L  
     Start the serve as daemon, and wait for the db to be ready polling for the `properties` endpoints.
  - execute.sh  
     `gremlin.sh -e /tmp/query 2>> /exp/errors 1>> /exp/results`




** Due to #1939 I've to use arangoimp to load the original dataset which I've stored as graphson, thus I've to convert it... and I am using a small go 'program'.

**Comment by kuzeko** [comment] 2017-01-30 15:52
Any update on this?
Thanks

**Comment by dothebart** [comment] 2017-01-30 16:19
We can confirm this is a bug. However currently all resources are allocated so we didn't find out why its happening.

**Comment by fceller** [comment] 2017-02-14 07:44
@MartinBrugnara I'm trying to reproduce this locally. You already provided a lot of information. Unfortunately, this bug still manages to elude me. 

One question regarding:

> Starting command is the classic docker run --rm with some -e and -v we need.
> If you want I can generate an example but I think what you really want is the init scripts:

Is the ArangoDB data directory mapped to the outside world with -v?

**Comment by MartinBrugnara** [comment] 2017-02-14 08:33
Hi @fceller, 
no the data is not a shared nor host volume, long story short I've to commit the data in the image.

I am conscious this provide a slow down in terms of I/O but this shall affect all experiments and not only the _micro_ ones.

**Comment by fceller** [comment] 2017-02-14 08:36
@MartinBrugnara I currently tried on a Mac. I will switch to Linux machine and try there.

**Comment by fceller** [comment] 2017-02-14 12:42
@MartinBrugnara I still had no luck in reproducing this. The data is only fake data, right?

Can we try something desperate?

> Since we (in order)
> 1- fire up a new docker image with a clean arango installation and no dataset loaded (this first step, arango reply to the curl in ~4s)
> 2- load the dataset with the aforementioned arangoimp command
> 3- shut down the docker container
> 4- fire up again the container and test the curl

Instead of 4 can you execute a "docker inspect CONTAINERID" and look for

```
        "Mounts": [
            {
                "Name": "2e4801762652ef3ffaf5129fb68dd261e01a42834f4b637bb90642088a9ba959",
                "Source": "/var/lib/docker/volumes/2e4801762652ef3ffaf5129fb68dd261e01a42834f4b637bb90642088a9ba959/_data",
                "Destination": "/var/lib/arangodb",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Name": "7ea332537fe04c666a124292d5b7823f6c088ad9491723466728fb51e1374842",
                "Source": "/var/lib/docker/volumes/7ea332537fe04c666a124292d5b7823f6c088ad9491723466728fb51e1374842/_data",
                "Destination": "/var/lib/arangodb-apps",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
```

Can you tar the two Source directories on the host and send them to me?

**Comment by MartinBrugnara** [comment] 2017-02-14 13:19
Sure, at the moment I am out of office, thus no access to the servers...
I will come back to this ASAP.

**Comment by fceller** [comment] 2017-02-14 13:21
Perfect. It is a bit frustration if we are not able to reproduce (and then solve) your issue. I hope that this will give us enough insight.

**Comment by MartinBrugnara** [comment] 2017-05-09 15:04
*Sorry for disappearing, but other critical things required my attention.*

### Volumes snapshot
> 4- fire up again the container and test the curl

Technically this is point 5 because we do not restart the same container: we commit it as an image to achieve persistence of the data and initial setup.
This also implies that we are not using the volumes to hold the data (yes we are aware of the slowdown introduced by AUFS, but this does not explain the behavior).

In place of the requested volumes snapshot I am providing the full images snapshot (from which you can extract the content of the binded directories).

### Links
I've used an `Ubuntu 14.04.5 LTS`, docker  `1.13.0`, and arangodb `2.8.11`
- Datasets:
   - 1.6 KB, **~520s** wake up time:  [freebase_0000.json](https://drive.google.com/file/d/0B6A9_3MuVDTwalRyUWZEVzBvcm8/view?usp=sharing)
   - 64 MB, **~7s** wake up time:  [freebase_0001.json](https://drive.google.com/file/d/0B6A9_3MuVDTwTlEzMWl4eTFKaEU/view?usp=sharing)
- Full docker image: 
   These images were created with `docker save <name> | bzip2`. You can thus use `cat <name> | bunzip2 | docker load` to restore them.
   - [arangodb_f0000](https://drive.google.com/file/d/0B6A9_3MuVDTwQi1udGE1ZkFadVE/view?usp=sharing)
   - [arangodb_f0001](https://drive.google.com/file/d/0B6A9_3MuVDTwdEV4UHJISk40YXc/view?usp=sharing)

**Comment by dothebart** [comment] 2018-09-21 08:04
Hi, 
You may be interested in the tinkerpop rework of @arcanefoam - you can find more details here: https://github.com/ArangoDB-Community/tinkerpop-arangodb-provider

Please note that ArangoDB 2.8 isn't maintained anymore; which is why I will close this ticket. If you find this behaviour still with more recent versions of ArangoDB, don't hesitate to re-open this ticket.

**Closed by dothebart** 2018-09-21 08:04 UTC
Labels: 1 Bug, 3 Docker, 4 MacOSX
