### ISSUE TITLE
Datafile for collection corrupt (no apparent reason), but can't delete collection

### ISSUE THREAD

**Issue by miguel-porto** [arangodb/arangodb#4173] opened 2017-12-27 21:40 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Single-Server

Storage-Engine:
- [x] mmfiles

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

Hello,
For some unknown reason, I got a datafile corrupt for one collection. This is the problem reported:
```
2017-12-27T21:26:36Z [1929] WARNING crc mismatch found in datafile '/var/lib/arangodb3/databases/database-1489771778867/collection-1489743768287-1811945200/journal-1489772003064.db' of size 33554432, at position 56
2017-12-27T21:26:36Z [1929] WARNING crc mismatch found inside marker of type 'document' and size 114. expected crc: 4102192310, actual crc: 4093630817
2017-12-27T21:26:36Z [1929] INFO last good marker found at: 0x0000000000000020
2017-12-27T21:26:36Z [1929] INFO raw marker data following:
2017-12-27T21:26:36Z [1929] INFO type: document, size: 114, crc: 4093630817
2017-12-27T21:26:36Z [1929] INFO (expected layout: size (4 bytes), crc (4 bytes), type and tick (8 bytes), payload following)
2017-12-27T21:26:36Z [1929] INFO 0x0000000000000038: 72 00 00 00 61 D9 FF F3  F8 BE 54 DD 5A 01 00 1E   r...a... ..T.Z...
2017-12-27T21:26:36Z [1929] INFO 0x0000000000000048: F4 BE 54 DD 5A 01 00 00  0B 5A 05 31 4C 33 34 34   ..T.Z... .Z.1L344
2017-12-27T21:26:36Z [1929] INFO 0x0000000000000058: 37 38 39 31 36 39 30 35  34 33 F3 DF EA A5 DB 5A   78916905 43.....Z
2017-12-27T21:26:36Z [1929] INFO 0x0000000000000068: 01 00 00 34 53 74 61 78  65 6E 74 2F 33 33 37 39   ...4Stax ent/3379
2017-12-27T21:26:36Z [1929] INFO 0x0000000000000078: 39 34 33 39 36 35 37 34  32 30 31 37 2D 31 32 2D   94396574 2017-12-
2017-12-27T21:26:36Z [1929] INFO 0x0000000000000088: 31 37 54 30 36 3A 32 35  3A 30 31 5A 20 5B 36 34   17T06:25 :01Z [64
2017-12-27T21:26:36Z [1929] INFO 0x0000000000000098: 38 39 5D 20 49 4E 46 4F  20 68 61 6E 67 75 70 20   89] INFO  hangup 
2017-12-27T21:26:36Z [1929] INFO 0x00000000000000A8: 72 65 63 65 69 76 65 64  2C 20 61 62 6F 75 74 20   received , about 
2017-12-27T21:26:36Z [1929] INFO 0x00000000000000B8: 74 6F 20 72 65 6F 70 65                            to reope 
2017-12-27T21:26:36Z [1929] WARNING data directly following this marker cannot be analyzed
2017-12-27T21:26:36Z [1929] ERROR datafile '/var/lib/arangodb3/databases/database-1489771778867/collection-1489743768287-1811945200/journal-1489772003064.db' is corrupt
2017-12-27T21:26:36Z [1929] ERROR unable to close datafile '/var/lib/arangodb3/databases/database-1489771778867/collection-1489743768287-1811945200/journal-1489772003064.db': -1
2017-12-27T21:26:36Z [1929] ERROR {datafiles} cannot open datafile '/var/lib/arangodb3/databases/database-1489771778867/collection-1489743768287-1811945200/journal-1489772003064.db': corrupted datafile
2017-12-27T21:26:36Z [1929] ERROR caught exception while opening collection 'HAS_QUALITY': cannot open document collection from path '/var/lib/arangodb3/databases/database-1489771778867/collection-1489743768287-1811945200': corrupted datafile
```
Luckily, this was not a problem for me because I only had dummy data there, however, I'd like to restart the server normally, but I can't delete the corrupt collection through arangosh: `db._collection('HAS_QUALITY').drop()` throws an error.
Is there any other way I can I delete the corrupt collection? I need the data from the other collections, so I need to restart the server and have db access. (EDIT: of course I have db access with the option to ignore errors, I meant that I need to get the website online again normally!)

Let me know if I can help in further investigating the problem, in case it's a bug.
Cheers,
Miguel

**Comment by miguel-porto** [comment] 2017-12-27 22:31
Ok, I manually moved the corrupt datafile away and also one of the logfiles (which was corrupt also), and managed to restart the db normally.
Anyway, let me know if you want to inspect the problem further. Is it possible to have any idea of what caused this problem? It's scary because I have important data in other collections (which is backed-up, but anyway...)
Best,
Miguel

**Comment by ObiWahn** [comment] 2017-12-28 08:17
We assume this is a duplicate of https://github.com/arangodb/arangodb/issues/3632 which will be fixed in the upcoming release.

**Comment by ObiWahn** [comment] 2017-12-28 08:19
Please report to the other bug or reopen this bug in case you have reason to believe the bugs are not the same.

**Closed by ObiWahn** 2017-12-28 08:19 UTC
Labels: 1 Duplicate

**Comment by miguel-porto** [comment] 2017-12-28 11:03
Hmm... maybe the same, though I don't remember having problems on upgrading. The files were already corrupt before I tried to upgrade to 3.2.10.
But let's see how it goes now.

**Comment by ObiWahn** [comment] 2017-12-28 11:34
Hi Miguel,

it becomes visible whenever ArangoDB is restarted. For people who have dedicated servers this happens mostly during upgrades.

Cheers

**Comment by miguel-porto** [comment] 2017-12-28 12:14
Yep, it's probably the same! Thanks,
Best,
Miguel
