### ISSUE TITLE
3.0.3 fails to compile

### ISSUE THREAD

**Issue by dmitri--** [arangodb/arangodb#1961] opened 2016-07-23 02:12 UTC
steps to reproduce:
1) pick a Linux host 
2) pick a non-privileged user account that has no rights to write into the root directory
3) run:
$ mkdir -p build
$ cd build
$ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/username/install/ArangoDB && \
make all install

expected:
it should compile and install into specified directory

actually:
it failed to install in attempt to create /init.d directory in the root

cause:
cmake script uses ETCDIR which I didn't find among GNUInstallDirs. Latter has SYSCONFDIR. Did you by mistake type ETCDIR instead of SYSCONFDIR?

workaround:
add -DETCDIR=/home/username/install/ArangoDB/etc 
into commandline arguments for cmake

**Comment by servusoft** [comment] 2016-07-23 19:26
ArangoDB tries to install itself as a service and requires root rights.
You can create a package with <b>make package</b> or <b>cpack -G STGZ</b> (performed in build folder) and then install in any location with write access.
I mean the title is wrong; "Fails to install" would be better.

**Comment by dmitri--** [comment] 2016-07-23 21:04
servusoft please re-read the report once again.
It has nothing to do with root. It has nothing to do with installation.
It's merely cmake script related problem.

**Comment by servusoft** [comment] 2016-07-24 08:07
Ok, the fault on 3.0.3 confirmed:

'# get 
git clone -b 3.0 git://github.com/arangodb/arangodb.git

'# config
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/user/install/ArangoDB

'# compile use 4 core
make -j4

'#install 
make install >inst.log 2>err.log

'# err.log:
```
CMake Error at cmake_install.cmake:64 (file):
  file cannot create directory: /init.d.  Maybe need administrative
  privileges.

make: *** [install] Error 1
```
However on 3.0.x (devel branch) is no error was apparently fixed.

**Comment by dothebart** [comment] 2016-07-25 11:33
@dmitri-- I think we already fixed that in devel, we removed parts doing those special directory calculations of the directories
Can you retry with devel to confirm?

**Comment by dmitri--** [comment] 2016-07-28 02:24
tried the clone and yeah it  worked, no problems with make install trying to create directory in root.

The only two things concern me:

1) is it possible to avoid rewriting rpath for the compiled binaries while running  "make install"? This /lib64 dir for stdlibc++ and libgcc render the binaries useless.

2) check these 3 lines in the daemon config:
[cluster]
...
arangod-path = @SBINDIR@/arangod@PROGRAM_SUFFIX@
dbserver-config = @SYSCONFDIR@/arangod.conf
coordinator-config = @SYSCONFDIR@/arangod.conf

What are @SBDIR@, @SYSCONFIGDIR@ and @PROGRAM_SUFFIX@?

**Comment by fceller** [comment] 2016-07-28 08:44
@dmitri-- do the cmake options help with (1) https://cmake.org/Wiki/CMake_RPATH_handling ?

**Comment by dothebart** [comment] 2016-08-17 07:49
regarding these config lines, they were leftovers from 2.8;  If you have a look at etc/arangodb3/arangod.conf.in - there are more of them which are still used and thus replaced during the install process.

In windows some of these markers are replaced during arangodb starttime, since you can't tell the install directory during configure / compile time.

**Comment by dothebart** [comment] 2016-09-27 15:29
does this still persist with current devel? Else may we close this?
Meanwhile we have: 
https://github.com/arangodb-helper/build-docker-containers
which we use for our internal CI;  It could be used to aid compiling.

**Comment by dothebart** [comment] 2016-11-09 16:11
Major work was done on the cmake build system; so please open a new bug if something similar still persists. Closing.

**Closed by dothebart** 2016-11-09 16:11 UTC
Labels: 2_Question, build
