### ISSUE TITLE
Graph can't access existing Edge collections --> Could not create edge: collection or view not found: E1 

### ISSUE THREAD

**Issue by qohelet** [arangodb/arangodb#16399] opened 2022-06-13 12:10 UTC
## My Environment

* __ArangoDB Version__:        3.9.0
* __Deployment Mode__:       Docker
* __Deployment Strategy__:   ArangoDB Starter in Docker
* __Configuration__:               Default
* __Infrastructure__:               Intranet
* __Operating System__:        Fedora 32
* __Total RAM in your machine__:        7961Mb
* __Disks in use__:         SSD
* __Used Package__:             Docker - official Docker library

## Component, Query & Data

__Affected feature__:
Graph

__AQL query (if applicable)__:
```
FOR e IN E1
    RETURN e

```
__AQL explain and/or profile (if applicable)__:
```
Query String (25 chars, cacheable: true):
 FOR e IN E1
     Return e
 

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode     24     - FOR e IN E1   /* full collection scan  */
  3   ReturnNode                  24       - RETURN e

Indexes used:
 none

Optimization rules applied:
 none

Optimization rules with highest execution times:
 RuleName                                    Duration [s]
 use-indexes                                      0.00001
 reduce-extraction-to-projection                  0.00000
 splice-subqueries                                0.00000
 interchange-adjacent-enumerations                0.00000
 replace-function-with-index                      0.00000

40 rule(s) executed, 1 plan(s) created
```

__Dataset__:
Attached. 

## Steps to reproduce
I write my thesis about Versioning in ArangoDB. In this test I create 2 Vertex and 2 Edge Collection in a Python Script. These are then renamed with the usage of:
`import arango
vertex_collection.rename(newname)`. Then the Edges have to be reset to the new collection. I do that with AQL:

```
    def getRenameEdgesAQL(vertex_col_name,edge_col_name,old_db,feld):
        database.aql.execute(f"FOR e IN {edge_col_name} UPDATE e with {{ {feld}: REGEX_REPLACE(TO_STRING(e._from), '{old_db}', '{vertex_col_name}') }} IN {edge_col_name}")
```
Afterwards another two 2 Vertex and 2 Edge collections are created and this cycle repeats (one for each iteration of the versioning)

1. Go to the Online Interface --> Graphs
2. Set up a new Graph. From-Collections=To-Collections= V1; Edge-Definitions: E1
3. Graph appears, but shows Nodes only

__Problem__:
Edges are not existing. Regardless what I do. I started drawing them manually, but only get the error:
`Could not create edge: collection or view not found: E1 `
Executing the given AQL shows that the Edges are existing. 

__Expected result__:
Edges show, possible to draw Edges

[results-verstionTestDB.txt](https://github.com/arangodb/arangodb/files/8890583/results-verstionTestDB.txt)
![Selection_043](https://user-images.githubusercontent.com/13061154/173345584-7f67ebd0-2df8-440a-ad59-4105fd9d0dcf.png)

**Comment by maany** [comment] 2022-06-21 23:29
+1, I have the same issue with the web interface

**Comment by qohelet** [comment] 2022-06-22 11:41
@maany - how did you encounter the issue? Same as me?

**Comment by maxkernbach** [comment] 2022-07-19 11:30
Hi @maany and @qohelet,

Thanks to both of you for reporting the issue. This is a bug, which affects 3.9 and is easily reproducible using the graph viewer with any graph (e.g. with one of the "Example" graphs).

To be more precise, there is a formatting issue within the API request. However, you should still be able to insert and delete edges outside the graph viewer: Either by adding/deleting an edge in the edge collection or through the [gharial API](https://www.arangodb.com/docs/stable/http/gharial-edges.html).

**Comment by qohelet** [comment] 2022-09-06 09:12
@maxkernbach - thank you for the reply. Will there ever be a bugfix for that?
The Web-Based Graph feature is a pretty cool tool. Would be great if there's a solution

**Comment by bearpawmx** [comment] 2022-09-29 02:27
I can confirm this bug is also in the Docker image for version Arango 3.9.3

**Comment by qohelet** [comment] 2022-10-03 09:26
@ bearpawmx I talked to some colleagues. Seems the bug is appearing in general and not just in my limited UC

**Comment by maxkernbach** [comment] 2022-10-17 11:24
Hi @maany, @qohelet and @bearpawmx,

A fix for this UI issue will be part of the upcoming releases 3.9.4 and 3.10.1.

[Changelog entry](https://github.com/arangodb/arangodb/blob/85600a2d233685af7d82b0c5d276bc7c90092623/CHANGELOG#L12):

> * BTS-908: Fixed WebUI GraphViewer not being able to create a new edge relation
>   between two nodes in cases where only one edge definition has been defined
>   inside the graph definition.

**Comment by maxkernbach** [comment] 2022-10-31 11:02
Hi @maany, @qohelet and @bearpawmx,

I would like to inform you that version 3.9.4, including the aforementioned fix, has been released. Please comment in case the issue is still reproducible.

**Closed by maxkernbach** 2022-10-31 11:02 UTC
Labels: 1 Bug, 3 UI, 3 Graph Visualization, 2 Fixed

**Comment by psytron** [comment] 2022-11-18 01:24
Still experiencing this issue in 3.10.0.

**Comment by psytron** [comment] 2022-11-18 01:51
Reproduce:
Take any example graph and try to make an edge between any nodes:
<img width="743" alt="adberr" src="https://user-images.githubusercontent.com/7834453/202598300-96f58359-90b8-425b-aa96-2912946b6aa5.png">

**Comment by Simran-B** [comment] 2022-11-18 13:06
As @maxkernbach wrote, it's only fixed in 3.9.4 and 3.10.1, as well as in later versions. It is not fixed in 3.10.0.

**Comment by psytron** [comment] 2022-11-18 20:39
Ok thanks! I didn't notice a way to install 3.10.1 with homebrew on osx. The homebrew recipes are still on 3.10.0 ( https://formulae.brew.sh/formula/arangodb )

**Comment by Simran-B** [comment] 2022-11-18 22:24
It takes some time after a release before a new version becomes available via homebrew. You may use the DMG or tar packages instead: https://www.arangodb.com/download-major/macosx/

**Comment by psytron** [comment] 2022-11-18 23:32
> It takes some time after a release before a new version becomes available via homebrew. You may use the DMG or tar packages instead: https://www.arangodb.com/download-major/macosx/

Thank you @Simran-B  I tried the DMG packages but they don't work on my machines. It launches a terminal window and opens a browser window with connection reset error and error 400 on port 8529 when visiting with another browser.

**Comment by dothebart** [comment] 2022-11-20 12:53
it seems that there is some unholy time conflict with the homebrew PRs:
- ours: https://github.com/Homebrew/homebrew-core/pull/115397
- theirs: https://github.com/Homebrew/homebrew-core/pull/115383
maybe @iMichka can have a word on this and how to best proceed?
