### ISSUE TITLE
Can't dump/restore with user and password 

### ISSUE THREAD

**Issue by petitchevalroux** [arangodb/arangodb#1521] opened 2015-10-06 13:41 UTC
Using arangodb 2.6.8, i am unable to dump/restore db + collection using user and password

Here are the commands i use.  The sample dump can be downloaded as zip here http://dl.free.fr/n5nhqFNM2

arangodump --server.endpoint tcp://192.168.99.100:8529 --output-directory "dump" --server.username user --server.password password --server.database database --include-system-collections false --dump-data false --overwrite true

arangorestore --server.endpoint tcp://192.168.99.100:8529 --server.username user --server.password password --server.database database --create-database true --input-directory "dump"
Could not connect to endpoint tcp://192.168.99.100:8529
Error message: 'got error from server: HTTP 401 (Unauthorized)'

**Comment by jsteemann** [comment] 2015-10-06 14:14
As far as I can see the dump is taken from server `192.168.99.100:8529` with username `user` and password `password` from database `database`. I understood that this worked ok, because the error message above is printed after the *arangorestore* and not after the *arangodump* command invocation.

The restore however is done on the same server and same database and same user, but with a different password (`qmcHwhHNPjfnOM1y`). I don't think this is expected to work, as this user had a different password (`password`) when dumping, and I don't see the password being changed in between.

So either the example above is incorrect, or, if it is correct and two different passwords are used for dump and restore, then the failure is intentional. Or am I missing something?

**Comment by petitchevalroux** [comment] 2015-10-06 14:42
Sorry example incorrect fixed

**Comment by petitchevalroux** [comment] 2015-10-06 14:52
More infos : after restore cmd database is created (I can see it using the web interface), but i can't login using interface or nodejs.

So I can't say if collection exists

**Comment by jsteemann** [comment] 2015-10-06 20:41
Ok, I was able to reproduce. The database needs to be dropped in between, and then re-creation failed. I have pushed a fix for the 2.6, 2.7 and devel branches. The fixes will be contained in the next releases (i.e. 2.6.10 and first 2.7.0 stable).

**Comment by petitchevalroux** [comment] 2015-10-07 10:07
Sorry I forgot to mention the fact that database must be drop between the two commands.

Thank you for the fix ;)

**Closed** 2015-10-07 15:37 UTC
Labels: Bug
