### ISSUE TITLE
Arango becomes unresponsive and needs restarts after a while 

### ISSUE THREAD

**Issue by awasta** [arangodb/arangodb#4230] opened 2018-01-05 08:20 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1 - Using 3.1 
- [ ] 3.2
- [ ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server  - Single Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb 
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[x] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:  running on this OS:
- [ ] arangosh
- [x] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS: Ubuntu
- [x] authentication is enabled? Yes
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://bud.gc.magicpin.in:8529
2) log in as buddy/Buddy_2017
3) use database [ ] `_friendfinder` 
4) click to ...
...

The following problem occurs: [Screenshot?] - After running fine for several hours, arango just becomes jombie and stops responding on 8529 port. We are forced to restart the process which also takes very long to come back. Disk operation pattern on the server shows that there are spikes in read operation post which this problem occurs. 

This is causing us down time on some of our critical features. 

Instead I would be expecting: It should run smoothly all the time. 

![screenshot from 2018-01-05 13-40-37](https://user-images.githubusercontent.com/4686536/34600855-8e10da5e-f21f-11e7-81d2-eeb8b5721d93.png)

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by jsteemann** [comment] 2018-01-25 22:03
These read spikes seem to happen in somewhat regular intervals.
Is it possible to find out the time of day (hour/minute) on which the read spikes occur, in order to look for scheduled operations that run on the server at around that time?
I am not saying that this is the cause, but I have seen other servers running regular cron jobs that indexed the filesystem (e.g. updatedb), updated OS packages, or that did other things and causing very heavy disk I/O. The extra disk I/O caused by the jobs of course very negatively influenced the server's regular performance. Can you check if that could also be the case here?
If it's not the case, is there any application code that is known to be read/write-intensive and running at about the same times when the I/O spikes occur?

**Comment by OmarAyo** [comment] 2018-03-13 16:04
Hi @awasta 

Could you please send us an update on this ticket?

**Comment by maxkernbach** [comment] 2018-04-10 12:06
Hi @awasta,

im am closing this issue for now as we have not received any feedback for a few months.
Please feel free to reopen this issue and comment in case your problem persists.

**Closed by maxkernbach** 2018-04-10 12:06 UTC
Labels: Waiting User Reply
