### ISSUE TITLE
graph._commonNeighbors function not working

### ISSUE THREAD

**Issue by tttlh** [arangodb/arangodb#1995] opened 2016-08-10 09:48 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: 
- [ ] MacOS, version:

### related stuff:
[x] I'm using graph features via arangosh

[From the manual](https://docs.arangodb.com/3.0/Manual/Graphs/GeneralGraphs/Functions.html#commonneighbors)
"This function returns the intersection of graph_module._neighbors(vertex1Example, optionsVertex1) and graph_module._neighbors(vertex2Example, optionsVertex2)"

So I'm trying to get common neighbors between Hamburg and Berlin and I also want to restrict the edge collection to "internationalHighway" . I 've run command to show Hamburg's neighbors

>routeplanner._neighbors('germanCity/Hamburg', {edgeCollectionRestriction: "internationalHighway"})
[ 
  "frenchCity/Lyon", 
  "frenchCity/Paris" 
]

then Berlin
>routeplanner._neighbors('germanCity/Berlin', {edgeCollectionRestriction: "internationalHighway"})
[ 
  "frenchCity/Paris", 
  "frenchCity/Lyon" 
]

and finally
>routeplanner._commonNeighbors('germanCity/Hamburg', "germanCity/Berlin", {edgeCollectionRestriction: "internationalHighway"}, {edgeCollectionRestriction: "internationalHighway"});
[ 
  { 
    "left" : "germanCity/Hamburg", 
    "right" : "germanCity/Berlin", 
    "neighbors" : [ 
      **"germanCity/Cologne",** 
      "frenchCity/Lyon", 
      "frenchCity/Paris" 
    ] 
  } 
]

So why Cologne is in the results????

**Comment by Simran-B** [comment] 2016-08-10 12:58
This could be a bug, we will investigate. I would only expect Cologne in the result with maxDepth > 1, which would include 2nd degree neighbors. But the default is minDepth = maxDepth = 1.

In general, we recommend to use native AQL traversal:

```js
LET neighborsHamburg = (
  FOR v IN ANY 'germanCity/Hamburg' internationalHighway
    RETURN v._id
)
LET neighborsBerlin = (
  FOR v IN ANY 'germanCity/Berlin' internationalHighway
    RETURN v._id
)
RETURN INTERSECTION( neighborsHamburg, neighborsBerlin )
```

This returns the expected result

```json
[
  [
    "frenchCity/Lyon",
    "frenchCity/Paris"
  ]
]
```

By using a min depth of 1 and a max depth of 2, Cologne is returned as well:

```js
LET neighborsHamburg = (
  FOR v IN 1..2 ANY 'germanCity/Hamburg' internationalHighway
    RETURN v._id
)
LET neighborsBerlin = (
  FOR v IN 1..2 ANY 'germanCity/Berlin' internationalHighway
    RETURN v._id
)
RETURN INTERSECTION( neighborsHamburg, neighborsBerlin )
```

```json
[
  [
    "frenchCity/Lyon",
    "germanCity/Cologne",
    "frenchCity/Paris"
  ]
]
```

**Comment by mchacki** [comment] 2016-08-19 13:37
I managed to trace it down. The issue is, that the edge collection restriction is not forwarded correctly. I am now working on a fix. Which will be included in the next devel version.

**Closed** 2016-08-19 13:40 UTC
Labels: 1_Bug, graph

**Comment by dothebart** [comment] 2016-08-19 14:07
the patch wasn't in time for 3.0.5; if you want it to be fixed now for you, please download the referenced source file, and replace it in your installation; restart ArangoDB to make it take effect.
