### ISSUE TITLE
documents do not get indexed

### ISSUE THREAD

**Issue by smurfio** [arangodb/arangodb#5643] opened 2018-06-21 08:22 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [ ] Linux 
  - [x] docker - official docker library on kubernetes engine on gcp

### this is an AQL-related issue:
probably

I'm issuing AQL via:
- [x] this Driver: foxx

The following problem occurs:
Some documents seem not to get indexed within an edge-collection and are not "available/existent" on later queries, regardless which attributes are the filter criteria (except _key and _id, also not working on filtering on _from and _to).

When I do an INSERT query however these documents get found because some uniqueness constraints get violated.

indexes are:
_from,_to -> hash, unique, deduplicate
_from,index,array1,array2 -> hash, unique, deduplicate (index is the main identifier related to _from attribute, array1 and array2 are additional identiefiers that are not available for every document)

**Comment by Simran-B** [comment] 2018-06-21 11:35
We require more information to help you. Please provide some sample data and an execution plan of a problematic query.

How do you tell that documents are missing in the index, or is it about secondary indexes not being utilized?

**Comment by smurfio** [comment] 2018-06-21 18:09
Query that doesn’t return a document:

```
FOR doc IN edgeCollection FILTER doc._from=="collection1/5770774798" && doc.index=="market|2|mv|0|0|period|bp|tp|4"
RETURN doc
```

If I only filter on doc._from this document is also not listed.

doc.index can differ completely or only in the last number/character. Is the hash built on the whole string as I expect it to be or does it cut at a specific point?
(I’ve experienced another database having such behaviour.)


Query that returns an error:

```
UPSERT {"_from":"collection1/5770774798","_to":"collection2/5846705964","index":"market|2|mv|0|0|period|bp|tp|4"}
INSERT {"_from":"collection1/5770774798","_to":"collection2/5846705964","index":"market|2|mv|0|0|period|bp|tp|4"}
UPDATE {}
IN edgeCollection
RETURN {"new":NEW, "old":OLD}
```

> Query: AQL: unique constraint violated - in index 5728045941 of type rocksdb-hash over ["_from","index“,"array1“,"array2"]; conflicting key: 5784741613 (while executing)

querying for that key exactly returns the document that already exists and should have been found.

**Comment by Simran-B** [comment] 2018-06-21 18:28
The error message says something about `conflicting key: 5784741613`, but what document is that? It is neither of the ones referred in _from and _to. Also, the error is about a key conflict, but you don't have any key specified, only _from, _to and index.

Please post your index definitions and the query execution plans.

**Comment by smurfio** [comment] 2018-06-22 06:09
index definitions:
_from,_to -> hash, unique, deduplicate
_from,index,array1,array2 -> hash, unique, deduplicate (index is the main identifier related to _from attribute, array1 and array2 are additional identiefiers that are not available for every document)

> Query: AQL: unique constraint violated - in index 5728045941 of type rocksdb-hash over ["_from","index“,"array1“,"array2"]; conflicting key: 5784741613 (while executing)

As I understand this says that index ["_from","index“,"array1“,"array2"] got violated because a document with _key:5784741613 exists already. And if I query for a document with that _key it returns exactly a document fulfilling my the initial query


```
FOR doc IN edgeCollection FILTER doc._from=="collection1/5770774798" && doc.index=="market|2|mv|0|0|period|bp|tp|4"
RETURN doc
```


Query execution plans:

```
Query string:
FOR doc IN edgeCollection FILTER doc._from=="collection1/5770774798" && 
doc.index=="totalgoals|2|mv|0|0|period|bp|tp|4"
RETURN doc

Execution plan:
Id   NodeType          Est.   Comment
 1   SingletonNode        1   * ROOT
 6   IndexNode          225     - FOR doc IN edgeCollection   /* edge index scan */
 7   CalculationNode    225       - LET #1 = (doc.`index` == "market|2|mv|0|0|period|bp|tp|4")   /* simple expression */   /* collections used: doc : edgeCollection */
 4   FilterNode         225       - FILTER #1
 5   ReturnNode         225       - RETURN doc

Indexes used:
 By   Type   Collection     Unique   Sparse   Selectivity   Fields        Ranges
 6   edge   edgeCollection   false    false         0.44 %   [ `_from` ]   (doc.`_from` == "collection1/5770774798")
 
Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
```


```
Query string:
 UPSERT {"_from":"collection1/5770774798","_to":"collection2/5846705964","index":"market|2|mv|0|0|period|bp|tp|4"}
 INSERT {"_from":"collection1/5770774798","_to":"collection2/5846705964","index":"market|2|mv|0|0|period|bp|tp|4"}
 UPDATE {}
 IN edgeCollection
 RETURN {"new":NEW, "old":OLD}

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  8   SubqueryNode         1     - LET #3 = ...   /* const subquery */
  2   SingletonNode        1       * ROOT
 15   IndexNode            1         - FOR #1 IN edgeCollection   /* hash index scan */
 16   CalculationNode      1           - LET #6 = (#1.`index` == "market|2|mv|0|0|period|bp|tp|4")   /* simple expression */
  5   FilterNode           1           - FILTER #6
  6   LimitNode            1           - LIMIT 0, 1
  7   ReturnNode           1           - RETURN #1
  9   CalculationNode      1     - LET $OLD = #3[0]   /* simple expression */
 11   CalculationNode      1     - LET #10 = { }   /* json expression */   /* const assignment */
 10   CalculationNode      1     - LET #8 = { "_from" : "collection1/5770774798", "_to" : "collection2/5846705964", "index" : "market|2|mv|0|0|period|bp|tp|4" }   /* json expression */   /* const assignment */
 12   UpsertNode           1     - UPSERT $OLD INSERT #8 UPDATE #10 IN edgeCollection
 13   CalculationNode      1     - LET #12 = { "new" : $NEW, "old" : $OLD }   /* simple expression */
 14   ReturnNode           1     - RETURN #12
 
Indexes used:
 By   Type   Collection     Unique   Sparse   Selectivity   Fields               Ranges
 15   hash   edgeCollection   true     false       100.00 %   [ `_from`, `_to` ]   ((#1.`_from` == "collection1/5770774798") && (#1.`_to` == "collection2/5846705964"))
 
Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-calculations-up-2
  3   remove-data-modification-out-variables
  4   use-indexes
  5   remove-filter-covered-by-index
  6   move-calculations-down
 
Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          false
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        false
 useIsRestore             false
 consultAqlWriteFilter    false
```

**Comment by Simran-B** [comment] 2018-06-22 09:44
You can retrieve the index definitions in Arangosh like `db.edgeCollection.getIndexes()`, which will include all the information. I assume however, that your index `["_from","index“,"array1“,"array2"]` is unique and **non-sparse**.

If `array1` and `array2` are not present in the document, then their value will be `null`. The unique constraint applies to `null` too. You can't have two documents with the same _from and index values, without array1 and array2, because that would make it non-unique.

So, with a unique, non-sparse hash index `["_from","index“,"array1“,"array2"]` on an edge collection, the first `INSERT { _from: "collection1/test", index: 1 } INTO edgeCollection` will succeed, but a subsequent execution of the query will fail. This is expected. You may want to use a sparse unique index instead.

**Comment by smurfio** [comment] 2018-06-22 19:24
yes, the index ["_from","index“,"array1","array2"] is unique and non-sparse.
some documents have to have a value in array1 and/or array2. And these, of course, are different to a document having the same attribute "index" without any or different values in array1 or array2.
Since array1 and array2 are treated as null if not existent the whole document doesn't get indexed if I create a sparse unique index. This is the reason why it is not sparse.

This works for some documents (I'm talking about a couple of million) but not for all. For some reason, these documents are not even accessible by their _from attribute.

Not sure why I added the deduplicate option to the [_from,_to] index. Of course, this makes no sense.

**Comment by Simran-B** [comment] 2018-06-24 00:35
Did you try to count the number of documents with and without index? The result should be the same. If it's not, then it sounds like a bug, because queries should not change only because an index exists or not.

**Comment by smurfio** [comment] 2018-06-25 08:28
If I have a glimpse on the number of datasets within this collection - using the dashboard - this shows me:
2,373,812

Using this query:
```
FOR doc IN edgeCollection
COLLECT WITH COUNT INTO nr
RETURN nr
```
returns 2,373,786

Not sure how to query for all documents even if they are existent but not indexed at all. In my case, every document has the attribute with the name index and some documents are even not in the default edge collection index [_from,_to].

**Comment by vinaypyati** [comment] 2018-06-29 10:45
Hi @smurfio,

This issue is important for us and would like to help you resolve this bug. We would like to further analyze and have the issue reproduced on our side too. If it is possible can you please share us the data files/datasets that you are using? 

Presuming the data files are large in size, we request you to please send us an email to `hackers@arangodb.com` referencing the GitHub this issue(5643). The motive behind this is to let you upload your files to our cloud. We will share the access information/necessary credentials over the email. 

This will be very helpful for us to debug the problem and provide you with a possible solution as soon as possible. Thank you for your understanding.

Best,

**Comment by Simran-B** [comment] 2018-12-05 12:13
Hi @smurfio,

can you upgrade to the latest stable 3.3 release (v3.3.19 at the time of writing) and see if you can still reproduce the problem? If so, please share the dataset with us as vinaypyati wrote above. Thanks!

**Comment by smurfio** [comment] 2018-12-20 14:05
Hi Simran,
I'm currently on 3.4 and the behaviour is exactly the same. So the data I've already sent should still work.

**Comment by dothebart** [comment] 2020-09-02 08:38
with the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) I'm closing this as outdated.

**Closed by dothebart** 2020-09-02 08:38 UTC
Labels: 1 Bug, 2 Cannot Reproduce, 3 Index, 3 RocksDB
