### ISSUE TITLE
The result data of filter operation on edge document with  _from or _to field  ALWAYS miss some data on version 3.6.2

### ISSUE THREAD

**Issue by liuxiong888** [arangodb/arangodb#11303] opened 2020-03-19 08:04 UTC
We uses the lates version 3.6.2 ,BUT :

The result data of filter operation on edge document with  _from or _to field  ALWAYS miss some data.

How can I do with it?

Urgent for help.

## My Environment 

* __ArangoDB Version__3.6.2 :        
* __Storage Engine__:             
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:

__Expected result__:

**Comment by liuxiong888** [comment] 2020-03-19 15:31
We find a very serious error after we update to 3.6.2
We can't get correct result in a general  AQL operation of For  with a _from  or _to filter.

Very very urgent.

**Comment by liuxiong888** [comment] 2020-04-11 08:54
**for rs in my_gpro_relationships
filter rs._from == "my_gpro_persons/1484934153" and rs._to == "my_gpro_persons/1502302371"
return rs**

can't find data
[] 

for rs in my_gpro_relationships
filter rs._from == "my_gpro_persons/1484934153"
return rs

can find data
  {
    "_key": "1502302373",
    "_id": "my_gpro_relationships/1502302373",
    "_from": "my_gpro_persons/1484934153",
    "_to": "my_gpro_persons/1502302371",
    "_rev": "_aNcKq9e--A",
    "type": 2,
    "treeKey": "1458936908",
    "treeType": 1
  }

**Comment by jsteemann** [comment] 2020-04-14 07:04
@liuxiong888 : are there any additional indexes present on the `my_gpro_relationships` collections? Can you provide the output of `db.my_gpro_relationships.indexes()`?
Does the problem persist after unloading the collection, via `db.my_gpro_relationships.unload()`?
(note these commands can be executed in arangosh)
Thanks.

**Comment by liuxiong888** [comment] 2020-04-15 08:21
_key	primary
_from, _to	edge
type	idx_3
treeKey	idx_4
treeType	idx_1057908931

unload():some data(original is bad) is ok; but other(original is ok) is bad

**Comment by liuxiong888** [comment] 2020-04-16 00:47
@jsteemann   We still has the challage upper,I wish get more help from U urgently.

**Comment by jsteemann** [comment] 2020-04-16 07:28
Without any further context it is hard to tell what is causing this. I don't even know what kind of deployment is used, as the issue template for new issues has not been filled in.

What would be most helpful is a debug package for the query that goes wrong. You can create one using ArangoDB's web UI (in the query editor) and attach it here.
That will also show if this is a cluster or a single server deployment.

Apart from that, are the edges in collection "my_gpro_relationships" subject to change very often or are they read-mostly? How many edges can be expected for each value of _from and for each value of _to, on average? 
Additionally, does the problem happen all the time or only sometimes, after a while?
You also mentioned you upgraded to 3.6.2. Does it mean that 3.6.2 is the first version you encountered the problem with? From which ArangoDB version did you upgrade?
All this may help debugging this.
Thanks!

**Comment by liuxiong888** [comment] 2020-04-16 12:34
Dear  @jsteemann 
My Environment.   __ArangoDB Version__3.6.2 :
Storage Engine:  RockDB
Deployment Mode:  Stand alone
Deployment Strategy: just use linux command
Configuration:
Infrastructure: 
Operating System: CentOS 7
Total RAM in your machine: 16G
Disks in use: 10G
Used Package: /
Component, Query & Data
Affected feature:Error fetch result,lost many data.

AQL query (if applicable):for rs in my_gpro_relationships
filter rs._from == "my_gpro_persons/1484934153" and rs._to == "my_gpro_persons/1502302371"
return rs

AQL explain (if applicable):Get some edges

Dataset: my_gpro_relationships

Size of your Dataset on disk:10GB

Replication Factor & Number of Shards (Cluster only):/

Steps to reproduce
Problem:Lost result dataset

Expected result:all data with the _to or _from

 a debug package: you can copy and download
http://cdn-icare.qingtime.cn/upload/naodong/2020-04/2eafad30-7fd8-11ea-93d5-33b240ee055d.zip



Apart from that, are the edges in collection "my_gpro_relationships" subject to change very often or are they read-mostly? 
A:Only for Read mostly.

How many edges can be expected for each value of _from and for each value of _to, on average?
A:less then 10 edges

Additionally, does the problem happen all the time or only sometimes, after a while?
A: Always hanppes now.

You also mentioned you upgraded to 3.6.2. Does it mean that 3.6.2 is the first version you encountered the problem with?
A:After we migrate to 3.6.2 it happes.

 From which ArangoDB version did you upgrade?
A:3.6.1

We has use the way you suggent last time ,Some data once can't find now can see.BUT more data can fetch now.

I wish his can help you.

**Comment by liuxiong888** [comment] 2020-04-16 12:35
[debugDump.zip](https://github.com/arangodb/arangodb/files/4487029/debugDump.zip)

**Comment by liuxiong888** [comment] 2020-04-17 01:08
we have to dump and restore the document of my_gpro_relationships , the data once can't find can find now ,but some else can't find now. The same way as we use the unload.

We have about 200 volunteers work on this project but THAY HAVE TO STOP WORK NOW, so please help us.

We can give you a teamview ID so you can access our server to find more clue.

Thanks. @jsteemann @OmarAyo @a2800276 @pekeler

**Comment by jsteemann** [comment] 2020-04-19 19:27
@liuxiong888 : I tried reproducing the issue locally several times in the past few days, but didn't manage to.
So I guess there is either some difference in the setup or in the workload.

To rule out a few potential problems causes, can you run the following code in the arangosh in the database that shows the problem?
Please note that in the last line of the code the actual from and to values need to be put in for a combination of `_from` and `_to` values that exhibits the problem:

```js
function check(from, to) {
  let stats = db._engineStats();
  print(Object.keys(stats).filter(function(k) { return k.match(/^cache/) }).map(function(k) { return { [k]: stats[k] }; }));
  print();

  print(require("@arangodb/aql/cache").properties());
  print();

  const q1 = `FOR rs IN my_gpro_relationships FILTER rs._from == @from AND rs._to == @to RETURN rs`; 
  const q2 = `FOR rs IN my_gpro_relationships FILTER rs._from == @from RETURN rs`; 
  const q3 = `FOR rs IN my_gpro_relationships FILTER rs._to == @to RETURN rs`;
 
  let process = function(q, b = null, o = null) {
    print("Result for " + JSON.stringify({ q, b, o }));
    db._explain(q, b, o);
    let result = db._query(q, b, 0);
    let docs = result.toArray();
    print({ count: docs.length, docs: docs, stats: result.getExtra() });
    print();
    print();
  };

  process(q1, { from, to });
  process(q1, { from, to }, { optimizer: { rules: ["-move-filters-into-enumerate"] } });
  process(q1, { from, to }, { optimizer: { rules: ["-all"] } });
  process(q2, { from });
  process(q3, { to });  
}

/* the following line needs to contain the actual _from and _to values */
check("my_gpro_persons/3", "my_gpro_persons/1");
```

Running that code should produce some output that could shed some more light on this. 
The output should help us find out if a specific query optimizer rule is to blame for the mismatching results.
Can you share that output here so we can have a look at it?

Additionally, is it possibly to produce a dump of the "my_gpro_relationships" edge collection so we can import it locally and try reproducing the issue? I expect the "my_gpro_relationships" collection to contain only non-sensitive data, but that is just a guess.

**Comment by liuxiong888** [comment] 2020-04-20 04:13
[_to_error.txt](https://github.com/arangodb/arangodb/files/4501168/_to_error.txt)
http://youpu219.qingtime.cn/gedcomxDownload/20200417.zip
300MB

**Comment by liuxiong888** [comment] 2020-04-20 04:14
@jsteemann @OmarAyo @pekeler Wish It's useful for your debug.

**Comment by jsteemann** [comment] 2020-04-20 05:37
@liuxiong888 : thanks for the data!
I have looked at the script output and it helps ruling out a few things.
* the AQL query results cache is not used and thus cannot be blamed.
* we can't blame the AQL query optimizer rule `move-filters-into-enumerate`. The problem also happens when the rule is turned off.
* the edge index on `_to` does not return the edge when asked individually. The edge index on `_from` does return the document. So it is an error in the edge index or in the layers below it (edge cache, RocksDB storage engine).
Now importing the data to find out more.

**Comment by jsteemann** [comment] 2020-04-20 06:39
@liuxiong888 : I can't download the file http://youpu219.qingtime.cn/gedcomxDownload/20200417.zip
I tried several times, but the download rate is between some 100 B/s and a few KB/s. Currently the ETA for the download is 15 days. Apart from that, in all of my download attempts the remote server hung up after a few minutes.
Is it possible to upload the file somewhere else?

**Comment by liuxiong888** [comment] 2020-04-20 07:21
Thanks for your help.
I am sending the dump 

file by  skyp to Wolfgang Fresser now.He can get in in 10 minutes.
<img width="673" alt="skype" src="https://user-images.githubusercontent.com/12511611/79724679-814e4480-831a-11ea-804a-00dd03283ca5.png">

Would you mind give me your skype so I can also send a copy directly to you?

@jsteemann

**Comment by jsteemann** [comment] 2020-04-20 07:31
@liuxiong888 : Sorry, I am not using Skype. Uploading it to any website where it can be downloaded using simple HTTP/HTTPS is fine, as long as it has reasonable bandwidth.
https://www.file.io/ or such should be fine.

**Comment by liuxiong888** [comment] 2020-04-20 12:17
https://drive.google.com/file/d/1CVBFNANiOnhGg_rKnNnR28P6GES1ebnu/view?usp=sharing
@jsteemann

**Comment by liuxiong888** [comment] 2020-04-21 12:39
dear @jsteemann ,have you down load the data? Any progress was wanted.

**Comment by jsteemann** [comment] 2020-04-21 13:59
@liuxiong888 : yes, I have downloaded and imported the data yesterday and tried to reproduce it for several hours. But the problem did **not** occur locally. Others have also tried to reproduce, but again it did not occur.

We have two candidates for left for the problem cause, and for both it is likely that the problem occurs only under very specific circumstances, or server state, respectively:

* the in-memory edge cache: edges are first served from an in-memory cache, and are looked up from the storage engine only if they are not in the cache. If there is an issue with this cache, it is at least not trivial will only show up under yet unknown circumstances. Because the cache is in-memory only, all we could do here is to build a special version that turns off the cache, just to check if the problem goes away then. If not, then we can rule out the cache as the problem source.
* the RocksDB storage engine: we may have hit an edge case in RocksDB in which it does not return all the data even though it should. If that is the case, it seems to happen only when the database is in some certain state. As the problem did not occur whenever we tried to reproduce it locally, the only way for us to make progress here is to check if we can reproduce it with the original database directory (i.e. a copy of the files in the database directory).

So what we can do to make progress is the following:
1) provide a special 3.6.2 version to you that allows turning of the in-memory edge cache. This is just an experimental switch that will allow detecting if the edge cache is the problem source or not. When the edge cache is turned off (using that switch) but the problem persists, the edge cache is not the problem source.
2) try reproducing the problem with an exact copy of the entire database, on the filesystem level. This would mean taking a filesystem copy of the original database and providing it to us for the purpose of problem reproduction. I am not sure if it is possible for you legally to provide a copy of the database for problem reproduction, but if it can be done, then this would help.

What do you think, can we move on with one of these options (or both)?

**Comment by liuxiong888** [comment] 2020-04-22 05:55
Both way are welcome. Please give me a email address and I will send you the url.

There is an important message is: when we migrate from 3.6.1 to 3.6.2 , we copy the database directly to new system instead of dump the old database and restore to new system. Is this the reason?

@jsteemann

**Comment by jsteemann** [comment] 2020-04-22 08:21
I don't think that copying the database directory from 3.4 into a 3.6 has caused the issue. The data file format should have remained the same.

Does the problem also happen on your backup server? If so, I could use a filesystem copy of the backup database for debugging. Remote accessing the backup server will likely not help much, as I will need to make some modifications to the ArangoDB source code, compile them, try them out etc. All this I can better do locally, with the build environment already set up. So if you are sure it happens on the backup server too, that is probably the easiest option. My e-mail address is jan@arangodb.com.

**Comment by liuxiong888** [comment] 2020-04-25 09:22
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hello JanIs there any progress on the bug? Thanks for you work.Best wishes.
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                liux
                            
                    
                        
                            
                                    liux@qingtime.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 04/22/2020 16:22，Jan<notifications@github.com> wrote： 



I don't think that copying the database directory from 3.4 into a 3.6 has caused the issue. The data file format should have remained the same.
Does the problem also happen on your backup server? If so, I could use a filesystem copy of the backup database for debugging. Remote accessing the backup server will likely not help much, as I will need to make some modifications to the ArangoDB source code, compile them, try them out etc. All this I can better do locally, with the build environment already set up. So if you are sure it happens on the backup server too, that is probably the easiest option. My e-mail address is jan@arangodb.com.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jsteemann** [comment] 2020-05-05 10:38
@liuxiong888 : there is a bugfix PR pending for the issue: https://github.com/arangodb/arangodb/pull/11537
Despite the name of the PR, the problem has nothing to do with the edge cache. I just started a PR to add a toggle for the edge cache when I was finally able to reproduce the issue. So that means the toggle and the bugfix are now handled in the same PR.

**Comment by vanobig** [comment] 2020-05-05 16:26
@jsteemann do you have any thoughts about which versions of ArangoDB are affected by this issue? We are on 3.6.1 and it seems to be having a similar issue.

**Comment by jsteemann** [comment] 2020-05-05 19:45
@vanobig : it affects both 3.5.x and 3.6.x. Technically it also affected the unreleased devel version, but there haven't been releases for that except nightly builds.

There are bugfix PRs pending for the stable releases:
* 3.5: https://github.com/arangodb/arangodb/pull/11536
* 3.6: https://github.com/arangodb/arangodb/pull/11537

The bugfix PRs haven't been merged yet, but I am confident we will merge them soon into the respective branches. That means the fixes will be included in the next 3.5 and 3.6 bugfixes releases.

**Comment by jsteemann** [comment] 2020-05-05 19:46
Regarding release dates: this is hard to predict for me, as I am not in charge of release dates. I can only push for having bug fix releases for the affected versions soon.

**Comment by vanobig** [comment] 2020-05-05 19:47
Thank you @jsteemann. Appreciate such a quick response 🙇

**Comment by jsteemann** [comment] 2020-05-07 07:14
@liuxiong888 @vanobig : for info, there is a version 3.6.3-1 online on our website, containing the fix for this issue.

**Comment by fceller** [comment] 2020-05-07 07:54
@liuxiong888 @vanobig please confirm that 3.6.3-1 fixes the issue for you. Thx.

**Comment by fceller** [comment] 2020-05-07 07:56
Confirmation received, thanks for your help.

**Closed by fceller** 2020-05-07 07:56 UTC
Labels: 1 Bug, 2 Fixed, 3 AQL, 3 Index

**Comment by liuxiong888** [comment] 2020-05-07 09:28
Thanks all

**Comment by liuxiong888** [comment] 2020-05-08 01:49
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Dear Jan,you can use the test DB I send to u last time:My EnvironmentArangoDB Version: 3.6.3.1-1Storage Engine: RocksDBDeployment Mode: Single ServerDeployment Strategy: Manual StartConfiguration:Infrastructure: ownOperating System: centos7Total RAM in your machine: 8GBDisks in use: 15G/50GUsed Package: noneComponent, Query & Data QUERYAffected feature:A filter y.name="*" is VERY SLOW,buta filter y.name="鸿庆" or any string else is normalAQL query (if applicable):let tmp = (for r in my_gpro_gResourcefilter r.gcId =="1596176426" and r.resourceType == 2 and r.status == 1 return r._key)let xx =(for p in my_gpro_personsfilter p.treeKey in tmp and (p.dynastic == 1)return p)for y in xxfilter y.name == "*"return yAQL explain (if applicable): search dcoument name == "*"Dataset:Size of your Dataset on disk:Replication Factor & Number of Shards (Cluster only):Steps to reproduceset y.name="*" time cost 6s~80sset y.name="X" ,time cost 20ms3 we save the result with out filter to a static document , then the cost of y.name="*" is also change to [20ms.]Problem:WHY？Expected result:Should the same
            
        
    
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                liux
                            
                    
                        
                            
                                    liux@qingtime.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 05/7/2020 15:15，Jan<notifications@github.com> wrote： 



@liuxiong888 @vanobig : for info, there is a version 3.6.3-1 online on our website, containing the fix for this issue.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dothebart** [comment] 2020-05-11 09:08
Hi @liuxiong888 , 
if I read your mail correctly, this is not related to this issue? 
So I think we can leave this as fixed and please open a new ticket with this information.

**Comment by liuxiong888** [comment] 2020-05-11 09:10
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Yes .This bug has be fixed.
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                liux
                            
                    
                        
                            
                                    liux@qingtime.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 05/11/2020 17:08，Wilfried Goesgens<notifications@github.com> wrote： 



Hi @liuxiong888 ,
if I read your mail correctly, this is not related to this issue?
So I think we can leave this as fixed and please open a new ticket with this information.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
