### ISSUE TITLE
New Graph: Edge definitions with edges in fromCollections na toCollections

### ISSUE THREAD

**Issue by edersonbrilhante** [arangodb/arangodb#3031] opened 2017-08-14 22:17 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [x] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[x] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [x] this Driver: python-arango==3.8.0

When I try to create a graph, in second "edge definition", the web interface shows me edges in "fromCollections" and "toCollections". That permit me to save a edge definition only with edges.

![screen shot 2017-08-14 at 7 10 16 pm](https://user-images.githubusercontent.com/1094995/29294146-47589244-8124-11e7-86f1-ed542697a980.png)

**Comment by hkernbach** [comment] 2017-08-28 11:44
Unfortunately, I'm not able to reproduce that issue. Could you provide a bit more information on how to reproduce? (_the web interface shows me edges in "fromCollections" and "toCollections"_). 

Are they automatically inserted? And then unremovable?

**Comment by sleto-it** [comment] 2017-10-11 20:33
Hi @edersonbrilhante,

Thank you for the bug report. Verified as described with version 3.2.3

@hkernbach : the problem is that in the UI the fields "fromCollections" and "toCollections" should filter only the "document" collections - and not visualize there the edge collections. However, this does not happen with the **second** edge definition. To reproduce, add a second "edge definition". Then click on "fromCollections": among the suggested collections you will see edge collections (should not be there)

Thanks,

**Comment by hkernbach** [comment] 2017-12-04 12:40
Fixed in 3.2 and devel branch. PRs:
https://github.com/arangodb/arangodb/pull/3882 & https://github.com/arangodb/arangodb/pull/3881

**Comment by sleto-it** [comment] 2017-12-23 15:21
Hi,

Thanks again for opening this ticket. Version 3.2.10 has been released yesterday

I am now closing this ticket. Please feel free to comment if the problem persists

Many thanks,

**Closed by sleto-it** 2017-12-23 15:21 UTC
Labels: 1 Bug, 2 Fixed, 3 UI
