### ISSUE TITLE
Feature request:  graphml import

### ISSUE THREAD

**Issue by MikeB2019x** [arangodb/arangodb#14752] opened 2021-09-09 13:17 UTC
## Feature request

There are many graph storage formats.  One that offers a lot of portability is GRAPHML.  I'm a heavy user of networkx and export to graphml is the most straightforward way of porting my graphs into other apps/db's such as neo4j, orientdb, and gephi.  Has such a feature been considered?

**Comment by dothebart** [comment] 2021-09-09 14:44
no, I don't think this has been done yet anywhere. Can you provide a sample dataset?

**Comment by MikeB2019x** [comment] 2021-09-09 15:48
Attached is a graphml file to which I added .txt extension so it could drop in here.  It's for a small directed graph with the following nodes, edges, and attributes:

```
(NodeDataView({0: {'label': '0', 'random': 6}, 1: {'label': '1', 'random': 7}, 2: {'label': '2', 'random': 0}, 3: {'label': '3', 'random': 7}, 4: {'label': '4', 'random': 4}}),
 OutEdgeDataView([(0, 2, {'weight': 7}), (0, 3, {'weight': 2}), (0, 4, {'weight': 2}), (1, 0, {'weight': 3}), (1, 3, {'weight': 4}), (1, 4, {'weight': 1}), (2, 0, {'weight': 3}), (2, 3, {'weight': 6}), (3, 1, {'weight': 7}), (3, 4, {'weight': 8}), (4, 0, {'weight': 8}), (4, 1, {'weight': 5}), (4, 2, {'weight': 9}), (4, 3, {'weight': 2})]))
```

[small_test_graph.graphml.txt](https://github.com/arangodb/arangodb/files/7137927/small_test_graph.graphml.txt)

**Comment by Simran-B** [comment] 2021-09-15 12:50
Closing as a duplicate of #14573

**Closed by Simran-B** 2021-09-15 12:50 UTC
Labels: 1 Feature, 3 Graph, 3 ImportExport

**Comment by MikeB2019x** [comment] 2021-09-15 13:00
Apologies for the duplication.  I was just reminded in reading this that I had posted as an issue in networkx-adapter here:  https://github.com/arangoml/networkx-adapter/issues/19.  I will include a graphml sample there.
