### ISSUE TITLE
ArangoDB Http Endpoint returns "Address not available"

### ISSUE THREAD

**Issue by alexyzhou** [arangodb/arangodb#8469] opened 2019-03-20 10:50 UTC
## My Environment

* __ArangoDB Version__:        3.4.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               8 Core, 32GB Nodes * 6
* __Infrastructure__:               AWS
* __Operating System__:        AWS AMI Latest
* __Total RAM in your machine__:        32GB
* __Disks in use__:        SSD
* __Used Package__:              SUSE or RedHat .rpm

## Component, Query & Data

__Affected feature__:
ArangoDB Foxx

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:
A financial datasets with 71,187,289 nodes and 7,212,539 edge(s)

__Size of your Dataset on disk__:
20G on SSD * 6 nodes

__Replication Factor & Number of Shards (Cluster only)__:
Replication Factor: 2
Number of Shards: 12

__Problem__:
I have a foxx program using @arangodb/request to make HTTP call to arangodb to retrieve the data at high performance. 
It turns out that when I execute the foxx query at a high concurrency (20 threads and ~100 loops), the HTTP endpoint:
http://localhost:8529/_db/miograph/_api/edges/

will returns error:
{"statusCode":500,"status":500,"message":"Could not connect to 'http+tcp://127.0.0.1:8529' 'connect() failed with #99 - Address not available'","headers":{}}

After I rest for a while, it is working again.

I wander if there is any rate limit control on arangodb http endpoint? Since my program requires lots of http call, is there any configuration that I can raise the limit?

Thanks!

**Comment by alexyzhou** [comment] 2019-03-20 10:53
The query I am using is:
const request = require("@arangodb/request");
    var response = request.post({url: "http://localhost:8529/_db/miograph/_api/edges/mio_company_company?direction=in", body: [vertexId], json: true});

**Comment by dothebart** [comment] 2019-03-20 10:56
please have a look at netstat in that case; you may have run out of sockets; you probably will have many close_wait s. Tuning the systems TCP stack may fix this.
In general its not advised to synchroneously send http requests from foxx services for high volume queries, rather use foxx-queues for this. 
You will also have the problem that you can't use persistent http connections from Foxx, which could be the cause for this.

**Comment by alexyzhou** [comment] 2019-03-21 01:55
I used netstat and I could see a lot of close_wait s. So I think it is the problem of running out of sockets in foxx side.

So can you suggest any workaround for this? I don't want to tune systems TCP stack since it won't permanently solve this problem.

**Comment by alexyzhou** [comment] 2019-03-21 09:08
I end up abandoning foxx and use Java HTTP to write the program. But I still think it will be best if we can skip firing http request in foxx to arangodb (and waste the socket to localhost) and can use direct API call for arangodb HTTP endpoint.

**Comment by dothebart** [comment] 2019-03-21 09:09
Sorry if I repeat myself, 
the solution would be to have [persistent HTTP Connections](https://en.wikipedia.org/wiki/HTTP_persistent_connection) which is not supported by foxx. Its simply not made what you're trying to use it for. You're trying to push a square peg into a round hole.

**Comment by alexyzhou** [comment] 2019-03-22 03:41
I think the real problem is Foxx's inEdges query is made slower than the HTTP endpoint thus I have to use HTTP call to boost the performance. It will be great if you could:
1) improve the performance of inEdges query in foxx (as described in https://github.com/arangodb/arangodb/issues/8437) to have the identical performance like HTTP endpoint.
2) make foxx has a scalable approach to call HTTP endpoint if 1) can not meet.

Thanks!

**Comment by dothebart** [comment] 2020-09-02 11:06
With ArangoDB 3.4 being EOL and [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) being available for download closing this as out of date.

**Closed by dothebart** 2020-09-02 11:06 UTC
Labels: 1 Analyzing, 3 Foxx, performance
