### ISSUE TITLE
Unexpected "rocksdb unique constraint violated" with unique hash index

### ISSUE THREAD

**Issue by ukebako** [arangodb/arangodb#3581] opened 2017-11-04 12:15 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

ArangoDB 3.2.6 [linux] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.0.0, OpenSSL 1.0.2g 1 Mar 2016

**The problem**
I have a collection containing 160k documents.
Collection has field "id" which is indexed with hash unique index.
I read documents from another DB, search by example document that has same "id" field and update existing document or create new in the loop. 
Sometimes (but not always) I catch the exception: **_unique constraint violated - in index 22055009145420 of type rocksdb-hash over ["id"]_**
When I try to filter collection with this id I get empty result.

**Expected behavior**
If document exists with particular id value, search by example should return it. Or, if document doesn't exists, then create operation has to be successful without exception.

**Comment by jsteemann** [comment] 2017-11-04 13:41
Can you provide the code that does the search-update-insert?

Not having seen it, it may be prone to data races in the following case:
Given two parallel clients (C1 and C2) that execute the operations in parallel
They may execute the operations in the following order:
- C1 searches by example for a document with id A, doesn't find it
- C2 searches by example for a document with id A, doesn't find it
- C1 now inserts document with id A, succeeds
- C2 now inserts document with id A, fails with unique constraint violation

This is because search-then-update-or-insert is not an atomic operation. It may be interleaved with other operations on the same documents/index values.

But as I do not know the exact client code and use case, the above is pure speculation for now.

**Comment by ukebako** [comment] 2017-11-04 14:15
Thanks for answer. 
I'm aware of such cases so I use message queue to be sure that only one client thread at a time can do the operation. I also have to notice that this issue starts to appear after upgrade from 2.8 to 3.2+rockdb.
This is my code:
```php
$myDoc = $this->getDocumentData(); // init doc data ready to save to Arango
$cursor = $this->getCollectionHandler()->byExample($this->collection, ['id' => $myDoc['id']]);
$arangoDoc = ArangoDocument::createFromArray($myDoc);
if (!$cursor || !$cursor->getCount()) {
    $this->getDocumentHandler()->save($arangoDoc);
}
else {
    $oldDoc = $cursor->current()->getAll();
    $this->getDocumentHandler()->updateById($this->collection, $oldDoc['_key'], $arangoDoc);
}
```

**Comment by jsteemann** [comment] 2017-11-04 21:58
So you are 100% sure the PHP application code above runs single-threaded, and no other parallel operation will insert documents at the same time?
If so, is it possible for you to provide all the index definitions for the collection in question plus the "id" value of the document for which an insert fails? Thanks!

**Comment by ukebako** [comment] 2017-11-05 05:04
Yes, that's true. Only one thread updates Arango records.
I have only one custom index in this collection. It's hash unique index of "id" field.
Values of "id" are simple unsigned integers, like 152371

**Comment by jsteemann** [comment] 2017-11-06 21:00
I can confirm there is some (volume-dependent) problem with this. It will only occur once the RocksDB compaction has run, that's also the reason why it was not caught earlier.
A potential fix for the problem can be found here:
https://github.com/arangodb/arangodb/pull/3596
If it passes all tests, we will conduct some more performance tests and merge the fix if all goes well.

**Comment by jsteemann** [comment] 2017-11-07 15:58
A PR for 3.2 has also been opened: https://github.com/arangodb/arangodb/pull/3609

**Comment by sleto-it** [comment] 2017-11-15 19:35
Hi @ukebako,

Thanks again for opening this ticket. Version 3.2.7 has now been released and it includes a fix for this problem

Please could you upgrade? I am now closing this ticket. If the issue persists, please feel free to comment

Many thanks,

**Closed by sleto-it** 2017-11-15 19:35 UTC
Labels: 1 Bug, 2 Fixed, 3 Core, 3 RocksDB
