### ISSUE TITLE
Edge document w/o one vertex

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#1659] opened 2016-01-14 17:12 UTC
Hi

After NEIGHBORS function returned following error:

Query: document not found (while executing)

I found out that our database has edge without one _to vertex:

[
  {
    "dstIntL2Name": "Et2/0",
    "neiIp": "10.123.253.134",
    "_id": "eCdp/3594035143268",
    "_rev": "3594035143268",
    "_key": "3594035143268",
    "_from": "vIntL2/3593999950436",
    "_to": "vIntL2/3551233647204"
  }
]

_from vertex exists:

for i in vIntL2
  filter i._id == "vIntL2/3593999950436"
    return i

[
  {
    "name": "Et1/0",
    "_id": "vIntL2/3593999950436",
    "_rev": "3593999950436",
    "_key": "3593999950436"
  }
]

but _to vertex doesn't exists:

for i in vIntL2
  filter i._id == "vIntL2/3551233647204"
    return i

[]

Our app is quite complicated, so unfortunately I don't know how to replicate this.
Any ideas how this could happen or how to troubleshoot it?

-------------------

When I tried to replace NEIGHBORS function with GRAPH_NEIGHBORS, then query doesn't throw error and _to vertex is in result null.
But similar to this issue #1543 (slow GRAPH_EDGE, which is fixed now), GRAPH_NEIGHBORS is not fixed and is slow as hell (compared to NEIGHBORS).

Here is query:

for dev in vertex
  for srcIntL2 in NEIGHBORS(vDevice,eDevIntL2, dev, "outbound", [], {includeData: true})
    for dstIntL2 in NEIGHBORS(vIntL2,eCdp,srcIntL2, "any", [], {includeData: true})
    //for dstIntL2 in GRAPH_NEIGHBORS("network",srcIntL2, {direction : 'any', includeData: true, edgeCollectionRestriction: 'eCdp'})
      return {srcIntL2, dstIntL2}

I running 2.8beta2 on Debian 8.

**Comment by jsteemann** [comment] 2016-01-15 09:36
I can confirm `NEIGHBORS` could have thrown a `document not found` error in some cases. That should be fixed now (current 2.8 and devel).

That was caused by an edge pointing to a non-existing document. That an edge refers to a non-existing document may actually occur in practice. Edges are collections with special `_from` and `_to` attributes, which are mandatory to be filled in. When an edge is created, there will always be a check that the referenced *collections* do exist. However, there'll be no validation of whether the referenced *documents* exist. That means it is possible to create an edge that links non-existing documents from existing collections.
Additionally, when a (vertex) document gets deleted, any edges that reference it will not be affected. This may also cause edges pointing to non-existing documents. 

In order to have additional checks enabled when creating or removing documents, the operations need to be performed via the general-graph module or API. This module provides operations that can e.g. remove a vertex from a graph, and will perform the required cross-checks. It has some overhead of course, as checking references is not for free.

**Comment by CoDEmanX** [comment] 2016-01-15 10:17
Related (managed vs. unmanaged graphs):
http://stackoverflow.com/questions/26631854/aangodb-ghrarial-interface-vs-edges-documents#26632660

**Comment by dothebart** [comment] 2016-01-15 10:19
(we settled to call 'managed' named nowadays ;-)

**Comment by CoDEmanX** [comment] 2016-01-15 10:32
I see, it's *named* and *anonymous* graphs now. (Un)managed would emphasize the fact that edges in anonymous graphs may have loose ends though.

**Comment by roman1720** [comment] 2016-01-15 14:42
Ok, thanks all for explanation, makes sense.

What about speed of GRAPH_NEIGHBORS function? Did you check it?

**Comment by roman1720** [comment] 2016-01-15 15:19
Also I was checking arangojs doc and it seems that there is no possibility to delete in named (managed) style delete vertex?

**Comment by jsteemann** [comment] 2016-01-15 15:48
It seems that [arangojs](https://github.com/arangodb/arangojs) is indeed missing functionality for removing vertices and edges from a named (managed) graph.

There should be:
* `graphVertexCollection.remove()`: this should be mapped to HTTP DELETE /_api/gharial/:graph/vertex/:collection/:key
* `graphEdgeCollection.remove()`: this should mapped to HTTP DELETE /_api/gharial/:graph/edge/:collection/:key

**Comment by jsteemann** [comment] 2016-01-15 15:55
`GRAPH_NEIGHBORS` is known to be slower than `NEIGHBORS`, for the following reasons:
* `NEIGHBORS()` will use a single edge collection, which is known at query compile time, but `GRAPH_NEIGHBORS` may use an arbitrary number of collections, to be determined at runtime. That means it is more complex inside
* `NEIGHBORS()` has a C++ implementation, but `GRAPH_NEIGHBORS()` does not. It will use V8 internally, which means there is the need to convert data when passing it into V8 and back. This conversion may be notable for bigger inputs or output values, or when called often (as in the 3-levels loops shown above).

**Comment by roman1720** [comment] 2016-01-15 16:15
Ok, thanks. Where possible, I will use C++ functions.

I just was wondering, because in my example query above the difference is really big. For small collection, NEI() speed was instantaneous, G_NEI() took about 20s. For larger collections where query with NEI() runs for longer (30s), then G_NEI() is unusable, after few minutes I stopped query.

**Comment by pluma** [comment] 2016-01-15 17:06
@jsteemann they existed, but they're inherited from the (unmanaged) collection API, so they manipulate the collections directly rather than using the graph API.

That should be relatively trivial to fix. I've added an issue to arangojs.

**Comment by dothebart** [comment] 2016-01-26 17:30
Closing as progress on this is now tracked on the arangojs issue.

**Closed by dothebart** 2016-01-26 17:30 UTC
Labels: graph
