### ISSUE TITLE
Failed to load API definition, Unauthorized... (Foxx Swagger API)

### ISSUE THREAD

**Issue by Phillips126** [arangodb/arangodb#4464] opened 2018-01-29 21:17 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Single-Server

Storage-Engine:
- [x] mmfiles

On this operating system:
- [x] Windows, version: 10 Pro, Version 1709, Build 16299.125

### this is a web interface-related issue:
I'm using the web interface with this browser:  Chrome (Version 63.0.3239.132)    running on this OS: Windows  10 Pro (same as above)
- [x] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as anyone (used root in screenshots)
3) use database: Any (used _system in screenshots)
4) click "Services" on side menu and then "Add Service"
5) create "New Service", fill with any data, doesn't matter (used "test" for each field in screenshots)
6) click newly created service then click "API" in the top bar

The following problem occurs: 
Newer versions (3.3.3-1 and 3.3.2-3) I receive an error message displayed in the screenshots.  Version number of ArangoDB is Photoshopped in the bottom corner.

Each screenshot was taken with a fresh install of ArangoDB on Windows with the .EXE installer.  Previous versions of ArangoDB were uninstalled prior to installing the next version.

![3 3 3-1](https://user-images.githubusercontent.com/11968220/35534175-ab639d3e-050d-11e8-82c0-a520833634bd.jpg)

![3 3 2-3](https://user-images.githubusercontent.com/11968220/35534187-b3fad214-050d-11e8-85d7-84de562baa93.jpg)

Instead I would be expecting: 
ArangoDB version 3.3.2-2 appears to be working as shown in the below screenshot.

![3 3 2-2](https://user-images.githubusercontent.com/11968220/35534245-e8b21116-050d-11e8-835d-c92ed5d5fd95.jpg)

It is worth noting that on the newer versions that are not working by default (3.3.3-1 and 3.3.2-3), I am able to get them working by changing "authentication = false".

**Comment by maxkernbach** [comment] 2018-01-30 09:32
Hi,

thanks for reporting the bug. The same issue was already opened by another user yesterday though.
Closing this issue as a duplicate of [#4453](https://github.com/arangodb/arangodb/issues/4453).

**Closed by maxkernbach** 2018-01-30 09:32 UTC
Labels: 3 API, 3 Foxx, 3 Swagger, 3 UI

**Comment by milko** [comment] 2018-02-11 14:20
Hello,

same issue for me, tried creating simple service and tried downloading service: in both cases it was impossible to see the API, but the service interface was visible.
