### ISSUE TITLE
Using URL-encoded strings in document keys

### ISSUE THREAD

**Issue by joachimboggild** [arangodb/arangodb#1793] opened 2016-04-04 09:35 UTC
If I create a document with the key 'c-bl%C3%A5%2C' in a collection, i cannot retrieve it again. All the characters used are listed in the "allowed characters" in the https://docs.arangodb.com/NamingConventions/DocumentKeys.html help page. If I create this document in the web interface for my local database, I can create the document, and I can open the page to view/edit it, but I cannot update with any content - I get a "could not save" error.

My use case: I have a collection that I use for a cache. I get a web request containing some tags (where international characters are allowed). The first time I get a request, I do a search on some external web services and retrieve a list of results. These are saved as a document to a cache collection, and the next time I get the same request, I use the cache instead of going to the external services again. In this scenario, it makes sense to use the tags as the document key and the document contents as the results. An alternative solution would be to make a document property containing the search tags and index that property, but I figured this way was faster and needed less parsing of the document contents.

**Comment by dothebart** [comment] 2016-04-04 13:13
Check! The webinterface even decodes the URL-encoding which it definitely shouldn't do.

**Comment by hkernbach** [comment] 2016-04-07 10:57
Thanks, fixed in current devel branch.

**Closed by hkernbach** 2016-04-07 10:57 UTC
Labels: 1_Bug, front-end

**Comment by dothebart** [comment] 2016-04-07 13:12
This will also be part of ArangoDB 2.8.7 which will be available next week.

**Comment by bard** [comment] 2017-02-10 14:43
(Posting here instead of opening a new bug because this might have more to do with my being new to Arango.)

I have the same use case and similar problem as OP and there's something going on with URL-escaping that I can't figure out.

```
$ echo '{"_key": "http%3A%2F%2Fexample.com%2F", "body": "<html/>"}' | curl -X POST --data-binary @- --dump - http://localhost:8529/_db/mydb/_api/document/cached_pages
HTTP/1.1 202 Accepted
Location: /_db/mydb/_api/document/cached_pages/http%253A%252F%252Fexample%2Ecom%252F
Etag: "_UgfesYy---"
Server: ArangoDB
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Content-Length: 108

{"_id":"cached_pages/http%3A%2F%2Fexample.com%2F","_key":"http%3A%2F%2Fexample.com%2F","_rev":"_UgfesYy---"}
```

The key of the saved document is `http%3A%2F%2Fexample.com%2F` (as I expected) but the key in the URL to access the document (as shown in the Location header) is `http%253A%252F%252Fexample%2Ecom%252F`, that is, `%` is further escaped into `%25`.

Trying to access the document using the original key:

```
$ curl 'http://localhost:8529/_db/housescout/_api/document/cached_pages/http%3A%2F%2Fexample.com%2F'
{"error":true,"errorMessage":"document not found","code":404,"errorNum":1202}
```

But trying to retrieve the document using the extra-escaped key does work:

```
$ curl 'http://localhost:8529/_db/mydb/_api/document/cached_pages/http%253A%252F%252Fexample%2Ecom%252F'
{"_key":"http%3A%2F%2Fexample.com%2F","_id":"cached_pages/http%3A%2F%2Fexample.com%2F","_rev":"_UgfesYy---","body":"<html/>"}
```

Intended?

Version information:

```
$ curl http://localhost:8529/_db/mydb/_api/version
{"server":"arango","version":"3.1.10","license":"community"}
```

**Comment by mpv1989** [comment] 2017-02-13 10:54
This is the expected behavior. Independent of your document-key - in the stored document - whether it is URL encoded or not, you have to URL encode it in the request. If your document-key is already URL encoded you have to encode it a second time.

**Comment by bard** [comment] 2017-02-13 12:16
Hmm, I see. 

If the _key in the request must always be URL-encoded, then perhaps it should be enforced at the JavaScript driver level?

Because I'd expect I could use a document-key, as returned by a successful `save()` operation, to re-fetch the document, but that doesn't seem to be the case:

```
const arangojs = require('arangojs')
const db = new arangojs({ databaseName: 'mydb' })
const CACHE = db.collection('cached_pages')

const url = 'http://example.com/'

CACHE
    .save({ _key: encodeURIComponent(url), body: '<html/>' })
    .then(res => CACHE.document(res._key))
    .then(doc => console.log(doc))
    .catch(err => console.error(err.code))
```

That prints:

```
404
```

The following works:

```
const arangojs = require('arangojs')
const db = new arangojs({ databaseName: 'mydb' })
const CACHE = db.collection('cached_pages')

const url = 'http://example.com/'

CACHE
    .save({ _key: encodeURIComponent(url), body: '<html/>' })
    .then(res => CACHE.document(encodeURIComponent(res._key))) // <-- extra encoding
    .then(doc => console.log(doc))
    .catch(err => console.error(err.code))
```

It prints:

```
{ _key: 'http%3A%2F%2Fexample.com%2F',
  _id: 'cached_pages/http%3A%2F%2Fexample.com%2F',
  _rev: '_UhbfqTW---',
  body: '<html/>' }
```

But that `encodeURIComponent()` on the marked line smells a bit of a driver's job.
