### ISSUE TITLE
Is there an API to monitor data changement in ArangoJS, like LIVE QUERY in OrientJS/OrientDB?

### ISSUE THREAD

**Issue by angkor-wat** [arangodb/arangodb#7866] opened 2019-01-02 07:31 UTC
We are comparing between ArangoDB and OrientDB for a new project.

For our users, notification(of task and data modification) is important. So I like the LIVE QUERY of OrientDB. What is the solution in ArangoDB?

**Comment by dothebart** [comment] 2019-01-07 09:18
Closing as a duplicate of https://github.com/arangodb/arangodb/issues/602

**Closed** 2019-01-07 09:19 UTC
Labels: 1 Duplicate, 1 Question
