### ISSUE TITLE
CRITICAL! - Sudden +100% CPU Spikes with Arangodb

### ISSUE THREAD

**Issue by codewithpatelo** [arangodb/arangodb#13508] opened 2021-02-08 11:24 UTC
## My Environment

* __ArangoDB Version__:        3.7.3
* __Storage Engine__:             RocksDB rocksdb-version: 6.8.0
* __Deployment Mode__:       Single server
* __Infrastructure__:               AWS EC2 t2.medium
* __Operating System__:        Amazon Linux
* __Total RAM in your machine__:        4 GB

## Component, Query & Data

__Affected feature__:
Arangod / RocksDB

## Steps to reproduce

1. Run the program
2. 
3. 

__Problem__:
I've been deploying the same program for +5 months for now at the production environment and was everything alright until very recently. Today Arangodb suddenly started to spike in CPU at higher rates than %100. It seems like some bugged processes are underneath or something consuming unnecessary CPU.

This is critical for our program.

Here are some pictures:

![image](https://user-images.githubusercontent.com/16574952/107207743-6fd84500-69df-11eb-953d-0f5664bc15d2.png)

![image](https://user-images.githubusercontent.com/16574952/107211667-a6fd2500-69e4-11eb-9a60-b95ad717012f.png)

__Expected result__:
No CPU spikes at all.

**Comment by dothebart** [comment] 2021-02-08 12:18
Hi, 
please note that ArangoDB 3.7.6 is available and you should upgrade. 

There are background jobs that have to be executed now and then, like compacting the WAL files; these are system imanent and there is no way to stop it. 

If you want to reduce the resource footprint of ArangoDB you can disable the internal statistics feature. 
for details about resource usage please have a look at: 
https://www.arangodb.com/docs/stable/tutorials-reduce-memory-footprint.html

**Comment by codewithpatelo** [comment] 2021-02-08 18:43
So, a few minutes after this reply it re-stabilise to -5% CPU use. It was a weird peak with background threads.

Alright, I'll try upgrading. Is there a command to do so? (Without losing db data)

**Comment by dothebart** [comment] 2021-02-08 19:56
depends on your installation-mode? 
```
apt-get update; apt-get upgrade arangodb3
```
would be a wild guess from what you've posted.

**Comment by codewithpatelo** [comment] 2021-02-09 21:18
Amazon Linux has yum packages. I updated it. So far CPU use seems stable (but weirdly the issue was solved by waiting for those threads to end by themselves somehow).

**Comment by brunoaduarte** [comment] 2021-03-03 20:07
I have the same problem here

https://stackoverflow.com/questions/66463912/random-high-cpu-usage-in-arangodb-large-database

**Comment by brunoaduarte** [comment] 2021-03-09 15:26
This "wal compaction" thing of ArangoDB is making me spend the double of the budged i would need with a virtual machine. My average CPU load is 15%, but when the "wal compaction" starts it will go to 99% and freeze all my system. Is there a way to limit this "wal" thing cpu usage ?

**Comment by brunoaduarte** [comment] 2021-03-15 18:49
> I'd compare the wal compaction to dreaming: you need it in order to have your data structured.
> 
> However, like you can control when you go to sleep, you also know when you are idle and want to invoke it:
> 
> ```
> db.<any collection>.compact()
> ```
> 
> so you can do this at times when you're idle, and you can do it more often so (maybe) the amount of work it has to do is lower.

I setup a task to compact all DBs every 5 minutes, let's see if that fixes the problem.

```
tasks.register({
  id: "compaction-task",
  name: "Compaction task",
  period: 300,
  command: function () {
    require('console').log('--------------------------');
    require('console').log('Running compaction task...');

    require('console').log('Compacting access...');
    require('@arangodb').db.access.compact();

    require('console').log('Compacting users...');
    require('@arangodb').db.users.compact();

    require('console').log('Compacting logs...');
    require('@arangodb').db.logs.compact();

    require('console').log('--------------------------');
  }
});
```

**Comment by Simran-B** [comment] 2021-03-17 15:46
Starting the compaction every 5 minutes doesn't sound like a good idea. Have a look at the documentation here: 

https://www.arangodb.com/docs/devel/data-modeling-collections-collection-methods.html#compact

> the operation will compact the document and index data by rewriting the underlying .sst files and only keeping the relevant entries.

Rewriting the files that often seems undesirable.

**Comment by brunoaduarte** [comment] 2021-03-17 16:09
> Starting the compaction every 5 minutes doesn't sound like a good idea. Have a look at the documentation here:
> 
> https://www.arangodb.com/docs/devel/data-modeling-collections-collection-methods.html#compact
> 
> > the operation will compact the document and index data by rewriting the underlying .sst files and only keeping the relevant entries.
> 
> Rewriting the files that often seems undesirable.

Well, at least for now it seems to have fixed the issue. 2 days without freezing the server with 99.9% cpu usages.

In my case is much more undesirable having to pay for 48x vCPUs AWS when a 16x core will be enough for what i need.

Also i don't see any undesirability in it, the documentation only says it's not needed (in my case it seems to be since i have a lot of updates in the db).

What would you recommend then?

**Comment by brunoaduarte** [comment] 2021-03-23 04:33
???

**Comment by Simran-B** [comment] 2021-06-02 14:51
The upcoming version 3.8 might help to reduce the CPU spikes. From the CHANGELOG:

* When dropping a collection or an index with a larger amount of documents, the
  key range for the collection/index in RocksDB gets compacted. Previously, the
  compaction was running in foreground and thus would block the deletion
  operations.
  Now, the compaction is running in background, so that the deletion operations
  can return earlier. 
  The maximum number of compaction jobs that are executed in background can be
  configured using the new startup parameter
  `--rocksdb.max-parallel-compactions`, which defaults to 2.
* Increased the default value of `--rocksdb.min-write-buffer-number-to-merge` in
  some cases when we have allocated a sufficient amount of memory to the write
  buffers for this to make sense. The increased value should help prevent
  compaction-induced write stalls/stops, and should only be enabled when under
  conditions such that it shouldn't greatly increase the chance of flush-induced
  write stalls/stops.

**Comment by tomdavidson** [comment] 2021-07-20 15:03
Is [renicing](https://man7.org/linux/man-pages/man1/renice.1.html) the compaction jobs until 3.8 is released with the additional control? For example, in my crontab I have `*/5 * * * *     root    renice 5 $(pidof firefox)`

What are the conditions or rules that trigger the compaction jobs, perhaps @brunoaduarte can preempt them with less to compact or change some other condition? Add more storage to balance the number quantity of updates? Do smaller ETL batches with manually calling compact after each, etc? Ive throttled ingest with a queue architecture to avoid maxing disk io & the expensive up-size.  

Can RocksDB be [configured](https://github.com/facebook/rocksdb/wiki/RocksDB-Options-File) outside of ArangoDB so the compaction can be tuned prior to 3.8's release?

I'm not an operator or expert, this is just empathy triggered brain storming.

**Comment by codewithpatelo** [comment] 2023-02-06 14:45
Hi guys. I have to say that I'm still facing these problems. I'm using Arangodb with this set-up:

ArangoDB Version: 3.8.8
Storage Engine: RocksDB rocksdb-version: 6.8.0
Deployment Mode: Single server
Infrastructure: AWS EC2 t2.small
Operating System: Amazon Linux
Total RAM in your machine: 2 GB

I run a front-end and micro-services with a driver on the Arangodb database. The program scraps certain data from a website each minute and then processes it creating a registry in the database. This data can be accessed through the front-end application. As the runtime of the application increases it gets to a point where ArangoDB takes 100% of the CPU.

**Comment by codewithpatelo** [comment] 2023-02-06 20:46
![image](https://user-images.githubusercontent.com/16574952/217081262-c0607259-6ca0-4464-b5b9-6f8c09dc0205.png)
Details of CPU consumption.

**Closed** 2023-11-14 18:54 UTC
Labels: 3 RocksDB, 1 Analyzing, 3 Compaction

**Comment by robross0606** [comment] 2023-12-19 16:23
We are seeing similar issues on If this was closed as "completed" can someone document how it was resolved?

**Comment by RienNeVaPlus** [comment] 2024-03-26 02:53
Was anybody able to make some progress on this?

**Comment by dothebart** [comment] 2024-03-26 13:13
No. 3.8 has long been EOLed. 
Please upgrade to at least 3.11, and if you have a reliable way to reproduce this, open a new issue.
