### ISSUE TITLE
Arangod should respond with timeout if no workers become available in a grace period

### ISSUE THREAD

**Issue by samuelgoldenbaum** [arangodb/arangodb#1380] opened 2015-06-20 15:15 UTC
Testing performance of saving docs and having the following error thrown every few thousand writes:

```
{ [Error: connect EADDRNOTAVAIL]
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'connect',
  request: 
   { domain: null,
     _events: { response: [Object], error: [Function] },
     _maxListeners: 10,
     output: [],
     outputEncodings: [],
     writable: true,
     _last: false,
     chunkedEncoding: false,
     shouldKeepAlive: true,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _headerSent: true,
     _header: 'POST /_db/loadtest/_api/document/?collection=load HTTP/1.1\r\ncontent-type: application/json\r\ncontent-length: 169\r\nx-arango-version: 20300\r\nHost: localhost:8000\r\nConnection: keep-alive\r\n\r\n',
     _hasBody: true,
     _trailer: '',
     finished: true,
     _hangupClose: false,
     socket: 
      { _connecting: false,
        _handle: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        onend: [Function: socketOnEnd],
        destroyed: true,
        bytesRead: 0,
        _bytesDispatched: 0,
        _pendingData: 'POST /_db/loadtest/_api/document/?collection=load HTTP/1.1\r\ncontent-type: application/json\r\ncontent-length: 169\r\nx-arango-version: 20300\r\nHost: localhost:8000\r\nConnection: keep-alive\r\n\r\n{"id":16313,"type":9,"connections":[100,59,26,58],"positions":[{"time":"2015-06-20T10:49:32.749Z","type":9,"position":{"lat":-122.423246,"lng":37.779388,"radius":250}}]}',
        _pendingEncoding: 'utf8',
        parser: [Object],
        _httpMessage: [Circular],
        ondata: [Function: socketOnData],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     connection: 
      { _connecting: false,
        _handle: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        onend: [Function: socketOnEnd],
        destroyed: true,
        bytesRead: 0,
        _bytesDispatched: 0,
        _pendingData: 'POST /_db/loadtest/_api/document/?collection=load HTTP/1.1\r\ncontent-type: application/json\r\ncontent-length: 169\r\nx-arango-version: 20300\r\nHost: localhost:8000\r\nConnection: keep-alive\r\n\r\n{"id":16313,"type":9,"connections":[100,59,26,58],"positions":[{"time":"2015-06-20T10:49:32.749Z","type":9,"position":{"lat":-122.423246,"lng":37.779388,"radius":250}}]}',
        _pendingEncoding: 'utf8',
        parser: [Object],
        _httpMessage: [Circular],
        ondata: [Function: socketOnData],
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     agent: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        options: [Object],
        requests: {},
        sockets: [Object],
        maxSockets: 5,
        createConnection: [Function] },
     socketPath: undefined,
     method: 'POST',
     path: '/_db/loadtest/_api/document/?collection=load',
     _headers: 
      { 'content-type': 'application/json',
        'content-length': 169,
        'x-arango-version': 20300,
        host: 'localhost:8000' },
     _headerNames: 
      { 'content-type': 'content-type',
        'content-length': 'content-length',
        'x-arango-version': 'x-arango-version',
        host: 'Host' },
     parser: 
      { _headers: [],
        _url: '',
        onHeaders: [Function: parserOnHeaders],
        onHeadersComplete: [Function: parserOnHeadersComplete],
        onBody: [Function: parserOnBody],
        onMessageComplete: [Function: parserOnMessageComplete],
        socket: [Object],
        incoming: null,
        maxHeaderPairs: 2000,
        onIncoming: [Function: parserOnIncomingClient] } } }
```

I believe it has something to do with no more available sockets on my machine - but thought that  {maxSockets: 5} would control that? I have changed maxSockets from 1 to 25 and keep having the same result. I see keepalive is enabled by default so assume new connections are not being fired up?
Below is the script I am using to test with:

```
var moment = require('moment'),
    opts = {maxSockets: 5},
    Agent = require('http').Agent;

var db = require('arangojs')({
    url: 'http://localhost:8000',
    databaseName: 'loadtest',
    agent: new Agent(opts)
});

var recs = 1000000,
    currentDoc = 0,
    type,
    start = new Date(),
    collection;

function save() {
    type = Math.round(Math.random() * 10) + 1;
    collection
        .save({
            'id': currentDoc,
            'type': type,
            'connections': [
                Math.round(Math.random() * 100) + 1,
                Math.round(Math.random() * 100) + 1,
                Math.round(Math.random() * 100) + 1,
                Math.round(Math.random() * 100) + 1
            ],
            'positions': [
                {
                    'time': new Date(),
                    'type': type,
                    'position': {'lat': -122.423246, 'lng': 37.779388, 'radius': 250}
                }
            ]
        },
        function (err, result) {
            if (err || result.error) {
                return console.error(err);
            }
            console.log('inserted ' + currentDoc + ' of ' + recs);
            if (currentDoc === recs) {
                return console.log('inserted ' + currentDoc + ' in ' + moment.utc(moment(new Date(), "DD/MM/YYYY HH:mm:ss").diff(moment(start, "DD/MM/YYYY HH:mm:ss"))).format("HH:mm:ss"));
            }
            currentDoc++;
            save();
        });
}

db.collection('load', function (err, result) {
    if (err) {
        console.error(err);
        return;
    }
    collection = result;
    save();
});
```

_UPDATE:_
Only seems to happen when durability is set to soft and the waitForSync is set to false on the collection - I assume then this is an Arangodb issue and not a driver issue? or possibly both?

**Comment by pluma** [comment] 2015-06-21 13:05
This issue is also tracked in arangojs: https://github.com/arangodb/arangojs/issues/44

At this time I'm convinced the error is caused by the client, not the server.

**Comment by pluma** [comment] 2015-06-22 08:20
Okay, the EADDRNOTAVAIL is definitely on the client-side as it goes away when using keep-alive (and thus enforcing the maxSockets). But the root cause seems to be that enough of the requests are getting stuck that the client runs out of sockets when using node's default behaviour of opening new sockets when all sockets are busy.

In other words: some of the requests time out (hence the ETIMEDOUT that appears when using keep-alive -- see the arangojs issue) before receiving a response from the server.

@fceller Could you look into this? Is there any reason the server might (sometimes?) forget to send a response (and thus forget to end the HTTP request) when durability is set to soft and waitForSync is false?

**Comment by samuelgoldenbaum** [comment] 2015-06-22 12:21
Just to confirm: have been using v2.5.5, busy installing 2.6 and will test again

**Comment by fceller** [comment] 2015-10-12 09:27
@samuelgoldenbaum does this problem still exist in 2.7.0?

**Comment by dothebart** [comment] 2016-01-13 17:32
Whenever a request was received, and no worker becomes availailable in a configurable timout the request should be replied with a static answer noting that the server is busy and can't reply on time.

**Comment by CoDEmanX** [comment] 2016-01-13 18:31
Appropriate HTTP error codes:

**503 Service Unavailable**
The server is currently unavailable (because it is overloaded or down for maintenance). Generally, this is a temporary state.

**504 Gateway Timeout**
The server was acting as a gateway or proxy and did not receive a timely response from the upstream server.

**Comment by pluma** [comment] 2016-01-13 20:26
@CoDEmanX probably 503 is the most appropriate one. It's not really serving as a gateway when the API or Foxx times out (except maybe in some cluster setups but that's an implementation detail).

**Comment by dothebart** [comment] 2017-07-21 12:12
We're pleased to anounce that ArangoDB 3.2 containing lots of improvements. One of these is a better handling when server resources are unavailable, thus closing this ticket.

**Closed by dothebart** 2017-07-21 12:12 UTC
Labels: 1 Feature, 3 Core
