### ISSUE TITLE
Cluster: replication writes cause shards to become unresponsive

### ISSUE THREAD

**Issue by natbaker** [arangodb/arangodb#2960] opened 2017-08-04 17:37 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Cluster

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] other: Centos7 .rpm

Cluster is running on EC2 in AWS: 
2x coodinators + agency / m4.large
3x dbservers (1 running agency) / m4.2xlarge

During heavy writes on collections with replication factor >1, we start experiencing timeouts on the client.  

**Coordinator logs:**
>2017-08-04T16:02:12Z [12842] ERROR {cluster} ClusterComm::performRequests: got no answer from shard:s172393817:/_db/dimensionwarehouse/_api/document?collection=s172393817&waitForSync=false&returnNew=false&returnOld=false with error 4
2017-08-04T16:02:12Z [12842] ERROR {cluster} ClusterComm::performRequests: got no answer from shard:s172393856:/_db/dimensionwarehouse/_api/document?collection=s172393856&waitForSync=false&returnNew=false&returnOld=false with error 4
2017-08-04T16:02:12Z [12842] ERROR {cluster} ClusterComm::performRequests: got no answer from shard:s172393841:/_db/dimensionwarehouse/_api/document?collection=s172393841&waitForSync=false&returnNew=false&returnOld=false with error 4
2017-08-04T16:02:12Z [12842] ERROR {cluster} ClusterComm::performRequests: got no answer from shard:s172393844:/_db/dimensionwarehouse/_api/document?collection=s172393844&waitForSync=false&returnNew=false&returnOld=false with error 4

**DBServer0002 / PRMR-a059d653-b757-4f20-abef-28755ba9698d**

>2017-08-04T16:02:06Z [15135] ERROR {cluster} ClusterComm::performRequests: got no answer from server:PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9:/_db/dimensionwarehouse/_api/document/s194989909?isRestore=true&isSynchronousReplication=PRMR-a059d653-b757-4f20-abef-28755ba9698d with error 4
2017-08-04T16:02:06Z [15135] ERROR {cluster} ClusterComm::performRequests: got no answer from server:PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9:/_db/dimensionwarehouse/_api/document/s194989915?isRestore=true&isSynchronousReplication=PRMR-a059d653-b757-4f20-abef-28755ba9698d with error 4
2017-08-04T16:02:06Z [15135] ERROR {cluster} ClusterComm::performRequests: got no answer from server:PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9:/_db/dimensionwarehouse/_api/document/s194989906?isRestore=true&isSynchronousReplication=PRMR-a059d653-b757-4f20-abef-28755ba9698d with error 4
2017-08-04T16:02:06Z [15135] ERROR {cluster} ClusterComm::performRequests: got no answer from server:PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9:/_db/dimensionwarehouse/_api/document/s194989906?isRestore=true&isSynchronousReplication=PRMR-a059d653-b757-4f20-abef-28755ba9698d with error 4
2017-08-04T16:02:06Z [15135] WARNING {replication} insertLocal: dropping follower PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9 for shard s194989906
2017-08-04T16:02:06Z [15135] WARNING {replication} insertLocal: dropping follower PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9 for shard s194989906
2017-08-04T16:02:06Z [15135] WARNING {replication} insertLocal: dropping follower PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9 for shard s194989909
2017-08-04T16:02:06Z [15135] WARNING {replication} insertLocal: dropping follower PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9 for shard s194989915
2017-08-04T16:02:06Z [15135] ERROR {cluster} ClusterComm::performRequests: got no answer from server:PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9:/_db/dimensionwarehouse/_api/document/s194989915?isRestore=true&isSynchronousReplication=PRMR-a059d653-b757-4f20-abef-28755ba9698d with error 4
2017-08-04T16:02:06Z [15135] ERROR {cluster} ClusterComm::performRequests: got no answer from server:PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9:/_db/dimensionwarehouse/_api/document/s194989912?isRestore=true&isSynchronousReplication=PRMR-a059d653-b757-4f20-abef-28755ba9698d with error 4
2017-08-04T16:02:06Z [15135] WARNING {replication} insertLocal: dropping follower PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9 for shard s194989915
2017-08-04T16:02:06Z [15135] WARNING {replication} insertLocal: dropping follower PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9 for shard s194989912
2017-08-04T16:02:54Z [15135] ERROR {cluster} ClusterComm::performRequests: got no answer from server:PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9:/_db/dimensionwarehouse/_api/document/s194989906?isRestore=true&isSynchronousReplication=PRMR-a059d653-b757-4f20-abef-28755ba9698d with error 4
2017-08-04T16:02:54Z [15135] ERROR {cluster} ClusterComm::performRequests: got no answer from server:PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9:/_db/dimensionwarehouse/_api/document/s194989912?isRestore=true&isSynchronousReplication=PRMR-a059d653-b757-4f20-abef-28755ba9698d with error 4
2017-08-04T16:02:54Z [15135] WARNING {replication} insertLocal: dropping follower PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9 for shard s194989906
2017-08-04T16:02:54Z [15135] WARNING {replication} insertLocal: dropping follower PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9 for shard s194989912

**DBServer0001 / PRMR-b4f1508e-130a-4581-adb0-ad7406a243d9**
 
>221862:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/database/target-version'
221863:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/foxx/setup'
221864:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/foxx/teardown'
221865:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/foxx/install'
221866:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/foxx/uninstall'
221867:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/foxx/replace'
221868:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/foxx/upgrade'
221869:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/foxx/configure'
221870:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/foxx/configuration'
221871:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/foxx/set-dependencies'
221872:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/foxx/dependencies'
221873:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/foxx/development'
221874:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/foxx/tests'
221875:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/foxx/script'
221876:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/routing/reload'
221877:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/routing/routes'
221878:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/server/role'
221879:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/server/id'
221880:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/statistics/short'
221881:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/statistics/long'
221882:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/time'
221883:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/sleep'
221884:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_admin/echo'
221885:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_admin/long_echo'
221886:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/statistics'
221887:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/statistics-description'
221888:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/test'
221889:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/collection'
221890:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/aqlfunction'
221891:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/cluster/removeServer'
221892:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_admin/cluster-test'
221893:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/clusterNodeVersion'
221894:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/clusterNodeStats'
221895:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/clusterNodeEngine'
221896:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/clusterStatistics'
221897:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/cluster/health'
221898:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/history'
221899:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/cluster/getSecondary'
221900:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/cluster/replaceSecondary'
221901:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/cluster/swapPrimaryAndSecondary'
221902:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/cluster/numberOfServers'
221903:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/cluster/cleanOutServer'
221904:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/cluster/moveShard'
221905:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/cluster/shardDistribution'
221906:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/cluster/rebalanceShards'
221907:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/cluster/supervisionState'
221908:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_api/cluster/endpoints'
221909:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/configuration/notifications/versions'
221910:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/endpoint'
221911:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/explain'
221912:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/control_pregel'
221913:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/simple/any'
221914:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/simple/near'
221915:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/simple/within'
221916:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/simple/within-rectangle'
221917:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/simple/fulltext'
221918:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/simple/by-example'
221919:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/simple/first-example'
221920:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/simple/first'
221921:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/simple/last'
221922:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/simple/range'
221923:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/simple/remove-by-example'
221924:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/simple/replace-by-example'
221925:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/simple/update-by-example'
221926:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action ''
221927:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/auth/reload'
221928:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript  action '_admin/aql/reload'
221929:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/tasks'
221930:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/transaction'
221931:2017-08-04T16:02:07Z [4263] DEBUG created JavaScript prefix  action '_api/traversal'
221932:2017-08-04T16:02:07Z [4263] DEBUG connecting to ip endpoint 'http+tcp://10.101.2.56:8529'
221933:2017-08-04T16:02:07Z [4263] INFO {replication} connected to master at tcp://10.101.2.56:8529, id 215517693768543, version 3.2, last log tick 125600629
221934:2017-08-04T16:02:07Z [4263] DEBUG connecting to ip endpoint 'http+tcp://10.101.2.56:8529'
221935:2017-08-04T16:02:07Z [4263] DEBUG connecting to ip endpoint 'http+tcp://10.101.2.56:8529'
221936:2017-08-04T16:02:07Z [4263] DEBUG connecting to ip endpoint 'http+tcp://10.101.2.56:8529'
221937:2017-08-04T16:02:07Z [4263] DEBUG connecting to ip endpoint 'http+tcp://10.101.2.56:8529'
221938:2017-08-04T16:02:08Z [4263] DEBUG Applying chunk: [ { "database" : "178127410", "tick" : "125600631", "tid" : "200824359", "type" : 2200 }, { "database" : "178127410", "tick" : "125600634", "tid" : "200824359", "type" : 2201 }, { "database" : "178127410", "tick" : "125600632", "tid" : "200824353", "type" : 2200 }, { "database" : "178127410", "tick" : "125600635", "tid" : "200824353", "type" : 2201 }, { "database" : "178127410", "tick" : "125600634", "tid" : "200824362", "type" : 2200 },  
---snip---

>221940:2017-08-04T16:02:08Z [4263] DEBUG connecting to ip endpoint 'http+tcp://10.101.2.56:8529'
221941:2017-08-04T16:02:08Z [4263] DEBUG connecting to ip endpoint 'http+tcp://10.101.2.56:8529'
221942:2017-08-04T16:02:08Z [4263] DEBUG connecting to ip endpoint 'http+tcp://10.101.2.56:8529'
221943:2017-08-04T16:02:08Z [4263] INFO {replication} connected to master at tcp://10.101.2.56:8529, id 215517693768543, version 3.2, last log tick 125618071
221944:2017-08-04T16:02:08Z [4263] DEBUG connecting to ip endpoint 'http+tcp://10.101.2.56:8529'
221945:2017-08-04T16:02:08Z [4263] DEBUG connecting to ip endpoint 'http+tcp://10.101.2.56:8529'
221946:2017-08-04T16:02:08Z [4263] DEBUG connecting to ip endpoint 'http+tcp://10.101.2.56:8529'
221947:2017-08-04T16:02:08Z [4263] DEBUG connecting to ip endpoint 'http+tcp://10.101.2.56:8529'
221948:2017-08-04T16:02:09Z [4263] DEBUG Applying chunk: [ {....

The applying chunk lines are ~800k characters long.
This pattern repeats several times within a minute, and has happened on all 3 dbservers at various points. 

Conf files attached.  The rocksdb settings in dbserver.conf were my attempt to resolve this, removing them doesn't fix this issue.

[dbserver.conf.txt](https://github.com/arangodb/arangodb/files/1201118/dbserver.conf.txt)
[coordinator.conf.txt](https://github.com/arangodb/arangodb/files/1201119/coordinator.conf.txt)

**Comment by hellomanjack** [comment] 2017-08-07 01:46
how can you set replication factor for rocksdb cluster. There is no such setting in the web UI. Can you tell me ? Thanks. @natbaker

**Comment by natbaker** [comment] 2017-08-07 02:03
@hellomanjack. It's set per collection, at the bottom of the create collection ui.

**Comment by hellomanjack** [comment] 2017-08-07 02:21
![image](https://user-images.githubusercontent.com/25783698/29009838-58b7f8ca-7b59-11e7-8205-ed3ba0594aef.png)
I use the community Edition in the dcos cluster. I use the docker image arangodb/arangodb-mesos-framework:3.2-build1 and set "--arangodb_storage_engine=rocksdb" to enable rocksdb.
I use the marathon json. As you can see, there is no replication factor there. What's the difference?

**Comment by natbaker** [comment] 2017-08-07 14:43
Huh, weird.  I am running 3.2.0 enterprise (via rpm), and it shows up.  However, I seem to remember it showing on community as well.  I assume you're running more than 1 node?

![image](https://user-images.githubusercontent.com/8976479/29031580-bdc9b188-7b5c-11e7-8956-2703b6f236e8.png)


You could try setting it via the api: https://docs.arangodb.com/devel/HTTP/Collection/Creating.html

**Comment by ldap4life** [comment] 2018-03-09 15:22
@natbaker did you ever find a resolution for this? I am finding similar issues during load testing, using 3.3.3. At some point during a constant load, cpu usage spikes to 100% and stays there, taking a long time to recover, seemingly working on queries that have long since timed out. The slow query history fills up, eventually they all time out at either 120s, 150s, 1200s, or some go to 3600s. The queries are basic inserts or reads keyed on the id

My coordinator logs are filled with:

ERROR {cluster} ClusterComm::performRequests: got no answer from shard:s1010016:/_db/_system/_api/collection/s1010016/count with status timeout
ERROR {cluster} cannot create connection to server 'PRMR-54b9d30a-d40f-4680-92da-a73ac76e683b' at endpoint 'ssl://ip:8539'
WARNING {cluster} Received invalid response for count. Shard distribution inaccurate
2018-03-09T15:03:54Z [31181] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s1010016:/_db/_system/_api/index?collection=s1010016
WARNING catch error in historian: ArangoError: AQL: A cluster backend which was required for the operation could not be reached (while optimizing plan)\n    at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:81:16)\n    at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:94:45)\n    at lastEntry (/usr/share/arangodb3/js/server/modules/@arangodb/statistics.js:106:19)\n    at Object.exports.historian (/usr/share/arangodb3/js/server/modules/@arangodb/statistics.js:451:19)\n    at eval (eval at <anonymous> (unknown source), <anonymous>:3:54)\n    at eval (eval at <anonymous> (unknown source), <anonymous>:3:70)

my db server logs have
2018-03-09T15:05:02Z [14415] ERROR {heartbeat} ALARM: Scheduling background job took 594.005 seconds, scheduler info at schedule time: working: 64, queued: 8, blocked: 0, running: 64, outstanding: 0, min/max: 2/64, scheduler info now: working: 64, queued: 6, blocked: 1, running: 64, outstanding: 0, min/max: 2/64
2018-03-09T15:05:02Z [14415] ERROR {communication} unable to perform ssl handshake: short read : 335544539

**Comment by vinaypyati** [comment] 2018-09-28 12:36
Hi @natbaker, @ldap4life,

Just sending a quick follow up. Did you have a chance to reproduce this issue on the [latest](https://www.arangodb.com/download-major/) ArangoDB  or [v3.4.0 RC1](https://www.arangodb.com/download-technical-preview/)? Please let us know your feedback. 

Thanks!

**Comment by ldap4life** [comment] 2018-09-28 13:05
Apologies, no I have not. Unfortunately i am no longer using arango db.

**Comment by natbaker** [comment] 2018-09-28 14:59
Sorry, same here. We no longer use arango for this.

**Comment by maxkernbach** [comment] 2018-10-23 13:43
Hi @natbaker and @ldap4life,

Please excuse us for the big delay. We are sorry to hear that you are no longer using ArangoDB.

In case anyone is facing a similar issue with the latest available versions 3.3.17 or 3.4 RC2 and could provide a script to reproduce the problem, we would be glad to investigate it.
For now I am closing this issue as "cannot reproduce".

**Comment by maxkernbach** [comment] 2018-10-29 13:51
Hi @toymachiner62,

could you please share some further information so that we can investigate this issue?

1. ArangoDB version + storage engine
1. Number of agents, coordinators and dbservers
2. Replication factor and number of shards for the involved collections
3. Logs of agents, coordinators and dbservers
4. Optimally a small dataset and a script to reproduce the crash

Thanks

**Comment by vinaypyati** [comment] 2018-11-09 10:28
Hi @toymachiner62,

Did you have a chance to read the latest message by maxkernbach? Could you please share us some further information as requested by maxkernbach? 

Thanks!

**Comment by toymachiner62** [comment] 2018-11-09 17:17
@gcallaghan Are you able to answer the questions asked? https://github.com/arangodb/arangodb/issues/2960#issuecomment-433917012

**Comment by maxkernbach** [comment] 2018-12-17 13:08
@toymachiner62 @gcallaghan

Since we have not received any feedback in a while I am closing this issue for now. 

In case the problem persists, please share some details and we will investigate it.

**Closed by maxkernbach** 2018-12-17 13:08 UTC
Labels: 1 Analyzing, 2 Cannot Reproduce, 3 Cluster, Waiting User Reply, performance

**Comment by Himan000** [comment] 2019-04-02 09:38
I think there is a big problem for arangodb. User encounter issue/bug/problem and new an issue here, but nobody reply/support or provide a solution  for a long time. Then the user have to move to other database. Hopefully ArangoDB could pay attention to this problem.

**Comment by dothebart** [comment] 2019-04-02 09:53
@Himan000 we can only solve issues that we can reproduce. If the user doesn't provide neccessary information (half of the questions are about information if you have a closer look) we can't help. 

There will however be some replication improvements in ArangoDB 3.4.5 which is currently in QA - phase.

So yes, we're paying attention to this problem, but your reply was as helpfull as most of the above; if you're able to answer the questions that vinay and max have asked, please let us know.

**Comment by Himan000** [comment] 2019-04-02 10:23
Hi @dothebart,
Thanks for your reply. I'm not able to answer the question above. However I changed replication factor to 1 to aviod replication. But sometime even replication_factor=1, after finish some update collection 
 operation, there is some unknown operation runing in arangodb server and make collection unavailable, that's can't query the collection updated. It's  strange and fatal. At this time, I have to restart arangodb server.

**Comment by dothebart** [comment] 2019-04-02 10:25
if you see such a situation, please obtain cores using gcore: https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#linux-coredumps

**Comment by Himan000** [comment] 2019-04-03 01:57
Hi @dothebart ,

Thanks. Because the problem does not occur every time, I will enable coredumps and see the log next time the problem occur. But only the collection I update can't access, other collection have no such problem, hopefully can dump some log next time. I will update you next time when I encounter the problem.

**Comment by rocketraman** [comment] 2019-07-16 15:01
I have this (or something very similar) on 3.4.3 also. I will try updating to the latest 3.4.x to see if matters improve.

> ArangoDB version + storage engine
3.4.3, RocksDB

> Number of agents, coordinators and dbservers
3 agents, 2 coordinators, 3 dbservers

> Replication factor and number of shards for the involved collections
Replication factor 3, 1 shard

> Logs of agents, coordinators and dbservers
arangodb-db-0 arangodb 2019-07-16T14:25:17Z [1] WARNING {engines} slow background settings sync: 1.199788 s
arangodb-db-0 arangodb 2019-07-16T14:25:23Z [1] WARNING {engines} slow background settings sync: 0.889906 s
arangodb-db-0 arangodb 2019-07-16T14:28:53Z [1] WARNING {replication} synchronous replication: dropping follower PRMR-e6e30ee8-02f5-4707-8361-89cbc0f69c69 for shard s3010755

and on the client:

Operation timed out
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 2003: Error while reading
!      throw error;
!      ^
stacktrace: ArangoError: Error while reading
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:97:21)
    at ArangoStatement.execute (/usr/share/arangodb3/js/client/modules/@arangodb/arango-statement.js:171:12)
    at Proxy.ArangoDatabase._query (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:946:42)
    at <shell command>:1:4

> Optimally a small dataset and a script to reproduce the crash

Don't have this, sorry.
