### ISSUE TITLE
users_users collection not found after arangorestore

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1532] opened 2015-10-17 22:16 UTC
Using ArangoDB 2.6.8:
1. make a backup of my production DB `arangodump --output-directory bu --server.database 'myapp' --include-system-collections true --server.disable-authentication false --server.password 'haha'`
2. on my dev machine `arangorestore --input-directory bu --server.database 'myapp'`
3. confirmed with Aardvark that the users_users collections has been restored correctly
4. trying to log into my foxx app, I get an exception `ArangoError 1203: collection not found`
5. restart arangod
6. now logging in works just fine
7. goto step 2 to repeat problem (i.e. restoring the exact same data that's already in the DB)

This problem seems to be limited to the users collection. If I log in prior to the restore, I can use the other functionality (which use different collections) just fine.

Relevant trace:

```
ERROR [ArangoError 1203: collection not found]
ERROR   at Error (native)
ERROR   at Repository._.extend.byId (/usr/local/Cellar/arangodb/2.6.8/share/arangodb/js/server/modules/org/arangodb/foxx/repository.js:223:32)
ERROR   at Object.getUser [as get] (./foxx/_db/myapp/users/APP/storage.js:70:18)
```

I've seen #1521 but this seems different because a simple restart helps.

**Comment by dothebart** [comment] 2015-10-19 11:21
do I get that correctly that you query one of your own collections in that line of your app?

**Comment by razvanphp** [comment] 2015-10-19 13:09
I had this too, but in my case I could not login to Aardvark because `_sessions` collection was gone. After restart it was fine again.

**Comment by pekeler** [comment] 2015-10-19 15:50
@dothebart I have everything running in my own db ("myapp"), i.e. I'm not using "_system". Within that db, I have Arango's [users app](https://github.com/arangodb-foxx/util-users-local) installed next to my own foxx app. So the collection users_users is created/owned by that users app. I've integrated the users app via a users injector.

So, my controller action "login" calls my users injector which calls code in the users app

**Comment by pekeler** [comment] 2015-10-19 15:53
@dothebart to answer your question: it's my collection in the sense that it's in my db "myapp", but it's your collection in the sense that it was created and is used by the foxx app users.

**Comment by pekeler** [comment] 2015-10-19 16:03
I'm not using persistent sessions which might be why I didn't run into the same problem as @razvanphp.

**Comment by razvanphp** [comment] 2015-10-19 16:06
You are not using persistent sessions in your foxx app, but Aardvark uses them, so maybe this bug is not related with your specific app, but it's something more general.

**Comment by pekeler** [comment] 2015-10-19 16:07
@razvanphp good point.

**Comment by razvanphp** [comment] 2015-10-19 16:11
In my case, I was restoring everything in my "custom" db, including system collections, that drops and rebuilds them, so maybe there is some sort of cache in between that don't check if the collection is back there.

I was even trying to reimport only the `_sessions` collection, it was saying successful, but still I could not login into the web admin. Only restarting arango fixed this. The collection was clearly there, because I could access it with `arangosh`.

**Comment by sleto-it** [comment] 2017-12-17 13:52
All - apologies for very late reply

I see this issue is quite old, and it has been opened more than 2 years ago when the current version was 2.6.8 - which is EOL now

Please could you try latest 3.2 version and let me know if this is still current - or if we can now close this ticket?

Many thanks,

**Comment by pekeler** [comment] 2018-01-10 20:22
sorry - I'm unable to test this any time soon

**Comment by sleto-it** [comment] 2018-01-10 20:25
sure - thanks for the feedback. Closing, please comment if needed and we will reopen

**Comment by dothebart** [comment] 2018-01-17 11:29
reproduced using the graph browser.

**Closed** 2018-01-24 12:50 UTC
Labels: 1 Bug, 3 UserManagement, workaround available
