### ISSUE TITLE
arangoexport progress

### ISSUE THREAD

**Issue by piewared** [arangodb/arangodb#9243] opened 2019-06-10 19:10 UTC
## My Environment

ArangoDB Version: 3.4.6
Storage Engine: RocksDB
Deployment Mode: Single Server
Deployment Strategy: Manual Start
Operating System: Ubuntu 16.04.2
Total RAM in your machine: 16 GB
Disks in use: SSD

## Component, Query & Data

__Affected feature__:

arangoexport

__Problem__:

Arangoexport does not display progress in the console the way arangoimport does. The documentation states that 'progress' is an option that is enabled by default. However, the progress percentage does not display even when the 'progress' flag is included as a command line argument.

**Comment by Simran-B** [comment] 2019-06-11 10:57
This is not a bug, because the implementation of the progress flag doesn't intend to print the progress like arangoimport does. Therefore labeling this as feature request.

With progress=true:

```
arangoexport --collection foo --collection bar --collection baz --progress
Connected to ArangoDB 'http+tcp://127.0.0.1:8529', version 3.4.5, database: '_system', username: 'root'
# Exporting collection 'foo'...
# Exporting collection 'bar'...
# Exporting collection 'baz'...
Processed 3 collection(s), wrote 100200882 byte(s), 292 HTTP request(s)
```

With progress=false:

```
arangoexport --collection foo --collection bar --collection baz --progress false
Connected to ArangoDB 'http+tcp://127.0.0.1:8529', version 3.4.5, database: '_system', username: 'root'
Processed 3 collection(s), wrote 100200882 byte(s), 292 HTTP request(s)
```

On import, progress is logged like this:
`INFO processed 163835 bytes (25%) of input file`

For exports, it could be done in a similar fashion: based on the bytes written to disk, but without a percentage because it's impossible to estimate the total amount including the number of documents (if streaming or the --query parameter are used):
`INFO wrote 163835 bytes to output file`

The question is whether this is helpful, because you can't really predict when it will finish.

**Comment by dothebart** [comment] 2020-09-02 13:59
Since its not easily possible to have a relative progress instead of anouncing what has been done already, closing this as won't fix. 

Please note [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.

**Closed by dothebart** 2020-09-02 13:59 UTC
Labels: 1 Feature, 3 ImportExport
