### ISSUE TITLE
Not able to remove/update existing document (or able to view a deleted document)

### ISSUE THREAD

**Issue by akki** [arangodb/arangodb#2748] opened 2017-07-07 12:21 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.1

On this operating system:
- [ ] Linux 
  - [ ] Ubuntu .deb

I am using ArangoDB in cluster mode.

Hi guys, I am facing an issue. I am not very sure it's related to cluster only.

I have a `coauthors` (edge) collections  in which I have a document with `_key` value `205299267`. I am facing some weird issues with this document. This is the behavior of this document under various queries (all issued from web interface).
1. `FOR coauthor IN coauthors FILTER coauthor._id == "205299267" RETURN coauthor`
    returns me the document
2. `RETURN DOCUMENT("coauthors/205299267")`
    returns `[null]`
3. `REMOVE "205299267" IN coauthors`
Query fails to execute with error `Query: Error message received from shard 's3542516' on cluster node 'PRMR-2a633716-3540-4a30-8ec3-2f00b99f3a46': document not found (while executing)`
4. `REMOVE {"_key": "205299267"} IN coauthors`
Query fails to execute with error `Query: Error message received from shard 's3542516' on cluster node 'PRMR-2a633716-3540-4a30-8ec3-2f00b99f3a46': document not found (while executing)`
5. I can open open this document in my collections i.e. from it's web page on `_admin/aardvark/index.html#collection/coauthors/205299267`
6. When I delete or save this document from it's web page I am thrown no error but it doesn't get deleted or updated.

**Comment by dothebart** [comment] 2018-10-26 14:34
Hi, 
Sorry for the late reply; This is actually a duplicate of a bug fixed a while back; Coordinators wouldn't propperly distribute the documents to the propper DB-Servers. Subsequent queries would then fail to find the document in most cases except for full collection scans. 

ArangoDB 3.3.19 is available for download with this bug fixed. 
Please note the ArangoDB 3.4 Milestone 3 release including the brand new ArangoSearch.

Closing.

**Closed by dothebart** 2018-10-26 14:34 UTC
Labels: 1 Bug, 3 Cluster
