### ISSUE TITLE
Foxx model constructor no longer called

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1592] opened 2015-11-25 16:46 UTC
I'm trying to upgrade from 2.6.8 to 2.7.1 and noticed that my model's constructor is no longer being invoked. From the release note, my understanding is that the old style extend should still be working.

```JavaScript
var Model = Foxx.Model.extend({
  constructor: function() {
    require('console').log('hello?');
    throw('hello???');
    ...
```

**Comment by pluma** [comment] 2015-11-25 16:58
Confirmed. I'm looking into it.

**Comment by pluma** [comment] 2015-11-25 17:22
Thanks to our V8 version support classes but not the spread operation the fix is a bit ugly, but it seems to work fine now. The fix will be in the next bugfix release of 2.7.

**Closed by pluma** 2015-11-25 17:22 UTC
Labels: 1_Bug

**Comment by pekeler** [comment] 2015-11-25 17:23
Thanks for the quick fix!

**Comment by CoDEmanX** [comment] 2015-11-25 17:58
@pluma: spread operator should work in the upcoming V8 v4.7, I think they finally fixed all relevant issues. Not sure when Chrome 47 will ship though, but possibly this year still.

**Comment by pekeler** [comment] 2015-12-05 23:23
Trying out 2.7.2. The constructor is now called, but calling super does not seem to work.

```JavaScript
var Model = Foxx.Model.extend({
  schema: {
    // ...
  },
  constructor: function() {
    // ...
    Foxx.Model.apply(this, arguments);
  }
});
```

```
2015-12-05T23:07:35Z [32561] ERROR TypeError: Class constructors cannot be invoked without 'new'
2015-12-05T23:07:35Z [32561] ERROR   at [object Object].Model (/usr/local/Cellar/arangodb/2.7.2/share/arangodb/js/server/modules/org/arangodb/foxx/model.js:76:14)
```

Is there perhaps an alternative way of overriding constructors that works in 2.6 and 2.7?

**Comment by pluma** [comment] 2015-12-08 12:42
I've reverted the move to ES 2015 for Repository and Model due to the incompatibilities (f781440 for 2.7, b132079 for 2.8). This should be solved in 2.8.0 and the next 2.7 bugfix release.

**Comment by CoDEmanX** [comment] 2015-12-08 13:31
@Alan: some more ES2015 features will be available after an upgrade to V8 4.7, but some other prominent ones in 4.8 or later. What exact features do you need?

**Comment by pluma** [comment] 2015-12-08 13:47
@CoDEmanX there's no sane way to make ES6 classes fully backwards compatible for Foxx.Model and Foxx.Repository. There are at least two major problems:

1. The implementation of the `extend` method in Foxx needs the spread operator to work properly (because `super` is not a regular function and therefore doesn't have an `apply` method).

2. There is no way to make ES6 constructors compatible with Backbone-style "constructors" when using ES6 inheritance (because parent ES6 constructors have to be invoked using `super`, which must be done before `this` is available).

Number 2 isn't a problem in @pekeler's example as `Foxx.Model.apply(this, arguments)` is redundant (because `super(...args)` already takes care of that), but it prevents sub-classes from intercepting constructor arguments or delaying the invocation.

**Comment by CoDEmanX** [comment] 2015-12-08 14:18
Spread operator and rest params [will be available in V8 4.7](https://code.google.com/p/v8/issues/detail?id=3018#c27), but I don't think such a V8 upgrade will make it in time for Arango v2.8, will it?

**Comment by dothebart** [comment] 2015-12-08 14:35
no, fiddling with the new way to do buffers in V8 doesn't get ready in time - still hacking.

**Comment by pluma** [comment] 2015-12-08 15:59
@CoDEmanX even if the spread syntax were available, number 2 is basically a killer.

**Comment by CoDEmanX** [comment] 2015-12-15 15:00
@pluma: You might wanna remove the deprecation warning `"extend" is deprecated, use clas
s syntax instead` then.

**Comment by pluma** [comment] 2015-12-15 16:42
@CoDEmanX you're probably looking at the devel branch which 3.0 will be based on. The changes are only in 2.8.

**Comment by CoDEmanX** [comment] 2015-12-15 16:51
The official 2.8 beta for Windows actually...

**Comment by pluma** [comment] 2015-12-15 17:58
Ah, the change landed after that release.
