### ISSUE TITLE
Misbehaviour on async replication

### ISSUE THREAD

**Issue by smurfio** [arangodb/arangodb#4301] opened 2018-01-14 12:37 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x ] 3.3

Mode:
- [x ] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- Google Kubernetes Engine
- [x] Linux
  - [x] docker - official docker library

### this is an replication-related issue:

Hi, I've set up an async-replication which doesn't seem to work properly.

I've several queries of the following type on the master:

```
FOR doc IN edgeCollection FILTER doc._from==fromOld
UPDATE doc WITH {"_from":fromNew} IN edgeCollection
```

On the master all relevant edges get updated as expected.
For some reason only the update of the first found edge gets replicated to the slave.

Same seems to be happening for queries like the following:

```
FOR doc IN [{"from":from1,"attr":attr1,"to":to1},{"from":from2,"attr":attr2,"to":to2}]
UPSERT {"_from":doc.from,"_to":doc.to}
INSERT {"_from":doc.from,"attr":doc.attr,"_to":doc.to}
UPDATE {"attr":doc.attr}
IN edgeCollection
```

**Comment by sleto-it** [comment] 2018-01-16 08:56
Hi @smurfio,

Thanks for opening this issue. We have worked on some improvements in the replication in the latest days, so our next hotfix could fix your problem already

However, to be sure and in case work to provide any additional needed fix, it would be nice if we can reproduce your issue internally

Could it be possible for you to share your master database? You can share it using services like dropbox or google drive, or directly, using this email address hackers (at) arangodb (dot) com

Many thanks,

**Comment by smurfio** [comment] 2018-01-22 09:59
Hi,

sorry for the late reply. Unfortunately I’m not able to share the database. There is no public access. And the database itself has around 20GB.

However it is not just a „special“ collection that causes the problems. It seems that every query that causes modifications/removals on multiple documents only replicates the first changed/removed document.
I’m sure this happens on edge collections. With vertex collections I’m not sure. Every edge collection in our setup has an additional unique hash index on [„_from“,“_to“]

Regards,
Manuel

**Comment by jsteemann** [comment] 2018-01-29 11:41
@smurfio : ArangoDB 3.3.3 has been released last week, which contains some improvements for the RocksDB-based replication.
Can you check with that release if the problem persists? I have written a few tests for queries as the above, and I can't reproduce the problem anymore with the latest version. So hopefully it will work for you too. Thanks.

**Comment by maxkernbach** [comment] 2018-02-20 11:35
Hi @smurfio,

did you have a chance to retry the replication with the latest version 3.3.3?

**Comment by maxkernbach** [comment] 2018-03-05 16:11
I am closing this issue for now as we can't reproduce the problem using the current version. We have not received any feedback for over one month and recent hotfixes include several replication improvements.

Please feel free to comment and reopen in case this problem still occurs.

**Closed by maxkernbach** 2018-03-05 16:11 UTC
Labels: 1 Bug, 2 Fixed, 3 Master/Slave Replication, Waiting User Reply
