### ISSUE TITLE
Can we get an alias for FOR ... FILTER ... LIMIT ... RETURN queries?

### ISSUE THREAD

**Issue by RienNeVaPlus** [arangodb/arangodb#10623] opened 2019-12-04 05:16 UTC
I love AQL because it can get quite complex. However, I often end up with nasty queries like:

````aql
RETURN MERGE(result, {
    related1: (FOR r1 IN OneToOne FILTER r1._key == result.related1 LIMIT 1 RETURN r1)[0],
    items: (FOR item IN OneToMany FILTER item._key IN result.items RETURN item),
    list: (FOR r2 IN OneToMany FILTER r2.related == result.id LIMIT 10, 20 RETURN r2)
    ...
})
````

Having a `DOCUMENTS()` or `FOR_FILTER()` or something like that would be really cool:

````aql
RETURN MERGE(result, {
    related1: DOCUMENTS('OneToOne", {_key: result.related1}, 1),
    items: DOCUMENTS('OneToMany', {_key: ['IN', result.items]}),
    list: DOCUMENTS('OneToMany", {related:result.id}, [10,20])
})
````

### DOCUMENTS(collection, filter, limit?)
Alias for `FOR i IN c FILTER {...filter} LIMIT limit RETURN i`:

 - **collection**: `string`
   The name of the collection
 - **filter**: `{[key:string]: any | [string, any] }`
    Filters the collection either by `{key: val}` or `{key: [operator, value]}`
 - **limit**?: `number | [number, number]`
    Use `1` to return the first document instead of an array. Use `[number, number]` to skip results.

Maybe this is too specific, but I've created a custom AQL function, and it's quite slow in comparison to the verbose way, so I thought I'd share the idea with whom it really matters 🥑 👍 

Thanks

**Comment by dothebart** [comment] 2020-09-02 15:02
Hi, 
I'll close this as a duplicate of https://github.com/arangodb/arangodb/issues/4009

Please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.

**Closed by dothebart** 2020-09-02 15:02 UTC
Labels: 1 Feature, 3 AQL
