### ISSUE TITLE
"operation was canceled" on an attempt to get a collection

### ISSUE THREAD

**Issue by vanobig** [arangodb/arangodb#9137] opened 2019-05-29 17:22 UTC
## My Environment

* __ArangoDB Version__:        3.4.5
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Infrastructure__:               Google Cloud
* __Operating System__:        Debian 9
* __Total RAM in your machine__:        54G
* __Disks in use__:        SSD
* __Used Package__:              Debian

## Component, Query & Data

__Affected feature__:
Request to get a collection via Golang's driver.

__AQL query (if applicable)__:
N/A restful call is made via the go-driver

__AQL explain (if applicable)__:
N/A

__Dataset__:
Can't be shared, but, as an example, it happened to a collection with just 1500 records.

__Size of your Dataset on disk__:
???

__Replication Factor & Number of Shards (Cluster only)__:
N/A

## Steps to reproduce
Couldn't figure out. Happens 4-6 times a day but without any clues about the root cause.

__Problem__:
Here is a code snippet where it happens

ctx := context.Background()
col, err := access.DB.Collection(ctx, "alert")
if err != nil {
	access.Log.Errorf("cannot access alert collection: %v", err)
	return err
}

And the error would look like this
Get http://arango:xxxxx/_db/xxxx/_api/collection/alert: dial tcp: lookup arango on x.x.x.x: dial udp x.x.x.x: operation was canceled"

__Expected result__:
No error, get a collection back.

**Comment by vanobig** [comment] 2019-05-29 17:26
There is another variation of a similar issue, with the following error message:
Head http://arango:xxxxx/_db/xxxx/_api/collection/alert/xxx: dial tcp: lookup arango on x.x.x.x: dial udp x.x.x.x: operation was canceled

**Comment by alpenfritz** [comment] 2020-08-12 02:43
We encountered the same issue:

## Environment
ArangoDB Version: 3.6.4 Community Edition
Storage Engine: RocksDB
Deployment Mode: Single Server
Deployment Strategy: ArangoDB Deployment Operator
Configuration: vCPU 4
Infrastructure: Azure Standard_D4s_v3
Operating System: Ubuntu 16.04-LTS
Total RAM in your machine: 16Gb
Disks in use: SSD 100Gb
Used Package: N/A

## Component, Query & Data
Affected feature:
Request to run a query via Golang's driver.

AQL query (if applicable):
```
	ctx := context.Background()
	db, err := dbUtils.ArangoDbOpen(&ctx)
	if err != nil {
		...
	}

	bindVars := map[string]interface{}{
		"user_id":      fmt.Sprintf("users/%v", userID),
		"workspace_id": fmt.Sprintf("workspaces/%v", workspaceID),
	}
	query := `
		FOR e IN edges
			FILTER e._from == @user_id
			FILTER e._to == @workspace_id
			RETURN e
	`
	cursor, err := db.Query(ctx, query, bindVars)
	if err != nil {
		...
	}
	defer cursor.Close()
```

AQL explain (if applicable):
N/A

Dataset:
Can't be shared

Size of your Dataset on disk:
N/A

Replication Factor & Number of Shards (Cluster only):
N/A

## Steps to reproduce
Occurs only sporadically.

Problem:
```
Get https://arangodbXXX:8529/_db/YYY/_api/database/current: dial tcp: lookup arangodbXXX on 10.0.XX.YY:ZZ: dial udp 10.0.XX.YY:ZZ: operation was canceled
```

Expected result:
No error

**Comment by dothebart** [comment] 2020-08-12 15:45
Googling the error message, this seems to be a DNS lookup issue inside the GO runtime? 
i.e. https://github.com/hashicorp/terraform-provider-vsphere/issues/366 - 
so, 
- fix your DNS
- don't use DNS (use IP directly) 
are the possible solutions here that come to my mind, but as far as I get it this is not directly related to ArangoDB itself hence there can't be a fix there.

**Comment by dothebart** [comment] 2020-08-26 08:40
closing as solved.

**Closed by dothebart** 2020-08-26 08:40 UTC
Labels: 1 Question, 2 Solved, 3 Driver, workaround available
