### ISSUE TITLE
HTTPS call inside Foxx application 

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#2418] opened 2017-04-10 15:42 UTC
Dear team,
   We are trying to see whether we can call https call with in Foxx service. Our requirement is one Foxx service calls another Foxx service exposed over https.

I tried with request module. But no luck. Is there any way this can be done.

Thanks & Regards,
Sajeev

**Comment by dothebart** [comment] 2017-04-11 11:29
could this be a duplicate of #1974 ? So then you're lucky ;-)

**Comment by baslr** [comment] 2017-04-11 16:15
@sajeevpr this is fixed with ArangoDB v3.1.18

**Comment by sajeevpr** [comment] 2017-04-12 12:55
Thank you. Will wait for 3.1.18

**Comment by dothebart** [comment] 2017-05-22 09:10
Sorry, the target milestone was missing. The release containing this bugfix is available for download.

**Closed by dothebart** 2017-05-22 09:10 UTC
Labels: 3 SSL
