### ISSUE TITLE
OOM with Big Documents on small machine

### ISSUE THREAD

**Issue by sdy7** [arangodb/arangodb#3206] opened 2017-09-05 07:13 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [* ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [* ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [* ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ *] Ubuntu .deb

Ubuntu 16.04 on aws ec2 c4.large. Default configuration, only authentication disabled.
Loading two collections (3k + 500k docs) and an edge collection (2.5m edges) with arangoimp. The arangod service breaks down before it completes. Nothing in the logs about it (from what I could find). Failure observed in version 3.2.2. ArangoDB v3.2.1 works fine on this.

**Comment by sdy7** [comment] 2017-09-05 07:15
For easy reproduction of error. Run this python3 script:
[loaderscript dummy.zip](https://github.com/arangodb/arangodb/files/1276399/loaderscript.dummy.zip)

**Comment by dothebart** [comment] 2017-09-05 12:09
Hi, 
I've tried with current devel (which is one week ahead of 3.2.2), and it worked for me. 
Can you retry with the nightlies?

**Comment by dothebart** [comment] 2017-09-05 12:11
AWS tends to have troubles with too much disk I/O, it then simply cuts of I/O completely, can you reproduce this issue yourselves on raw iron? (workstation?)

**Comment by sdy7** [comment] 2017-09-05 14:09
Hi, the nightly also failed. Same behaviour.

Another observation is that after crash, I can't start arangod. 
$ sudo /etc/init.d/arangodb3 start
[ ok ] Starting arangodb3 (via systemctl): arangodb3.service.
but it doesn't start or shuts down immediately again.
Haven't tried on "raw iron" - don't have a ubuntu installed currently.

**Comment by dothebart** [comment] 2017-09-07 09:08
do you see any output in `dmesg` in the related timeframes?

**Comment by sdy7** [comment] 2017-09-07 11:12
here is dmesg output. Aha, there is something about out-of-mem...
[dmesg.txt](https://github.com/arangodb/arangodb/files/1284459/dmesg.txt)

**Comment by dothebart** [comment] 2017-09-07 11:14
How much ram does that instance have?

**Comment by sdy7** [comment] 2017-09-07 11:17
3.75 G

**Comment by dothebart** [comment] 2017-09-11 15:06
Ok, so its an OOM in your case. 

From 3.2.1 to 3.2.2 we changed the used version of jemalloc, ( https://github.com/arangodb/arangodb/blob/v3.2.2/CHANGELOG ) since the old version had some issues in certain memory intense scenarios. 

Obviously the new version doesn't work better for your scenario. 

Can you retry with an instance with more memory? (to compare - my workstation has 32GB - but 6 or 8 GB should work)

**Comment by sdy7** [comment] 2017-09-12 06:44
Thanks for sharing the reason. With more RAM it loaded with success. 
Will this "scenario" be addressed?

**Comment by dothebart** [comment] 2017-09-13 15:11
Jemalloc has a flush interval which every 10 seconds will try to return RAM to the OS. 

It could be that this value is to huge so the oom killer kicks in. 

You could add some swap space for that - which should also work most of the time. 

whats your value of `/proc/sys/vm/overcommit_memory` and `/proc/sys/vm/overcommit_ratio` ?

You could try to altter the settings of 
`--rocksdb.block-cache-size`
and 
`  --cache.size <uint64>                                       size of cache in bytes (default: 9454398259)`
(which influences edge caching)

Do you run the python script on the same machine? If not, can you try to run it on another?

**Comment by sdy7** [comment] 2017-09-19 13:21
/proc/sys/vm/overcommit_memory is 0
/proc/sys/vm/overcommit_ratio is 50

I rather go up in mem size than use swap. Something sends mem usage up while loading the edges. An easier workaround however, is to reduce the batch size for arangoimp from 1m to 1k records while loading edges along with some throttling. That worked though it took longer. 

On this machine (c4.large 3.75G) the values of --rocksdb.block-cache-size and --cache.size defaults to 
268435456 bytes according to arangod --help.  I tried to set them to 100000000 in the arangod.conf file. But it didn't make a difference.

My exercise is to load robustly without worrying about crossing an invisible line.

**Comment by dothebart** [comment] 2017-09-20 10:31
Ok, We should investigate whether we can make jemalloc behave smarter - so its most probably large chunks being released, but not returned on time.

**Comment by dothebart** [comment] 2017-11-23 16:36
Hi, 
with 3.2.8 we have upgraded V8 with some memory problems fixed, plus added more jemalloc related optimisation.
Can you retry whether ArangoDB now behaves better for you?

**Comment by sleto-it** [comment] 2017-12-17 13:08
Hi,

Considering that:

- we have not received additional feedback in the recent 24 days
- recent 3.2 versions, as @dothebart wrote, contain some fixes related to memory usage
- 3.75 G of RAM, as originally reported, seems quite a low value for a database server
- original user reported that with more RAM the *arangoimp* command was successful
- we have opened an internal issue for us to investigate more if something can be done to tune Jemalloc

I think it is safe to close this issue now. @sdy7 if you have additional feedback, please do let us know and we will consider to re-open the ticket

Thanks again for reporting this,

**Closed by sleto-it** 2017-12-17 13:08 UTC
Labels: 1 Feature, 3 Core, 3 OOM, Waiting User Reply
