### ISSUE TITLE
ArangoDb graph create exception: Persisted graph is invalid

### ISSUE THREAD

**Issue by leonidUH** [arangodb/arangodb#12982] opened 2020-11-04 10:14 UTC
## My Environment

* __ArangoDB Version__:        3.6.3-664
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Kubernetes ArangoDeployment
* __Configuration__:               3 agents ,3 dbservers ,3 coordinators
* __Infrastructure__:              AWS
* __Agent Requests__:       3X - cpu: 1500m, memory: 1536Mi
* __DbServer Requests__:   3X  -   cpu: 3, memory: 4G
* __Coordinator Requests__:   3X  -    cpu: 1500m, memory: 1536Mi
* __Arangodb-java-driver__:    6.4.1
* __Kube-arangodb-operator__:    1.0.5

__Problem__:

We had a very unpleasant problem on our PROD cluster.
When i tried to create graph with arango java client  it failed with some arangodb exception

**exception **:

> WARN [2020-11-04 00:00:10,806] ArangoHandler: Exception while adding query 938ece9040f118dd738fc4f60c8d9284 ! com.arangodb.ArangoDBException: Response: 500, Error: 4 - Persisted graph is invalid. It does not have a _key set. Please contact support. (exception location: /work/ArangoDB/arangod/Graph/Graph.cpp:99). Please report this error to arangodb.com ! at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:53) ! at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:142) ! at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:128) ! at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:42) ! at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:125) ! at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:47) ! at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:72) ! at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:62) ! at com.arangodb.internal.ArangoDatabaseImpl.createGraph(ArangoDatabaseImpl.java:318) ! at 

**code example:**:
```
String queryId="938ece9040f118dd738fc4f60c8d9284";
EdgeDefinition edgeDefinition1 = new EdgeDefinition()
                .collection(CLASS_EDGE_1)
                .from(CLASS_VERTEX_1)
                .to(CLASS_VERTEX_2);
        EdgeDefinition edgeDefinition2 = new EdgeDefinition()
                .collection(CLASS_EDGE_2)
                .from(CLASS_VERTEX_2)
                .to(CLASS_VERTEX_2);
        EdgeDefinition edgeDefinition3 = new EdgeDefinition()
                .collection(CLASS_EDGE_3)
                .from(CLASS_VERTEX_1)
                .to(CLASS_VERTEX_1);
        arangoDatabase.createGraph(
                queryId, Arrays.asList(edgeDefinition1, edgeDefinition2, edgeDefinition3), new GraphCreateOptions());

```

**Comment by dothebart** [comment] 2020-11-04 10:18
This error is thrown if there is no name in the graph definition. 
Can you inspect your existing `_graphs` system collection for that?

**Comment by leonidUH** [comment] 2020-11-04 10:32
@dothebart 
I know it , but when i called to arango createGraph method queryId is not NULL
This specific graph "938ece9040f118dd738fc4f60c8d9284" does not appear in _graphs , but all other graph yes

**Comment by Simran-B** [comment] 2020-11-04 13:46
@leonidUH Can you share the contents of the `_graphs` collection for inspection?

**Comment by leonidUH** [comment] 2020-11-04 14:26
Our Prod system has been working for a while and suddenly yesterday it happened about 20 times  (from 17:47:33.571 up to 00:00:11.217 UTC) 
Before adding a new graph, we make a drop if there was already a graph with the same name
```
[
  {
    "_key": "95d254d6cf1725189efeb9e6f229b782",
    "_id": "_graphs/95d254d6cf1725189efeb9e6f229b782",
    "_rev": "_bW4yzvy--A",
    "numberOfShards": 1,
    "replicationFactor": 1,
    "minReplicationFactor": 1,
    "writeConcern": 1,
    "isSmart": false,
    "edgeDefinitions": [
      {
        "collection": "edge1",
        "from": [
          "collection1"
        ],
        "to": [
          "collection1"
        ]
      },
      {
        "collection": "edge2",
        "from": [
          "collection2"
        ],
        "to": [
          "collection2"
        ]
      },
      {
        "collection": "edge3",
        "from": [
          "collection2"
        ],
        "to": [
          "collection1"
        ]
      }
    ],
    "orphanCollections": []
  }
]
```

**Comment by leonidUH** [comment] 2020-11-04 14:27
![1](https://user-images.githubusercontent.com/11331844/98123529-a53e3580-1eba-11eb-9244-2c8a31b416bd.jpg)

**Comment by Simran-B** [comment] 2020-11-04 16:44
So there is no graph with _key `938ece9040f118dd738fc4f60c8d9284` at any point, or does it get dropped automatically by chance? I wonder if replication has something to do with this...

**Comment by leonidUH** [comment] 2020-11-04 18:02
@Simran-B 
there is no graph with _key 938ece9040f118dd738fc4f60c8d9284.
Maybe due to the fact that there were a couple of milliseconds between the graph drop and graph create after it ,it first drop it from first replica and dropping from second replica was already after next graph creation.

**Comment by leonidUH** [comment] 2020-11-05 06:10
@Simran-B 
One more thing is strange that in the Info  section replicationFactor:2  but in graph itself : replicationFactor: 1

**Comment by leonidUH** [comment] 2020-11-09 10:22
Are there any updates?

**Comment by dothebart** [comment] 2020-11-09 10:32
Hi, 
please note that community subscritptions don't contain an SLA - https://www.arangodb.com/subscriptions/ 
If you need that, please use the contact formular at the bottom of the page.

**Comment by Simran-B** [comment] 2020-11-12 12:01
Is the issue reproducible in a fresh instance? Also with the most recent 3.7 version?
Can you tell us file system is in use? Certain types are known to be problematic.

**Comment by Simran-B** [comment] 2020-11-25 15:35
@leonidUH Can you provide us more information (see above)? We still don't know what can cause this or how to reproduce it.

**Comment by leonidUH** [comment] 2020-12-01 12:39
@Simran-B 
we had it only that time and was no longer reproduced

**Comment by maxkernbach** [comment] 2020-12-02 15:55
@leonidUH Closing this issue for now since we are missing the information to reproduce it.

In case the problem reoccurs, please comment and we will have a look.

**Closed by maxkernbach** 2020-12-02 15:55 UTC
Labels: 1 Bug, 3 Cluster, 3 Graph, 3 RocksDB, Waiting User Reply
