### ISSUE TITLE
arangodump and immediate arangorestore with new database not working in 2.7.2

### ISSUE THREAD

**Issue by mknittig** [arangodb/arangodb#1598] opened 2015-12-08 14:52 UTC
Trying this: 
```
arangodump --server.database <database> --output-directory $TEMPDIR --overwrite true
arangorestore --create-database true --server.database <new-database> --input-directory $TEMPDIR --overwrite true
```
I always get:
```
Processed 15 collection(s), read 5984700 byte(s) from datafiles, sent 14 batch(es)
Error: internal error: got error from server: HTTP 500 (Internal Server Error): ArangoError 1205: illegal document handle
```
No error message in the log file..

**Comment by jsteemann** [comment] 2015-12-08 15:19
It works fine when I try it. I think the error you're reporting can only if a collection type (edge / document) somehow does not match, or if documents without `_from` and `_to` attributes are imported into an edge collection.

This may happen because the `--overwrite` option is set to `true`. This can cause problems, for example, when performing an arangodump, `--overwrite true` will add the dump to an existing output directory (i.e. `$TEMPDIR` in your case). In case `$TEMPDIR` is not empty, then the dump will contain whatever arangodump produces **plus** what was in `$TEMPDIR` before.
If you reimport that, this may cause problems, because the data does not necessarily fit together.

Apart from that, re-importing with `--overwrite true` into an existing database may cause similar problems: if the target database already exists, but the collections in it have different types (document vs. edge) than expected, then the import may fail with the error message you reported.

To find out the root cause, can you make sure that the output directory is empty or does not exist when dumping. Additionally, could you check before re-importing that the target database does not already exist (`--create-database true` does not mean the restore will fail if it does already exist), or if it exists, that the collection types match the ones in your dump?

If you don't want to do all this, you can retry dump and restore with `--overwrite false`.

**Comment by mknittig** [comment] 2015-12-08 16:04
Tried it without `--overwrite false`, still happens. I guess there could be inconsistencies with edges as this is my developer database. Is there any way to check this automatically?

**Comment by jsteemann** [comment] 2015-12-08 16:11
Probably your dumped edges refer to one or many non-existing collection(s), so the dump contains `_unknown/...` values in the `_from` and/or `_to` attributes of the edges. These will be somewhat meaningless and cannot be re-imported sensibly.
To go ahead, you could exclude these collections from either the dump or the restore, or, if you want to keep them, replace the `_unknown/...` in the dump files with some existing collection name.

**Comment by jsteemann** [comment] 2015-12-08 17:26
I have added better error reporting for these cases in the 2.8 and devel branches:

* dumping edges that refer to a non-existing collection will now fail by default and produce an error message. These errors can be ignored by specifying the option `--force true` when invoking arangodump
* restoring edges that refer to an unknown collection (including the pseudo-collection `_unknown`) will now fail with a meaningful error message that will be displayed by arangorestore. 

This should help diagnosing that problem much quicker in the future. 2.7 remains unchanged for now, as 2.8 will be out soon.

**Comment by mknittig** [comment] 2015-12-09 17:58
Thanks, there are indeed `_unknown/...` entries in collections. Will probably just remove these..

**Comment by jsteemann** [comment] 2015-12-16 21:40
Thanks for conforming. I'll close this issue then.

**Closed by jsteemann** 2015-12-16 21:40 UTC
