### ISSUE TITLE
Query timeouts & coordinator crash

### ISSUE THREAD

**Issue by CMogilko** [arangodb/arangodb#14431] opened 2021-06-29 15:52 UTC
## My Environment

* __ArangoDB Version__: 3.7.11
* __Storage Engine__: RocksDB
* __Deployment Mode__: Cluster
* __Deployment Strategy__: Manual Start in Docker
* __Configuration__: 5 dbserver, 5 agency on 5 separate server, 8 coordiators on 8 separate servers
* __Infrastructure__: own
* __Operating System__: centos7
* __Total RAM in your machine__: 120gb
* __Disks in use__: ssd nvme
* __Used Package__: Docker - official Docker library

## Component, Query & Data

__Affected feature__:
github.com/arangodb/go-driver v0.0.0-20210621075908-e7a6fa0cbd18 (master)

__AQL query (if applicable)__:
Find group IDs for given entity ID:
```
WITH entities
FOR v, e IN 1..100 INBOUND @id membership OPTIONS { bfs: true, uniqueVertices : 'global' }
    RETURN v
```

__Dataset__:
100k edges: 1 entity to 1 group

__Size of your Dataset on disk__:
300 MB

__Replication Factor & Number of Shards (Cluster only)__:
Entities: 1 shard, 5 replicas, 3 write concern
Membership: 1 shard, 5 replicas, 3 write concern

## Steps to reproduce

1. Run load testing with only 1500 RPS this query
2. Get 30% errors `i/o timeout` in clients
3. Get SIGSEGV in a coordinator

__Problem__:
I was running a load testing with simple graph query which returns user's group ids only in a single collection in the powerful cluster configuration. But on a relatively low rps gets timeouts with very low cpu usage (1% on 16 cores) and disk utilization (1%).
Then coordinator server just crashed segfault.

```
2021-06-29T14:00:34Z [1] FATAL [a7902] {crash} ArangoDB 3.7.11 [linux], thread 16 [Io] caught unexpected signal 11 (SIGSEGV) accessing address 0x0000000000000078: signal handler invoked - image base address: 0x00007f605cc64000 - CPU context: rip: 0x00007f605e2eb670, rsp: 0x00007f6042be4670, efl: 0x0000000000010206, rbp: 0x00007f6042be4770, rsi: 0x0000000000000036, rdi: 0x00007f6042be47f0, rax: 0x00000000140e0197, rbx: 0x00007f603defe680, rcx: 0x0000000000000020, rdx: 0x0000000000000000, r8: 0x0000000000000000, r9: 0x00007f6042be6b5c, r10: 0x0000000000000000, r11: 0x0000000000000246, r12: 0x00007f6061023030, r13: 0x00007f6042be47f0, r14: 0x00007f603defe6c8, r15: 0x00000000041f4564
2021-06-29T14:00:39Z [1] WARNING [77655] {heartbeat} ATTENTION: Sending a heartbeat took longer than 2 seconds, this might be causing trouble with health checks. Please contact ArangoDB Support.
2021-06-29T14:01:06Z [1] INFO [308c3] {crash} frame  1 [+0x00000000007eb730] *no symbol name available for this frame
2021-06-29T14:01:25Z [1] WARNING [77622] {heartbeat} ATTENTION: Getting news from agency took longer than 10 seconds, this might be causing trouble. Please contact ArangoDB Support.
2021-06-29T14:01:29Z [1] INFO [308c3] {crash} frame  2 [+0x000000000380b0f2] *no symbol name available for this frame
2021-06-29T14:01:54Z [1] INFO [308c3] {crash} frame  3 [+0x000000000168aca8] *no symbol name available for this frame
2021-06-29T14:02:20Z [1] INFO [308c3] {crash} frame  4 [+0x00000000018ee191] *no symbol name available for this frame
2021-06-29T14:02:46Z [1] INFO [308c3] {crash} frame  5 [+0x00000000019047a8] *no symbol name available for this frame
2021-06-29T14:03:22Z [1] INFO [308c3] {crash} frame  6 [+0x00000000007e848b] *no symbol name available for this frame
2021-06-29T14:03:40Z [1] ERROR [abcde] {communication} communication error: 'Error while writing' from destination 'shard:s10019'
2021-06-29T14:03:45Z [1] ERROR [abcde] {communication} communication error: 'Error while writing' from destination 'server:PRMR-761b9a31-690a-41f0-a127-d13d3bbdcb6d'
2021-06-29T14:03:41Z [1] WARNING [77655] {heartbeat} ATTENTION: Sending a heartbeat took longer than 2 seconds, this might be causing trouble with health checks. Please contact ArangoDB Support.
2021-06-29T14:03:47Z [1] ERROR [abcde] {communication} communication error: 'Error while writing' from destination 'server:PRMR-761b9a31-690a-41f0-a127-d13d3bbdcb6d'
2021-06-29T14:03:47Z [1] ERROR [abcde] {communication} communication error: 'Error while writing' from destination 'shard:s10019'
2021-06-29T14:03:48Z [1] INFO [308c3] {crash} frame  7 [+0x0000000000775baf] *no symbol name available for this frame
2021-06-29T14:03:57Z [1] ERROR [abcde] {communication} communication error: 'Error while writing' from destination 'server:PRMR-761b9a31-690a-41f0-a127-d13d3bbdcb6d'
2021-06-29T14:04:04Z [1] ERROR [abcde] {communication} communication error: 'Error while writing' from destination 'server:PRMR-761b9a31-690a-41f0-a127-d13d3bbdcb6d'
2021-06-29T14:04:08Z [1] WARNING [77622] {heartbeat} ATTENTION: Getting news from agency took longer than 10 seconds, this might be causing trouble. Please contact ArangoDB Support.
2021-06-29T14:04:14Z [1] INFO [308c3] {crash} frame  8 [+0x0000000003811c45] *no symbol name available for this frame
2021-06-29T14:04:24Z [1] INFO [ded81] {crash} available physical memory: 7951142912, rss usage: 273715200, vsz usage: 1342480384, threads: 95
...
2021-06-29T13:54:29Z [1] WARNING [6d997] {threads} caught exception in runCronThread: named queue is full
2021-06-29T13:54:31Z [1] WARNING [6d997] {threads} caught exception in runCronThread: named queue is full
2021-06-29T13:54:32Z [1] WARNING [dead1] {threads} Scheduler queue 2 with max capacity 4096 is full (happened 2193 times since last message)
2021-06-29T13:54:40Z [1] WARNING [dead2] {threads} Scheduler queue with max capacity 4096 has approximately 4128 tasks and is filled more than 50% in last 10.2712s (happened 11537 times since last message)
2021-06-29T13:54:42Z [1] WARNING [dead1] {threads} Scheduler queue 2 with max capacity 4096 is full (happened 2836 times since last message)
2021-06-29T13:54:50Z [1] WARNING [dead2] {threads} Scheduler queue with max capacity 4096 has approximately 4124 tasks and is filled more than 50% in last 10.1095s (happened 14101 times since last message)
2021-06-29T13:54:52Z [1] WARNING [dead1] {threads} Scheduler queue 2 with max capacity 4096 is full (happened 2762 times since last message)
```

__Expected result__:
Timeouts with high cpu or disk usage, no segfaults.

**Comment by maxkernbach** [comment] 2021-06-30 14:29
Hi @CMogilko,

When running the query, do you monitor the memory usage? Possibly, the coordinator restart is caused by an out of memory.

**Comment by CMogilko** [comment] 2021-06-30 15:00
![изображение](https://user-images.githubusercontent.com/2893054/123984080-03c99e00-d9cd-11eb-9285-0db0275a15df.png)

**Comment by CMogilko** [comment] 2021-06-30 15:01
no high memory usage. 13:54 timeouts to dbserver, 14:04 crash according to log.

**Comment by mpoeter** [comment] 2021-07-05 08:24
@CMogilko The above PR should potentially fix the segfault and will probably land in the upcoming 3.7.13 release.
However, the fix is already part of the current 3.8 release candidate in case you want to give it a spin.

FWIW: you wrote that you are performing some load tests, but the fact that your scheduler queues are full indicates that you are _overloading_ your system. Granted, it should definitely not segfault, but an overloaded system will not operate at peak performance. For more information about measuring possible capacity see this blog post: https://www.arangodb.com/2017/10/performance-analysis-pyarango-usage-scenarios/

**Comment by maxkernbach** [comment] 2021-09-06 15:57
Hi @CMogilko,

Both latest versions 3.7.14 and 3.8.1 include the fix for a potential segfault.
Could you please upgrade and let us know whether server crashes still occur?

**Comment by Simran-B** [comment] 2021-09-15 12:44
@CMogilko Can you check whether the problem is fixed in the latest versions?

**Comment by dothebart** [comment] 2021-11-30 14:45
closing as fixed.

**Closed by dothebart** 2021-11-30 14:45 UTC
Labels: 3 Graph, 3 Cluster, Waiting User Reply, 1 Analyzing
