### ISSUE TITLE
Web UI Query editor - comments handling

### ISSUE THREAD

**Issue by davidmw** [arangodb/arangodb#5361] opened 2018-05-16 08:58 UTC
- [ ] 3.3
- [ ] rocksdb
- [ ] AWS

The query editor reacts to both the // and the /* */ style of comments by changing the font color to green.

In the 'Explain' results the // style comments are highlighted in red. The /* */ style are ignored.

The execution plan results are computed even for sections of code that are within comments. 

The actual execution of the query seems to respect both type of comments as you'd expect.

**Comment by vinaypyati** [comment] 2018-05-16 09:52
Hi @davidmw,

Thank you for reporting this. 

I could reproduce this and here is how the _Explain_ looks like for both the styles of comments. 

![image](https://user-images.githubusercontent.com/34657484/40109604-03ab7978-58fe-11e8-8c15-f0cb22f40ed4.png)

Best,

**Comment by Simran-B** [comment] 2018-05-16 10:08
The execution plan does not process the commented parts of the query. The explain output only repeats the query string as-is, including comments. We discussed removing comments from the string before, but it's not straightforward and definitely not a priority.

Regarding syntax highlighting in the Web UI: Query results use the JSON mode for ACE editor, which is correct for actual query results, but not so much for explainer output.

![image](https://user-images.githubusercontent.com/7819991/40109861-b81fff3c-58fe-11e8-8ef7-c9467b6b203a.png)

This could be improved by using AQL mode, which seems to work quite well even though most of the output isn't AQL:

![image](https://user-images.githubusercontent.com/7819991/40109923-e9f4a260-58fe-11e8-865c-1b8bcd19a886.png)

You can test this for the currently visible output editors in devtools with

`Array.from(document.querySelectorAll("[id^=outputEditor].ace_editor")).filter(elem => elem.parentElement.querySelector(".toolbarType").textContent == "Explain").forEach(elem => ace.edit(elem).getSession().setMode("ace/mode/json"))`

**Comment by Simran-B** [comment] 2018-05-16 10:18
PR for devel: https://github.com/arangodb/arangodb/pull/5366

**Comment by davidmw** [comment] 2018-05-16 10:44
<img width="1147" alt="screen shot 2018-05-16 at 10 40 02 pm" src="https://user-images.githubusercontent.com/3413901/40112470-278d7178-595a-11e8-98d6-9487e3f3aae1.png">

The execution plan for the traversal in comments certainly looks processed here and the estimate is way off.

**Comment by davidmw** [comment] 2018-05-23 04:38
Many thanks for painting the picture that I needed - very helpful!

**Comment by Simran-B** [comment] 2018-05-23 15:33
PR merged in devel to use AQL syntax highlighting, which will make the explain output more readable in general and color comments as seen in the query editor. This fixes the visual problem. The entire query string will still be sent to the server, including any comments. The entire string goes through the lexer, but commented code is "eaten". We don't intent to remove commented code on the client side before sending it.

**Comment by vinaypyati** [comment] 2018-09-07 11:53
Hi @davidmw,

version 3.4.0-RC1 has been released, which contains the fix for this problem. Please check it out. 
I will be closing this issue for now. Please comment, if you the issue still persists, and we will reopen it.

Thanks again for reporting this issue.

Best,

**Closed by vinaypyati** 2018-09-07 11:53 UTC
Labels: 1 Bug, 2 Fixed, 3 UI, quality of life
