### ISSUE TITLE
Simple AQL construct for update of embedded array attribute 

### ISSUE THREAD

**Issue by kibarda** [arangodb/arangodb#1663] opened 2016-01-18 17:11 UTC
This is a feature request... 

I want to be able to change 'ext' attribute value of the 2nd items in the following object:

```js
{
  "_id": "1234",
  "purpose": "tree",
  "items": [
    { "name": "list1", "ext": "alpha3" },
    { "name": "list2", "ext": "beta3" },
    { "name": "list3", "ext": "gamma3"
    }
  ],
  "gasp": {
    "ref": "creation1"
  }
}
```

I know there are AQL solutions using SLICE / MERGE  (  as shown here  https://github.com/arangodb/arangodb/issues/1633  and http://stackoverflow.com/questions/29105660/arangodb-aql-update-single-object-in-embedded-array )

In a future version of ArangoDB,  I'd like to have access to a more _simple_  AQL construct
maybe something like

```js
FOR p in myCollection
FILTER p._key=='1234'
UPDATE p.items[2] with {ext:"beta4"} in myCollection
```

Regards,

**Comment by pluma** [comment] 2016-08-16 13:29
This sounds like a duplicate of https://github.com/arangodb/arangodb/issues/1639

**Comment by dothebart** [comment] 2020-07-20 11:37
with 3.7 there will be replace_nth : https://www.arangodb.com/docs/devel/aql/functions-array.html#replace_nth

**Closed by dothebart** 2020-07-20 11:37 UTC
Labels: 1 Feature, 3 AQL
