### ISSUE TITLE
ArangoError: _templateObject is not defined

### ISSUE THREAD

**Issue by nireak** [arangodb/arangodb#3142] opened 2017-08-25 17:44 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x ] 3.2 (3.2.1)
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

When creating the "action" string for a transaction (db._executeTransaction) if I try to use the aql template string:
```javascript
const db = require('@arangodb').db
const aql = require('@arangodb').aql
const result = db._query(aql`FOR u in users RETURN u._key`).toArray()
return result
```
I get the ArangoError: _templateObject is not defined
I can confirm that debugging the code: this sentence of code is translated into
```javascript
var result = db._query(aql(_templateObject)).toArray();
```
Note: if I try to predefine previously the var _templateObject...the code changes to a new undefined _templateObject2.

If I don't use the aql template 
```javascript
const result = db._query('FOR u in users RETURN u._key').toArray()
```
...everything goes ok

Am I using the aql template string in a wrong way? Thank you.

**Comment by jsteemann** [comment] 2017-08-28 06:54
What is the exact command you used to execute the query, and where did you execute it from?
I tried
```js
db._executeTransaction({ collections: { read: "users" }, action: function() { const db = require('@arangodb').db; const aql = require('@arangodb').aql; const result = db._query(aql`FOR u in users RETURN u._key`).toArray(); return result; } });
```
from both the ArangoShell and the server console and was not able to reproduce the error. I tried single server and cluster setups.

**Comment by nireak** [comment] 2017-08-28 18:08
Hi @jsteemann ... I've tried to execute it from a node.js class.

The simplified code woudl be:

```javascript
 import {Database} from 'arangojs'

  const stringAction = String(function (params) {
    // This code will be executed inside ArangoDB!
    const db = require('@arangodb').db
    const aql = require('@arangodb').aql
    const result = db._query(aql`FOR u in users RETURN u._key`).toArray()
    return result
  })

  export class Users {
    constructor (db) {
      this.db = new Database()
    }
    getUsers = async () => {
      ...
      const result = await this.db.transaction(
        {write: ['users']},
        stringAction,
        {...}
      )
      console.log(result)
      ...
    }
  }
```

Thank you

**Comment by janhartmann** [comment] 2018-04-02 15:08
I am having the same issue, @nireak did you solve this?

**Comment by janhartmann** [comment] 2018-04-03 03:43
Hi @nireak 
Thank you for your quick response! I have not yet looked into Foxx (still completely new to ArangoDB), but I will put it on my reading list for sure.

However, I managed to get the code to work by not using ES6 string interpolation or `_aql` but just rely on standard  `bindVars` argument:

```js
const action = String(params => {
            // This code will be executed inside ArangoDB!
            const _db = require("@arangodb").db;
            return _db
                ._query(
                    `FOR day IN @days 
                        INSERT { 
                            project: ( 
                                FOR project IN projects 
                                FILTER project._id == @projectId 
                                RETURN project 
                            ), 
                            category: ( 
                                FOR category IN categories 
                                FILTER category._id == @categoryId 
                                RETURN category 
                            ), 
                            day: day, 
                            estimate: @estimate, 
                            minutes: @minutes, 
                            comment: @comment, 
                            status: @status, 
                            inserted: DATE_ISO8601(DATE_NOW()), 
                            updated: DATE_ISO8601(DATE_NOW()) 
                        } 
                        IN tasks 
                        RETURN NEW`,
                    {
                        days: params.task.days,
                        projectId: params.task.projectId,
                        categoryId: params.task.categoryId,
                        estimate: params.task.estimate,
                        minutes: params.task.minutes,
                        comment: params.task.comment,
                        status: params.task.status
                    }
                )
                .toArray();
        });
```

**Comment by nireak** [comment] 2018-04-03 07:12
Hi @janhartmann  glad to hear you managed to get it working, although not with aql.

I'm sure you'll love Foxx services! :)

**Comment by OmarAyo** [comment] 2018-06-19 09:50
Hi @nireak &  @janhartmann 

Just sending a quick followup - how things are going with this ticket? 

Should we go ahead and close it, or you prefer to leave it open for now?

Best,

**Comment by nireak** [comment] 2018-06-19 18:27
Hi @OmarAyo 
I ended up using a different strategy and I made no further testings with this ticket.
In my case, you can close it.
Thank you

**Comment by OmarAyo** [comment] 2018-06-20 08:19
Hi @nireak 

I am going ahead and close this, please note that tickets can be reopened at any time by adding a new comment

Best,

**Closed by OmarAyo** 2018-06-20 08:19 UTC
Labels: 1 Question, 3 Arangojs, Waiting User Reply
