### ISSUE TITLE
Allocation failed - process out of memory

### ISSUE THREAD

**Issue by koorukuroo** [arangodb/arangodb#1971] opened 2016-07-29 05:34 UTC
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [x] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:
### this is an AQL-related issue:

[x] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:  HTTP API
- [ ] arangosh
- [ ] this Driver:

When I run the traversal HTTP,

Arangod automatically killed with below message 'out of memory'.
But my machine has a fluent available memory.

```
2016-07-29T05:29:55Z [25683] INFO using endpoint 'http+tcp://127.0.0.1:8529' for non-encrypted requests
2016-07-29T05:29:55Z [25683] INFO Authentication is turned off
2016-07-29T05:29:57Z [25683] INFO ArangoDB (version 3.0.3 [linux]) is ready for business. Have fun!

<--- Last few GCs --->

  180014 ms: Mark-sweep 1381.2 (1435.0) -> 1381.2 (1435.0) MB, 1196.7 / 0 ms (+ 0.5 ms in 1 steps since start of marking, biggest step 0.5 ms) [allocation failure] [GC in old space requested].
  181096 ms: Mark-sweep 1381.2 (1435.0) -> 1381.2 (1435.0) MB, 1081.2 / 0 ms [allocation failure] [GC in old space requested].
  182143 ms: Mark-sweep 1381.2 (1435.0) -> 1381.2 (1435.0) MB, 1047.7 / 0 ms [last resort gc].
  183132 ms: Mark-sweep 1381.2 (1435.0) -> 1381.2 (1435.0) MB, 988.7 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3e534343fcd9 <JS Object>
    1: clone [/usr/share/arangodb3/js/common/modules/@arangodb/graph/traversal.js:~70] [pc=0x38f99dfb4839] (this=0x392255c3f2b9 <JS Global Object>,obj=0x14ce368c3cd9 <String[8]: 12295287>)
    2: /* anonymous */ [/usr/share/arangodb3/js/common/modules/@arangodb/graph/traversal.js:85] [pc=0x38f99dffbbda] (this=0x392255c3f2b9 <JS Global Object>,k=0x392255c40869 <String[4]: _rev>)
    3: arguments...


#
# Fatal error in CALL_AND_RETRY_LAST
# Allocation failed - process out of memory
#

```

```
2016-07-29T05:27:23Z [25440] INFO using endpoint 'http+tcp://127.0.0.1:8529' for non-encrypted requests
2016-07-29T05:27:23Z [25440] INFO Authentication is turned off
2016-07-29T05:27:25Z [25440] INFO ArangoDB (version 3.0.3 [linux]) is ready for business. Have fun!

<--- Last few GCs --->

   49507 ms: Mark-sweep 1386.1 (1435.0) -> 1385.9 (1435.0) MB, 1157.5 / 0 ms [allocation failure] [GC in old space requested].
   50658 ms: Mark-sweep 1385.9 (1435.0) -> 1385.7 (1435.0) MB, 1151.6 / 0 ms [allocation failure] [GC in old space requested].
   51792 ms: Mark-sweep 1385.7 (1435.0) -> 1385.7 (1435.0) MB, 1133.9 / 0 ms [last resort gc].
   52899 ms: Mark-sweep 1385.7 (1435.0) -> 1385.7 (1435.0) MB, 1106.4 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2c8b4733fcd9 <JS Object>
    1: /* anonymous */ [/usr/share/arangodb3/js/common/modules/@arangodb/graph/traversal.js:948] [pc=0x2e3a814fc87e] (this=0x2afa9642f519 <JS Global Object>,item=0x11a143658901 <an Object with map 0x194d0a7d07c9>)
    2: arguments adaptor frame: 3->1
    3: InnerArrayForEach(aka InnerArrayForEach) [native array.js:~946] [pc=0x2e3a8190687f] (this=0x2c8b47304139 <undefined>,br=0x1a74c4aba4e9 <JS ...


#
# Fatal error in CALL_AND_RETRY_LAST
# Allocation failed - process out of memory
#

```

**Comment by dothebart** [comment] 2016-07-29 09:15
Hi, 
the problem is, that whatever you're currently doing you're using V8; 
V8 has internal resource allocation mechanisms that sometimes fail long before the systems available memory is exhausted.

The last time we saw this was a user errnously feeding a collection into an AQL function like this:

      db._query("FOR x IN somecollection FILTER COUNT(somecollection) > 5 RETURN x")

This will for each iteration of a document of `somecollection` map the complete collection into V8 javascript for the function call to `COUNT()` - and if `somecollection` has some 100k documents it will abort with similar errors.

Next versions of ArangoDB may prohibit putting collections into function arguments to circumvent these sorts of errors.

**Comment by Simran-B** [comment] 2016-08-04 14:01
@dothebart: `COUNT(somecollection)` is actually special and optimized away, even with `{optimizer: {rules: ["-all"]} }`. It shows as `COLLECTION_COUNT(somecollection)` in the explainer output and no warning like "collection ... used as expression operand" is issued. `NOOPT(COUNT(...))` prevents this optimization and the warning is returned.

**Comment by jsteemann** [comment] 2016-11-17 08:37
The original problem seemed to have occurred during a graph traversal and not AQL, as indicated by the following line from the stack trace:
```
[/usr/share/arangodb3/js/common/modules/@arangodb/graph/traversal.js:948]
```
The error is thrown when V8 runs out of memory during JavaScript execution. If it cannot get any more memory, it fails hard.

3.1 should mitigate this problem, so it may be worth trying it. Additionally it is possible to start ArangoDB with a special options that allows V8 to use more memory. This is described [here](https://github.com/arangodb/arangodb/issues/2141#issuecomment-258184178).

**Comment by baslr** [comment] 2017-02-09 17:16
@koorukuroo did you tried it with ArangoDB version 3.1?

**Comment by dothebart** [comment] 2017-03-29 12:43
Meanwhile ArangoDB 3.1.16 is available for download - Closing.

**Closed by dothebart** 2017-03-29 12:43 UTC
Labels: 1_Bug, graph
