### ISSUE TITLE
AQL unexpected LENGTH(null) = 4

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#1311] opened 2015-04-14 14:33 UTC
So today we stumbled upon this, when evaluating why some statistics are not right.

The full example is something like:
````
FOR c IN customers
    FILTER LENGTH(c.preferences.size) > 0
    RETURN c
````

This will also return all the customers that don't have the property `size` defined in preferences, probably because the returned length is 4.

**Comment by CoDEmanX** [comment] 2015-04-14 15:08
Duplicate of https://github.com/arangodb/arangodb/issues/1231

**Closed** 2015-04-14 15:27 UTC
