### ISSUE TITLE
Segfault during init on docker swarm cluster

### ISSUE THREAD

**Issue by crubier** [arangodb/arangodb#3074] opened 2017-08-18 13:51 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [x] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

When starting arango in a cluster, I get a segfault on init. Here is the console output:

```
automaticaly choosing storage engine
Initializing root user...Hang on...
/entrypoint.sh: line 141:    10 Segmentation fault      ARANGODB_DEFAULT_ROOT_PASSWORD="$ARANGO_ROOT_PASSWORD" /usr/sbin/arango-init-database
Initializing database...Hang on...
/entrypoint.sh: line 141:    12 Segmentation fault      arangod --server.endpoint unix:///tmp/arangodb-tmp.sock --server.authentication false --log.file /tmp/init-log --log.foreground-tty false
ArangoDB didn't start correctly during init
2017-08-18T13:40:55Z [12] INFO ArangoDB 3.2.1 [linux] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.0.0, OpenSSL 1.0.1t  3 May 2016
```

Here is the dockerfile to reproduce this error:

```yml
version: '3'

networks:
  front:
    driver: overlay
  back:
    driver: overlay

services:
  arango-agent-1:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.endpoint tcp://0.0.0.0:5001
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --agency.my-address=tcp://arango-agent-1:5001
      --agency.size 3
      --agency.endpoint tcp://arango-agent-1:5001
      --agency.supervision true
      --agency.activate true
      --foxx.queues false
      --server.statistics false
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango1/agent:/var/lib/arangodb3
    networks:
      - back

  arango-agent-2:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.endpoint tcp://0.0.0.0:5002
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --agency.my-address=tcp://arango-agent-2:5002
      --agency.size 3
      --agency.endpoint tcp://arango-agent-1:5001
      --agency.supervision true
      --agency.activate true
      --foxx.queues false
      --server.statistics false
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango2/agent:/var/lib/arangodb3
    depends_on:
      - arango-agent-1
    networks:
      - back

  arango-agent-3:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.endpoint tcp://0.0.0.0:5003
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --agency.my-address=tcp://arango-agent-3:5003
      --agency.size 3
      --agency.endpoint tcp://arango-agent-1:5001
      --agency.supervision true
      --agency.activate true
      --foxx.queues false
      --server.statistics false
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango3/agent:/var/lib/arangodb3
    depends_on:
      - arango-agent-1
      - arango-agent-2
    networks:
      - back

  arango-db-1:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --server.endpoint tcp://0.0.0.0:8529
      --cluster.my-address tcp://arango-db-1:8529
      --cluster.my-local-info db1
      --cluster.my-role PRIMARY
      --cluster.agency-endpoint tcp://arango-agent-1:5001
      --cluster.agency-endpoint tcp://arango-agent-2:5002
      --cluster.agency-endpoint tcp://arango-agent-3:5003
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango1/db:/var/lib/arangodb3
    depends_on:
      - arango-agent-1
      - arango-agent-2
      - arango-agent-3
    networks:
      - back

  arango-db-2:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --server.endpoint tcp://0.0.0.0:8529
      --cluster.my-address tcp://arango-db-2:8529
      --cluster.my-local-info db2
      --cluster.my-role PRIMARY
      --cluster.agency-endpoint tcp://arango-agent-1:5001
      --cluster.agency-endpoint tcp://arango-agent-2:5002
      --cluster.agency-endpoint tcp://arango-agent-3:5003
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango2/db:/var/lib/arangodb3
    depends_on:
      - arango-agent-1
      - arango-agent-2
      - arango-agent-3
    networks:
      - back

  arango-db-3:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --server.endpoint tcp://0.0.0.0:8529
      --cluster.my-address tcp://arango-db-3:8529
      --cluster.my-local-info db3
      --cluster.my-role PRIMARY
      --cluster.agency-endpoint tcp://arango-agent-1:5001
      --cluster.agency-endpoint tcp://arango-agent-2:5002
      --cluster.agency-endpoint tcp://arango-agent-3:5003
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango3/db:/var/lib/arangodb3
    depends_on:
      - arango-agent-1
      - arango-agent-2
      - arango-agent-3
    networks:
      - back

  arango-coord-1:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --server.endpoint tcp://0.0.0.0:8529
      --cluster.my-address tcp://arango-coord-1:8529
      --cluster.my-local-info coord1
      --cluster.my-role COORDINATOR
      --cluster.agency-endpoint tcp://arango-agent-1:5001
      --cluster.agency-endpoint tcp://arango-agent-2:5002
      --cluster.agency-endpoint tcp://arango-agent-3:5003
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango1/coord:/var/lib/arangodb3
      - ${DOCKER_VOLUME_MNT}/arango1/apps:/var/lib/arangodb3-apps
    depends_on:
      - arango-agent-1
      - arango-agent-2
      - arango-agent-3
    networks:
      - back
      - front
    ports:
      - 8001:8529

  arango-coord-2:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --server.endpoint tcp://0.0.0.0:8529
      --cluster.my-address tcp://arango-coord-2:8529
      --cluster.my-local-info coord2
      --cluster.my-role COORDINATOR
      --cluster.agency-endpoint tcp://arango-agent-1:5001
      --cluster.agency-endpoint tcp://arango-agent-2:5002
      --cluster.agency-endpoint tcp://arango-agent-3:5003
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango2/coord:/var/lib/arangodb3
      - ${DOCKER_VOLUME_MNT}/arango2/apps:/var/lib/arangodb3-apps
    depends_on:
      - arango-agent-1
      - arango-agent-2
      - arango-agent-3
    networks:
      - back
      - front
    ports:
      - 8002:8529

  arango-coord-3:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --server.endpoint tcp://0.0.0.0:8529
      --cluster.my-address tcp://arango-coord-3:8529
      --cluster.my-local-info coord3
      --cluster.my-role COORDINATOR
      --cluster.agency-endpoint tcp://arango-agent-1:5001
      --cluster.agency-endpoint tcp://arango-agent-2:5002
      --cluster.agency-endpoint tcp://arango-agent-3:5003
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango3/coord:/var/lib/arangodb3
      - ${DOCKER_VOLUME_MNT}/arango3/apps:/var/lib/arangodb3-apps
    depends_on:
      - arango-agent-1
      - arango-agent-2
      - arango-agent-3
    networks:
      - back
      - front
    ports:
      - 8003:8529
```

And a little script to create necessary folders 

```bash
#!/usr/bin/env bash

rm -rf $DOCKER_VOLUME_MNT/arango1
rm -rf $DOCKER_VOLUME_MNT/arango2
rm -rf $DOCKER_VOLUME_MNT/arango3

mkdir $DOCKER_VOLUME_MNT/arango1
mkdir $DOCKER_VOLUME_MNT/arango2
mkdir $DOCKER_VOLUME_MNT/arango3
mkdir $DOCKER_VOLUME_MNT/arango1/agent
mkdir $DOCKER_VOLUME_MNT/arango2/agent
mkdir $DOCKER_VOLUME_MNT/arango3/agent
mkdir $DOCKER_VOLUME_MNT/arango1/coord
mkdir $DOCKER_VOLUME_MNT/arango2/coord
mkdir $DOCKER_VOLUME_MNT/arango3/coord
mkdir $DOCKER_VOLUME_MNT/arango1/db
mkdir $DOCKER_VOLUME_MNT/arango2/db
mkdir $DOCKER_VOLUME_MNT/arango3/db
mkdir $DOCKER_VOLUME_MNT/arango1/apps
mkdir $DOCKER_VOLUME_MNT/arango2/apps
mkdir $DOCKER_VOLUME_MNT/arango3/apps

echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango1/agent/ENGINE
echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango1/coord/ENGINE
echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango1/db/ENGINE
echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango2/agent/ENGINE
echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango2/coord/ENGINE
echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango2/db/ENGINE
echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango3/agent/ENGINE
echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango3/coord/ENGINE
echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango3/db/ENGINE
```

**Comment by crubier** [comment] 2017-08-18 13:53
This bug happens when running on `Docker version 17.07.0-ce-rc2, build 36ce605` 
Both on a MacOS host, and on a ubuntu host.

**Comment by dothebart** [comment] 2017-08-21 10:03
Ok, not having done much with docker swarm yet I tried to get this running locally. 

I've installed the latest docker-compose from: https://github.com/docker/compose/releases

which then would work with the yml file. However during startup I get:

```
 /usr/local/bin/docker-compose -f ./dockerfile.yml  up 
WARNING: Some services (arango-agent-1, arango-agent-2, arango-agent-3, arango-coord-1, arango-coord-2, arango-coord-3, arango-db-1, arango-db-2, arango-db-3) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "willi_front" with driver "overlay"
Creating network "willi_back" with driver "overlay"
Creating willi_arango-agent-1_1 ... 
Creating willi_arango-agent-1_1 ... done
Creating willi_arango-agent-2_1 ... 
Creating willi_arango-agent-2_1 ... done
Creating willi_arango-agent-3_1 ... 
Creating willi_arango-agent-3_1 ... done
Creating willi_arango-db-3_1 ... 
Creating willi_arango-coord-2_1 ... 
Creating willi_arango-db-1_1 ... 
Creating willi_arango-db-3_1
Creating willi_arango-coord-3_1 ... 
Creating willi_arango-db-2_1 ... 
Creating willi_arango-db-1_1
Creating willi_arango-coord-1_1 ... 
Creating willi_arango-db-2_1
Creating willi_arango-coord-2_1
Creating willi_arango-coord-1_1
Creating willi_arango-coord-1_1 ... error

ERROR: for willi_arango-coord-1_1  Cannot start service arango-coord-1: container 22911deb00f06359498d272bb681ed1e2f5771d966c4cb623edd12ba300ac86d: endpoint join on GW Network failed: driver failed programming external connectivity on endpoint gateway_22911deb00f0 (a56c72628a2c29e9fec4bf5b9c775c309f4b163792dd2c2332b1fCreating willi_arango-coord-2_1 ... done

ERROR: for arango-coord-1  Cannot start service arango-coord-1: container 22911deb00f06359498d272bb681ed1e2f5771d966c4cb623edd12ba300ac86d: endpoint join on GW Network failed: driver failed programming external connectivity on endpoint gateway_22911deb00f0 (a56c72628a2c29e9fec4bf5b9c775c309f4b163792dd2c2332b1fd85e7a5d4a7): Bind for 0.0.0.0:8001 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

When issuing ` /usr/local/bin/docker-compose -f ./dockerfile.yml  down` I see its stopping the services in a random order, which should rather happen along the lines of https://github.com/arangodb/arangodb/blob/devel/scripts/shutdownLocalCluster.sh

Do you have any chance of creating core dumps for these issues?

**Comment by dothebart** [comment] 2017-08-21 13:10
ok, Following https://superuser.com/questions/302754/increase-the-maximum-number-of-open-file-descriptors-in-snow-leopard worked to increase the number of fd's, now inserting works flawlessly. 

Running the 3.2 on that database directory will give the typical message: ```
2017-08-21T13:08:06Z [47126] INFO ArangoDB 3.2.1 [darwin] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.0.0, OpenSSL 1.0.2k  26 Jan 2017
2017-08-21T13:08:06Z [47126] INFO using storage engine mmfiles
2017-08-21T13:08:06Z [47126] INFO {cluster} Starting up with role SINGLE
2017-08-21T13:08:06Z [47126] INFO {syscall} file-descriptors (nofiles) hard limit is 1000000, soft limit is 1000000
2017-08-21T13:08:06Z [47126] INFO Authentication is turned on (system only), authentication for unix sockets is turned on
2017-08-21T13:08:07Z [47126] ERROR In database '_system': Database directory version (30127) is lower than current version (30201).
2017-08-21T13:08:07Z [47126] ERROR In database '_system': ----------------------------------------------------------------------
2017-08-21T13:08:07Z [47126] ERROR In database '_system': It seems like you have upgraded the ArangoDB binary.
2017-08-21T13:08:07Z [47126] ERROR In database '_system': If this is what you wanted to do, please restart with the
2017-08-21T13:08:07Z [47126] ERROR In database '_system':   --database.auto-upgrade true
2017-08-21T13:08:07Z [47126] ERROR In database '_system': option to upgrade the data in the database directory.
2017-08-21T13:08:07Z [47126] ERROR In database '_system': Normally you can use the control script to upgrade your database
2017-08-21T13:08:07Z [47126] ERROR In database '_system':   /etc/init.d/arangodb stop
2017-08-21T13:08:07Z [47126] ERROR In database '_system':   /etc/init.d/arangodb upgrade
2017-08-21T13:08:07Z [47126] ERROR In database '_system':   /etc/init.d/arangodb start
2017-08-21T13:08:07Z [47126] ERROR In database '_system': ----------------------------------------------------------------------
2017-08-21T13:08:07Z [47126] FATAL Database '_system' needs upgrade. Please start the server with the --database.auto-upgrade option
2017-08-21T13:08:07Z [47126] FATAL Database '_system' upgrade failed. Please inspect the logs from the upgrade procedure
```

And after an upgrade of the database everything is working fine.

**Comment by dothebart** [comment] 2017-08-31 14:09
Hi, 
Any news on this? or can we close it?

**Comment by crubier** [comment] 2017-09-03 17:34
Hi, I guess we can close it for now as I found a workaround:
In `docker-compose.yml`, I replaced the default command with another command that sets the storage engine in `/etc/arangodb3/arangod.conf` prior to launching arangod. Instead of the above `command` fields in the `docker-compose.yml`, I now use:

```
  command: bash -c "
      sed -i '/storage-engine = auto/c\storage-engine = $ARANGO_STORAGE_ENGINE' /etc/arangodb3/arangod.conf ;
      arangod \
      --server.endpoint tcp://0.0.0.0:5001 \
      --server.authentication true \
      --server.jwt-secret ${ARANGO_JWT_SECRET} \
      --agency.my-address=tcp://arango-agent-1:5001 \
      --agency.size 3 \
      --agency.endpoint tcp://arango-agent-1:5001 \
      --agency.supervision true \
      --agency.activate true \
      --foxx.queues false \
      --server.statistics false \
      --server.storage-engine ${ARANGO_STORAGE_ENGINE}"
```

**Comment by dothebart** [comment] 2017-09-04 09:42
Ok, so the problem is to override the storage engine from the commandline? Do you derive our container for that?

**Comment by dothebart** [comment] 2017-11-23 15:22
Ok, 
please note that 3.2.8 containing many cluster bugfixes is available - closing now.

**Closed by dothebart** 2017-11-23 15:22 UTC
Labels: 3 Cluster
