### ISSUE TITLE
Arangod wont start the database

### ISSUE THREAD

**Issue by matt24smith** [arangodb/arangodb#2385] opened 2017-03-21 12:31 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [X ] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [X] Windows, version:  7
- [ ] MacOS, version:

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

When I run ArangoDB from command line `arangod testDB` the database does not start. Instead, i get the output

    2017-03-21T12:29:49Z [2720] INFO ArangoDB 3.1.14 [win64] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.2a 19 Mar 2015
    2017-03-21T12:29:49Z [2720] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
    2017-03-21T12:29:49Z [2720] INFO Starting up with role SINGLE
    2017-03-21T12:29:49Z [2720] INFO Authentication is turned on
    2017-03-21T12:29:49Z [2720] INFO Authentication system only

and the program terminates. This seems to be reoccurring when I perform operations with arangoimp. The first time this happened, I had run arangoimp without having the database running. The second time this happened, arangoimp had frozen and I terminated it. The DB froze, and when I tried to restart it, I found that I could not. 

Instead I would be expecting: 
The database to run

**Comment by jsteemann** [comment] 2017-03-21 12:43
This may be a duplicate of https://github.com/arangodb/arangodb/issues/2376?
Can you re-try with 3.1.15?

**Comment by matt24smith** [comment] 2017-03-21 12:48
Yes, I will do some testing today and report back if the error reoccurs

**Comment by matt24smith** [comment] 2017-03-21 15:52
I cannot reproduce the error on 3.1.15. looks like it fixed it. Thanks!

**Comment by dothebart** [comment] 2017-03-21 16:12
okies, marking as closed then.

**Closed by dothebart** 2017-03-21 16:12 UTC
