### ISSUE TITLE
ArangoError: unique constraint violated on Edge Collection Save

### ISSUE THREAD

**Issue by seansilvestri** [arangodb/arangodb#5811] opened 2018-07-09 18:33 UTC
## My Environment

* __ArangoDB Version__:        3.3.9
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Configuration__:               Arango Helper
* __Infrastructure__:               own
* __Operating System__:        Centos 7.4
* __Used Package__:              arangodb3-3.3.9-1.x86_64.rpm (Centos)

My logging picked up an occurrence of the below error. Its a very simple insert into an edge collection but the _key that was autogenerated already existed in that collection.

Details: Save in an edge collection via a FOXX app.

Error: ArangoError: unique constraint violated - in index 0 of type primary over [“_key”]; conflicting key: 13647205

Arangodb version: 3.3.9 using RocksDB

**Comment by seansilvestri** [comment] 2018-07-10 19:07
Unfortunately, I'm only seeing the error that my FOXX app generated which only included the description of the Arrango level error. 

I'm noticing that all the files in the dbserver directory contain text similar to:

2018-07-10T00:55:10Z [28621] INFO hangup received, about to reopen logfile 
2018-07-10T00:55:10Z [28621] INFO hangup received, reopened logfile 

(I'm using the arango helper for my cluster)

**Comment by seansilvestri** [comment] 2018-07-11 17:36
I'm seeing this error again. Is there any info I can provide?

**Comment by seansilvestri** [comment] 2018-07-11 17:45
I had not seen this error prior to my upgrade to 3.3.9. Before that I was on 3.2.10. Please advise.

**Comment by Simran-B** [comment] 2018-07-11 18:41
Maybe `--log.level queries=trace` helps to track down what query causes this?

**Comment by OmarAyo** [comment] 2018-07-13 11:08
Hi @seansilvestri 

Just sending a quick followup - Did you try the option that Simaran provided you? 
Could you please attach all your logs from each node ?

Thanks,

**Comment by seansilvestri** [comment] 2018-07-13 16:34
I tested out the log.level queries=trace in another environment first and am enabling it now on my production servers.
I will then have to wait for the issue to occur...

**Comment by seansilvestri** [comment] 2018-07-13 16:59
Below are the spots in the code where I'm creating the edge document where the error has occurred. It has occurred 4 times in the last 6 weeks and I've not seen it prior to 3.3.9.
The error happens on the .save line every time...

--- occurance 1
 // Create company/user edge relation
        let companyUserEdge = {};
        companyUserEdge._from = user._id;
        companyUserEdge._to = company._id;
        relations.save(companyUserEdge);

--- occurrance 2
// Create user/feature edge relation
    let userFeatureEdge = {};
    userFeatureEdge._from = constants.USER_COLLECTION + '/' + userId;
    userFeatureEdge._to = constants.FEATURE_COLLECTION + '/' + featureId;
    relations.save(userFeatureEdge);

--- occurrance 3
 let userRoleEdge = {};
    userRoleEdge._from = constants.USER_COLLECTION + '/' + userId;
    userRoleEdge._to = constants.ROLE_COLLECTION + '/' + util.prepareAndExecuteQuery(queries.getRoleKeyByName,
        [roleId.toUpperCase(), prodTypeKey])[0]._key;
    if (deleteLink) {
        let s = relations.byExample(userRoleEdge).toArray();
        if (s.length !== 0) {
            relations.remove(s[0]._key);
        }
    } else {
        relations.save(userRoleEdge);
    }

**Comment by seansilvestri** [comment] 2018-07-13 17:00
Did you need any meta data on the collection? its an edge collection with 2 shards and replication factor of 3.

**Comment by Simran-B** [comment] 2018-07-17 13:36
Can you post the definitions of `constants` and `util`?

**Comment by seansilvestri** [comment] 2018-07-17 18:12
I had the error occur. What would I be looking for in the trace file?
I grepped it for 'error' and have found no occurrences...

**Comment by seansilvestri** [comment] 2018-08-01 14:59
Have you had a chance to review my logs? this is happening about once a day now.

**Comment by seansilvestri** [comment] 2018-08-01 15:00
I've upgraded to 3.3.12 and am still seeing the issue.

**Comment by seansilvestri** [comment] 2018-08-03 17:36
This is happening in our system about once daily and we really need some assistance on the issue. We are not in the position to be able to fix data every day and thus would have to consider other options outside of arangodb if we can't figure out what is going on :(

**Comment by Simran-B** [comment] 2018-08-14 15:30
The development team identified possible causes of the problem, which should all be fixed in the upcoming 3.3.14 (should be out by end of this week). Note that existing collections will most likely still be affected, which means you need to re-create them (dump/restore). It will fix possible sharding faults.

**Comment by Simran-B** [comment] 2018-08-15 23:54
Intermediate commits committing transactions in the middle and forgetting about what they did before could be a possible cause, or data getting erroneously distributed to all or wrong shards. The normal upgrade procedure followed by dump & restore of the affected collections should fix it.

**Comment by seansilvestri** [comment] 2018-08-22 17:11
I wanted to validate that this issue is fixed in 3.3.14 prior to upgrading my Production environment. I did not see anything that looked similar in the change log for 3.3.14.
thanks!

**Comment by jsteemann** [comment] 2018-08-22 18:55
@seansilvestri : it should be [this one](https://github.com/arangodb/arangodb/blob/v3.3.14/CHANGELOG#L37)

> intermediate commits in the RocksDB engine are now only enabled in standalone AQL 
> queries (not within a JS transaction), standalone truncate as well as for the 
> "import" API

At least that is what we suspect has created the issue. We have seen issues after intermediate commits, with the constraints on the collection partly being ignored. This could have caused duplicate entries on insert/update/replace in case of big transactions (containing many operations or huge documents).

**Comment by sleto-it** [comment] 2018-10-12 17:57
Hi @seansilvestri ,

have you had a chance to upgrade and restore from a dump - is this issue still happening to you?

please let us know how things are going

thanks,

**Comment by vinaypyati** [comment] 2018-10-19 15:03
Hi @seansilvestri,

Just sending a quick follow up. How things are going? Did you have a chance to upgrade and restore the dump? 

Thanks for your feedback!

**Comment by maxkernbach** [comment] 2018-10-22 12:28
Since there was no feedback in a while, I am closing this issue for now.

In case the fix, which is included in versions 3.3.14+, did not resolve your problem please feel free to reopen the issue by adding a new comment.

**Comment by seansilvestri** [comment] 2018-10-25 17:12
Unfortunately I was on holiday and only updated the production server 2
days ago. The issue is still there. Could you re-open the issue?

**Comment by dothebart** [comment] 2018-10-26 09:09
Hi, to continue on this, you probably upgraded to 3.3.19? or did that just got released meanwhile?

Can you provide a copy of your database, and a test howto reproduce?

**Comment by Simran-B** [comment] 2018-12-05 12:38
Hi @seansilvestri,

did you dump the affected collections, upgrade to 3.3.19 and restore the data?  Upgrading the binaries only may not suffice in this case, as the persisted index data could be corrupted because of previous issues with intermediate commits.

**Comment by vinaypyati** [comment] 2019-01-03 12:17
Hi @seansilvestri,

Did you have a chance to read what Simran-B wrote above? Does the issue still show up for you? If so, can you please share us a copy of your database and a test that can reproduce it? 

Thanks!

**Comment by juchoe** [comment] 2019-01-09 19:21
Hello, I took over seansilvestri's project (he moved on to another) and should be able to participate in the discussion on his behalf. We always use dump & restore whenever we create a new cluster or upgrade our arangoDB version. So, yes, we did this as well when we last upgraded our arangoDB version to 3.3.14. We also tried to repro this error on our non-production environment with heavy concurrent workloads but was not successful. On our next test, I'm considering restoring prod DB dump on nonProd environment and see if it repros. Also, we plan on upgrading to v3.3.21 soon so after that's done I will report back here. Thanks!

**Comment by juchoe** [comment] 2019-02-08 22:50
We just upgraded our prod environment with v3.3.21 last night. We used arangodb dump and restore.  So far so good.

**Comment by juchoe** [comment] 2019-02-11 19:32
The error just occurred on our prod environment. Upgrading to v3.3.21 did not resolve the issue.
`ArangoError: unique constraint violated - in index 0 of type primary over ["_key"]; conflicting key: 75744`

**Comment by juchoe** [comment] 2019-05-09 14:33
Last night, we observed our very first incident where all 5 retry attempts failed. We are still on 3.3.21.
`May 8th 2019, 22:10:12.940	unique constraint violated - in index 0 of type primary over ["_key"]; conflicting key: 13530946
May 8th 2019, 22:10:11.939	unique constraint violated - in index 0 of type primary over ["_key"]; conflicting key: 13530945
May 8th 2019, 22:10:10.938	unique constraint violated - in index 0 of type primary over ["_key"]; conflicting key: 13530944
May 8th 2019, 22:10:09.937	unique constraint violated - in index 0 of type primary over ["_key"]; conflicting key: 13530943
May 8th 2019, 22:10:08.936	unique constraint violated - in index 0 of type primary over ["_key"]; conflicting key: 13530942
May 8th 2019, 22:10:07.926	unique constraint violated - in index 0 of type primary over ["_key"]; conflicting key: 13530940`

**Comment by swathika** [comment] 2020-03-20 20:38
Hello, I wanted to follow up on the unique constraint violation issue, we get this error more frequently now. I wanted to know if there was any recent upgrade that addresses this issue?

**Comment by Simran-B** [comment] 2020-03-23 08:25
v3.3.25 was released on February 25th and the v3.3 series reached end of life on February 29th. I do not know whether any changes between your version v3.3.21 and the latest one fixes the problem. You should upgrade regardless. Also consider to try a more recent series, see if this is still a problem in e.g. v3.6.x and possibly upgrade. There will be no v3.3.26, so if it's not fixed in the last published version then we can unfortunately not solve this issue in the form of a bugfix for v3.3.

https://www.arangodb.com/eol-notice/

**Comment by dothebart** [comment] 2020-09-02 08:26
closing this with the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) and 3.3 EOLed. 

One Idea since this is(?) a virtualized environment, whether the clock-driver of the OS is set up properly to use the host-os'es physical device.

**Closed by dothebart** 2020-09-02 08:26 UTC
Labels: 1 Bug, 3 Index, 3 RocksDB

**Comment by mathsyouth** [comment] 2020-12-16 10:35
@dothebart  I also wanted to follow up on the unique constraint violation issue. We got this error on ArangoDB 3.6.9. I wanted to know if there is any recent upgrade to fix this bug?

**Comment by dothebart** [comment] 2020-12-16 12:28
Hi, please open a new issue with the complete scenario that you see, and at best with a way to reproduce it.
