### ISSUE TITLE
arangoimp, arangoexport, arangorestore and arango cmd line tools feature support with GCS or s3

### ISSUE THREAD

**Issue by sudarsan005** [arangodb/arangodb#11937] opened 2020-06-23 05:28 UTC
## My Environment

* __ArangoDB Version__:        3.6
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               GCP
* __Used Package__:              Docker

## New Feature Request

Can you please add support to AWS s3 or GCS like support to command line tool arangoimp, arangoexport, arangorestore etc.
Right now we have to store files locally to use command line tools, this feature will be very useful

**Comment by dothebart** [comment] 2020-06-23 08:18
hm, you *do* want these tools to transparently download the files, and upload them again? 
As for arangodump & arangorestore, this is here as part of [Hot Backup](https://www.arangodb.com/2019/10/arangodb-hot-backup-creating-consistent-cluster-wide-snapshots/), so we definitely will not double these features in another set of tools.

**Comment by dothebart** [comment] 2020-06-23 08:23
As for arangoimp, the best way is to simply [mount the s3 volume in a small temporary cloud instance](https://cloud.netapp.com/blog/amazon-s3-as-a-file-system), and run arangoimp there, so your data doesn't travel the net twice - but instead not at all.

**Comment by dothebart** [comment] 2020-09-04 09:03
Closing this, as you can achieve the intended behaviour by readily existing tools. 

Please note [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.

**Closed by dothebart** 2020-09-04 09:03 UTC
Labels: 1 Feature, 3 ImportExport, workaround available
