### ISSUE TITLE
Arango 2.8.0b3 eats up all disk space

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#1662] opened 2016-01-17 00:36 UTC
Nothing special to see, just that the hdd got full in 3 days since we updated our staging server (Wheezy).

here is the proof that space is restored after arango is shut down:

```
root@ay-p-arango2:~# df -h
Filesystem                                              Size  Used Avail Use% Mounted on
rootfs                                                  296G  261G   20G  93% /
udev                                                     10M     0   10M   0% /dev
tmpfs                                                   1.6G  500K  1.6G   1% /run
/dev/disk/by-uuid/bac94e65-77c3-4135-b1a8-2636059d817c  296G  261G   20G  93% /
tmpfs                                                   5.0M     0  5.0M   0% /run/lock
tmpfs                                                   3.2G   12K  3.2G   1% /run/shm
root@ay-p-arango2:~#
root@ay-p-arango2:/# du -sh /
du: cannot access `/proc/93259/task/93259/fd/4': No such file or directory
du: cannot access `/proc/93259/task/93259/fdinfo/4': No such file or directory
du: cannot access `/proc/93259/fd/4': No such file or directory
du: cannot access `/proc/93259/fdinfo/4': No such file or directory
44G	/
root@ay-p-arango2:/#
root@ay-p-arango2:/# service arangodb stop
[ ok ] Stopping arango database server: arangod.
[ ok ] Waiting for shutdown: . . . . . . . done.
root@ay-p-arango2:/# df -h
Filesystem                                              Size  Used Avail Use% Mounted on
rootfs                                                  296G   44G  237G  16% /
udev                                                     10M     0   10M   0% /dev
tmpfs                                                   1.6G  528K  1.6G   1% /run
/dev/disk/by-uuid/bac94e65-77c3-4135-b1a8-2636059d817c  296G   44G  237G  16% /
tmpfs                                                   5.0M     0  5.0M   0% /run/lock
tmpfs                                                   3.2G   12K  3.2G   1% /run/shm
root@ay-p-arango2:/#
```

**Comment by baslr** [comment] 2016-01-17 13:14
Maybe compaction issue? Did you see where the major part is used? `du -d 1 -h /var/lib/arangodb`

**Comment by razvanphp** [comment] 2016-01-17 13:20
The arangodb database folder you indicated had the real size, around 7GB, I was also surprised..

So my guess is he was not really using that much disk space, just maybe not releasing mapped memory files properly.

**Comment by baslr** [comment] 2016-01-17 14:39
But you don't know which particular file grown so big?
Could be already fixed in devel?
```
commit 583bc906260082f58b4bf7348726392aba6963b2
Author: Jan Steemann <jan@arangodb.com>
Date:   Fri Jan 15 16:27:36 2016 +0100

    fixed leak

commit f1b0114e892a89dd5ee524a4b3ac166fab4efb82
Author: Jan Steemann <jan@arangodb.com>
Date:   Thu Jan 14 17:56:57 2016 +0100

    fixed leak

commit e4992ff37a7b6a5f3f62ed735275caa3071e4bfa
Author: jsteemann <jan@arangodb.com>
Date:   Tue Jan 12 00:08:58 2016 +0100

    fixed leak

commit 9eb056b97151850174b6e888214383ab012fb3b2
Author: Max Neunhoeffer <max@arangodb.com>
Date:   Mon Jan 11 10:51:56 2016 +0100

    Fix a memory leak.

commit 625cc51732a87d222dc2adeebd2c48de1c485746
Author: Wilfried Goesgens <willi@arangodb.com>
Date:   Mon Jan 11 10:05:29 2016 +0100

    fix memleak.

commit 2bfe9b26769b0584031761be97a0cf70ca20e6dc
Author: Jan Steemann <jan@arangodb.com>
Date:   Wed Jan 6 13:45:25 2016 +0100

    fixed leak

commit 28d80cf8d4f53a8ffb96ff245c070b86d76a3d80
Author: Jan Steemann <jan@arangodb.com>
Date:   Mon Jan 4 18:37:01 2016 +0100

    fixed shutdown leak
```

**Comment by fceller** [comment] 2016-01-17 16:05
We are currently hunting down a compaction bug. I have to investigate if this is related to the behavior @razvanphp has reported. Unfortunately, this bug is very resilient.

**Comment by ericfiala** [comment] 2016-01-18 23:33
I suspect we have encountered the same problem (arangodb-2.7.3-18.1.x86_64)
It appears that the files are deleted but never closed.

lsof | grep ^arangod | grep DEL   

should show several like these:
arangod   18995 arangodb  DEL       REG              252,1             1059610 /var/lib/arangodb/databases/database-1428191574563/collection-3400318652753/deleted-5571486473711.db
arangod   18995 arangodb  DEL       REG              252,1             1059507 /var/lib/arangodb/databases/database-1428191574563/collection-3400348275025/deleted-5342913945071.db
arangod   18995 arangodb  DEL       REG              252,1             1059502 /var/lib/arangodb/databases/database-1428191574563/collection-3400348275025/deleted-5342913945071.db
arangod   18995 arangodb  DEL       REG              252,1             1059475 /var/lib/arangodb/databases/database-1428191574563/collection-3400318652753/deleted-5428592631279.db

Hence the space is consumed, but files of the corresponding size cannot be found.

**Comment by fceller** [comment] 2016-01-19 10:28
We found at least one bug which fixed the issue in our test-case. I'll create a new beta of 2.8 tonight. There is good chance that it will ride of @razvanphp issue.

**Comment by jsteemann** [comment] 2016-01-19 15:22
A much improved version of the compaction (mainly due to datafile statistics fixes) will be available in 2.8-beta3 (build started today). That should sort out the number of datafiles growing, and the number of live/dead documents in the figures increasing beyond sense. A backport to 2.7 is in the works, too.

That won't cover the DEL files mentioned by @ericfiala however. It seems that some of the datafiles are logically deleted and thus will disappear for commands such as `ls`, but still remain mapped. It seems that this is due to the size of a memory mapping being changed under some circumstances, which will lead to the a memory mapping being unmapped only partly, which then keeps files based on these (partial) mappings lingering around "invisibly". We're currently looking into this as well.

**Comment by jsteemann** [comment] 2016-01-25 14:02
@ericfiala : depending on the OS, there may have been files still being mapped to the arangod process after they have been deleted. This was due to incongruent ranges for mmap/munmap on memory-regions backed by those files. This may have led to small portions of the files still being mapped, meaning their file descriptors were potentially not released to the OS when the files were deleted after compaction.
This has been fixed in 2.7.5 and in 2.8.0 directly *after* beta8 was created.

Together with the fix for #1596, this should fix the problem of using much disk space.

**Comment by ericfiala** [comment] 2016-02-07 20:17
@jsteemann - looks like the problem I reported in this thread is gone with arangodb-2.7.6-21.1.x86_64 
DEL files are no longer stacking up / excess "ghost" diskspace is no longer consumed

**Comment by jsteemann** [comment] 2016-02-08 08:53
@ericfiala : thanks for the confirmation!

**Comment by dothebart** [comment] 2016-02-18 12:43
Confirmed to be fixed.

**Closed by dothebart** 2016-02-18 12:43 UTC
Labels: 1_Bug, core

**Comment by razvanphp** [comment] 2016-03-15 06:39
Let's reopen this please, problem seems to persist even in 2.8.3 stable.

I have another theory how this can happen: log files are still open after logrotate deleted / truncated them. Since we log every request, this files are rather big.

```
rgrigore@ay-p-arango1:~$ sudo du -sh /
du: cannot access ‘/proc/12041/task/12041/fd/4’: No such file or directory
du: cannot access ‘/proc/12041/task/12041/fdinfo/4’: No such file or directory
du: cannot access ‘/proc/12041/fd/3’: No such file or directory
du: cannot access ‘/proc/12041/fdinfo/3’: No such file or directory
du: cannot access ‘/proc/68995/task/69000/fd/542’: No such file or directory
du: cannot access ‘/proc/68995/task/81455/fd/901’: No such file or directory
du: cannot access ‘/proc/68995/task/81455/fdinfo/835’: No such file or directory
du: cannot access ‘/proc/68995/task/81461/fdinfo/871’: No such file or directory
du: cannot access ‘/proc/68995/task/81473/fd/542’: No such file or directory
du: cannot access ‘/proc/68995/task/81479/fdinfo/735’: No such file or directory
77G	/
rgrigore@ay-p-arango1:~$ sudo df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             10M     0   10M   0% /dev
tmpfs            24G  2.5G   22G  11% /run
/dev/xvda1      296G  212G   69G  76% /
tmpfs            60G   12K   60G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            60G     0   60G   0% /sys/fs/cgroup
tmpfs            12G     0   12G   0% /run/user/2123
user@ay-p-arango1:~$
```
Those are the offending lines in lsof:

```
rgrigore@ay-p-arango1:~$ sudo lsof -u arangodb |grep deleted
arangodb 40679 arangodb    3w   REG              202,1            0 17042127 /var/log/arangodb/arangod.log.requests.daemon (deleted)
arangodb 40679 arangodb    4w   REG              202,1        17088 17041956 /var/log/arangodb/arangod.log.daemon (deleted)
arangodb 68995 arangodb    3w   REG              202,1 147087581297 17039516 /var/log/arangodb/arangod.log.requests (deleted)
rgrigore@ay-p-arango1:~$
```

**Comment by wirtsi** [comment] 2016-03-15 08:25
The daemon probably needs a SIGHUP (or similar) so it can be notified to recreate the file handles...

**Comment by razvanphp** [comment] 2016-03-15 08:37
Well I can put this in logrotate post rotate, but can somebody confirm this is what needs to be done? Is this restarting arango completely?

**Comment by wirtsi** [comment] 2016-03-15 09:03
I think it has no effect at all so far..

**Comment by fceller** [comment] 2016-03-15 10:09
@razvanphp @wirtsi yes seems to be a bug in the SIGHUP handling:

https://github.com/arangodb/arangodb/issues/1783
