### ISSUE TITLE
Streaming transactional query succeeds prior to 3.6.6, but fails in 3.6.6 with "Cursor Not Found" error

### ISSUE THREAD

**Issue by robross0606** [arangodb/arangodb#12644] opened 2020-09-11 17:11 UTC
## My Environment

* __ArangoDB Version__:        3.6.6
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               Default
* __Infrastructure__:               AWS EC2 t3a.xlarge
* __Operating System__:        CentOS Linux release 7.8.2003 (Core)
* __Total RAM in your machine__:        16 GB
* __Disks in use__:        SSD (AWS GP2); No encryption
* __Used Package__:              RedHat .rpm (official ArangoDB repo)

## Component, Query & Data

__Affected feature__:
AQL streaming transaction queries ArangoJS JavaScript driver 6.14.1

__AQL query (if applicable)__:
Multiple complex transactional queries involved.

__AQL explain and/or profile (if applicable)__:
Our Arango model includes some data with a parent/child hierarchy.  We have a JavaScript function which kicks off an Arango transaction stream in which it determines which items are children of a parent, does some "decoupling" where necessary, and then deletes the parent/child hierarchy of a specific top-level parent.  We then have a unit test against his function which attempts to do several of these concurrently to ensure that Arango locks are behaving properly and in a performant manner.

__Dataset__:

[LOCAL-Dump.zip](https://github.com/arangodb/arangodb/files/5210636/LOCAL-Dump.zip)

__Size of your Dataset on disk__:
How do you even determine this?  My entire engine-rocksdb folder is 119MB

__Replication Factor & Number of Shards (Cluster only)__:
N/A

## Steps to reproduce

1. Run a unit test against a 3.6.5 Arango server.  Test succeeds.
2. Switch to 3.6.6 Arango server and run unit test.  Test fails. 

__Problem__:
This function has worked fine and passed unit tests in our Jenkins CI environment from 3.5.4 all the way up to 3.6.5.  When the server was updated to 3.6.6, this unit test began consistently failing:
```
[2020-09-10T17:53:44.900Z]     console.log
[2020-09-10T17:53:44.900Z]       [error]: Failed to delete document: Aborting multi-level delete transaction 1 due to error: cursor not found  metadata: {
[2020-09-10T17:53:44.900Z]         "stack": [
[2020-09-10T17:53:44.900Z]           "new ArangoError (/var/lib/jenkins/workspace/NCP_study-design-service_PR-228@2/node_modules/arangojs/src/error.ts:76:17)",
[2020-09-10T17:53:44.900Z]           "Object.resolve (/var/lib/jenkins/workspace/NCP_study-design-service_PR-228@2/node_modules/arangojs/src/connection.ts:378:20)",
[2020-09-10T17:53:44.900Z]           "callback (/var/lib/jenkins/workspace/NCP_study-design-service_PR-228@2/node_modules/arangojs/src/connection.ts:220:16)",
[2020-09-10T17:53:44.900Z]           "IncomingMessage.<anonymous> (/var/lib/jenkins/workspace/NCP_study-design-service_PR-228@2/node_modules/arangojs/src/util/request.node.ts:117:15)",
[2020-09-10T17:53:44.900Z]           "IncomingMessage.emit (events.js:327:22)",
[2020-09-10T17:53:44.900Z]           "endReadableNT (_stream_readable.js:1220:12)",
[2020-09-10T17:53:44.900Z]           "processTicksAndRejections (internal/process/task_queues.js:84:21)"
[2020-09-10T17:53:44.900Z]         ],
[2020-09-10T17:53:44.900Z]         "ncpLogClient": "study-design-service"
[2020-09-10T17:53:44.900Z]       }
[2020-09-10T17:53:44.900Z] 
[2020-09-10T17:53:44.900Z]       at Console.log (node_modules/winston/lib/winston/transports/console.js:79:23)
```
We were able to toggle using the same branch code and build against multiple different Arango servers (3.6.4, 3.6.5 and 3.6.6).  It works consistently fine up until we point it at 3.6.6, at which point it fails consistently with a "Cursor not found" error.

__Expected result__:
The unit test should succeed in 3.6.6 just as it did in 3.6.5, 3.6.4 and several other releases dating back to 3.5.4.  With 3.6.6 being a +0.0.1 "patch" release as per semantic versioning, we should be able to switch from 3.6.5 to 3.6.6 without seeing severe performance related issues or other behavioral changes.  This appears to be a regression bug.

**Comment by Simran-B** [comment] 2020-09-23 10:50
> We then have a unit test against his function which attempts to do several of these concurrently to ensure that Arango locks are behaving properly and in a performant manner.

Do you mean that you run multiple stream transactions in parallel, with overlapping target documents? Or a single transaction to which you submit operations concurrently?

**Comment by robross0606** [comment] 2020-09-23 12:00
Neither. Multiple transactions in parallel but not on overlapping target documents.  Just overlapping target collections.  There are no exclusive locks involved.
-------- Original message --------From: Simran <notifications@github.com> Date: 9/23/20  6:50 AM  (GMT-05:00) To: arangodb/arangodb <arangodb@noreply.github.com> Cc: robross0606 <robross0606@gmail.com>, Author <author@noreply.github.com> Subject: Re: [arangodb/arangodb] Streaming transactional query succeeds prior to 3.6.6, but fails in 3.6.6 with "Cursor Not Found" error (#12644) 

We then have a unit test against his function which attempts to do several of these concurrently to ensure that Arango locks are behaving properly and in a performant manner.

Do you mean that you run multiple stream transactions in parallel, with overlapping target documents? Or a single transaction to which you submit operations concurrently?

**Comment by goedderz** [comment] 2020-11-05 08:05
Can you share the test in question, or a reduced test case which exhibits the same problem?

**Comment by robross0606** [comment] 2020-11-09 16:42
It would take a considerable amount of work to try and create a reduced project that touches this issue, particularly because I have no idea what is causing it.  However, here is the actual jest test, if that helps:
```javascript
/* Copyright (c) 2020 Nurocor Inc. All Rights Reserved. */

require('expect-more-jest')
const { createTestClient } = require('apollo-server-testing')

// eslint-disable-next-line
const mockUser = require('../../__mocks__/data/demo-user')
const data = require('./data')

// const utils = require('../../utils')
const service = require('../../arango-service')
const server = require('../../server')
const { mutate } = createTestClient(server.apolloServer)

const { TYPES } = require('../../graphql/types/object-types')
const testUtils = require('../test-utils')

require('../expect-even-more-jest')

// Initialize database collections.
beforeAll(async () => {
  await service.initializeDatabase(false)
})

describe('Study Protocol Version Resolvers', () => {
  it('Correctly handles multiple concurrent study deletes', async () => {
    const CONCURRENTS = 5 // utils.randomBetween(3, 10)
    const studies = []
    const definedActivityIds = [
      '1.0_1568285915313-593119490',
      '1.0_15682859155822009145981',
      '1.0_1568285915990-1795162165',
      '1.0_1568285916238317969935',
      '1.0_1568285916492237623621',
      '1.0_15705645989401269921379',
      '1.0_1570519632854-681895765',
      '1.0_1568285916491793082958',
      '1.0_1568285917243881087966',
      '1.0_1568285917621-52663062',
      '1.0_1568285917994-1556304630',
      '1.0_1569588810116829060534',
      '1.0_15682859184951666892924',
      '1.0_15682859194972052168379',
      '1.0_1568285919748-824970273',
      '1.0_1568285919748-745994471',
      '1.0_1568285920499-1095236015',
      '1.0_15682859210001766669710',
      '1.0_15682859212511731619003',
      '1.0_1568285921752-1318186823'
    ]

    for (let c = 0; c < CONCURRENTS; c++) {
      const objects = await testUtils.createStudyWithSchedule(mutate, false, definedActivityIds)
      const study = objects.originalVersion[TYPES.Study][0]
      expect(study.id).toBeNonEmptyString()
      studies.push(study)
    }

    const deleting = []
    for (const study of studies) {
      deleting.push(
        mutate({
          mutation: data.queries.delete_study,
          variables: {
            id: study.id
          }
        })
      )
    }
    for (const response of await Promise.all(deleting)) {
      expect(response).toBeApiSuccessResponse()
    }
  }, 180000 /*3 minute timeout */)
})

```

**Comment by goedderz** [comment] 2020-11-10 11:10
Hi @robross0606,

thanks. However, without the included files, this is sadly not of much help. We will need some way of reproducing this, or more specific information about it.

Note that cursors have a TTL (per default 30s) and will be cleaned up after being unused for that amount of time. I assume that's not what's happening here, but please confirm that this cannot be the reason.

Maybe you could add some more logging around your cursors? I.e. when your cursors are created and when they are being used, always including the cursorId so they can be kept apart. That combined with some more logging on the server-side, e.g. increasing the log level of the `queries` topic to `debug` with `--log.level queries=debug` (and maybe turn statistics off with `--server.statistics false` to avoid some noise in the logs).

**Comment by robross0606** [comment] 2020-11-10 14:01
@goedderz, my concern with these suggestions is that they provide no insight into why this works fine up until version 3.6.6.

**Comment by goedderz** [comment] 2020-11-10 15:31
> my concern with these suggestions is that they provide no insight into why this might work fine up until version 3.6.6.

That's not true. If we find the reason why this happens at all, we can also find out why this didn't happen in 3.6.5. And if you cannot observe what happens during your tests you cannot debug the problems they show. Of course logging might impact the performance, but that this is a problem here is at best a guess; also you will usually find that out if you try.

There are changes to cursors, but as far as I can see that should only affect queries which were killed or timed out. For reference, https://github.com/arangodb/arangodb/pull/12439 and https://github.com/arangodb/arangodb/pull/12371.

But again, without any additional information, I will probably neither be able to help you nor find the cause.

**Comment by robross0606** [comment] 2020-11-10 15:34
What I mean is the suggestions are "shooting in the dark" rather than targeting the debugging to the specific problems that might have been introduced in 3.6.6.  We already log when our transactions start and end.  These transaction cursors simply disappear mid-flight.  I don't know what else you expect us to log.

**Comment by robross0606** [comment] 2020-11-10 15:44
Your last comment about #12371 is actually _exactly_ for what I was asking.  How does Arango identify that a query is "hanging"? 
 Perhaps things worked previously due to a bug which was fixed and now causing a regression issue on our end?  That at least gives me a target path for debugging.  That would also explain why a +0.0.1 version increment caused a significant regression issue on our end.  I'll take a look at transaction

**Comment by robross0606** [comment] 2020-11-10 17:27
Is there some way to control TTL on a per-transaction basis, or is it only a server-wide setting?

**Comment by goedderz** [comment] 2020-11-11 15:50
> Is there some way to control transaction/cursor TTL on a per-transaction basis, or is it only a server-wide setting? You suggest the cursor has a default TTL of 30 seconds, but the [documentation ](https://www.arangodb.com/docs/stable/aql/invocation-with-arangosh.html#setting-options) appears to state otherwise unless I'm misunderstanding:
> 
> > maxRuntime: The query has to be executed within the given runtime or it will be killed. The value is specified in seconds. The default value is 0.0 (no timeout).

That option refers to the total query runtime. There is a TTL for cursors, which is intended to clean up resources of a query on the server if a client doesn't fetch them. The latter is what I was referring to, you can find documentation details here: https://www.arangodb.com/docs/stable/http/aql-query-cursor-accessing-cursors.html#create-cursor

As you've referred to arangosh, you can set that option there as in `db._query(query, bindVars, { ttl: 30 }, {})` (the last argument in this case containing the query options, as opposed to the cursor options). You can also use `--query.registry-ttl ` to set it globally (see https://www.arangodb.com/docs/stable/programs-arangod-options.html#query).

>  How does Arango identify that a query is "hanging"?

These PR mostly refer to the case where cursor are created via the async HTTP interface (https://www.arangodb.com/docs/3.7/http/async-results-management.html). While the web interface does that, other drivers do not as far as I know.

There might still be a change however in how the server responds to requests to a cursor which was already killed, or timed out, I haven't looked into that in detail.

HTH

**Comment by robross0606** [comment] 2020-11-11 15:56
> As you've referred to arangosh

Where did I refer to "arangosh"?  I'm using the regular ArangoJS driver with standard calls to things like `.query()`.  Most of our queries using the [transaction stream API](https://arangodb.github.io/arangojs/latest/classes/_transaction_.transaction.html) and not the "server side" [executeTransaction()](https://arangodb.github.io/arangojs/latest/classes/_database_.database.html#executetransaction) API call.  Your suggested use of `db._query()` seems to imply use of the later.

**Comment by robross0606** [comment] 2020-11-11 16:39
I think I _might_ be zeroing in on part of the problem.  Looks like the `ttl` option on `db.query()` was not added (or at least documented) until version 7.0.0.  Compare these two:

- https://arangodb.github.io/arangojs/6.14.1/Reference/Database/Queries.html
- https://arangodb.github.io/arangojs/7.0.0/modules/_database_.html#queryoptions

The documentation for 6.14.1 doesn't appear to provide specific `queryOptions` details.  Instead, it says this:

> Possible key options in opts.options include: failOnWarning, cache, profile or skipInaccessibleCollections. For a complete list of query settings please reference the [setting options](https://www.arangodb.com/docs/stable/aql/invocation-with-arangosh.html#setting-options).  That page does not document the `ttl` option.

**Comment by goedderz** [comment] 2020-11-12 07:17
Sorry, that was a misunderstanding. You shared a link to the arangosh documentation in this comment: https://github.com/arangodb/arangodb/issues/12644#issuecomment-724850177, and I wrongly assumed you're using that. So my example was for arangosh, not arangojs; and I did not want to suggest to use `executeTransaction()`. Though it is good to know you're also using streaming transactions.

> That referenced page for arangosh does not document the ttl option or default behavior.

You're right, there seems to be an oversight. However, it looks like arangojs 6.14.1 should work already with the `ttl` option: https://github.com/arangodb/arangojs/blob/ee30e4dd899e3a33e18d7538e0bf4e9ea7e02975/src/database.ts#L59.
 I will make the addition to the documentation. Until then you can look into the documentation of the HTTP API instead, which is the basis for all drivers, including both arangosh and arangojs: https://www.arangodb.com/docs/devel/http/aql-query-cursor-accessing-cursors.html#create-cursor

**Comment by Simran-B** [comment] 2020-11-12 11:52
If I compare
https://www.arangodb.com/docs/stable/aql/invocation-with-arangosh.html#setting-options to
https://www.arangodb.com/docs/stable/http/aql-query-cursor-accessing-cursors.html
then the listed arangosh options are what is under the `options` attribute in the API. `ttl` and others are not, they are top level attributes like `options`.
There is a separate section about `memoryLimit`, a top level attribute in the API:
https://www.arangodb.com/docs/stable/aql/invocation-with-arangosh.html#setting-a-memory-limit
Looks like the rest of the cursor options isn't documented for arangosh - I'll look into that.

**Comment by Simran-B** [comment] 2023-11-15 13:28
The documentation around arangosh query options has been reworked: https://github.com/arangodb/docs/pull/1207

A bug that prevented the forwarding of the `ttl` option has been addressed: https://github.com/arangodb/arangodb/pull/17601

Furthermore, v3.6 reached end of life a long time ago. Closing.

**Closed by Simran-B** 2023-11-15 13:28 UTC
Labels: Waiting User Reply, 1 Analyzing, 3 Transaction
