### ISSUE TITLE
arangorestore command terminated arangodb process

### ISSUE THREAD

**Issue by mathsyouth** [arangodb/arangodb#12896] opened 2020-10-23 15:19 UTC
## My Environment

* __ArangoDB Version__:        3.6.7-1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:        single instance
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:              1 machine
* __Infrastructure__:               own
* __Operating System__:        CentOS 7.3
* __Total RAM in your machine__:        64Gb each
* __Disks in use__:        HDD

## Component, Query & Data

__Affected feature__:
`arangorestore`  restores a database

__AQL query (if applicable)__:

__AQL explain and/or profile (if applicable)__:

__Problem__:

I created a database named "test" which has no collections and no edge collections.

I run the following code:

```
bin/arangorestore --server.endpoint tcp://127.0.0.1:8529 --server.name test --server.password test --server.authentication true --server.database test --input-directory "dump_db" --force-same-database true
```

The printed log on the screen is:

```
[13336] ERROR [e8e7a] {restore} Error while creating collection 'production': got invalid response from server: 'Connection closed by remote' while executing restoring collection with this payload: '{"index": [],"parameters":{"cacheEnabled":false,"deleted":false,"globallyUniquedId":"c10011700/","id":"10011700:......}
[13336] ERROR [cb69f] {restore} got invalid response from server: 'Connection closed by remote' while executing restoring collection with this payload: '{"indexes":[],....}'
```

There is also an INFO  message in arangodb's arangod.log:

```
|INFO| Wait on 31818 returned component=arangodb core-dump=true signal="segmentation fault" trap-cause=-1
|INFO| Terminated single component=arangodb process=31818
|INFO| single has terminated component=arangodb
|INFO| restarting single component=arangodb
|INFO| Looking for a running instance of single on port 8529 componnent=arangodb
.......
```

However,  if I created all the collections for the "test" database manually and then run the above commands, all the data was successfully loaded into arangodb. I don't know why.

__Expected result__:

The  `arangorestore` could be executed successfully, without creating collections ahead of time.

**Comment by Simran-B** [comment] 2020-10-28 11:30
@mathsyouth Would it be possible for you to share the dump so that we can try to reproduce the problem?

**Comment by mathsyouth** [comment] 2020-10-29 12:28
@Simran-B I am so sorry that I couldn't share the dump because of the company's data security requirements. However, you can easily reproduce the problem by following steps: 1. create a database and load data into that database; 2. dump the data to the local folder; 3.  create the other database with the same same but without creating any collections; 4. run the `arangorestore` command to reproduce the problem.

**Comment by Simran-B** [comment] 2020-11-04 13:53
We will try to reproduce the problem using `--server.database ... --force-same-database` (`--import-data` and `--create-collection` default to true). In a fresh instance, a database should be created manually, with the same name as in the dump. No collections before import.

**Comment by Simran-B** [comment] 2020-11-11 15:51
We could not reproduce the problem. Can you share the `production.structure.json` file?

**Comment by Simran-B** [comment] 2020-11-25 15:42
@mathsyouth Can you share the requested file?

**Comment by mathsyouth** [comment] 2020-11-27 08:46
@Simran-B Please check the attached files. 
[Uploading structure_json_temp.zip…]()

**Comment by maxkernbach** [comment] 2020-12-09 11:09
Hi @mathsyouth,

Could you please double check whether you attached the correct file? In your initial report the restore failed at the creation of collection "production".

However, no "production.structure.json" is included in the provided dump. The restore of your structure dump (with an additional option `--import data false` since only structure files are included) was successful.

In case you can reproduce an error with the given dump, let us know the exact `arangorestore` command.

**Comment by mathsyouth** [comment] 2020-12-11 10:28
Hi @maxkernbach
I replaced every collection name in the attached files with "production" for convenience. In other words, nearly every restored collection would fail if it is not created ahead of time.

**Comment by maxkernbach** [comment] 2020-12-16 16:12
Hi @mathsyouth,

Does the restore also fail if you specify `--import-data false` in addition? Also, does this happen on a fresh environment?

Can you please provide the `arangodump` command you used to create the stated dump?

**Comment by mathsyouth** [comment] 2020-12-22 02:08
Hi @maxkernbach 
I didn't specify the option `--import-data false`. Neither I tried the command on a fresh environment. 

The `arangodump` command is:

```
bin/arangodump --server.endpoint tcp://127.0.0.1:8501 --server.username test -server.password test --server.authentication true --server.database test --output-directory "dump_db"
```

**Comment by maxkernbach** [comment] 2021-01-20 15:19
Hi @mathsyouth,

Since this is not reproducible for now, I am closing the issue.

In case you can reproduce this issue in a fresh environment, please let us know and we will investigate.

**Closed by maxkernbach** 2021-01-20 15:19 UTC
Labels: 1 Analyzing, 3 ImportExport, Waiting User Reply
