### ISSUE TITLE
K_SHORTEST_PATHS LIMIT 1 can not return the shortest path

### ISSUE THREAD

**Issue by zhihui1084** [arangodb/arangodb#10371] opened 2019-11-06 05:47 UTC
## My Environment

* __ArangoDB Version__:        3.5.1 COMMUNITY EDITION
* __Storage Engine__:             
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter in Docker
* __Configuration__:               notable server settings
* __Infrastructure__:               own
* __Operating System__:        CentOS7.4
* __Total RAM in your machine__:        16Gb
* __Disks in use__:       SSD
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__:
AQL query using web interface or with driver

__AQL query (if applicable)__:
FOR switch
  IN OUTBOUND K_SHORTEST_PATHS
  "switch/1720.2911.5019.00" TO "switch/1720.2911.5004.00"
  GRAPH "utn"
  OPTIONS {weightAttribute: "cost"}
  LIMIT 1
  RETURN switch

__AQL explain (if applicable)__:
Query String (182 chars, cacheable: true):
 FOR switch
   IN OUTBOUND K_SHORTEST_PATHS
   "switch/1720.2911.5019.00" TO "switch/1720.2911.5004.00"
   GRAPH "utn"
   OPTIONS {weightAttribute: "cost"}
   LIMIT 1
   RETURN switch

Execution plan:
 Id   NodeType             Est.   Comment
  1   SingletonNode           1   * ROOT
  2   KShortestPathsNode   2187     - FOR switch  /* path */ IN OUTBOUND K_SHORTEST_PATHS 'switch/1720.2911.5019.00' /* startnode */ TO 'switch/1720.2911.5004.00' /* targetnode */ GRAPH 'utn'
  3   LimitNode               1     - LIMIT 0, 1
  4   ReturnNode              1     - RETURN switch

Indexes used:
 none

k shortest paths on graphs:
 Id   Vertex collections   Edge collections
  2   switch               switch_connect     

Optimization rules applied:
 none

__Dataset__:

vertices:
{
  "switch_name": "TBR-001-SEA02-jakarta02-L6C-C03",
  "idc": "SEA02",
  "region": "6ZuF5Yqg6L6"
}
edge:
{
  "cost": 1,
  "is_edge_node": false,
  "status": true,
  "auto_insert": true,
  "to_switch_name": "TER-001-SEA02-jakarta02-L6C-C03",
  "from_switch_name": "TBR-001-SEA02-jakarta02-L6C-C03"
}

__Size of your Dataset on disk__:
18M

__Replication Factor & Number of Shards (Cluster only)__:
1

## Steps to reproduce

1. limit 1 result: [
	{
		"edges": [
		...
		],
		"vertices": [
		...
		],
		"weight": 25004
	}
]
2. limit 2 result:
[
	{
		"edges": [
		...
		],
		"vertices": [
		...
		],
		"weight": 25004
	},
	{
		"edges": [
		...
		],
		"vertices": [
		...
		],
		"weight": 21003
	}
]
3. FOR switch
  IN OUTBOUND SHORTEST_PATH
  "switch/1720.2911.5019.00" TO "switch/1720.2911.5004.00"
  GRAPH "utn"
  OPTIONS {weightAttribute: "cost"}
  RETURN switch
result is right, and weight is 21003

__Problem__:
The K_SHORTEST_PATHS result is not order by weight.

__Expected result__:
limit 1 result: [
	{
		"edges": [
		...
		],
		"vertices": [
		...
		],
		"weight": 21003
	}
]

**Comment by markuspf** [comment] 2019-11-08 13:54
Hi,

I reproduced the problem, and will provide a fix soon

**Comment by zhihui1084** [comment] 2019-11-11 13:45
@markuspf Thanks for the support.

**Comment by maxkernbach** [comment] 2019-11-14 13:08
Hi @zhihui1084,

A fix for this bug will be available in the next minor release 3.5.3.
We will inform you and close this issue once version 3.5.3 is available.

**Comment by maxkernbach** [comment] 2019-12-05 14:07
Hi @zhihui1084,

Version 3.5.3, which includes a fix for K_SHORTEST_PATHS, has been released.

From the [Changelog](https://github.com/arangodb/arangodb/blob/660ff994dbfa994a18fe921481f591b878b51619/CHANGELOG#L64):

> 
> * Fixed issue #10371: K_SHORTEST_PATHS LIMIT 1 can not return the shortest path.
>   Now the shortest path is returned as the first one in such queries.
> 

Please find the latest release in the [download section](https://www.arangodb.com/download-major/ubuntu/).

**Comment by zhihui1084** [comment] 2020-04-09 04:30
I sorry about reopen this issue. The issue is still in my env;

Steps to reproduce
FOR path 
    IN OUTBOUND K_SHORTEST_PATHS
    "switch/10.190.42.6" TO "switch/10.190.6.7" 
    GRAPH "utn" 
    OPTIONS { weightAttribute: "cost", defaultWeight: 100000 } 
    LIMIT 1
    RETURN path
limit 1 result: [
{
"edges": [
...
],
"vertices": [
...
],
"weight": 22003
}
]
limit 2 result:
[
{
"edges": [
...
],
"vertices": [
...
],
"weight": 22003
},
{
"edges": [
...
],
"vertices": [
...
],
"weight": 18002
}
]
3. The result of SHORTEST_PATH is correct:
FOR path 
    IN OUTBOUND SHORTEST_PATH
    "switch/10.190.42.6" TO "switch/10.190.6.7" 
    GRAPH "utn" 
    OPTIONS { weightAttribute: "cost", defaultWeight: 100000 } 
    RETURN path
result is right, and weight is 18002
Problem:
The K_SHORTEST_PATHS result is not order by weight.

Expected result:
limit 1 result: [
{
"edges": [
...
],
"vertices": [
...
],
"weight": 18002
}
]

**Comment by zhihui1084** [comment] 2020-04-09 04:47
Hi, @maxkernbach,

I want to reopen this issue. The issue is still in my env when I update the version 3.6.2

### **My Environment**

- ArangoDB Version: 3.6.2 COMMUNITY EDITION
- Storage Engine:
- Deployment Mode: Single Server
- Deployment Strategy: ArangoDB Starter in Docker
- Configuration: notable server settings
- Infrastructure: own
- Operating System: CentOS7.4
- Total RAM in your machine: 16Gb
- Disks in use: SSD
- Used Package: Docker - official Docker library

### **Component, Query & Data**
Affected feature:
AQL query using web interface or with driver

**AQL query (if applicable):**
FOR path 
    IN INBOUND K_SHORTEST_PATHS
    "switch/10.190.42.6" TO "switch/10.190.6.7" 
    GRAPH "utn" 
    OPTIONS { weightAttribute: "cost", defaultWeight: 100000 } 
    LIMIT 1
    RETURN path

**AQL explain (if applicable):**
Query String (199 chars, cacheable: true):
 FOR path 
     IN INBOUND K_SHORTEST_PATHS
     "switch/10.190.42.6" TO "switch/10.190.6.7" 
     GRAPH "utn" 
     OPTIONS { weightAttribute: "cost", defaultWeight: 100000 } 
     LIMIT 1
     RETURN path

Execution plan:
 Id   NodeType             Est.   Comment
  1   SingletonNode           1   * ROOT
  2   KShortestPathsNode   2187     - FOR path  /* path */ IN INBOUND K_SHORTEST_PATHS 'switch/10.190.42.6' /* startnode */ TO 'switch/10.190.6.7' /* targetnode */ GRAPH 'utn'
  3   LimitNode               1     - LIMIT 0, 1
  4   ReturnNode              1     - RETURN path

Indexes used:
 none

k shortest paths on graphs:
 Id   Vertex collections   Edge collections  
  2   switch               utn_switch_connect   

Optimization rules applied:
 none

**Dataset:**

vertices:
{
  "switch_name": "TER-02-HB05-DP10-F13",
  "isis_number": "1720.2999.0006.00",
  "idc": "HB05",
  "level": "utn"
}
edge:
{
"cost": 1,
"is_edge_node": false,
"status": true,
"auto_insert": true,
"to_switch_name": "TER-001-SEA02-jakarta02-L6C-C03",
"from_switch_name": "TBR-001-SEA02-jakarta02-L6C-C03"
}

Size of your Dataset on disk:
18M

Replication Factor & Number of Shards (Cluster only):
1

### **Steps to reproduce**
1. limit 1 result: [
{
"edges": [
...
],
"vertices": [
...
],
"weight": 22003
}
]
2. limit 2 result:
[
{
"edges": [
...
],
"vertices": [
...
],
"weight": 22003
},
{
"edges": [
...
],
"vertices": [
...
],
"weight": 18002
}
]
3. FOR path 
    IN INBOUND SHORTEST_PATH
    "switch/10.190.42.6" TO "switch/10.190.6.7" 
    GRAPH "utn" 
    OPTIONS { weightAttribute: "cost", defaultWeight: 100000 } 
    RETURN path
result is right, and weight is 18002

**Problem:**
The K_SHORTEST_PATHS result is not order by weight.

**Expected result:**
limit 1 result: [
{
"edges": [
...
],
"vertices": [
...
],
"weight": 18002
}
]

**Comment by maxkernbach** [comment] 2020-04-09 09:24
Hi @zhihui1084,

Thanks for reporting. Would it be possible to share the dump (created by **arangodump** with option **--include-system-collections=true** to include the graph definition) of the involved database either via this issue or mail?

You can send us a message to hackers@arangodb.com (this ML is not public) and attach the dump in that email. This way we can try to reproduce and find the root cause. Please reference the number of this issue in your email.

**Comment by zhihui1084** [comment] 2020-04-09 10:12
> Hi @zhihui1084,
> 
> Thanks for reporting. Would it be possible to share the dump (created by **arangodump** with option **--include-system-collections=true** to include the graph definition) of the involved database either via this issue or mail?
> 
> You can send us a message to [hackers@arangodb.com](mailto:hackers@arangodb.com) (this ML is not public) and attach the dump in that email. This way we can try to reproduce and find the root cause. Please reference the number of this issue in your email.

Thanks for your support. I have sent the mail.

**Comment by zhihui1084** [comment] 2020-04-13 06:03
> Hi @zhihui1084,
> 
> Thanks for reporting. Would it be possible to share the dump (created by **arangodump** with option **--include-system-collections=true** to include the graph definition) of the involved database either via this issue or mail?
> 
> You can send us a message to [hackers@arangodb.com](mailto:hackers@arangodb.com) (this ML is not public) and attach the dump in that email. This way we can try to reproduce and find the root cause. Please reference the number of this issue in your email.

 Hi, @maxkernbach, 

I have sent the mail. Please check it. thanks.

**Comment by maxkernbach** [comment] 2020-04-14 10:21
Hi @zhihui1084,

Thanks, we have received your mail and were able to reproduce this issue with the provided dataset.
Please note that I can't provide an ETA for a bug-fix though.

**Comment by zhihui1084** [comment] 2020-04-15 08:39
> Hi @zhihui1084,
> 
> Thanks, we have received your mail and were able to reproduce this issue with the provided dataset.
> Please note that I can't provide an ETA for a bug-fix though.

Hi @maxkernbach ,

Thank for your support. But how can I know about the ETA for this bug?

**Comment by dothebart** [comment] 2020-04-15 10:20
Hi,
please note that community subscription doesn't contain any SLA, see 
https://www.arangodb.com/subscriptions/
for details.

**Comment by zhihui1084** [comment] 2020-04-15 10:33
> Hi,
> please note that community subscription doesn't contain any SLA, see
> https://www.arangodb.com/subscriptions/
> for details.

Hi, @dothebart ,

OK, Thanks.

**Closed** 2020-05-15 19:23 UTC
Labels: 1 Bug, 3 AQL, 3 Graph
