### ISSUE TITLE
AQL: cannot use shrink() to increase block

### ISSUE THREAD

**Issue by abrekhov** [arangodb/arangodb#13147] opened 2020-12-04 17:13 UTC
## My Environment

* __ArangoDB Version__:        3.7.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:  Manual Start in Docker
* __Infrastructure__:               own
* __Operating System__:        Alpine Linux v3.11
* __Total RAM in your machine__:        16GB
* __Disks in use__:        HDD
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__:
Foxx

__AQL query (if applicable)__:
```
ArangoError: AQL: cannot use shrink() to increase block (exception location: /work/ArangoDB/arangod/Aql/AqlItemBlock.cpp:372). Please report this error to arangodb.com (while executing)
    at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:84:16)
    at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:102:45)
    at runQuery (/var/lib/arangodb3-apps/_db/CMDB/QDSL/APP/scripts/getNodeList.js:35:22)
    at /var/lib/arangodb3-apps/_db/CMDB/QDSL/APP/scripts/getNodeList.js:52:15
    at Array.forEach (<anonymous>)
    at executeNodeSearch (/var/lib/arangodb3-apps/_db/CMDB/QDSL/APP/scripts/getNodeList.js:49:11)
    at /var/lib/arangodb3-apps/_db/CMDB/QDSL/APP/scripts/getNodeList.js:51:15
    at Array.forEach (<anonymous>)
    at executeNodeSearch (/var/lib/arangodb3-apps/_db/CMDB/QDSL/APP/scripts/getNodeList.js:49:11)
    at Object.executeQDSL (/var/lib/arangodb3-apps/_db/CMDB/QDSL/APP/scripts/getNodeList.js:80:19)

```

__Problem__:
Can't understand the problem. I've upgraded from arangodb v3.4.7 to v3.7.3 and our foxx service log this errors...

__Expected result__:

**Comment by jsteemann** [comment] 2020-12-04 20:46
@abrekhov : this is an internal error that is not supposed to happen.
Is it possible to share the query that triggers this error with us?
That would be very helpful!
Thanks!

**Comment by abrekhov** [comment] 2020-12-05 13:37
@jsteemann : 
here is the AQL from our foxx microservice:

```
for bObject, bLink, path in 0..10
outbound 'groups/opa'
links, geometricLinks, topologyLinks, storageLinks
filter (
        for iv in 0..(length(path.vertices) - 1)
            let r = path.vertices[iv]._meta.restrict
            return iv < 0 || !r ||
                (for e in slice(path.edges, iv)
                    return parse_identifier(e).collection) all in r
    ) all == true
filter path.edges[*].type ALL == 'path-downlink'

            let object = bObject
            let link = bLink
filter object
let fullPath = path
            for lvl in 0..(length(fullPath.vertices) - 1)
                let rPath = {
                    edges: slice(fullPath.edges, 0, lvl),
                    vertices: slice(fullPath.vertices, 0, lvl + 1)
                }
                let rObject = fullPath.vertices[lvl]
                let rLink = lvl > 0 ? fullPath.edges[lvl - 1] : {}
                return distinct {
id: rObject._id,
    mo: rObject._key,
    group: is_same_collection('groups', rObject._id),
    edges: rPath.edges[*].name,
    has_children:
            length((for o, l in 1 outbound rObject links, geometricLinks, topologyLinks, storageLinks
                filter l.type == 'path-downlink'
                let extPath = {
                    vertices: push(path.vertices, o),
                    edges: push(path.edges, l)
                }
                filter (
        for iv in 0..(length(extPath.vertices) - 1)
            let r = extPath.vertices[iv]._meta.restrict
            return iv < 0 || !r ||
                (for e in slice(extPath.edges, iv)
                    return parse_identifier(e).collection) all in r
    ) all == true
                limit 1
                return l)
            ) != 0
}
```

**Comment by dothebart** [comment] 2020-12-07 07:14
as discussed on https://github.com/arangodb/arangodb/issues/13124#issuecomment-739312809 - `splice-subqueries` is not the origin of this very issue.

**Comment by abrekhov** [comment] 2020-12-07 08:26
@dothebart : I'm sorry but the author of https://github.com/arangodb/arangodb/issues/13124 issue said that turning off the splice-subquiries feature helped. Maybe I didn't get it?

**Comment by dothebart** [comment] 2020-12-07 08:49
oh, sorry - then I misread your post - I read it as "didn't fix it for me? "

**Comment by dothebart** [comment] 2020-12-07 13:58
ok, reading the later post by @goedderz in this other ticket, its now working for you. So we can confirm that this issue is most probably a duplicate of #13124 ?

**Comment by abrekhov** [comment] 2020-12-08 10:59
@dothebart yeah, you're right! It's duplicate. Hope this will be fixed in next versions :)

**Comment by dothebart** [comment] 2020-12-08 12:22
thanks for confirming.

**Comment by Simran-B** [comment] 2020-12-09 15:37
Apparently the same root cause as #13099

**Comment by Simran-B** [comment] 2021-02-12 15:11
Hi @abrekhov,

v3.7.7 with a fix for the problem is now available. Please let us know if the issue is fully resolved.

Thanks

**Comment by maxkernbach** [comment] 2021-03-24 15:40
Hi @abrekhov,

Did you have a chance to upgrade and test the fix?

**Closed** 2021-05-05 14:38 UTC
Labels: 1 Bug, 1 Duplicate, 2 Fixed, 3 AQL, Waiting User Reply

**Comment by abrekhov** [comment] 2021-05-17 15:46
@maxkernbach Hi! 
I am sorry for the late reply! 
Yes, everything works fine. 
Thanks team for the fix!
