### ISSUE TITLE
Fatal crash on combined FLATTEN/SUBQUERY/FILTER/COLLECT

### ISSUE THREAD

**Issue by mdmm13** [arangodb/arangodb#13702] opened 2021-03-12 18:12 UTC
## My Environment

```
2021-03-12T17:31:26Z [1] INFO [e52b0] ArangoDB 3.7.9 [linux] 64bit, using jemalloc, build tags/v3.7.9-0-ga97bd5419c, VPack 0.1.33, RocksDB 6.8.0, ICU 64.2, V8 7.9.317, OpenSSL 1.1.1j  16 Feb 2021
2021-03-12T17:31:26Z [1] INFO [75ddc] detected operating system: Linux version 5.4.0-42-generic (buildd@lgw01-amd64-038) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
2021-03-12T17:31:26Z [1] INFO [25362] {memory} Available physical memory: 2147483648 bytes (overriden by environment variable), available cores: 2
2021-03-12T17:31:26Z [1] WARNING [118b0] {memory} maximum number of memory mappings per process is 65530, which seems too low. it is recommended to set it to at least 128000
2021-03-12T17:31:26Z [1] WARNING [49528] {memory} execute 'sudo sysctl -w "vm.max_map_count=128000"'
2021-03-12T17:31:26Z [1] INFO [43396] {authentication} Jwt secret not specified, generating...
2021-03-12T17:31:26Z [1] INFO [144fe] using storage engine 'rocksdb'
2021-03-12T17:31:26Z [1] INFO [3bb7d] {cluster} Starting up with role SINGLE
2021-03-12T17:31:26Z [1] INFO [a1c60] {syscall} file-descriptors (nofiles) hard limit is 1048576, soft limit is 1048576
2021-03-12T17:31:26Z [1] INFO [3844e] {authentication} Authentication is turned on (system only), authentication for unix sockets is turned on
2021-03-12T17:31:27Z [1] INFO [c1b63] {arangosearch} ArangoSearch maintenance: [1..1] commit thread(s), [1..1] consolidation thread(s)
2021-03-12T17:31:27Z [1] INFO [6ea38] using endpoint 'http+tcp://x.x.x.x:xxxx' for non-encrypted requests
2021-03-12T17:31:27Z [1] INFO [cf3f4] ArangoDB (version 3.7.9 [linux]) is ready for business. Have fun!
2021-03-12T17:32:41Z [1] FATAL [a7902] {crash} ArangoDB 3.7.9 [linux], thread 4 [SchedWorker] caught unexpected signal 11 (SIGSEGV) accessing address 0xfffffffffffffff8: signal handler invoked - image base address: 0x00007f29d2ece000 - CPU context: rip: 0x00007f29d40a40d7, rsp: 0x00007f29cb9f7770, efl: 0x0000000000010246, rbp: 0x00007f29cb9f77d0, rsi: 0x0000000000000000, rdi: 0x0000000000000000, rax: 0x0000000000000000, rbx: 0x0000000000000000, rcx: 0x0000000000000000, rdx: 0x0000000000000000, r8: 0x00007f29bd600e00, r9: 0x00007f29d72250e8, r10: 0x0000000000000021, r11: 0x00007f29bf14aac0, r12: 0x00007f29cb9f77f0, r13: 0x0000000000000000, r14: 0x00007f29bd542b40, r15: 0x00007f29cb9f7b70
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame  1 [+0x00000000007e2490] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame  2 [+0x00000000037fe0f2] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame  3 [+0x00000000011d6125] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame  4 [+0x000000000133705e] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame  5 [+0x000000000133972e] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame  6 [+0x0000000001187c75] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame  7 [+0x0000000001507926] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame  8 [+0x0000000001336cbe] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame  9 [+0x000000000133945c] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame 10 [+0x000000000127aa65] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame 11 [+0x0000000001558672] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame 12 [+0x000000000066b97e] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame 13 [+0x00000000015575dc] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame 14 [+0x00000000006900cc] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame 15 [+0x0000000001856a30] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame 16 [+0x0000000001857c44] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame 17 [+0x00000000018d1e16] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame 18 [+0x00000000018fd87a] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame 19 [+0x00000000015c7475] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame 20 [+0x00000000017b6923] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame 21 [+0x00000000007df20b] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame 22 [+0x0000000000776aaf] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [308c3] {crash} frame 23 [+0x0000000003804c45] *no symbol name available for this frame
2021-03-12T17:32:41Z [1] INFO [ded81] {crash} available physical memory: 2147483648, rss usage: 236138496, vsz usage: 949506048, threads: 29
```

* __ArangoDB Version__:        Docker 3.7.7 and 3.7.9 (have not tried others)
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single (Test) Server
* __Deployment Strategy__:   Docker via docker-compose
* __Configuration__:               None/ nothing special
* __Infrastructure__:               VPS
* __Operating System__:        Ubuntu 20.04.1 LTS
* __Total RAM in your machine__:        2G
* __Disks in use__:        1 SSD
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__:
AQL query using web interface (and with Java driver)

__AQL query (if applicable)__:
```
FOR r IN FLATTEN(
   FOR v IN 1..1 OUTBOUND @test TestEdge
    LET x = (FOR v2 IN 1..1 OUTBOUND v TestEdge
        FILTER v2.name IN @someArray
        RETURN v2)
    RETURN x)
COLLECT col = r
RETURN col
```

Original query is way more complex, but this is the simplified test query that still crashes every time.

__AQL explain and/or profile (if applicable)__:
Crashes with a longer list of frames (40+)

__Dataset__:
Create Document collection with name Test. Create Edge collection with name TestEdge. Add 2 entries to Test with "name"="value". Create 1 entry in Edge just linking Test entry 1 and entry 2.

__Size of your Dataset on disk__:
< 1MB

__Replication Factor & Number of Shards (Cluster only)__:
N/A

## Steps to reproduce

1. Start Docker via docker-compose with image: arangodb:latest
2. Create test database
3. Run query in Web Interface or via Java Driver, setting @test to the Test entry 1 _id and @someArray to either [] or null

__Problem__:
Fatal crash

__Expected result__:
Empty array OR query warning/error, but not a full-on crash.

__Possibly related__:
[13124](https://github.com/arangodb/arangodb/issues/13124), though explain/profile also crash.

__Other notes__:
1. Removing FILTER statement provides desired empty array (except it is unfiltered :-))
2. Removing COLLECT statement (but leaving FILTER) also works

**Comment by maxkernbach** [comment] 2021-03-15 10:34
Hi @mdmm13,

thanks for reporting. This crash is reproducible with a 3.7.9 single server as described.

Once the optimizer rule `splice-subqueries` is disabled, the query executes successfully.

Reproduction steps via `arangosh`:

- Create sample collections and documents:
```
 db._createDocumentCollection("Test");
 db._createEdgeCollection("TestEdge");
 db.Test.insert({"_key":"1111"});
 db.Test.insert({"_key":"1112"});
 db.TestEdge.insert({"_from": "Test/1111", "_to": "Test/1112"});
 ```
 
- Run query **with `splice-subqueries` -> server crash**
```
db._query(`FOR r IN FLATTEN(    FOR v IN 1..1 OUTBOUND "Test/1111" TestEdge     LET x = (FOR v2 IN 1..1 OUTBOUND v TestEdge         FILTER v2.name IN []         RETURN v2)     RETURN x) COLLECT col = r RETURN col`, {}, {optimizer: {rules: ["+splice-subqueries"] }})
```

Run query **without `splice-subqueries` -> successful execution**
```
db._query(`FOR r IN FLATTEN(    FOR v IN 1..1 OUTBOUND "Test/1111" TestEdge     LET x = (FOR v2 IN 1..1 OUTBOUND v TestEdge         FILTER v2.name IN []         RETURN v2)     RETURN x) COLLECT col = r RETURN col`, {}, {optimizer: {rules: ["-splice-subqueries"] }})
```

**Comment by Simran-B** [comment] 2021-03-17 15:12
The problem will be fixed in 3.7.11, thanks for reporting!

**Comment by mdmm13** [comment] 2021-03-18 13:35
Hi @maxkernbach

Thank you for the quick response and fix. Deactivating `splice-subqueries` seems to do the trick for the moment. Looking forward to 3.7.11!

Keep up the amazing work and congratulations on your product.

**Comment by maxkernbach** [comment] 2021-05-10 09:29
Hi @ajscarvalho,

Version 3.7.11 including a fix has been released.

Could you please let us know whether the issue is resolved?

**Comment by mdmm13** [comment] 2021-05-18 09:31
Hi @maxkernbach 

That's awesome, thank you for the fix! Seems to be working 👍 

All the best

**Closed** 2021-05-18 12:53 UTC
Labels: 1 Bug, 2 Fixed, 3 AQL, 3 Optimizer, Waiting User Reply, workaround available
