### ISSUE TITLE
I can not connect arangodb.

### ISSUE THREAD

**Issue by Jake132456** [arangodb/arangodb#3978] opened 2017-12-10 05:52 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ V] 3.2
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [V ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ V] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [x] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

Could not connect to endpoint 'http+tcp://127.0.0.1:8529', database: '_system', username: 'root'
Error message: '401: Unauthorized'

Type 'tutorial' for a tutorial or 'help' to see common examples
127.0.0.1:8529@_system>

when I log in I typed password and I got this message.
How can I solve it?
and How can I know my username?

**Comment by Jake132456** [comment] 2017-12-10 10:05
When I using it arangoshell

Please specify a password:

[32m                                  [31m     _      [0m
[32m  __ _ _ __ __ _ _ __   __ _  ___ [31m ___| |__  [0m
[32m / _` | '__/ _` | '_ \ / _` |/ _ \ [31m/ __| '_ \ [0m
[32m| (_| | | | (_| | | | | (_| | (_) [31m\__ \ | | | [0m
[32m \__,_|_|  \__,_|_| |_|\__, |\___/ [31m|___/_| |_| [0m
[32m                       |___/      [31m            [0m

arangosh (ArangoDB 3.2.9 enterprise [win64] 64bit, using VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2a 19 Mar 2015)
Copyright (c) ArangoDB GmbH

Pretty printing values.
Could not connect to endpoint 'http+tcp://127.0.0.1:8529', database: '_system', username: 'root'
Error message: '401: Unauthorized'

Type 'tutorial' for a tutorial or 'help' to see common examples
127.0.0.1:8529@_system> help




When I using it arangopy, I got this message.
from pyArango.connection import *
conn = Connection(username="root", password="0000")

Traceback (most recent call last):
  File "D:\Web page ����\pyarango\sample.py", line 2, in <module>
    conn = Connection(username="root", password="0000")
  File "C:\Users\User\Anaconda3\lib\site-packages\pyArango\connection.py", line 105, in __init__
    self.reload()
  File "C:\Users\User\Anaconda3\lib\site-packages\pyArango\connection.py", line 122, in reload
    r = self.session.get(self.databasesURL)
  File "C:\Users\User\Anaconda3\lib\site-packages\pyArango\connection.py", line 42, in __call__
    raise ConnectionError("Empty server response", ret.url, ret.status_code, ret.content)
pyArango.theExceptions.ConnectionError: Empty server response. URL: http://127.0.0.1:8529/_api/user/root/database, status: 401. Errors: b''
[Finished in 0.565s]

**Comment by jsteemann** [comment] 2017-12-11 08:57
It seems from the above output that the server returned with HTTP 401, which is "Unauthorized".
Which means no username / password were specified, or that the credentials used were not matching the credentials stored for the user.
Can you verify that the credentials you are using are actually correct?

**Comment by Jake132456** [comment] 2017-12-11 10:40
thanks for the reply.
Actually, I thought it several times, however, I use my main computer and I
didn't changed username.
So, I typed root and password I chose it at the install program as a 0000.
But it didn't work.
I reinstalled it only for me, at that time it didn't require initial
password, however, when I'm starting the arangoshell it require password.
How can I initialize it?
I installed ArangoDB3e-3.2.9-1_win64.exe at the window 10.


Sincerely yours,
Kyuho Hwang.



2017-12-11 17:57 GMT+09:00 Jan <notifications@github.com>:

**Comment by dothebart** [comment] 2017-12-11 10:56
Hi, on the console in the arangodb installation folder you should be able to invoke `usr/bin/arango-secure-installation.exe` which will ask you for a new password for your installation.

**Comment by Jake132456** [comment] 2017-12-11 11:14
I execute it.
I got this message.

2017-12-11 19:56 GMT+09:00 Wilfried Goesgens <notifications@github.com>:

**Comment by jsteemann** [comment] 2017-12-11 11:21
Which message?

**Comment by Jake132456** [comment] 2017-12-11 11:37
You can see the image file.
I attach it.

Thanks for your kindness.

2017-12-11 20:21 GMT+09:00 Jan <notifications@github.com>:

**Comment by jsteemann** [comment] 2017-12-11 11:40
The problem is that there is no attached image when looking at the issue in Github.

**Comment by Jake132456** [comment] 2017-12-11 12:12
Okay.
I was attaching at the mail.
I'll attach it at the github.

2017-12-11 20:40 GMT+09:00 Jan <notifications@github.com>:

**Comment by dothebart** [comment] 2017-12-11 12:15
Hi, 
you have to stop the running arangodb service first using: 

`net stop arangodb`

after changing the password you can restart it again using 

`net start arangodb`

**Comment by Jake132456** [comment] 2017-12-11 12:21
I killed arangod at the task manager in windows10
And resetting the password.
Is it not enough?

**Comment by Jake132456** [comment] 2017-12-11 12:24
I can't understand because after I had problem for all user, I reinstalled it for the current user.
I didn't typed any password, however, they required me the password and username.
Login failed.

**Comment by dothebart** [comment] 2017-12-11 12:51
You will be requried to specify a password, even if its empty. Now you've changed the password, you should re-start the arangod.exe or the service. 
You now should be able to talk to it with the password you just gave it.

**Comment by Jake132456** [comment] 2017-12-11 13:04
You mean I have to type net stop arangodb at the cmd?

2017년 12월 11일 월요일, Wilfried Goesgens<notifications@github.com>님이 작성한 메시지:

**Comment by dothebart** [comment] 2017-12-11 13:29
see https://technet.microsoft.com/en-us/library/bb490713.aspx for more details.

**Comment by Jake132456** [comment] 2017-12-12 00:28
![default](https://user-images.githubusercontent.com/28842033/33860951-7f6381c8-df1e-11e7-920b-3fbe9a07d6f6.png)
I got this error message.
Access was denied even though 'net stop arangodb' >'arango secure installation.exe' > enter password(new password)

**Comment by OmarAyo** [comment] 2018-03-28 11:57
Hi @Jake132456 

It is hard to read your last attachment. 
By the way, how things are going ? Still facing the same problem ?

Best

**Comment by maxkernbach** [comment] 2018-06-12 09:54
I am closing this issue for now as we have not received any feedback for over two months.

Please feel free to comment and reopen in case this problem persists.

**Closed by maxkernbach** 2018-06-12 09:54 UTC
Labels: 1 Question, 4 Windows, Waiting User Reply
