### ISSUE TITLE
Skiplist Indexes cannot be used when using a dynamic variable in AQL query

### ISSUE THREAD

**Issue by Sukrat** [arangodb/arangodb#4831] opened 2018-03-13 01:47 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser: Chrome running on this OS: Windows 10
- [ ] arangosh
- [ ] this Driver:

The AQL query in question is:

So, my collection `data` has the following schema is `{ col1: Double, col2: Double, col3: Double }`.
I have created skiplist indexes on all the attributes of collection `data`.

and the query I am running is:

    FOR a IN data
        LIMIT 10
        LET elem = (
            FOR b IN data
            FILTER (b.col1 >= (-@tol + a.col1) && b.col1 <= (@tol + a.col1))
            RETURN { _from: a._id, _to: b._id }
        )
        FOR e IN elem
            INSERT e INTO clust

My question is when I use `FILTER (b.col1 >= (-@tol) && b.col1 <= (@tol))` and see the explaination of the query. I can see that the skiplist index will be used.
But when I use `FILTER (b.col1 >= (-@tol + a.col1) && b.col1 <= (@tol + a.col1))`  where `a` is element of outside `for`. _The explain command shows me Indexes used None_. Why can't ArangoDB able to use skiplist when filtering with a dynamic variable but is able to when using the query parameters?

**Comment by jsteemann** [comment] 2018-03-13 07:19
I tried to reproduce it with the instructions above, and the skiplist index is well used in my case.

So I guess that the indexes that you created are sparse, so they will not be used in the latter query.
Examples following:

**with non-sparse skiplist index on col1**:
Here the skiplist index will be used for both queries as expected:
```
Query string:
 FOR a IN data     LIMIT 10     LET elem = (         FOR b IN data         FILTER (b.col1 >= (-@tol) 
 && b.col1 <= (@tol))         RETURN { _from: a._id, _to: b._id }     )     FOR e IN elem         
 INSERT e INTO clust

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode   2000     - FOR a IN data   /* full collection scan, projection: `_id` */
  3   LimitNode                   10       - LIMIT 0, 10
 13   IndexNode                 2660       - FOR #13 IN data   /* skiplist index scan */
  8   CalculationNode           2660         - LET e = { "_from" : a, "_to" : #13.`_id` }   /* simple expression */   /* collections used: a : data */
 12   InsertNode                   0         - INSERT e IN clust

Indexes used:
 By   Type       Collection   Unique   Sparse   Selectivity   Fields       Ranges
 13   skiplist   data         false    false       100.00 %   [ `col1` ]   ((#13.`col1` >= -3) && (#13.`col1` <= 3))
```

```
Query string:
 FOR a IN data     LIMIT 10     LET elem = (         FOR b IN data         FILTER (b.col1 >= (-@tol + 
 a.col1) && b.col1 <= (@tol + a.col1))         RETURN { _from: a._id, _to: b._id }     )     FOR e IN 
 elem         INSERT e INTO clust

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode   2000     - FOR a IN data   /* full collection scan */
  3   LimitNode                   10       - LIMIT 0, 10
 13   IndexNode                 2660       - FOR #13 IN data   /* skiplist index scan */
  8   CalculationNode           2660         - LET e = { "_from" : a.`_id`, "_to" : #13.`_id` }   /* simple expression */   /* collections used: a : data */
 12   InsertNode                   0         - INSERT e IN clust

Indexes used:
 By   Type       Collection   Unique   Sparse   Selectivity   Fields       Ranges
 13   skiplist   data         false    false       100.00 %   [ `col1` ]   ((#13.`col1` >= (10 + a.`col1`)) && (#13.`col1` <= (-10 + a.`col1`)))
```

Now trying the same with a sparse skiplist index.

**with sparse skiplist index on col1**:

Here the skiplist index will only be used for the query that specifies the range by the hard-coded bind parameter:
```
Query string:
 FOR a IN data     LIMIT 10     LET elem = (         FOR b IN data         FILTER (b.col1 >= (-@tol) 
 && b.col1 <= (@tol))         RETURN { _from: a._id, _to: b._id }     )     FOR e IN elem         
 INSERT e INTO clust

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode   2000     - FOR a IN data   /* full collection scan, projection: `_id` */
  3   LimitNode                   10       - LIMIT 0, 10
 13   IndexNode                 2660       - FOR #13 IN data   /* skiplist index scan */
  8   CalculationNode           2660         - LET e = { "_from" : a, "_to" : #13.`_id` }   /* simple expression */   /* collections used: a : data */
 12   InsertNode                   0         - INSERT e IN clust

Indexes used:
 By   Type       Collection   Unique   Sparse   Selectivity   Fields       Ranges
 13   skiplist   data         false    true        100.00 %   [ `col1` ]   ((#13.`col1` >= -3) && (#13.`col1` <= 3))
```

When using some arithmetic calculation (bind parameter plus/minus dynamic value) the query optimizer is not able to prove the range will exclude the value `null`. `null` values however are not included in sparse indexes, so the optimizer has no choice but to not use the index and fall back to a full collection scan here. Otherwise the query result (in terms of number of documents returned) may be different when using the index vs. when not using the index:
```
Query string:
 FOR a IN data     LIMIT 10     LET elem = (         FOR b IN data         FILTER (b.col1 >= (-@tol + 
 a.col1) && b.col1 <= (@tol + a.col1))         RETURN { _from: a._id, _to: b._id }     )     FOR e IN 
 elem         INSERT e INTO clust

Execution plan:
 Id   NodeType                   Est.   Comment
  1   SingletonNode                 1   * ROOT
  2   EnumerateCollectionNode    2000     - FOR a IN data   /* full collection scan */
  3   LimitNode                    10       - LIMIT 0, 10
  5   EnumerateCollectionNode   20000       - FOR #13 IN data   /* full collection scan */
  6   CalculationNode           20000         - LET #12 = ((#13.`col1` >= (10 + a.`col1`)) && (#13.`col1` <= (-10 + a.`col1`)))   /* simple expression */   /* collections used: a : data */
  7   FilterNode                20000         - FILTER #12
  8   CalculationNode           20000         - LET e = { "_from" : a.`_id`, "_to" : #13.`_id` }   /* simple expression */   /* collections used: a : data */
 12   InsertNode                    0         - INSERT e IN clust

Indexes used:
 none
```
So the solution for the problem is probably to create non-sparse indexes.

**Comment by Sukrat** [comment] 2018-03-13 10:21
Yes, I did have the index as sparse. That makes sense, Thank you @jsteemann !

**Comment by OmarAyo** [comment] 2018-03-13 14:34
Hi @Sukrat 

I am going to close the issue, feel free to re-open it if the issue occurs again.

Best

**Closed by OmarAyo** 2018-03-13 14:34 UTC
Labels: 1 Question, 2 Solved, 3 AQL
