### ISSUE TITLE
Restart Arango

### ISSUE THREAD

**Issue by tthil** [arangodb/arangodb#1911] opened 2016-06-30 07:43 UTC
Hi,
I develop a Foxx application in Arango. To make sure the current code is actually running I need to restart Arango. If not I will not be able to know if the code running is the previous code or current. This makes the process of development very hard and slow. 
Is there any way to make sure Arango runs the current code?

//Thomas

**Comment by dothebart** [comment] 2016-06-30 08:36
You should be able to click in the webinterface on `services-><your instance>->settings->Set Development` - then the your Foxx service isn't cached and you can edit it with the changes taking effect immediately at the next execution. You should be able to use console.log() to print entries into the ArangoDB log file.

**Comment by tthil** [comment] 2016-06-30 10:53
My Foxx application has always been set to Development but sometimes the changes in code has no effect until I restart Arango. I first noticed this when I added a console.log and noting was printed out until restart Arango.

//Thomas

**Comment by jsteemann** [comment] 2016-06-30 13:53
Can you provide a bit more information about what kind of code changes don't become visible in your Foxx app in development mode? Without that it's mainly guessing what could be happening.

I would think that after making modifications to a JavaScript file of your Foxx apps, the changes just made don't become visible when a route in the Foxx app is reloaded. Is that correct? If so, what's the route's URL and HTTP method?
And how is the Foxx app's route called (from browser, via curl, from application?) and can client-side caching be excluded as a potential cause?
Additionally, which part of the Foxx app are you changing (a manifest file, a controller file, a repository, model or any include other file), and how is that part loaded (require?).
Thanks!

**Comment by pluma** [comment] 2016-07-14 11:08
This seems like an exact duplicate of #1927 which has an example service demonstrating the problem.

**Closed by pluma** 2016-07-14 11:08 UTC
