### ISSUE TITLE
Server crashes with FILTER in AQL query (after upgrade from 3.4 to 3.7)

### ISSUE THREAD

**Issue by miguel-porto** [arangodb/arangodb#13124] opened 2020-12-01 13:18 UTC
## My Environment

* __ArangoDB Version__:        3.7.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        12Gb
* __Disks in use__:        SSD
* __Used Package__:              Ubuntu .deb

## Component, Query & Data

__Affected feature__:
AQL query using both the web interface or the Java driver

__AQL query (if applicable)__:
```
FOR v, e, p IN 1..100 OUTBOUND "taxent/340942205854" PART_OF, ANY SYNONYM OPTIONS {uniqueVertices: 'path'}
    LET children = (FOR v1, e1, p1 IN 1..5 INBOUND v PART_OF, ANY SYNONYM OPTIONS {uniqueVertices: 'path'}
        LET po = (FOR i IN p1.edges FILTER IS_SAME_COLLECTION('PART_OF', i) LIMIT 2 RETURN 1) 
        LET lpo = LENGTH(po)
        FILTER lpo == 1
        LIMIT 2 RETURN 1)
    RETURN {id:v._id, c:LENGTH(children)}
```
__AQL explain and/or profile (if applicable)__:
```
Query String (525 chars, cacheable: true):
 /* Climb up the taxonomic tree to see which is the highest node that encloses only this one */
 FOR v, e, p IN 1..100 OUTBOUND "taxent/340942205854" PART_OF, ANY SYNONYM OPTIONS {uniqueVertices: 
 'path'}
     LET children = (FOR v1, e1, p1 IN 1..5 INBOUND v PART_OF, ANY SYNONYM OPTIONS {uniqueVertices: 
 'path'}
         LET po = (FOR i IN p1.edges FILTER IS_SAME_COLLECTION('PART_OF', i) LIMIT 2 RETURN 1) 
         LET lpo = LENGTH(po)
         FILTER lpo == 1
         LIMIT 2 RETURN 1)
     RETURN {id:v._id, c:LENGTH(children)}
 

Execution plan:
 Id   NodeType                Est.   Comment
  1   SingletonNode              1   * ROOT
  2   TraversalNode       53144100     - FOR v  /* vertex */ IN 1..100  /* min..maxPathDepth */ OUTBOUND 'taxent/340942205854' /* startnode */  PART_OF, ANY SYNONYM
 25   SubqueryStartNode   53144100       - LET children = ( /* subquery begin */
  4   TraversalNode           3125         - FOR v1  /* vertex */, p1  /* paths */ IN 1..5  /* min..maxPathDepth */ INBOUND v /* startnode */  PART_OF, ANY SYNONYM
 27   SubqueryStartNode       3125           - LET po = ( /* subquery begin */
  6   CalculationNode         3125             - LET #18 = p1.`edges`   /* attribute expression */
  7   EnumerateListNode     312500             - FOR i IN #18   /* list iteration */
  8   CalculationNode       312500               - LET #20 = IS_SAME_COLLECTION("PART_OF", i)   /* simple expression */
  9   FilterNode            312500               - FILTER #20
 10   LimitNode                  2               - LIMIT 0, 2
 23   CalculationNode            2               - LET #30 = true   /* json expression */   /* const assignment */
 28   SubqueryEndNode            2               - RETURN  #30 ) /* subquery end */
 14   CalculationNode            2           - LET lpo = LENGTH(po)   /* simple expression */
 15   CalculationNode            2           - LET #24 = (lpo == 1)   /* simple expression */
 16   FilterNode                 2           - FILTER #24
 17   LimitNode                  2           - LIMIT 0, 2
 24   CalculationNode            2           - LET #32 = true   /* json expression */   /* const assignment */
 26   SubqueryEndNode            2           - RETURN  #32 ) /* subquery end */
 21   CalculationNode            2       - LET #28 = { "id" : v.`_id`, "c" : LENGTH(children) }   /* simple expression */
 22   ReturnNode                 2       - RETURN #28

Indexes used:
 By   Name   Type   Collection   Unique   Sparse   Selectivity   Fields        Ranges
  2   edge   edge   PART_OF      false    false        98.86 %   [ `_from` ]   base OUTBOUND
  2   edge   edge   SYNONYM      false    false        90.24 %   [ `_to` ]     base INBOUND
  2   edge   edge   SYNONYM      false    false        99.27 %   [ `_from` ]   base OUTBOUND
  4   edge   edge   PART_OF      false    false        32.52 %   [ `_to` ]     base INBOUND
  4   edge   edge   SYNONYM      false    false        90.24 %   [ `_to` ]     base INBOUND
  4   edge   edge   SYNONYM      false    false        99.27 %   [ `_from` ]   base OUTBOUND

Functions used:
 Name                 Deterministic   Cacheable   Uses V8
 IS_SAME_COLLECTION   true            true        false  
 LENGTH               true            true        false  

Traversals on graphs:
 Id  Depth   Vertex collections  Edge collections  Options                                  Filter / Prune Conditions
 2   1..100                      PART_OF, SYNONYM  uniqueVertices: path, uniqueEdges: path                           
 4   1..5                        PART_OF, SYNONYM  uniqueVertices: path, uniqueEdges: path                           

Optimization rules applied:
 Id   RuleName
  1   optimize-subqueries
  2   move-calculations-up-2
  3   optimize-traversals
  4   remove-unnecessary-calculations-2
  5   splice-subqueries
```

__Dataset__:
Can send the debug package if needed.

__Size of your Dataset on disk__:

__Problem__:
Hello!
When running the above query, no results are issued and I get the error:

`Query: AQL: cannot use shrink() to increase block (exception location: /work/ArangoDB/arangod/Aql/AqlItemBlock.cpp:372). (while executing) (exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:311)`

And sometimes the server crashes. This happens in both installations I'm using (different machines, same data). The problem is at the line `FILTER lpo == 1` : removing this line, the query runs ok. This problem started to happen when I upgraded form version 3.4 to 3.7.
Let me know if you need the debug package.
Thanks!

**Comment by maxkernbach** [comment] 2020-12-02 10:52
Hi @miguel-porto,

Thanks for reporting.

How big is the dataset that is causing the error and would it be possible to share it?
If so, please contact me in the ArangoDB community slack (user: maxk.arangodb) and I will provide a private upload link.

**Comment by miguel-porto** [comment] 2020-12-02 22:30
Hello, thanks for the reply,
Don't have slack account, but no problem to send you the dataset by email. Let me know.

**Comment by maxkernbach** [comment] 2020-12-02 22:39
Hi @miguel-porto,

Sure, if the dataset is not too big for a mail attachment, send us a mail to hackers@arangodb.com and attach the dump. Please reference the number of this issue in your email.

**Comment by miguel-porto** [comment] 2020-12-02 22:42
Sent!
Thanks @maxkernbach

**Comment by maxkernbach** [comment] 2020-12-03 11:38
@miguel-porto Thank you, we have been able to reproduce the issue as described.

**Comment by miguel-porto** [comment] 2020-12-03 12:29
Excellent! Thanks @maxkernbach .
BTW, I downgraded to 3.4 and I confirm that the issue does not happen in that version.

**Comment by miguel-porto** [comment] 2020-12-04 00:00
The problem should be in the splice-subqueries optimization of 3.7, as disabling it, the query runs ok.

**Comment by abrekhov** [comment] 2020-12-05 15:48
@miguel-porto : I've faced same issue here https://github.com/arangodb/arangodb/issues/13147 .
How did you switched off  splice-subqueries optimization?
Thanks!

**Comment by miguel-porto** [comment] 2020-12-05 18:20
Hmmm, I guess that depends on how you're issuing the query... in my case, using the Java driver, it's plain easy, just pass the query options along with the query:
`new AqlQueryOptions().rules(Collections.singleton("-splice-subqueries"))`
I did not find a way to switch it off globally when starting the server... `arangod --help-query`

**Comment by abrekhov** [comment] 2020-12-05 18:45
@miguel-porto : I've turned it off with `arangod --query.optimizer-rules "splice-subqueries" ` flag.
Thanks anyway!

**Comment by miguel-porto** [comment] 2020-12-05 19:53
Huh? That's not documented in the `arangod --help`! Thanks for the hint!

**Comment by abrekhov** [comment] 2020-12-05 20:58
@miguel-porto I've found it here: https://www.arangodb.com/docs/3.7/programs-arangod-query.html#optimizer-rule-defaults

**Comment by miguel-porto** [comment] 2020-12-05 21:36
Thanks @abrekhov .

**Comment by abrekhov** [comment] 2020-12-06 20:35
@maxkernbach : I've disable splice subqueries and it doesn't help.

**Comment by goedderz** [comment] 2020-12-07 09:41
> @miguel-porto : I've turned it off with `arangod --query.optimizer-rules "splice-subqueries" ` flag.
> Thanks anyway!

It has to spell `--query.optimizer-rules "-splice-subqueries"`; observe the leading `-`.

**Comment by abrekhov** [comment] 2020-12-07 10:08
@goedderz thank you! That helped! No error occurred after disabling this feature.

**Comment by maxkernbach** [comment] 2020-12-08 09:59
> Huh? That's not documented in the `arangod --help`! Thanks for the hint!

@miguel-porto This option is currently listed as a hidden option. It will only show with `arangod --help-.` as below:

```
max@maxk:~$ arangod --help-. | grep -A 1 query.optimizer-rules
  --query.optimizer-rules <string...>                          enable or disable specific optimizer rules (use rule name prefixed with '-' for disabling, '+' for enabling) (default: 
                                                               ) (introduced in v3.6.0)
```

**Comment by Simran-B** [comment] 2020-12-08 10:31
To clarify: hidden just means that an option isn't listed by default (when running `--help`) in order to limit the amount of information that is printed to the terminal. You can use `--help-.` or `--help-all` to list all available options.

**Comment by miguel-porto** [comment] 2020-12-08 10:58
Ok, thanks for the hints!

**Comment by goedderz** [comment] 2020-12-09 11:15
It turns out that, while not obvious from the behaviour, this is actually a duplicate of https://github.com/arangodb/arangodb/issues/13099. A fix is being worked on.

**Comment by Simran-B** [comment] 2021-02-12 15:11
Hi @miguel-porto ,

v3.7.7 with a fix for the problem is now available. Please let us know if the issue is fully resolved.

Thanks

**Comment by maxkernbach** [comment] 2021-03-24 15:41
Hi @miguel-porto,

Did you have a chance to upgrade and test the fix?

**Closed** 2021-05-05 14:37 UTC
Labels: 1 Bug, 1 Duplicate, 2 Fixed, 3 AQL, Waiting User Reply
