### ISSUE TITLE
Search problems (doesn't find everything it should)

### ISSUE THREAD

**Issue by ile** [arangodb/arangodb#2074] opened 2016-09-24 04:43 UTC
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [x] 3.0.9

On this operating system:
- [x] Ubuntu .deb

I'm issuing AQL via:
- [x] arangosh
- [x] this Driver: arangojs

The AQL query in question is: 
`db._query('FOR c IN FULLTEXT(items , @v0 , @v1 , @v2) RETURN c.data', { v0: 'data',      v1: 'prefix:pomm',      v2: 10 } );`

The search should find items but the above query returns 0: 

```
127.0.0.1:8529@some> db._query('FOR c IN FULLTEXT(items , @v0 , @v1 , @v2) RETURN c.data', { v0: 'data',      v1: 'prefix:pomm',      v2: 10 } );
[object ArangoQueryCursor, count: 0, hasMore: false]
```

If I change the limit to 100, it will find the relevant items (all of them I guess):

```
127.0.0.1:8529@some> db._query('FOR c IN FULLTEXT(items , @v0 , @v1 , @v2) RETURN c.data', { v0: 'data',      v1: 'prefix:pomm',      v2: 100 } );
[object ArangoQueryCursor, count: 6, hasMore: false]


[ 
  "Pomm", 
  "Pomm pomm...", 
  "Pomm pomm xxx", 
  "Pomm pommi", 
  "pommi pommi", 
  "pomm http://blogit.iltalehti.fi/pauli-vahtera/2016/09/24/suomen-sosialistinen-ne..." 
]
```

If I change the limit to 30 it will not find all of those it did with the limit of 100:

```
127.0.0.1:8529@some> db._query('FOR c IN FULLTEXT(items , @v0 , @v1 , @v2) RETURN c.data', { v0: 'data',      v1: 'prefix:pomm',      v2: 30 } );
[object ArangoQueryCursor, count: 4, hasMore: false]


[ 
  "Pomm", 
  "Pomm pomm...", 
  "Pomm pomm xxx", 
  "Pomm pommi" 
]

```

Now, I can't reproduce this problem if I do arangodump/arangorestore. The problem can be reproduced only with the current database that is running/installed. If I do arangodump/arangorestore the search _will work_ with the restored dataset.

I don't know how to get you this dataset that has the problem? (Also I'm not even sure I want to send this dataset to anywhere ...)

Maybe you can think of what could be wrong and reproduce this?

**Comment by jsteemann** [comment] 2016-09-26 09:05
I think the issue is related to #2072, which was fixed in 3.0.10. That means 3.0.10 should fix this issue as well.

**Comment by dothebart** [comment] 2016-09-27 14:22
3.0.10 is available for download; @ile can you revalidate whether it fixes this issue?

**Comment by dothebart** [comment] 2016-11-25 14:33
3.0.12 is available for download via the regular upgrade channels - closing.

**Closed by dothebart** 2016-11-25 14:33 UTC
Labels: 1_Bug, aql, Fixed
