### ISSUE TITLE
Out of memory error on 3.2 with RocksDB

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#3005] opened 2017-08-09 12:20 UTC
## my environment running ArangoDB
- [x] 3.2

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

I have a high number of out of memory errors in my Foxx scripts. It seems that all of them concern the same operation (a replace within a transaction). I should clarify that there is plenty of available memory on the server. Full stack trace:
```at execute (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1234:7)
at callback (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/service.js:347:35)
at Tree.dispatch (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:135:7)
at dispatch (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:426:3)
at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:412:15)
at Route._handler (/var/lib/arangodb3-apps/_db/keakr/commands/APP/routes/common2.js:23:8)
at ArangoDatabase._executeTransaction (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:130:10)
at action (/var/lib/arangodb3-apps/_db/keakr/commands/APP/routes/common2.js:49:49)
via ArangoError: out of memory
Service "/commands" encountered error 500 while handling POST http://xxx.westeurope.cloudapp.azure.com:8529/_db/keakr/commands/v1/common/createLike?userEdge=isAuthorOf
encountered out-of-memory error
```

For reference:
`common2.js:23:8` is the start of the transaction
`common2.js:49:49` is the replace operation

I couldn't find any reference to that particular error so I'm wondering what could cause it?

Thanks in advance

**Comment by jsteemann** [comment] 2017-08-09 12:33
Potentially has the same root cause as 
https://github.com/arangodb/arangodb/issues/2810

Is there a fulltext index present for the collection in question?

**Comment by ThomasWeiss** [comment] 2017-08-09 12:37
Indeed, there is a full-text index on that collection!

**Comment by jsteemann** [comment] 2017-08-09 12:41
Then this bug is hopefully fixed in 3.2.1. The out-of-memory error is wrong here. This error occurs when a document is inserted into the fulltext index that does not have the indexed attribute or for which no words will be inserted into the index.
The error is just wrong. Instead the operation should just continue, even without inserting anything into the index.

**Comment by ThomasWeiss** [comment] 2017-08-09 12:44
Great news, thanks Jan. You probably guess my next question: any ETA for the 3.2.1?

**Comment by jsteemann** [comment] 2017-08-10 09:24
3.2.1 is already built, and is currently being tested internally. When that testing is done, it will be released.
I expect this to happen this week.

**Comment by jsteemann** [comment] 2017-08-11 09:27
3.2.1 has been released and is [available for download](https://www.arangodb.com/download-major/).

**Closed by jsteemann** 2017-08-11 09:27 UTC
Labels: 1 Bug, 2 Fixed
