### ISSUE TITLE
Graph AQL Traversal Filter Optimisation

### ISSUE THREAD

**Issue by osveco** [arangodb/arangodb#8112] opened 2019-02-05 11:14 UTC
## My Environment

* __ArangoDB Version__:        3.4.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Serve
* __Deployment Strategy__:  Manual Start in Docker
* __Configuration__:               N/A
* __Infrastructure__:               own
* __Operating System__:        CentOS 7
* __Total RAM in your machine__:         32Gb
* __Disks in use__:        HDD
* __Used Package__:             Docker - official Docker library

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
FOR v, e, p  IN 1..3 ANY  "person/3" GRAPH "testgraph"   OPTIONS {uniqueVertices:"path", uniqueEdges:"path", bfs:true}  FILTER v._id == "person/391"  LIMIT 20000000 
  RETURN p

__AQL explain (if applicable)__:
Query String:
 FOR v, e, p  IN 1..3 ANY  "person/3" GRAPH "testgraph"   OPTIONS {uniqueVertices:"path", 
 uniqueEdges:"path", bfs:true}  FILTER v._id == "person/391"  LIMIT 20000000 
   RETURN p

Execution plan:
 Id   NodeType              Est.   Comment
  1   SingletonNode            1   * ROOT
  2   TraversalNode     13824000     - FOR v  /* vertex */, p  /* paths */ IN 1..3  /* min..maxPathDepth */ ANY 'person/3' /* startnode */  GRAPH 'testgraph'
  3   CalculationNode   13824000       - LET #5 = (v.`_id` == "person/391")   /* simple expression */
  4   FilterNode        13824000       - FILTER #5
  5   LimitNode         13824000       - LIMIT 0, 20000000
  6   ReturnNode        13824000       - RETURN p

Indexes used:
 By   Type   Collection         Unique   Sparse   Selectivity   Fields        Ranges
  2   edge   from               false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   from               false    false            n/a   [ `_from` ]   base OUTBOUND
  2   edge   has_bank_account   false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   has_bank_account   false    false            n/a   [ `_from` ]   base OUTBOUND
  2   edge   has_list           false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   has_list           false    false            n/a   [ `_from` ]   base OUTBOUND
  2   edge   is_in              false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   is_in              false    false            n/a   [ `_from` ]   base OUTBOUND
  2   edge   is_on_list         false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   is_on_list         false    false            n/a   [ `_from` ]   base OUTBOUND
  2   edge   is_on_watchlist    false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   is_on_watchlist    false    false            n/a   [ `_from` ]   base OUTBOUND
  2   edge   lives_at           false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   lives_at           false    false            n/a   [ `_from` ]   base OUTBOUND
  2   edge   located_at         false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   located_at         false    false            n/a   [ `_from` ]   base OUTBOUND
  2   edge   money_transfer     false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   money_transfer     false    false            n/a   [ `_from` ]   base OUTBOUND
  2   edge   owned_by           false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   owned_by           false    false            n/a   [ `_from` ]   base OUTBOUND
  2   edge   part_of            false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   part_of            false    false            n/a   [ `_from` ]   base OUTBOUND
  2   edge   phone_call         false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   phone_call         false    false            n/a   [ `_from` ]   base OUTBOUND
  2   edge   received           false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   received           false    false            n/a   [ `_from` ]   base OUTBOUND
  2   edge   sent               false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   sent               false    false            n/a   [ `_from` ]   base OUTBOUND
  2   edge   to                 false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   to                 false    false            n/a   [ `_from` ]   base OUTBOUND
  2   edge   visited            false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   visited            false    false            n/a   [ `_from` ]   base OUTBOUND
  2   edge   withdrawl          false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   withdrawl          false    false            n/a   [ `_from` ]   base OUTBOUND

Traversals on graphs:
 Id   Depth   Vertex collections                                                                                     Edge collections                                                                                                                                                                    Options                                              Filter conditions
  2   1..3    address, bank_account, cell, company, contact_list, package, person, phone_number, prison, watchlist   from, has_bank_account, has_list, is_in, is_on_list, is_on_watchlist, lives_at, located_at, money_transfer, owned_by, part_of, phone_call, received, sent, to, visited, withdrawl   bfs: true, uniqueVertices: path, uniqueEdges: path   

Optimization rules applied:
 Id   RuleName
  1   optimize-traversals

+profiler:
 Id   NodeType          Calls   Items   Runtime [s]   Comment
  1   SingletonNode         1       1       0.00001   * ROOT
  2   TraversalNode        45   44414       2.84142     - FOR v  /* vertex */, p  /* paths */ IN 1..3  /* min..maxPathDepth */ ANY 'person/3' /* startnode */  GRAPH 'testgraph'
  3   CalculationNode      45   44414       0.03403       - LET #5 = (v.`_id` == "person/391")   /* simple expression */
  4   FilterNode            1      14       0.01281       - FILTER #5
  5   LimitNode             2      14       0.00002       - LIMIT 0, 20000000
  6   ReturnNode            1      14       0.00002       - RETURN p

__Dataset__:
"part_of", ["company"], ["person"]
"withdrawl", ["person"], ["bank_account"]
"has_bank_account", ["person"], ["bank_account"]
"money_transfer", ["bank_account"], ["bank_account"]
"owned_by", ["person"], ["phone_number"]
"phone_call", ["person"], ["phone_number"]
"visited", ["person"], ["person"]
"lives_at", ["person"], ["address"]
"sent", ["person"], ["package"]
"received", ["person"], ["package"]
"from", ["package"], ["address"]
"to", ["package"], ["address"]
"is_on_list", ["person"], ["contact_list"]
"located_at", ["person"], ["cell"]
"is_in", ["cell"], ["prison"]
"is_on_watchlist", ["person"], ["watchlist"]
"has_list", ["person"], ["contact_list"]

Cannot share the data itself.

__Size of your Dataset on disk__:
Couple of MBs, the size of data is not that relevant to the issue

__Replication Factor & Number of Shards (Cluster only)__:
N/A

## Steps to reproduce

1. Initiate the graph
2. Load in some test data (can be fairly random as we are just using _id)
3. Execute the AQL query above

__Problem__:
Out of the profiler and also the Explain it is evident, that the filter is applied after the Traversal, e.g. 1st is the full traversal to depth 3 and only after it is complete, the filter is applied.

__Expected result__:
Filter be applied during the traversal. What we need is, to filter last vertex of the path while we are traversing. We are able to do that for example for depth 3 in three separate AQL traversals as follows: 

Query String:
 LET a = (
      FOR v, e, p  IN 1 ANY  "person/3" GRAPH "testgraph"   OPTIONS {uniqueVertices:"path", 
 uniqueEdges:"path", bfs:true}  FILTER p.vertices[1]._id == "person/391"  LIMIT 20000000 return p
   )
 LET b = (
      FOR v, e, p  IN 2 ANY  "person/3" GRAPH "testgraph"   OPTIONS {uniqueVertices:"path", 
 uniqueEdges:"path", bfs:true}  FILTER p.vertices[2]._id == "person/391"  LIMIT 20000000 return p
   )
 LET c = (
      FOR v, e, p  IN 3 ANY  "person/3" GRAPH "testgraph"   OPTIONS {uniqueVertices:"path", 
 uniqueEdges:"path", bfs:true}  FILTER p.vertices[3]._id == "person/391"  LIMIT 20000000 return p
   )
   RETURN MERGE({"1" : a},{"2" : b},{"3" : c})
 

Execution plan:
 Id   NodeType          Calls   Items   Runtime [s]   Comment
  1   SingletonNode         1       1       0.00001   * ROOT
  8   SubqueryNode          1       1       0.00142     - LET a = ...   /* const subquery */
  2   SingletonNode         1       1       0.00001       * ROOT
  3   TraversalNode         1       0       0.00136         - FOR v  /* vertex */, p  /* paths */ IN 1..1  /* min..maxPathDepth */ ANY 'person/3' /* startnode */  GRAPH 'testgraph'
  6   LimitNode             1       0       0.00002           - LIMIT 0, 20000000
  7   ReturnNode            1       0       0.00001           - RETURN p
 15   SubqueryNode          1       1       0.02328     - LET b = ...   /* const subquery */
  9   SingletonNode         1       1       0.00001       * ROOT
 10   TraversalNode         1       0       0.02322         - FOR v  /* vertex */, p  /* paths */ IN 2..2  /* min..maxPathDepth */ ANY 'person/3' /* startnode */  GRAPH 'testgraph'
 13   LimitNode             1       0       0.00002           - LIMIT 0, 20000000
 14   ReturnNode            1       0       0.00001           - RETURN p
 22   SubqueryNode          1       1       0.79065     - LET c = ...   /* const subquery */
 16   SingletonNode         1       1       0.00001       * ROOT
 17   TraversalNode         1      14       0.79057         - FOR v  /* vertex */, p  /* paths */ IN 3..3  /* min..maxPathDepth */ ANY 'person/3' /* startnode */  GRAPH 'testgraph'
 20   LimitNode             2      14       0.00002           - LIMIT 0, 20000000
 21   ReturnNode            1      14       0.00003           - RETURN p
 23   CalculationNode       1       1       0.00019     - LET #30 = MERGE({ "1" : a }, { "2" : b }, { "3" : c })   /* simple expression */
 24   ReturnNode            1       1       0.00001     - RETURN #30

Now that will return the same amount of results as the first AQL but will take significantly lower amount of time and use lower RAM as it does not first load all the paths and then filter. Question really is, can I do that in a single AQL query or do I have to do it this way so the optimiser works properly? Or is there some best practice ? What we are doing really is finding all paths from A to B, potentially on large datasets and therefore it really matters if we filter during traversal or after.

Thanks for help/investigation of this.

**Comment by Simran-B** [comment] 2019-02-05 14:21
Labeling this as a feature request, because the current behavior (post-filter) is working as intended, but there will be a new keyword PRUNE to apply filters during traversal soon.

**Comment by maxkernbach** [comment] 2019-08-16 14:40
Hi @osveco,

I am closing this issue as fixed since the PRUNE feature was introduced in 3.4.5 and 3.5 RC1.

>Pruning is the easiest variant to formulate conditions to reduce the amount of data to be checked during a search. So it allows to improve query performance and reduces the amount of overhead generated by the query. Pruning can be executed on the vertex, the edge and the path and any variable defined before.

This [video tutorial](https://www.youtube.com/watch?v=wex3Nb2RYQE) shows the difference between FILTER and the new PRUNE with a hands-on example. You can find more details in our [documentation](https://www.arangodb.com/docs/3.4/aql/graphs-traversals.html#pruning).

**Closed by maxkernbach** 2019-08-16 14:40 UTC
Labels: 1 Feature, 3 AQL, 3 Graph
