### ISSUE TITLE
Foxx Add Application from Private Github

### ISSUE THREAD

**Issue by riverdusty** [arangodb/arangodb#1464] opened 2015-08-31 14:59 UTC
This would be really nice for the corporate product I'm developing for the company I work for.
Feature Request? ;)

**Comment by pluma** [comment] 2015-08-31 15:39
I'm suspecting this is a duplicate of #1331?

I agree, the feature would be very nice to have. If you have any input on what the authorized URLs for private repos on GitHub are supposed to look like or what I'm doing wrong, that would help a lot.

**Closed by pluma** 2015-08-31 15:39 UTC

**Comment by dothebart** [comment] 2015-08-31 15:48
You can actually overrule the FOXX-base like this:
export FOXX_BASE_URL="http://somehost/fakegit/"

However, you have to mimic the foxx repository structure there.
