### ISSUE TITLE
STARTS_WITH function doesn't correctly return result

### ISSUE THREAD

**Issue by homo-sapiens-github** [arangodb/arangodb#12391] opened 2020-08-09 14:23 UTC
## My Environment

* __ArangoDB Version__:        3.6.4
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               n/a
* __Infrastructure__:              own
* __Operating System__:       MacOS 10.15.6
* __Total RAM in your machine__:        8Gb
* __Disks in use__:        SSD
* __Used Package__:              dmg

## Component, Query & Data

__Affected feature__:
Arango SEARCH with function STARTS_WITH 

__AQL query (if applicable)__:
```
FOR doc IN item_search
              SEARCH ANALYZER(STARTS_WITH(doc.title, "Tttt"), "text_en")
              RETURN {doc:doc.title}
```

__AQL explain (if applicable)__:

__Dataset__:
Collection: item with 3 docs having attributes '1111', '4444', 'Tttt' respectively. 
View: item_search

```json
{
  "type": "arangosearch",
  "links": {
    "Items": {
      "analyzers": [ "identity" ],
      "fields": {
        "title": {
          "analyzers": [ "text_en" ]
        },
        "tags": {
          "analyzers": [ "text_en" ]
        }
      },
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    }
  }
}
```

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
There is a doc with title "Tttt" in the collection. If we search and use STARTS_WITH with "tt","ttt", "tttt", "t", it returns the doc correctly. But if we search with "Tttt" itself, it returns nothing. 

One more thing, (properly not bug) ,the search does not update after changing the doc.title from the web interface http://127.0.0.1:8529/. 

__Expected result__:

**Comment by Simran-B** [comment] 2020-08-12 11:37
The problem is probably that the indexed values are processed by the `text_en` Analyzer, which case-folds to lower-case, so `Tttt` becomes `tttt` in the index. The prefix you pass to the `STARTS_WITH()` function does not apply any normalization, so `Tttt`
will not match the indexed value of `tttt`. You can normalize it like this with the TOKENS() function:

```
FOR doc IN item_search
              SEARCH ANALYZER(STARTS_WITH(doc.title, TOKENS("Tttt", "text_en")[0], "text_en")
              RETURN {doc:doc.title}
```

**Comment by Simran-B** [comment] 2020-08-19 12:07
I take your thumbs-up as confirmation of what I suspected and will therefore close the issue. Feel free to re-open it if you still have trouble to get STARTS_WITH() to work.

**Closed by Simran-B** 2020-08-19 12:07 UTC
Labels: 1 Question, 2 Solved, 3 ArangoSearch
