### ISSUE TITLE
Scheduler Thread lead to CPU high

### ISSUE THREAD

**Issue by liuqian1990** [arangodb/arangodb#9419] opened 2019-07-06 08:11 UTC
# arangodb 3.4.5

![image](https://user-images.githubusercontent.com/8868514/60753663-b77b3b80-a008-11e9-90aa-ea507090e17d.png)

**Comment by NingLee** [comment] 2019-07-27 07:04
+1

**Comment by NingLee** [comment] 2019-07-27 07:24
+1

**Comment by Simran-B** [comment] 2019-07-30 07:34
Please fill out the complete issue template.

**Comment by NingLee** [comment] 2019-08-14 08:46
I found the case when the cpu is high.
I found a slow query `FOR v in 1..10 outbound  'xxx/key' graph  'xxxgraph' options {bfs:true,uniqueVertices:'global'} return distinct split(v._id, '/')[0]` which can execute last even 20000+ seconds.

So it consume all cpu and many memory.

**Comment by maxkernbach** [comment] 2019-08-14 15:55
Hi @NingLee,

Depending on the size of your graph a traversal with depth 10 can be quite costly. The default value for the maximum amount of memory that a single AQL query can use ([--query.memory-limit value](https://www.arangodb.com/docs/stable/programs-arangod-query.html#limiting-memory-for-aql-queries)) is **0**, meaning that there is no memory limit.

Therefore the memory growth is expected. Specifying a value for this option aborts the AQL query once the given limit value is exceeded.

Is there anything else you would like to discuss in this issue or can we consider it resolved?

**Comment by OmarAyo** [comment] 2019-08-21 14:24
Hi @NingLee 

Seems that the root cause has been sorted out hence I am closing this ticket now

Feel free to comment again and we will reopen it 

Best

**Closed by OmarAyo** 2019-08-21 14:24 UTC
Labels: Waiting User Reply
