### ISSUE TITLE
unique constraint violated over '_key' after arangorestore (padded key generator)

### ISSUE THREAD

**Issue by andrea-tesei** [arangodb/arangodb#12378] opened 2020-08-06 12:39 UTC
## My Environment

* __ArangoDB Version__:        
3.6.5
* __Storage Engine__:             
RocksDB
* __Deployment Mode__:       
Single Server
* __Deployment Strategy__:   
Manual Start in Docker
* __Configuration__:               
* __Infrastructure__:               
AWS
* __Operating System__:        
Amazon Linux 2 (Red Hat based)
* __Total RAM in your machine__:        
8GB
* __Disks in use__:        
100GB
* __Used Package__:              
Official Docker Image

## Component, Query & Data

__Affected feature__:

AQL query INSERT using arangojs driver **ONLY** after a restore

__AQL query (if applicable)__:

__Dataset__:

The documents are composed by tree keys:
db.collection.save({
uri: "URI_STRING",
node_type: "NODE_TYPE",
heading: "HEADING_NUMBER"
})

__Size of your Dataset on disk__:

500MB

## Steps to reproduce

1. Insert a set of documents in two different collections (set 'padded' key generator for these collection)
2. Create a dump with arangodump saving also system-collections
3. Restore the dump created at previous step in a fresh copy of ArangoDB 3.6.4
4. Insert a new document in a collection

__Problem__:
I'm using ArangoDB Docker container v3.6.5 and I'm experiencing a problem while indexing new documents after a restore. The DB answer with a '**unique constraint violated - in index primary of type primary over '_key'; conflicting key: 00000000000004bb**' error when I try to index a new document after a restore. 

This problem does not arises if I index new documents in the empty database. It only appears after a restore operation. I use arangorestore command from within the container to restore the dump previously created with arangodump. It seems that the key generator for the given collection does not update the 'counter' after restore and returns the error as soon as a new insert operation is executed. I use 'padded' key generator for the collections if that information can help.

__Expected result__:
The expected result should be the same as index a new document in empty database.

**Comment by andrea-tesei** [comment] 2020-08-25 14:22
Hi guys. Any news about this issue?

**Comment by maxkernbach** [comment] 2020-09-17 13:21
Hi @andrea-tesei,

Thanks for reporting, I was able to reproduce this issue according to your description. Including system collections does not seem necessary, it it also reproducible without them.

For easy reproduction, I am attaching a sample dump in this ticket: 
[dump.zip](https://github.com/arangodb/arangodb/files/5239320/dump.zip)

Perform arangorestore into a fresh 3.6.5 single server deployment:
```
arangorestore dump/ --server.database padded --create-database true
```

Execute AQL query:
```
FOR i IN 1..1 INSERT {value: i} IN test3
```

Results in error:
```
unique constraint violated - in index primary of type primary over '_key'; conflicting key: 0000000000000100
```

**Comment by Simran-B** [comment] 2020-09-23 11:10
According to our docs, only the autoincrement key generator accepts an offset, but it might just be outdated: https://www.arangodb.com/docs/stable/http/collection-creating.html#create-collection
Still, it would only be a workaround. When writing a dump, the offset+1 should be exported so that restores work out of the box.

**Comment by andrea-tesei** [comment] 2020-10-01 11:42
Thanks @Simran-B for the explanation. Can I do something to use this workaround for now? Or you have to fix this bug in the next release?

**Comment by Simran-B** [comment] 2020-10-01 12:11
maxkernbach checked and the padded generator does not accept an offset nor is the current value dumped, so no workaround is available. This will require a larger bug fix, for which there is no ETA unfortunately.

**Comment by andrea-tesei** [comment] 2020-10-01 12:31
Ok, I understood. So the only available solution is to move to another key generator, right? The autoincrement will be a good choice in this case? I'm worried about the performances of autoincrement key in case of huge databases: have you some performance measurements of the different key generators that I can study to evaluate this change? Thanks for your help.

**Comment by andrea-tesei** [comment] 2020-10-13 12:39
Any news about my previous comment? If I had to change key generator, I want to know more on the differences between the ones available. I can take only _informed_ decisions/changes at this state of development. I hope you understand.

**Comment by Simran-B** [comment] 2021-01-29 19:22
There are two upcoming fixes for 3.6 #13424 and #13417 (and for 3.7 as well). I tested them with 3.8.devel and it correctly dumped and restored `lastValue`, and also assigned _keys > lastValue after restore.

@andrea-tesei The bug fixes are expected to be released with v3.6.12 and v3.7.7 soon. Sorry that it took so long.

**Comment by andrea-tesei** [comment] 2021-01-31 08:47
Hi @Simran-B thanks for this update. If you can notify me as soon as those two fixes for 3.7 will be released, I can do some tests and give you feedbacks. Thanks

**Comment by choppedpork** [comment] 2021-02-01 15:41
Hello,

I've been struggling with a very similar (but not identical) issue myself recently and wanted to check here first whether it's possible the root cause is the same before potentially raising another issue - I'm also getting a unique constraint violation on `_key` (to be specific: `Response: 409, Error: 1210 - unique constraint violated - in index primary of type primary over '_key'; conflicting key: 10070041`) but in my case the collection is using the default (traditional) key generator. Similarly to this issue's description this happens *only* following an arangorestore. In my case this is the Java driver and a clustered ArangoDB deployment - more than happy to provide more info, keeping it minimal in case this is not a related issue at all.

**Comment by Simran-B** [comment] 2021-02-01 17:26
@choppedpork The upcoming bug fixes are limited to the autoincrement and padded key generators and the issue here is about the padded key generator, so I would classify your issue as a different problem. I created a separate issue here: #13465

**Comment by whoiscarlo** [comment] 2022-09-20 17:58
Was this issue ever solved/ were the bug fixed add to the latest releases?

**Comment by coronabytes** [comment] 2023-10-11 07:13
just happend in production in 3.11.4... investigating

**Comment by dothebart** [comment] 2023-10-11 08:25
but not in conjunction with an arangorestore?
This should have been fixed as part of the 3.9 release series. So it should probably be closed.

**Comment by coronabytes** [comment] 2023-10-11 09:35
Luckily it for you it probably was^^
Last Friday I dumped an 3.9.0.2 Arango Windows installation and restored on 3.11.4 Linux with the 3.9 arango restore tool.

The system was in production use from Monday 8am till today 9am when it began failing.
My fix was to rename the collection and recreate the collection with the key generator set to uuid.
Its a history collection, so it being empty now is not that bad and I will copy the old data back in with a new key

**Comment by dothebart** [comment] 2023-10-11 11:05
ok, since 3.9 is running end of life now, lets close it.

**Closed by dothebart** 2023-10-11 11:05 UTC
Labels: 1 Bug, 2 Fixed, 3 RocksDB, 3 ImportExport
