### ISSUE TITLE
Regular "arangod.exe stopped working" crashes on Windows

### ISSUE THREAD

**Issue by gyulaborsos** [arangodb/arangodb#1406] opened 2015-07-08 08:16 UTC
Hi there!

We have regular "arangod.exe stopped working" crashes on Windows.
Happens with ArangoDB 2.5.2, 2.5.3, 2.6.
We could not isolate what causes it, but it happens quite often on developer machines.
Not necessarily when the DB is used heavily, often happens just randomly, sometimes more than once a day.

Attached you can find several instances of the crash happening, screenshots from windows Event Log and the details of the crashes, also a log file from ArangoDB itself.

The common log entries for the crashes are :
- In the ArangoDB log: ERROR Unhandled exception: -1073741819 - will crash now. 
- In the windows event log: Unhandled exception: -1073741819 - will crash now. ..\..\arangod\RestServer\WindowsServiceUtils.cpp  unhandledExceptionHandler 527

Full logs can be found here:
https://drive.google.com/file/d/0B-Rhoo8GyarIUDFVb0hMUnZNVTA/view
and here
https://drive.google.com/file/d/0B-Rhoo8GyarId29Rc3lTVDQtZW8/view

![arango_app_error_event](https://cloud.githubusercontent.com/assets/7009104/8565911/2ddb17f6-255a-11e5-8eeb-98082e152928.png)
![arango_crash_event_log_scr_gmt 2](https://cloud.githubusercontent.com/assets/7009104/8565912/2e03a43c-255a-11e5-98d4-6dc22beb0eaa.png)

**Comment by dothebart** [comment] 2015-07-08 09:15
So it seems you already found some of our efforts to make ArangoDB a first class citizen on Windows - using the windows eventlog, and the unhandled exception handler to get more information in these cases.
The Information already is a good start, it however doesn't yet get us closer to a point where we can propose a fix.
Could you download procdump:
https://technet.microsoft.com/en-us/sysinternals/dd996900.aspx

And run it like that:
procdump -accepteula -e -ma <PID of arangod>
?
It will then generate a dump file if the incident occurs, and we can use it to actualy debug the problem.

**Comment by gyulaborsos** [comment] 2015-07-08 11:23
Hi!

Thanks, I've asked all members of the development team to run this along ArangoDB. 
We'll let you know if a crash happens, it might within be days, might be within weeks :)

Thank you!

**Comment by gyulaborsos** [comment] 2015-07-14 13:34
Hi!

Below you can find the dump file after a crash:
https://drive.google.com/file/d/0B-Rhoo8GyarIMmp1dkJtMXJSM1k/view?usp=sharing

Please note that it's a 2.5.2 version ArangoDB, but we experienced it with 2.6.x as well.

Regards,
Gyula

**Comment by dothebart** [comment] 2015-07-14 14:10
ok, thanks. Fetching it now, will give feedback once I've analyzed it.

**Comment by nebulaszlonemethi** [comment] 2015-07-20 10:47
Hi, here's another report about crashing a single-server cluster on win8.1 (dump file, screenshot, config, steps)
https://drive.google.com/a/nebu.com/file/d/0B6Z2oxj3VUQDRERRMU4yWDFNaUE/view?usp=sharing

**Comment by dothebart** [comment] 2015-07-22 12:03
We've built new releases (2.5.6 + 2.6.3) with extra debug informations (especialy for you ;-) Please retry with these whether the problem is still reproducible and send us dumps created (if) with these new versions.

@gyulaborsos please note that you should always use the latest version of one release series, since it contains bugfixes over previous versions - so you shouldn't use 2.5.2 anymore.

**Comment by nebulaszlonemethi** [comment] 2015-07-23 12:29
Hi,
here is a crash dump and related infos about crashing a 2.6.3 in non-cluster mode.
https://drive.google.com/file/d/0B6Z2oxj3VUQDcHpWUDcwZ2RWWXM/view?usp=sharing

**Comment by dothebart** [comment] 2015-07-29 14:31
ok, Thanks a lot. The crash points into V8. We're going to release a fix with an upgraded V8 version.

**Comment by dothebart** [comment] 2015-08-11 09:21
As you may have already seen, we've released 2.5.7 and 2.6.4 with the propper js versions.
Please upgrade your systems. I'll close this bug for now, please open a new one if further crashes appear.

**Comment by nebulaszlonemethi** [comment] 2015-09-28 11:40
Hi,
actually the number of random crashes hasn't decreased at all using higher versions than 2.6.4.
Dump created: https://drive.google.com/file/d/0B6Z2oxj3VUQDa3gtQU1hOVVFdGs/view?usp=sharing

Could you please reopen this one?

**Comment by dothebart** [comment] 2015-09-28 13:57
hm, ok, analyzing the dump points into the V8 garbage collection again.
If I see that correctly you dropped and recreated a database immediately before the incident occured?
Are you using a Foxx application? or are you doing that via the HTTP-Interface?

**Comment by nebulaszlonemethi** [comment] 2015-09-28 14:27
Hi,
we use the http interface to communicate with ArangoDB, from a java application. 

About the log, sorry i attached a wrong piece of log, that was for an earlier crash (on 24th).
Here is the proper log happened today. As you can see, the crash happened not immediately after the db re-creation but some hours later, after several read/writes. Actually it crashes almost daily in our environment (Win 8.1), just this was the first time for some weeks i created a dump about it.

```
2015-09-28T07:15:30Z [8308] INFO ArangoDB 2.6.8 64bit -- ICU 54.1, V8 4.1.0.27, OpenSSL 1.0.2 22 Jan 2015
2015-09-28T07:15:30Z [8308] INFO using default language 'en'
2015-09-28T07:15:31Z [8308] INFO loaded database '_system' from 'd:\www\arangodb\bin\..\var\lib\arangodb\databases\database-74346'
2015-09-28T07:15:31Z [8308] INFO loaded database 'nlac' from 'd:\www\arangodb\bin\..\var\lib\arangodb\databases\database-540811882'
2015-09-28T07:15:31Z [8308] INFO loaded database 'DQO' from 'd:\www\arangodb\bin\..\var\lib\arangodb\databases\database-7101027657'
2015-09-28T07:15:31Z [8308] INFO running WAL recovery (1 logfiles)
2015-09-28T07:15:31Z [8308] INFO replaying WAL logfile 'd:\www\arangodb\bin\../var/lib/arangodb\journals\logfile-7365484201.db' (1 of 1)
2015-09-28T07:15:32Z [8308] INFO WAL recovery finished successfully
2015-09-28T07:15:32Z [8308] INFO using endpoint 'tcp://0.0.0.0:8529' for non-encrypted requests
2015-09-28T07:15:32Z [8308] INFO using default API compatibility: 20600
2015-09-28T07:15:32Z [8308] INFO JavaScript using startup 'd:\www\arangodb\bin\../share/arangodb/js', application 'd:\www\arangodb\bin\../var/lib/arangodb-apps'
2015-09-28T07:15:39Z [8308] INFO In database '_system': Database is up-to-date (20608/prod/standalone/existing)
2015-09-28T07:15:39Z [8308] INFO In database 'nlac': Database is up-to-date (20608/prod/standalone/existing)
2015-09-28T07:15:39Z [8308] INFO In database 'DQO': Database is up-to-date (20608/prod/standalone/existing)
2015-09-28T07:15:42Z [8308] INFO Authentication is turned off
2015-09-28T07:15:42Z [8308] INFO ArangoDB (version 2.6.8 [win64]) is ready for business. Have fun!
2015-09-28T07:20:59Z [8308] INFO dropping database 'DQO', directory 'd:\www\arangodb\bin\..\var\lib\arangodb\databases\database-7101027657'
2015-09-28T07:20:59Z [8308] INFO creating database 'DQO', directory 'd:\www\arangodb\bin\..\var\lib\arangodb\databases\database-9912413722'
2015-09-28T07:20:59Z [8308] INFO collection '_users' does not exist, no authentication available
2015-09-28T07:20:59Z [8308] INFO In database 'DQO': No version information file found in database directory.
2015-09-28T07:20:59Z [8308] INFO In database 'DQO': Found 24 defined task(s), 19 task(s) to run
2015-09-28T07:20:59Z [8308] INFO In database 'DQO': state prod/standalone/init, tasks setupUsers, createUsersIndex, addDefaultUser, updateUserModel, setupGraphs, createModules, createRouting, createKickstarterConfiguration, insertRedirectionsAll, setupAal, createAalIndex, setupAqlFunctions, createStatistics, createConfiguration, systemAppEndpoints, setupQueues, setupJobs, moveFoxxApps, dropAal
2015-09-28T07:21:00Z [8308] INFO In database 'DQO': init successfully finished
2015-09-28T11:14:57Z [8308] ERROR Unhandled exception: -1073741819 - will crash now.
```

**Comment by dothebart** [comment] 2015-09-28 14:30
can you reproduce from your application logs what you were currently doing around that time?

**Comment by nebulaszlonemethi** [comment] 2015-09-28 14:37
Unfortunately no, we logged on console only, it has been lost. What i can try is to reproduce the crash, also change arango's log level to debug/trace?

**Comment by dothebart** [comment] 2015-09-28 14:42
yes, debug loglevel could probably add some more output. 
Maybe you also can enable a log on the client side?
I'm currently trying to reproduce that september 24th incident with a little script.

**Comment by nebulaszlonemethi** [comment] 2015-09-29 09:11
Ok, a new crash reported. Attached the java app log (about the ~last minute) + the ArangoDB log level set on DEBUG. ArangoDB died during frequent AQL writes.
https://drive.google.com/file/d/0B6Z2oxj3VUQDOWhHMVdSa0x4enc/view?usp=sharing

**Comment by dothebart** [comment] 2015-09-29 09:54
Ok, since this again barfs in the V8 garbage collections, we'd want to digg deeper into the javascript functions that are invoked in your AQL-queries: FIRST and DOCUMENT.
Can you give me a dump of your test database, so I can retry that localy?

**Comment by nebulaszlonemethi** [comment] 2015-09-29 10:34
ok, here it is: https://drive.google.com/file/d/0B6Z2oxj3VUQDNW9MZm16Y3NTXzg/view?usp=sharing

**Comment by dothebart** [comment] 2015-09-29 15:17
i've collected the queries from your logfile, and processed it into a js file: 
https://gist.github.com/6bf28fca86400d5b942c
Valgrind on linux didn't get any catches; I'm currently running it on our windows test environment like this:
while /bin/true; do ./bin/arangosh --javascript.execute queries.js; sleep 1; done &

So far no crashes. Maybe you can have a look at that script, whether I got s.th. wrong?

I also don't see any insert operations? Is that intentional? or are they missing from your log? Or was the dataset static during that time period?

**Comment by dothebart** [comment] 2015-09-29 15:41
oh, its dead.

**Comment by nebulaszlonemethi** [comment] 2015-09-30 06:48
Nice that you could reproduce! Yep i see that writing ops weren't logged in the app but actually a lot of request POSTed continuously to the /cursor endpoint, like that:
```
Request URL: http://127.0.0.1:8529/_db/testdb/_api/cursor
Request Method: POST
Request body:
{"query":"FOR d IN [{\"name\":\"bob\",\"age\":29}, {\"name\":\"alice\",\"age\":31},...(~100 records here)....] INSERT r INTO Persons"}
```
But i'm not sure that it is strongly related to the crashes. Many times, being in idle state (or almost idle, one read by 5 secs), ArangoDB just randomly crashes. Or a typical scenario, ArangoDB is completely idle, i put my machine to sleep, then later i wake it up and the immediately get the "stopped working" dialog.

**Comment by dothebart** [comment] 2015-09-30 07:26
yea, as said above, its the garbage collection. This is for shure run when the process isn't as busy. But even stressing things more doesn't reproduce this on linux :-\

**Comment by nebulaszlonemethi** [comment] 2015-09-30 10:48
wouldn't it help to enhance somehow the exception handling/logging a bit more usable for this case of crashing in ArangoDB? It's a bit weird that there is one single log line in the log files, without any details or stack trace, even on debug level.

**Comment by dothebart** [comment] 2015-10-01 13:52
yes, we have native backtraces on linux and windows in certain situations.
However, they bring a significant performance overhead, which is why they're only enabled in debug builds.

We used the full stress script to reproduce this issue in ~10 minutes. Reducing it to the last dozend of queries makes the issue appear in around 2 hours. 
Re-testing the full script with 2.7 RC however did not reveal similar issues. 
Since 2.7 does have a newer V8 version, there probably was a fix for this upstream.
We found out in June that we didn't pick a proper V8 version for 2.5 & 2.6, However adjusting that to as we did later in these release series didn't fix your issues.

The newer version, V8-4.3.61, has some breaking API changes, so we decided not to introduce them into a stable release cycle (which works flawlessly for linux & mac users). 

If you want to test whether 2.7 fixes your troubles, you may try the RC: https://www.arangodb.com/download-preview/
We expect the RC to be more or less the final state, so we can build it in release mode next week.

**Comment by nebulaszlonemethi** [comment] 2015-10-02 06:27
Thank you, i'll test the 2.7 soon and let you know what happened.

**Comment by nebulaszlonemethi** [comment] 2015-10-05 15:05
The 2.7 RC seems to be stable, i couldn't manage to get the "stopped working" popup so far! Let me test it for some more 1-2 days.

**Comment by nebulaszlonemethi** [comment] 2015-10-06 11:49
I've got the "arangodb crashed" popup. This time there was no load (just periodic reads by seconds, for hours), i opened the web interface and when i clicked the "Services" menu item the app crashed.

"Unhandled exception: -1073741819 - will crash now.
C:\b\ArangoDB-2.7.0-rc2\arangod\RestServer\WindowsServiceUtils.cpp"

Config file, log, windows events are on the link below. This time minidump wasn't created.
https://drive.google.com/file/d/0B6Z2oxj3VUQDUGZ4Q2tiTTFicTA/view?usp=sharing

**Comment by jsteemann** [comment] 2015-10-06 12:45
Do you know if that is reproducible, i.e. does it crash every time the "Services" menu is opened in the web interface, or if this was  just a coincidence?

**Comment by nebulaszlonemethi** [comment] 2015-10-06 12:51
No, not every time. That time the crash was right after when clicked the Services item, after when i restarted, i couldn't reproduce it again.

**Comment by nebulaszlonemethi** [comment] 2015-10-06 14:42
Crash again, this time no user interaction happened, just the periodic aql reads in the background. https://drive.google.com/file/d/0B6Z2oxj3VUQDMVlJSTNyTndOSDQ/view?usp=sharing (minidump also created)

**Comment by jsteemann** [comment] 2015-10-06 14:57
Ok, so it's probably not related to the web interface & clicking the "Services" menu.

**Comment by nlac** [comment] 2015-10-06 17:45
Guys, couldn't help if you'd publish a debug build that can log these V8-related exceptions with full stack trace (and any other info you need, var dump, memory state etc)? I can't really report you more with the current tools.

**Comment by nlac** [comment] 2015-10-06 17:49
(sorry guys: nebulaszlonemethi and nlac is the same person, i forgot to switch my account at home. Don't be confused :-) )

**Comment by dothebart** [comment] 2015-10-20 12:13
hm, bad news - its still the V8 garbage collection.
We offer a [public symbol server]( https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#debugging-symbols) (now.. forgot to add the upload to the build process) -
So you can obtain backtraces to the crashes in visual studio yourselves. 
For shure you can also [compile your own V8 + ArangoDB](https://docs.arangodb.com/cookbook/CompilingUnderWindows.html), I didn't manage to get the V8 debug symbols completely included with the arangodb pdb files, so no line numbers and easy clicking in the V8 stackframes with visual studio. 

We may later on try to upgrade V8 once more.

**Comment by nlac** [comment] 2015-10-22 19:34
Thanks for the info, will try that symbol server thing, perhaps it will give more info. 
Could me ask a very naive question, just thinking about the issue.. i and many colleagues run couple of apps on Windows using V8 eg. Brackets, Chrome, custom apps on node, many times these run for days continuously and i just don't remember any unexpected crash. Just wondering cannot be some special cause why V8 is so unstable in ArangoDB?

**Comment by dothebart** [comment] 2015-10-23 10:38
most probably arangosh will also work flawless for you without similar crashes over a very long time. The problematic part could be the 'weak' integration, thats how V8 calls it if its got native datastructures that are represented into js. We have this i.e. for direct access to collection values, so you can fetch a document, and work with it in js, but only if you modify something in it, something special happenes. Its i.e. in arangod/V8Server/v8-wrapshapedjson.cpp, but there are other places too. 
Whats fancy in this case is, that it only seems to appear on windows - other platforms appear completely stable. 
Its really hard to isolate the actual miss behavior since the data structures in the garbage collector seem to be completely wasted at the time the actual crash appears. If you have any more good ideas how to narrow this down, we would be thankfull.

**Comment by dothebart** [comment] 2016-03-14 21:42
During the 2.8.x release cycle we found and fixed possible incidents which may occur. Have you upgraded to 2.8.5 yet, and does your problem still occur?

In general, should we close this issue now?

**Comment by nebulaszlonemethi** [comment] 2016-04-08 08:49
Hello,
sorry for the late answer.. yes the random crash still does occur on Windows, even with 2.8.6: popup comes "arangodb has stopped working", nothing in the log on info level, the whole thing happens on zero load, no pending requests at all, it just happens.

**Comment by renfidel** [comment] 2016-04-13 18:26
I concur, same issue happens for me as well.

**Comment by renfidel** [comment] 2016-05-16 05:50
I believe this issue is security related, I am running ArangoDB 2.8.7 in both Windows 10 and Windows Server 2012 R2 and I have not had a random crash/failure for a few days now. To resolve this problem I did the following:

1)	Navigated to the installation directory
2)	Select the Var folder, right click and select “Properties”
3)	On the Security Tab, click the “Advanced” button
4)	Then select the “Disable inheritance” button
5)	Apply and OK

Hope this helps somebody.

**Comment by dothebart** [comment] 2016-07-14 11:52
ArangoDB 3.0 introduces the new V8 version 5.0 - We couldn't see issues like that anymore. 

@renfidel If I get that correctly you just assign folder access permissions there; Any ideas how that could interfere with the V8 garbage collection? Is it about virtual memory via temporary files created by the windows allocator internally? Should it be part of the NSIS installation process? If yes, do you actually know what do do [there](https://github.com/arangodb/arangodb/blob/devel/Installation/Windows/Templates/NSIS.template.in)?

**Closed by dothebart** 2016-07-14 11:52 UTC
Labels: 1_Bug, windows

**Comment by renfidel** [comment] 2016-07-14 15:54
@dothebart To be honest I am not quite sure but I believe this is due to fact that my installation path was within the "Program Files" directory which requires UAC and is notoriously strict.

**Comment by alexpavlovaskblue** [comment] 2017-08-12 16:59
First of all, many thanks for your amazing software I want to use for our production purposes.
I tried to install the new ArangoDB version (3.2 - ArangoDB3e-3.2.0-1_win64.exe) on my server (Windows Server 2012 R2) and I got the message:

"Installation aborted...."

When I try to execute the arangod.exe, I got:

**"arangod.exe has stopped working"**

The text of this message comes here:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	arangod.exe
  Application Version:	0.0.0.0
  Application Timestamp:	597b19dd
  Fault Module Name:	arangod.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	597b19dd
  Exception Code:	c000001d
  Exception Offset:	0000000000200f77
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	2070
  Additional Information 1:	1897
  Additional Information 2:	189728da1647e425ba8f628d85b06640
  Additional Information 3:	8b92
  Additional Information 4:	8b9276e71e0f84328dc8e1cff420f116

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt


May I ask you what is wrong with this installation? I don't have any problem installing the previous (3.1.21) version.


I really appreciate your help!

The full report comes here:

Version=1
EventType=APPCRASH
EventTime=131470284335039030
ReportType=2
Consent=1
ReportIdentifier=29f4a6ff-7f7a-11e7-80c8-005056965dc2
IntegratorReportIdentifier=29f4a6fe-7f7a-11e7-80c8-005056965dc2
NsAppName=arangod.exe
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=arangod.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=597b19dd
Sig[3].Name=Fault Module Name
Sig[3].Value=arangod.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=597b19dd
Sig[6].Name=Exception Code
Sig[6].Value=c000001d
Sig[7].Name=Exception Offset
Sig[7].Value=0000000000200f77
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.3.9600.2.0.0.272.7
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=2070
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=1897
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=189728da1647e425ba8f628d85b06640
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=8b92
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=8b9276e71e0f84328dc8e1cff420f116
UI[2]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\arangod.exe
UI[3]=arangod.exe has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\arangod.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[5]=C:\Windows\system32\WS2_32.dll
LoadedModule[6]=C:\Windows\SYSTEM32\dbghelp.dll
LoadedModule[7]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[8]=C:\Windows\system32\RPCRT4.dll
LoadedModule[9]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\SSLEAY32.dll
LoadedModule[10]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\LIBEAY32.dll
LoadedModule[11]=C:\Windows\system32\WLDAP32.dll
LoadedModule[12]=C:\Windows\SYSTEM32\MSWSOCK.dll
LoadedModule[13]=C:\Windows\SYSTEM32\WINMM.dll
LoadedModule[14]=C:\Windows\system32\msvcrt.dll
LoadedModule[15]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[16]=C:\Windows\system32\NSI.dll
LoadedModule[17]=C:\Windows\SYSTEM32\combase.dll
LoadedModule[18]=C:\Windows\system32\USER32.dll
LoadedModule[19]=C:\Windows\system32\GDI32.dll
LoadedModule[20]=C:\Windows\system32\SspiCli.dll
LoadedModule[21]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\VCRUNTIME140.dll
LoadedModule[22]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\api-ms-win-crt-time-l1-1-0.dll
LoadedModule[23]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\api-ms-win-crt-stdio-l1-1-0.dll
LoadedModule[24]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\api-ms-win-crt-string-l1-1-0.dll
LoadedModule[25]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\api-ms-win-crt-heap-l1-1-0.dll
LoadedModule[26]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\api-ms-win-crt-runtime-l1-1-0.dll
LoadedModule[27]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\api-ms-win-crt-convert-l1-1-0.dll
LoadedModule[28]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\api-ms-win-crt-environment-l1-1-0.dll
LoadedModule[29]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\api-ms-win-crt-utility-l1-1-0.dll
LoadedModule[30]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\api-ms-win-crt-math-l1-1-0.dll
LoadedModule[31]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\api-ms-win-crt-filesystem-l1-1-0.dll
LoadedModule[32]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\api-ms-win-crt-conio-l1-1-0.dll
LoadedModule[33]=C:\Windows\SYSTEM32\WINMMBASE.dll
LoadedModule[34]=C:\Windows\SYSTEM32\cfgmgr32.dll
LoadedModule[35]=C:\Windows\SYSTEM32\DEVOBJ.dll
LoadedModule[36]=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\ucrtbase.DLL
LoadedModule[37]=C:\Windows\system32\IMM32.DLL
LoadedModule[38]=C:\Windows\system32\MSCTF.dll
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=arangod.exe
AppPath=C:\ArangoDB\ArangoDB3e 3.2.0\usr\bin\arangod.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=CAE80E286024C6B635F3482E2D51BBC6

**Comment by alexpavlovaskblue** [comment] 2017-08-12 17:24
One comment: When I check the event Viewer I only can see:

********Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program arangod.exe because of this error.

Program: arangod.exe
File: 
*******************

There are no mention about the file....

**Comment by jsteemann** [comment] 2017-08-14 07:30
@alexpavlovaskblue : you said you tried version 3.2.0-1.
Can you try installing ArangoDB 3.2.1-2 (the current version as of now)? It should provide a fix for some specific startup error. I can't tell from here whether this release fixes your particular problem or not, but it would be helpful if you could try it out and let us know.
Thanks in advance.

**Comment by alexpavlovaskblue** [comment] 2017-08-14 17:32
Hi, jsteemann,
Thank you for your help!
At this moment, the server seems to be working with the new 3.2.1-2 version.
But I have now the problems when I try to install a foxx service from the ArangoDB dashboard:

![image](https://user-images.githubusercontent.com/29273892/29283470-be2b5380-811e-11e7-839c-9a0a0db74b75.png)

What is wrong?

I'm using the entreprise version ArangoDB3e-3.2.1-2_win64.exe

MAny thanks for your help!

**Comment by jsteemann** [comment] 2017-08-15 07:17
@alexpavlovaskblue from the error message it seems that the manifest.json file is missing in the upload file.
If you uploaded a zip file with the Foxx application, did this zip file contain a manifest.json file?
If yes, which steps did you carry out exactly, and which app did you upload?

**Comment by alexpavlovaskblue** [comment] 2017-08-15 09:25
Hi, jsteemann,
It happens with any service FROM STORE I try to install:

![image](https://user-images.githubusercontent.com/29273892/29309904-906ab096-81a3-11e7-8209-ddd252528945.png)

I installed 3.2.1 version by default. e.g, C:\Program Files\ArangoDB3e 3.2.1.
I have permissions as admin in this PC.

Please note, that in the previous 3.1 version I didn't get any related issue.

Thank you!
