### ISSUE TITLE
Foxx manifest does not accept script names with 3 "-" in the name

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#1534] opened 2015-10-19 13:12 UTC
This is really funny, but @pluma asked for an investigative ticket about this.

In my `manifest.json`:
```
  "scripts": {
    "setup": "scripts/setup.js",
    "teardown": "scripts/teardown.js",
    "clean-by-user": "scripts/clean-by-user.js"
  },
```

this triggers:
```
2015-10-19T14:58:56 [3088] ERROR Error in foxx route '{ "match" : "/foxxes/scripts/:name", "methods" : [ "post" ], "constraint" : { "name" : "/[^/]+/" } }': 'Arguments to path.join must be strings - have undefined', Stacktrace:
2015-10-19T14:58:56 [3088] ERROR TypeError: Arguments to path.join must be strings - have undefined
2015-10-19T14:58:56 [3088] ERROR   at /usr/share/arangodb/js/common/bootstrap/module-fs.js:318:15
2015-10-19T14:58:56 [3088] ERROR   at Array.filter (native)
2015-10-19T14:58:56 [3088] ERROR   at Object.exports.join (/usr/share/arangodb/js/common/bootstrap/module-fs.js:316:28)
2015-10-19T14:58:56 [3088] ERROR   at ArangoApp.loadAppScript (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/arangoApp.js:423:17)
2015-10-19T14:58:56 [3088] ERROR   at executeAppScript (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/manager.js:510:18)
2015-10-19T14:58:56 [3088] ERROR   at Object.runScript (/usr/share/arangodb/js/server/modules/org/arangodb/foxx/manager.js:814:10)
2015-10-19T14:58:56 [3088] ERROR   at /usr/share/arangodb/js/apps/system/_admin/aardvark/APP/foxxes.js:289:28
```

If I change the name to `clean-user` then it works fine.

**Comment by pluma** [comment] 2015-10-19 15:30
Likely already existed in 2.6. I'll look into this when I'm on site tomorrow.

**Comment by pluma** [comment] 2015-11-24 13:14
This is weird. The problem seems to occur in `fs.join(this._root, this._path, filename)` (as the error indicates, one of the arguments is undefined). I'm not sure how this can vary based on the number of dashes in the script name. I'll have to investigate further.

**Comment by pluma** [comment] 2015-11-24 13:35
I'm pretty sure this bug will no longer be reproducible in 2.8 as the implementation of the module loader has changed but I'll leave this open for now.

**Comment by pluma** [comment] 2015-12-02 16:47
Unassigning this as I'm knee-deep in Foxx and can't reproduce the problem in 2.8. Someone should try to reproduce this in 2.7 and see if we can patch it.

**Comment by pluma** [comment] 2016-06-17 13:14
This also seems to no longer happen in 3.0. Closing this as it's unlikely we'll backport a bugfix to 2.7 at this point.

**Closed by pluma** 2016-06-17 13:14 UTC
Labels: 1_Bug, foxx
