### ISSUE TITLE
Failed to initialize db after install

### ISSUE THREAD

**Issue by zbauer91** [arangodb/arangodb#8718] opened 2019-04-09 19:07 UTC
## My Environment

* __ArangoDB Version__: 3.4.4 / 3.4.5       
* __Storage Engine__: RocksDB            
* __Deployment Mode__: Single Server      
* __Configuration__: No password, default DB, defalt installation directories. I've tried single user and all users settings with the same results            
* __Operating System__: Windows 10 Enterprise 1803      
* __Total RAM in your machine__: 16Gb       
* __Disks in use__: SSD       
* __Used Package__: Windows Official             

## Component, Query & Data

__Affected feature__: Installation

## Steps to reproduce

1. Run installer as administrator following steps above
2. executable installs all dependencies (sh, imp, dump, etc...) and attempts to initialize `_system` database
3. Installer throws general error that  it failed to initialize the DB with a password.  

__Problem__:
I'm unable to install Arango on Windows with any combination of settings. The Windows event viewer says Arango tries to make changes to a few files in `C:\vm02-windows`, a directory which doesn't exist. 

I asked my IT dept. to temporarily give me unrestricted admin access, which they did, and I got the same results. We manage permissions through Avecto Defendpoint, but I've never had issues installing Arango before. 

__Expected result__:
I expect the database to initialize

**Comment by KVS85** [comment] 2019-04-10 20:35
Hello @zbauer91,

Can you please tell where did you download Windows installer and put here contents of `etc\arangodb3\arangod.conf` (in installation folder of ArangoDB binaries)?

**Comment by zbauer91** [comment] 2019-04-11 11:48
Hi @KVS85 

I downloaded the installer from the Arango website, and I'm using Windows 10 Enterprise 1803

arangod.conf:
```
# ArangoDB configuration file
# 
# Documentation: 
# https://docs.arangodb.com/latest/Manual/Administration/Configuration/
# 

[database]
directory = @ROOTDIR@var/lib/arangodb3

# maximal-journal-size = 33554432

[server]
# Specify the endpoint for HTTP requests by clients.
#  tcp://ipv4-address:port
#  tcp://[ipv6-address]:port
#  ssl://ipv4-address:port
#  ssl://[ipv6-address]:port
#  unix:///path/to/socket
#
# Examples:
#   endpoint = tcp://0.0.0.0:8529
#   endpoint = tcp://127.0.0.1:8529
#   endpoint = tcp://localhost:8529
#   endpoint = tcp://myserver.arangodb.com:8529
#   endpoint = tcp://[::]:8529
#   endpoint = tcp://[fe80::21a:5df1:aede:98cf]:8529
#
endpoint = tcp://127.0.0.1:8529
storage-engine = auto

# reuse a port on restart or wait until it is freed by the operating system
# reuse-address = false

authentication = true

# number of maximal server threads. use 0 to make arangod determine the
# number of threads automatically, based on available CPUs
# maximal-threads = 0

# gather server statistics
statistics = true

# the user and group are normally set in the start script
# uid = arangodb
# gid = arangodb

# uid = arangodb


[javascript]
startup-directory = @ROOTDIR@/usr/share/arangodb3/js
app-path = @ROOTDIR@var/lib/arangodb3-apps
# app-path = //arangodb3/apps

# number of V8 contexts available for JavaScript execution. use 0 to 
# make arangod determine the number of contexts automatically.
# v8-contexts = 0

[foxx]
# enable Foxx queues in the server
# queues = true

# interval (seconds) to use for polling jobs in Foxx queues
# queues-poll-interval = 1

[log]
level = info
# file = @ROOTDIR@var/log/arangodb3/arangod.log

[cluster]

[rocksdb]
# encryption-keyfile=/your-encryption-file


```

windows event logs:
```
cannot rename saved file 'C:\ProgramData\ArangoDB\VERSION-1.tmp' to 'C:\ProgramData\ArangoDB\VERSION-1': Permission denied
C:\vm02-windows\oskar\work\ArangoDB\lib\Basics\VelocyPackHelper.cpp
arangodb::basics::VelocyPackHelper::velocyPackToFile
732
```
```
{startup} writing VERSION file 'C:\ProgramData\ArangoDB\VERSION-1' failed: Permission denied
C:\vm02-windows\oskar\work\ArangoDB\arangod\VocBase\Methods\Version.cpp
arangodb::methods::Version::write
167
```
```
Database '_system' initialization failed (Permission denied). Please inspect the logs from the initialization procedure and try starting the server again.
C:\vm02-windows\oskar\work\ArangoDB\arangod\RestServer\UpgradeFeature.cpp
arangodb::UpgradeFeature::upgradeDatabase
205
```

**Comment by KVS85** [comment] 2019-04-11 16:07
@zbauer91 thank you for this information.

I have several questions to narrow-down this problem:
- was this an "all users" installation (service)?
- did you have an ArangoDB installed before on this machine (probably, a previous one version)?
- is your account belongs to "Administrators" group?

From what I see the problem is that ArangoDB couldn't deploy DB into C:\ProgramData\ArangoDB (default installation directory for service) due to insufficient rights.

**Comment by zbauer91** [comment] 2019-04-11 16:19
>was this an "all users" installation (service)? 

Yes, this time. I've also tried performing the installation for myself only, I've also tried changing the install directory to one that I know I have W/R access to. All combinations of installation parameters results in the same error.
- all users/just current user
- default directory / custom directory
- password/no password

>  did you have an ArangoDB installed before on this machine (probably, a previous one version)?

Yes, I had 3.3.x installed previously.

> is your account belongs to "Administrators" group?

That's what I thought. Our company manages administrative privileges through Avecto Defendpoint (as mentioned).  Administrator calls are gated through this software, and I have to sign in to temporarily allow the changes to take place. This isn't full admin, though, so I got the go-ahead from IT to temporarily add my user back to the admin group for the purposes of this installation. With full administrative access, I still received the same errors that I replied with above.

**Comment by zbauer91** [comment] 2019-04-16 13:40
Just checking back in. Is there any more information you need on my end?

**Comment by natejgardner** [comment] 2019-10-07 19:14
Just encountered this issue as well. I set permissions for `Everyone` on `C:\ProgramData\ArangoDB` to full control and the error persists.

**Comment by natejgardner** [comment] 2019-10-07 22:12
Additionally, this error affects installation on Windows.

**Comment by Calrain** [comment] 2020-03-06 04:18
I'm seeing this on a server as well, not sure if Anti Virus is jumping in to stop the VERSION-1 file from being modified.

@natejgardner Did you resolve this issue?

**Comment by Calrain** [comment] 2020-03-06 04:26
Quick feedback, we fixed this error by changing arangod.conf to disable authentication, and change the log level to 'level = startup=trace' in order to see the details of the startup phase.

Amazingly, that alone fixed it.

So we enabled auth again and changed the level back to info, and it's fine

**Comment by linpanusst** [comment] 2020-04-08 03:28
@Calrain  Could you please detailly tell me how you fixed this issue? I am facing the same problems.

**Comment by Calrain** [comment] 2020-04-08 05:34
@linpanusst We shut the ArangoDB service down, modified arangod.conf and changed the log level to `level = startup=trace` (yes, two = signs in there), as well as disabled authentication in the same file.

Then start the ArangoDB service again, then shut it down, and change the log level back to what it was, and reenable authentication, both in arangod.conf.

Probably worth backing up your original arangod.conf before you do it.

**Comment by linpanusst** [comment] 2020-04-08 06:08
@Calrain Thank you for you time. I tried on my PC. It doesn't work. Maybe there are some difference between your side and my side. I install the ArangoDB by .exe file. Is that the method you install on your PC? I know there is another way which is the terminal method to install ArangoDB.

**Comment by Calrain** [comment] 2020-04-08 06:37
@linpanusst Ah, sorry, just remembered, it was running on Windows 2016, and when I started the database after making the changes to arangod.conf, when I started the server the next time, I opened a CMD window in Administrator mode, changed into the directory that arangod.exe was, ran it, and then i could see that it initialised ok. Control C two times shuts down the process, then I reverted arangod.conf. After that I could run it as a service again.

**Comment by linpanusst** [comment] 2020-04-08 11:00
@Calrain Thanks for the patience and time. If I find out the reason someday, I will share with you.

**Comment by dothebart** [comment] 2020-04-14 11:38
Hi, 
please change this section: 
```

[log]
level = info
# file = @ROOTDIR@var/log/arangodb3/arangod.log
```
of the arangod.conf to point somewhere with write access, and check back whether you have some meaningfull error message in there.

**Comment by dothebart** [comment] 2020-09-03 12:36
closing as a duplicate of https://github.com/arangodb/arangodb/issues/11041

**Closed by dothebart** 2020-09-03 12:36 UTC
Labels: 3 Packaging, 4 Windows
