### ISSUE TITLE
ArangoDB not respond after a bunch of insertion

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9131] opened 2019-05-29 04:41 UTC
## My Environment

* __ArangoDB Version__:        3.4.5
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               --dbservers.rocksdb.block-cache-size=10240000000 --dbservers.rocksdb.enforce-block-cache-size-limit=true 
* __Infrastructure__:               bare machine
* __Operating System__:        CentOS 7.2
* __Total RAM in your machine__:        96G
* __Disks in use__:       HDD
* __Used Package__:             RedHat .rpm

## Component, Query & Data

__Affected feature__:
AQL query with python driver

__AQL query (if applicable)__:
for i in 1..10000 insert {'link': 'http://www.baidu.com/fake', 'domain_name':'baidu.com', 'version': i} into test_stream

__AQL explain (if applicable)__:

__Dataset__:
repeat inserting records from 0

__Size of your Dataset on disk__:
2G

__Replication Factor & Number of Shards (Cluster only)__:
Replication factor=3
Number of Shards=25 (on 5 bare machines)

## Steps to reproduce

1. the script:

> from arango import ArangoClient
import time
import sys
arango_conn = ArangoClient(protocol='http', host='10.206.120.3', port=8529)
arango_db = arango_conn.db('my_test', username='root', password='hello1234')
while True:
    aql = "for i in 1..10000 insert {'link': 'http://www.baidu.com/fake', 'domain_name':'baidu.com', 'version': i} into test_stream"
    c = arango_db.aql.execute(aql, batch_size=10, stream=True, ttl=3600)
    print('.', end='')
    sys.stdout.flush()

2.  run 1000 instances of the above script

__Problem__:
Arangodb cannot accept any connections. Seems dead without any response, but the port is still occupied, and can find processes alive by ps command.

**Comment by daoxian** [comment] 2019-05-29 15:57
I think the reason may be that the nodes are behind a VIP ?

**Comment by ObiWahn** [comment] 2019-05-31 12:59
duplicate of #9132

**Closed** 2019-05-31 13:12 UTC
Labels: 1 Duplicate, 3 AQL, 3 Cluster
