### ISSUE TITLE
Aardvark graph view is ghosting

### ISSUE THREAD

**Issue by davidmw** [arangodb/arangodb#3580] opened 2017-11-03 22:10 UTC
Viewing graphs of any complexity in the web interface results in ghosting of the graph after changes are made in the right panel. Typically I'm turning off Size by Connection and changing Search Depth and Labels.

The ghosting is most apparent if the graph area is zoomed in or out - then the copies of the graph are not directly on top of each other.  Without zooming you might notice a pixel / subpixel shift of labels.

Once the graph is ghosted - one copy remains active (can be zoomed, radial menus function) while the original graph remains static.

Seems easiest to reproduce if your first zoom happens after graph configuration changes are made and while the right panel remains open.  Just click on the graph behind the panel, use trackpad to zoom and the problem should become clear.

This is on Safari v11.0, Mac OSX 10.13, and both ArangoDB 3.2.3 and 3.2.6.  

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ X] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [ X] Single-Server

Storage-Engine:
- [X ] mmfiles
- [ ] rocksdb

### this is a web interface-related issue:
I'm using the web interface with this browser:   Safari  running on this OS: OSX 10.13
![screen shot 2017-11-04 at 8 58 30 am](https://user-images.githubusercontent.com/3413901/32397640-d770b3a2-c13e-11e7-928d-2d35d02104cc.png)

**Comment by Simran-B** [comment] 2018-07-26 07:51
Does not seem to occur in Chrome 67 under Windows 10. As soon as I change a dropdown field in the graph viewer settings, the change is applied immediately to the graph visualization. If I click Save, then the visualization is re-initialized it seems. Might therefore be an artifact in Safari (not clearing the background correctly?)

**Comment by vinaypyati** [comment] 2018-07-26 09:37
Tried reproducing on Windows 10 in Chrome 68: Ghosting seems to happen. In the third attempt, I could reproduce it. 

1. Open _GRAPHS_ and create one of the example graphs. 
2. Click on the newly created Graph, open the right side panel and change one of the edit labels(Search Depth for example).
3. Save it and do not close the right side panel. 

One copy seems active and other looks static with no labels. 
![image](https://user-images.githubusercontent.com/34657484/43254557-f3958658-90c7-11e8-9485-94ca091bddcb.png)

Note: If we keep this graph for a while, for some reason the browser seems crashed. 
![image](https://user-images.githubusercontent.com/34657484/43254660-2e4d37d2-90c8-11e8-9da2-212b7acaa966.png)

**Comment by Simran-B** [comment] 2018-07-26 10:31
Crashes may occur because of Sigma.js leaking memory over time, and eventually Chrome will run out of memory. At least that is what I remember seeing, and we even reported this problem upstream but no resolution so far AFAIK.

**Comment by dothebart** [comment] 2023-11-14 18:22
With ArangoDB 3.11 `sigma.js` has been replaced by `vis.js`. Hence closing this issue.

**Closed by dothebart** 2023-11-14 18:22 UTC
Labels: 1 Bug, 3 UI, 4 MacOSX, 3 Graph Visualization
