### ISSUE TITLE
Modification of _to/_from on edge doesn't throw error

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#1618] opened 2015-12-17 08:09 UTC
Hi, I was trying in my code to modify _to edge property (to switch edge from one vertex to another). It took me some time to find that it doesn't change it value. Then I found in documentation that these properties are immutable. So then modification query should throw error and not just silently do nothing.

Btw. it would be good if these properties could be modified, code logic would be easier with less db operations (one property update vs edge delete and create).

**Comment by dothebart** [comment] 2015-12-17 14:59
Confirmed, it doesn't even set a warning flag.

**Comment by CoDEmanX** [comment] 2015-12-17 15:06
Seems to be true for all system fields, you can't change a vertex document _key either:

    for doc in test
    update doc with {_key: random_token(32)} in test

**Comment by dothebart** [comment] 2016-01-13 17:39
duplicate of #1080

**Closed by dothebart** 2016-01-13 17:39 UTC
Labels: 2_Question

**Comment by dothebart** [comment] 2016-06-16 09:11
this will become possible with ArangoDB 3. 

Download & try via https://www.arangodb.com/download-preview/
