### ISSUE TITLE
The primary nodes interrupt abnormally

### ISSUE THREAD

**Issue by CalicoBox** [arangodb/arangodb#6042] opened 2018-08-01 03:21 UTC
## My Environment

* __ArangoDB Version__:        3.3.12
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Configuration__:               default config
* __Infrastructure__:               three physical machines
* __Operating System__:        Centos 7
* __Used Package__:              SUSE or RedHat .rpm

## Steps to reproduce

1. start arango agency(3 nodes), arango primary (3 nodes), arango coordinator (1 node) (cluster started successed).
2. run a Spark tast to read data from HBase and then write the data into arangodb.
3. interrupt abnormally after running serveral hours.

__Problem__:

Two nodes interrupt abnormally. I have checked the network, and there is no problem.

### deaded node 1 (tjhadoop06):
* arango.log:
```
2018-07-31T21:10:11Z [106803] WARNING {agency} Last confirmation from peer AGNT-f6fd462b-a81f-46d1-961d-918936e0cf79 was received more than minPing ago: 1.0817
2018-07-31T21:10:22Z [106803] INFO {supervision} Create failedLeader for s104072115 from PRMR-6ba812f2-14d3-469f-9616-82604f4782b4
2018-07-31T21:10:22Z [106803] INFO {supervision} Start failedLeader for s104072115 from PRMR-6ba812f2-14d3-469f-9616-82604f4782b4 to PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:10:22Z [106803] INFO {supervision} Create failedFollower for s104072114 from PRMR-6ba812f2-14d3-469f-9616-82604f4782b4
2018-07-31T21:10:22Z [106803] INFO {supervision} Start failedFollower for s104072114 from PRMR-6ba812f2-14d3-469f-9616-82604f4782b4 to PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:10:22Z [106803] INFO {supervision} Create failedFollower for s5010078 from PRMR-6ba812f2-14d3-469f-9616-82604f4782b4
2018-07-31T21:10:22Z [106803] INFO {supervision} Start failedFollower for s5010078 from PRMR-6ba812f2-14d3-469f-9616-82604f4782b4 to PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:10:22Z [106803] INFO {supervision} Create failedFollower for s5010072 from PRMR-6ba812f2-14d3-469f-9616-82604f4782b4
2018-07-31T21:10:22Z [106803] INFO {supervision} Start failedFollower for s5010072 from PRMR-6ba812f2-14d3-469f-9616-82604f4782b4 to PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:10:22Z [106803] INFO {supervision} Create failedFollower for s5010070 from PRMR-6ba812f2-14d3-469f-9616-82604f4782b4
2018-07-31T21:10:22Z [106803] INFO {supervision} Start failedFollower for s5010070 from PRMR-6ba812f2-14d3-469f-9616-82604f4782b4 to PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:10:22Z [106803] INFO {supervision} Create failedFollower for s104072126 from PRMR-6ba812f2-14d3-469f-9616-82604f4782b4
2018-07-31T21:10:22Z [106803] INFO {supervision} Start failedFollower for s104072126 from PRMR-6ba812f2-14d3-469f-9616-82604f4782b4 to PRMR-f0a9347d-c8dd-408d-9011-b8368bd2623a
2018-07-31T21:10:22Z [106803] INFO {supervision} Create failedLeader for s104072124 from PRMR-6ba812f2-14d3-469f-9616-82604f4782b4
2018-07-31T21:10:22Z [106803] INFO {supervision} Create failedFollower for s3010002 from PRMR-6ba812f2-14d3-469f-9616-82604f4782b4
2018-07-31T21:10:22Z [106803] INFO {supervision} Start failedFollower for s3010002 from PRMR-6ba812f2-14d3-469f-9616-82604f4782b4 to PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:10:23Z [106803] INFO {supervision} Finished failedLeader for s104072115 from PRMR-6ba812f2-14d3-469f-9616-82604f4782b4 to PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:10:24Z [106803] INFO {supervision} Todo: RemoveFollower(s)  to shard s104072115 in collection 104072113
2018-07-31T21:20:42Z [106803] INFO {supervision} Create failedFollower for s5010015 from PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:20:42Z [106803] INFO {supervision} Create failedLeader for s104072116 from PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:20:42Z [106803] INFO {supervision} Start failedLeader for s104072116 from PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2 to PRMR-f0a9347d-c8dd-408d-9011-b8368bd2623a
2018-07-31T21:20:42Z [106803] INFO {supervision} Create failedLeader for s104072115 from PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:20:42Z [106803] INFO {supervision} Create failedFollower for s104072114 from PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:20:42Z [106803] INFO {cluster} cannot create connection to server '' at endpoint 'tcp://tjhadoop07:8529'
2018-07-31T21:20:42Z [106803] INFO {supervision} Create failedFollower for s5010080 from PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:20:42Z [106803] INFO {supervision} Create failedFollower for s5010079 from PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:20:42Z [106803] INFO {supervision} Create failedFollower for s5010078 from PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:20:42Z [106803] INFO {supervision} Create failedFollower for s5010072 from PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:20:42Z [106803] INFO {supervision} Create failedFollower for s5010071 from PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:20:42Z [106803] INFO {supervision} Create failedFollower for s5010070 from PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:20:42Z [106803] INFO {supervision} Create failedFollower for s104072125 from PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:20:42Z [106803] INFO {supervision} Create failedLeader for s104072126 from PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:20:42Z [106803] INFO {supervision} Create failedFollower for s3010002 from PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2
2018-07-31T21:20:43Z [106803] INFO {cluster} cannot create connection to server '' at endpoint 'tcp://tjhadoop07:8529'
2018-07-31T21:20:43Z [106803] INFO {supervision} Finished failedLeader for s104072116 from PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2 to PRMR-f0a9347d-c8dd-408d-9011-b8368bd2623a
```
* primary.log:
```
2018-07-31T20:56:01Z [93081] ERROR {replication} initial sync failed for database 'relationgraph': got invalid response from master at tcp://tjhadoop08:8529: HTTP 404: Not Found
2018-07-31T20:56:06Z [93081] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 519146854
2018-07-31T21:06:07Z [93081] WARNING {httpclient} retrying failed HTTP request for endpoint 'tcp://tjhadoop08:8529' for replication applier in database 'relationgraph' - retries left: 1
2018-07-31T21:06:09Z [93081] ERROR {replication} initial sync failed for database 'relationgraph': got invalid response from master at tcp://tjhadoop08:8529: HTTP 404: Not Found
2018-07-31T21:06:14Z [93081] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 520146805
2018-07-31T21:10:23Z [93081] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 520419849
2018-07-31T21:10:23Z [93081] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 520419849
2018-07-31T21:10:23Z [93081] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 520419849
2018-07-31T21:10:24Z [93081] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 520419849
2018-07-31T21:10:24Z [93081] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 520419849
2018-07-31T21:10:24Z [93081] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 520419875
2018-07-31T21:10:24Z [93081] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 520419875
2018-07-31T21:10:25Z [93081] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 520419875
2018-07-31T21:10:25Z [93081] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 520419875
2018-07-31T21:10:25Z [93081] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 520419881
2018-07-31T21:10:25Z [93081] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 520419881
2018-07-31T21:10:26Z [93081] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 520419881
2018-07-31T21:14:01Z [93081] ERROR {replication} initial sync failed for database 'relationgraph': got invalid response from master at tcp://tjhadoop08:8529: HTTP 404: Not Found
2018-07-31T21:14:01Z [93081] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 520682093
```
### deaded node 2 (tjhadoop07):
* arangodb.log:

`nothing`

* primary.log:
```
2018-07-31T20:41:01Z [171464] WARNING {heartbeat} synchronizeOneShard: long call to syncCollection for shard s5010072 {"barrierId":"256596792","lastLogTick":"512303006","collections":[{"id":"10018","name":"s5010072"}]} start time:  Wed Aug 01 2018 04:32:10 GMT+0800 (CST) end time:  Wed Aug 01 2018 04:41:01 GMT+0800 (CST)
2018-07-31T20:41:01Z [171464] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 515924763
2018-07-31T20:41:02Z [171464] ERROR {replication} syncCollectionFinalize failed: required follow tick value '514544986' is not present (anymore?) on master at tcp://tjhadoop08:8529. Last tick available on master is '514544986'. It may be required to do a full resync and increase the number of historic logfiles on the master.
2018-07-31T20:41:02Z [171464] ERROR {heartbeat} synchronizeOneshard: exception in syncCollectionFinalize: ArangoError 1414: cannot sync data for shard 's5010072' from remote endpoint: required follow tick value '514544986' is not present (anymore?) on master at tcp://tjhadoop08:8529. Last tick available on master is '514544986'. It may be required to do a full resync and increase the number of historic logfiles on the master.
2018-07-31T20:41:02Z [171464] ERROR {heartbeat} synchronization of local shard 'relationgraph/s5010072' for central 'relationgraph/5010069' failed: "Did not work for shard s5010072.", started: Wed Aug 01 2018 04:32:10 GMT+0800 (CST), ended: Wed Aug 01 2018 04:41:02 GMT+0800 (CST)
2018-07-31T20:41:02Z [171464] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 515930355
2018-07-31T20:53:05Z [171464] ERROR {replication} initial sync failed for database 'relationgraph': got invalid response from master at tcp://tjhadoop08:8529: HTTP 404: Not Found
2018-07-31T20:53:05Z [171464] INFO {replication} connected to master at tcp://tjhadoop06:8529, id 36596665784163, version 3.3, last log tick 394143742
2018-07-31T21:05:17Z [171464] ERROR {replication} initial sync failed for database 'relationgraph': got invalid response from master at tcp://tjhadoop06:8529: HTTP 404: Not Found
2018-07-31T21:05:17Z [171464] INFO {replication} connected to master at tcp://tjhadoop08:8529, id 150886126952996, version 3.3, last log tick 520076128
```

### active node (tjhadoop08):
* arangodb.log:

`nothing`

* primary.log:
```
......
2018-07-31T21:43:10Z [45213] ERROR {replication} initial sync failed for database 'relationgraph': could not connect to master at tcp://tjhadoop06:8529 for URL /_api/replication/logger-state?serverId=150886126952996: Could not connect to 'http+tcp://tjhadoop06:8529' 'connect() failed with #111 - Connection refused'
2018-07-31T21:43:16Z [45213] WARNING {httpclient} retrying failed HTTP request for endpoint 'tcp://tjhadoop06:8529' for replication applier in database 'relationgraph' - no retries left
2018-07-31T21:43:16Z [45213] ERROR {replication} initial sync failed for database 'relationgraph': could not connect to master at tcp://tjhadoop06:8529 for URL /_api/replication/logger-state?serverId=150886126952996: Could not connect to 'http+tcp://tjhadoop06:8529' 'connect() failed with #111 - Connection refused'
2018-07-31T21:43:16Z [45213] WARNING {httpclient} retrying failed HTTP request for endpoint 'tcp://tjhadoop07:8529' for replication applier in database 'relationgraph' - no retries left
2018-07-31T21:43:16Z [45213] ERROR {replication} initial sync failed for database 'relationgraph': could not connect to master at tcp://tjhadoop07:8529 for URL /_api/replication/logger-state?serverId=150886126952996: Could not connect to 'http+tcp://tjhadoop07:8529' 'connect() failed with #111 - Connection refused'
2018-07-31T21:43:17Z [45213] WARNING {httpclient} retrying failed HTTP request for endpoint 'tcp://tjhadoop06:8529' for replication applier in database 'relationgraph' - no retries left
2018-07-31T21:43:17Z [45213] ERROR {replication} initial sync failed for database 'relationgraph': could not connect to master at tcp://tjhadoop06:8529 for URL /_api/replication/logger-state?serverId=150886126952996: Could not connect to 'http+tcp://tjhadoop06:8529' 'connect() failed with #111 - Connection refused'
2018-07-31T21:43:24Z [45213] WARNING {httpclient} retrying failed HTTP request for endpoint 'tcp://tjhadoop06:8529' for replication applier in database 'relationgraph' - no retries left
2018-07-31T21:43:24Z [45213] ERROR {replication} initial sync failed for database 'relationgraph': could not connect to master at tcp://tjhadoop06:8529 for URL /_api/replication/logger-state?serverId=150886126952996: Could not connect to 'http+tcp://tjhadoop06:8529' 'connect() failed with #111 - Connection refused'
......
```
__Expected result__:

be able to complete the Spark task successfully.

Please help me !! X(

**Comment by sleto-it** [comment] 2018-08-01 06:48
Hi @CalicoBox,

Thanks for trying our Cluster and for opening this ticket

Some preliminary questions:

- I assume you started the Cluster [manually](https://docs.arangodb.com/devel/Manual/Deployment/Cluster/ManualStart.html), without using the ArangoDB _Starter_ . Is this correct?
- Off-topic, but could you clarify why you started only 1 Coordinator (instead of, at minimum, two)?
- What _replication factor_ and _number of shards_ are you using for your collections?
- Have you perhaps tried to start async [replication](https://docs.arangodb.com/devel/Manual/Architecture/Replication/) using the [Replication Applier](
https://docs.arangodb.com/devel/Manual/Administration/MasterSlave/ReplicationApplier.html) in this Cluster? (something that should _not_ be done)

Thanks,

**Comment by CalicoBox** [comment] 2018-08-01 08:18
thanks for your attention @sleto-it,

I'll answer your questions one by one,

* Yes, I started my cluster manually. But it seems that all going well.
* In fact, I started 2 Coordinators, but when I started the Coordinators I didn't configure the properties which allow the two Coordinators to connect to each other, so I think I just use one
* replication factor : 2; shards : 3
* No

tx :)

**Comment by CalicoBox** [comment] 2018-08-02 14:51
The issus has happened again after running correctly for 9 hours, and I just get this from the primary.log:
```
2018-08-02T11:06:49Z [98106] INFO {cluster} cannot create connection to server 'PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2' at endpoint 'tcp://tjhadoop06:8529'
2018-08-02T11:06:49Z [98106] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from server:PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2:/_db/relationgraph_1/_api/document/s507093420?isRestore=true&isSynchronousReplication=PRMR-6ba812f2-14d3-469f-9616-82604f4782b4
2018-08-02T11:06:49Z [98106] WARNING {replication} insertLocal: dropping follower PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2 for shard s507093420
2018-08-02T11:06:52Z [98106] INFO {cluster} cannot create connection to server 'PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2' at endpoint 'tcp://tjhadoop06:8529'
2018-08-02T11:06:52Z [98106] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from server:PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2:/_db/relationgraph_1/_api/document/s507093393?isRestore=true&isSynchronousReplication=PRMR-6ba812f2-14d3-469f-9616-82604f4782b4
2018-08-02T11:06:52Z [98106] WARNING {replication} insertLocal: dropping follower PRMR-0a216faa-dd38-46fc-92bc-32a4968b78a2 for shard s507093393
```

so what does it mean?

**Comment by OmarAyo** [comment] 2018-08-06 08:36
Hi @CalicoBox 

Thanks for providing us with the above information, I would like to ask some more question, in order to best analyze your case:
-  the exact command used when deploying manually the _Cluster_
- the exact version of the _Spark connector_ and how did you configure it 
- How many data you have in HBase?
- all log files: you should have 3 log files for the agency, 2 for the coordinators and 3 from the dbservers (primary)

Thanks for your collaboration,

**Comment by OmarAyo** [comment] 2018-08-21 08:40
Hi @CalicoBox 

We haven't heard back from you recently. I am closing this ticket now.

Note: tickets can be reopened at any time by adding a new comment

Best,

**Comment by SankaD** [comment] 2018-10-07 14:46
Hi @CalicoBox , Did you find a way to fix this issue? I'm also getting random errors like that.

**Comment by dothebart** [comment] 2018-10-08 07:37
@SankaD as the original user didn't reply to any questions, maybe you could?

**Comment by CalicoBox** [comment] 2018-10-09 08:02
@SankaD  This problem has greatly influenced me using arangodb . Later, I found an immature solution to `split the entire spark task into several smaller tasks`. Although I writed data into arangodb successfully, I failed to locate the problem exactly.

Hope this can help u. Cheers.

**Comment by dothebart** [comment] 2018-10-09 09:15
It would be usefull if any of you could provide sample sourcecode  / a binary with verbose logging that reproduces the issue.

**Comment by maxkernbach** [comment] 2018-10-30 09:41
Hi @SankaD and @CalicoBox, 

could you please respond to @dothebart's latest comments? We would be glad to investigate this issue if you could provide a sample to reproduce this problem.

Thanks

**Comment by vinaypyati** [comment] 2018-11-09 10:02
Hi @CalicoBox and @SankaD,

Just a quick follow up. How things are going? Do you still face this issue? If so can you please share us some sample source code so that we can reproduce this problem on our side too? 

Thanks!

**Comment by SankaD** [comment] 2018-11-09 23:55
@vinaypyati I just moved to a different DB since I couldn't figure out the issue.

Thanks.

**Comment by dothebart** [comment] 2018-11-14 14:28
ok. so we may close it again.

**Closed by dothebart** 2018-11-14 14:28 UTC
Labels: 3 Cluster, Waiting User Reply
