### ISSUE TITLE
Memory issues with big import

### ISSUE THREAD

**Issue by CasperCLD** [arangodb/arangodb#1251] opened 2015-02-19 07:35 UTC
Hello. I was testing ArangoDB to see if it could hold up with large datasets. I loaded a data set of 2 million nodes and 5 million edges with the following script:

	var fillNetwork = function() {
	  var _ = require("underscore");
	  var fs = require("fs");
	  var Graph = require("org/arangodb/graph").Graph;
	  var gName = "graph_wiki-talk";
	  var g;
	  try {
	    g = new Graph(gName);
	  } catch (e) {
	    var nName = "wiki_talk_users";
	    db._create(nName);
	    var eName = "wiki_talk_edits";
	    db._createEdgeCollection(eName);
	    g = new Graph(gName, nName, eName);
	  }
	  var relations = fs.read("wikitalk.edges");
	  relations = relations.split("\r\n");
	  _.each(relations, function(pair) {
	    pair = pair.split(",");
	    if (pair.length === 2) {
	      try {g.addVertex(pair[0]);} catch (e) {}
	      try {g.addVertex(pair[1]);} catch (e) {}
	      try {g.addEdge(pair[0], pair[1]);} catch (e) {}
	    }
	  });
	};

	fillNetwork();
The dataset I used can be found [here](http://snap.stanford.edu/data/wiki-Talk.html). The test ran nicely for about 4 hours (!). I put the system to sleep two times and at the first time (after 3,5 hours) I noticed that ArangoDB took around 3,97GB of my system, while it was showing in the admin portal it only had 200mb as its resident. Memory leak?
I ran the test on a Macbook Air (2011) i7 4GB.

**Comment by jsteemann** [comment] 2015-02-20 14:01
I just tried to run the import myself.
The above script took about 1000 seconds to complete when run inside ArangoDB. It will take even longer when started from the ArangoShell (please refer to http://jsteemann.github.io/blog/2014/08/30/understanding-where-operations-are-executed/ for an explanation).

There are numerous ways to improve this:

* the above script will always try to create the vertices, even if they already exist. because the dataset contains lots of duplicate vertices, a lot of these operations will fail, but cause unnecessary traffic and CPU utilization. running a (partial) client-side deduplication will decrease the time to insert. In my case a simple partial deduplication reduced the net time to about 1/3 of the original time.
* even with de-duplication, the script will perform millions of individual insert operations. these will be slower than batch operations. using a specialized batch imported API will be much faster.

For example, I used the following Unix commands to deduplicate the input file, and convert it into a format that's understood by arangoimp, the batch importer shipped with ArangoDB:

```bash
# remove headlines, replace tab with comma
grep -v "^#" wiki-Talk.txt | sed -e "s/^M$//" -e "s/     /,/" > wiki_no_newlines  # note: the ^M is a CTRL-v plus TAB

# create file with unique vertices
(cut -d "," -f 1 --only-delimited wiki_no_newlines; cut -d "," -f 2 --only-delimited wiki_no_newlines) | sort --unique | sed -e 's/^\(.*\)$/{"_key":"\1"}/' > vertices

# create file with edges
sed -e 's/^\(.*\),\(.*\)$/{"_from":"wiki_talk_users\/\1","_to":"wiki_talk_users\/\2"}/' wiki_no_newlines > edges
```

Now these two files can be imported:
```bash
arangoimp  --file vertices --collection wiki_talk_users
arangoimp  --file edges --collection wiki_talk_edits
```

Altogether this took about 70 seconds, and is thus much more efficient than the original line-by-line processing.

I don't understand the memory issues:

> I noticed that ArangoDB took around 3,97GB of my system, while it was showing in the admin portal it only had 200mb as its resident. Memory leak?

Where exactly does the 3,97GB value come from? Is this a value reported by ArangoDB or the `top` command? And are the 3,97GB virtual or resident memory? 200MB resident seem a bit low for storing the example dataset. I think ArangoDB will need about 2-3 GB for the indexes alone. That was also what the web interface was showing when I had a look. Do you know how to reproduce the 200 MB in the web interface?

**Comment by CasperCLD** [comment] 2015-02-20 15:30
Hi Jan, thanks for your reply! I wasn't aware that you could import data that way. 

The value 3,97GB comes from the Activity Monitor in Mac OS X (on the tab memory).
![screen shot 2015-02-20 at 16 28 01](https://cloud.githubusercontent.com/assets/6095436/6289026/8c1807ce-b91d-11e4-8cdb-a7b0a4e297da.png)

I think this was pretty accurate because my system was unresponsive after the 4 hours import. 
When you have got an instance of ArangoDB running, and navigate to the web interface (localhost:8529 for me) there is a header called 'System Resources' where an indication of the 'Resident Size' is given. 
![untitled](https://cloud.githubusercontent.com/assets/6095436/6288986/5366a070-b91d-11e4-82e7-19e5d4e0720c.png)

ArangoDB v2.4.3

**Comment by jsteemann** [comment] 2015-02-20 16:15
I think the resident value shown in the web interface is what `task_info()` reports for the server process:
```c
mach_msg_type_number_t t_info_count = TASK_BASIC_INFO_COUNT;

rc = task_info(mach_task_self(), TASK_BASIC_INFO, (task_info_t)&t_info, &t_info_count);
if (rc == KERN_SUCCESS) {
  result._virtualSize = t_info.virtual_size;
  result._residentSize = t_info.resident_size;
}
``` 
I think this should be correct. I am not sure if this is also the amount that activity monitor shows, as I have no access to a Mac and no idea how its tools work.

Obviously ArangoDB uses not only resident memory, but also virtual memory. When an ArangoDB instance starts, the amount of virtual memory it uses should already be quite high. This is mostly due to some V8 threads reserving virtual memory. But it does not indicate physical memory usage. Physical memory usage should increase when creating or loading collections.
Index data will be kept in main memory, meaning that having collections with many documents requires much RAM, too. In the two collections from the above example, the indexes alone will take more than 1 GB in the optimal case, and presumably about 2 GB when created by inserting the documents sequentially. So it is not unrealistic the arangod process has used a few GB of RAM, and if 4 GB is your system maximum, then this might already be a problem and cause the computer to swap data in and out permanently.

**Comment by CasperCLD** [comment] 2015-02-23 07:41
Ah oke. Shouldn't be there any kind of warning of this happening ? Like if you exceed 80% of your memory, you should get a memory warning in the console or any (Java/Javascript) listeners. This would be nice, since it is hard to find the documentation of what you just told me.

**Comment by dothebart** [comment] 2016-07-14 12:02
There is no way to interact with V8 to acquire that sort of informations. 

With ArangoDB 3.0's switch to the internal Velocypack memory usage of the database has been decreased - give it a try - Macport packages are available now.

Since I don't see anything special which could be done here, I will close this now.

**Closed by dothebart** 2016-07-14 12:02 UTC
Labels: 3_Feature
