### ISSUE TITLE
[FEATURE] Auto create indexes by user queries 

### ISSUE THREAD

**Issue by MegaUITeam** [arangodb/arangodb#3222] opened 2017-09-08 19:30 UTC
Why do we force the user to manually control the indexes???
===
If this is purely the internal part of the database. Which is needed only for its internal mechanisms of acceleration.

**I suggested dynamic indexes that are themselves created, then deleted based on query statistics. if 1 query is more then 10% query, index created. if less then 10% query, index remove. Thus, the database dynamically adapts to the current load like a living thing**

I'm not suggesting removing manual control over the indexes.
===
I propose to add the option of automatic indexes. Then the database, from the incoming queries will generate optimal indexes for this queries, that speed up these queries.

Why do we force the programmer to engage in routine, instead creativity?

Just lead statistics
===
If user select by the `createTime` field in more than 10% of queries - create index.
If user select by the `createTime` field in less than 10% of queries - remove index.
If user select  `FILTER age > 20 AND friends > 10` - create SkipList index  (age, friends)

Of course, give the possibility to disable automatic indexes.
---
However, indexes are purely internal, technical part of databases. You do not force the user to get involved in query optimization ??? 

The maximum that you need to give a person, is control over what the computer can not itself predict. For example, the property `unique` or `geoIndex`

I just want to work with the database. And I want it to be fast. And how database will do it, I do not care.
 I want to have magic 👍 

But if I want to manually adjust something, of course I should be able to do it. But I think that 99% of programmers will not turn off automatic indexing.

1) is not happened in production
2) 1 query not have `10% of queries` and index not create
3) 1  query is debug, in debug mode auto indexes will be disabled
4) I suggested dynamic indexes that are themselves created, then deleted based on query statistics. if 1 query is more then 10% query, index created. if less then 10% query, index remove. **Thus, the database dynamically adapts to the current load** like a living thing.
5) you are drunk

**Comment by dothebart** [comment] 2017-09-11 08:19
closing as duplicate of #3209

**Closed** 2017-09-11 08:44 UTC
