### ISSUE TITLE
Timeout when trying to iterate over 10M documents without limit

### ISSUE THREAD

**Issue by shift-evgeny** [arangodb/arangodb#1740] opened 2016-02-15 11:14 UTC
Trying out ArangoDB 2.8.2 on Windows 7 x64. I imported a simple collection using arangoimp with just under 10M documents (14 columns per document).

I want to iterate over all those documents in .NET using the latest client from arangoclient.net:

```
            using (var db = new ArangoDatabase("http://localhost:8529", "Jabba"))
            {
                var entities = db.Collection("Entities");
                var cursor = entities.All<Entities>(limit: null, batchSize: 1000);

                foreach (var value in cursor.AsEnumerable())
                {
                    // Do some stuff
                }
            }
```

This sends the following request to ArangoDB:   

```
    PUT http://localhost:8529/_db/Jabba/_api/simple/all
```

After about a minute a TaskCancelledException is thrown. I think this indicates a timeout, i.e. the server has not returned any results during that time.

If I set "limit: 1000000" then the above code works - I can iterate over the results. But I should be able to iterate over all of them.

**Comment by dothebart** [comment] 2016-02-15 11:49
@yojimbo87 can you confirm that the http client inside of the client driver aborts the connection? I don't think that this is a bug on the serverside.

**Comment by shift-evgeny** [comment] 2016-02-15 11:59
I wasn't using yojimbo87's client, I was using the one from arangoclient.net (ra0o0f's).

**Comment by dothebart** [comment] 2016-02-15 12:05
@ra0o0f can you have a look at this?

**Comment by ra0o0f** [comment] 2016-02-15 14:46
@shift-evgeny i could reproduce it, when the cursor `limit` size is set and its below 1mil, it could iterate the result set, you can see how many requests sent to the server by printing `cursor.Statistics.RequestCount`. 

but when i set the limit to 5mil the client request for the first batch and waits for the result. at this time Arangodb server memory increases to 2.5gb(almost all the memory here) (the index size of the collection is 400mb) and it timed out before sending the first batch, @dothebart correct me if i'm wrong but i think Arangodb produce all results set(in this case 5mil)  at the server and then foreward the batches to the client. @dothebart is it normal for the server to increases memory this much?

@shift-evgeny  i think the problem would go away if the timeout is disabled by setting 
`ArangoDatabase.ClientSetting.HttpRequestTimeout = TimeSpan.FromMilliseconds(Timeout.Infinite);`
(this setting is at source code yet, i will publish new nuget packages asap). but sending the first batch would take time(@shift-evgeny test it by new nuget packages).

**Comment by ra0o0f** [comment] 2016-02-15 15:11
@shift-evgeny nuget package is updated, can you try by disabling the timeout

**Comment by shift-evgeny** [comment] 2016-02-15 15:31
@ra0o0f I'm not using the nuget package, I got the code from GitHub so that I could work around another issue (I'll raise that separately). Is this change in Git somewhere?

**Comment by dothebart** [comment] 2016-02-15 17:19
Yes, fetching the whole collection will build up a JSON copy of the collection content in memory on the server side. 

If you want to create a backup of your collection, you should use [arangodump](https://docs.arangodb.com/HttpBulkImports/Arangodump.html).

If you need to iterate over all documents in the collection programmatically, it's cheaper to use the [export api](https://docs.arangodb.com/HttpExport/index.html) and only use parts of the documents (i.e. `_key`) for further processing.

Otherwise you should rather use AQL to [FILTER](https://docs.arangodb.com/Aql/Basics.html) in combination with [indices](https://docs.arangodb.com/IndexHandling/index.html) to get a reduced result set that can easily be transfered to your client. You can also reduce the result size by only returning relevant parts of your documents. 

 If you intend to  manipulate the data you should do this inside of the server (i.e. [add or update](https://docs.arangodb.com/Aql/DataModification.html) one attribute of all documents)

**Comment by shift-evgeny** [comment] 2016-02-15 18:35
It's not for backup. I actually do want to load the entire collection into memory on the client to do some processing on it. Currently I'm not storing the objects on the client side, but they _should_ comfortably fit within client memory.

> Yes, fetching the whole collection will build up a JSON copy of the collection content in memory on the server side.

What about when doing AQL queries - does the server also store the entire result set in memory?

In this case I'm testing retrieving the whole collection, but in other cases I might want to load 90% of it or 50% or 30%, etc. using some filter. The result set could still be a few GB in size. This is something an RDBMS would handle by streaming the results to the client, so neither the server nor the client need to store all results in memory at once. Is there any API in ArangoDB that does this? If not, any plans to implement it?

**Comment by shift-evgeny** [comment] 2016-02-16 10:15
I should add that even with "limit: 1000000" specified the above code doesn't work reliably. Sometimes the first row is returned in 10 seconds or so, but other times no row is returned even after 5 minutes. The server uses very little CPU (~1%) but RAM usage gradually goes to 3 GB and keeps increasing slowly...

**Comment by dothebart** [comment] 2016-02-18 09:51
Internaly that simple query builds up aql nowadays - so the answer is the same, the result hast to be built up in memory.

Yes, `limit` and `skip` is the way to go to get it more compact.

Another more clever thing to do is implement this special task in FOXX, so you can save yourselves the roundtrips to the client.

**Comment by shift-evgeny** [comment] 2016-02-18 10:27
It's not really a "special task", just a very ordinary query, the kind that we'd like to do all the time on an ad-hoc basis. Given that the querying user has to be very careful to supply `limit`/`skip` every time and even with `limit` the performance isn't reliable, it seems that ArangoDB is not well-suited to our use case. When you add #1741 into it as well, it becomes far too easy for a user to inadvertently DoS the DB server.

**Comment by dothebart** [comment] 2016-03-08 14:03
I've been around when an ill formed query drowned a big database of another vendor. The database can't protect you from coding errors for sanitizing user input. #1741 will be fixed with 3.0, so I'm closing this now.

**Comment by shift-evgeny** [comment] 2016-03-08 17:14
This was not a coding error. I wrote exactly what I wanted: iterate over all nodes of type "Entity". Being unable to support a simple use case like this has to be considered a serious limitation for any DBMS. As such, I'd hope that you'd want to fix it - but it's your product.

**Comment by weinberger** [comment] 2016-03-08 17:44
I'm Claudius, CEO of ArangoDB.

I reopen the ticket because you are totally right. It's our product, and we want fix this. I will come back to that soon and give you a feedback.

**Comment by razvanphp** [comment] 2016-04-05 09:14
What if I write a rather simple modification query like this, over a collection of 1.6M entries, why is this taking forever?

Since it's not returning anything, maybe it's not related to this issue, but it's clearly connected, since it works with some reasonable limit specified.

```
FOR c IN customers
    UPDATE c WITH { email: 'protected-email@domain.com' } IN customers
```

**Comment by matthiasg** [comment] 2016-07-25 11:40
basically it would be helpful if the server could just stream the results back page by page as soon as the server has them. usually databases returning JSON would return a simple newline delimited set of responses but they could also do [ {},{},{} ] provided the server knows when the last page is returned to skip the final , for conformance.

internally it could still do paging if necessary architecture-wise but keep the return stream open and push more events until done.

Clients could then either wait to receive all as usual or pass the results on as a stream as well.

In our use case this would indeed be quite helpful. Perform a potentially long running query right away, process the incoming results and augment them etc and pass them on to the clients as they come in. 

This would reduce latency quite a bit and solve the full scan issue as described above.

**Comment by dothebart** [comment] 2020-07-20 11:59
this can now be achieved using streaming cursors: 
https://www.arangodb.com/docs/stable/release-notes-new-features34.html#streaming-aql-cursors

**Closed by dothebart** 2020-07-20 11:59 UTC
Labels: 1 Feature
