### ISSUE TITLE
async replication: very slow syncCollection execution

### ISSUE THREAD

**Issue by avive99** [arangodb/arangodb#4305] opened 2018-01-15 09:37 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [V ] 3.2
- [ ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [V ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [V ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [V ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 
Greetings

I have a single Replication master running ArangoDB 3.2.9.
At another single ArangoDB 3.2.9 host i've set replication.
Generally it works, but i have two issues with replication:
1. After some ArangoDB failure restarts (not enough memory) at the Master - the situation is that collection @Master has X records, and the same collection @Slave has X-n (less) records.
Replication still works (applier=true), and new records are replicated once in a time.
There is no lag in replication.
Question 1: how does the delta in collection's size occurred and how can i avoid it ?
Question 2 : what the quickest way to re-sync that collection ?

2. I've stopped the Applier, and run @Slave the syncCollection method - to cause a manual sync of given collection.
  It works however very slow ! The collection at Master has 300M documents, and still growing.
The syncCollection method , after running almost 22 hours, managed to bring only 8M documents.
So , it will take weeks to finish the syncCollection (if at all...).
Question 3: Why does the syncCollection working so slow, and is there any way to run it much faster ?

Best regards,
Avi Vainshtein

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by avive99** [comment] 2018-01-15 13:12
some more information:
i noticed in the output of the sync command :
- there is cycle of 5-6 minutes of the sync log messages in the terminal window
- every 10 seconds a similar message appears:
"still synchronizing... last received status: 2018-01-15T13:01:26Z: fetching master collection dump for collection 'files', type: document, id 313538779, batch 25, markers processed: 718474, bytes received: 226758468"
As i understand, the "markers processed" number is actually the count of documents which are totally replicated from given master's collection.
- Only once in 5-6 minutes there is a "jump" in the "markers processed" values.
The "jump" values is about 32K-33K.
So, the current speed of the "sync" is 32K-33K documents every 5 minutes...
I.e. about 10M in 24 hours.
So to sync 300M documents (currently in collection) - i need a month...
Something is wrong here...

**Comment by avive99** [comment] 2018-01-15 13:21
I've stopped/cancelled the syncCollection operation (after 24 hours in managed to replicate 9M docs from 300M...).
Then I've re-created the DB at Slave, and run an initial Replication setup (commands attached below).
The speed of replication is still VERY SLOW .

> db._dropDatabase("pm1db");
true

> db._createDatabase("pm1db");
true

> db._useDatabase("pm1db");
true

> require("@arangodb/replication").applier.state();
{
  "state" : {
    "running" : false,
    "lastAppliedContinuousTick" : "1908562739",
    "lastProcessedContinuousTick" : "1908562739",
    "lastAvailableContinuousTick" : null,
    "safeResumeTick" : "1908562739",
    "progress" : {
      "time" : "2018-01-15T11:16:16Z",
      "message" : "applier initially created",
      "failedConnects" : 0
    },
    "totalRequests" : 0,
    "totalFailedConnects" : 0,
    "totalEvents" : 0,
    "totalOperationsExcluded" : 0,
    "lastError" : {
      "errorNum" : 0
    },
    "time" : "2018-01-15T11:16:26Z"
  },
  "server" : {
    "version" : "3.2.9",
    "serverId" : "159757613179818"
  }
}

> db._useDatabase("pm1db");
true

> require("@arangodb/replication").setupReplication({
...>   endpoint: "tcp://masterhost:8529",
...>   username: "root",
...>   password: "xxxxxxxxx",
...>   verbose: false,
...>   includeSystem: false,
...>   incremental: true,
...>   autoResync: true
...> });
still synchronizing... last received status: 2018-01-15T11:16:41Z: fetching master collection dump for collection 'files', type: document, id 313538779, batch 1, markers processed: 0, bytes received: 0
still synchronizing... last received status: 2018-01-15T11:16:41Z: fetching master collection dump for collection 'files', type: document, id 313538779, batch 1, markers processed: 0, bytes received: 0
....

Regards and looking forward your kind assistance,
Avi

**Comment by dothebart** [comment] 2018-01-16 13:44
Hi, 
when you do a synchroneous replication on a collection a write operation of one set will only finish when the master has sent all your data all his slaves, and each of them has confirmed that the data has been synced to disk. This is what makes it "sync" above the also available "async" replications.
As you can see, more communication and more waiting is involved which limits the throughput as you have experienced.
The other way would be to first set up the master, import all its data, and then create the slave and let it catch up. As you can see, this also involves reading all your documents from the master to the slave on the initial sync.

**Comment by jsteemann** [comment] 2018-01-17 17:51
@avive99 : is the connection between slave and master somehow limited by firewalls, internal network bandwidth or traffic shaping?
I.e. how much data can normally be transferred on other connections between the slave and the master host? Is that amount in the same ballpark, or can you normally transfer a much larger amount of data between the two servers?
Is the slave server maxed out in terms of CPU or I/Os it can achieve? A quick view into `top` or `iotop` should reveal this. If the slave is mostly idle, can you check if the master server is somewhat maxed out?

**Comment by avive99** [comment] 2018-01-23 12:18
@dothebart : Thanks for the explanations.
As for now, at the Master host - our main db has main collection which has 116GB disk size (RocksDB engine). 
What is the fastest way to re-set replication of that db at Slave host , while Master is working 7*24 ? 

I've read at some place about arangodump@Master/arangorestore@Slave and start replication. Could it be an acceptable solution in our case ?
Could it be that arangodump will manage to dump that db at Master , and still don't cause significant impact on running DB ? 
Once the arangorestore is done at Slave - is it a way to start replication by just providing the "last tick" value got @Master during arangodump, and avoiding any sync with the Master ?

**Comment by avive99** [comment] 2018-01-23 12:30
@jsteemann : Both Master and Slave hosts are inside the same network segment, and no firewalls between them. 
As for the data transfer rate between hosts : i've copied by scp a 10GB file from Master to Slave and it took 2 minutes. It took much-much less time than replication by ArangoDB...
As per CPU/IO utilization at Slave during replication sync : the Slave seems to do about nothing...
Master does show some usage, but that's a production host which supports applications' , and still it is definitely far from being overloaded.

**Comment by avive99** [comment] 2018-02-21 11:24
Started similar test case after Arangofb has been upgraded to 3.3.3.
The case : single maser host (rocksdb), a db with two collections, each one has more than 200M documents. Total disk size of the db is about 50GB.
At a slave host (also single host 3.3.3), created an empty db and started "All-in-one setup" as described in the documentation :
https://docs.arangodb.com/3.3/Manual/Administration/Replication/Asynchronous/DatabaseSetup.html

Started the replication:
require("@arangodb/replication").setupReplication({
  endpoint: "tcp://vm-tskdbn1:8529",
  username: "root",
  password: "xxxxxx",
  verbose: true,
  includeSystem: false,
  incremental: true,
  autoResync: true
});

After running during 25 minutes - about 80K documents have been copied to Slave (from more than 200M to be done...).
The replication seems to be progressing once in 3-4 minutes.
Again, as in 3,29, it seems the Replication in 3.3.3 is also very slow.

What bring me to the initial questions:
I have a Production singe host Master db with set of collections, each one with more than 300M documents, total disk size about 300GB.
What is the proper and still considerable fast scenario to build a Replication Slave , able to make an initial sync and to continue the further replication ?

**Comment by avive99** [comment] 2018-02-21 13:54
and after some time the whole replication thing failed (after brought/synced 76882 documents) with messages :

still synchronizing... last received status: 2018-02-21T11:10:05Z: fetching master collection dump for collection 'files', type: document, id files, batch 5, markers processed: 47694, bytes received: 17039786
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/replication.js' at 209,7: ArangoError 1402: caught exception during slave creation: got invalid response from master at tcp://vm-tskdbn1:8529 for URL /_api/replication/dump?collection=files&batchId=285368745&flush=false&from=6&to=605954748&serverId=159757613179818&chunkSize=10485760&includeSystem=false: HTTP 404: Not Found - {"error":true,"errorMessage":"replication dump - unable to find context (it could be expired)","code":404,"errorNum":400}
!      throw err;
!      ^
stacktrace: ArangoError: caught exception during slave creation: got invalid response from master at tcp://vm-tskdbn1:8529 for URL /_api/replication/dump?collection=files&batchId=285368745&flush=false&from=6&to=605954748&serverId=159757613179818&chunkSize=10485760&includeSystem=false: HTTP 404: Not Found - {"error":true,"errorMessage":"replication dump - unable to find context (it could be expired)","code":404,"errorNum":400}
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:96:21)
    at waitForResult (/usr/share/arangodb3/js/client/modules/@arangodb/replication.js:207:16)
    at setup (/usr/share/arangodb3/js/client/modules/@arangodb/replication.js:310:10)
    at Object.setupReplication (/usr/share/arangodb3/js/client/modules/@arangodb/replication.js:313:51)
    at <shell command>:1:34

**Comment by vinaypyati** [comment] 2018-09-28 10:12
Hi @avive99,

ArangoDB 3.4 RC 1 has been released, which includes performance improvements. You can find the ArangoDB 3.4 RC 1 [here ](https://www.arangodb.com/download-technical-preview/). Let us know your feedback!

Thanks!

**Comment by maxkernbach** [comment] 2018-10-16 11:09
Hi @avive99,

did you already try 3.4 RC1?
FYI: The latest available 3.4 Release Candidate is RC2 and can be found in the [download section](https://www.arangodb.com/download-technical-preview/).

Your feedback is highly appreciated!

**Comment by maxkernbach** [comment] 2018-10-30 10:07
I am closing this issue for now since we have not heard back from you in a while.

The replication performance in 3.4 using RocksDB is significantly improved (documented at [What's new in 3.4](https://docs.arangodb.com/devel/Manual/ReleaseNotes/NewFeatures34.html#reduced-replication-catch-up-time) and in the [CHANGELOG](https://github.com/arangodb/arangodb/blob/3.4/CHANGELOG#L674).

Please feel free to share some feedback, we will reopen in case the performance issue persists.

**Closed by maxkernbach** 2018-10-30 10:07 UTC
Labels: 1 Feature, 3 Cluster, Waiting User Reply, performance
