### ISSUE TITLE
Support autoincrement feature on clusters

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#3589] opened 2017-11-06 13:02 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Cluster

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

### this is a feature request
Clusters don't seem to support _key auto-increment option at the moment. Notably `arangorestore`ing a collection with auto-increment fails.

While auto-increment is not absolutely necessary in our case, it would be very useful and appreciated (see #3539).

I understand from the discussion at #212 that it's not easy to implement on a cluster, but it's been many years so maybe some progress was made in that direction ?

Thanks,
Mathias

**Comment by dothebart** [comment] 2017-11-06 13:51
Hi, 
yes, the two referenced issues discuss related topics. 
However, this is a direct duplicate of #2535 - thus I will close this issue now.

**Closed by dothebart** 2017-11-06 13:51 UTC
