### ISSUE TITLE
[Arangosh] out of memory

### ISSUE THREAD

**Issue by amurchick** [arangodb/arangodb#3806] opened 2017-11-26 08:34 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2.8

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] Debian .deb

I'm issuing AQL via:
- [x] arangosh

The issue can be reproduced using this dataset:

800000 documents like this
```
{
  "created": "2017-10-02T20:06:29.060Z",
  "armed": false,
  "message": {
    "from": "outside-light",
    "cmd": "sensors",
    "T": 44.27,
    "H": 38.56543,
    "P": 1007.257,
    "L": 4
  },
  "temp": 44.27,
  "humidity": 38.56543,
  "pressure": 1007.257,
  "light": 4
}
```

These are the steps to reproduce:
```
127.0.0.1:8529> cursor = db._collection('afmSensorsData').all(); console.log(cursor.hasNext());
```
The following problem occurs: 

```
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 98,7: ArangoError 3: out of memory (while executing) (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/RestHandler/RestCursorHandler.cpp:130)
!      throw error;
!      ^
stacktrace: ArangoError: out of memory (while executing) (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/RestHandler/RestCursorHandler.cpp:130)
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:96:21)
    at SimpleQueryAll.execute (/usr/share/arangodb3/js/client/modules/@arangodb/simple-query.js:77:14)
    at SimpleQueryAll.SimpleQuery.hasNext (/usr/share/arangodb3/js/common/modules/@arangodb/simple-query-common.js:395:8)
    at <shell command>:1:64
```

**Comment by amurchick** [comment] 2017-12-23 03:00
In ```ArangoDB 3.3.0 enterprise [linux] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.1.0f  25 May 2017``` this issue fixed:

```
127.0.0.1:8529@geohelp> cursor = db._collection('afmSensorsData').all(); console.log(cursor.hasNext());
2017-12-23T02:56:15Z [15693] INFO true

127.0.0.1:8529@geohelp> db._collection('afmSensorsData').count()
1025672
```

**Comment by dothebart** [comment] 2018-01-03 14:47
Hi, 
the problem here is, that you load the whole collection into ram and transfer it to the client. 
Depending on the size of the collection this may take (to) long.

**Comment by dothebart** [comment] 2018-04-26 15:01
ok, closing this as a duplicate of #1740. 
You need to use AQL with LIMIT etc. and do several requests to get this working currently.

**Closed by dothebart** 2018-04-26 15:01 UTC
Labels: 1 Bug, 3 Benchmark, 3 Core
