### ISSUE TITLE
Suggestion: TTL index

### ISSUE THREAD

**Issue by tkallioras** [arangodb/arangodb#6005] opened 2018-07-26 13:28 UTC
It would be nice to have a TTL collection index on a document field. In this way it could be possible to store for a limited amount of time some documents, for session keeping purposes, or for tracking other user interactions which are time based (let's say a valid paid user subscription).

It is something that has also been implemented in other databases and it's quite useful.

**Comment by dothebart** [comment] 2018-07-26 13:35
Hi, I'd like to close this as a duplicate of https://github.com/arangodb/arangodb/issues/210

**Closed by dothebart** 2018-07-26 13:35 UTC
Labels: 1 Duplicate, 1 Feature
