### ISSUE TITLE
Homebrew package is missing the starter

### ISSUE THREAD

**Issue by fceller** [arangodb/arangodb#3633] opened 2017-11-09 08:56 UTC
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [x] MacOS, version:

### this is an installation-related issue:
`brew install arangodb` should also install the ArangoDB starter

**Comment by dothebart** [comment] 2017-11-09 09:28
Closing as duplicate of #3604

**Closed by dothebart** 2017-11-09 09:28 UTC
