### ISSUE TITLE
Node.js modules that use process.version fail to instantiate in a Foxx app and throw an unhandled exception

### ISSUE THREAD

**Issue by gvelesandro** [arangodb/arangodb#1808] opened 2016-04-26 06:03 UTC
Unable to use node.js modules that reference the `process` global variable

Reproduce this exception with the following steps:
1) Create a new Foxx app
2) In the Foxx app folder, `npm install readable-stream`
3) In the Foxx app controller, `require('readable-stream')`
4) The following exception is thrown in the controller:

> TypeError: Cannot read property 'slice' of undefined
>     at Object.<anonymous> (/Users/sandro/arangoDB/data/sandrodb-test-1/apps/_db/Test-Services/my/service-1/APP/node_modules/readable-stream/lib/_stream_writable.js:14:80)
>     at Module._compile (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/common/bootstrap/modules.js:585:6)
>     at Object.Module._extensions..js (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/common/bootstrap/modules.js:605:10)
>     at Module.load (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/common/bootstrap/modules.js:524:34)
>     at Function.Module._load (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/common/bootstrap/modules.js:468:14)
>     at Module.require (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/common/bootstrap/modules.js:557:17)
>     at require (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/common/bootstrap/modules.js:91:19)
>     at Object.<anonymous> (/Users/sandro/arangoDB/data/sandrodb-test-1/apps/_db/Test-Services/my/service-1/APP/node_modules/readable-stream/readable.js:9:20)
>     at Module._compile (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/common/bootstrap/modules.js:585:6)
>     at Object.Module._extensions..js (/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/common/bootstrap/modules.js:605:10)

In ArangoDB's Foxx application context, `process` refers to the ArangoDB process, rather than the Node.js process.  If a Node.JS module references the `process` global variable, an exception is thrown.

**Comment by pekeler** [comment] 2016-04-26 14:21
You could just set it yourself. `process.version = '4.0';` and see which number makes it work. If arango populates this with its own version, it may not be what your module expects.

**Comment by gvelesandro** [comment] 2016-04-26 21:52
Setting `process.version` immediately before `require('readable-stream')` is called solve the problem. Should this global variable be set somewhere else in the Foxx app lifecycle?

**Comment by pekeler** [comment] 2016-04-26 22:04
I don't think you'll be able to make https://github.com/nodejs/readable-stream work on ArangoDB. readable-stream is an asynchronous library and ArangoDB doesn't have the event loop. Fundamentally incompatible.

I read in another issue that you're trying to get data from another DBMS into ArangoDB. Could you perhaps send the data using https://github.com/arangodb/arangojs ?

**Comment by Simran-B** [comment] 2016-04-27 00:19
Agreed, you can use Node and its entire ecosystem to fetch data, then use e.g. arangojs to get it into ArangoDB. All drivers are essentially thin wrappers for the HTTP API, which is currently the only way in which Arango communicates with the outside world (this will change in 3.0 with VelocyStream). That said, there's no performance penalty to be expected caused by a particular driver, and the HTTP overhead in general is rather low (keep-alive should be used though). Long lasting operations don't belong into a DB / Foxx anyway.

**Comment by dothebart** [comment] 2016-04-27 09:48
ArangoDBs nodejs compatibility has limits; dependencies on binary node modules won't work. Since ArangoDB/Foxx is synchroneus by nature, promises or async handling won't work either. 

Therefore its not a good idea to do excessive i/o with wait times in Foxx services either, since you block worker threads with it. 

Foxx is intended to deliver a tool to develop own REST services where you i.e. would create a persistent API to manage users; If several AQL queries are neccessary to get creating of users done (i.e. first do a duplicate check, then insert in collection users, create a basic profile in a `profiles` collection and return the result to your application. 

In this approach the business logic lives in your application, but it won't know about the details more than 'create user'. 

In some cases a foxx service combined with a frontend browser application (or mobile application) may be a good fit for a usecase, but in many more usecases you want to implement certain business logic inside of an application server as nodejs, rails or tomcat. Your usecase sounds like you should use a nodjs alongside with arangodb.

**Comment by pluma** [comment] 2016-04-28 10:16
What @pekeler said, basically. The streams API expects the environment to be async, ArangoDB is synchronous. Even if we did somehow fake a node version number, it would still be broken.

As for the version number: it's doing a check on the version number to determine which Node version it is running on (because it assumes if `process.browser` is not set, it must be running on Node). It's presumably doing this to detect some known bug which can't be detected via feature detection (otherwise it could just detect the feature itself). Providing a meaningful version number for checks like these would require determining what Node version most closely corresponds to what ArangoDB version -- which isn't really feasible.

As you're using `readable-streams` directly, I suggest simply not using it. It most likely doesn't work with ArangoDB (because setImmediate is a no-op in ArangoDB) and there is no benefit to using the streams API in ArangoDB itself as neither the request cycle nor the filesystem API support streams.

**Comment by dothebart** [comment] 2016-06-16 15:32
Ok, I think we can close this case now. 

ArangoDB 3.0.0 RC2 is available featuring V8 5.0: https://www.arangodb.com/download-preview/

**Closed by dothebart** 2016-06-16 15:32 UTC
Labels: 2_Question
