### ISSUE TITLE
Collections lost during insertion?!

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9133] opened 2019-05-29 07:32 UTC
Well, me again. I've met amounts of bugs in only a few hours.

I created one collection with 1000 shards and one collection with 625 shards, then kept inserting normal documents into them. Then suddenly found the collections had both lost in the web UI, also lost in arangosh.  After restarting of service, still not found the lost collections.

So I'm confused whether arangodb is production ready ?......

**Comment by daoxian** [comment] 2019-05-29 07:32
version is still 3.4.5, a 5-node cluster.

**Comment by OmarAyo** [comment] 2019-05-29 14:23
Linked to #9131

**Comment by ObiWahn** [comment] 2019-05-31 13:00
duplicate of #9132

**Closed** 2019-05-31 13:12 UTC
Labels: 1 Duplicate, 3 AQL, 3 Cluster
