### ISSUE TITLE
VPack error: expecting object

### ISSUE THREAD

**Issue by mtruyens** [arangodb/arangodb#2192] opened 2016-11-29 20:37 UTC
I consistently receive the following error message:

Arango error: VPack error: Expecting Object (exception location: /tmp/arangodb-20161128-83534-187fube/ArangoDB-3.1.2/arangod/GeneralServer/RestHandler.cpp:183). Please report this error to arangodb.com

when trying to invoke the following URL:

... _api/simple/all-keys?collection=testcollection&type=id

**Comment by jsteemann** [comment] 2016-11-30 08:15
Reproduced in 3.1. Looking into it.

**Comment by jsteemann** [comment] 2016-11-30 08:28
As far as I can see the error is caused by the "collection" attribute missing from the request.
It is expected in the request body, but there is none.
So the following request will work:
```
curl -X PUT "http://127.0.0.1:8529/_api/simple/all-keys?collection=testcollection&type=id" --data '{"collection":"testCollection"}' --dump - --basic --user "root:"
```
and this one won't work:
```
curl -X PUT "http://127.0.0.1:8529/_api/simple/all-keys?collection=testcollection&type=id" --dump - --basic --user "root:"
```

**Comment by kvahed** [comment] 2016-11-30 08:29
curl -XPUT localhost:8529/_api/simple/all-keys -d'{"collection":"testcollection","type":"id"}'

**Comment by jsteemann** [comment] 2016-11-30 08:35
There should never be an internal error if a required parameter is missing in an API call. The error message should be fixed.

**Comment by weinberger** [comment] 2016-11-30 08:36
As @jsteemann said it shouldn't a internal error.

**Comment by dothebart** [comment] 2016-12-02 18:03
3.1.3 is Released, Closing.

**Closed by dothebart** 2016-12-02 18:03 UTC
Labels: 1_Bug, Fixed

**Comment by kavin26** [comment] 2018-04-18 10:58
Hi, i'm using arangodb version 3.1.28 for my testing purposes... i got an error when i run my script which is to be deployed into production soon...
Complete traceback is as follows,
`Traceback (most recent call last):
  File "zeenews_preprocessing_v2.py", line 634, in raw_data_processing
    docid = doc_query_result['_key']
KeyError: '_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "zeenews_preprocessing_v2.py", line 656, in raw_data_processing
    bindVars={'title': metadata['title'], 'type': doctype, 'updateobj': metadata})
  File "/usr/local/lib/python3.5/dist-packages/pyArango/database.py", line 178, in AQLQuery
    json_encoder = json_encoder, **moreArgs)
  File "/usr/local/lib/python3.5/dist-packages/pyArango/query.py", line 145, in __init__
    Query.__init__(self, request, database, rawResults)
  File "/usr/local/lib/python3.5/dist-packages/pyArango/query.py", line 38, in __init__
    raise QueryError(self.response["errorMessage"], self.response)
pyArango.theExceptions.QueryError: VPack error: Expecting digit (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/GeneralServer/RestHandler.cpp:191). Please report this error to arangodb.com. Errors: {'code': 500, 'errorNum': 4, 'errorMessage': 'VPack error: Expecting digit (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/GeneralServer/RestHandler.cpp:191). Please report this error to arangodb.com', 'error': True}
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "zeenews_preprocessing_v2.py", line 2752, in <module>
    pool.starmap(raw_data_processing, zip(todoprocess_itemnodes, epochtime))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 268, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
pyArango.theExceptions.QueryError: VPack error: Expecting digit (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/GeneralServer/RestHandler.cpp:191). Please report this error to arangodb.com. Errors: {'code': 500, 'errorNum': 4, 'errorMessage': 'VPack error: Expecting digit (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/GeneralServer/RestHandler.cpp:191). Please report this error to arangodb.com', 'error': True}`

What might be the cause for this?
